// admin-ops-moderation — an owner/admin operations console (users, reports,
// moderation, operations, audit log), ported from Kindred-Connection's real
// admin system (backend/routers/admin.py + backend/core.py require_admin +
// frontend/src/pages/admin/AdminUsers.js / AdminReports.js / AdminAudit.js).
//
// We keep its actual model and logic, generalized off Mongo onto the app owner's
// own Postgres:
//   - Users list/search with the same status filters (all | onboarded |
//     suspended | admins | no-show 14d+), ported from GET /admin/users, run over
//     the app's real users table.
//   - Moderator actions ported from PATCH /admin/users/{id} + DELETE (soft
//     delete): suspend/unsuspend, grant/revoke admin, soft-delete that releases
//     the email and blanks the name — with the same self-guardrails ("cannot
//     suspend yourself", "cannot revoke your own admin", "cannot delete
//     yourself").
//   - Reports / Trust & Safety queue ported from GET /admin/reports +
//     POST /admin/reports/{id}/resolve: reason/note, status open|resolved|
//     dismissed, actions dismiss|resolve|suspend_target (suspend_target also
//     suspends the reported user), resolver + resolved_at recorded.
//   - Operations: manual, audited ops runs ported from POST /admin/ops/*.
//   - Audit log ported from _audit() + GET /admin/audit: actor id/email,
//     action, JSON payload, created_at, newest first.
//
// Runs on the app owner's own database with a graceful sample-data fallback,
// feature-flagged (FEATURE_ADMIN_OPS). Customers may read the console; only
// admins may act.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/admin-ops.ts (model + queries, ported from admin.py) --------

function adminOpsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/admin-ops.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A user row as the console shows it, ported from GET /admin/users' projection",
    "// (email, name, role, suspended, created_at). We reference the app's real",
    "// users(id) instead of a Mongo user_id.",
    "export type AdminUser = {",
    "  id: string;",
    "  email: string;",
    "  name: string;",
    "  role: string;",
    "  suspended: boolean;",
    "  deleted: boolean;",
    "  createdAt: string | null;",
    "  lastSeenAt: string | null;",
    "};",
    "",
    "// Trust & Safety report, ported from the reports doc",
    "// (reporter_id, reported_user_id, reason, note, status, resolution...).",
    "export type AdminReport = {",
    "  id: string;",
    "  reporterId: string | null;",
    "  reporterEmail: string | null;",
    "  reportedUserId: string | null;",
    "  reportedEmail: string | null;",
    "  reportedSuspended: boolean;",
    "  reason: string;",
    "  note: string;",
    "  status: string;",
    "  resolution: string | null;",
    "  resolutionNote: string | null;",
    "  resolvedBy: string | null;",
    "  resolvedAt: string | null;",
    "  createdAt: string | null;",
    "};",
    "",
    "// Audit entry, ported from _audit(): actor, action, payload, created_at.",
    "export type AuditEntry = {",
    "  id: string;",
    "  actorUserId: string | null;",
    "  actorEmail: string | null;",
    "  action: string;",
    "  payload: Record<string, unknown>;",
    "  createdAt: string | null;",
    "};",
    "",
    "// The status filters ported verbatim from GET /admin/users.",
    'export type UserStatusFilter = "all" | "onboarded" | "suspended" | "admins" | "no-show";',
    "export type UserFilters = { q?: string; status?: UserStatusFilter; limit?: number };",
    "export type ReportFilters = { status?: string; limit?: number };",
    "",
    "// The self-guardrails ported from patch_user / soft_delete_user.",
    'export type ModerationAction = "suspend" | "unsuspend" | "grant_admin" | "revoke_admin" | "soft_delete";',
    'export type ReportAction = "dismiss" | "resolve" | "suspend_target";',
    "",
    "const fallbackUsers: AdminUser[] = [",
    '  { id: "sample-1", email: "ada@example.com", name: "Ada Lovelace", role: "admin", suspended: false, deleted: false, createdAt: "2026-01-02T00:00:00.000Z", lastSeenAt: "2026-06-30T00:00:00.000Z" },',
    '  { id: "sample-2", email: "grace@example.com", name: "Grace Hopper", role: "customer", suspended: false, deleted: false, createdAt: "2026-03-14T00:00:00.000Z", lastSeenAt: null },',
    '  { id: "sample-3", email: "flagged@example.com", name: "Flagged Account", role: "customer", suspended: true, deleted: false, createdAt: "2026-05-01T00:00:00.000Z", lastSeenAt: "2026-05-02T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackReports: AdminReport[] = [",
    '  { id: "sample-report-1", reporterId: "sample-2", reporterEmail: "grace@example.com", reportedUserId: "sample-3", reportedEmail: "flagged@example.com", reportedSuspended: true, reason: "Harassment", note: "Repeated unwanted messages.", status: "open", resolution: null, resolutionNote: null, resolvedBy: null, resolvedAt: null, createdAt: "2026-06-01T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackAudit: AuditEntry[] = [",
    '  { id: "sample-audit-1", actorUserId: "sample-1", actorEmail: "ada@example.com", action: "report.resolve", payload: { report_id: "sample-report-1", action: "suspend_target" }, createdAt: "2026-06-02T00:00:00.000Z" }',
    "];",
    "",
    "function rowToUser(row: Record<string, unknown>): AdminUser {",
    "  return {",
    "    id: String(row.id),",
    '    email: String(row.email || ""),',
    '    name: String(row.name || ""),',
    '    role: String(row.role || "customer"),',
    "    suspended: Boolean(row.suspended),",
    "    deleted: Boolean(row.deleted),",
    "    createdAt: row.created_at ? new Date(row.created_at as string).toISOString() : null,",
    "    lastSeenAt: row.last_seen_at ? new Date(row.last_seen_at as string).toISOString() : null",
    "  };",
    "}",
    "",
    "function rowToReport(row: Record<string, unknown>): AdminReport {",
    "  return {",
    "    id: String(row.id),",
    "    reporterId: row.reporter_id ? String(row.reporter_id) : null,",
    "    reporterEmail: row.reporter_email ? String(row.reporter_email) : null,",
    "    reportedUserId: row.reported_user_id ? String(row.reported_user_id) : null,",
    "    reportedEmail: row.reported_email ? String(row.reported_email) : null,",
    "    reportedSuspended: Boolean(row.reported_suspended),",
    '    reason: String(row.reason || ""),',
    '    note: String(row.note || ""),',
    '    status: String(row.status || "open"),',
    "    resolution: row.resolution ? String(row.resolution) : null,",
    "    resolutionNote: row.resolution_note ? String(row.resolution_note) : null,",
    "    resolvedBy: row.resolved_by ? String(row.resolved_by) : null,",
    "    resolvedAt: row.resolved_at ? new Date(row.resolved_at as string).toISOString() : null,",
    "    createdAt: row.created_at ? new Date(row.created_at as string).toISOString() : null",
    "  };",
    "}",
    "",
    "function rowToAudit(row: Record<string, unknown>): AuditEntry {",
    "  let payload: Record<string, unknown> = {};",
    "  const raw = row.payload;",
    "  if (raw && typeof raw === \"object\") {",
    "    payload = raw as Record<string, unknown>;",
    "  } else if (typeof raw === \"string\") {",
    "    try { payload = JSON.parse(raw) as Record<string, unknown>; } catch { payload = {}; }",
    "  }",
    "  return {",
    "    id: String(row.id),",
    "    actorUserId: row.actor_user_id ? String(row.actor_user_id) : null,",
    "    actorEmail: row.actor_email ? String(row.actor_email) : null,",
    '    action: String(row.action || ""),',
    "    payload,",
    "    createdAt: row.created_at ? new Date(row.created_at as string).toISOString() : null",
    "  };",
    "}",
    "",
    "// List + search users, ported from GET /admin/users: match email/name/id, apply",
    "// the status filter, hide deleted, newest first.",
    "export async function listUsers(filters: UserFilters = {}): Promise<AdminUser[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const status = filters.status || "all";',
    "  if (!hasDatabase()) {",
    "    const cutoff = Date.now() - 14 * 24 * 60 * 60 * 1000;",
    "    return fallbackUsers",
    "      .filter((u) => !u.deleted)",
    "      .filter((u) => !q || (u.email + \" \" + u.name + \" \" + u.id).toLowerCase().includes(q))",
    "      .filter((u) => {",
    '        if (status === "suspended") return u.suspended;',
    '        if (status === "admins") return u.role === "admin" || u.role === "owner";',
    '        if (status === "onboarded") return Boolean(u.lastSeenAt);',
    '        if (status === "no-show") return !u.lastSeenAt || new Date(u.lastSeenAt).getTime() < cutoff;',
    "        return true;",
    "      })",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    '    const wantSuspended = status === "suspended";',
    '    const wantAdmins = status === "admins";',
    '    const wantOnboarded = status === "onboarded";',
    '    const wantNoShow = status === "no-show";',
    "    const rows = (await sql`",
    "      select users.id, users.email, users.name,",
    "        coalesce(prof.role, 'customer') as role,",
    "        coalesce(prof.suspended, false) as suspended,",
    "        coalesce(prof.deleted, false) as deleted,",
    "        users.created_at, prof.last_seen_at",
    "      from users",
    "      left join admin_ops_user_flags prof on prof.user_id = users.id",
    "      where coalesce(prof.deleted, false) = false",
    "        and (${like}::text is null",
    "          or lower(users.email) like ${like}",
    "          or lower(coalesce(users.name, '')) like ${like}",
    "          or lower(users.id::text) like ${like})",
    "        and (${wantSuspended} = false or coalesce(prof.suspended, false) = true)",
    "        and (${wantAdmins} = false or coalesce(prof.role, 'customer') in ('admin','owner'))",
    "        and (${wantOnboarded} = false or prof.last_seen_at is not null)",
    "        and (${wantNoShow} = false or prof.last_seen_at is null or prof.last_seen_at < now() - interval '14 days')",
    "      order by users.created_at desc nulls last",
    "      limit ${limit}",
    "    `) as Record<string, unknown>[];",
    "    return rows.map(rowToUser);",
    "  } catch {",
    "    return fallbackUsers.filter((u) => !u.deleted).slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getUser(id: string): Promise<AdminUser | null> {",
    "  if (!hasDatabase()) return fallbackUsers.find((u) => u.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`",
    "      select users.id, users.email, users.name,",
    "        coalesce(prof.role, 'customer') as role,",
    "        coalesce(prof.suspended, false) as suspended,",
    "        coalesce(prof.deleted, false) as deleted,",
    "        users.created_at, prof.last_seen_at",
    "      from users",
    "      left join admin_ops_user_flags prof on prof.user_id = users.id",
    "      where users.id::text = ${id}",
    "      limit 1",
    "    `) as Record<string, unknown>[];",
    "    return rows[0] ? rowToUser(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Moderator action, ported from patch_user / soft_delete_user + their guardrails.",
    "// actorId is the signed-in admin; we refuse self-targeting moves like the source.",
    "export async function moderateUser(",
    "  actorId: string,",
    "  actorEmail: string,",
    "  targetId: string,",
    "  action: ModerationAction",
    "): Promise<{ ok: boolean; message?: string }> {",
    "  // Guardrails ported from the source: no acting on yourself for the",
    "  // destructive moves.",
    '  if (targetId === actorId && (action === "suspend" || action === "revoke_admin" || action === "soft_delete")) {',
    '    const msg = action === "suspend" ? "You cannot suspend yourself."',
    '      : action === "revoke_admin" ? "You cannot revoke your own admin." : "You cannot delete yourself.";',
    "    return { ok: false, message: msg };",
    "  }",
    "  if (!hasDatabase()) return { ok: false, message: \"Connect a database to moderate accounts.\" };",
    "  try {",
    "    const sql = getDatabase();",
    "    const existing = (await sql`select id from users where id::text = ${targetId} limit 1`) as Record<string, unknown>[];",
    "    if (!existing[0]) return { ok: false, message: \"User not found.\" };",
    "    // Ensure a flags row exists to update.",
    "    await sql`insert into admin_ops_user_flags (user_id) values (${targetId}) on conflict (user_id) do nothing`;",
    "    let auditAction = \"\";",
    '    if (action === "suspend") {',
    "      await sql`update admin_ops_user_flags set suspended = true, suspended_at = now(), updated_at = now() where user_id = ${targetId}`;",
    '      auditAction = "user.suspend";',
    '    } else if (action === "unsuspend") {',
    "      await sql`update admin_ops_user_flags set suspended = false, suspended_at = null, updated_at = now() where user_id = ${targetId}`;",
    '      auditAction = "user.unsuspend";',
    '    } else if (action === "grant_admin") {',
    "      await sql`update admin_ops_user_flags set role = 'admin', updated_at = now() where user_id = ${targetId}`;",
    '      auditAction = "user.grant_admin";',
    '    } else if (action === "revoke_admin") {',
    "      await sql`update admin_ops_user_flags set role = 'customer', updated_at = now() where user_id = ${targetId}`;",
    '      auditAction = "user.revoke_admin";',
    '    } else if (action === "soft_delete") {',
    "      // Ported from soft_delete_user: suspend, mark deleted, release the email.",
    "      await sql`update admin_ops_user_flags set suspended = true, deleted = true, deleted_at = now(), updated_at = now() where user_id = ${targetId}`;",
    "      await sql`update users set email = ${`deleted+${targetId}@app.local`}, name = 'Deleted user' where id::text = ${targetId}`;",
    '      auditAction = "user.delete";',
    "    }",
    "    await writeAudit(actorId, actorEmail, auditAction, { user_id: targetId });",
    "    return { ok: true };",
    "  } catch {",
    "    return { ok: false, message: \"Could not complete that action.\" };",
    "  }",
    "}",
    "",
    "// Reports queue, ported from GET /admin/reports with name/email hydration.",
    "export async function listReports(filters: ReportFilters = {}): Promise<AdminReport[]> {",
    "  const limit = Math.min(500, Math.max(1, filters.limit || 100));",
    '  const status = (filters.status || "").trim();',
    "  if (!hasDatabase()) {",
    "    return fallbackReports.filter((r) => !status || r.status === status).slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const statusFilter = status || null;",
    "    const rows = (await sql`",
    "      select r.id, r.reporter_id, rep.email as reporter_email,",
    "        r.reported_user_id, tgt.email as reported_email,",
    "        coalesce(tf.suspended, false) as reported_suspended,",
    "        r.reason, r.note, r.status, r.resolution, r.resolution_note,",
    "        r.resolved_by, r.resolved_at, r.created_at",
    "      from admin_ops_reports r",
    "      left join users rep on rep.id = r.reporter_id",
    "      left join users tgt on tgt.id = r.reported_user_id",
    "      left join admin_ops_user_flags tf on tf.user_id = r.reported_user_id",
    "      where (${statusFilter}::text is null or r.status = ${statusFilter})",
    "      order by r.created_at desc",
    "      limit ${limit}",
    "    `) as Record<string, unknown>[];",
    "    return rows.map(rowToReport);",
    "  } catch {",
    "    return fallbackReports.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getReport(id: string): Promise<AdminReport | null> {",
    "  if (!hasDatabase()) return fallbackReports.find((r) => r.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`",
    "      select r.id, r.reporter_id, rep.email as reporter_email,",
    "        r.reported_user_id, tgt.email as reported_email,",
    "        coalesce(tf.suspended, false) as reported_suspended,",
    "        r.reason, r.note, r.status, r.resolution, r.resolution_note,",
    "        r.resolved_by, r.resolved_at, r.created_at",
    "      from admin_ops_reports r",
    "      left join users rep on rep.id = r.reporter_id",
    "      left join users tgt on tgt.id = r.reported_user_id",
    "      left join admin_ops_user_flags tf on tf.user_id = r.reported_user_id",
    "      where r.id::text = ${id}",
    "      limit 1",
    "    `) as Record<string, unknown>[];",
    "    return rows[0] ? rowToReport(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Resolve a report, ported from POST /admin/reports/{id}/resolve: dismiss ->",
    "// dismissed; resolve/suspend_target -> resolved; suspend_target also suspends",
    "// the reported user. Resolver + resolved_at are recorded.",
    "export async function resolveReport(",
    "  actorId: string,",
    "  actorEmail: string,",
    "  reportId: string,",
    "  action: ReportAction,",
    "  note: string",
    "): Promise<{ ok: boolean; status?: string; message?: string }> {",
    "  if (!hasDatabase()) return { ok: false, message: \"Connect a database to resolve reports.\" };",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`select id, reported_user_id, reason from admin_ops_reports where id::text = ${reportId} limit 1`) as Record<string, unknown>[];",
    "    const report = rows[0];",
    "    if (!report) return { ok: false, message: \"Report not found.\" };",
    '    const newStatus = action === "dismiss" ? "dismissed" : "resolved";',
    "    await sql`",
    "      update admin_ops_reports",
    "      set status = ${newStatus}, resolution = ${action}, resolution_note = ${note || null},",
    "        resolved_by = ${actorId}, resolved_at = now()",
    "      where id::text = ${reportId}",
    "    `;",
    '    if (action === "suspend_target" && report.reported_user_id) {',
    "      const targetId = String(report.reported_user_id);",
    '      const suspendReason = `Report ${reportId}: ` + (report.reason || "");',
    "      await sql`insert into admin_ops_user_flags (user_id) values (${targetId}) on conflict (user_id) do nothing`;",
    "      await sql`update admin_ops_user_flags set suspended = true, suspended_at = now(), suspended_reason = ${suspendReason}, updated_at = now() where user_id = ${targetId}`;",
    "    }",
    '    await writeAudit(actorId, actorEmail, "report.resolve", { report_id: reportId, action });',
    "    return { ok: true, status: newStatus };",
    "  } catch {",
    "    return { ok: false, message: \"Could not resolve that report.\" };",
    "  }",
    "}",
    "",
    "// Operations run, ported from the audited POST /admin/ops/* handlers. Each op",
    "// records an audit entry; without a DB we report the no-op honestly.",
    'export const opsCatalog = [',
    '  { key: "run-nudges", label: "Send re-engagement nudges", description: "Notify accounts that have gone quiet." },',
    '  { key: "recount-reports", label: "Recount open reports", description: "Refresh the Trust & Safety counters." },',
    '  { key: "sweep-no-shows", label: "Sweep no-show accounts", description: "Flag accounts inactive for 14+ days." }',
    "] as const;",
    "export type OpsKey = (typeof opsCatalog)[number][\"key\"];",
    "",
    "export function isOpsKey(value: string): value is OpsKey {",
    "  return opsCatalog.some((op) => op.key === value);",
    "}",
    "",
    "export async function runOp(",
    "  actorId: string,",
    "  actorEmail: string,",
    "  op: OpsKey",
    "): Promise<{ ok: boolean; result: Record<string, unknown>; message?: string }> {",
    "  if (!hasDatabase()) {",
    "    return { ok: false, result: {}, message: \"Connect a database to run operations.\" };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    let result: Record<string, unknown> = {};",
    '    if (op === "recount-reports") {',
    "      const rows = (await sql`select count(*)::int as n from admin_ops_reports where status = 'open'`) as Record<string, unknown>[];",
    "      result = { open_reports: Number(rows[0]?.n || 0) };",
    '    } else if (op === "sweep-no-shows") {',
    "      const rows = (await sql`select count(*)::int as n from admin_ops_user_flags where deleted = false and (last_seen_at is null or last_seen_at < now() - interval '14 days')`) as Record<string, unknown>[];",
    "      result = { no_show: Number(rows[0]?.n || 0) };",
    "    } else {",
    "      // run-nudges: no external mailer wired here; report the candidate count.",
    "      const rows = (await sql`select count(*)::int as n from admin_ops_user_flags where deleted = false and suspended = false and (last_seen_at is null or last_seen_at < now() - interval '7 days')`) as Record<string, unknown>[];",
    "      result = { nudge_candidates: Number(rows[0]?.n || 0) };",
    "    }",
    "    await writeAudit(actorId, actorEmail, `ops.${op}`, result);",
    "    return { ok: true, result };",
    "  } catch {",
    "    return { ok: false, result: {}, message: \"Could not run that operation.\" };",
    "  }",
    "}",
    "",
    "// Audit log read + write, ported from _audit() + GET /admin/audit.",
    "export async function writeAudit(",
    "  actorId: string | null,",
    "  actorEmail: string | null,",
    "  action: string,",
    "  payload: Record<string, unknown>",
    "): Promise<void> {",
    "  if (!hasDatabase()) return;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into admin_ops_audit (actor_user_id, actor_email, action, payload) values (${actorId}, ${actorEmail}, ${action}, ${JSON.stringify(payload)}::jsonb)`;",
    "  } catch {",
    "    // Ported behavior: an audit failure never blocks the action.",
    "  }",
    "}",
    "",
    "export async function listAudit(limit = 200): Promise<AuditEntry[]> {",
    "  const capped = Math.min(1000, Math.max(1, limit));",
    "  if (!hasDatabase()) return fallbackAudit.slice(0, capped);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`select id, actor_user_id, actor_email, action, payload, created_at from admin_ops_audit order by created_at desc limit ${capped}`) as Record<string, unknown>[];",
    "    return rows.map(rowToAudit);",
    "  } catch {",
    "    return fallbackAudit.slice(0, capped);",
    "  }",
    "}",
    "",
    "export function adminOpsEnabled(): boolean {",
    '  return process.env.FEATURE_ADMIN_OPS !== "false";',
    "}"
  ]);
}

// ---- src/app/api/admin-ops/users/route.ts -----------------------------------

function usersApiFile(): GeneratedModuleFile {
  return file("src/app/api/admin-ops/users/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listUsers, moderateUser, adminOpsEnabled } from "@/lib/db/admin-ops";',
    'import type { ModerationAction, UserStatusFilter } from "@/lib/db/admin-ops";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    'const statuses = ["all", "onboarded", "suspended", "admins", "no-show"];',
    'const actions = ["suspend", "unsuspend", "grant_admin", "revoke_admin", "soft_delete"];',
    "",
    "export async function GET(request: Request) {",
    '  if (!adminOpsEnabled()) return NextResponse.json({ ok: false, message: "The operations console is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const rawStatus = url.searchParams.get("status") || "all";',
    '  const status = (statuses.includes(rawStatus) ? rawStatus : "all") as UserStatusFilter;',
    '  const users = await listUsers({ q: url.searchParams.get("q") || undefined, status });',
    "  return NextResponse.json({ ok: true, users });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const targetId = typeof body.targetId === "string" ? body.targetId.trim() : "";',
    '  const action = typeof body.action === "string" ? body.action : "";',
    '  if (!targetId) return NextResponse.json({ ok: false, message: "A target user is required." }, { status: 400 });',
    '  if (!actions.includes(action)) return NextResponse.json({ ok: false, message: "Unknown action." }, { status: 400 });',
    '  const result = await moderateUser(user.email, user.email, targetId, action as ModerationAction);',
    "  if (!result.ok) {",
    '    const status = result.message && result.message.startsWith("You cannot") ? 400 : 503;',
    "    return NextResponse.json({ ok: false, message: result.message }, { status });",
    "  }",
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/admin-ops/reports/route.ts ---------------------------------

function reportsApiFile(): GeneratedModuleFile {
  return file("src/app/api/admin-ops/reports/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listReports, resolveReport, adminOpsEnabled } from "@/lib/db/admin-ops";',
    'import type { ReportAction } from "@/lib/db/admin-ops";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    'const reportActions = ["dismiss", "resolve", "suspend_target"];',
    "",
    "export async function GET(request: Request) {",
    '  if (!adminOpsEnabled()) return NextResponse.json({ ok: false, message: "The operations console is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const reports = await listReports({ status: url.searchParams.get("status") || undefined });',
    "  return NextResponse.json({ ok: true, reports });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const reportId = typeof body.reportId === "string" ? body.reportId.trim() : "";',
    '  const action = typeof body.action === "string" ? body.action : "";',
    '  const note = typeof body.note === "string" ? body.note : "";',
    '  if (!reportId) return NextResponse.json({ ok: false, message: "A report is required." }, { status: 400 });',
    '  if (!reportActions.includes(action)) return NextResponse.json({ ok: false, message: "Unknown action." }, { status: 400 });',
    '  const result = await resolveReport(user.email, user.email, reportId, action as ReportAction, note);',
    '  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 503 });',
    "  return NextResponse.json({ ok: true, status: result.status });",
    "}"
  ]);
}

// ---- src/app/api/admin-ops/operations/route.ts ------------------------------

function operationsApiFile(): GeneratedModuleFile {
  return file("src/app/api/admin-ops/operations/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { runOp, isOpsKey, adminOpsEnabled } from "@/lib/db/admin-ops";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(request: Request) {",
    '  if (!adminOpsEnabled()) return NextResponse.json({ ok: false, message: "The operations console is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const op = typeof body.op === "string" ? body.op : "";',
    '  if (!isOpsKey(op)) return NextResponse.json({ ok: false, message: "Unknown operation." }, { status: 400 });',
    '  const result = await runOp(user.email, user.email, op);',
    '  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 503 });',
    "  return NextResponse.json({ ok: true, result: result.result });",
    "}"
  ]);
}

// ---- src/app/admin-ops/page.tsx (console home) ------------------------------

function consolePageFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listReports, adminOpsEnabled } from "@/lib/db/admin-ops";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AdminOpsHome() {",
    "  if (!adminOpsEnabled()) {",
    '    return (<main className="shell"><h1>Operations</h1><p>The operations console is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/admin-ops");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    '  const openReports = (await listReports({ status: "open" })).length;',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Operations</p>',
    "      <h1>Admin console</h1>",
    "      <p>Manage members, work the Trust &amp; Safety queue, run operations, and review the audit trail.</p>",
    "      {!isAdmin ? (",
    '        <p className="note">You can view the console. Only admins can take action.</p>',
    "      ) : null}",
    '      <section className="grid">',
    '        <Link className="card" href="/admin-ops/users"><span>Members</span><strong>Users</strong><p>Search, suspend, and manage accounts.</p></Link>',
    '        <Link className="card" href="/admin-ops/reports"><span>Trust &amp; Safety</span><strong>Reports{openReports > 0 ? ` (${openReports} open)` : ""}</strong><p>Review and resolve reports.</p></Link>',
    '        <Link className="card" href="/admin-ops/operations"><span>Operations</span><strong>Run ops</strong><p>Trigger maintenance jobs.</p></Link>',
    '        <Link className="card" href="/admin-ops/audit"><span>History</span><strong>Audit log</strong><p>Every action, newest first.</p></Link>',
    "      </section>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/users/page.tsx (list + search) -----------------------

function usersPageFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/users/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listUsers, adminOpsEnabled } from "@/lib/db/admin-ops";',
    'import type { UserStatusFilter } from "@/lib/db/admin-ops";',
    'import { UserActions } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    'const statuses: UserStatusFilter[] = ["all", "onboarded", "suspended", "admins", "no-show"];',
    "",
    "export default async function AdminUsersPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; status?: string }>;",
    "}) {",
    "  if (!adminOpsEnabled()) {",
    '    return (<main className="shell"><h1>Users</h1><p>The operations console is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/admin-ops/users");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const status = (statuses.includes((params?.status || "all") as UserStatusFilter) ? params?.status : "all") as UserStatusFilter;',
    "  const users = await listUsers({ q: q || undefined, status });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow"><a href="/admin-ops">Operations</a> · Members</p>',
    "      <h1>Users</h1>",
    "      <p>{users.length} shown.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search email, name, or id" aria-label="Search users" />',
    '        <label className="field"><span>Status</span>',
    '          <select className="input" name="status" defaultValue={status} aria-label="Filter by status">',
    "            {statuses.map((s) => (<option key={s} value={s}>{s}</option>))}",
    "          </select>",
    "        </label>",
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {users.length === 0 ? (",
    '        <p className="note">{q ? `No users match "${q}".` : "No users yet."}</p>',
    "      ) : (",
    '        <div className="table-scroll">',
    '          <table className="table">',
    "            <thead>",
    "              <tr><th scope=\"col\">User</th><th scope=\"col\">Role</th><th scope=\"col\">Status</th><th scope=\"col\">Created</th>{isAdmin ? <th scope=\"col\">Actions</th> : null}</tr>",
    "            </thead>",
    "            <tbody>",
    "              {users.map((u) => (",
    "                <tr key={u.id}>",
    "                  <td><strong>{u.name || \"Unnamed\"}</strong><br /><span className=\"note\">{u.email}</span></td>",
    "                  <td>{u.role}</td>",
    "                  <td>{u.suspended ? \"Suspended\" : \"Active\"}</td>",
    "                  <td>{u.createdAt ? u.createdAt.slice(0, 10) : \"—\"}</td>",
    "                  {isAdmin ? (<td><UserActions userId={u.id} role={u.role} suspended={u.suspended} isSelf={String(user?.email || \"\") === u.email} /></td>) : null}",
    "                </tr>",
    "              ))}",
    "            </tbody>",
    "          </table>",
    "        </div>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/users/actions.tsx (client action buttons) ------------

function usersActionsFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/users/actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function UserActions({",
    "  userId,",
    "  role,",
    "  suspended,",
    "  isSelf",
    "}: {",
    "  userId: string;",
    "  role: string;",
    "  suspended: boolean;",
    "  isSelf: boolean;",
    "}) {",
    "  const router = useRouter();",
    '  const [error, setError] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    '  const isAdminRole = role === "admin" || role === "owner";',
    "",
    "  async function act(action: string) {",
    '    if (action === "soft_delete" && !window.confirm("Soft-delete this account? This releases their email.")) return;',
    "    setBusy(true);",
    '    setError("");',
    "    try {",
    '      const res = await fetch("/api/admin-ops/users", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ targetId: userId, action })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok) {",
    '        setError(data.message || "That action did not work.");',
    "      } else {",
    "        router.refresh();",
    "      }",
    "    } catch {",
    '      setError("Something went wrong. Try again.");',
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="row-actions">',
    "      {suspended ? (",
    '        <button className="button" type="button" disabled={busy} onClick={() => act("unsuspend")}>Unsuspend</button>',
    "      ) : (",
    '        <button className="button" type="button" disabled={busy || isSelf} onClick={() => act("suspend")}>Suspend</button>',
    "      )}",
    "      {isAdminRole ? (",
    '        <button className="button" type="button" disabled={busy || isSelf} onClick={() => act("revoke_admin")}>Revoke admin</button>',
    "      ) : (",
    '        <button className="button" type="button" disabled={busy} onClick={() => act("grant_admin")}>Make admin</button>',
    "      )}",
    '      <button className="button danger" type="button" disabled={busy || isSelf} onClick={() => act("soft_delete")}>Delete</button>',
    '      {error ? <span className="note" role="alert">{error}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/reports/page.tsx -------------------------------------

function reportsPageFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/reports/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listReports, adminOpsEnabled } from "@/lib/db/admin-ops";',
    'import { ReportActions } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    'const filters = ["open", "resolved", "dismissed", "all"];',
    "",
    "export default async function AdminReportsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ status?: string }>;",
    "}) {",
    "  if (!adminOpsEnabled()) {",
    '    return (<main className="shell"><h1>Reports</h1><p>The operations console is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/admin-ops/reports");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const filter = filters.includes(params?.status || "open") ? (params?.status || "open") : "open";',
    '  const reports = await listReports({ status: filter === "all" ? undefined : filter });',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow"><a href="/admin-ops">Operations</a> · Trust &amp; Safety</p>',
    "      <h1>Reports</h1>",
    '      <nav className="chips" aria-label="Filter reports by status">',
    "        {filters.map((s) => (",
    '          <a key={s} className={`chip${filter === s ? " active" : ""}`} href={`/admin-ops/reports?status=${s}`}>{s}</a>',
    "        ))}",
    "      </nav>",
    "      {reports.length === 0 ? (",
    '        <p className="note">No reports in this view.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {reports.map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    "              <span>{r.status}{r.createdAt ? ` · ${r.createdAt.slice(0, 10)}` : \"\"}</span>",
    "              <strong>{r.reason || \"Report\"}</strong>",
    "              {r.note ? <p>&ldquo;{r.note}&rdquo;</p> : null}",
    "              <p className=\"note\">Reporter: {r.reporterEmail || \"—\"} · Reported: {r.reportedEmail || \"—\"}{r.reportedSuspended ? \" (suspended)\" : \"\"}</p>",
    "              {r.resolution ? (",
    "                <p className=\"note\">Resolved as {r.resolution}{r.resolutionNote ? `: ${r.resolutionNote}` : \"\"}</p>",
    '              ) : isAdmin && r.status === "open" ? (',
    "                <ReportActions reportId={r.id} />",
    "              ) : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/reports/actions.tsx ----------------------------------

function reportsActionsFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/reports/actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ReportActions({ reportId }: { reportId: string }) {",
    "  const router = useRouter();",
    '  const [note, setNote] = useState("");',
    '  const [error, setError] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    "",
    "  async function resolve(action: string) {",
    '    if (action === "suspend_target" && !window.confirm("Suspend the reported user?")) return;',
    "    setBusy(true);",
    '    setError("");',
    "    try {",
    '      const res = await fetch("/api/admin-ops/reports", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ reportId, action, note })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok) {",
    '        setError(data.message || "That action did not work.");',
    "      } else {",
    "        router.refresh();",
    "      }",
    "    } catch {",
    '      setError("Something went wrong. Try again.");',
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <label className="field"><span>Resolution note (optional)</span>',
    '        <input className="input" type="text" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Context for the log" aria-label="Resolution note" />',
    "      </label>",
    '      <div className="row-actions">',
    '        <button className="button danger" type="button" disabled={busy} onClick={() => resolve("suspend_target")}>Suspend target</button>',
    '        <button className="button" type="button" disabled={busy} onClick={() => resolve("resolve")}>Mark resolved</button>',
    '        <button className="button" type="button" disabled={busy} onClick={() => resolve("dismiss")}>Dismiss</button>',
    "      </div>",
    '      {error ? <span className="note" role="alert">{error}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/operations/page.tsx ----------------------------------

function operationsPageFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/operations/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { opsCatalog, adminOpsEnabled } from "@/lib/db/admin-ops";',
    'import { OpsRunner } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AdminOperationsPage() {",
    "  if (!adminOpsEnabled()) {",
    '    return (<main className="shell"><h1>Operations</h1><p>The operations console is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/admin-ops/operations");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow"><a href="/admin-ops">Operations</a> · Run ops</p>',
    "      <h1>Operations</h1>",
    "      <p>Trigger maintenance jobs by hand. Every run is written to the audit log.</p>",
    "      {!isAdmin ? (",
    '        <p className="note">Only admins can run operations.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {opsCatalog.map((op) => (",
    "            <OpsRunner key={op.key} opKey={op.key} label={op.label} description={op.description} />",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/operations/actions.tsx -------------------------------

function operationsActionsFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/operations/actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "export function OpsRunner({",
    "  opKey,",
    "  label,",
    "  description",
    "}: {",
    "  opKey: string;",
    "  label: string;",
    "  description: string;",
    "}) {",
    "  const [busy, setBusy] = useState(false);",
    '  const [message, setMessage] = useState("");',
    "  const [ok, setOk] = useState(false);",
    "",
    "  async function run() {",
    "    setBusy(true);",
    '    setMessage("");',
    "    try {",
    '      const res = await fetch("/api/admin-ops/operations", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ op: opKey })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok) {",
    "        setOk(false);",
    '        setMessage(data.message || "That run did not work.");',
    "      } else {",
    "        setOk(true);",
    '        setMessage("Done: " + JSON.stringify(data.result || {}));',
    "      }",
    "    } catch {",
    "      setOk(false);",
    '      setMessage("Something went wrong. Try again.");',
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <article className="wide-card">',
    "      <strong>{label}</strong>",
    "      <p>{description}</p>",
    '      <div className="row-actions">',
    '        <button className="button primary" type="button" disabled={busy} onClick={run}>{busy ? "Running…" : "Run"}</button>',
    "      </div>",
    '      {message ? <p className={ok ? "note" : "note"} role="status">{message}</p> : null}',
    "    </article>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin-ops/audit/page.tsx ---------------------------------------

function auditPageFile(): GeneratedModuleFile {
  return file("src/app/admin-ops/audit/page.tsx", [
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listAudit, adminOpsEnabled } from "@/lib/db/admin-ops";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AdminAuditPage() {",
    "  if (!adminOpsEnabled()) {",
    '    return (<main className="shell"><h1>Audit log</h1><p>The operations console is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/admin-ops/audit");',
    "  const entries = await listAudit(200);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow"><a href="/admin-ops">Operations</a> · History</p>',
    "      <h1>Audit log</h1>",
    "      <p>Every operator action, newest first.</p>",
    "      {entries.length === 0 ? (",
    '        <p className="note">No actions have been logged yet.</p>',
    "      ) : (",
    '        <div className="table-scroll">',
    '          <table className="table">',
    "            <thead>",
    "              <tr><th scope=\"col\">When</th><th scope=\"col\">Actor</th><th scope=\"col\">Action</th><th scope=\"col\">Details</th></tr>",
    "            </thead>",
    "            <tbody>",
    "              {entries.map((e) => (",
    "                <tr key={e.id}>",
    "                  <td>{e.createdAt ? e.createdAt.slice(0, 16).replace(\"T\", \" \") : \"—\"}</td>",
    "                  <td>{e.actorEmail || e.actorUserId || \"—\"}</td>",
    "                  <td>{e.action}</td>",
    "                  <td><code>{JSON.stringify(e.payload)}</code></td>",
    "                </tr>",
    "              ))}",
    "            </tbody>",
    "          </table>",
    "        </div>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

export const adminOpsModule: AppModule = {
  slug: "admin-ops-moderation",
  name: "Admin, Ops & Moderation",
  tier: "optional",
  featureFlagEnv: "FEATURE_ADMIN_OPS",
  files: () => [
    adminOpsLibFile(),
    usersApiFile(),
    reportsApiFile(),
    operationsApiFile(),
    consolePageFile(),
    usersPageFile(),
    usersActionsFile(),
    reportsPageFile(),
    reportsActionsFile(),
    operationsPageFile(),
    operationsActionsFile(),
    auditPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "-- admin-ops-moderation: per-user moderation flags, reports queue, and audit",
      "-- log. Flags live in their own table (not on users) so the module owns its",
      "-- schema and references the app's real users(id).",
      "create table if not exists admin_ops_user_flags (",
      "  user_id uuid primary key references users(id) on delete cascade,",
      "  role text not null default 'customer',",
      "  suspended boolean not null default false,",
      "  suspended_at timestamptz,",
      "  suspended_reason text,",
      "  deleted boolean not null default false,",
      "  deleted_at timestamptz,",
      "  last_seen_at timestamptz,",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists admin_ops_user_flags_suspended_idx on admin_ops_user_flags (suspended) where suspended = true;",
      "",
      "create table if not exists admin_ops_reports (",
      "  id uuid primary key default gen_random_uuid(),",
      "  reporter_id uuid references users(id) on delete set null,",
      "  reported_user_id uuid references users(id) on delete set null,",
      "  reason text not null default '',",
      "  note text not null default '',",
      "  status text not null default 'open',",
      "  resolution text,",
      "  resolution_note text,",
      "  resolved_by uuid references users(id) on delete set null,",
      "  resolved_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists admin_ops_reports_status_idx on admin_ops_reports (status, created_at desc);",
      "",
      "create table if not exists admin_ops_audit (",
      "  id uuid primary key default gen_random_uuid(),",
      "  actor_user_id uuid references users(id) on delete set null,",
      "  actor_email text,",
      "  action text not null,",
      "  payload jsonb not null default '{}'::jsonb,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists admin_ops_audit_created_idx on admin_ops_audit (created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Seed one resolved audit entry so the log renders on a fresh install.",
      "insert into admin_ops_audit (actor_email, action, payload) values",
      "  ('owner@example.com', 'console.installed', '{\"note\": \"Admin, Ops & Moderation ready\"}'::jsonb)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Admin, Ops & Moderation — set to false to switch the operations console off.",
    "FEATURE_ADMIN_OPS=true"
  ],
  homeLinks: () => ['        <a className="button" href="/admin-ops">Admin console</a>'],
  navLinks: () => [{ href: "/admin-ops", label: "Admin console" }]
};
