// ai-assist — AI services for content generation and suggestions, ported from
// ChurchConnect's real AI layer (backend/routes/ai_services.py + the shared
// helpers in backend/routes/__init__.py). We carried over the ACTUAL logic:
//   - the owner's-own-key gate: EMERGENT_LLM_KEY / OPENAI_API_KEY read from env,
//     graceful {"error":"AI service not configured"} when unset (never blocks UI).
//   - get_ai_response: call the model with a system prompt + user text, then log
//     usage; get_ai_json_response's resilient JSON extraction (```json fences,
//     bare ```, first-brace-to-last-brace fallback, raw_response last resort).
//   - track_ai_usage: log every call to ai_usage with feature, tokens_estimated,
//     and cost_estimated = round(tokens * 0.00003, 4).
//   - the feature-specific system prompts from ai_chat (scripture_library,
//     devotional, pastoral_care, bible_study, general) — generalized off the
//     church framing into plain content-assistant prompts (drafting, summarizing,
//     brainstorming, rewriting, general) so it drops into any app.
//   - the /api/ai/chat pattern: pick a feature prompt, append optional context,
//     log the request, return the generated text; plus the curate-video style
//     structured JSON suggestion (title/summary/tags) via json mode.
// Runs on the app owner's own database with graceful fallback, feature-flagged
// (FEATURE_AI_ASSIST); customers generate + read their own history, admins see
// the usage/cost ledger. Every table is prefixed ai_assist_ so it can never
// collide with another module's tables.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/ai-assist.ts (model + queries + provider call) --------------

function aiAssistLibFile(): GeneratedModuleFile {
  return file("src/lib/db/ai-assist.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A saved AI generation, ported from the ai_chat response shape + ai_usage",
    "// row (feature, tokens_estimated, cost_estimated). Each generation is scoped",
    "// to the owner (ownerId -> users.id) so people only see their own history.",
    "export type AiGeneration = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  feature: string;",
    "  prompt: string;",
    "  context: string;",
    "  output: string;",
    "  tokensEstimated: number;",
    "  costEstimated: number;",
    "  createdAt: string;",
    "};",
    "",
    "// The assist 'features', ported in spirit from ai_chat's feature_additions",
    "// (scripture_library/devotional/pastoral_care/bible_study/general) and",
    "// generalized off the church framing so any app can use them.",
    "export const AI_ASSIST_FEATURES = [",
    '  "draft",',
    '  "summarize",',
    '  "brainstorm",',
    '  "rewrite",',
    '  "suggest",',
    '  "general"',
    "] as const;",
    "",
    "export type AiAssistFeature = (typeof AI_ASSIST_FEATURES)[number];",
    "",
    "// System-prompt additions per feature, ported from ai_chat feature_additions",
    "// and rewritten as a neutral content assistant (no provider name, no domain).",
    "const FEATURE_PROMPTS: Record<string, string> = {",
    '  draft: "You are a helpful writing assistant. Draft clear, well-structured content in the user\'s own voice. Be concrete and useful.",',
    '  summarize: "You are a summarizing assistant. Condense the material into its key points. Be faithful to the source and never invent facts.",',
    '  brainstorm: "You are a brainstorming partner. Offer a varied, practical list of ideas. Favor breadth, then note the two or three strongest.",',
    '  rewrite: "You are an editing assistant. Rewrite the text to be clearer and tighter while preserving the meaning and tone. Return only the rewrite.",',
    '  suggest: "You are a suggestion assistant. Analyze the material and propose a title, a one-to-two sentence summary, and 5-10 relevant tags. Return valid JSON: {\\"title\\": \\"\\", \\"summary\\": \\"\\", \\"tags\\": []}.",',
    '  general: "You are a helpful, honest assistant. Answer plainly and admit when you are unsure."',
    "};",
    "",
    "export function systemPromptFor(feature: string, context?: string): string {",
    "  // Ported from ai_chat: base prompt by feature, then append optional context.",
    "  let prompt = FEATURE_PROMPTS[feature] || FEATURE_PROMPTS.general;",
    '  const ctx = (context || "").trim();',
    "  if (ctx) prompt += `\\n\\nAdditional context: ${ctx}`;",
    "  return prompt;",
    "}",
    "",
    "// The owner's own AI key, ported from routes/__init__.py:",
    "//   EMERGENT_LLM_KEY = os.environ.get('EMERGENT_LLM_KEY') or os.environ.get('OPENAI_API_KEY')",
    "// No provider name is shown to users; the app owner supplies the key.",
    "export function aiKey(): string {",
    '  return (process.env.AI_ASSIST_API_KEY || process.env.OPENAI_API_KEY || "").trim();',
    "}",
    "",
    "export function aiConfigured(): boolean {",
    "  return aiKey().length > 0;",
    "}",
    "",
    "// Cost estimate, ported verbatim from track_ai_usage:",
    "//   cost_estimated = round(tokens_est * 0.00003, 4)",
    "export function estimateCost(tokens: number): number {",
    "  return Math.round(tokens * 0.00003 * 10000) / 10000;",
    "}",
    "",
    "// Resilient JSON extraction, ported from get_ai_json_response: try a ```json",
    "// fence, then a bare ``` fence, then the raw string, then first-brace-to-last;",
    "// fall back to { raw_response } exactly like the source.",
    "export function extractJson(response: string): Record<string, unknown> {",
    "  const candidates: string[] = [];",
    '  if (response.includes("```json")) {',
    '    try { candidates.push(response.split("```json")[1].split("```")[0].trim()); } catch { /* ignore */ }',
    "  }",
    '  if (response.includes("```")) {',
    '    try { candidates.push(response.split("```")[1].split("```")[0].trim()); } catch { /* ignore */ }',
    "  }",
    "  candidates.push(response.trim());",
    '  for (const [open, close] of [["{", "}"], ["[", "]"]] as const) {',
    "    const first = response.indexOf(open);",
    "    const last = response.lastIndexOf(close);",
    "    if (first !== -1 && last > first) candidates.push(response.slice(first, last + 1));",
    "  }",
    "  for (const candidate of candidates) {",
    "    try {",
    "      const parsed = JSON.parse(candidate);",
    '      if (parsed && typeof parsed === "object") return parsed as Record<string, unknown>;',
    "    } catch {",
    "      continue;",
    "    }",
    "  }",
    "  return { raw_response: response };",
    "}",
    "",
    "export type AiCallResult = {",
    "  ok: boolean;",
    "  output: string;",
    "  tokensEstimated: number;",
    "  costEstimated: number;",
    "  error?: string;",
    "};",
    "",
    "// Call the model, ported from get_ai_response: require the owner's key, send the",
    "// system + user message, then estimate tokens (len(user_text)+len(response)) and",
    "// cost. Graceful when the key is unset — returns ok:false, never throws to the UI.",
    "// The provider is called over a plain HTTPS chat-completions endpoint using the",
    "// owner's key; no SDK and no provider name are surfaced to users.",
    "export async function generate(",
    "  systemMessage: string,",
    "  userText: string,",
    '  options: { feature?: string; jsonMode?: boolean; maxTokens?: number } = {}',
    "): Promise<AiCallResult> {",
    "  const key = aiKey();",
    "  if (!key) {",
    "    // Ported from get_ai_response's 'AI service not configured' guard.",
    '    return { ok: false, output: "", tokensEstimated: 0, costEstimated: 0, error: "AI service not configured" };',
    "  }",
    "  const maxTokens = Math.min(4096, Math.max(256, options.maxTokens || 4096));",
    "  try {",
    '    const base = (process.env.AI_ASSIST_BASE_URL || "https://api.openai.com/v1").replace(/\\/$/, "");',
    '    const model = process.env.AI_ASSIST_MODEL || "gpt-4o";',
    "    const body: Record<string, unknown> = {",
    "      model,",
    "      max_tokens: maxTokens,",
    "      messages: [",
    '        { role: "system", content: systemMessage },',
    '        { role: "user", content: userText }',
    "      ]",
    "    };",
    '    if (options.jsonMode) body.response_format = { type: "json_object" };',
    "    const response = await fetch(`${base}/chat/completions`, {",
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },',
    "      body: JSON.stringify(body)",
    "    });",
    "    if (!response.ok) {",
    "      const detail = await response.text().catch(() => \"\");",
    '      return { ok: false, output: "", tokensEstimated: 0, costEstimated: 0, error: `AI service error: ${response.status} ${detail.slice(0, 200)}` };',
    "    }",
    "    const data = (await response.json()) as {",
    "      choices?: Array<{ message?: { content?: string } }>;",
    "      usage?: { total_tokens?: number };",
    "    };",
    '    const output = data.choices?.[0]?.message?.content || "";',
    "    // Ported estimate: prefer the provider's token count, else len(input)+len(output).",
    "    const tokens = data.usage?.total_tokens || userText.length + output.length;",
    "    return { ok: true, output, tokensEstimated: tokens, costEstimated: estimateCost(tokens) };",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    '    return { ok: false, output: "", tokensEstimated: 0, costEstimated: 0, error: `AI service error: ${message}` };',
    "  }",
    "}",
    "",
    "function rowToGeneration(row: Record<string, unknown>): AiGeneration {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    feature: String(row.feature || "general"),',
    '    prompt: String(row.prompt || ""),',
    '    context: String(row.context || ""),',
    '    output: String(row.output || ""),',
    "    tokensEstimated: Number(row.tokens_estimated || 0),",
    "    costEstimated: Number(row.cost_estimated || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "const fallbackGenerations: AiGeneration[] = [",
    "  {",
    '    id: "sample-1",',
    "    ownerId: null,",
    '    feature: "draft",',
    '    prompt: "Draft a warm welcome message for new members.",',
    '    context: "",',
    '    output: "Welcome! We are so glad you are here. Take your time settling in — reach out any time and someone will be glad to help you find your way.",',
    "    tokensEstimated: 96,",
    "    costEstimated: 0.0029,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "// Log every call, ported from track_ai_usage: this row IS the usage ledger the",
    "// admin cost view reads. On no DB it is a no-op (best-effort), like the source.",
    "export async function logGeneration(input: {",
    "  ownerId?: string | null;",
    "  feature: string;",
    "  prompt: string;",
    "  context?: string;",
    "  output: string;",
    "  tokensEstimated: number;",
    "  costEstimated: number;",
    "}): Promise<AiGeneration | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into ai_assist_generations (",
    "        owner_id, feature, prompt, context, output, tokens_estimated, cost_estimated",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.feature}, ${input.prompt},",
    '        ${input.context || ""}, ${input.output}, ${input.tokensEstimated}, ${input.costEstimated}',
    "      )",
    "      returning id, owner_id, feature, prompt, context, output, tokens_estimated, cost_estimated, created_at`;",
    "    return rows[0] ? rowToGeneration(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// A person's own generation history, newest first (scoped to ownerId).",
    "export async function listGenerations(ownerId: string, limit = 50): Promise<AiGeneration[]> {",
    "  const capped = Math.min(200, Math.max(1, limit));",
    "  if (!hasDatabase()) return fallbackGenerations.slice(0, capped);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, feature, prompt, context, output, tokens_estimated, cost_estimated, created_at",
    "      from ai_assist_generations",
    "      where owner_id = ${ownerId}",
    "      order by created_at desc",
    "      limit ${capped}`;",
    "    return rows.map(rowToGeneration);",
    "  } catch {",
    "    return fallbackGenerations.slice(0, capped);",
    "  }",
    "}",
    "",
    "export async function getGeneration(id: string, ownerId: string): Promise<AiGeneration | null> {",
    "  if (!hasDatabase()) return fallbackGenerations.find((g) => g.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, feature, prompt, context, output, tokens_estimated, cost_estimated, created_at",
    "      from ai_assist_generations where id = ${id} and owner_id = ${ownerId} limit 1`;",
    "    return rows[0] ? rowToGeneration(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type AiUsageSummary = {",
    "  totalCalls: number;",
    "  totalTokens: number;",
    "  totalCost: number;",
    "  byFeature: Array<{ feature: string; calls: number; cost: number }>;",
    "};",
    "",
    "// The usage/cost ledger, ported from admin.py get_ai_usage + get_admin_stats:",
    "//   total_ai_calls = count(ai_usage); total_ai_cost = sum(cost_estimated).",
    "export async function usageSummary(): Promise<AiUsageSummary> {",
    "  if (!hasDatabase()) {",
    "    return { totalCalls: 0, totalTokens: 0, totalCost: 0, byFeature: [] };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const totals = await sql`",
    "      select count(*)::int as calls,",
    "        coalesce(sum(tokens_estimated), 0)::int as tokens,",
    "        coalesce(sum(cost_estimated), 0)::float as cost",
    "      from ai_assist_generations`;",
    "    const byFeature = await sql`",
    "      select feature, count(*)::int as calls, coalesce(sum(cost_estimated), 0)::float as cost",
    "      from ai_assist_generations",
    "      group by feature",
    "      order by cost desc`;",
    "    const t = totals[0] || {};",
    "    return {",
    "      totalCalls: Number(t.calls || 0),",
    "      totalTokens: Number(t.tokens || 0),",
    "      totalCost: Number(t.cost || 0),",
    "      byFeature: byFeature.map((r: Record<string, unknown>) => ({",
    '        feature: String(r.feature || "general"),',
    "        calls: Number(r.calls || 0),",
    "        cost: Number(r.cost || 0)",
    "      }))",
    "    };",
    "  } catch {",
    "    return { totalCalls: 0, totalTokens: 0, totalCost: 0, byFeature: [] };",
    "  }",
    "}",
    "",
    "export function aiAssistEnabled(): boolean {",
    '  return process.env.FEATURE_AI_ASSIST !== "false";',
    "}"
  ]);
}

// ---- src/app/api/ai-assist/route.ts (generate + list history) ---------------

function aiAssistApiFile(): GeneratedModuleFile {
  return file("src/app/api/ai-assist/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    "import {",
    "  aiAssistEnabled,",
    "  aiConfigured,",
    "  systemPromptFor,",
    "  generate,",
    "  logGeneration,",
    "  listGenerations,",
    "  extractJson,",
    "  AI_ASSIST_FEATURES",
    '} from "@/lib/db/ai-assist";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!aiAssistEnabled()) return NextResponse.json({ ok: false, message: "AI assist is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const generations = await listGenerations(String(user.id));",
    "  // Report readiness without ever blocking: configured tells the UI if a key is set.",
    "  return NextResponse.json({ ok: true, configured: aiConfigured(), generations });",
    "}",
    "",
    "// Generate content, ported from /api/ai/chat: pick the feature system prompt,",
    "// append optional context, call the model, log usage, and save the result.",
    "export async function POST(request: Request) {",
    '  if (!aiAssistEnabled()) return NextResponse.json({ ok: false, message: "AI assist is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const prompt = typeof body.prompt === "string" ? body.prompt.trim() : "";',
    '  const context = typeof body.context === "string" ? body.context.trim() : "";',
    '  const requested = typeof body.feature === "string" ? body.feature : "general";',
    '  const feature = (AI_ASSIST_FEATURES as readonly string[]).includes(requested) ? requested : "general";',
    "  if (prompt.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Tell the assistant what you need." }, { status: 400 });',
    "  }",
    "  // Graceful degrade, ported from get_ai_response's 'not configured' guard:",
    "  // the UI stays usable, we just say the owner needs to add a key.",
    "  if (!aiConfigured()) {",
    '    return NextResponse.json({ ok: false, configured: false, message: "This app owner has not connected an AI key yet." }, { status: 503 });',
    "  }",
    '  const jsonMode = feature === "suggest";',
    "  const system = systemPromptFor(feature, context);",
    "  const result = await generate(system, prompt, { feature, jsonMode });",
    "  if (!result.ok) {",
    '    return NextResponse.json({ ok: false, message: result.error || "The AI service is unavailable right now." }, { status: 502 });',
    "  }",
    "  // For 'suggest', surface the parsed JSON too (ported from curate-video shape).",
    "  const structured = jsonMode ? extractJson(result.output) : undefined;",
    "  const saved = await logGeneration({",
    "    ownerId: String(user.id),",
    "    feature,",
    "    prompt,",
    "    context,",
    "    output: result.output,",
    "    tokensEstimated: result.tokensEstimated,",
    "    costEstimated: result.costEstimated",
    "  });",
    "  return NextResponse.json({",
    "    ok: true,",
    "    output: result.output,",
    "    structured,",
    "    tokensEstimated: result.tokensEstimated,",
    "    costEstimated: result.costEstimated,",
    "    generation: saved",
    "  });",
    "}"
  ]);
}

// ---- src/app/api/ai-assist/[id]/route.ts (one saved generation) -------------

function aiAssistDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/ai-assist/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getGeneration, aiAssistEnabled } from "@/lib/db/ai-assist";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!aiAssistEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const generation = await getGeneration(id, String(user.id));",
    '  if (!generation) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, generation });",
    "}"
  ]);
}

// ---- src/app/api/ai-assist/usage/route.ts (admin cost ledger) ---------------

function aiAssistUsageApiFile(): GeneratedModuleFile {
  return file("src/app/api/ai-assist/usage/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { usageSummary, aiAssistEnabled } from "@/lib/db/ai-assist";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// The AI cost/usage ledger, ported from admin.py get_ai_usage — admins only.",
    "export async function GET() {",
    '  if (!aiAssistEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const summary = await usageSummary();",
    "  return NextResponse.json({ ok: true, summary });",
    "}"
  ]);
}

// ---- src/app/ai-assist/page.tsx (generate + history) ------------------------

function aiAssistPageFile(): GeneratedModuleFile {
  return file("src/app/ai-assist/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listGenerations, aiConfigured, aiAssistEnabled } from "@/lib/db/ai-assist";',
    'import { AssistForm } from "./assist-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AiAssistPage() {",
    "  if (!aiAssistEnabled()) {",
    '    return (<main className="shell"><h1>AI assist</h1><p>AI assist is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ai-assist");',
    "  const user = await getCurrentUser();",
    '  const generations = user?.id ? await listGenerations(String(user.id)) : [];',
    "  const configured = aiConfigured();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">AI assist</p>',
    "      <h1>Generate content &amp; suggestions</h1>",
    "      <p>Draft, summarize, brainstorm, or get title and tag suggestions. Everything you generate is saved to your history below.</p>",
    "      {!configured ? (",
    '        <p className="note" role="status">The app owner has not connected an AI key yet, so generation is paused. You can still browse your history.</p>',
    "      ) : null}",
    "      <AssistForm configured={configured} />",
    "      <h2>Your history</h2>",
    "      {generations.length === 0 ? (",
    '        <p className="note">Nothing yet. Your generations will appear here.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {generations.map((g) => (",
    '            <Link className="wide-card" key={g.id} href={`/ai-assist/${g.id}`}>',
    "              <span>{g.feature}</span>",
    "              <strong>{g.prompt.slice(0, 80)}{g.prompt.length > 80 ? \"…\" : \"\"}</strong>",
    "              <p>{g.output.slice(0, 140)}{g.output.length > 140 ? \"…\" : \"\"}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ai-assist/assist-form.tsx (client) -----------------------------

function assistFormFile(): GeneratedModuleFile {
  return file("src/app/ai-assist/assist-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function AssistForm({ configured }: { configured: boolean }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    '  const [output, setOutput] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("working");',
    '    setMessage("");',
    '    setOutput("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/ai-assist", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          feature: form.get("feature"),',
    '          prompt: form.get("prompt"),',
    '          context: form.get("context")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    '      setOutput(data.output || "");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <select className="input" name="feature" aria-label="What do you need?" defaultValue="draft">',
    '        <option value="draft">Draft something</option>',
    '        <option value="summarize">Summarize</option>',
    '        <option value="brainstorm">Brainstorm ideas</option>',
    '        <option value="rewrite">Rewrite / tighten</option>',
    '        <option value="suggest">Suggest title &amp; tags</option>',
    '        <option value="general">Ask anything</option>',
    "      </select>",
    '      <textarea className="input" name="prompt" rows={4} placeholder="What do you want the assistant to do?" aria-label="Your prompt" required />',
    '      <textarea className="input" name="context" rows={3} placeholder="Optional: paste any context or source material" aria-label="Optional context" />',
    '      {message ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "working" || !configured}>',
    '        {status === "working" ? "Generating…" : "Generate"}',
    "      </button>",
    "      {output ? (",
    '        <section className="panel" aria-live="polite">',
    '          <p className="eyebrow">Result</p>',
    '          <pre className="pre-wrap">{output}</pre>',
    "        </section>",
    "      ) : null}",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ai-assist/[id]/page.tsx (one saved generation) -----------------

function aiAssistDetailPageFile(): GeneratedModuleFile {
  return file("src/app/ai-assist/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getGeneration, aiAssistEnabled } from "@/lib/db/ai-assist";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AiAssistDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!aiAssistEnabled()) {",
    '    return (<main className="shell"><h1>AI assist</h1><p>AI assist is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ai-assist");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    '  const generation = user?.id ? await getGeneration(id, String(user.id)) : null;',
    "  if (!generation) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{generation.feature}</p>',
    "      <h1>Saved generation</h1>",
    '      <section className="card">',
    "        <span>Prompt</span>",
    "        <p>{generation.prompt}</p>",
    "      </section>",
    "      {generation.context ? (",
    '        <section className="card"><span>Context</span><p>{generation.context}</p></section>',
    "      ) : null}",
    '      <section className="panel">',
    '        <p className="eyebrow">Result</p>',
    '        <pre className="pre-wrap">{generation.output}</pre>',
    "      </section>",
    '      <p className="note">~{generation.tokensEstimated} tokens · est. ${generation.costEstimated.toFixed(4)}</p>',
    '      <p><Link className="button" href="/ai-assist">Back to AI assist</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ai-assist/usage/page.tsx (admin cost ledger) -------------------

function aiAssistUsagePageFile(): GeneratedModuleFile {
  return file("src/app/ai-assist/usage/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { usageSummary, aiAssistEnabled } from "@/lib/db/ai-assist";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AiAssistUsagePage() {",
    "  if (!aiAssistEnabled()) {",
    '    return (<main className="shell"><h1>AI usage</h1><p>AI assist is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ai-assist/usage");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>AI usage</h1><p className="note">This usage ledger is for admins only.</p></main>);',
    "  }",
    "  const summary = await usageSummary();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>AI usage &amp; cost</h1>",
    "      <p>Estimated spend across every AI generation in this app.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Total calls</span><strong>{summary.totalCalls}</strong></article>',
    '        <article className="card"><span>Total tokens</span><strong>{summary.totalTokens}</strong></article>',
    "        <article className=\"card\"><span>Est. cost</span><strong>${summary.totalCost.toFixed(4)}</strong></article>",
    "      </section>",
    "      {summary.byFeature.length > 0 ? (",
    "        <>",
    "          <h2>By feature</h2>",
    '          <section className="panel-list">',
    "            {summary.byFeature.map((row) => (",
    '              <article className="wide-card" key={row.feature}>',
    "                <span>{row.feature}</span>",
    "                <strong>{row.calls} calls</strong>",
    "                <p>Est. ${row.cost.toFixed(4)}</p>",
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : (",
    '        <p className="note">No AI usage recorded yet.</p>',
    "      )}",
    '      <p><Link className="button" href="/ai-assist">Back to AI assist</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const aiAssistModule: AppModule = {
  slug: "ai-assist",
  name: "AI Assist",
  tier: "optional",
  featureFlagEnv: "FEATURE_AI_ASSIST",
  files: () => [
    aiAssistLibFile(),
    aiAssistApiFile(),
    aiAssistDetailApiFile(),
    aiAssistUsageApiFile(),
    aiAssistPageFile(),
    assistFormFile(),
    aiAssistDetailPageFile(),
    aiAssistUsagePageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists ai_assist_generations (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  feature text not null default 'general',",
      "  prompt text not null default '',",
      "  context text not null default '',",
      "  output text not null default '',",
      "  tokens_estimated integer not null default 0,",
      "  cost_estimated numeric(12, 4) not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists ai_assist_generations_owner_idx on ai_assist_generations (owner_id, created_at desc);",
      "create index if not exists ai_assist_generations_feature_idx on ai_assist_generations (feature);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into ai_assist_generations (feature, prompt, context, output, tokens_estimated, cost_estimated) values",
      "  ('draft', 'Draft a warm welcome message for new members.', '', 'Welcome! We are so glad you are here. Take your time settling in — reach out any time and someone will be glad to help you find your way.', 96, 0.0029)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# AI Assist — set to false to switch AI content generation off.",
    "FEATURE_AI_ASSIST=true",
    "# The app owner's own AI key. Generation degrades gracefully when this is unset;",
    "# OPENAI_API_KEY is used as a fallback. AI_ASSIST_BASE_URL and AI_ASSIST_MODEL are optional.",
    "AI_ASSIST_API_KEY=",
    "# AI_ASSIST_BASE_URL=https://api.openai.com/v1",
    "# AI_ASSIST_MODEL=gpt-4o"
  ],
  requiredEnv: ["AI_ASSIST_API_KEY"],
  homeLinks: () => ['        <a className="button" href="/ai-assist">AI assist</a>'],
  navLinks: () => [{ href: "/ai-assist", label: "AI assist" }]
};
