// analytics-hope-index — reporting, engagement metrics, surveys, and a cross-app
// hope/belonging index, ported from ChurchConnect's real analytics code:
//   - backend/routes/reporting.py — /overview (total + new-in-30d/7d user counts,
//     content + engagement rollups), /user-growth (daily signups, cumulative,
//     first-week-vs-last-week growth-rate percent), /engagement-metrics
//     (active users, avg logins per user).
//   - backend/routes/user_analytics.py — log_user_activity (activity_type + details
//     rows), /engagement (activity counts by type with unique-user sets + top
//     features), engagement_rate daily/weekly/monthly = active / total * 100.
//   - src/components/SurveyAnalytics.tsx — survey question insights: choice
//     distribution + mostCommon %, numeric average/median/min/max, the low-rating
//     "needs attention" flag (avg < 3), and CSV-shaped response rollups.
// The hope/belonging index is the cross-app synthesis the survey ratings feed:
// scale answers are normalized 0..100 and averaged into an overall index with a
// per-app breakdown, so one dashboard reads belonging across every app on the DB.
// Generalized off ChurchConnect's church framing into plain copy. Runs on the app
// owner's own database with graceful sample-data fallback, feature-flagged
// (FEATURE_ANALYTICS); customers see their own dashboards, admins see everything.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/analytics.ts (model + queries, ported from the Python + TSX) --

function analyticsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/analytics.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// An activity event, ported from user_analytics.py log_user_activity:",
    "// (user_id, activity_type, details json, created_at). Everything the",
    "// engagement + hope views read is derived from these rows plus survey answers.",
    "export type ActivityType =",
    '  | "scripture_search"',
    '  | "journal_entry"',
    '  | "prayer_request"',
    '  | "testimony_shared"',
    '  | "connection_made"',
    '  | "devotional_read"',
    '  | "survey_completed"',
    '  | "sign_in";',
    "",
    "export type ActivityEvent = {",
    "  id: string;",
    "  userId: string;",
    "  appSlug: string;",
    "  activityType: string;",
    "  details: Record<string, unknown>;",
    "  createdAt: string;",
    "};",
    "",
    "// Overview counters, ported from reporting.py /overview: total users, new in the",
    "// last 30/7 days, plus content + engagement rollups over recorded activity.",
    "export type ReportingOverview = {",
    "  users: { total: number; newLast30Days: number; newLast7Days: number };",
    "  content: { events: number; surveysCompleted: number; connectionsMade: number };",
    "  engagement: { activeLast30Days: number; totalEvents: number };",
    "  generatedAt: string;",
    "};",
    "",
    "// A point on the growth curve, ported from reporting.py /user-growth daily_data.",
    "export type GrowthPoint = { date: string; newEvents: number; cumulative: number };",
    "export type UserGrowth = {",
    "  periodDays: number;",
    "  totalNewEvents: number;",
    "  growthRatePercent: number;",
    "  dailyData: GrowthPoint[];",
    "};",
    "",
    "// Feature engagement, ported from user_analytics.py /engagement: per activity",
    "// type, total_actions + unique_users, and the sorted top_features list; plus the",
    "// engagement_rate (active / total * 100) at daily/weekly/monthly windows.",
    "export type FeatureUsage = { activityType: string; totalActions: number; uniqueUsers: number };",
    "export type EngagementReport = {",
    "  periodDays: number;",
    "  features: FeatureUsage[];",
    "  topFeatures: FeatureUsage[];",
    "  engagementRate: { daily: number; weekly: number; monthly: number };",
    "};",
    "",
    "// Survey question insight, ported from SurveyAnalytics.tsx generateInsights.",
    "export type ChoiceInsight = {",
    '  type: "choice";',
    "  questionId: string;",
    "  questionText: string;",
    "  totalResponses: number;",
    "  distribution: Record<string, number>;",
    "  mostCommon: { answer: string; count: number; percentage: string } | null;",
    "};",
    "export type NumericInsight = {",
    '  type: "numeric";',
    "  questionId: string;",
    "  questionText: string;",
    "  totalResponses: number;",
    "  average: string;",
    "  median: number;",
    "  min: number;",
    "  max: number;",
    "  needsAttention: boolean;",
    "};",
    "export type QuestionInsight = ChoiceInsight | NumericInsight;",
    "export type SurveyInsights = {",
    "  surveyId: string;",
    "  title: string;",
    "  totalResponses: number;",
    "  questions: QuestionInsight[];",
    "  unusual: Array<{ questionId: string; questionText: string; message: string }>;",
    "};",
    "",
    "// The cross-app hope/belonging index: scale answers normalized to 0..100 and",
    "// averaged, with a per-app breakdown so one number reads belonging everywhere.",
    "export type HopeIndex = {",
    "  overall: number;",
    "  responseCount: number;",
    "  byApp: Array<{ appSlug: string; score: number; responseCount: number }>;",
    "  band: string;",
    "};",
    "",
    "// ---- shape helpers ---------------------------------------------------------",
    "",
    "function isoDaysAgo(days: number): string {",
    "  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();",
    "}",
    "",
    "// Hope band label from the 0..100 index (plain, non-clinical copy).",
    "export function hopeBand(score: number): string {",
    '  if (score >= 75) return "thriving";',
    '  if (score >= 55) return "steady";',
    '  if (score >= 35) return "strained";',
    '  return "at risk";',
    "}",
    "",
    "// ---- fallback sample data (no DB) ------------------------------------------",
    "",
    "const fallbackEvents: ActivityEvent[] = [",
    '  { id: "evt-1", userId: "u-1", appSlug: "wellbeing", activityType: "journal_entry", details: {}, createdAt: isoDaysAgo(1) },',
    '  { id: "evt-2", userId: "u-1", appSlug: "wellbeing", activityType: "survey_completed", details: {}, createdAt: isoDaysAgo(2) },',
    '  { id: "evt-3", userId: "u-2", appSlug: "wellbeing", activityType: "prayer_request", details: {}, createdAt: isoDaysAgo(3) },',
    '  { id: "evt-4", userId: "u-2", appSlug: "community", activityType: "connection_made", details: {}, createdAt: isoDaysAgo(5) },',
    '  { id: "evt-5", userId: "u-3", appSlug: "community", activityType: "testimony_shared", details: {}, createdAt: isoDaysAgo(9) },',
    '  { id: "evt-6", userId: "u-3", appSlug: "wellbeing", activityType: "scripture_search", details: {}, createdAt: isoDaysAgo(20) }',
    "];",
    "",
    "const fallbackOverview: ReportingOverview = {",
    "  users: { total: 3, newLast30Days: 3, newLast7Days: 2 },",
    "  content: { events: 6, surveysCompleted: 1, connectionsMade: 1 },",
    "  engagement: { activeLast30Days: 3, totalEvents: 6 },",
    "  generatedAt: new Date().toISOString()",
    "};",
    "",
    "const fallbackHope: HopeIndex = {",
    "  overall: 68,",
    "  responseCount: 4,",
    '  band: "steady",',
    "  byApp: [",
    '    { appSlug: "wellbeing", score: 72, responseCount: 3 },',
    '    { appSlug: "community", score: 56, responseCount: 1 }',
    "  ]",
    "};",
    "",
    "// ---- activity log (ported from log_user_activity) --------------------------",
    "",
    "export async function logActivity(userId: string, appSlug: string, activityType: string, details: Record<string, unknown> = {}): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into analytics_events (user_id, app_slug, activity_type, details) values (${userId}, ${appSlug}, ${activityType}, ${JSON.stringify(details)}::jsonb)`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- overview (ported from reporting.py /overview) -------------------------",
    "",
    "export async function getOverview(): Promise<ReportingOverview> {",
    "  if (!hasDatabase()) return fallbackOverview;",
    "  try {",
    "    const sql = getDatabase();",
    "    const day30 = isoDaysAgo(30);",
    "    const day7 = isoDaysAgo(7);",
    "    const totalUsers = await sql`select count(*)::int as c from users`;",
    "    const new30 = await sql`select count(*)::int as c from users where created_at >= ${day30}`;",
    "    const new7 = await sql`select count(*)::int as c from users where created_at >= ${day7}`;",
    "    const totalEvents = await sql`select count(*)::int as c from analytics_events`;",
    "    const surveys = await sql`select count(*)::int as c from analytics_survey_responses where is_complete = true`;",
    "    const connections = await sql`select count(*)::int as c from analytics_events where activity_type = 'connection_made'`;",
    "    const active30 = await sql`select count(distinct user_id)::int as c from analytics_events where created_at >= ${day30}`;",
    "    return {",
    "      users: {",
    "        total: Number(totalUsers[0]?.c || 0),",
    "        newLast30Days: Number(new30[0]?.c || 0),",
    "        newLast7Days: Number(new7[0]?.c || 0)",
    "      },",
    "      content: {",
    "        events: Number(totalEvents[0]?.c || 0),",
    "        surveysCompleted: Number(surveys[0]?.c || 0),",
    "        connectionsMade: Number(connections[0]?.c || 0)",
    "      },",
    "      engagement: {",
    "        activeLast30Days: Number(active30[0]?.c || 0),",
    "        totalEvents: Number(totalEvents[0]?.c || 0)",
    "      },",
    "      generatedAt: new Date().toISOString()",
    "    };",
    "  } catch {",
    "    return fallbackOverview;",
    "  }",
    "}",
    "",
    "// ---- growth (ported from reporting.py /user-growth) ------------------------",
    "// Aggregate events by YYYY-MM-DD, build a cumulative running total, and compute",
    "// a growth-rate percent = (last 7 days - first 7 days) / max(first, 1) * 100.",
    "",
    "function buildGrowth(dates: string[], periodDays: number): UserGrowth {",
    "  const daily = new Map<string, number>();",
    "  for (const iso of dates) {",
    "    const key = (iso || \"\").slice(0, 10);",
    "    if (!key) continue;",
    "    daily.set(key, (daily.get(key) || 0) + 1);",
    "  }",
    "  const sorted = Array.from(daily.entries()).sort((a, b) => (a[0] < b[0] ? -1 : 1));",
    "  let cumulative = 0;",
    "  const dailyData: Array<{ date: string; newEvents: number; cumulative: number }> = [];",
    "  for (const [date, count] of sorted) {",
    "    cumulative += count;",
    "    dailyData.push({ date, newEvents: count, cumulative });",
    "  }",
    "  let growthRate = 0;",
    "  if (dailyData.length >= 2) {",
    "    const firstWeek = dailyData.slice(0, 7).reduce((s, d) => s + d.newEvents, 0);",
    "    const lastWeek = dailyData.slice(-7).reduce((s, d) => s + d.newEvents, 0);",
    "    growthRate = ((lastWeek - firstWeek) / Math.max(firstWeek, 1)) * 100;",
    "  }",
    "  return {",
    "    periodDays,",
    "    totalNewEvents: dates.length,",
    "    growthRatePercent: Math.round(growthRate * 10) / 10,",
    "    dailyData",
    "  };",
    "}",
    "",
    "export async function getGrowth(days = 30): Promise<UserGrowth> {",
    "  const periodDays = Math.min(365, Math.max(7, days));",
    "  if (!hasDatabase()) {",
    "    return buildGrowth(fallbackEvents.map((e) => e.createdAt), periodDays);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const start = isoDaysAgo(periodDays);",
    "    const rows = await sql`select created_at from analytics_events where created_at >= ${start} order by created_at asc limit 5000`;",
    "    return buildGrowth(rows.map((r) => String(r.created_at || \"\")), periodDays);",
    "  } catch {",
    "    return buildGrowth([], periodDays);",
    "  }",
    "}",
    "",
    "// ---- engagement (ported from user_analytics.py /engagement) ----------------",
    "",
    "export async function getEngagement(days = 30): Promise<EngagementReport> {",
    "  const periodDays = Math.min(365, Math.max(1, days));",
    "  if (!hasDatabase()) {",
    "    const features = buildFeatureUsage(fallbackEvents, isoDaysAgo(periodDays));",
    "    return {",
    "      periodDays,",
    "      features,",
    "      topFeatures: [...features].sort((a, b) => b.totalActions - a.totalActions),",
    "      engagementRate: { daily: 66.7, weekly: 100, monthly: 100 }",
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const cutoff = isoDaysAgo(periodDays);",
    "    // total_actions + unique_users per activity_type, ported from the aggregate.",
    "    const rows = await sql`",
    "      select activity_type,",
    "        count(*)::int as total_actions,",
    "        count(distinct user_id)::int as unique_users",
    "      from analytics_events",
    "      where created_at >= ${cutoff}",
    "      group by activity_type",
    "      order by total_actions desc`;",
    "    const features: FeatureUsage[] = rows.map((r) => ({",
    '      activityType: String(r.activity_type || "unknown"),',
    "      totalActions: Number(r.total_actions || 0),",
    "      uniqueUsers: Number(r.unique_users || 0)",
    "    }));",
    "    // engagement_rate = active / total * 100 at three windows.",
    "    const totalUsersRows = await sql`select count(*)::int as c from users`;",
    "    const totalUsers = Number(totalUsersRows[0]?.c || 0);",
    "    const activeIn = async (d: number) => {",
    "      const r = await sql`select count(distinct user_id)::int as c from analytics_events where created_at >= ${isoDaysAgo(d)}`;",
    "      return Number(r[0]?.c || 0);",
    "    };",
    "    const rate = (active: number) => (totalUsers > 0 ? Math.round((active / totalUsers) * 1000) / 10 : 0);",
    "    const [d1, d7, d30] = await Promise.all([activeIn(1), activeIn(7), activeIn(30)]);",
    "    return {",
    "      periodDays,",
    "      features,",
    "      topFeatures: [...features].sort((a, b) => b.totalActions - a.totalActions).slice(0, 5),",
    "      engagementRate: { daily: rate(d1), weekly: rate(d7), monthly: rate(d30) }",
    "    };",
    "  } catch {",
    "    return { periodDays, features: [], topFeatures: [], engagementRate: { daily: 0, weekly: 0, monthly: 0 } };",
    "  }",
    "}",
    "",
    "function buildFeatureUsage(events: ActivityEvent[], cutoffIso: string): FeatureUsage[] {",
    "  const byType = new Map<string, { total: number; users: Set<string> }>();",
    "  for (const e of events) {",
    "    if (e.createdAt < cutoffIso) continue;",
    "    const bucket = byType.get(e.activityType) || { total: 0, users: new Set<string>() };",
    "    bucket.total += 1;",
    "    bucket.users.add(e.userId);",
    "    byType.set(e.activityType, bucket);",
    "  }",
    "  return Array.from(byType.entries())",
    "    .map(([activityType, v]) => ({ activityType, totalActions: v.total, uniqueUsers: v.users.size }))",
    "    .sort((a, b) => b.totalActions - a.totalActions);",
    "}",
    "",
    "// ---- surveys (ported from SurveyAnalytics.tsx generateInsights) ------------",
    "",
    "export type SurveyRow = { id: string; title: string; appSlug: string };",
    "",
    "type QuestionRow = { id: string; question_text: string; question_type: string };",
    "type AnswerRow = { question_id: string; answer_text: string };",
    "",
    "// Port of generateInsights: choice distribution + mostCommon %, numeric",
    "// average/median/min/max, and the avg < 3 'needs attention' flag.",
    "export function computeInsights(",
    "  surveyId: string,",
    "  title: string,",
    "  questions: QuestionRow[],",
    "  answers: AnswerRow[]",
    "): SurveyInsights {",
    "  const insights: QuestionInsight[] = [];",
    "  const unusual: SurveyInsights[\"unusual\"] = [];",
    "",
    "  for (const question of questions) {",
    "    const qAnswers = answers.filter((a) => a.question_id === question.id);",
    "    const type = (question.question_type || \"\").toLowerCase();",
    "",
    '    if (type === "multiple_choice" || type === "yes_no" || type === "choice") {',
    "      const distribution: Record<string, number> = {};",
    "      for (const a of qAnswers) {",
    '        const answer = (a.answer_text || "No response").trim() || "No response";',
    "        distribution[answer] = (distribution[answer] || 0) + 1;",
    "      }",
    "      const total = qAnswers.length;",
    "      const entries = Object.entries(distribution).sort((a, b) => b[1] - a[1]);",
    "      const top = entries[0];",
    "      insights.push({",
    '        type: "choice",',
    "        questionId: question.id,",
    "        questionText: question.question_text,",
    "        totalResponses: total,",
    "        distribution,",
    "        mostCommon: top",
    "          ? { answer: top[0], count: top[1], percentage: total ? ((top[1] / total) * 100).toFixed(1) : \"0.0\" }",
    "          : null",
    "      });",
    '    } else if (type === "rating" || type === "scale") {',
    "      const values = qAnswers.map((a) => parseFloat(a.answer_text)).filter((v) => !Number.isNaN(v));",
    "      if (values.length === 0) {",
    '        insights.push({ type: "numeric", questionId: question.id, questionText: question.question_text, totalResponses: 0, average: "0.0", median: 0, min: 0, max: 0, needsAttention: false });',
    "        continue;",
    "      }",
    "      const avg = values.reduce((s, v) => s + v, 0) / values.length;",
    "      const sortedVals = [...values].sort((a, b) => a - b);",
    "      const median = sortedVals[Math.floor(sortedVals.length / 2)];",
    "      const needsAttention = avg < 3;",
    "      insights.push({",
    '        type: "numeric",',
    "        questionId: question.id,",
    "        questionText: question.question_text,",
    "        totalResponses: values.length,",
    "        average: avg.toFixed(1),",
    "        median,",
    "        min: Math.min(...values),",
    "        max: Math.max(...values),",
    "        needsAttention",
    "      });",
    "      if (needsAttention) {",
    "        unusual.push({",
    "          questionId: question.id,",
    "          questionText: question.question_text,",
    "          message: `Low average rating (${avg.toFixed(1)}/5) — may need attention`",
    "        });",
    "      }",
    "    }",
    "  }",
    "  return { surveyId, title, totalResponses: questions.length ? Math.max(...questions.map((q) => answers.filter((a) => a.question_id === q.id).length), 0) : 0, questions: insights, unusual };",
    "}",
    "",
    "const fallbackSurvey: SurveyRow = { id: \"sample-survey\", title: \"Belonging check-in\", appSlug: \"wellbeing\" };",
    "const fallbackQuestions: QuestionRow[] = [",
    '  { id: "q1", question_text: "I feel a sense of belonging here.", question_type: "scale" },',
    '  { id: "q2", question_text: "I have hope about the season ahead.", question_type: "scale" },',
    '  { id: "q3", question_text: "Would you recommend this to a friend?", question_type: "yes_no" }',
    "];",
    "const fallbackAnswers: AnswerRow[] = [",
    '  { question_id: "q1", answer_text: "4" },',
    '  { question_id: "q1", answer_text: "5" },',
    '  { question_id: "q1", answer_text: "3" },',
    '  { question_id: "q2", answer_text: "4" },',
    '  { question_id: "q2", answer_text: "5" },',
    '  { question_id: "q3", answer_text: "Yes" },',
    '  { question_id: "q3", answer_text: "Yes" },',
    '  { question_id: "q3", answer_text: "No" }',
    "];",
    "",
    "export async function listSurveys(): Promise<SurveyRow[]> {",
    "  if (!hasDatabase()) return [fallbackSurvey];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, title, app_slug from analytics_surveys order by created_at desc limit 100`;",
    '    return rows.map((r) => ({ id: String(r.id), title: String(r.title || "Survey"), appSlug: String(r.app_slug || "app") }));',
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function getSurveyInsights(surveyId: string): Promise<SurveyInsights | null> {",
    "  if (!hasDatabase()) {",
    "    if (surveyId !== fallbackSurvey.id) return null;",
    "    return computeInsights(fallbackSurvey.id, fallbackSurvey.title, fallbackQuestions, fallbackAnswers);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const surveyRows = await sql`select id, title from analytics_surveys where id = ${surveyId} limit 1`;",
    "    if (!surveyRows[0]) return null;",
    "    const questions = await sql`select id, question_text, question_type from analytics_survey_questions where survey_id = ${surveyId} order by position asc`;",
    "    const answers = await sql`",
    "      select a.question_id, a.answer_text",
    "      from analytics_survey_answers a",
    "      join analytics_survey_responses r on r.id = a.response_id",
    "      where r.survey_id = ${surveyId} and r.is_complete = true`;",
    "    return computeInsights(",
    "      surveyId,",
    '      String(surveyRows[0].title || "Survey"),',
    '      questions.map((q) => ({ id: String(q.id), question_text: String(q.question_text || ""), question_type: String(q.question_type || "text") })),',
    '      answers.map((a) => ({ question_id: String(a.question_id || ""), answer_text: String(a.answer_text || "") }))',
    "    );",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- hope / belonging index (cross-app synthesis of scale answers) ---------",
    "// Every scale answer is normalized to 0..100 assuming a 1..5 Likert: (v-1)/4*100.",
    "// The overall index is the mean of those; byApp groups the same math per app.",
    "",
    "export function normalizeScale(value: number, min = 1, max = 5): number {",
    "  if (max <= min) return 0;",
    "  const clamped = Math.min(max, Math.max(min, value));",
    "  return Math.round(((clamped - min) / (max - min)) * 100);",
    "}",
    "",
    "export async function getHopeIndex(): Promise<HopeIndex> {",
    "  if (!hasDatabase()) return fallbackHope;",
    "  try {",
    "    const sql = getDatabase();",
    "    // Pull every numeric scale/rating answer with its survey's app, ported in",
    "    // spirit from the SurveyAnalytics numeric branch, then normalize + average.",
    "    const rows = await sql`",
    "      select s.app_slug as app_slug, a.answer_text as answer_text",
    "      from analytics_survey_answers a",
    "      join analytics_survey_responses r on r.id = a.response_id",
    "      join analytics_surveys s on s.id = r.survey_id",
    "      join analytics_survey_questions q on q.id = a.question_id",
    "      where r.is_complete = true and q.question_type in ('scale', 'rating')",
    "      limit 20000`;",
    "    const perApp = new Map<string, { sum: number; count: number }>();",
    "    let sum = 0;",
    "    let count = 0;",
    "    for (const row of rows) {",
    "      const v = parseFloat(String(row.answer_text));",
    "      if (Number.isNaN(v)) continue;",
    "      const score = normalizeScale(v);",
    '      const app = String(row.app_slug || "app");',
    "      const bucket = perApp.get(app) || { sum: 0, count: 0 };",
    "      bucket.sum += score;",
    "      bucket.count += 1;",
    "      perApp.set(app, bucket);",
    "      sum += score;",
    "      count += 1;",
    "    }",
    "    const overall = count ? Math.round(sum / count) : 0;",
    "    const byApp = Array.from(perApp.entries())",
    "      .map(([appSlug, v]) => ({ appSlug, score: v.count ? Math.round(v.sum / v.count) : 0, responseCount: v.count }))",
    "      .sort((a, b) => b.responseCount - a.responseCount);",
    "    return { overall, responseCount: count, byApp, band: hopeBand(overall) };",
    "  } catch {",
    "    return fallbackHope;",
    "  }",
    "}",
    "",
    "export function analyticsEnabled(): boolean {",
    '  return process.env.FEATURE_ANALYTICS !== "false";',
    "}"
  ]);
}

// ---- src/app/api/analytics/route.ts (overview + growth + engagement) ---------

function analyticsApiFile(): GeneratedModuleFile {
  return file("src/app/api/analytics/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getOverview, getGrowth, getEngagement, getHopeIndex, analyticsEnabled } from "@/lib/db/analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!analyticsEnabled()) return NextResponse.json({ ok: false, message: "Analytics is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const days = Number(url.searchParams.get("days") || 30);',
    "  const [overview, growth, engagement, hope] = await Promise.all([",
    "    getOverview(),",
    "    getGrowth(Number.isFinite(days) ? days : 30),",
    "    getEngagement(Number.isFinite(days) ? days : 30),",
    "    getHopeIndex()",
    "  ]);",
    "  return NextResponse.json({ ok: true, overview, growth, engagement, hope });",
    "}"
  ]);
}

// ---- src/app/api/analytics/track/route.ts (ported from /track) --------------

function trackApiFile(): GeneratedModuleFile {
  return file("src/app/api/analytics/track/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { logActivity, analyticsEnabled } from "@/lib/db/analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Ported from user_analytics.py /track: any signed-in user can log their own",
    "// activity event (activity_type + details).",
    "export async function POST(request: Request) {",
    '  if (!analyticsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const activityType = typeof body.activityType === "string" ? body.activityType.trim() : "";',
    '  if (!activityType) return NextResponse.json({ ok: false, message: "An activity type is required." }, { status: 400 });',
    '  const appSlug = typeof body.appSlug === "string" && body.appSlug.trim() ? body.appSlug.trim() : "app";',
    '  const details = body.details && typeof body.details === "object" ? (body.details as Record<string, unknown>) : {};',
    '  const saved = await logActivity(String(user?.email || ""), appSlug, activityType, details);',
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to record activity." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/analytics/surveys/[id]/route.ts ----------------------------

function surveyApiFile(): GeneratedModuleFile {
  return file("src/app/api/analytics/surveys/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getSurveyInsights, analyticsEnabled } from "@/lib/db/analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!analyticsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const insights = await getSurveyInsights(id);",
    '  if (!insights) return NextResponse.json({ ok: false, message: "Survey not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, insights });",
    "}"
  ]);
}

// ---- src/app/analytics/page.tsx (dashboard: overview + engagement + hope) ----

function analyticsPageFile(): GeneratedModuleFile {
  return file("src/app/analytics/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getOverview, getGrowth, getEngagement, getHopeIndex, listSurveys, analyticsEnabled } from "@/lib/db/analytics";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AnalyticsPage() {",
    "  if (!analyticsEnabled()) {",
    '    return (<main className="shell"><h1>Analytics</h1><p>Analytics is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/analytics");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const [overview, growth, engagement, hope, surveys] = await Promise.all([",
    "    getOverview(),",
    "    getGrowth(30),",
    "    getEngagement(30),",
    "    getHopeIndex(),",
    "    listSurveys()",
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Analytics</p>',
    "      <h1>Reporting & the hope index</h1>",
    "      <p>How people are engaging — and how much hope and belonging your surveys are measuring across every app.</p>",
    "",
    '      <section className="panel">',
    "        <p className=\"eyebrow\">Hope & belonging index</p>",
    "        <h2>{hope.overall}<span className=\"note\"> / 100 · {hope.band}</span></h2>",
    "        <p className=\"note\">Across {hope.responseCount} scale response{hope.responseCount === 1 ? \"\" : \"s\"}.</p>",
    "        {hope.byApp.length > 0 ? (",
    '          <div className="panel-list">',
    "            {hope.byApp.map((row) => (",
    '              <article className="wide-card" key={row.appSlug}>',
    "                <span>{row.responseCount} response{row.responseCount === 1 ? \"\" : \"s\"}</span>",
    "                <strong>{row.appSlug}</strong>",
    "                <p>{row.score} / 100</p>",
    "              </article>",
    "            ))}",
    "          </div>",
    "        ) : null}",
    "      </section>",
    "",
    '      <section className="grid">',
    '        <article className="card"><span>People</span><strong>{overview.users.total}</strong></article>',
    '        <article className="card"><span>New (30 days)</span><strong>{overview.users.newLast30Days}</strong></article>',
    '        <article className="card"><span>Active (30 days)</span><strong>{overview.engagement.activeLast30Days}</strong></article>',
    '        <article className="card"><span>Surveys completed</span><strong>{overview.content.surveysCompleted}</strong></article>',
    "      </section>",
    "",
    '      <section className="grid">',
    '        <article className="card"><span>Daily engagement</span><strong>{engagement.engagementRate.daily}%</strong></article>',
    '        <article className="card"><span>Weekly engagement</span><strong>{engagement.engagementRate.weekly}%</strong></article>',
    '        <article className="card"><span>Monthly engagement</span><strong>{engagement.engagementRate.monthly}%</strong></article>',
    '        <article className="card"><span>Growth (30 days)</span><strong>{growth.growthRatePercent}%</strong></article>',
    "      </section>",
    "",
    "      <h2>Top features</h2>",
    "      {engagement.topFeatures.length === 0 ? (",
    '        <p className="note">No activity recorded yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {engagement.topFeatures.map((f) => (",
    '            <article className="wide-card" key={f.activityType}>',
    "              <span>{f.uniqueUsers} {f.uniqueUsers === 1 ? \"person\" : \"people\"}</span>",
    "              <strong>{f.activityType}</strong>",
    "              <p>{f.totalActions} action{f.totalActions === 1 ? \"\" : \"s\"}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Surveys</h2>",
    "      {surveys.length === 0 ? (",
    '        <p className="note">No surveys yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {surveys.map((s) => (",
    '            <Link className="wide-card" key={s.id} href={`/analytics/surveys/${s.id}`}>',
    "              <span>{s.appSlug}</span>",
    "              <strong>{s.title}</strong>",
    "              <p>View responses &amp; insights</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      {isAdmin ? <p className=\"note\">You are viewing the full admin dashboard.</p> : null}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/analytics/surveys/[id]/page.tsx (ported from SurveyAnalytics.tsx) -

function surveyPageFile(): GeneratedModuleFile {
  return file("src/app/analytics/surveys/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getSurveyInsights, analyticsEnabled } from "@/lib/db/analytics";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SurveyInsightsPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!analyticsEnabled()) {",
    '    return (<main className="shell"><h1>Analytics</h1><p>Analytics is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/analytics");',
    "  const { id } = await params;",
    "  const insights = await getSurveyInsights(id);",
    "  if (!insights) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Survey analytics</p>',
    "      <h1>{insights.title}</h1>",
    "      <p className=\"note\">Survey analytics &amp; insights.</p>",
    "",
    "      {insights.unusual.length > 0 ? (",
    '        <section className="panel">',
    "          <p className=\"eyebrow\">Interesting findings</p>",
    "          <ul>",
    "            {insights.unusual.map((u) => (",
    "              <li key={u.questionId}><strong>{u.questionText}</strong> — {u.message}</li>",
    "            ))}",
    "          </ul>",
    "        </section>",
    "      ) : null}",
    "",
    "      <h2>Question analysis</h2>",
    "      {insights.questions.length === 0 ? (",
    '        <p className="note">No answerable questions in this survey yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {insights.questions.map((q) => (",
    '            <article className="panel" key={q.questionId}>',
    "              <h3>{q.questionText}</h3>",
    "              <p className=\"note\">{q.totalResponses} response{q.totalResponses === 1 ? \"\" : \"s\"}</p>",
    '              {q.type === "choice" ? (',
    "                <div className=\"stack\">",
    "                  {Object.entries(q.distribution).map(([answer, count]) => {",
    "                    const pct = q.totalResponses ? ((count / q.totalResponses) * 100).toFixed(1) : \"0.0\";",
    "                    return (",
    '                      <div key={answer}>',
    "                        <p><span>{answer}</span> — <strong>{count} ({pct}%)</strong></p>",
    '                        <div className="meter" aria-hidden="true"><div className="meter-fill" style={{ width: `${pct}%` }} /></div>',
    "                      </div>",
    "                    );",
    "                  })}",
    "                  {q.mostCommon ? (",
    "                    <p className=\"note\">Most common: &ldquo;{q.mostCommon.answer}&rdquo; ({q.mostCommon.percentage}% of responses)</p>",
    "                  ) : null}",
    "                </div>",
    "              ) : (",
    '                <section className="grid">',
    '                  <article className="card"><span>Average</span><strong>{q.average}</strong></article>',
    '                  <article className="card"><span>Median</span><strong>{q.median}</strong></article>',
    '                  <article className="card"><span>Lowest</span><strong>{q.min}</strong></article>',
    '                  <article className="card"><span>Highest</span><strong>{q.max}</strong></article>',
    "                </section>",
    "              )}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/analytics">Back to analytics</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const analyticsHopeModule: AppModule = {
  slug: "analytics-hope-index",
  name: "Analytics & Hope Index",
  tier: "optional",
  featureFlagEnv: "FEATURE_ANALYTICS",
  files: () => [
    analyticsLibFile(),
    analyticsApiFile(),
    trackApiFile(),
    surveyApiFile(),
    analyticsPageFile(),
    surveyPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists analytics_events (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete set null,",
      "  app_slug text not null default 'app',",
      "  activity_type text not null,",
      "  details jsonb not null default '{}'::jsonb,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists analytics_events_type_idx on analytics_events (activity_type);",
      "create index if not exists analytics_events_created_idx on analytics_events (created_at);",
      "create index if not exists analytics_events_user_idx on analytics_events (user_id);",
      "",
      "create table if not exists analytics_surveys (",
      "  id uuid primary key default gen_random_uuid(),",
      "  title text not null default 'Survey',",
      "  app_slug text not null default 'app',",
      "  created_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now()",
      ");",
      "",
      "create table if not exists analytics_survey_questions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  survey_id uuid not null references analytics_surveys(id) on delete cascade,",
      "  question_text text not null default '',",
      "  question_type text not null default 'text',",
      "  position integer not null default 0",
      ");",
      "create index if not exists analytics_survey_questions_survey_idx on analytics_survey_questions (survey_id);",
      "",
      "create table if not exists analytics_survey_responses (",
      "  id uuid primary key default gen_random_uuid(),",
      "  survey_id uuid not null references analytics_surveys(id) on delete cascade,",
      "  user_id uuid references users(id) on delete set null,",
      "  is_complete boolean not null default false,",
      "  completed_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists analytics_survey_responses_survey_idx on analytics_survey_responses (survey_id);",
      "",
      "create table if not exists analytics_survey_answers (",
      "  id uuid primary key default gen_random_uuid(),",
      "  response_id uuid not null references analytics_survey_responses(id) on delete cascade,",
      "  question_id uuid not null references analytics_survey_questions(id) on delete cascade,",
      "  answer_text text not null default ''",
      ");",
      "create index if not exists analytics_survey_answers_response_idx on analytics_survey_answers (response_id);",
      "create index if not exists analytics_survey_answers_question_idx on analytics_survey_answers (question_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into analytics_surveys (id, title, app_slug) values",
      "  ('00000000-0000-0000-0000-0000000a0001', 'Belonging check-in', 'wellbeing')",
      "on conflict do nothing;",
      "",
      "insert into analytics_survey_questions (id, survey_id, question_text, question_type, position) values",
      "  ('00000000-0000-0000-0000-0000000b0001', '00000000-0000-0000-0000-0000000a0001', 'I feel a sense of belonging here.', 'scale', 0),",
      "  ('00000000-0000-0000-0000-0000000b0002', '00000000-0000-0000-0000-0000000a0001', 'I have hope about the season ahead.', 'scale', 1),",
      "  ('00000000-0000-0000-0000-0000000b0003', '00000000-0000-0000-0000-0000000a0001', 'Would you recommend this to a friend?', 'yes_no', 2)",
      "on conflict do nothing;",
      "",
      "insert into analytics_survey_responses (id, survey_id, is_complete, completed_at) values",
      "  ('00000000-0000-0000-0000-0000000c0001', '00000000-0000-0000-0000-0000000a0001', true, now())",
      "on conflict do nothing;",
      "",
      "insert into analytics_survey_answers (response_id, question_id, answer_text) values",
      "  ('00000000-0000-0000-0000-0000000c0001', '00000000-0000-0000-0000-0000000b0001', '4'),",
      "  ('00000000-0000-0000-0000-0000000c0001', '00000000-0000-0000-0000-0000000b0002', '5'),",
      "  ('00000000-0000-0000-0000-0000000c0001', '00000000-0000-0000-0000-0000000b0003', 'Yes')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Analytics & Hope Index — set to false to switch reporting + surveys + the hope index off.",
    "FEATURE_ANALYTICS=true"
  ],
  homeLinks: () => ['        <a className="button" href="/analytics">Analytics</a>'],
  navLinks: () => [{ href: "/analytics", label: "Analytics" }]
};
