// asset-claim — a generic "claim this thing, tell us where it goes, then check on
// it without an account" capability, generalized from the toner-management-app
// printer claim + delivery + status-token pattern shipped 2026-07-10 (claim-core.ts,
// routes/claim/{printer,status}.ts, migrations 0004 + 0008). The printer becomes any
// tracked asset; the four primitives carry over unchanged: an admin mints a per-asset
// claim (single-use token + human 8-hex code + /claim/{token} URL), a public visitor
// opens that URL to claim the asset and record where it should go, and a persistent
// read-only status token lets them bookmark /my-asset/{token} to see status — scoped
// to only their asset, no cost or other-user data ever returned.
//
// The on-device-print piece (streaming a claim sheet to a printer's raw ip:9100 so the
// code emerges from the RIGHT machine) is deliberately NOT here: it needs an on-site
// polling agent + a device with an IP, which fleet-monitoring-agent already owns, and
// the modules-registry smoke forbids cross-module FKs. asset-claim carries only a soft,
// DB-decoupled hook (asset_claim_assets.on_device_ref — a device id string, not an FK)
// so the two compose when both are present. Standalone, the printed card is the path.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/asset-claim/tokens.ts (pure, node:crypto, server-only) ----------

function tokensFile(): GeneratedModuleFile {
  return file("src/lib/asset-claim/tokens.ts", [
    "// Pure, dependency-free claim/status token helpers (mirrors the toner app's",
    "// claim-core + print-payload split). Server-only: it uses node:crypto, so it",
    "// must never be pulled into a client bundle.",
    'import { randomBytes, createHash } from "node:crypto";',
    "",
    "// The single-use claim token (in /claim/{token}) and the persistent read-only",
    "// status token (in /my-asset/{token}) are minted the same way but stored as",
    "// separate sha256 hashes — the plaintext only ever lives in the URL.",
    'export function mintToken(prefix = "ac"): string {',
    '  return `${prefix}_${randomBytes(24).toString("base64url")}`;',
    "}",
    "",
    "export function hashToken(token: string): string {",
    '  return createHash("sha256").update(token.trim()).digest("hex");',
    "}",
    "",
    "// Human-readable 8-hex code that prints on the claim card, so a person standing",
    "// at the asset can match the card to the right one even among identical units.",
    "export function uniqueClaimCode(): string {",
    '  return randomBytes(4).toString("hex").toUpperCase();',
    "}",
    "",
    "// Public origin for claim/status links. Set APP_URL (or AUTH_URL) so printed",
    "// links are absolute; falls back to a relative path otherwise.",
    "export function siteOrigin(): string {",
    '  return (process.env.APP_URL || process.env.AUTH_URL || "").replace(/\\/$/, "");',
    "}",
    "",
    "export function buildClaimUrl(token: string): string {",
    "  return `${siteOrigin()}/claim/${encodeURIComponent(token)}`;",
    "}",
    "",
    "export function buildStatusUrl(token: string): string {",
    "  return `${siteOrigin()}/my-asset/${encodeURIComponent(token)}`;",
    "}"
  ]);
}

// ---- src/lib/db/asset-claim.ts (model, queries) ------------------------------

function dbLibFile(): GeneratedModuleFile {
  return file("src/lib/db/asset-claim.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    'import { buildClaimUrl, buildStatusUrl, hashToken, mintToken, uniqueClaimCode } from "@/lib/asset-claim/tokens";',
    "",
    "type Sql = ReturnType<typeof getDatabase>;",
    "",
    "export function assetClaimEnabled(): boolean {",
    '  return process.env.FEATURE_ASSET_CLAIM !== "false";',
    "}",
    "",
    '// Kept in sync with the ASSET_TYPES list the console offers. "asset" is the',
    "// neutral catch-all so the module reads for anything, not just devices.",
    'export const ASSET_TYPES = ["device", "equipment", "item", "room", "vehicle", "asset"] as const;',
    "export const ASSET_TYPE_LABELS: Record<string, string> = {",
    '  device: "Device",',
    '  equipment: "Equipment",',
    '  item: "Item",',
    '  room: "Room",',
    '  vehicle: "Vehicle",',
    '  asset: "Asset"',
    "};",
    "",
    "export type AssetClaimClaim = { id: string; code: string; url: string; status: string; expiresAt: string };",
    "export type AssetClaimAsset = {",
    "  id: string;",
    "  name: string;",
    "  assetType: string;",
    "  identifier: string;",
    "  status: string;",
    "  assignedLabel: string;",
    "  claim: AssetClaimClaim | null;",
    "};",
    "",
    "export type ClaimDetail = {",
    "  claimCode: string;",
    "  status: string;",
    "  expiresAt: string;",
    "  claimedAt: string | null;",
    "  canClaim: boolean;",
    "  asset: { id: string; name: string; assetType: string; identifier: string };",
    "  organizationName: string;",
    "};",
    "",
    "export type ClaimSubmission = {",
    "  name: string;",
    "  email?: string;",
    "  building?: string;",
    "  floor?: string;",
    "  room?: string;",
    "  spot?: string;",
    "  department?: string;",
    "  deliveryInstructions?: string;",
    "};",
    "",
    "export type AssetStatus = {",
    "  claimed: boolean;",
    "  assetName: string;",
    "  assetType: string;",
    "  identifier: string;",
    "  organizationName: string;",
    "  claimedByName: string | null;",
    "  claimedAt: string | null;",
    "  status: string;",
    "  onDevice: boolean;",
    "  destination:",
    "    | { building: string | null; floor: string | null; room: string | null; spot: string | null; department: string | null; deliveryInstructions: string | null }",
    "    | null;",
    "  claimUrl: string | null;",
    "};",
    "",
    "// db-less previews render this sample so the console is never blank in dev.",
    "const fallbackAssets: AssetClaimAsset[] = [",
    '  { id: "sample-asset-1", name: "Sample asset", assetType: "equipment", identifier: "SAMPLE-001", status: "unclaimed", assignedLabel: "", claim: null }',
    "];",
    "",
    "// Best-effort audit into the base audit_events table; never blocks the action.",
    "async function audit(sql: Sql, organizationId: unknown, eventType: string): Promise<void> {",
    "  try {",
    "    await sql`insert into audit_events (organization_id, event_type) values (${organizationId}, ${eventType})`;",
    "  } catch {",
    "    // audit is best-effort",
    "  }",
    "}",
    "",
    "// Owner view: every asset with its latest still-open claim (code + link).",
    "export async function listAssets(): Promise<AssetClaimAsset[]> {",
    "  if (!hasDatabase()) return fallbackAssets;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select a.id, a.name, a.asset_type, a.identifier, a.status, coalesce(a.assigned_label, '') as assigned_label,",
    "             c.id as claim_id, c.claim_code, c.claim_url, c.status as claim_status, c.expires_at",
    "      from asset_claim_assets a",
    "      left join lateral (",
    "        select id, claim_code, claim_url, status, expires_at",
    "        from asset_claim_claims",
    "        where asset_id = a.id and status in ('pending', 'claimed')",
    "        order by created_at desc",
    "        limit 1",
    "      ) c on true",
    "      order by a.created_at desc",
    "      limit 500`;",
    "    return rows.map((row: Record<string, unknown>) => ({",
    "      id: String(row.id),",
    '      name: String(row.name || ""),',
    '      assetType: String(row.asset_type || "asset"),',
    '      identifier: String(row.identifier || ""),',
    '      status: String(row.status || "unclaimed"),',
    '      assignedLabel: String(row.assigned_label || ""),',
    "      claim: row.claim_id",
    '        ? { id: String(row.claim_id), code: String(row.claim_code || ""), url: String(row.claim_url || ""), status: String(row.claim_status || ""), expiresAt: String(row.expires_at || "") }',
    "        : null",
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// New assets attach to the first organization (single-org is the common shape",
    "// for these internal tools); returns false when there is no DB or no org yet.",
    "export async function createAsset(input: { name: string; assetType: string; identifier?: string }): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const orgRows = await sql`select id from organizations order by created_at asc limit 1`;",
    "  const organizationId = orgRows[0]?.id;",
    "  if (!organizationId) return false;",
    '  const assetType = (ASSET_TYPES as readonly string[]).includes(input.assetType) ? input.assetType : "asset";',
    "  await sql`insert into asset_claim_assets (organization_id, name, asset_type, identifier) values (${organizationId}, ${input.name}, ${assetType}, ${input.identifier || null})`;",
    "  return true;",
    "}",
    "",
    "// Mint a fresh single-use claim for an asset. The plaintext token is returned",
    "// once (only its hash is stored) so the caller can render the card + link + code.",
    "export async function createClaim(assetId: string): Promise<{ code: string; url: string; token: string } | null> {",
    "  if (!hasDatabase()) return null;",
    "  const sql = getDatabase();",
    "  const assetRows = await sql`select id, organization_id from asset_claim_assets where id = ${assetId} limit 1`;",
    "  const asset = assetRows[0];",
    "  if (!asset) return null;",
    '  const token = mintToken("ac");',
    "  const code = uniqueClaimCode();",
    "  const url = buildClaimUrl(token);",
    "  await sql`",
    "    insert into asset_claim_claims (organization_id, asset_id, claim_token_hash, claim_code, claim_url)",
    "    values (${asset.organization_id}, ${assetId}, ${hashToken(token)}, ${code}, ${url})`;",
    '  await audit(sql, asset.organization_id, "asset_claim_created");',
    "  return { code, url, token };",
    "}",
    "",
    "// Public read of one claim by its single-use token — enough to render the page.",
    "export async function getClaimByToken(token: string): Promise<ClaimDetail | null> {",
    "  if (!token) return null;",
    "  if (!hasDatabase()) {",
    "    return {",
    '      claimCode: "SAMPLE00", status: "pending", expiresAt: "", claimedAt: null, canClaim: true,',
    '      asset: { id: "sample-asset-1", name: "Sample asset", assetType: "equipment", identifier: "SAMPLE-001" }, organizationName: ""',
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select c.claim_code, c.status, c.expires_at, c.claimed_at,",
    "             a.id as asset_id, a.name as asset_name, a.asset_type, coalesce(a.identifier, '') as identifier,",
    "             coalesce(o.name, '') as organization_name",
    "      from asset_claim_claims c",
    "      join asset_claim_assets a on a.id = c.asset_id",
    "      left join organizations o on o.id = c.organization_id",
    "      where c.claim_token_hash = ${hashToken(token)}",
    "      limit 1`;",
    "    const row = rows[0];",
    "    if (!row) return null;",
    '    const open = row.status === "pending" && (!row.expires_at || new Date(String(row.expires_at)).getTime() > Date.now());',
    "    return {",
    '      claimCode: String(row.claim_code || ""),',
    '      status: String(row.status || ""),',
    '      expiresAt: String(row.expires_at || ""),',
    "      claimedAt: row.claimed_at ? String(row.claimed_at) : null,",
    "      canClaim: Boolean(open),",
    '      asset: { id: String(row.asset_id), name: String(row.asset_name || ""), assetType: String(row.asset_type || "asset"), identifier: String(row.identifier || "") },',
    '      organizationName: String(row.organization_name || "")',
    "    };",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Public claim submission: records the destination, assigns the asset, writes",
    "// history, and mints the persistent read-only status token. Anonymous claimants",
    "// are captured as plain name/email columns — never inserted into the auth users",
    "// table. Returns null when the claim is already closed or expired.",
    "export async function submitClaim(token: string, input: ClaimSubmission): Promise<{ statusUrl: string; statusToken: string } | null> {",
    "  if (!token || !hasDatabase()) return null;",
    "  const sql = getDatabase();",
    "  const claimRows = await sql`",
    "    select id, organization_id, asset_id, status, expires_at",
    "    from asset_claim_claims",
    "    where claim_token_hash = ${hashToken(token)}",
    "    limit 1`;",
    "  const claim = claimRows[0];",
    "  if (!claim) return null;",
    '  const open = claim.status === "pending" && (!claim.expires_at || new Date(String(claim.expires_at)).getTime() > Date.now());',
    "  if (!open) return null;",
    "",
    '  const label = [input.building, input.floor, input.room, input.spot].map((part) => (part || "").trim()).filter(Boolean).join(", ");',
    "  const locName = label || input.name;",
    '  const note = "Claimed by " + input.name;',
    "  const locationRows = await sql`",
    "    insert into asset_claim_locations (organization_id, name, building, floor, room, spot, department, contact_name, contact_email, delivery_instructions)",
    "    values (${claim.organization_id}, ${locName}, ${input.building || null}, ${input.floor || null}, ${input.room || null}, ${input.spot || null}, ${input.department || null}, ${input.name}, ${input.email || null}, ${input.deliveryInstructions || null})",
    "    returning id`;",
    "  const locationId = locationRows[0]?.id;",
    "",
    "  await sql`",
    "    update asset_claim_assets",
    "    set status = 'claimed', assigned_label = ${label || null}, location_id = ${locationId}, updated_at = now()",
    "    where id = ${claim.asset_id}`;",
    "",
    "  await sql`",
    "    insert into asset_claim_assignment_history (organization_id, asset_id, claim_id, to_location_id, change_reason, notes)",
    "    values (${claim.organization_id}, ${claim.asset_id}, ${claim.id}, ${locationId}, 'new_assignment', ${note})`;",
    "",
    '  const statusToken = mintToken("st");',
    "  await sql`",
    "    update asset_claim_claims",
    "    set status = 'claimed', claimed_by_name = ${input.name}, claimed_by_email = ${input.email || null},",
    "        claimed_at = now(), location_id = ${locationId}, status_token_hash = ${hashToken(statusToken)}, updated_at = now()",
    "    where id = ${claim.id}`;",
    "",
    '  await audit(sql, claim.organization_id, "asset_claimed");',
    "  return { statusUrl: buildStatusUrl(statusToken), statusToken };",
    "}",
    "",
    "// Persistent, read-only status. Scoped to one claim's asset; accepts the status",
    "// token, and falls back to the original claim token (the printed card is at the",
    "// asset). No billing amounts or other-asset data are ever selected or returned.",
    "export async function getAssetStatus(token: string): Promise<AssetStatus | null> {",
    "  if (!token || !hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const tokenHash = hashToken(token);",
    "    const rows = await sql`",
    "      select c.status as claim_status, c.claimed_by_name, c.claimed_at, c.status_token_hash, c.claim_url,",
    "             a.name as asset_name, a.asset_type, coalesce(a.identifier, '') as identifier, a.status as asset_status,",
    "             (a.on_device_ref is not null) as on_device,",
    "             coalesce(o.name, '') as organization_name,",
    "             l.building, l.floor, l.room, l.spot, l.department, l.delivery_instructions",
    "      from asset_claim_claims c",
    "      join asset_claim_assets a on a.id = c.asset_id",
    "      left join organizations o on o.id = c.organization_id",
    "      left join asset_claim_locations l on l.id = c.location_id",
    "      where c.status_token_hash = ${tokenHash} or c.claim_token_hash = ${tokenHash}",
    "      limit 1`;",
    "    const row = rows[0];",
    "    if (!row) return null;",
    "    if (row.status_token_hash && row.status_token_hash === tokenHash) {",
    "      await sql`update asset_claim_claims set status_token_last_used_at = now() where status_token_hash = ${tokenHash}`;",
    "    }",
    '    const claimed = row.claim_status === "claimed";',
    "    return {",
    "      claimed,",
    '      assetName: String(row.asset_name || ""),',
    '      assetType: String(row.asset_type || "asset"),',
    '      identifier: String(row.identifier || ""),',
    '      organizationName: String(row.organization_name || ""),',
    "      claimedByName: row.claimed_by_name ? String(row.claimed_by_name) : null,",
    "      claimedAt: row.claimed_at ? String(row.claimed_at) : null,",
    '      status: String(row.asset_status || ""),',
    "      onDevice: Boolean(row.on_device),",
    "      destination: claimed",
    "        ? {",
    "            building: row.building ? String(row.building) : null,",
    "            floor: row.floor ? String(row.floor) : null,",
    "            room: row.room ? String(row.room) : null,",
    "            spot: row.spot ? String(row.spot) : null,",
    "            department: row.department ? String(row.department) : null,",
    "            deliveryInstructions: row.delivery_instructions ? String(row.delivery_instructions) : null",
    "          }",
    "        : null,",
    "      claimUrl: row.claim_url ? String(row.claim_url) : null",
    "    };",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function revokeClaim(claimId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  await sql`update asset_claim_claims set status = 'revoked', updated_at = now() where id = ${claimId} and status in ('pending', 'claimed')`;",
    "  return true;",
    "}"
  ]);
}

// ---- src/app/api/asset-claim/route.ts (admin list + create asset/claim) ------

function apiRouteFile(): GeneratedModuleFile {
  return file("src/app/api/asset-claim/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { assetClaimEnabled, createAsset, createClaim, listAssets } from "@/lib/db/asset-claim";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function requireAdmin() {",
    "  const user = await getCurrentUser();",
    "  return user && canAccessAdmin(user.role) ? user : null;",
    "}",
    "",
    "export async function GET() {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    '  if (!(await requireAdmin())) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const assets = await listAssets();",
    "  return NextResponse.json({ ok: true, assets });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    '  if (!(await requireAdmin())) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const intent = typeof body.intent === "string" ? body.intent : "";',
    "",
    '  if (intent === "claim") {',
    '    const assetId = typeof body.assetId === "string" ? body.assetId : "";',
    '    if (!assetId) return NextResponse.json({ ok: false, message: "Which asset?" }, { status: 400 });',
    "    const claim = await createClaim(assetId);",
    '    if (!claim) return NextResponse.json({ ok: false, message: "Could not create a claim. Connect a database and add the asset first." }, { status: 503 });',
    "    return NextResponse.json({ ok: true, claim: { code: claim.code, url: claim.url } });",
    "  }",
    "",
    '  const name = typeof body.name === "string" ? body.name.trim().slice(0, 200) : "";',
    '  if (name.length < 2) return NextResponse.json({ ok: false, message: "Give the asset a name." }, { status: 400 });',
    "  const created = await createAsset({",
    "    name,",
    '    assetType: typeof body.assetType === "string" ? body.assetType : "asset",',
    '    identifier: typeof body.identifier === "string" ? body.identifier.trim().slice(0, 120) : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database and create an organization first." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/asset-claim/[id]/route.ts (admin revoke a claim) ------------

function apiDetailRouteFile(): GeneratedModuleFile {
  return file("src/app/api/asset-claim/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { assetClaimEnabled, revokeClaim } from "@/lib/db/asset-claim";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function PATCH(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const done = await revokeClaim(id);",
    '  if (!done) return NextResponse.json({ ok: false, message: "Connect a database first." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/claim/[token]/route.ts (public claim) -----------------------

function publicClaimApiFile(): GeneratedModuleFile {
  return file("src/app/api/claim/[token]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { assetClaimEnabled, getClaimByToken, submitClaim } from "@/lib/db/asset-claim";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ token: string }> }) {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const { token } = await params;",
    "  const claim = await getClaimByToken(token);",
    '  if (!claim) return NextResponse.json({ ok: false, message: "This claim link was not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, claim });",
    "}",
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ token: string }> }) {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const { token } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  // Honeypot: bots that fill the hidden field get a quiet yes and no row.",
    '  if (typeof body.hp === "string" && body.hp.trim().length > 0) return NextResponse.json({ ok: true });',
    '  const name = typeof body.name === "string" ? body.name.trim().slice(0, 200) : "";',
    '  if (!name) return NextResponse.json({ ok: false, message: "Please tell us your name." }, { status: 400 });',
    '  const str = (value: unknown, max: number) => (typeof value === "string" ? value.trim().slice(0, max) : undefined);',
    "  const result = await submitClaim(token, {",
    "    name,",
    "    email: str(body.email, 320),",
    "    building: str(body.building, 200),",
    "    floor: str(body.floor, 100),",
    "    room: str(body.room, 100),",
    "    spot: str(body.spot, 100),",
    "    department: str(body.department, 200),",
    "    deliveryInstructions: str(body.deliveryInstructions, 2000)",
    "  });",
    '  if (!result) return NextResponse.json({ ok: false, message: "This asset has already been claimed, or the link expired." }, { status: 409 });',
    "  return NextResponse.json({ ok: true, statusUrl: result.statusUrl });",
    "}"
  ]);
}

// ---- src/app/api/my-asset/[token]/route.ts (public read-only status) ---------

function publicStatusApiFile(): GeneratedModuleFile {
  return file("src/app/api/my-asset/[token]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { assetClaimEnabled, getAssetStatus } from "@/lib/db/asset-claim";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ token: string }> }) {",
    "  if (!assetClaimEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const { token } = await params;",
    "  const status = await getAssetStatus(token);",
    '  if (!status) return NextResponse.json({ ok: false, message: "This status link was not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, status });",
    "}"
  ]);
}

// ---- src/components/asset-claim/claim-form.tsx (client) ----------------------

function claimFormFile(): GeneratedModuleFile {
  return file("src/components/asset-claim/claim-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "export function ClaimForm({ token }: { token: string }) {",
    '  const [status, setStatus] = useState<"idle" | "sending" | "done" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    '  const [statusUrl, setStatusUrl] = useState("");',
    "",
    "  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = event.currentTarget;",
    "    const data = new FormData(form);",
    '    setStatus("sending");',
    '    setMessage("");',
    "    const response = await fetch(`/api/claim/${encodeURIComponent(token)}`, {",
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    "      body: JSON.stringify({",
    '        name: String(data.get("name") || ""),',
    '        email: String(data.get("email") || ""),',
    '        building: String(data.get("building") || ""),',
    '        floor: String(data.get("floor") || ""),',
    '        room: String(data.get("room") || ""),',
    '        spot: String(data.get("spot") || ""),',
    '        department: String(data.get("department") || ""),',
    '        deliveryInstructions: String(data.get("deliveryInstructions") || ""),',
    '        hp: String(data.get("hp") || "")',
    "      })",
    "    }).catch(() => null);",
    "    const payload = response ? await response.json().catch(() => null) : null;",
    "    if (!response || !response.ok || !payload?.ok) {",
    '      setStatus("error");',
    '      setMessage(payload?.message || "Something went wrong. Please try again.");',
    "      return;",
    "    }",
    '    setStatusUrl(String(payload.statusUrl || ""));',
    '    setStatus("done");',
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <div className="card" role="status">',
    "        <strong>All set.</strong>",
    "        <p>We know where this goes now. Bookmark your status page to check on it any time — no login needed:</p>",
    "        {statusUrl ? <p><a href={statusUrl}>{statusUrl}</a></p> : null}",
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={handleSubmit} noValidate>',
    '      <input className="input" name="name" type="text" maxLength={200} placeholder="Your name" aria-label="Your name" required />',
    '      <input className="input" name="email" type="email" maxLength={320} placeholder="Email (optional, for updates)" aria-label="Email" />',
    '      <input className="input" name="building" type="text" maxLength={200} placeholder="Building (optional)" aria-label="Building" />',
    '      <input className="input" name="floor" type="text" maxLength={100} placeholder="Floor (optional)" aria-label="Floor" />',
    '      <input className="input" name="room" type="text" maxLength={100} placeholder="Room / office (optional)" aria-label="Room" />',
    '      <input className="input" name="spot" type="text" maxLength={100} placeholder="Desk / spot (optional)" aria-label="Spot" />',
    '      <input className="input" name="department" type="text" maxLength={200} placeholder="Department (optional)" aria-label="Department" />',
    '      <textarea className="input" name="deliveryInstructions" maxLength={2000} placeholder="Anything else about where it should go? (optional)" aria-label="Delivery instructions" />',
    "      {/* honeypot — humans never see it; bots fill it and the server quietly declines */}",
    '      <input name="hp" type="text" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{ position: "absolute", left: "-9999px" }} />',
    '      <button className="button primary" type="submit" disabled={status === "sending"}>',
    '        {status === "sending" ? "Saving…" : "Claim it & set delivery"}',
    "      </button>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/claim/[token]/page.tsx (public claim page) ----------------------

function claimPageFile(): GeneratedModuleFile {
  return file("src/app/claim/[token]/page.tsx", [
    'import { ClaimForm } from "@/components/asset-claim/claim-form";',
    'import { ASSET_TYPE_LABELS, assetClaimEnabled, getClaimByToken } from "@/lib/db/asset-claim";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ClaimPage({ params }: { params: Promise<{ token: string }> }) {",
    "  if (!assetClaimEnabled()) {",
    '    return (<main className="shell"><h1>Claim</h1><p>Claiming is turned off for this app.</p></main>);',
    "  }",
    "  const { token } = await params;",
    "  const claim = await getClaimByToken(token);",
    "  if (!claim) {",
    '    return (<main className="shell"><h1>Claim link not found</h1><p className="note">Double-check the link, or the code on your card.</p></main>);',
    "  }",
    '  const typeLabel = ASSET_TYPE_LABELS[claim.asset.assetType] || "Asset";',
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{claim.organizationName || "Claim"}</p>',
    "      <h1>Claim {claim.asset.name}</h1>",
    '      <p className="note">{typeLabel}{claim.asset.identifier ? ` · ${claim.asset.identifier}` : ""} · Code {claim.claimCode}</p>',
    "      {claim.canClaim ? (",
    "        <ClaimForm token={token} />",
    "      ) : (",
    '        <div className="card" role="status">',
    "          <strong>This asset is already claimed.</strong>",
    "          <p>If it should be yours, ask an admin for a fresh claim link.</p>",
    "        </div>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/my-asset/[token]/page.tsx (public status page) ------------------

function statusPageFile(): GeneratedModuleFile {
  return file("src/app/my-asset/[token]/page.tsx", [
    'import { ASSET_TYPE_LABELS, assetClaimEnabled, getAssetStatus } from "@/lib/db/asset-claim";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MyAssetPage({ params }: { params: Promise<{ token: string }> }) {",
    "  if (!assetClaimEnabled()) {",
    '    return (<main className="shell"><h1>Status</h1><p>This page is turned off for this app.</p></main>);',
    "  }",
    "  const { token } = await params;",
    "  const status = await getAssetStatus(token);",
    "  if (!status) {",
    '    return (<main className="shell"><h1>Status link not found</h1><p className="note">Check the link, or claim your asset first.</p></main>);',
    "  }",
    '  const typeLabel = ASSET_TYPE_LABELS[status.assetType] || "Asset";',
    "  if (!status.claimed) {",
    "    return (",
    '      <main className="shell">',
    '        <p className="eyebrow">{status.organizationName || "Status"}</p>',
    "        <h1>{status.assetName}</h1>",
    "        <p>This asset has not been claimed yet.</p>",
    '        {status.claimUrl ? <p><a className="button primary" href={status.claimUrl}>Claim it now</a></p> : null}',
    "      </main>",
    "    );",
    "  }",
    "  const destination = status.destination;",
    '  const where = destination ? [destination.building, destination.floor, destination.room, destination.spot, destination.department].filter(Boolean).join(", ") : "";',
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{status.organizationName || "Status"}</p>',
    "      <h1>{status.assetName}</h1>",
    '      <p className="note">{typeLabel}{status.identifier ? ` · ${status.identifier}` : ""}</p>',
    '      <section className="card">',
    "        <strong>Claimed</strong>",
    "        <p>{status.claimedByName ? `By ${status.claimedByName}` : \"Claimed\"}{status.claimedAt ? ` · ${new Date(status.claimedAt).toLocaleDateString()}` : \"\"}</p>",
    "        {where ? <p>Delivers to: {where}</p> : null}",
    "        {destination?.deliveryInstructions ? <p>Note: {destination.deliveryInstructions}</p> : null}",
    "      </section>",
    '      {status.onDevice ? <p className="note">Live device monitoring is connected for this asset.</p> : null}',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/asset-claims/page.tsx (owner console) ---------------------------

function consolePageFile(): GeneratedModuleFile {
  return file("src/app/asset-claims/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { assetClaimEnabled, listAssets } from "@/lib/db/asset-claim";',
    'import { AssetClaimConsole } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AssetClaimsPage() {",
    "  if (!assetClaimEnabled()) {",
    '    return (<main className="shell"><h1>Assets</h1><p>Asset claiming is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/asset-claims");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Assets</h1><p className="note">Only admins can manage asset claims.</p></main>);',
    "  }",
    "  const assets = await listAssets();",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Assets</p>',
    "      <h1>Asset claims</h1>",
    "      <p>Add an asset, generate a claim card (a code and link the holder opens), and see who claimed what.</p>",
    "      <AssetClaimConsole assets={assets} />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/asset-claims/actions.tsx (client console) -----------------------

function consoleActionsFile(): GeneratedModuleFile {
  return file("src/app/asset-claims/actions.tsx", [
    '"use client";',
    "",
    'import { useRouter } from "next/navigation";',
    'import { useState } from "react";',
    "",
    "type Claim = { id: string; code: string; url: string; status: string; expiresAt: string };",
    "type Asset = { id: string; name: string; assetType: string; identifier: string; status: string; assignedLabel: string; claim: Claim | null };",
    "",
    "const ASSET_TYPES = [",
    '  { value: "equipment", label: "Equipment" },',
    '  { value: "device", label: "Device" },',
    '  { value: "item", label: "Item" },',
    '  { value: "room", label: "Room" },',
    '  { value: "vehicle", label: "Vehicle" },',
    '  { value: "asset", label: "Other" }',
    "];",
    "",
    "export function AssetClaimConsole({ assets }: { assets: Asset[] }) {",
    "  const router = useRouter();",
    "  const [working, setWorking] = useState(false);",
    "  const [fresh, setFresh] = useState<Record<string, { code: string; url: string }>>({});",
    "",
    "  async function addAsset(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = event.currentTarget;",
    "    const data = new FormData(form);",
    "    setWorking(true);",
    '    const response = await fetch("/api/asset-claim", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    '      body: JSON.stringify({ name: String(data.get("name") || ""), assetType: String(data.get("assetType") || "asset"), identifier: String(data.get("identifier") || "") })',
    "    }).catch(() => null);",
    "    setWorking(false);",
    "    if (response && response.ok) {",
    "      form.reset();",
    "      router.refresh();",
    "    }",
    "  }",
    "",
    "  async function generate(assetId: string) {",
    "    setWorking(true);",
    '    const response = await fetch("/api/asset-claim", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    '      body: JSON.stringify({ intent: "claim", assetId })',
    "    }).catch(() => null);",
    "    const payload = response ? await response.json().catch(() => null) : null;",
    "    setWorking(false);",
    "    if (payload?.ok && payload.claim) {",
    "      setFresh((prev) => ({ ...prev, [assetId]: { code: String(payload.claim.code), url: String(payload.claim.url) } }));",
    "      router.refresh();",
    "    }",
    "  }",
    "",
    "  async function revoke(claimId: string) {",
    "    setWorking(true);",
    "    await fetch(`/api/asset-claim/${claimId}`, { method: \"PATCH\" }).catch(() => null);",
    "    setWorking(false);",
    "    router.refresh();",
    "  }",
    "",
    "  return (",
    "    <>",
    '      <form className="stack card" onSubmit={addAsset}>',
    "        <strong>Add an asset</strong>",
    '        <input className="input" name="name" type="text" maxLength={200} placeholder="Asset name" aria-label="Asset name" required />',
    '        <select className="input" name="assetType" defaultValue="equipment" aria-label="Asset type">',
    "          {ASSET_TYPES.map((option) => (<option key={option.value} value={option.value}>{option.label}</option>))}",
    "        </select>",
    '        <input className="input" name="identifier" type="text" maxLength={120} placeholder="Serial / tag (optional)" aria-label="Identifier" />',
    '        <button className="button primary" type="submit" disabled={working}>Add asset</button>',
    "      </form>",
    "",
    "      {assets.length === 0 ? (",
    '        <p className="note">No assets yet. Add one above to generate its first claim card.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {assets.map((asset) => {",
    "            const card = fresh[asset.id];",
    "            const openClaim = asset.claim && asset.claim.status !== \"revoked\" ? asset.claim : null;",
    "            const code = card ? card.code : openClaim ? openClaim.code : \"\";",
    "            const url = card ? card.url : openClaim ? openClaim.url : \"\";",
    "            return (",
    '              <article className="wide-card" key={asset.id}>',
    '                <span>{asset.assetType}{asset.status === "claimed" ? " · claimed" : " · unclaimed"}</span>',
    "                <strong>{asset.name}</strong>",
    "                {asset.identifier ? <p>{asset.identifier}</p> : null}",
    "                {asset.assignedLabel ? <p>Delivers to: {asset.assignedLabel}</p> : null}",
    "                {code ? (",
    '                  <div className="card">',
    "                    <p>Claim code <strong>{code}</strong></p>",
    "                    {url ? <p><a href={url}>{url}</a></p> : null}",
    '                    <p className="stack">',
    '                      <button className="button" type="button" disabled={working} onClick={() => void generate(asset.id)}>New code</button>',
    '                      {openClaim ? <button className="button" type="button" disabled={working} onClick={() => void revoke(openClaim.id)}>Revoke</button> : null}',
    "                    </p>",
    "                  </div>",
    "                ) : (",
    '                  <button className="button primary" type="button" disabled={working} onClick={() => void generate(asset.id)}>Generate claim card</button>',
    "                )}",
    "              </article>",
    "            );",
    "          })}",
    "        </section>",
    "      )}",
    "    </>",
    "  );",
    "}"
  ]);
}

// ---- schema / seed -----------------------------------------------------------

function schemaSql(): string {
  return [
    "",
    "-- asset-claim: locations first (assets/claims reference them), then assets,",
    "-- then claims, then assignment history — so the composed schema applies in order.",
    "create table if not exists asset_claim_locations (",
    "  id uuid primary key default gen_random_uuid(),",
    "  organization_id uuid not null references organizations(id) on delete cascade,",
    "  name text not null,",
    "  building text,",
    "  floor text,",
    "  room text,",
    "  spot text,",
    "  department text,",
    "  contact_name text,",
    "  contact_email text,",
    "  delivery_instructions text,",
    "  metadata jsonb not null default '{}'::jsonb,",
    "  created_at timestamptz not null default now(),",
    "  updated_at timestamptz not null default now()",
    ");",
    "create index if not exists asset_claim_locations_org_idx on asset_claim_locations (organization_id);",
    "",
    "create table if not exists asset_claim_assets (",
    "  id uuid primary key default gen_random_uuid(),",
    "  organization_id uuid not null references organizations(id) on delete cascade,",
    "  name text not null,",
    "  asset_type text not null default 'asset',",
    "  identifier text,",
    "  status text not null default 'unclaimed',",
    "  assigned_user_id uuid references users(id) on delete set null,",
    "  assigned_label text,",
    "  location_id uuid references asset_claim_locations(id) on delete set null,",
    "  on_device_ref text,",
    "  metadata jsonb not null default '{}'::jsonb,",
    "  created_at timestamptz not null default now(),",
    "  updated_at timestamptz not null default now()",
    ");",
    "create index if not exists asset_claim_assets_org_status_idx on asset_claim_assets (organization_id, status);",
    "",
    "create table if not exists asset_claim_claims (",
    "  id uuid primary key default gen_random_uuid(),",
    "  organization_id uuid not null references organizations(id) on delete cascade,",
    "  asset_id uuid not null references asset_claim_assets(id) on delete cascade,",
    "  claim_token_hash text not null unique,",
    "  claim_code text not null unique,",
    "  claim_url text,",
    "  status text not null default 'pending',",
    "  expires_at timestamptz not null default now() + interval '30 days',",
    "  claimed_by_user_id uuid references users(id) on delete set null,",
    "  claimed_by_name text,",
    "  claimed_by_email text,",
    "  claimed_at timestamptz,",
    "  location_id uuid references asset_claim_locations(id) on delete set null,",
    "  status_token_hash text,",
    "  status_token_last_used_at timestamptz,",
    "  created_by_user_id uuid references users(id) on delete set null,",
    "  metadata jsonb not null default '{}'::jsonb,",
    "  created_at timestamptz not null default now(),",
    "  updated_at timestamptz not null default now()",
    ");",
    "create index if not exists asset_claim_claims_asset_status_idx on asset_claim_claims (asset_id, status);",
    "create index if not exists asset_claim_claims_org_status_idx on asset_claim_claims (organization_id, status);",
    "create unique index if not exists asset_claim_claims_status_token_uq on asset_claim_claims (status_token_hash) where status_token_hash is not null;",
    "",
    "create table if not exists asset_claim_assignment_history (",
    "  id uuid primary key default gen_random_uuid(),",
    "  organization_id uuid not null references organizations(id) on delete cascade,",
    "  asset_id uuid not null references asset_claim_assets(id) on delete cascade,",
    "  claim_id uuid references asset_claim_claims(id) on delete set null,",
    "  from_user_id uuid references users(id) on delete set null,",
    "  to_user_id uuid references users(id) on delete set null,",
    "  from_location_id uuid references asset_claim_locations(id) on delete set null,",
    "  to_location_id uuid references asset_claim_locations(id) on delete set null,",
    "  change_reason text not null default 'new_assignment',",
    "  notes text,",
    "  metadata jsonb not null default '{}'::jsonb,",
    "  created_at timestamptz not null default now()",
    ");",
    "create index if not exists asset_claim_assignment_history_asset_idx on asset_claim_assignment_history (asset_id, created_at desc);"
  ].join("\n");
}

function seedSql(): string {
  return [
    "",
    "-- One sample asset (only if none exist and an organization is present) so the",
    "-- console shows something real to generate a first claim card against.",
    "insert into asset_claim_assets (organization_id, name, asset_type, identifier, status)",
    "select o.id, 'Sample asset', 'equipment', 'SAMPLE-001', 'unclaimed'",
    "from organizations o",
    "where not exists (select 1 from asset_claim_assets)",
    "limit 1;"
  ].join("\n");
}

export const assetClaimModule: AppModule = {
  slug: "asset-claim",
  name: "Asset Claim & Delivery",
  tier: "optional",
  featureFlagEnv: "FEATURE_ASSET_CLAIM",
  files: () => [
    tokensFile(),
    dbLibFile(),
    apiRouteFile(),
    apiDetailRouteFile(),
    publicClaimApiFile(),
    publicStatusApiFile(),
    claimFormFile(),
    claimPageFile(),
    statusPageFile(),
    consolePageFile(),
    consoleActionsFile()
  ],
  schemaSql,
  seedSql,
  envLines: () => [
    "",
    "# Asset Claim — set to false to switch the claim/delivery flow off.",
    "# APP_URL (or AUTH_URL) is used as the origin in printed claim + status links.",
    "FEATURE_ASSET_CLAIM=true"
  ],
  homeLinks: () => ['        <a className="button" href="/asset-claims">Assets</a>'],
  navLinks: () => [{ href: "/asset-claims", label: "Assets" }]
};
