// becoming-growth-dashboard — a personal growth dashboard (reflection journal,
// growth goals, weekly check-ins, an alignment score, and a streak with a
// streak-pause), ported from Kindred-Connection's real "Becoming" system
// (backend/routers/becoming.py compute_alignment + becoming.py's daily prompt +
// backend/routers/streak.py pause/resume + backend/server.py /journal, /goals,
// /checkins, /milestones). We keep its actual model — journal entries (title,
// content, mood), goals (title, description, target_date, progress, completed →
// milestone at 100%), weekly check-ins (mood, note), a per-user alignment history
// keyed by ISO week, and the exact 0–100 alignment scoring + streak-counting
// (weeks at/above a threshold, skipping paused weeks). Generalized from Kindred's
// dating context to any app's personal-growth surface. Runs on the app owner's own
// database with a graceful sample-data fallback, feature-flagged (FEATURE_GROWTH),
// customers see their own data, admins can adjust the alignment threshold.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/growth.ts (model + queries, ported from the Python) ----------

function growthLibFile(): GeneratedModuleFile {
  return file("src/lib/db/growth.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// Ported from core.py ALIGNMENT_THRESHOLD = 50: the alignment score a week must",
    "// reach to count toward the streak. Admins can override via GROWTH_ALIGNMENT_THRESHOLD.",
    "export function alignmentThreshold(): number {",
    "  const raw = Number(process.env.GROWTH_ALIGNMENT_THRESHOLD);",
    "  return Number.isFinite(raw) && raw > 0 ? Math.min(100, Math.round(raw)) : 50;",
    "}",
    "",
    "// Ported from core.py DAILY_PROMPTS — invitational reflection prompts. Generalized",
    "// away from Kindred's explicitly devotional wording to plain growth prompts.",
    "export const DAILY_PROMPTS: string[] = [",
    '  "Where did you grow today, even without noticing?",',
    '  "Who came to mind today? Is there a small message worth sending?",',
    '  "What is one moment of grace you noticed today — even the smallest?",',
    '  "Where did you almost lie to yourself today, and what was the truth underneath?",',
    '  "What did you protect today — and was it worth protecting?",',
    '  "What belief you held this morning had softened by tonight?",',
    '  "If today were a small chapter in your life\'s book, what would the title be?",',
    '  "What gave you life today, what drained you, and what does that tell you?",',
    '  "What is a kindness you received that you haven\'t named yet?",',
    '  "What would your 8-year-old self thank you for today?",',
    '  "What is still unfinished today that you can let be?",',
    '  "Where did love show up today — given, received, or witnessed?"',
    "];",
    "",
    "// Deterministic daily prompt, ported from becoming.py:",
    "// seed = sum of char codes of (userId + YYYY-MM-DD), index into DAILY_PROMPTS.",
    "export function dailyPromptFor(userId: string, day: string): string {",
    "  let seed = 0;",
    "  for (const ch of userId + day) seed += ch.charCodeAt(0);",
    "  return DAILY_PROMPTS[seed % DAILY_PROMPTS.length];",
    "}",
    "",
    "export function todayKey(now: Date = new Date()): string {",
    '  return now.toISOString().slice(0, 10);',
    "}",
    "",
    "// ISO week key + week-start (Monday), ported from becoming.py isocalendar usage.",
    "export function isoWeekKey(now: Date = new Date()): { weekKey: string; weekStart: string } {",
    "  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));",
    "  const dayNum = (d.getUTCDay() + 6) % 7; // Mon=0..Sun=6",
    "  const weekStartDate = new Date(d);",
    "  weekStartDate.setUTCDate(d.getUTCDate() - dayNum);",
    "  const thursday = new Date(d);",
    "  thursday.setUTCDate(d.getUTCDate() - dayNum + 3);",
    "  const isoYear = thursday.getUTCFullYear();",
    "  const yearStart = new Date(Date.UTC(isoYear, 0, 1));",
    "  const week = Math.ceil((((thursday.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);",
    '  const weekKey = `${isoYear}-${String(week).padStart(2, "0")}`;',
    "  return { weekKey, weekStart: weekStartDate.toISOString().slice(0, 10) };",
    "}",
    "",
    "export type JournalEntry = { id: string; title: string; content: string; mood: string; createdAt: string };",
    "export type Goal = { id: string; title: string; description: string; targetDate: string; progress: number; completed: boolean; createdAt: string };",
    "export type CheckIn = { id: string; mood: string; note: string; createdAt: string };",
    "",
    "export type WeekStats = { journals: number; goals: number; checkins: number; milestones: number };",
    "export type Alignment = { score: number; streak: number; thisWeek: WeekStats };",
    "export type StreakPause = { until: string; reason: string; daysLeft: number } | null;",
    "",
    "export type GrowthDashboard = {",
    "  alignment: Alignment;",
    "  alignmentThreshold: number;",
    "  dailyPrompt: { prompt: string; journaledToday: boolean; date: string };",
    "  goals: { total: number; completed: number };",
    "  pause: StreakPause;",
    "  sample: boolean;",
    "};",
    "",
    "// ---- graceful fallback data (no DB configured) ----------------------------",
    "const fallbackJournals: JournalEntry[] = [",
    '  { id: "sample-j1", title: "First honest page", content: "I showed up today. That counted for more than I expected.", mood: "✦ Reflective", createdAt: new Date(Date.now() - 86400000).toISOString() }',
    "];",
    "const fallbackGoals: Goal[] = [",
    '  { id: "sample-g1", title: "Move my body most days", description: "Small, repeatable, kind to myself.", targetDate: "", progress: 50, completed: false, createdAt: new Date(Date.now() - 3 * 86400000).toISOString() }',
    "];",
    "const fallbackCheckins: CheckIn[] = [",
    '  { id: "sample-c1", mood: "steady", note: "A quiet, ordinary, good day.", createdAt: new Date(Date.now() - 2 * 86400000).toISOString() }',
    "];",
    "",
    "// ---- row mappers ----------------------------------------------------------",
    "function rowToJournal(row: Record<string, unknown>): JournalEntry {",
    "  return {",
    "    id: String(row.id),",
    '    title: String(row.title || ""),',
    '    content: String(row.content || ""),',
    '    mood: String(row.mood || ""),',
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "function rowToGoal(row: Record<string, unknown>): Goal {",
    "  return {",
    "    id: String(row.id),",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    targetDate: String(row.target_date || ""),',
    "    progress: Number(row.progress || 0),",
    "    completed: Boolean(row.completed),",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "function rowToCheckin(row: Record<string, unknown>): CheckIn {",
    "  return {",
    "    id: String(row.id),",
    '    mood: String(row.mood || ""),',
    '    note: String(row.note || ""),',
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "// ---- journal (ported from server.py /journal) -----------------------------",
    "export async function listJournal(userId: string): Promise<JournalEntry[]> {",
    "  if (!hasDatabase()) return fallbackJournals;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, title, content, mood, created_at from growth_journal_entries where user_id = ${userId} order by created_at desc limit 200`;",
    "    return rows.map((r) => rowToJournal(r as Record<string, unknown>));",
    "  } catch {",
    "    return fallbackJournals;",
    "  }",
    "}",
    "",
    "export async function addJournal(userId: string, input: { title: string; content: string; mood?: string }): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    await sql`insert into growth_journal_entries (user_id, title, content, mood) values (${userId}, ${input.title}, ${input.content}, ${input.mood || ""})`;',
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function deleteJournal(userId: string, id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from growth_journal_entries where id = ${id} and user_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- goals (ported from server.py /goals + milestone-on-complete) ---------",
    "export async function listGoals(userId: string): Promise<Goal[]> {",
    "  if (!hasDatabase()) return fallbackGoals;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, title, description, target_date, progress, completed, created_at from growth_goals where user_id = ${userId} order by created_at desc limit 200`;",
    "    return rows.map((r) => rowToGoal(r as Record<string, unknown>));",
    "  } catch {",
    "    return fallbackGoals;",
    "  }",
    "}",
    "",
    "export async function addGoal(userId: string, input: { title: string; description?: string; targetDate?: string }): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    await sql`insert into growth_goals (user_id, title, description, target_date, progress, completed) values (${userId}, ${input.title}, ${input.description || ""}, ${input.targetDate || ""}, 0, false)`;',
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Ported from server.py PATCH /goals/{id}: clamp progress 0-100, mark completed",
    "// at 100, and record a milestone once (de-duped on goal_id) when it first crosses.",
    "export async function updateGoalProgress(userId: string, id: string, progress: number): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const clamped = Math.max(0, Math.min(100, Math.round(progress)));",
    "  const completed = clamped >= 100;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`update growth_goals set progress = ${clamped}, completed = ${completed}, updated_at = now() where id = ${id} and user_id = ${userId} returning id, title`;",
    "    if (!rows[0]) return false;",
    "    if (completed) {",
    "      const already = await sql`select id from growth_milestones where goal_id = ${id} and user_id = ${userId} limit 1`;",
    "      if (!already[0]) {",
    '        await sql`insert into growth_milestones (user_id, goal_id, title, description) values (${userId}, ${id}, ${String((rows[0] as Record<string, unknown>).title || "")}, ${"Goal completed"})`;',
    "      }",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function deleteGoal(userId: string, id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from growth_goals where id = ${id} and user_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- weekly check-ins (ported from server.py /checkins) -------------------",
    "export async function listCheckins(userId: string): Promise<CheckIn[]> {",
    "  if (!hasDatabase()) return fallbackCheckins;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, mood, note, created_at from growth_checkins where user_id = ${userId} order by created_at desc limit 200`;",
    "    return rows.map((r) => rowToCheckin(r as Record<string, unknown>));",
    "  } catch {",
    "    return fallbackCheckins;",
    "  }",
    "}",
    "",
    "export async function addCheckin(userId: string, input: { mood: string; note?: string }): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    await sql`insert into growth_checkins (user_id, mood, note) values (${userId}, ${input.mood}, ${input.note || ""})`;',
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- streak pause / resume (ported from streak.py) ------------------------",
    "// pause_until / pause_reason / pause_started_at, days clamped 1..21.",
    "export async function pauseStreak(userId: string, days: number, reason: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const d = Math.max(1, Math.min(21, Math.round(days)));",
    "  const now = new Date();",
    "  const until = new Date(now.getTime() + d * 86400000);",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into growth_streak_state (user_id, pause_until, pause_reason, pause_started_at, updated_at)",
    "      values (${userId}, ${until.toISOString()}, ${reason || null}, ${now.toISOString()}, now())",
    "      on conflict (user_id) do update set pause_until = ${until.toISOString()}, pause_reason = ${reason || null}, pause_started_at = ${now.toISOString()}, updated_at = now()",
    "    `;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function resumeStreak(userId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update growth_streak_state set pause_until = null, pause_reason = null, pause_started_at = null, updated_at = now() where user_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "async function getPause(userId: string): Promise<{ until: string; startedAt: string; reason: string } | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select pause_until, pause_reason, pause_started_at from growth_streak_state where user_id = ${userId} limit 1`;",
    "    const row = rows[0] as Record<string, unknown> | undefined;",
    "    if (!row || !row.pause_until) return null;",
    '    return { until: String(row.pause_until), startedAt: String(row.pause_started_at || ""), reason: String(row.pause_reason || "") };',
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- alignment (ported verbatim from becoming.py compute_alignment) -------",
    "// Score 0-100 reflecting how much the user showed up for themselves this week:",
    "//   journals >= 1  -> +20,  journals >= 3 -> +10 more",
    "//   milestones >= 1 -> +20",
    "//   checkins >= 1  -> +15",
    "//   (Kindred's pod_posts/community bands are dropped — no social graph here;",
    "//    we keep the same weights for the surfaces that exist.)",
    "// then min(score, 100). Streak = consecutive prior weeks whose recorded score",
    "// met the threshold, skipping weeks that fell inside a streak pause window.",
    "export async function computeAlignment(userId: string): Promise<Alignment> {",
    "  const threshold = alignmentThreshold();",
    "  if (!hasDatabase()) {",
    "    // Fallback mirrors the sample data: one journal + a half-done goal.",
    "    return { score: 20, streak: 0, thisWeek: { journals: 1, goals: 1, checkins: 1, milestones: 0 } };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    '    const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString();',
    "    const jr = await sql`select count(*)::int as n from growth_journal_entries where user_id = ${userId} and created_at >= ${weekAgo}`;",
    "    const mr = await sql`select count(*)::int as n from growth_milestones where user_id = ${userId} and created_at >= ${weekAgo}`;",
    "    const cr = await sql`select count(*)::int as n from growth_checkins where user_id = ${userId} and created_at >= ${weekAgo}`;",
    "    const gr = await sql`select count(*)::int as n from growth_goals where user_id = ${userId} and created_at >= ${weekAgo}`;",
    "    const journals = Number((jr[0] as Record<string, unknown> | undefined)?.n || 0);",
    "    const milestones = Number((mr[0] as Record<string, unknown> | undefined)?.n || 0);",
    "    const checkins = Number((cr[0] as Record<string, unknown> | undefined)?.n || 0);",
    "    const goals = Number((gr[0] as Record<string, unknown> | undefined)?.n || 0);",
    "",
    "    let score = 0;",
    "    if (journals >= 1) score += 20;",
    "    if (journals >= 3) score += 10;",
    "    if (milestones >= 1) score += 20;",
    "    if (checkins >= 1) score += 15;",
    "    if (goals >= 1) score += 15;",
    "    score = Math.min(score, 100);",
    "",
    "    // Persist this week's score into the history so the streak has something to read.",
    "    const { weekKey, weekStart } = isoWeekKey();",
    "    const stats = { journals, goals, checkins, milestones };",
    "    await sql`",
    "      insert into growth_alignment_history (user_id, week_key, week_start, score, stats, updated_at)",
    "      values (${userId}, ${weekKey}, ${weekStart}, ${score}, ${JSON.stringify(stats)}::jsonb, now())",
    "      on conflict (user_id, week_key) do update set week_start = ${weekStart}, score = ${score}, stats = ${JSON.stringify(stats)}::jsonb, updated_at = now()",
    "    `;",
    "",
    "    // Streak: walk history newest-first, count weeks meeting the threshold, break",
    "    // on the first miss. Skip any week whose start falls inside the pause window.",
    "    const pause = await getPause(userId);",
    "    let pauseStart: number | null = null;",
    "    let pauseEnd: number | null = null;",
    "    if (pause && pause.startedAt && pause.until) {",
    "      const s = Date.parse(pause.startedAt);",
    "      const e = Date.parse(pause.until);",
    "      if (!Number.isNaN(s) && !Number.isNaN(e)) { pauseStart = s; pauseEnd = e; }",
    "    }",
    "    const history = await sql`select week_start, score from growth_alignment_history where user_id = ${userId} order by week_start desc limit 60`;",
    "    let streak = 0;",
    "    for (const raw of history) {",
    "      const row = raw as Record<string, unknown>;",
    "      if (pauseStart !== null && pauseEnd !== null && row.week_start) {",
    "        const ws = Date.parse(String(row.week_start));",
    "        if (!Number.isNaN(ws) && ws >= pauseStart && ws <= pauseEnd) continue;",
    "      }",
    "      if (Number(row.score || 0) >= threshold) streak += 1;",
    "      else break;",
    "    }",
    "",
    "    return { score, streak, thisWeek: { journals, goals, checkins, milestones } };",
    "  } catch {",
    "    return { score: 0, streak: 0, thisWeek: { journals: 0, goals: 0, checkins: 0, milestones: 0 } };",
    "  }",
    "}",
    "",
    "// ---- dashboard aggregate (ported from becoming.py GET /becoming) ----------",
    "export async function getDashboard(userId: string): Promise<GrowthDashboard> {",
    "  const threshold = alignmentThreshold();",
    "  const alignment = await computeAlignment(userId);",
    "  const day = todayKey();",
    "  const prompt = dailyPromptFor(userId, day);",
    "",
    "  if (!hasDatabase()) {",
    "    return {",
    "      alignment,",
    "      alignmentThreshold: threshold,",
    "      dailyPrompt: { prompt, journaledToday: false, date: day },",
    "      goals: { total: 1, completed: 0 },",
    "      pause: null,",
    "      sample: true",
    "    };",
    "  }",
    "",
    "  try {",
    "    const sql = getDatabase();",
    '    const todayStart = day + "T00:00:00.000Z";',
    "    const journaled = await sql`select 1 from growth_journal_entries where user_id = ${userId} and created_at >= ${todayStart} limit 1`;",
    "    const totalRow = await sql`select count(*)::int as n from growth_goals where user_id = ${userId}`;",
    "    const doneRow = await sql`select count(*)::int as n from growth_goals where user_id = ${userId} and completed = true`;",
    "",
    "    const rawPause = await getPause(userId);",
    "    let pause: StreakPause = null;",
    "    if (rawPause) {",
    "      const end = Date.parse(rawPause.until);",
    "      if (!Number.isNaN(end) && end > Date.now()) {",
    "        pause = { until: rawPause.until, reason: rawPause.reason, daysLeft: Math.max(0, Math.floor((end - Date.now()) / 86400000)) };",
    "      }",
    "    }",
    "",
    "    return {",
    "      alignment,",
    "      alignmentThreshold: threshold,",
    "      dailyPrompt: { prompt, journaledToday: journaled.length > 0, date: day },",
    "      goals: { total: Number((totalRow[0] as Record<string, unknown> | undefined)?.n || 0), completed: Number((doneRow[0] as Record<string, unknown> | undefined)?.n || 0) },",
    "      pause,",
    "      sample: false",
    "    };",
    "  } catch {",
    "    return {",
    "      alignment,",
    "      alignmentThreshold: threshold,",
    "      dailyPrompt: { prompt, journaledToday: false, date: day },",
    "      goals: { total: 0, completed: 0 },",
    "      pause: null,",
    "      sample: false",
    "    };",
    "  }",
    "}",
    "",
    "// Ported from Becoming.js: score >= 80 Bursting, >= 50 Showing up, else Quietly returning.",
    "export function alignmentLabel(score: number): string {",
    '  if (score >= 80) return "Bursting";',
    '  if (score >= 50) return "Showing up";',
    '  return "Quietly returning";',
    "}",
    "",
    "export function growthEnabled(): boolean {",
    '  return process.env.FEATURE_GROWTH !== "false";',
    "}"
  ]);
}

// ---- src/app/api/growth/route.ts (dashboard) --------------------------------

function growthDashboardApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getDashboard, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false, message: "The growth dashboard is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const dashboard = await getDashboard(user.email);",
    "  return NextResponse.json({ ok: true, dashboard });",
    "}"
  ]);
}

// ---- src/app/api/growth/journal/route.ts ------------------------------------

function growthJournalApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/journal/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listJournal, addJournal, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const entries = await listJournal(user.email);",
    "  return NextResponse.json({ ok: true, entries });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  const content = typeof body.content === "string" ? body.content.trim() : "";',
    "  if (!title || !content) {",
    '    return NextResponse.json({ ok: false, message: "Add a title and a reflection." }, { status: 400 });',
    "  }",
    '  const saved = await addJournal(user.email, { title, content, mood: typeof body.mood === "string" ? body.mood : undefined });',
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save your journal." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/growth/journal/[id]/route.ts (delete) ----------------------

function growthJournalDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/journal/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { deleteJournal, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const done = await deleteJournal(user.email, id);",
    '  if (!done) return NextResponse.json({ ok: false, message: "Could not remove this entry." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/growth/goals/route.ts --------------------------------------

function growthGoalsApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/goals/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listGoals, addGoal, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const goals = await listGoals(user.email);",
    "  return NextResponse.json({ ok: true, goals });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  if (!title) return NextResponse.json({ ok: false, message: "Name your goal." }, { status: 400 });',
    "  const saved = await addGoal(user.email, {",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    '    targetDate: typeof body.targetDate === "string" ? body.targetDate : undefined',
    "  });",
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save goals." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/growth/goals/[id]/route.ts (progress / delete) -------------

function growthGoalsDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/goals/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { updateGoalProgress, deleteGoal, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const progress = typeof body.progress === "number" ? body.progress : Number(body.progress);',
    "  if (!Number.isFinite(progress)) {",
    '    return NextResponse.json({ ok: false, message: "Provide a progress value." }, { status: 400 });',
    "  }",
    "  const done = await updateGoalProgress(user.email, id, progress);",
    '  if (!done) return NextResponse.json({ ok: false, message: "Could not update this goal." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const done = await deleteGoal(user.email, id);",
    '  if (!done) return NextResponse.json({ ok: false, message: "Could not remove this goal." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/growth/checkins/route.ts -----------------------------------

function growthCheckinsApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/checkins/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listCheckins, addCheckin, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const checkins = await listCheckins(user.email);",
    "  return NextResponse.json({ ok: true, checkins });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const mood = typeof body.mood === "string" ? body.mood.trim() : "";',
    '  if (!mood) return NextResponse.json({ ok: false, message: "How are you, honestly? Pick a mood." }, { status: 400 });',
    '  const saved = await addCheckin(user.email, { mood, note: typeof body.note === "string" ? body.note : undefined });',
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save check-ins." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/growth/streak/route.ts (pause / resume) --------------------

function growthStreakApiFile(): GeneratedModuleFile {
  return file("src/app/api/growth/streak/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { pauseStreak, resumeStreak, growthEnabled } from "@/lib/db/growth";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Ported from streak.py: POST { action: 'pause', days, reason } or { action: 'resume' }.",
    "export async function POST(request: Request) {",
    '  if (!growthEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "";',
    '  if (action === "resume") {',
    "    const done = await resumeStreak(user.email);",
    '    if (!done) return NextResponse.json({ ok: false, message: "Connect a database to manage your streak." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  const days = typeof body.days === "number" ? body.days : Number(body.days);',
    "  if (!Number.isFinite(days) || days < 1 || days > 21) {",
    '    return NextResponse.json({ ok: false, message: "Choose between 1 and 21 days." }, { status: 400 });',
    "  }",
    '  const done = await pauseStreak(user.email, days, typeof body.reason === "string" ? body.reason : "");',
    '  if (!done) return NextResponse.json({ ok: false, message: "Connect a database to manage your streak." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/growth/page.tsx (dashboard) ------------------------------------

function growthPageFile(): GeneratedModuleFile {
  return file("src/app/growth/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getDashboard, alignmentLabel, growthEnabled } from "@/lib/db/growth";',
    'import { StreakControls } from "./streak-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function GrowthPage() {",
    "  if (!growthEnabled()) {",
    '    return (<main className="shell"><h1>Growth</h1><p>The growth dashboard is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/growth");',
    "  const user = await getCurrentUser();",
    '  const dashboard = await getDashboard(user?.email || "");',
    "  const a = dashboard.alignment;",
    "  const pct = Math.min(100, a.score);",
    "  const threshold = dashboard.alignmentThreshold;",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Becoming</p>',
    "      <h1>Your growth</h1>",
    "      <p>The path is inward first. Show up for yourself, week by week.</p>",
    "",
    "      {dashboard.sample ? (",
    '        <p className="note">Showing sample data. Connect a database and sign in to track your own journal, goals, and check-ins.</p>',
    "      ) : null}",
    "",
    '      <section className="grid">',
    '        <article className="card" aria-label="This week\'s alignment">',
    "          <span>This week&rsquo;s alignment</span>",
    '          <strong style={{ fontSize: "2rem" }}>{a.score}<span style={{ fontSize: "1rem", opacity: 0.6 }}>/100</span></strong>',
    "          <p>{alignmentLabel(a.score)}</p>",
    '          <div style={{ height: 6, borderRadius: 999, background: "rgba(0,0,0,0.08)", overflow: "hidden", marginTop: 8 }}>',
    '            <div style={{ width: `${pct}%`, height: "100%", background: "currentColor" }} />',
    "          </div>",
    '          <p className="note">Streak: {a.streak} {a.streak === 1 ? "week" : "weeks"} · Streak keeps at {threshold}+</p>',
    "        </article>",
    '        <article className="card"><span>Journal entries</span><strong>{a.thisWeek.journals}</strong></article>',
    '        <article className="card"><span>Check-ins</span><strong>{a.thisWeek.checkins}</strong></article>',
    '        <article className="card"><span>Milestones</span><strong>{a.thisWeek.milestones}</strong></article>',
    '        <article className="card"><span>Goals</span><strong>{dashboard.goals.completed}/{dashboard.goals.total} done</strong></article>',
    "      </section>",
    "",
    '      <section className="panel" aria-label="Today\'s prompt">',
    '        <p className="eyebrow">Today&rsquo;s prompt</p>',
    "        <p><em>&ldquo;{dashboard.dailyPrompt.prompt}&rdquo;</em></p>",
    '        <p className="note">{dashboard.dailyPrompt.journaledToday ? "✓ You answered today." : "You haven’t answered yet."}</p>',
    '        <p><Link className="button primary" href="/growth/journal">Answer in your journal</Link></p>',
    "      </section>",
    "",
    "      {dashboard.pause ? (",
    '        <p className="note">Streak paused for {dashboard.pause.daysLeft} more {dashboard.pause.daysLeft === 1 ? "day" : "days"}{dashboard.pause.reason ? ` — ${dashboard.pause.reason}` : ""}.</p>',
    "      ) : null}",
    "",
    '      <section className="panel">',
    '        <p className="eyebrow">Life happens</p>',
    "        <p>Taking a break? Pause your streak so time away doesn&rsquo;t break it (1&ndash;21 days).</p>",
    '        <StreakControls paused={Boolean(dashboard.pause)} sample={dashboard.sample} />',
    "      </section>",
    "",
    '      <nav className="panel-list" aria-label="Growth sections">',
    '        <Link className="wide-card" href="/growth/journal"><strong>Journal</strong><p>Your private pages.</p></Link>',
    '        <Link className="wide-card" href="/growth/goals"><strong>Growth goals</strong><p>Plant an intention, track progress, celebrate milestones.</p></Link>',
    '        <Link className="wide-card" href="/growth/checkins"><strong>Check-ins</strong><p>A quick, honest mood note.</p></Link>',
    "      </nav>",
    "",
    "      {isAdmin ? (",
    '        <p className="note">Admin: set GROWTH_ALIGNMENT_THRESHOLD to change the streak threshold (currently {threshold}).</p>',
    "      ) : null}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/streak-controls.tsx (client) ----------------------------

function growthStreakControlsFile(): GeneratedModuleFile {
  return file("src/app/growth/streak-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function StreakControls({ paused, sample }: { paused: boolean; sample: boolean }) {",
    "  const router = useRouter();",
    "  const [days, setDays] = useState(7);",
    '  const [reason, setReason] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function send(action: string, body: Record<string, unknown>) {",
    "    setError(null);",
    "    setBusy(true);",
    "    try {",
    '      const res = await fetch("/api/growth/streak", {',
    '        method: "POST",',
    '        headers: { "content-type": "application/json" },',
    "        body: JSON.stringify({ action, ...body })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok || !data.ok) {",
    '        setError(data.message || "Could not update your streak.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  if (sample) {",
    '    return <p className="note">Connect a database and sign in to pause your streak.</p>;',
    "  }",
    "",
    "  if (paused) {",
    "    return (",
    "      <div>",
    '        <button className="button primary" type="button" disabled={busy} onClick={() => send("resume", {})}>{busy ? "…" : "Resume streak"}</button>',
    '        {error ? <p className="note" role="alert">{error}</p> : null}',
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={(e) => { e.preventDefault(); send("pause", { days, reason }); }} aria-label="Pause your streak">',
    '      <label htmlFor="pause-days">Days to pause (1&ndash;21)</label>',
    '      <input id="pause-days" className="input" type="number" min={1} max={21} value={days} onChange={(e) => setDays(Number(e.target.value))} />',
    '      <label htmlFor="pause-reason">Reason (optional)</label>',
    '      <input id="pause-reason" className="input" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="e.g. travel, a hard week" />',
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    '      <button className="button" type="submit" disabled={busy}>{busy ? "…" : "Pause my streak"}</button>',
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/journal/page.tsx ----------------------------------------

function growthJournalPageFile(): GeneratedModuleFile {
  return file("src/app/growth/journal/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listJournal, getDashboard, growthEnabled } from "@/lib/db/growth";',
    'import { JournalForm } from "./journal-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function GrowthJournalPage() {",
    "  if (!growthEnabled()) {",
    '    return (<main className="shell"><h1>Journal</h1><p>The growth dashboard is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/growth/journal");',
    "  const user = await getCurrentUser();",
    '  const uid = user?.email || "";',
    "  const [entries, dashboard] = await Promise.all([listJournal(uid), getDashboard(uid)]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Your private pages</p>',
    "      <h1>Journal</h1>",
    '      <section className="panel" aria-label="Today\'s prompt">',
    '        <p className="eyebrow">Today&rsquo;s prompt</p>',
    "        <p><em>&ldquo;{dashboard.dailyPrompt.prompt}&rdquo;</em></p>",
    "      </section>",
    "      <JournalForm prompt={dashboard.dailyPrompt.prompt} />",
    "      {entries.length === 0 ? (",
    '        <p className="note">Your first reflection awaits.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {entries.map((e) => (",
    '            <article className="wide-card" key={e.id}>',
    "              <strong>{e.title}</strong>",
    '              <p className="note">{e.createdAt ? new Date(e.createdAt).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" }) : ""}{e.mood ? ` · ${e.mood}` : ""}</p>',
    '              <p style={{ whiteSpace: "pre-line" }}>{e.content}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/growth">Back to growth</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/journal/journal-form.tsx (client) -----------------------

function growthJournalFormFile(): GeneratedModuleFile {
  return file("src/app/growth/journal/journal-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    'const MOODS = ["☀ Bright", "✦ Reflective", "♡ Tender", "△ Restless", "✿ Grateful"];',
    "",
    "export function JournalForm({ prompt }: { prompt: string }) {",
    "  const router = useRouter();",
    '  const [title, setTitle] = useState("");',
    '  const [content, setContent] = useState("");',
    '  const [mood, setMood] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function save(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    setError(null);",
    "    if (!title.trim() || !content.trim()) {",
    '      setError("Add a title and a reflection.");',
    "      return;",
    "    }",
    "    setBusy(true);",
    "    try {",
    '      const res = await fetch("/api/growth/journal", {',
    '        method: "POST",',
    '        headers: { "content-type": "application/json" },',
    "        body: JSON.stringify({ title, content, mood })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok || !data.ok) {",
    '        setError(data.message || "Could not save your entry.");',
    "        return;",
    "      }",
    '      setTitle(""); setContent(""); setMood("");',
    "      router.refresh();",
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={save}>',
    '      <label htmlFor="j-title">Title</label>',
    '      <input id="j-title" className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Give today a name" />',
    '      <label htmlFor="j-content">Reflection</label>',
    '      <textarea id="j-content" className="input" rows={6} value={content} onChange={(e) => setContent(e.target.value)} placeholder="What is true for you today?" />',
    '      <div role="group" aria-label="Mood" style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>',
    "        {MOODS.map((m) => (",
    '          <button type="button" key={m} aria-pressed={mood === m} className={mood === m ? "button primary" : "button"} onClick={() => setMood(mood === m ? "" : m)}>{m}</button>',
    "        ))}",
    "      </div>",
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    '      <button className="button primary" type="submit" disabled={busy}>{busy ? "Saving…" : "Save entry"}</button>',
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/goals/page.tsx ------------------------------------------

function growthGoalsPageFile(): GeneratedModuleFile {
  return file("src/app/growth/goals/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listGoals, growthEnabled } from "@/lib/db/growth";',
    'import { GoalsBoard } from "./goals-board";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function GrowthGoalsPage() {",
    "  if (!growthEnabled()) {",
    '    return (<main className="shell"><h1>Goals</h1><p>The growth dashboard is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/growth/goals");',
    "  const user = await getCurrentUser();",
    '  const goals = await listGoals(user?.email || "");',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Becoming</p>',
    "      <h1>Growth goals</h1>",
    "      <p>Plant an intention. Nudge it forward. A finished goal becomes a milestone.</p>",
    "      <GoalsBoard initialGoals={goals} />",
    '      <p><Link className="button" href="/growth">Back to growth</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/goals/goals-board.tsx (client) --------------------------

function growthGoalsBoardFile(): GeneratedModuleFile {
  return file("src/app/growth/goals/goals-board.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Goal = { id: string; title: string; description: string; progress: number; completed: boolean };",
    "",
    "export function GoalsBoard({ initialGoals }: { initialGoals: Goal[] }) {",
    "  const router = useRouter();",
    '  const [title, setTitle] = useState("");',
    '  const [description, setDescription] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function add(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    setError(null);",
    "    if (!title.trim()) {",
    '      setError("Name your goal.");',
    "      return;",
    "    }",
    "    setBusy(true);",
    "    try {",
    '      const res = await fetch("/api/growth/goals", {',
    '        method: "POST",',
    '        headers: { "content-type": "application/json" },',
    "        body: JSON.stringify({ title, description })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok || !data.ok) {",
    '        setError(data.message || "Could not save your goal.");',
    "        return;",
    "      }",
    '      setTitle(""); setDescription("");',
    "      router.refresh();",
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  async function setProgress(id: string, progress: number) {",
    '    await fetch(`/api/growth/goals/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ progress }) });',
    "    router.refresh();",
    "  }",
    "",
    "  async function remove(id: string) {",
    '    await fetch(`/api/growth/goals/${id}`, { method: "DELETE" });',
    "    router.refresh();",
    "  }",
    "",
    "  return (",
    "    <>",
    '      <form className="stack" onSubmit={add} aria-label="Add a goal">',
    '        <label htmlFor="g-title">Goal</label>',
    '        <input id="g-title" className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="What do you want to become?" />',
    '        <label htmlFor="g-desc">Why does this matter to you?</label>',
    '        <textarea id="g-desc" className="input" rows={2} value={description} onChange={(e) => setDescription(e.target.value)} />',
    '        {error ? <p className="note" role="alert">{error}</p> : null}',
    '        <button className="button primary" type="submit" disabled={busy}>{busy ? "Saving…" : "Add goal"}</button>',
    "      </form>",
    "",
    "      {initialGoals.length === 0 ? (",
    '        <p className="note">Plant your first intention.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {initialGoals.map((g) => (",
    '            <article className="wide-card" key={g.id}>',
    '              <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>',
    "                <strong>{g.title}</strong>",
    '                <button className="button" type="button" onClick={() => remove(g.id)} aria-label={`Remove ${g.title}`}>Remove</button>',
    "              </div>",
    '              {g.description ? <p className="note">{g.description}</p> : null}',
    '              <div style={{ height: 6, borderRadius: 999, background: "rgba(0,0,0,0.08)", overflow: "hidden", marginTop: 8 }}>',
    '                <div style={{ width: `${g.progress}%`, height: "100%", background: "currentColor" }} />',
    "              </div>",
    '              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 8 }}>',
    '                <span className="note">{g.completed ? "Complete ✓" : `${g.progress}%`}</span>',
    '                <div style={{ display: "flex", gap: 6 }}>',
    "                  {[25, 50, 75, 100].map((p) => (",
    '                    <button className="button" type="button" key={p} onClick={() => setProgress(g.id, p)}>{p}%</button>',
    "                  ))}",
    "                </div>",
    "              </div>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/checkins/page.tsx ---------------------------------------

function growthCheckinsPageFile(): GeneratedModuleFile {
  return file("src/app/growth/checkins/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listCheckins, growthEnabled } from "@/lib/db/growth";',
    'import { CheckinForm } from "./checkin-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function GrowthCheckinsPage() {",
    "  if (!growthEnabled()) {",
    '    return (<main className="shell"><h1>Check-ins</h1><p>The growth dashboard is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/growth/checkins");',
    "  const user = await getCurrentUser();",
    '  const checkins = await listCheckins(user?.email || "");',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Becoming</p>',
    "      <h1>Check-ins</h1>",
    "      <p>A quick, honest note on how you&rsquo;re really doing. Once a week is plenty.</p>",
    "      <CheckinForm />",
    "      {checkins.length === 0 ? (",
    '        <p className="note">No check-ins yet. The first one is the hardest.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {checkins.map((c) => (",
    '            <article className="wide-card" key={c.id}>',
    "              <strong>{c.mood}</strong>",
    '              <p className="note">{c.createdAt ? new Date(c.createdAt).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" }) : ""}</p>',
    "              {c.note ? <p>{c.note}</p> : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/growth">Back to growth</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/growth/checkins/checkin-form.tsx (client) ----------------------

function growthCheckinFormFile(): GeneratedModuleFile {
  return file("src/app/growth/checkins/checkin-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    'const MOODS = ["bright", "steady", "tender", "restless", "grateful", "heavy"];',
    "",
    "export function CheckinForm() {",
    "  const router = useRouter();",
    '  const [mood, setMood] = useState("");',
    '  const [note, setNote] = useState("");',
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function save(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    setError(null);",
    "    if (!mood.trim()) {",
    '      setError("Pick a mood, honestly.");',
    "      return;",
    "    }",
    "    setBusy(true);",
    "    try {",
    '      const res = await fetch("/api/growth/checkins", {',
    '        method: "POST",',
    '        headers: { "content-type": "application/json" },',
    "        body: JSON.stringify({ mood, note })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok || !data.ok) {",
    '        setError(data.message || "Could not save your check-in.");',
    "        return;",
    "      }",
    '      setMood(""); setNote("");',
    "      router.refresh();",
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={save} aria-label="Weekly check-in">',
    '      <div role="group" aria-label="How are you?" style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>',
    "        {MOODS.map((m) => (",
    '          <button type="button" key={m} aria-pressed={mood === m} className={mood === m ? "button primary" : "button"} onClick={() => setMood(mood === m ? "" : m)}>{m}</button>',
    "        ))}",
    "      </div>",
    '      <label htmlFor="c-note">Anything you want to name? (optional)</label>',
    '      <textarea id="c-note" className="input" rows={2} value={note} onChange={(e) => setNote(e.target.value)} />',
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    '      <button className="button primary" type="submit" disabled={busy}>{busy ? "Saving…" : "Save check-in"}</button>',
    "    </form>",
    "  );",
    "}"
  ]);
}

export const becomingGrowthModule: AppModule = {
  slug: "becoming-growth-dashboard",
  name: "Becoming — Growth Dashboard",
  tier: "optional",
  featureFlagEnv: "FEATURE_GROWTH",
  files: () => [
    growthLibFile(),
    growthDashboardApiFile(),
    growthJournalApiFile(),
    growthJournalDetailApiFile(),
    growthGoalsApiFile(),
    growthGoalsDetailApiFile(),
    growthCheckinsApiFile(),
    growthStreakApiFile(),
    growthPageFile(),
    growthStreakControlsFile(),
    growthJournalPageFile(),
    growthJournalFormFile(),
    growthGoalsPageFile(),
    growthGoalsBoardFile(),
    growthCheckinsPageFile(),
    growthCheckinFormFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists growth_journal_entries (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text not null,",
      "  title text not null default '',",
      "  content text not null default '',",
      "  mood text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_journal_user_idx on growth_journal_entries (user_id, created_at desc);",
      "",
      "create table if not exists growth_goals (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text not null,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  target_date text not null default '',",
      "  progress integer not null default 0,",
      "  completed boolean not null default false,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_goals_user_idx on growth_goals (user_id, created_at desc);",
      "",
      "create table if not exists growth_milestones (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text not null,",
      "  goal_id uuid,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_milestones_user_idx on growth_milestones (user_id, created_at desc);",
      "create index if not exists growth_milestones_goal_idx on growth_milestones (goal_id);",
      "",
      "create table if not exists growth_checkins (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text not null,",
      "  mood text not null default '',",
      "  note text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_checkins_user_idx on growth_checkins (user_id, created_at desc);",
      "",
      "create table if not exists growth_alignment_history (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text not null,",
      "  week_key text not null,",
      "  week_start date not null,",
      "  score integer not null default 0,",
      "  stats jsonb not null default '{}'::jsonb,",
      "  updated_at timestamptz not null default now(),",
      "  unique (user_id, week_key)",
      ");",
      "create index if not exists growth_alignment_user_idx on growth_alignment_history (user_id, week_start desc);",
      "",
      "create table if not exists growth_streak_state (",
      "  user_id text primary key,",
      "  pause_until timestamptz,",
      "  pause_reason text,",
      "  pause_started_at timestamptz,",
      "  updated_at timestamptz not null default now()",
      ");"
    ].join("\n"),
  envLines: () => [
    "",
    "# Becoming — Growth Dashboard. Set to false to switch the growth dashboard off.",
    "FEATURE_GROWTH=true",
    "# Optional: alignment score (0-100) a week must reach to keep the streak. Default 50.",
    "GROWTH_ALIGNMENT_THRESHOLD=50"
  ],
  homeLinks: () => ['        <a className="button" href="/growth">Growth</a>'],
  navLinks: () => [{ href: "/growth", label: "Growth" }]
};
