// branding-design — in-app branding settings + simple design editing/templates,
// ported from ChurchConnect's real design system:
//   - src/components/ChurchBrandingSettings.tsx: the per-user branding record
//     (church_branding table) with fields church_name, tagline, logo_url,
//     primary_color, secondary_color, accent_color, font_heading, font_body,
//     website_url, phone, address; loaded per user (eq user_id, maybeSingle) and
//     saved as a single-row upsert (insert when none, update when brandingId set);
//     the fixed font option list (Inter, Roboto, Open Sans, Lato, Montserrat,
//     Playfair Display, Merriweather, Georgia, Times New Roman, Arial) and the
//     colors/typography/header live preview.
//   - src/components/InAppDesignEditor.tsx: DESIGN_TEMPLATES (id, name, width,
//     height, category, backgroundColor) — Modern Church Flyer, Instagram Post,
//     Facebook Event Cover, Bulletin Cover — the "choose a template to start
//     designing" pick grid, and saveDesign(), which writes a saved design
//     (canva_design_assets: title, design_type, category, width, height,
//     export_url) scoped to the creator.
// Generalized off the church framing into plain copy so it drops into any app.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_BRANDING); each customer owns their own branding and
// designs (scoped by user.id), admins can see everyone's designs.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/branding-design-options.ts (pure options, client-safe) ------
// The branding form is a client component; the font list lives in a file with
// no database driver so importing it never pulls @/lib/db/client toward the
// client bundle.

function brandingOptionsFile(): GeneratedModuleFile {
  return file("src/lib/db/branding-design-options.ts", [
    "// Pure branding option lists — importable from client components (no",
    "// database driver in this file).",
    "",
    "// The font choices, ported verbatim from ChurchBrandingSettings.tsx fontOptions.",
    "export const FONT_OPTIONS = [",
    '  "Inter",',
    '  "Roboto",',
    '  "Open Sans",',
    '  "Lato",',
    '  "Montserrat",',
    '  "Playfair Display",',
    '  "Merriweather",',
    '  "Georgia",',
    '  "Times New Roman",',
    '  "Arial"',
    "];"
  ]);
}

// ---- src/lib/db/branding-design.ts (model + queries) ------------------------

function brandingLibFile(): GeneratedModuleFile {
  return file("src/lib/db/branding-design.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    'import { FONT_OPTIONS } from "@/lib/db/branding-design-options";',
    "",
    "// Re-exported for server-side callers; client components import the options",
    "// from @/lib/db/branding-design-options directly (keeps the db driver server-only).",
    "export { FONT_OPTIONS };",
    "",
    "// A per-owner branding record, ported from ChurchBrandingSettings.tsx formData:",
    "// name/tagline/logo, the three brand colors, heading + body fonts, and contact",
    "// details. Exactly one row per owner (user_id), created on first save.",
    "export type BrandingSettings = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  brandName: string;",
    "  tagline: string;",
    "  logoUrl: string;",
    "  primaryColor: string;",
    "  secondaryColor: string;",
    "  accentColor: string;",
    "  fontHeading: string;",
    "  fontBody: string;",
    "  websiteUrl: string;",
    "  phone: string;",
    "  address: string;",
    "};",
    "",
    "// The defaults, ported verbatim from ChurchBrandingSettings.tsx useState.",
    "export const DEFAULT_BRANDING: Omit<BrandingSettings, \"id\" | \"ownerId\"> = {",
    '  brandName: "",',
    '  tagline: "",',
    '  logoUrl: "",',
    '  primaryColor: "#3B82F6",',
    '  secondaryColor: "#1E40AF",',
    '  accentColor: "#10B981",',
    '  fontHeading: "Inter",',
    '  fontBody: "Inter",',
    '  websiteUrl: "",',
    '  phone: "",',
    '  address: ""',
    "};",
    "",
    "// A design template, ported from InAppDesignEditor.tsx DESIGN_TEMPLATES. The",
    "// canvas element list drives the real editor; here we carry the pickable",
    "// template metadata (size + category + background) that the pick grid shows.",
    "export type DesignTemplate = {",
    "  id: string;",
    "  name: string;",
    "  width: number;",
    "  height: number;",
    "  category: string;",
    "  backgroundColor: string;",
    "};",
    "",
    "// The four starter templates, ported verbatim from DESIGN_TEMPLATES.",
    "export const DESIGN_TEMPLATES: DesignTemplate[] = [",
    '  { id: "flyer-modern", name: "Modern Flyer", width: 816, height: 1056, category: "flyer", backgroundColor: "#ffffff" },',
    '  { id: "social-instagram", name: "Instagram Post", width: 1080, height: 1080, category: "social", backgroundColor: "#f3f4f6" },',
    '  { id: "facebook-event", name: "Facebook Event Cover", width: 1200, height: 628, category: "social", backgroundColor: "#ffffff" },',
    '  { id: "bulletin-cover", name: "Bulletin Cover", width: 816, height: 1056, category: "print", backgroundColor: "#ffffff" }',
    "];",
    "",
    "export function getTemplate(id: string): DesignTemplate | null {",
    "  return DESIGN_TEMPLATES.find((template) => template.id === id) || null;",
    "}",
    "",
    "// A saved design, ported from InAppDesignEditor.tsx saveDesign / canva_design_assets:",
    "// a titled export (data URL) with the template's size + category, owned by its creator.",
    "export type SavedDesign = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  designType: string;",
    "  category: string;",
    "  width: number;",
    "  height: number;",
    "  exportUrl: string;",
    "  createdAt: string;",
    "};",
    "",
    "const fallbackBranding: BrandingSettings = {",
    '  id: "sample-branding",',
    "  ownerId: null,",
    "  ...DEFAULT_BRANDING,",
    '  brandName: "Your Brand",',
    '  tagline: "A few words about what you do",',
    '  primaryColor: "#3B82F6",',
    '  secondaryColor: "#1E40AF",',
    '  accentColor: "#10B981"',
    "};",
    "",
    "const fallbackDesigns: SavedDesign[] = [",
    '  { id: "sample-design-1", ownerId: null, title: "Welcome Flyer", designType: "flyer", category: "flyer", width: 816, height: 1056, exportUrl: "", createdAt: "2025-01-01T00:00:00.000Z" },',
    '  { id: "sample-design-2", ownerId: null, title: "Event Announcement", designType: "social", category: "social", width: 1080, height: 1080, exportUrl: "", createdAt: "2025-02-01T00:00:00.000Z" }',
    "];",
    "",
    "function rowToBranding(row: Record<string, unknown>): BrandingSettings {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    brandName: String(row.brand_name || ""),',
    '    tagline: String(row.tagline || ""),',
    '    logoUrl: String(row.logo_url || ""),',
    '    primaryColor: String(row.primary_color || DEFAULT_BRANDING.primaryColor),',
    '    secondaryColor: String(row.secondary_color || DEFAULT_BRANDING.secondaryColor),',
    '    accentColor: String(row.accent_color || DEFAULT_BRANDING.accentColor),',
    '    fontHeading: String(row.font_heading || DEFAULT_BRANDING.fontHeading),',
    '    fontBody: String(row.font_body || DEFAULT_BRANDING.fontBody),',
    '    websiteUrl: String(row.website_url || ""),',
    '    phone: String(row.phone || ""),',
    '    address: String(row.address || "")',
    "  };",
    "}",
    "",
    "function rowToDesign(row: Record<string, unknown>): SavedDesign {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    title: String(row.title || "Untitled Design"),',
    '    designType: String(row.design_type || "general"),',
    '    category: String(row.category || "general"),',
    "    width: Number(row.width || 0),",
    "    height: Number(row.height || 0),",
    '    exportUrl: String(row.export_url || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// Load an owner's branding, ported from fetchBranding (eq user_id, maybeSingle).",
    "// Returns the app defaults when the owner has not saved anything yet.",
    "export async function getBranding(ownerId: string): Promise<BrandingSettings> {",
    "  if (!hasDatabase()) {",
    "    return { ...fallbackBranding, ownerId };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, brand_name, tagline, logo_url, primary_color, secondary_color,",
    "        accent_color, font_heading, font_body, website_url, phone, address",
    "      from branding_design_settings where owner_id = ${ownerId} limit 1`;",
    "    if (rows[0]) return rowToBranding(rows[0]);",
    "  } catch {",
    "    // fall through to defaults",
    "  }",
    '  return { id: "", ownerId, ...DEFAULT_BRANDING };',
    "}",
    "",
    "export type SaveBrandingInput = {",
    "  brandName?: string;",
    "  tagline?: string;",
    "  logoUrl?: string;",
    "  primaryColor?: string;",
    "  secondaryColor?: string;",
    "  accentColor?: string;",
    "  fontHeading?: string;",
    "  fontBody?: string;",
    "  websiteUrl?: string;",
    "  phone?: string;",
    "  address?: string;",
    "};",
    "",
    "// Save an owner's branding, ported from handleSave: update the existing row when",
    "// one exists for this owner, otherwise insert the first one (single row per owner).",
    "export async function saveBranding(ownerId: string, input: SaveBrandingInput): Promise<BrandingSettings | null> {",
    "  if (!hasDatabase()) return null;",
    "  const merged = {",
    "    brandName: (input.brandName ?? DEFAULT_BRANDING.brandName).trim(),",
    "    tagline: (input.tagline ?? DEFAULT_BRANDING.tagline).trim(),",
    "    logoUrl: (input.logoUrl ?? DEFAULT_BRANDING.logoUrl).trim(),",
    "    primaryColor: (input.primaryColor || DEFAULT_BRANDING.primaryColor).trim(),",
    "    secondaryColor: (input.secondaryColor || DEFAULT_BRANDING.secondaryColor).trim(),",
    "    accentColor: (input.accentColor || DEFAULT_BRANDING.accentColor).trim(),",
    "    fontHeading: (input.fontHeading || DEFAULT_BRANDING.fontHeading).trim(),",
    "    fontBody: (input.fontBody || DEFAULT_BRANDING.fontBody).trim(),",
    "    websiteUrl: (input.websiteUrl ?? DEFAULT_BRANDING.websiteUrl).trim(),",
    "    phone: (input.phone ?? DEFAULT_BRANDING.phone).trim(),",
    "    address: (input.address ?? DEFAULT_BRANDING.address).trim()",
    "  };",
    "  try {",
    "    const sql = getDatabase();",
    "    const existing = await sql`select id from branding_design_settings where owner_id = ${ownerId} limit 1`;",
    "    if (existing[0]) {",
    "      const rows = await sql`",
    "        update branding_design_settings set",
    "          brand_name = ${merged.brandName}, tagline = ${merged.tagline}, logo_url = ${merged.logoUrl},",
    "          primary_color = ${merged.primaryColor}, secondary_color = ${merged.secondaryColor},",
    "          accent_color = ${merged.accentColor}, font_heading = ${merged.fontHeading},",
    "          font_body = ${merged.fontBody}, website_url = ${merged.websiteUrl}, phone = ${merged.phone},",
    "          address = ${merged.address}, updated_at = now()",
    "        where id = ${existing[0].id}",
    "        returning id, owner_id, brand_name, tagline, logo_url, primary_color, secondary_color,",
    "          accent_color, font_heading, font_body, website_url, phone, address`;",
    "      return rows[0] ? rowToBranding(rows[0]) : null;",
    "    }",
    "    const rows = await sql`",
    "      insert into branding_design_settings (",
    "        owner_id, brand_name, tagline, logo_url, primary_color, secondary_color,",
    "        accent_color, font_heading, font_body, website_url, phone, address",
    "      ) values (",
    "        ${ownerId}, ${merged.brandName}, ${merged.tagline}, ${merged.logoUrl},",
    "        ${merged.primaryColor}, ${merged.secondaryColor}, ${merged.accentColor},",
    "        ${merged.fontHeading}, ${merged.fontBody}, ${merged.websiteUrl}, ${merged.phone}, ${merged.address}",
    "      )",
    "      returning id, owner_id, brand_name, tagline, logo_url, primary_color, secondary_color,",
    "        accent_color, font_heading, font_body, website_url, phone, address`;",
    "    return rows[0] ? rowToBranding(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// List an owner's saved designs, newest first. Admins may pass all=true to see",
    "// everyone's (ported from the church-wide asset library view).",
    "export async function listDesigns(ownerId: string, all = false): Promise<SavedDesign[]> {",
    "  if (!hasDatabase()) return fallbackDesigns;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = all",
    "      ? await sql`",
    "          select id, owner_id, title, design_type, category, width, height, export_url, created_at",
    "          from branding_design_designs order by created_at desc limit 200`",
    "      : await sql`",
    "          select id, owner_id, title, design_type, category, width, height, export_url, created_at",
    "          from branding_design_designs where owner_id = ${ownerId} order by created_at desc limit 200`;",
    "    return rows.map(rowToDesign);",
    "  } catch {",
    "    return fallbackDesigns;",
    "  }",
    "}",
    "",
    "export async function getDesign(id: string): Promise<SavedDesign | null> {",
    "  if (!hasDatabase()) return fallbackDesigns.find((design) => design.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, title, design_type, category, width, height, export_url, created_at",
    "      from branding_design_designs where id = ${id} limit 1`;",
    "    return rows[0] ? rowToDesign(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SaveDesignInput = {",
    "  title: string;",
    "  templateId?: string;",
    "  exportUrl?: string;",
    "};",
    "",
    "// Save a design, ported from InAppDesignEditor.tsx saveDesign: title + the picked",
    "// template's category/size become design_type/category/width/height, plus the",
    "// export data URL. Owned by its creator.",
    "export async function saveDesign(ownerId: string, input: SaveDesignInput): Promise<SavedDesign | null> {",
    "  if (!hasDatabase()) return null;",
    "  const template = input.templateId ? getTemplate(input.templateId) : null;",
    '  const category = template ? template.category : "general";',
    "  const width = template ? template.width : 0;",
    "  const height = template ? template.height : 0;",
    '  const title = (input.title || "Untitled Design").trim() || "Untitled Design";',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into branding_design_designs (",
    "        owner_id, title, design_type, category, width, height, export_url",
    "      ) values (",
    '        ${ownerId}, ${title}, ${category}, ${category}, ${width}, ${height}, ${input.exportUrl || ""}',
    "      )",
    "      returning id, owner_id, title, design_type, category, width, height, export_url, created_at`;",
    "    return rows[0] ? rowToDesign(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function deleteDesign(ownerId: string, id: string, isAdmin: boolean): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    if (isAdmin) {",
    "      await sql`delete from branding_design_designs where id = ${id}`;",
    "    } else {",
    "      await sql`delete from branding_design_designs where id = ${id} and owner_id = ${ownerId}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function brandingEnabled(): boolean {",
    '  return process.env.FEATURE_BRANDING !== "false";',
    "}"
  ]);
}

// ---- src/app/api/branding/route.ts (load + save branding) -------------------

function brandingApiFile(): GeneratedModuleFile {
  return file("src/app/api/branding/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getBranding, saveBranding, brandingEnabled } from "@/lib/db/branding-design";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false, message: "Branding is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const branding = await getBranding(String(user.id));",
    "  return NextResponse.json({ ok: true, branding });",
    "}",
    "",
    "// Each owner saves their own single branding record.",
    "export async function POST(request: Request) {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in to save your branding." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const str = (v: unknown) => (typeof v === \"string\" ? v : undefined);",
    "  const saved = await saveBranding(String(user.id), {",
    "    brandName: str(body.brandName),",
    "    tagline: str(body.tagline),",
    "    logoUrl: str(body.logoUrl),",
    "    primaryColor: str(body.primaryColor),",
    "    secondaryColor: str(body.secondaryColor),",
    "    accentColor: str(body.accentColor),",
    "    fontHeading: str(body.fontHeading),",
    "    fontBody: str(body.fontBody),",
    "    websiteUrl: str(body.websiteUrl),",
    "    phone: str(body.phone),",
    "    address: str(body.address)",
    "  });",
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save your branding." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, branding: saved, message: "Branding saved." });',
    "}"
  ]);
}

// ---- src/app/api/branding/designs/route.ts (list + save designs) ------------

function designsApiFile(): GeneratedModuleFile {
  return file("src/app/api/branding/designs/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listDesigns, saveDesign, brandingEnabled } from "@/lib/db/branding-design";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const all = url.searchParams.get("all") === "true" && canAccessAdmin(user.role);',
    "  const designs = await listDesigns(String(user.id), all);",
    "  return NextResponse.json({ ok: true, designs });",
    "}",
    "",
    "// Save a design the owner just made, ported from saveDesign.",
    "export async function POST(request: Request) {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in to save designs." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 1) {",
    '    return NextResponse.json({ ok: false, message: "Give your design a title." }, { status: 400 });',
    "  }",
    "  const saved = await saveDesign(String(user.id), {",
    "    title,",
    '    templateId: typeof body.templateId === "string" ? body.templateId : undefined,',
    '    exportUrl: typeof body.exportUrl === "string" ? body.exportUrl : undefined',
    "  });",
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save designs." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, design: saved });",
    "}"
  ]);
}

// ---- src/app/api/branding/designs/[id]/route.ts (detail + delete) -----------

function designDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/branding/designs/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getDesign, deleteDesign, brandingEnabled } from "@/lib/db/branding-design";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const design = await getDesign(id);",
    '  if (!design) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Owners see their own designs; admins see any.",
    "  if (design.ownerId && design.ownerId !== String(user.id) && !canAccessAdmin(user.role)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, design });",
    "}",
    "",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!brandingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const ok = await deleteDesign(String(user.id), id, canAccessAdmin(user.role));",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to manage designs." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/branding/page.tsx (settings + live preview) --------------------

function brandingPageFile(): GeneratedModuleFile {
  return file("src/app/branding/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getBranding, DEFAULT_BRANDING, brandingEnabled } from "@/lib/db/branding-design";',
    'import { BrandingForm } from "./branding-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function BrandingPage() {",
    "  if (!brandingEnabled()) {",
    '    return (<main className="shell"><h1>Branding</h1><p>Branding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/branding");',
    "  const user = await getCurrentUser();",
    '  const branding = user ? await getBranding(String(user.id)) : { id: "", ownerId: null, ...DEFAULT_BRANDING };',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Branding</p>',
    "      <h1>Your brand</h1>",
    "      <p>Set your name, logo, brand colors, and fonts. Every template you make picks these up.</p>",
    "      <BrandingForm initial={branding} />",
    '      <p><Link className="button" href="/branding/templates">Design something with your brand</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/branding/branding-form.tsx (client: form + live preview) -------

function brandingFormFile(): GeneratedModuleFile {
  return file("src/app/branding/branding-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    'import { FONT_OPTIONS } from "@/lib/db/branding-design-options";',
    "",
    "type BrandingValues = {",
    "  brandName: string;",
    "  tagline: string;",
    "  logoUrl: string;",
    "  primaryColor: string;",
    "  secondaryColor: string;",
    "  accentColor: string;",
    "  fontHeading: string;",
    "  fontBody: string;",
    "  websiteUrl: string;",
    "  phone: string;",
    "  address: string;",
    "};",
    "",
    "export function BrandingForm({ initial }: { initial: BrandingValues }) {",
    "  const router = useRouter();",
    "  const [values, setValues] = useState<BrandingValues>(initial);",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  function set<K extends keyof BrandingValues>(key: K, value: BrandingValues[K]) {",
    "    setValues((prev) => ({ ...prev, [key]: value }));",
    "  }",
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/branding", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(values)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save your branding.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Branding saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="grid">',
    '      <form className="stack" onSubmit={submit}>',
    "        <label className=\"field\">Brand name",
    '          <input className="input" value={values.brandName} onChange={(e) => set("brandName", e.target.value)} placeholder="Your Brand" />',
    "        </label>",
    "        <label className=\"field\">Tagline",
    '          <input className="input" value={values.tagline} onChange={(e) => set("tagline", e.target.value)} placeholder="A few words about what you do" />',
    "        </label>",
    "        <label className=\"field\">Logo URL",
    '          <input className="input" type="url" value={values.logoUrl} onChange={(e) => set("logoUrl", e.target.value)} placeholder="https://example.com/logo.png" />',
    "        </label>",
    "        <label className=\"field\">Primary color",
    '          <span className="color-row">',
    '            <input type="color" value={values.primaryColor} onChange={(e) => set("primaryColor", e.target.value)} aria-label="Primary color picker" />',
    '            <input className="input" value={values.primaryColor} onChange={(e) => set("primaryColor", e.target.value)} />',
    "          </span>",
    "        </label>",
    "        <label className=\"field\">Secondary color",
    '          <span className="color-row">',
    '            <input type="color" value={values.secondaryColor} onChange={(e) => set("secondaryColor", e.target.value)} aria-label="Secondary color picker" />',
    '            <input className="input" value={values.secondaryColor} onChange={(e) => set("secondaryColor", e.target.value)} />',
    "          </span>",
    "        </label>",
    "        <label className=\"field\">Accent color",
    '          <span className="color-row">',
    '            <input type="color" value={values.accentColor} onChange={(e) => set("accentColor", e.target.value)} aria-label="Accent color picker" />',
    '            <input className="input" value={values.accentColor} onChange={(e) => set("accentColor", e.target.value)} />',
    "          </span>",
    "        </label>",
    "        <label className=\"field\">Heading font",
    '          <select className="input" value={values.fontHeading} onChange={(e) => set("fontHeading", e.target.value)}>',
    "            {FONT_OPTIONS.map((font) => (<option key={font} value={font}>{font}</option>))}",
    "          </select>",
    "        </label>",
    "        <label className=\"field\">Body font",
    '          <select className="input" value={values.fontBody} onChange={(e) => set("fontBody", e.target.value)}>',
    "            {FONT_OPTIONS.map((font) => (<option key={font} value={font}>{font}</option>))}",
    "          </select>",
    "        </label>",
    "        <label className=\"field\">Website",
    '          <input className="input" type="url" value={values.websiteUrl} onChange={(e) => set("websiteUrl", e.target.value)} placeholder="https://www.example.com" />',
    "        </label>",
    "        <label className=\"field\">Phone",
    '          <input className="input" type="tel" value={values.phone} onChange={(e) => set("phone", e.target.value)} placeholder="(555) 123-4567" />',
    "        </label>",
    "        <label className=\"field\">Address",
    '          <textarea className="input" rows={2} value={values.address} onChange={(e) => set("address", e.target.value)} placeholder="123 Main Street, City, State 12345" />',
    "        </label>",
    '        {message ? <p className="note" role={status === "error" ? "alert" : "status"}>{message}</p> : null}',
    '        <button className="button primary" type="submit" disabled={status === "saving"}>',
    '          {status === "saving" ? "Saving…" : "Save branding"}',
    "        </button>",
    "      </form>",
    "",
    "      {/* Live preview, ported from ChurchBrandingSettings.tsx preview panel. */}",
    '      <aside className="panel" aria-label="Branding preview">',
    "        <h2>Preview</h2>",
    '        <div className="swatch-row">',
    '          <span className="swatch" style={{ backgroundColor: values.primaryColor }} title={values.primaryColor} />',
    '          <span className="swatch" style={{ backgroundColor: values.secondaryColor }} title={values.secondaryColor} />',
    '          <span className="swatch" style={{ backgroundColor: values.accentColor }} title={values.accentColor} />',
    "        </div>",
    "        <div",
    '          className="brand-header"',
    "          style={{",
    "            background: `linear-gradient(135deg, ${values.primaryColor}, ${values.secondaryColor})`,",
    "            fontFamily: values.fontHeading,",
    '            color: "#ffffff",',
    '            padding: "1.5rem",',
    '            borderRadius: "0.5rem",',
    '            textAlign: "center"',
    "          }}",
    "        >",
    '          {values.logoUrl ? <img src={values.logoUrl} alt="" style={{ height: "48px", margin: "0 auto 0.5rem" }} /> : null}',
    '          <strong style={{ display: "block", fontSize: "1.25rem" }}>{values.brandName || "Your Brand"}</strong>',
    "          {values.tagline ? <span>{values.tagline}</span> : null}",
    "        </div>",
    '        <p style={{ fontFamily: values.fontBody }}>Body text appears in {values.fontBody}. This is how your content will read.</p>',
    "      </aside>",
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/branding/templates/page.tsx (template pick + saved designs) -----

function templatesPageFile(): GeneratedModuleFile {
  return file("src/app/branding/templates/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { DESIGN_TEMPLATES, listDesigns, brandingEnabled, getBranding, DEFAULT_BRANDING } from "@/lib/db/branding-design";',
    'import { TemplatePicker } from "./template-picker";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TemplatesPage() {",
    "  if (!brandingEnabled()) {",
    '    return (<main className="shell"><h1>Templates</h1><p>Branding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/branding/templates");',
    "  const user = await getCurrentUser();",
    '  const branding = user ? await getBranding(String(user.id)) : { id: "", ownerId: null, ...DEFAULT_BRANDING };',
    "  const designs = user ? await listDesigns(String(user.id)) : [];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Design</p>',
    "      <h1>Choose a template</h1>",
    "      <p>Pick a starting point. Your brand colors and fonts come along automatically.</p>",
    "      <TemplatePicker",
    "        templates={DESIGN_TEMPLATES}",
    "        primaryColor={branding.primaryColor}",
    "        headingFont={branding.fontHeading}",
    "      />",
    "      <h2>Your saved designs</h2>",
    "      {designs.length === 0 ? (",
    '        <p className="note">You have not saved any designs yet. Pick a template above to start.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {designs.map((design) => (",
    '            <article className="wide-card" key={design.id}>',
    "              <span>{design.category}</span>",
    "              <strong>{design.title}</strong>",
    '              <p className="note">{design.width} × {design.height}px</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/branding">Back to branding</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/branding/templates/template-picker.tsx (client) ----------------

function templatePickerFile(): GeneratedModuleFile {
  return file("src/app/branding/templates/template-picker.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type DesignTemplate = {",
    "  id: string;",
    "  name: string;",
    "  width: number;",
    "  height: number;",
    "  category: string;",
    "  backgroundColor: string;",
    "};",
    "",
    "export function TemplatePicker({",
    "  templates,",
    "  primaryColor,",
    "  headingFont",
    "}: {",
    "  templates: DesignTemplate[];",
    "  primaryColor: string;",
    "  headingFont: string;",
    "}) {",
    "  const router = useRouter();",
    "  const [selected, setSelected] = useState<DesignTemplate | null>(null);",
    '  const [title, setTitle] = useState<string>("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  function pick(template: DesignTemplate) {",
    "    setSelected(template);",
    "    setTitle(template.name);",
    '    setStatus("idle");',
    '    setMessage("");',
    "  }",
    "",
    "  async function save() {",
    "    if (!selected) return;",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/branding/designs", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ title, templateId: selected.id })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save this design.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Saved to your designs.");',
    "      setSelected(null);",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <section className="stack">',
    '      <div className="grid">',
    "        {templates.map((template) => (",
    "          <button",
    '            type="button"',
    "            key={template.id}",
    '            className={selected?.id === template.id ? "wide-card selected" : "wide-card"}',
    "            onClick={() => pick(template)}",
    "          >",
    "            <div",
    "              style={{",
    "                background: template.backgroundColor,",
    "                borderTop: `6px solid ${primaryColor}`,",
    "                fontFamily: headingFont,",
    '                aspectRatio: `${template.width} / ${template.height}`,',
    '                display: "flex",',
    '                alignItems: "center",',
    '                justifyContent: "center",',
    '                minHeight: "120px"',
    "              }}",
    "            >",
    "              <span>{template.name}</span>",
    "            </div>",
    "            <strong>{template.name}</strong>",
    '            <p className="note">{template.width} × {template.height}px · {template.category}</p>',
    "          </button>",
    "        ))}",
    "      </div>",
    "      {selected ? (",
    '        <div className="panel stack" aria-live="polite">',
    "          <h3>Save “{selected.name}”</h3>",
    '          <input className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Design title" aria-label="Design title" />',
    '          {message ? <p className="note" role={status === "error" ? "alert" : "status"}>{message}</p> : null}',
    '          <button className="button primary" type="button" onClick={save} disabled={status === "saving" || title.trim().length < 1}>',
    '            {status === "saving" ? "Saving…" : "Save to my designs"}',
    "          </button>",
    "        </div>",
    "      ) : (",
    '        status === "done" ? <p className="note" role="status">{message}</p> : null',
    "      )}",
    "    </section>",
    "  );",
    "}"
  ]);
}

export const brandingDesignModule: AppModule = {
  slug: "branding-design",
  name: "Branding & Design",
  tier: "optional",
  featureFlagEnv: "FEATURE_BRANDING",
  files: () => [
    brandingOptionsFile(),
    brandingLibFile(),
    brandingApiFile(),
    designsApiFile(),
    designDetailApiFile(),
    brandingPageFile(),
    brandingFormFile(),
    templatesPageFile(),
    templatePickerFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists branding_design_settings (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  brand_name text not null default '',",
      "  tagline text not null default '',",
      "  logo_url text not null default '',",
      "  primary_color text not null default '#3B82F6',",
      "  secondary_color text not null default '#1E40AF',",
      "  accent_color text not null default '#10B981',",
      "  font_heading text not null default 'Inter',",
      "  font_body text not null default 'Inter',",
      "  website_url text not null default '',",
      "  phone text not null default '',",
      "  address text not null default '',",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists branding_design_settings_owner_idx on branding_design_settings (owner_id);",
      "",
      "create table if not exists branding_design_designs (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  title text not null default 'Untitled Design',",
      "  design_type text not null default 'general',",
      "  category text not null default 'general',",
      "  width integer not null default 0,",
      "  height integer not null default 0,",
      "  export_url text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists branding_design_designs_owner_idx on branding_design_designs (owner_id, created_at desc);"
    ].join("\n"),
  envLines: () => [
    "",
    "# Branding & Design — set to false to switch branding settings + templates off.",
    "FEATURE_BRANDING=true"
  ],
  homeLinks: () => ['        <a className="button" href="/branding">Branding</a>'],
  navLinks: () => [{ href: "/branding", label: "Branding" }]
};