// business-formation-provisioning — guide a customer from signup into domain,
// email, business formation, and service provisioning. Ported from the real
// "Website-friends" hosting SaaS:
//   - SignupPage.tsx: on signup, create a client profile (full_name, business_name,
//     email, phone, status='active') then a subscription (plan_type='basic',
//     monthly_fee=5.00, status='active', current_period_start/end, next_billing_date
//     one month out). Here the client IS the signed-in user, so we scope the
//     onboarding/client row by users(id) and derive fields from the signup form.
//   - ClientPortal.tsx: the portal that loads a client + subscription + websites +
//     domains + email_accounts + payments + service_requests and shows the
//     provisioning checklist (websites/domains/emails counts, subscription card,
//     recent service requests + payments, per-domain expiry/cost, per-email server
//     settings). Ported the model + the load fan-out + the "What You Get" checklist.
//   - provision-wordpress/index.ts: the provisioning job — record an automation job
//     (job_type='wordpress_setup', status processing→completed/failed, request_data,
//     started_at/completed_at), and on success create a website row (site_name,
//     site_url, status='active', divi_enabled). Generalized off DreamHost/ENOM
//     provider names into a neutral "provisioning" run on the app's own DB.
// Every provider name is dropped from what users see. Runs on the app owner's own
// database with graceful sample-data fallback, feature-flagged (FEATURE_FORMATION);
// customers see their own portal + request services, admins run provisioning +
// review requests.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/formation.ts (model + queries) ------------------------------

function formationLibFile(): GeneratedModuleFile {
  return file("src/lib/db/formation.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The onboarding / client profile, ported from SignupPage.tsx's clients insert",
    "// (full_name, business_name, email, phone, status). One per user — the person",
    "// we are guiding from signup into a provisioned business.",
    "export type ClientProfile = {",
    "  id: string;",
    "  ownerId: string;",
    "  fullName: string;",
    "  businessName: string;",
    "  email: string;",
    "  phone: string;",
    "  status: string;",
    "  createdAt: string;",
    "};",
    "",
    "// The subscription created alongside the client at signup (plan_type='basic',",
    "// monthly_fee=5.00, active, billing window one month out).",
    "export type Subscription = {",
    "  id: string;",
    "  clientId: string;",
    "  planType: string;",
    "  monthlyFee: number;",
    "  status: string;",
    "  currentPeriodStart: string;",
    "  currentPeriodEnd: string;",
    "  nextBillingDate: string;",
    "};",
    "",
    "// A registered domain, ported from the ClientPortal domains model.",
    "export type Domain = {",
    "  id: string;",
    "  clientId: string;",
    "  domainName: string;",
    "  status: string;",
    "  registrationDate: string;",
    "  expirationDate: string;",
    "  cost: number;",
    "  autoRenew: boolean;",
    "  privacyProtection: boolean;",
    "};",
    "",
    "// A provisioned website, ported from the websites model + provision-wordpress.",
    "export type Website = {",
    "  id: string;",
    "  clientId: string;",
    "  domainId: string | null;",
    "  siteName: string;",
    "  siteUrl: string;",
    "  status: string;",
    "  diviEnabled: boolean;",
    "  aiDesignerUsed: boolean;",
    "  sslEnabled: boolean;",
    "  deploymentDate: string;",
    "};",
    "",
    "// A mailbox on one of the client's domains, ported from email_accounts.",
    "export type EmailAccount = {",
    "  id: string;",
    "  clientId: string;",
    "  domainId: string | null;",
    "  emailAddress: string;",
    "  status: string;",
    "  mailServer: string;",
    "  webmailUrl: string;",
    "  storageUsedMb: number;",
    "  createdAt: string;",
    "};",
    "",
    "// A payment on the account, ported from the payments model.",
    "export type Payment = {",
    "  id: string;",
    "  clientId: string;",
    "  amount: number;",
    "  status: string;",
    "  paymentType: string;",
    "  paymentDate: string;",
    "};",
    "",
    "// A service request the client raises (a new site, a domain, a mailbox), ported",
    "// from the service_requests model that the portal Services tab hangs off of.",
    "export type ServiceRequest = {",
    "  id: string;",
    "  clientId: string;",
    "  title: string;",
    "  description: string;",
    "  requestType: string;",
    "  status: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A provisioning job, ported from provision-wordpress: it moves processing ->",
    "// completed/failed and, on success, materializes a website.",
    "export type ProvisioningJob = {",
    "  id: string;",
    "  clientId: string;",
    "  jobType: string;",
    "  status: string;",
    "  requestData: Record<string, unknown>;",
    "  errorMessage: string;",
    "  startedAt: string;",
    "  completedAt: string;",
    "};",
    "",
    "// The whole portal payload, ported from ClientPortal.loadClientData's fan-out.",
    "export type PortalData = {",
    "  client: ClientProfile | null;",
    "  subscription: Subscription | null;",
    "  domains: Domain[];",
    "  websites: Website[];",
    "  emails: EmailAccount[];",
    "  payments: Payment[];",
    "  requests: ServiceRequest[];",
    "};",
    "",
    "// The request types a client can raise, ported in spirit from the portal's",
    "// Services tab (website / domain / email / support).",
    "export const SERVICE_REQUEST_TYPES = [",
    '  "website",',
    '  "domain",',
    '  "email",',
    '  "support"',
    "];",
    "",
    "// The $5/month basic plan the signup flow provisions, ported verbatim from",
    "// SignupPage.tsx (plan_type='basic', monthly_fee=5.00).",
    "export const DEFAULT_PLAN = { planType: \"basic\", monthlyFee: 5.0 };",
    "",
    "function isoDate(d: Date): string {",
    '  return d.toISOString().split("T")[0];',
    "}",
    "",
    "// ---- graceful sample data (used when no database is connected) ----",
    "",
    "const sampleClient: ClientProfile = {",
    '  id: "sample-client",',
    '  ownerId: "sample-user",',
    '  fullName: "Jordan Lee",',
    '  businessName: "Lee & Co.",',
    '  email: "jordan@example.com",',
    '  phone: "(555) 123-4567",',
    '  status: "active",',
    '  createdAt: "2025-01-01T00:00:00.000Z"',
    "};",
    "",
    "const sampleSubscription: Subscription = {",
    '  id: "sample-sub",',
    '  clientId: "sample-client",',
    '  planType: "basic",',
    "  monthlyFee: 5.0,",
    '  status: "active",',
    '  currentPeriodStart: "2025-01-01",',
    '  currentPeriodEnd: "2025-02-01",',
    '  nextBillingDate: "2025-02-01"',
    "};",
    "",
    "const sampleDomains: Domain[] = [",
    "  {",
    '    id: "sample-domain",',
    '    clientId: "sample-client",',
    '    domainName: "leeandco.com",',
    '    status: "active",',
    '    registrationDate: "2025-01-02",',
    '    expirationDate: "2026-01-02",',
    "    cost: 14.99,",
    "    autoRenew: true,",
    "    privacyProtection: true",
    "  }",
    "];",
    "",
    "const sampleWebsites: Website[] = [",
    "  {",
    '    id: "sample-site",',
    '    clientId: "sample-client",',
    '    domainId: "sample-domain",',
    '    siteName: "Lee & Co. Home",',
    '    siteUrl: "https://leeandco.com",',
    '    status: "active",',
    "    diviEnabled: true,",
    "    aiDesignerUsed: true,",
    "    sslEnabled: true,",
    '    deploymentDate: "2025-01-03T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const sampleEmails: EmailAccount[] = [",
    "  {",
    '    id: "sample-email",',
    '    clientId: "sample-client",',
    '    domainId: "sample-domain",',
    '    emailAddress: "hello@leeandco.com",',
    '    status: "active",',
    '    mailServer: "mail.leeandco.com",',
    '    webmailUrl: "",',
    "    storageUsedMb: 42,",
    '    createdAt: "2025-01-03T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const samplePayments: Payment[] = [",
    "  {",
    '    id: "sample-payment",',
    '    clientId: "sample-client",',
    "    amount: 5.0,",
    '    status: "completed",',
    '    paymentType: "subscription",',
    '    paymentDate: "2025-01-01"',
    "  }",
    "];",
    "",
    "const sampleRequests: ServiceRequest[] = [",
    "  {",
    '    id: "sample-request",',
    '    clientId: "sample-client",',
    '    title: "Register a new domain",',
    '    description: "I would like leeandco.io for a landing page.",',
    '    requestType: "domain",',
    '    status: "pending",',
    '    createdAt: "2025-01-05T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "// ---- row mappers ----",
    "",
    "function rowToClient(row: Record<string, unknown>): ClientProfile {",
    "  return {",
    "    id: String(row.id),",
    '    ownerId: row.owner_id != null ? String(row.owner_id) : "",',
    '    fullName: String(row.full_name || ""),',
    '    businessName: String(row.business_name || ""),',
    '    email: String(row.email || ""),',
    '    phone: String(row.phone || ""),',
    '    status: String(row.status || "active"),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToSubscription(row: Record<string, unknown>): Subscription {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    '    planType: String(row.plan_type || "basic"),',
    "    monthlyFee: Number(row.monthly_fee || 0),",
    '    status: String(row.status || "active"),',
    '    currentPeriodStart: row.current_period_start ? String(row.current_period_start) : "",',
    '    currentPeriodEnd: row.current_period_end ? String(row.current_period_end) : "",',
    '    nextBillingDate: row.next_billing_date ? String(row.next_billing_date) : ""',
    "  };",
    "}",
    "",
    "function rowToDomain(row: Record<string, unknown>): Domain {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    '    domainName: String(row.domain_name || ""),',
    '    status: String(row.status || "pending"),',
    '    registrationDate: row.registration_date ? String(row.registration_date) : "",',
    '    expirationDate: row.expiration_date ? String(row.expiration_date) : "",',
    "    cost: Number(row.cost || 0),",
    "    autoRenew: row.auto_renew === true || String(row.auto_renew) === \"true\",",
    "    privacyProtection: row.privacy_protection === true || String(row.privacy_protection) === \"true\"",
    "  };",
    "}",
    "",
    "function rowToWebsite(row: Record<string, unknown>): Website {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    "    domainId: row.domain_id != null ? String(row.domain_id) : null,",
    '    siteName: String(row.site_name || ""),',
    '    siteUrl: String(row.site_url || ""),',
    '    status: String(row.status || "active"),',
    "    diviEnabled: row.divi_enabled === true || String(row.divi_enabled) === \"true\",",
    "    aiDesignerUsed: row.ai_designer_used === true || String(row.ai_designer_used) === \"true\",",
    "    sslEnabled: row.ssl_enabled === true || String(row.ssl_enabled) === \"true\",",
    '    deploymentDate: row.deployment_date ? String(row.deployment_date) : ""',
    "  };",
    "}",
    "",
    "function rowToEmail(row: Record<string, unknown>): EmailAccount {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    "    domainId: row.domain_id != null ? String(row.domain_id) : null,",
    '    emailAddress: String(row.email_address || ""),',
    '    status: String(row.status || "active"),',
    '    mailServer: String(row.mail_server || ""),',
    '    webmailUrl: String(row.webmail_url || ""),',
    "    storageUsedMb: Number(row.storage_used_mb || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToPayment(row: Record<string, unknown>): Payment {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    "    amount: Number(row.amount || 0),",
    '    status: String(row.status || "pending"),',
    '    paymentType: String(row.payment_type || ""),',
    '    paymentDate: row.payment_date ? String(row.payment_date) : ""',
    "  };",
    "}",
    "",
    "function rowToRequest(row: Record<string, unknown>): ServiceRequest {",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    requestType: String(row.request_type || "support"),',
    '    status: String(row.status || "pending"),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToJob(row: Record<string, unknown>): ProvisioningJob {",
    "  const parseData = (v: unknown): Record<string, unknown> => {",
    '    if (v && typeof v === "object") return v as Record<string, unknown>;',
    '    if (typeof v === "string" && v.trim()) { try { return JSON.parse(v) as Record<string, unknown>; } catch { return {}; } }',
    "    return {};",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    clientId: String(row.client_id),",
    '    jobType: String(row.job_type || ""),',
    '    status: String(row.status || "processing"),',
    "    requestData: parseData(row.request_data),",
    '    errorMessage: String(row.error_message || ""),',
    '    startedAt: row.started_at ? String(row.started_at) : "",',
    '    completedAt: row.completed_at ? String(row.completed_at) : ""',
    "  };",
    "}",
    "",
    "// ---- onboarding: create-or-get the client, ported from SignupPage handleSubmit",
    "",
    "export type OnboardInput = {",
    "  ownerId: string;",
    "  fullName?: string;",
    "  businessName?: string;",
    "  email?: string;",
    "  phone?: string;",
    "};",
    "",
    "// Fetch the client profile owned by this user.",
    "export async function getClientForOwner(ownerId: string): Promise<ClientProfile | null> {",
    "  if (!hasDatabase()) return { ...sampleClient, ownerId };",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, full_name, business_name, email, phone, status, created_at",
    "      from business_formation_provisioning_clients",
    "      where owner_id = ${ownerId} limit 1`;",
    "    return rows[0] ? rowToClient(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// The signup provisioning step, ported from SignupPage.tsx: insert the client",
    "// (status='active') then a basic subscription with a billing window one month",
    "// out. Idempotent per owner — a second call returns the existing client.",
    "export async function ensureOnboarded(input: OnboardInput): Promise<ClientProfile | null> {",
    "  if (!hasDatabase()) return { ...sampleClient, ownerId: input.ownerId };",
    "  const existing = await getClientForOwner(input.ownerId);",
    "  if (existing) return existing;",
    "  try {",
    "    const sql = getDatabase();",
    '    const fullName = (input.fullName || "").trim();',
    '    const businessName = (input.businessName || "").trim() || null;',
    '    const email = (input.email || "").trim();',
    '    const phone = (input.phone || "").trim() || null;',
    "    const rows = await sql`",
    "      insert into business_formation_provisioning_clients",
    "        (owner_id, full_name, business_name, email, phone, status)",
    "      values (${input.ownerId}, ${fullName}, ${businessName}, ${email}, ${phone}, 'active')",
    "      returning id, owner_id, full_name, business_name, email, phone, status, created_at`;",
    "    const client = rows[0] ? rowToClient(rows[0]) : null;",
    "    if (!client) return null;",
    "    // Subscription window: this month -> next month, ported from SignupPage.tsx.",
    "    const start = new Date();",
    "    const end = new Date(start);",
    "    end.setMonth(end.getMonth() + 1);",
    "    const startStr = isoDate(start);",
    "    const endStr = isoDate(end);",
    "    try {",
    "      await sql`",
    "        insert into business_formation_provisioning_subscriptions",
    "          (client_id, plan_type, monthly_fee, status,",
    "           current_period_start, current_period_end, next_billing_date)",
    "        values (${client.id}, 'basic', 5.00, 'active',",
    "           ${startStr}, ${endStr}, ${endStr})`;",
    "    } catch {",
    "      // Subscription is best-effort; the client profile is already created.",
    "    }",
    "    return client;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "async function getSubscription(clientId: string): Promise<Subscription | null> {",
    "  if (!hasDatabase()) return sampleSubscription;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, plan_type, monthly_fee, status,",
    "        current_period_start, current_period_end, next_billing_date",
    "      from business_formation_provisioning_subscriptions",
    "      where client_id = ${clientId} limit 1`;",
    "    return rows[0] ? rowToSubscription(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "async function listDomains(clientId: string): Promise<Domain[]> {",
    "  if (!hasDatabase()) return sampleDomains;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, domain_name, status, registration_date,",
    "        expiration_date, cost, auto_renew, privacy_protection",
    "      from business_formation_provisioning_domains",
    "      where client_id = ${clientId} order by registration_date desc`;",
    "    return rows.map(rowToDomain);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "async function listWebsites(clientId: string): Promise<Website[]> {",
    "  if (!hasDatabase()) return sampleWebsites;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, domain_id, site_name, site_url, status,",
    "        divi_enabled, ai_designer_used, ssl_enabled, deployment_date",
    "      from business_formation_provisioning_websites",
    "      where client_id = ${clientId} order by deployment_date desc`;",
    "    return rows.map(rowToWebsite);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "async function listEmails(clientId: string): Promise<EmailAccount[]> {",
    "  if (!hasDatabase()) return sampleEmails;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, domain_id, email_address, status, mail_server,",
    "        webmail_url, storage_used_mb, created_at",
    "      from business_formation_provisioning_email_accounts",
    "      where client_id = ${clientId} order by created_at desc`;",
    "    return rows.map(rowToEmail);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "async function listPayments(clientId: string): Promise<Payment[]> {",
    "  if (!hasDatabase()) return samplePayments;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, amount, status, payment_type, payment_date",
    "      from business_formation_provisioning_payments",
    "      where client_id = ${clientId} order by payment_date desc limit 10`;",
    "    return rows.map(rowToPayment);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function listRequests(clientId: string): Promise<ServiceRequest[]> {",
    "  if (!hasDatabase()) return sampleRequests;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, client_id, title, description, request_type, status, created_at",
    "      from business_formation_provisioning_service_requests",
    "      where client_id = ${clientId} order by created_at desc`;",
    "    return rows.map(rowToRequest);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// The portal fan-out, ported from ClientPortal.loadClientData: the client, its",
    "// subscription, and all provisioned resources in parallel.",
    "export async function getPortalData(ownerId: string): Promise<PortalData> {",
    "  const client = await ensureOnboarded({ ownerId });",
    "  if (!client) {",
    "    return { client: null, subscription: null, domains: [], websites: [], emails: [], payments: [], requests: [] };",
    "  }",
    "  const [subscription, domains, websites, emails, payments, requests] = await Promise.all([",
    "    getSubscription(client.id),",
    "    listDomains(client.id),",
    "    listWebsites(client.id),",
    "    listEmails(client.id),",
    "    listPayments(client.id),",
    "    listRequests(client.id)",
    "  ]);",
    "  return { client, subscription, domains, websites, emails, payments, requests };",
    "}",
    "",
    "// ---- service requests (the client-raised work that provisioning fulfils) ----",
    "",
    "export type CreateRequestInput = {",
    "  clientId: string;",
    "  title: string;",
    "  description?: string;",
    "  requestType?: string;",
    "};",
    "",
    "export async function createRequest(input: CreateRequestInput): Promise<ServiceRequest | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const requestType = SERVICE_REQUEST_TYPES.includes(input.requestType || \"\")",
    "      ? input.requestType",
    '      : "support";',
    "    const rows = await sql`",
    "      insert into business_formation_provisioning_service_requests",
    "        (client_id, title, description, request_type, status)",
    "      values (${input.clientId}, ${input.title}, ${input.description || \"\"}, ${requestType}, 'pending')",
    "      returning id, client_id, title, description, request_type, status, created_at`;",
    "    return rows[0] ? rowToRequest(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- provisioning (admin), ported from provision-wordpress/index.ts ----",
    "",
    "export type ProvisionInput = {",
    "  clientId: string;",
    "  domain: string;",
    "  siteName: string;",
    "};",
    "",
    "export type ProvisionResult = {",
    "  ok: boolean;",
    "  jobId?: string;",
    "  websiteId?: string;",
    "  message: string;",
    "};",
    "",
    "// Run a provisioning job, ported from provision-wordpress Deno.serve: record a",
    "// job (processing), then materialize a website and mark the job completed. The",
    "// external provider fetch is dropped — we provision on the app's own DB — but the",
    "// job lifecycle (processing -> completed/failed, request_data, timestamps) and",
    "// the website insert (site_name, site_url, status='active', divi_enabled) are",
    "// ported faithfully.",
    "export async function provisionWebsite(input: ProvisionInput): Promise<ProvisionResult> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to run provisioning." };',
    '  const domain = (input.domain || "").trim().toLowerCase();',
    '  const siteName = (input.siteName || "").trim();',
    "  if (!domain || !siteName) {",
    '    return { ok: false, message: "A domain and a site name are required to provision." };',
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const requestData = JSON.stringify({ domain, siteName });",
    "    const jobRows = await sql`",
    "      insert into business_formation_provisioning_jobs",
    "        (client_id, job_type, status, request_data, started_at)",
    "      values (${input.clientId}, 'wordpress_setup', 'processing', ${requestData}::jsonb, now())",
    "      returning id`;",
    "    const jobId = jobRows[0] ? String(jobRows[0].id) : null;",
    '    if (!jobId) return { ok: false, message: "Could not start the provisioning job." };',
    "    try {",
    "      const siteRows = await sql`",
    "        insert into business_formation_provisioning_websites",
    "          (client_id, site_name, site_url, status, divi_enabled, deployment_date)",
    "        values (${input.clientId}, ${siteName}, ${`https://${domain}`}, 'active', true, now())",
    "        returning id`;",
    "      const websiteId = siteRows[0] ? String(siteRows[0].id) : undefined;",
    "      const responseData = JSON.stringify({ domain, siteName });",
    "      await sql`",
    "        update business_formation_provisioning_jobs",
    "        set status = 'completed', response_data = ${responseData}::jsonb, completed_at = now()",
    "        where id = ${jobId}`;",
    '      return { ok: true, jobId, websiteId, message: "Site provisioned successfully." };',
    "    } catch (err) {",
    "      const message = err instanceof Error ? err.message : String(err);",
    "      await sql`",
    "        update business_formation_provisioning_jobs",
    "        set status = 'failed', error_message = ${message}, completed_at = now()",
    "        where id = ${jobId}`;",
    '      return { ok: false, jobId, message: "Provisioning failed. The job was recorded for review." };',
    "    }",
    "  } catch {",
    '    return { ok: false, message: "Could not run provisioning." };',
    "  }",
    "}",
    "",
    "// The admin work queue: pending service requests across all clients, newest",
    "// first — the loop-closer the provisioning run fulfils.",
    "export async function listAllPendingRequests(limit = 50): Promise<ServiceRequest[]> {",
    "  if (!hasDatabase()) return sampleRequests;",
    "  try {",
    "    const sql = getDatabase();",
    "    const capped = Math.min(200, Math.max(1, limit));",
    "    const rows = await sql`",
    "      select id, client_id, title, description, request_type, status, created_at",
    "      from business_formation_provisioning_service_requests",
    "      where status = 'pending'",
    "      order by created_at desc limit ${capped}`;",
    "    return rows.map(rowToRequest);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export function formationEnabled(): boolean {",
    '  return process.env.FEATURE_FORMATION !== "false";',
    "}"
  ]);
}

// ---- src/app/api/formation/route.ts (portal read + raise request) -----------

function formationApiFile(): GeneratedModuleFile {
  return file("src/app/api/formation/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getPortalData, ensureOnboarded, createRequest, SERVICE_REQUEST_TYPES, formationEnabled } from "@/lib/db/formation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!formationEnabled()) return NextResponse.json({ ok: false, message: "Onboarding is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  if (!user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const portal = await getPortalData(String(user.id));",
    "  return NextResponse.json({ ok: true, portal });",
    "}",
    "",
    "// Raise a service request (a new site, domain, or mailbox), ported from the",
    "// portal's Services tab. Scoped to the signed-in user's own client profile.",
    "export async function POST(request: Request) {",
    '  if (!formationEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  if (!user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Tell us what you need in a short title." }, { status: 400 });',
    "  }",
    "  // Ensure the user is onboarded (client profile exists) before attaching work.",
    "  const client = await ensureOnboarded({",
    "    ownerId: String(user.id),",
    '    fullName: user.name || "",',
    '    email: user.email ? String(user.email) : ""',
    "  });",
    '  if (!client) return NextResponse.json({ ok: false, message: "Connect a database to save requests." }, { status: 503 });',
    '  const requestType = typeof body.requestType === "string" && SERVICE_REQUEST_TYPES.includes(body.requestType) ? body.requestType : "support";',
    "  const created = await createRequest({",
    "    clientId: client.id,",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : "",',
    "    requestType",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save requests." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, request: created, message: "Request received. We will get it provisioned." });',
    "}"
  ]);
}

// ---- src/app/api/formation/provision/route.ts (admin provisioning) ----------

function provisionApiFile(): GeneratedModuleFile {
  return file("src/app/api/formation/provision/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { provisionWebsite, listAllPendingRequests, formationEnabled } from "@/lib/db/formation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// The admin work queue of pending service requests.",
    "export async function GET() {",
    '  if (!formationEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const requests = await listAllPendingRequests();",
    "  return NextResponse.json({ ok: true, requests });",
    "}",
    "",
    "// Run a provisioning job, ported from provision-wordpress. Admin-only.",
    "export async function POST(request: Request) {",
    '  if (!formationEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const clientId = typeof body.clientId === "string" ? body.clientId.trim() : "";',
    '  const domain = typeof body.domain === "string" ? body.domain.trim() : "";',
    '  const siteName = typeof body.siteName === "string" ? body.siteName.trim() : "";',
    "  if (!clientId || !domain || !siteName) {",
    '    return NextResponse.json({ ok: false, message: "A client, a domain, and a site name are required." }, { status: 400 });',
    "  }",
    "  const result = await provisionWebsite({ clientId, domain, siteName });",
    "  return NextResponse.json(result, { status: result.ok ? 200 : 400 });",
    "}"
  ]);
}

// ---- src/app/portal/page.tsx (the client portal, ported from ClientPortal) --

function portalPageFile(): GeneratedModuleFile {
  return file("src/app/portal/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getPortalData, formationEnabled } from "@/lib/db/formation";',
    'import { RequestServiceForm } from "./request-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function PortalPage() {",
    "  if (!formationEnabled()) {",
    '    return (<main className="shell"><h1>Portal</h1><p>Onboarding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/portal");',
    "  const user = await getCurrentUser();",
    '  if (!user?.id) {',
    '    return (<main className="shell"><h1>Portal</h1><p className="note">Please sign in to view your portal.</p></main>);',
    "  }",
    "  const { client, subscription, domains, websites, emails, payments, requests } = await getPortalData(String(user.id));",
    "  if (!client) {",
    "    return (",
    '      <main className="shell">',
    '        <p className="eyebrow">Setup</p>',
    "        <h1>Account setup required</h1>",
    '        <p className="note">Your account is being set up. Connect a database to finish provisioning.</p>',
    "      </main>",
    "    );",
    "  }",
    "  const nextBilling = subscription ? subscription.nextBillingDate : null;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Your portal</p>',
    "      <h1>Welcome, {client.fullName || client.email}</h1>",
    '      <p className="note">{client.businessName || client.email}</p>',
    "",
    "      {subscription ? (",
    '        <section className="panel">',
    "          <h2>Your subscription</h2>",
    "          <p><strong>${subscription.monthlyFee.toFixed(2)}/month</strong></p>",
    '          <p className="note">Status: {subscription.status}</p>',
    '          {nextBilling ? <p className="note">Next billing: {nextBilling}</p> : null}',
    "        </section>",
    "      ) : null}",
    "",
    "      {/* Provisioning checklist, ported from the portal's counts row. */}",
    '      <section className="panel-list">',
    '        <div className="wide-card"><span>Websites</span><strong>{websites.length}</strong><p className="note">Provisioned sites</p></div>',
    '        <div className="wide-card"><span>Domains</span><strong>{domains.length}</strong><p className="note">Registered domains</p></div>',
    '        <div className="wide-card"><span>Email accounts</span><strong>{emails.length}</strong><p className="note">Mailboxes</p></div>',
    "      </section>",
    "",
    "      <h2>Your websites</h2>",
    "      {websites.length === 0 ? (",
    '        <p className="note">No websites yet. Request one below and we will provision it.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {websites.map((w) => (",
    '            <article className="wide-card" key={w.id}>',
    "              <span>{w.status}</span>",
    "              <strong>{w.siteName}</strong>",
    "              {w.siteUrl ? (",
    '                <p><a className="link" href={w.siteUrl} target="_blank" rel="noopener noreferrer">Visit website</a></p>',
    "              ) : null}",
    '              <p className="note">',
    '                {w.diviEnabled ? "Premium theme · " : ""}',
    '                {w.aiDesignerUsed ? "AI designer · " : ""}',
    '                {w.sslEnabled ? "SSL enabled" : ""}',
    "              </p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Your domains</h2>",
    "      {domains.length === 0 ? (",
    '        <p className="note">No domains yet. Request one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {domains.map((d) => (",
    '            <article className="wide-card" key={d.id}>',
    "              <span>{d.status}</span>",
    "              <strong>{d.domainName}</strong>",
    '              <p className="note">Expires {d.expirationDate || "—"} · ${d.cost.toFixed(2)}/yr</p>',
    '              <p className="note">',
    '                {d.autoRenew ? "Auto-renewal on · " : ""}',
    '                {d.privacyProtection ? "Privacy protection" : ""}',
    "              </p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Your email accounts</h2>",
    "      {emails.length === 0 ? (",
    '        <p className="note">No mailboxes yet. Request one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {emails.map((e) => (",
    '            <article className="wide-card" key={e.id}>',
    "              <span>{e.status}</span>",
    "              <strong>{e.emailAddress}</strong>",
    '              {e.mailServer ? <p className="note">Mail server: {e.mailServer} · IMAP 993 (SSL) · SMTP 587 (TLS)</p> : null}',
    '              <p className="note">{e.storageUsedMb} MB used</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Recent service requests</h2>",
    "      {requests.length === 0 ? (",
    '        <p className="note">No service requests yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {requests.slice(0, 5).map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    '              <span>{r.status.replace("_", " ")}</span>',
    "              <strong>{r.title}</strong>",
    '              {r.description ? <p className="note">{r.description}</p> : null}',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Recent payments</h2>",
    "      {payments.length === 0 ? (",
    '        <p className="note">No payment history yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {payments.slice(0, 5).map((p) => (",
    '            <article className="wide-card" key={p.id}>',
    "              <span>{p.status}</span>",
    "              <strong>${p.amount.toFixed(2)}</strong>",
    '              <p className="note">{p.paymentType} · {p.paymentDate}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Request a service</h2>",
    "      <p>Need a new website, domain, or mailbox? Raise a request and we will provision it for you.</p>",
    "      <RequestServiceForm />",
    "",
    '      <p><Link className="button" href="/portal/provision">Admin: provisioning queue</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/portal/request-form.tsx (client) -------------------------------

function requestFormFile(): GeneratedModuleFile {
  return file("src/app/portal/request-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function RequestServiceForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/formation", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          description: form.get("description"),',
    '          requestType: form.get("requestType")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Request received.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Received</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="What do you need? (e.g. Register mystore.com)" aria-label="Request title" required />',
    '      <textarea className="input" name="description" rows={3} placeholder="Any details we should know" aria-label="Request details" />',
    '      <select className="input" name="requestType" aria-label="Request type" defaultValue="website">',
    '        <option value="website">New website</option>',
    '        <option value="domain">Register a domain</option>',
    '        <option value="email">New mailbox</option>',
    '        <option value="support">Support / other</option>',
    "      </select>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Sending…" : "Submit request"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/portal/provision/page.tsx (admin provisioning queue) -----------

function provisionPageFile(): GeneratedModuleFile {
  return file("src/app/portal/provision/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listAllPendingRequests, formationEnabled } from "@/lib/db/formation";',
    'import { ProvisionForm } from "./provision-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ProvisionPage() {",
    "  if (!formationEnabled()) {",
    '    return (<main className="shell"><h1>Provisioning</h1><p>Onboarding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/portal/provision");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Provisioning</h1><p className="note">This provisioning console is for admins only.</p></main>);',
    "  }",
    "  const requests = await listAllPendingRequests();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Provisioning console</h1>",
    "      <p>Fulfil client requests by provisioning a site. Each run records a job and, on success, publishes the website to that client's portal.</p>",
    "",
    "      <h2>Run a provisioning job</h2>",
    "      <ProvisionForm />",
    "",
    "      <h2>Pending requests</h2>",
    "      {requests.length === 0 ? (",
    '        <p className="note">Nothing waiting. The queue is clear.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {requests.map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    "              <span>{r.requestType}</span>",
    "              <strong>{r.title}</strong>",
    "              {r.description ? <p>{r.description}</p> : null}",
    '              <p className="note">Client {r.clientId}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/portal">Back to portal</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/portal/provision/provision-form.tsx (client) -------------------

function provisionFormFile(): GeneratedModuleFile {
  return file("src/app/portal/provision/provision-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ProvisionForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("working");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/formation/provision", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          clientId: form.get("clientId"),',
    '          domain: form.get("domain"),',
    '          siteName: form.get("siteName")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Provisioning failed.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Site provisioned.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="clientId" placeholder="Client ID" aria-label="Client ID" required />',
    '      <input className="input" name="domain" placeholder="Domain (e.g. mystore.com)" aria-label="Domain" required />',
    '      <input className="input" name="siteName" placeholder="Site name" aria-label="Site name" required />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "working"}>',
    '        {status === "working" ? "Provisioning…" : "Provision site"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

export const businessFormationModule: AppModule = {
  slug: "business-formation-provisioning",
  name: "Business Formation & Provisioning",
  tier: "optional",
  featureFlagEnv: "FEATURE_FORMATION",
  files: () => [
    formationLibFile(),
    formationApiFile(),
    provisionApiFile(),
    portalPageFile(),
    requestFormFile(),
    provisionPageFile(),
    provisionFormFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists business_formation_provisioning_clients (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid not null references users(id) on delete cascade,",
      "  full_name text not null default '',",
      "  business_name text,",
      "  email text not null default '',",
      "  phone text,",
      "  status text not null default 'active',",
      "  created_at timestamptz not null default now()",
      ");",
      "create unique index if not exists business_formation_provisioning_clients_owner_idx on business_formation_provisioning_clients (owner_id);",
      "",
      "create table if not exists business_formation_provisioning_subscriptions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  plan_type text not null default 'basic',",
      "  monthly_fee numeric(10,2) not null default 5.00,",
      "  status text not null default 'active',",
      "  current_period_start date,",
      "  current_period_end date,",
      "  next_billing_date date,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_subscriptions_client_idx on business_formation_provisioning_subscriptions (client_id);",
      "",
      "create table if not exists business_formation_provisioning_domains (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  domain_name text not null,",
      "  status text not null default 'pending',",
      "  registration_date date,",
      "  expiration_date date,",
      "  cost numeric(10,2) not null default 0,",
      "  auto_renew boolean not null default false,",
      "  privacy_protection boolean not null default false,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_domains_client_idx on business_formation_provisioning_domains (client_id);",
      "",
      "create table if not exists business_formation_provisioning_websites (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  domain_id uuid references business_formation_provisioning_domains(id) on delete set null,",
      "  site_name text not null default '',",
      "  site_url text not null default '',",
      "  status text not null default 'active',",
      "  divi_enabled boolean not null default false,",
      "  ai_designer_used boolean not null default false,",
      "  ssl_enabled boolean not null default false,",
      "  deployment_date timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_websites_client_idx on business_formation_provisioning_websites (client_id);",
      "",
      "create table if not exists business_formation_provisioning_email_accounts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  domain_id uuid references business_formation_provisioning_domains(id) on delete set null,",
      "  email_address text not null,",
      "  status text not null default 'active',",
      "  mail_server text not null default '',",
      "  webmail_url text not null default '',",
      "  storage_used_mb integer not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_email_accounts_client_idx on business_formation_provisioning_email_accounts (client_id);",
      "",
      "create table if not exists business_formation_provisioning_payments (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  amount numeric(10,2) not null default 0,",
      "  status text not null default 'pending',",
      "  payment_type text not null default 'subscription',",
      "  payment_date date not null default current_date,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_payments_client_idx on business_formation_provisioning_payments (client_id);",
      "",
      "create table if not exists business_formation_provisioning_service_requests (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  request_type text not null default 'support',",
      "  status text not null default 'pending',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_service_requests_client_idx on business_formation_provisioning_service_requests (client_id);",
      "create index if not exists business_formation_provisioning_service_requests_status_idx on business_formation_provisioning_service_requests (status);",
      "",
      "create table if not exists business_formation_provisioning_jobs (",
      "  id uuid primary key default gen_random_uuid(),",
      "  client_id uuid not null references business_formation_provisioning_clients(id) on delete cascade,",
      "  job_type text not null default 'wordpress_setup',",
      "  status text not null default 'processing',",
      "  request_data jsonb not null default '{}'::jsonb,",
      "  response_data jsonb not null default '{}'::jsonb,",
      "  error_message text not null default '',",
      "  started_at timestamptz,",
      "  completed_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists business_formation_provisioning_jobs_client_idx on business_formation_provisioning_jobs (client_id);",
      "create index if not exists business_formation_provisioning_jobs_status_idx on business_formation_provisioning_jobs (status);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Sample onboarding + provisioning data is bound to a user id at runtime, so",
      "-- no static seed rows are inserted here; the portal renders sample data when",
      "-- no database is connected instead."
    ].join("\n"),
  envLines: () => [
    "",
    "# Business Formation & Provisioning — set to false to switch the onboarding,",
    "# client portal, and provisioning console off.",
    "FEATURE_FORMATION=true"
  ],
  homeLinks: () => ['        <a className="button" href="/portal">Your portal</a>'],
  navLinks: () => [{ href: "/portal", label: "Portal" }]
};