// care-counseling — care requests, helper matching with a safety check-in/
// check-out loop, safety reports, and an encouragement loop so no one who was
// helped (or who helped) is forgotten. Ported from ChurchConnect's real code:
//   - backend/routes/care.py — care_profiles (profile_type needs_help/can_help/
//     both, needs[], abilities[], has_background_check, church_vouched→verified,
//     completed_visits), care_requests (title/description/category/urgency/status
//     open→matched→in_progress→completed), match_helper_to_request (6-char
//     safety_code, status pending_confirmation→confirmed→checked_in→completed),
//     care_checkin (verifies safety_code), care_checkout (marks completed, bumps
//     completed_visits), submit_safety_report (report_type concern/incident/
//     emergency, action_requested review/suspend/ban).
//   - backend/routes/encouragement_loop.py — PROMPT_TEMPLATES (1_week/1_month/
//     3_months/6_months/1_year intervals + copy), send_encouragement_message
//     (helped→helper, life_impact_rating, is_anonymous), received/mark-read.
//   - backend/routes/counselor.py — per-person pastoral notes (note_type general/
//     session/follow_up/concern/prayer, is_confidential) informs the private
//     admin note trail on a care request.
// Generalized off the church framing into plain, warm copy so it drops into any
// app. Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_CARE); customers post/browse requests + send
// encouragement, admins match/verify/review reports.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/care.ts (model + queries, ported from care.py + the loop) ----

function careLibFile(): GeneratedModuleFile {
  return file("src/lib/db/care.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// Urgency + status vocabularies, ported verbatim from care.py.",
    'export type CareUrgency = "urgent" | "high" | "normal" | "low";',
    'export const CARE_URGENCIES: CareUrgency[] = ["urgent", "high", "normal", "low"];',
    "",
    "// Request lifecycle from care.py: open -> matched -> in_progress -> completed.",
    'export type CareStatus = "open" | "matched" | "in_progress" | "completed" | "cancelled";',
    "",
    "// The kinds of help, ported from care.py needs/abilities lists.",
    "export const CARE_CATEGORIES: string[] = [",
    '  "groceries", "meals", "transportation", "companionship", "yard_work",',
    '  "house_cleaning", "medical_transport", "prayer", "errands", "tech_help", "general"',
    "];",
    "",
    "export type CareRequest = {",
    "  id: string;",
    "  requesterId: string | null;",
    "  requesterName: string;",
    "  title: string;",
    "  description: string;",
    "  category: string;",
    "  urgency: CareUrgency;",
    "  city: string;",
    "  dateNeeded: string;",
    "  status: CareStatus;",
    "  matchedHelperId: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "// A match between a helper and a request, ported from care.py match_helper_to_request.",
    "// safety_code is the 6-char code the helper presents at check-in.",
    'export type CareMatchStatus = "pending_confirmation" | "checked_in" | "completed" | "cancelled";',
    "",
    "export type CareMatch = {",
    "  id: string;",
    "  requestId: string;",
    "  helperId: string;",
    "  helperName: string;",
    "  requesterId: string | null;",
    "  status: CareMatchStatus;",
    "  safetyCode: string;",
    "  checkedInAt: string | null;",
    "  checkedOutAt: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "export type CareFilters = { category?: string; urgency?: string; status?: string; city?: string; limit?: number };",
    "",
    "// A 6-char verification code, ported from care.py str(uuid4())[:6].upper().",
    "export function generateSafetyCode(): string {",
    '  return Math.random().toString(36).slice(2, 8).toUpperCase().padEnd(6, "0");',
    "}",
    "",
    "const fallbackRequests: CareRequest[] = [",
    '  { id: "sample-1", requesterId: null, requesterName: "Marta", title: "Ride to a Thursday appointment", description: "I need a lift to a follow-up appointment across town and back.", category: "medical_transport", urgency: "high", city: "Riverside", dateNeeded: "", status: "open", matchedHelperId: null, createdAt: new Date().toISOString() },',
    '  { id: "sample-2", requesterId: null, requesterName: "Eli", title: "A few groceries this week", description: "Recovering from surgery and can\'t carry much. A small grocery run would help.", category: "groceries", urgency: "normal", city: "Riverside", dateNeeded: "", status: "open", matchedHelperId: null, createdAt: new Date().toISOString() }',
    "];",
    "",
    "function rowToRequest(row: Record<string, unknown>): CareRequest {",
    '  const urgency = String(row.urgency || "normal");',
    "  return {",
    "    id: String(row.id),",
    "    requesterId: row.requester_id != null ? String(row.requester_id) : null,",
    '    requesterName: String(row.requester_name || "Someone"),',
    '    title: String(row.title || "A request for help"),',
    '    description: String(row.description || ""),',
    '    category: String(row.category || "general"),',
    '    urgency: (CARE_URGENCIES as string[]).includes(urgency) ? (urgency as CareUrgency) : "normal",',
    '    city: String(row.city || ""),',
    '    dateNeeded: String(row.date_needed || ""),',
    '    status: String(row.status || "open") as CareStatus,',
    "    matchedHelperId: row.matched_helper_id != null ? String(row.matched_helper_id) : null,",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "// List care requests, ported from care.py get_care_requests: filter by category/",
    "// urgency/status/city, newest first. Defaults to open requests.",
    "export async function listRequests(filters: CareFilters = {}): Promise<CareRequest[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const status = (filters.status || "open").trim().toLowerCase();',
    '  const category = (filters.category || "").trim().toLowerCase();',
    '  const city = (filters.city || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackRequests",
    "      .filter((r) => !status || r.status === status)",
    "      .filter((r) => !category || r.category === category)",
    "      .filter((r) => !city || r.city.toLowerCase().includes(city))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const statusFilter = status || null;",
    "    const categoryFilter = category || null;",
    "    const cityLike = city ? `%${city}%` : null;",
    "    const rows = await sql`",
    "      select id, requester_id, requester_name, title, description, category, urgency, city, date_needed, status, matched_helper_id, created_at",
    "      from care_requests",
    "      where (${statusFilter}::text is null or status = ${statusFilter})",
    "        and (${categoryFilter}::text is null or category = ${categoryFilter})",
    "        and (${cityLike}::text is null or lower(city) like ${cityLike})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToRequest);",
    "  } catch {",
    "    return fallbackRequests.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getRequest(id: string): Promise<CareRequest | null> {",
    "  if (!hasDatabase()) return fallbackRequests.find((r) => r.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, requester_id, requester_name, title, description, category, urgency, city, date_needed, status, matched_helper_id, created_at from care_requests where id = ${id} limit 1`;",
    "    return rows[0] ? rowToRequest(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateRequestInput = {",
    "  requesterId: string;",
    "  requesterName: string;",
    "  title: string;",
    "  description?: string;",
    "  category?: string;",
    "  urgency?: CareUrgency;",
    "  city?: string;",
    "  dateNeeded?: string;",
    "};",
    "",
    "// Create a help request, ported from care.py create_care_request (status opens as 'open').",
    "export async function createRequest(input: CreateRequestInput): Promise<CareRequest | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    '    const urgency = (CARE_URGENCIES as string[]).includes(input.urgency || "") ? input.urgency : "normal";',
    '    const category = (CARE_CATEGORIES.includes(input.category || "") ? input.category : "general") as string;',
    "    const rows = await sql`",
    "      insert into care_requests (requester_id, requester_name, title, description, category, urgency, city, date_needed, status)",
    '      values (${input.requesterId}, ${input.requesterName}, ${input.title}, ${input.description || ""}, ${category}, ${urgency}, ${input.city || ""}, ${input.dateNeeded || ""}, \'open\')',
    "      returning id, requester_id, requester_name, title, description, category, urgency, city, date_needed, status, matched_helper_id, created_at",
    "    `;",
    "    return rows[0] ? rowToRequest(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Match a helper to a request with a safety code, ported from care.py",
    "// match_helper_to_request: create the match (pending_confirmation) and flip the",
    "// request to 'matched'. Admin action (staff pairs people).",
    "export async function matchHelper(requestId: string, helperId: string, helperName: string): Promise<CareMatch | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const reqRows = await sql`select id, requester_id, status from care_requests where id = ${requestId} limit 1`;",
    "    if (!reqRows[0]) return null;",
    "    const code = generateSafetyCode();",
    "    const requesterId = reqRows[0].requester_id != null ? String(reqRows[0].requester_id) : null;",
    "    const rows = await sql`",
    "      insert into care_matches (request_id, helper_id, helper_name, requester_id, status, safety_code)",
    "      values (${requestId}, ${helperId}, ${helperName}, ${requesterId}, 'pending_confirmation', ${code})",
    "      returning id, request_id, helper_id, helper_name, requester_id, status, safety_code, checked_in_at, checked_out_at, created_at",
    "    `;",
    "    const match = rows[0];",
    "    if (!match) return null;",
    "    await sql`update care_requests set status = 'matched', matched_helper_id = ${match.id} where id = ${requestId}`;",
    "    return rowToMatch(match);",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "function rowToMatch(row: Record<string, unknown>): CareMatch {",
    "  return {",
    "    id: String(row.id),",
    "    requestId: String(row.request_id),",
    "    helperId: String(row.helper_id),",
    '    helperName: String(row.helper_name || "Helper"),',
    "    requesterId: row.requester_id != null ? String(row.requester_id) : null,",
    '    status: String(row.status || "pending_confirmation") as CareMatchStatus,',
    '    safetyCode: String(row.safety_code || ""),',
    "    checkedInAt: row.checked_in_at != null ? String(row.checked_in_at) : null,",
    "    checkedOutAt: row.checked_out_at != null ? String(row.checked_out_at) : null,",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "// Helper checks in on arrival — must present the right safety code, ported from",
    "// care.py care_checkin (403 on a bad code).",
    "export async function checkIn(matchId: string, safetyCode: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to run safety check-ins." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, safety_code, status from care_matches where id = ${matchId} limit 1`;",
    '    if (!rows[0]) return { ok: false, message: "That match no longer exists." };',
    '    if (String(rows[0].safety_code) !== safetyCode.trim().toUpperCase()) return { ok: false, message: "That safety code doesn\'t match. Ask the person you\'re helping for the code." };',
    "    await sql`update care_matches set status = 'checked_in', checked_in_at = now() where id = ${matchId}`;",
    "    await sql`update care_requests set status = 'in_progress' where matched_helper_id = ${matchId}`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not check in right now." };',
    "  }",
    "}",
    "",
    "// Helper checks out on leaving — marks the match + request complete and bumps the",
    "// helper's completed_visits, ported from care.py care_checkout.",
    "export async function checkOut(matchId: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to run safety check-outs." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, request_id, helper_id from care_matches where id = ${matchId} limit 1`;",
    '    if (!rows[0]) return { ok: false, message: "That match no longer exists." };',
    "    await sql`update care_matches set status = 'completed', checked_out_at = now() where id = ${matchId}`;",
    "    await sql`update care_requests set status = 'completed' where id = ${rows[0].request_id}`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not check out right now." };',
    "  }",
    "}",
    "",
    "export type SafetyReportInput = {",
    "  matchId?: string | null;",
    "  reporterId: string;",
    "  reportType?: string;",
    "  description: string;",
    "  actionRequested?: string;",
    "};",
    "",
    "// Submit a safety report, ported from care.py submit_safety_report",
    "// (report_type concern/incident/emergency, action review/suspend/ban).",
    'export const SAFETY_REPORT_TYPES = ["concern", "incident", "emergency"];',
    "export async function submitReport(input: SafetyReportInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    const reportType = SAFETY_REPORT_TYPES.includes(input.reportType || "") ? input.reportType : "concern";',
    "    await sql`",
    "      insert into care_reports (match_id, reporter_id, report_type, description, action_requested, status)",
    '      values (${input.matchId || null}, ${input.reporterId}, ${reportType}, ${input.description}, ${input.actionRequested || "review"}, \'pending\')',
    "    `;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export type SafetyReport = {",
    "  id: string;",
    "  matchId: string | null;",
    "  reporterId: string | null;",
    "  reportType: string;",
    "  description: string;",
    "  actionRequested: string;",
    "  status: string;",
    "  createdAt: string;",
    "};",
    "",
    "// Admin queue of safety reports, ported from care.py get_safety_reports.",
    "export async function listReports(status?: string): Promise<SafetyReport[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const statusFilter = status && status.trim() ? status.trim() : null;",
    "    const rows = await sql`",
    "      select id, match_id, reporter_id, report_type, description, action_requested, status, created_at",
    "      from care_reports",
    "      where (${statusFilter}::text is null or status = ${statusFilter})",
    "      order by created_at desc limit 100",
    "    `;",
    "    return rows.map((row: Record<string, unknown>) => ({",
    "      id: String(row.id),",
    "      matchId: row.match_id != null ? String(row.match_id) : null,",
    "      reporterId: row.reporter_id != null ? String(row.reporter_id) : null,",
    '      reportType: String(row.report_type || "concern"),',
    '      description: String(row.description || ""),',
    '      actionRequested: String(row.action_requested || "review"),',
    '      status: String(row.status || "pending"),',
    '      createdAt: String(row.created_at || "")',
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// ---- Encouragement loop, ported from encouragement_loop.py ------------------",
    "",
    "// PROMPT_TEMPLATES intervals + copy, ported verbatim (generalized off the church",
    "// framing). After being helped, the recipient is nudged to send encouragement",
    "// back to the helper — who may need it right when it arrives.",
    "export type EncouragementInterval = {",
    "  key: string;",
    "  days: number;",
    "  title: string;",
    "  message: string;",
    "};",
    "export const ENCOURAGEMENT_INTERVALS: EncouragementInterval[] = [",
    '  { key: "1_week", days: 7, title: "How are you doing?", message: "A week ago, {helper} reached out with kindness. How has that moment stayed with you?" },',
    '  { key: "1_month", days: 30, title: "One month later", message: "It has been a month since {helper} showed you kindness. Take a moment to reflect on how that act has touched your life." },',
    '  { key: "3_months", days: 90, title: "Three months on", message: "Three months ago, someone showed up for you. How has that moment shaped things since? Your story could encourage {helper} today." },',
    '  { key: "6_months", days: 180, title: "Half a year of change", message: "Six months have passed since {helper} helped you. Looking back, how has your life changed? They would love to know their kindness mattered." },',
    '  { key: "1_year", days: 365, title: "One year on", message: "A year ago, {helper} made a difference in your life. Sharing how far you have come could be exactly what they need to hear today." }',
    "];",
    "",
    "export type Encouragement = {",
    "  id: string;",
    "  senderId: string | null;",
    "  senderName: string;",
    "  recipientId: string;",
    "  message: string;",
    "  lifeImpactRating: number | null;",
    "  isAnonymous: boolean;",
    "  read: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "function rowToEncouragement(row: Record<string, unknown>): Encouragement {",
    "  const anon = row.is_anonymous === true || String(row.is_anonymous) === \"true\";",
    "  return {",
    "    id: String(row.id),",
    "    senderId: anon ? null : (row.sender_id != null ? String(row.sender_id) : null),",
    '    senderName: anon ? "Anonymous" : String(row.sender_name || "Someone you helped"),',
    "    recipientId: String(row.recipient_id),",
    '    message: String(row.message || ""),',
    "    lifeImpactRating: row.life_impact_rating != null ? Number(row.life_impact_rating) : null,",
    "    isAnonymous: anon,",
    "    read: row.read === true || String(row.read) === \"true\",",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "export type SendEncouragementInput = {",
    "  senderId: string;",
    "  senderName: string;",
    "  recipientId: string;",
    "  message: string;",
    "  lifeImpactRating?: number | null;",
    "  isAnonymous?: boolean;",
    "};",
    "",
    "// Send encouragement from a helped person back to their helper, ported from",
    "// encouragement_loop.py send_encouragement_message (the heart of the loop).",
    "export async function sendEncouragement(input: SendEncouragementInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rating = typeof input.lifeImpactRating === \"number\" && input.lifeImpactRating >= 1 && input.lifeImpactRating <= 10 ? input.lifeImpactRating : null;",
    "    await sql`",
    "      insert into care_encouragements (sender_id, sender_name, recipient_id, message, life_impact_rating, is_anonymous, read)",
    "      values (${input.senderId}, ${input.senderName}, ${input.recipientId}, ${input.message}, ${rating}, ${input.isAnonymous === true}, false)",
    "    `;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "const fallbackEncouragements: Encouragement[] = [",
    '  { id: "enc-sample-1", senderId: null, senderName: "Someone you helped", recipientId: "me", message: "That ride you gave me last month meant more than you know. I hope today is kind to you.", lifeImpactRating: 9, isAnonymous: false, read: false, createdAt: new Date().toISOString() }',
    "];",
    "",
    "// Encouragement received by a user, ported from encouragement_loop.py",
    "// get_received_encouragement (anonymous senders are hidden).",
    "export async function listReceivedEncouragement(userId: string, unreadOnly = false): Promise<Encouragement[]> {",
    "  if (!hasDatabase()) return fallbackEncouragements.filter((e) => !unreadOnly || !e.read);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = unreadOnly",
    "      ? await sql`select id, sender_id, sender_name, recipient_id, message, life_impact_rating, is_anonymous, read, created_at from care_encouragements where recipient_id = ${userId} and read = false order by created_at desc limit 100`",
    "      : await sql`select id, sender_id, sender_name, recipient_id, message, life_impact_rating, is_anonymous, read, created_at from care_encouragements where recipient_id = ${userId} order by created_at desc limit 100`;",
    "    return rows.map(rowToEncouragement);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Mark an encouragement note as read, ported from encouragement_loop.py mark-read.",
    "export async function markEncouragementRead(id: string, userId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update care_encouragements set read = true, read_at = now() where id = ${id} and recipient_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function careEnabled(): boolean {",
    '  return process.env.FEATURE_CARE !== "false";',
    "}"
  ]);
}

// ---- src/app/api/care/route.ts (list + create requests) ---------------------

function careApiFile(): GeneratedModuleFile {
  return file("src/app/api/care/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listRequests, createRequest, careEnabled, CARE_URGENCIES, type CareUrgency } from "@/lib/db/care";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false, message: "Care is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const requests = await listRequests({",
    '    category: url.searchParams.get("category") || undefined,',
    '    urgency: url.searchParams.get("urgency") || undefined,',
    '    status: url.searchParams.get("status") || undefined,',
    '    city: url.searchParams.get("city") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, requests });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    "  // Anyone signed in may ask for help; ownership is tied to their identity.",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to ask for help." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  if (title.length < 3) return NextResponse.json({ ok: false, message: "Please give your request a short title." }, { status: 400 });',
    '  const urgency = (CARE_URGENCIES as string[]).includes(String(body.urgency)) ? (String(body.urgency) as CareUrgency) : "normal";',
    '  const userId = String(user?.email || "");',
    "  const created = await createRequest({",
    "    requesterId: userId,",
    '    requesterName: String(user?.name || user?.email || "Someone"),',
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    '    category: typeof body.category === "string" ? body.category : undefined,',
    "    urgency,",
    '    city: typeof body.city === "string" ? body.city : undefined,',
    '    dateNeeded: typeof body.dateNeeded === "string" ? body.dateNeeded : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to post requests." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, request: created });",
    "}"
  ]);
}

// ---- src/app/api/care/[id]/route.ts (detail + admin match) ------------------

function careDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/care/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getRequest, matchHelper, careEnabled } from "@/lib/db/care";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const careRequest = await getRequest(id);",
    '  if (!careRequest) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, request: careRequest });",
    "}",
    "",
    "// Matching a helper to a request is an admin/staff action (safety gate).",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const helperId = typeof body.helperId === "string" ? body.helperId.trim() : "";',
    '  const helperName = typeof body.helperName === "string" ? body.helperName.trim() : "";',
    '  if (!helperId) return NextResponse.json({ ok: false, message: "A helper is required." }, { status: 400 });',
    '  const match = await matchHelper(id, helperId, helperName || helperId);',
    '  if (!match) return NextResponse.json({ ok: false, message: "Could not create the match. Connect a database and check the request." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, match });",
    "}"
  ]);
}

// ---- src/app/api/care/encouragement/route.ts --------------------------------

function encouragementApiFile(): GeneratedModuleFile {
  return file("src/app/api/care/encouragement/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listReceivedEncouragement, sendEncouragement, careEnabled } from "@/lib/db/care";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const received = await listReceivedEncouragement(String(user?.email || ""));',
    "  return NextResponse.json({ ok: true, received });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!careEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const recipientId = typeof body.recipientId === "string" ? body.recipientId.trim() : "";',
    '  const message = typeof body.message === "string" ? body.message.trim() : "";',
    '  if (!recipientId || message.length < 2) return NextResponse.json({ ok: false, message: "Say a few words to the person who helped you." }, { status: 400 });',
    "  const sent = await sendEncouragement({",
    '    senderId: String(user?.email || ""),',
    '    senderName: String(user?.name || user?.email || "Someone you helped"),',
    "    recipientId,",
    "    message,",
    '    lifeImpactRating: typeof body.lifeImpactRating === "number" ? body.lifeImpactRating : null,',
    "    isAnonymous: body.isAnonymous === true",
    "  });",
    '  if (!sent) return NextResponse.json({ ok: false, message: "Connect a database to send encouragement." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/care/page.tsx (list + post a request) --------------------------

function carePageFile(): GeneratedModuleFile {
  return file("src/app/care/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listRequests, careEnabled, CARE_URGENCIES } from "@/lib/db/care";',
    'import { NewRequestForm } from "./new-request-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CarePage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ category?: string }>;",
    "}) {",
    "  if (!careEnabled()) {",
    '    return (<main className="shell"><h1>Care</h1><p>Care is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/care");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const category = (params?.category || "").trim();',
    "  const requests = await listRequests({ category: category || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Care</p>',
    "      <h1>No one carries it alone</h1>",
    "      <p>Ask for a hand, or offer one. Every request is watched over — helpers are matched with a safety check-in so no one in a hard season is missed.</p>",
    "      <NewRequestForm urgencies={[...CARE_URGENCIES]} />",
    "      <h2>Open requests</h2>",
    "      {requests.length === 0 ? (",
    '        <p className="note">No open requests right now. When someone asks for help, it shows up here.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {requests.map((r) => (",
    '            <Link className="wide-card" key={r.id} href={`/care/${r.id}`}>',
    "              <span>{r.urgency} &middot; {r.category}</span>",
    "              <strong>{r.title}</strong>",
    "              {r.description ? <p>{r.description}</p> : null}",
    '              <p className="note">{[r.requesterName, r.city].filter(Boolean).join(" · ")}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p className="stack">',
    '        <Link className="button" href="/care/encouragement">Encouragement you have received</Link>',
    "      </p>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/care/new-request-form.tsx (client) -----------------------------

function newRequestFormFile(): GeneratedModuleFile {
  return file("src/app/care/new-request-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function NewRequestForm({ urgencies }: { urgencies: string[] }) {",
    "  const router = useRouter();",
    '  const [title, setTitle] = useState("");',
    '  const [description, setDescription] = useState("");',
    '  const [category, setCategory] = useState("general");',
    '  const [urgency, setUrgency] = useState("normal");',
    '  const [city, setCity] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/care", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ title, description, category, urgency, city })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setTitle("");',
    '      setDescription("");',
    '      setCity("");',
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack panel" onSubmit={submit}>',
    "      <h2>Ask for help</h2>",
    '      <label className="field">',
    "        <span>What do you need?</span>",
    '        <input className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="A short title" required />',
    "      </label>",
    '      <label className="field">',
    "        <span>Tell us a little more</span>",
    '        <textarea className="input" value={description} onChange={(e) => setDescription(e.target.value)} rows={3} placeholder="Optional details" />',
    "      </label>",
    '      <div className="grid">',
    '        <label className="field">',
    "          <span>Kind of help</span>",
    '          <select className="input" value={category} onChange={(e) => setCategory(e.target.value)}>',
    '            {["general", "groceries", "meals", "transportation", "companionship", "yard_work", "house_cleaning", "medical_transport", "prayer", "errands", "tech_help"].map((c) => (',
    "              <option key={c} value={c}>{c.replace(/_/g, \" \")}</option>",
    "            ))}",
    "          </select>",
    "        </label>",
    '        <label className="field">',
    "          <span>Urgency</span>",
    '          <select className="input" value={urgency} onChange={(e) => setUrgency(e.target.value)}>',
    "            {urgencies.map((u) => (<option key={u} value={u}>{u}</option>))}",
    "          </select>",
    "        </label>",
    '        <label className="field">',
    "          <span>City</span>",
    '          <input className="input" value={city} onChange={(e) => setCity(e.target.value)} placeholder="Optional" />',
    "        </label>",
    "      </div>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Posting…" : "Post request"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/care/[id]/page.tsx (request detail + safety flow) --------------

function careDetailPageFile(): GeneratedModuleFile {
  return file("src/app/care/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getRequest, careEnabled } from "@/lib/db/care";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CareRequestPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!careEnabled()) {",
    '    return (<main className="shell"><h1>Care</h1><p>Care is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/care");',
    "  const { id } = await params;",
    "  const careRequest = await getRequest(id);",
    "  if (!careRequest) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Care request</p>',
    "      <h1>{careRequest.title}</h1>",
    '      <section className="grid">',
    '        <article className="card"><span>Urgency</span><strong>{careRequest.urgency}</strong></article>',
    '        <article className="card"><span>Kind of help</span><strong>{careRequest.category.replace(/_/g, " ")}</strong></article>',
    '        <article className="card"><span>Status</span><strong>{careRequest.status.replace(/_/g, " ")}</strong></article>',
    "        {careRequest.city ? (<article className=\"card\"><span>City</span><strong>{careRequest.city}</strong></article>) : null}",
    "      </section>",
    "      {careRequest.description ? <p>{careRequest.description}</p> : null}",
    '      <p className="note">Asked by {careRequest.requesterName}. When a helper is matched, they receive a safety code to check in on arrival and check out when they leave — so someone always knows a visit happened.</p>',
    '      <p><Link className="button" href="/care">Back to care</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/care/encouragement/page.tsx ------------------------------------

function encouragementPageFile(): GeneratedModuleFile {
  return file("src/app/care/encouragement/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listReceivedEncouragement, careEnabled } from "@/lib/db/care";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function EncouragementPage() {",
    "  if (!careEnabled()) {",
    '    return (<main className="shell"><h1>Care</h1><p>Care is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/care/encouragement");',
    "  const user = await getCurrentUser();",
    '  const received = user?.email ? await listReceivedEncouragement(String(user.email)) : [];',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Encouragement</p>',
    "      <h1>Notes from people you helped</h1>",
    "      <p>We don’t always know what someone is carrying. These are messages from people whose lives you touched — arriving, we hope, right when you need them.</p>",
    "      {received.length === 0 ? (",
    '        <p className="note">No encouragement yet. As people you have helped reflect back, their notes will land here.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {received.map((e) => (",
    '            <article className="wide-card" key={e.id}>',
    "              {e.lifeImpactRating ? <span>Impact {e.lifeImpactRating} / 10</span> : <span>A note for you</span>}",
    "              <strong>{e.senderName}</strong>",
    "              <p>{e.message}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/care">Back to care</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const careCounselingModule: AppModule = {
  slug: "care-counseling",
  name: "Care & Counseling",
  tier: "optional",
  featureFlagEnv: "FEATURE_CARE",
  files: () => [
    careLibFile(),
    careApiFile(),
    careDetailApiFile(),
    encouragementApiFile(),
    carePageFile(),
    newRequestFormFile(),
    careDetailPageFile(),
    encouragementPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists care_requests (",
      "  id uuid primary key default gen_random_uuid(),",
      "  requester_id uuid references users(id) on delete set null,",
      "  requester_name text not null default '',",
      "  title text not null,",
      "  description text not null default '',",
      "  category text not null default 'general',",
      "  urgency text not null default 'normal',",
      "  city text not null default '',",
      "  date_needed text not null default '',",
      "  status text not null default 'open',",
      "  matched_helper_id uuid,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists care_requests_status_idx on care_requests (status, created_at desc);",
      "create index if not exists care_requests_category_idx on care_requests (category);",
      "",
      "create table if not exists care_matches (",
      "  id uuid primary key default gen_random_uuid(),",
      "  request_id uuid not null references care_requests(id) on delete cascade,",
      "  helper_id uuid references users(id) on delete set null,",
      "  helper_name text not null default '',",
      "  requester_id uuid references users(id) on delete set null,",
      "  status text not null default 'pending_confirmation',",
      "  safety_code text not null,",
      "  checked_in_at timestamptz,",
      "  checked_out_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists care_matches_request_idx on care_matches (request_id);",
      "create index if not exists care_matches_helper_idx on care_matches (helper_id);",
      "",
      "create table if not exists care_reports (",
      "  id uuid primary key default gen_random_uuid(),",
      "  match_id uuid references care_matches(id) on delete set null,",
      "  reporter_id uuid references users(id) on delete set null,",
      "  report_type text not null default 'concern',",
      "  description text not null default '',",
      "  action_requested text not null default 'review',",
      "  status text not null default 'pending',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists care_reports_status_idx on care_reports (status, created_at desc);",
      "",
      "create table if not exists care_encouragements (",
      "  id uuid primary key default gen_random_uuid(),",
      "  sender_id uuid references users(id) on delete set null,",
      "  sender_name text not null default '',",
      "  recipient_id uuid not null references users(id) on delete cascade,",
      "  message text not null default '',",
      "  life_impact_rating integer,",
      "  is_anonymous boolean not null default false,",
      "  read boolean not null default false,",
      "  read_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists care_encouragements_recipient_idx on care_encouragements (recipient_id, read);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into care_requests (requester_name, title, description, category, urgency, city, status) values",
      "  ('Marta', 'Ride to a Thursday appointment', 'A lift across town for a follow-up appointment and back.', 'medical_transport', 'high', 'Riverside', 'open'),",
      "  ('Eli', 'A few groceries this week', 'Recovering from surgery and cannot carry much. A small grocery run would help.', 'groceries', 'normal', 'Riverside', 'open')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Care & Counseling — set to false to switch care requests + matching + the encouragement loop off.",
    "FEATURE_CARE=true"
  ],
  homeLinks: () => ['        <a className="button" href="/care">Care</a>'],
  navLinks: () => [{ href: "/care", label: "Care" }]
};
