// case-management — case timelines, a document center, court-ready summaries, and
// an agreement/attendance tracker, ported from childfirst-solutions' real
// co-parenting workspace:
//   - src/components/CaseTimeline.tsx + src/app/(app)/timeline/page.tsx +
//     src/types/events.ts (TimelineEvent) + src/types/case.ts (CaseEvent.eventType)
//     — the documented-event timeline: title, type (exchange/school/schedule/
//     medical/incident/pickup/communication/expense/request/violation), timestamp,
//     description, scoped to a parent case.
//   - src/components/DocumentCenter.tsx + src/types/events.ts (EventAttachment) —
//     upload + organize parenting plans, schedules, reports, supporting docs by
//     name + type (PDF/Image/...).
//   - src/components/CourtReadySummaryCard.tsx — court-ready summary rows: a
//     category (Parenting Time / Communication / Activities) + a detail line
//     ("92% schedule completion rate"), here derived live from the tracked data.
//   - src/components/AgreementTrackerCard.tsx — agreement/attendance tracker: a
//     topic (Summer Vacation Week, Pickup Adjustment) + a status (Accepted /
//     Pending Approval / Declined).
// The childfirst components were static sample arrays; this port keeps their exact
// model + copy and makes them real — persisted per owner on the app's own DB with
// a graceful sample-data fallback, feature-flagged (FEATURE_CASES). Customers own
// and manage their own cases, events, documents, and agreements; admins can review
// across owners.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/case-management.ts (model + queries) ------------------------

function caseLibFile(): GeneratedModuleFile {
  return file("src/lib/db/case-management.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A parent case — the container everything is scoped to, ported from",
    "// childfirst-solutions ParentCase (src/types/case.ts).",
    "export type ParentCase = {",
    "  id: string;",
    "  ownerId: string;",
    "  caseName: string;",
    "  childName: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A documented event on the case timeline, ported from TimelineEvent",
    "// (src/types/events.ts) + CaseTimeline.tsx (title/type/timestamp).",
    "export type TimelineEvent = {",
    "  id: string;",
    "  caseId: string;",
    "  title: string;",
    "  description: string;",
    "  eventType: string;",
    "  occurredAt: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A document in the document center, ported from DocumentCenter.tsx",
    "// (name/type) + EventAttachment (fileName/fileType/uploadedAt).",
    "export type CaseDocument = {",
    "  id: string;",
    "  caseId: string;",
    "  name: string;",
    "  docType: string;",
    "  url: string;",
    "  uploadedAt: string;",
    "};",
    "",
    "// An agreement/attendance item, ported from AgreementTrackerCard.tsx",
    "// (topic/status).",
    "export type CaseAgreement = {",
    "  id: string;",
    "  caseId: string;",
    "  topic: string;",
    "  status: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A court-ready summary row, ported from CourtReadySummaryCard.tsx",
    "// (category/detail).",
    "export type CourtSummaryRow = { category: string; detail: string };",
    "",
    "// The event types the timeline can file an event under, ported from",
    "// CaseEvent.eventType (case.ts) + the timeline page milestone filters",
    "// (Exchange / Medical / School / Request / Violation).",
    "export const TIMELINE_EVENT_TYPES = [",
    '  "exchange",',
    '  "pickup",',
    '  "school",',
    '  "medical",',
    '  "communication",',
    '  "expense",',
    '  "schedule",',
    '  "request",',
    '  "incident",',
    '  "violation"',
    "];",
    "",
    "// The statuses an agreement can hold, ported from AgreementTrackerCard.tsx",
    '// ("Accepted", "Pending Approval") plus the natural "Declined" close.',
    "export const AGREEMENT_STATUSES = [\"Pending Approval\", \"Accepted\", \"Declined\"];",
    "",
    "// ---- graceful sample-data fallback (mirrors the childfirst sample arrays) ---",
    "",
    "const fallbackCases: ParentCase[] = [",
    '  { id: "sample-case", ownerId: "sample", caseName: "Our Family Parenting Plan", childName: "Riley", createdAt: "2026-01-01T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackEvents: TimelineEvent[] = [",
    "  {",
    '    id: "sample-evt-1", caseId: "sample-case",',
    '    title: "Parenting Exchange Completed",',
    '    description: "Arrival and departure records verified with neutral exchange notes.",',
    '    eventType: "exchange",',
    '    occurredAt: "2026-05-20T17:00:00.000Z", createdAt: "2026-05-20T17:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-evt-2", caseId: "sample-case",',
    '    title: "School Event Added",',
    '    description: "Added to the shared calendar and confirmed with both parents.",',
    '    eventType: "school",',
    '    occurredAt: "2026-05-19T15:20:00.000Z", createdAt: "2026-05-19T15:20:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-evt-3", caseId: "sample-case",',
    '    title: "Schedule Adjustment Requested",',
    '    description: "A revised Saturday pickup window was proposed.",',
    '    eventType: "schedule",',
    '    occurredAt: "2026-05-18T08:10:00.000Z", createdAt: "2026-05-18T08:10:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackDocuments: CaseDocument[] = [",
    '  { id: "sample-doc-1", caseId: "sample-case", name: "Parenting Plan.pdf", docType: "PDF", url: "", uploadedAt: "2026-01-02T00:00:00.000Z" },',
    '  { id: "sample-doc-2", caseId: "sample-case", name: "School Calendar.png", docType: "Image", url: "", uploadedAt: "2026-01-03T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackAgreements: CaseAgreement[] = [",
    '  { id: "sample-agr-1", caseId: "sample-case", topic: "Summer Vacation Week", status: "Accepted", createdAt: "2026-01-04T00:00:00.000Z" },',
    '  { id: "sample-agr-2", caseId: "sample-case", topic: "Pickup Adjustment", status: "Pending Approval", createdAt: "2026-01-05T00:00:00.000Z" }',
    "];",
    "",
    "// ---- row mappers -----------------------------------------------------------",
    "",
    "function rowToCase(row: Record<string, unknown>): ParentCase {",
    "  return {",
    "    id: String(row.id),",
    '    ownerId: String(row.owner_id || ""),',
    '    caseName: String(row.case_name || ""),',
    '    childName: String(row.child_name || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToEvent(row: Record<string, unknown>): TimelineEvent {",
    "  return {",
    "    id: String(row.id),",
    "    caseId: String(row.case_id),",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    eventType: String(row.event_type || "exchange"),',
    '    occurredAt: row.occurred_at ? String(row.occurred_at) : "",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToDocument(row: Record<string, unknown>): CaseDocument {",
    "  return {",
    "    id: String(row.id),",
    "    caseId: String(row.case_id),",
    '    name: String(row.name || ""),',
    '    docType: String(row.doc_type || "File"),',
    '    url: String(row.url || ""),',
    '    uploadedAt: row.uploaded_at ? String(row.uploaded_at) : ""',
    "  };",
    "}",
    "",
    "function rowToAgreement(row: Record<string, unknown>): CaseAgreement {",
    "  return {",
    "    id: String(row.id),",
    "    caseId: String(row.case_id),",
    '    topic: String(row.topic || ""),',
    '    status: String(row.status || "Pending Approval"),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- cases -----------------------------------------------------------------",
    "",
    "// List an owner's cases (newest first). Admins may pass null to see all cases.",
    "export async function listCases(ownerId: string | null): Promise<ParentCase[]> {",
    "  if (!hasDatabase()) {",
    "    return ownerId === null ? fallbackCases : fallbackCases.map((c) => ({ ...c, ownerId }));",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId;",
    "    const rows = await sql`",
    "      select id, owner_id, case_name, child_name, created_at",
    "      from case_management_cases",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "      order by created_at desc",
    "    `;",
    "    return rows.map(rowToCase);",
    "  } catch {",
    "    return ownerId === null ? fallbackCases : fallbackCases.map((c) => ({ ...c, ownerId }));",
    "  }",
    "}",
    "",
    "// Fetch one case, scoped to its owner unless the caller is an admin (ownerId null).",
    "export async function getCase(id: string, ownerId: string | null): Promise<ParentCase | null> {",
    "  if (!hasDatabase()) {",
    "    const found = fallbackCases.find((c) => c.id === id) || null;",
    "    return found ? (ownerId === null ? found : { ...found, ownerId }) : null;",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId;",
    "    const rows = await sql`",
    "      select id, owner_id, case_name, child_name, created_at",
    "      from case_management_cases",
    "      where id = ${id} and (${owner}::uuid is null or owner_id = ${owner})",
    "      limit 1`;",
    "    return rows[0] ? rowToCase(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateCaseInput = { ownerId: string; caseName: string; childName?: string };",
    "",
    "export async function createCase(input: CreateCaseInput): Promise<ParentCase | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into case_management_cases (owner_id, case_name, child_name)",
    "      values (${input.ownerId}, ${input.caseName}, ${input.childName || \"\"})",
    "      returning id, owner_id, case_name, child_name, created_at`;",
    "    return rows[0] ? rowToCase(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Confirm the owner owns this case (or the caller is an admin) before nesting",
    "// timeline/document/agreement writes under it.",
    "async function ownsCase(caseId: string, ownerId: string | null): Promise<boolean> {",
    "  const found = await getCase(caseId, ownerId);",
    "  return Boolean(found);",
    "}",
    "",
    "// ---- timeline (ported from CaseTimeline.tsx + timeline/page.tsx) ------------",
    "",
    "// List a case's documented events, newest occurrence first (mirrors the",
    "// CaseTimeline sample ordering).",
    "export async function listEvents(caseId: string, ownerId: string | null): Promise<TimelineEvent[]> {",
    "  if (!hasDatabase()) return fallbackEvents.filter((e) => e.caseId === caseId);",
    "  if (!(await ownsCase(caseId, ownerId))) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, case_id, title, description, event_type, occurred_at, created_at",
    "      from case_management_events",
    "      where case_id = ${caseId}",
    "      order by occurred_at desc, created_at desc`;",
    "    return rows.map(rowToEvent);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type AddEventInput = {",
    "  caseId: string; ownerId: string | null;",
    "  title: string; description?: string; eventType?: string; occurredAt?: string;",
    "};",
    "",
    "export async function addEvent(input: AddEventInput): Promise<TimelineEvent | null> {",
    "  if (!hasDatabase()) return null;",
    "  if (!(await ownsCase(input.caseId, input.ownerId))) return null;",
    "  const eventType = TIMELINE_EVENT_TYPES.includes(input.eventType || \"\") ? input.eventType : \"exchange\";",
    "  try {",
    "    const sql = getDatabase();",
    "    const occurred = (input.occurredAt || \"\").trim() || null;",
    "    const rows = await sql`",
    "      insert into case_management_events (case_id, title, description, event_type, occurred_at)",
    "      values (${input.caseId}, ${input.title}, ${input.description || \"\"}, ${eventType},",
    "        coalesce(${occurred}::timestamptz, now()))",
    "      returning id, case_id, title, description, event_type, occurred_at, created_at`;",
    "    return rows[0] ? rowToEvent(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- document center (ported from DocumentCenter.tsx) ----------------------",
    "",
    "export async function listDocuments(caseId: string, ownerId: string | null): Promise<CaseDocument[]> {",
    "  if (!hasDatabase()) return fallbackDocuments.filter((d) => d.caseId === caseId);",
    "  if (!(await ownsCase(caseId, ownerId))) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, case_id, name, doc_type, url, uploaded_at",
    "      from case_management_documents",
    "      where case_id = ${caseId}",
    "      order by uploaded_at desc`;",
    "    return rows.map(rowToDocument);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Classify a document by its file name, ported from DocumentCenter's PDF/Image",
    "// framing (Parenting Plan.pdf -> PDF, School Calendar.png -> Image).",
    "export function classifyDocument(name: string): string {",
    '  const lower = (name || "").toLowerCase();',
    '  if (lower.endsWith(".pdf")) return "PDF";',
    "  if (/\\.(png|jpg|jpeg|gif|webp|heic)$/.test(lower)) return \"Image\";",
    '  if (/\\.(doc|docx|txt|rtf|pages)$/.test(lower)) return "Document";',
    '  if (/\\.(xls|xlsx|csv|numbers)$/.test(lower)) return "Spreadsheet";',
    '  return "File";',
    "}",
    "",
    "export type AddDocumentInput = {",
    "  caseId: string; ownerId: string | null; name: string; url?: string; docType?: string;",
    "};",
    "",
    "export async function addDocument(input: AddDocumentInput): Promise<CaseDocument | null> {",
    "  if (!hasDatabase()) return null;",
    "  if (!(await ownsCase(input.caseId, input.ownerId))) return null;",
    "  const docType = (input.docType || \"\").trim() || classifyDocument(input.name);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into case_management_documents (case_id, name, doc_type, url)",
    "      values (${input.caseId}, ${input.name}, ${docType}, ${input.url || \"\"})",
    "      returning id, case_id, name, doc_type, url, uploaded_at`;",
    "    return rows[0] ? rowToDocument(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- agreement / attendance tracker (ported from AgreementTrackerCard.tsx) --",
    "",
    "export async function listAgreements(caseId: string, ownerId: string | null): Promise<CaseAgreement[]> {",
    "  if (!hasDatabase()) return fallbackAgreements.filter((a) => a.caseId === caseId);",
    "  if (!(await ownsCase(caseId, ownerId))) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, case_id, topic, status, created_at",
    "      from case_management_agreements",
    "      where case_id = ${caseId}",
    "      order by created_at desc`;",
    "    return rows.map(rowToAgreement);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type AddAgreementInput = {",
    "  caseId: string; ownerId: string | null; topic: string; status?: string;",
    "};",
    "",
    "export async function addAgreement(input: AddAgreementInput): Promise<CaseAgreement | null> {",
    "  if (!hasDatabase()) return null;",
    "  if (!(await ownsCase(input.caseId, input.ownerId))) return null;",
    "  const status = AGREEMENT_STATUSES.includes(input.status || \"\") ? input.status : \"Pending Approval\";",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into case_management_agreements (case_id, topic, status)",
    "      values (${input.caseId}, ${input.topic}, ${status})",
    "      returning id, case_id, topic, status, created_at`;",
    "    return rows[0] ? rowToAgreement(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Advance an agreement's status (Pending Approval -> Accepted / Declined).",
    "export async function setAgreementStatus(id: string, caseId: string, ownerId: string | null, status: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  if (!(await ownsCase(caseId, ownerId))) return false;",
    "  const next = AGREEMENT_STATUSES.includes(status) ? status : \"Pending Approval\";",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update case_management_agreements set status = ${next} where id = ${id} and case_id = ${caseId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- court-ready summary (ported from CourtReadySummaryCard.tsx) -----------",
    "",
    "// Build the court-ready summary rows, ported from CourtReadySummaryCard's three",
    "// categories (Parenting Time / Communication / Activities). The childfirst card",
    "// hard-coded '92% schedule completion rate'; here each detail is derived live",
    "// from the case's tracked events + agreements so the summary is real evidence,",
    "// not a placeholder.",
    "export function buildCourtSummary(events: TimelineEvent[], agreements: CaseAgreement[]): CourtSummaryRow[] {",
    "  const exchanges = events.filter((e) => e.eventType === \"exchange\" || e.eventType === \"pickup\");",
    "  const scheduleRequests = events.filter((e) => e.eventType === \"schedule\" || e.eventType === \"request\");",
    "  const completion = exchanges.length + scheduleRequests.length > 0",
    "    ? Math.round((exchanges.length / (exchanges.length + scheduleRequests.length)) * 100)",
    "    : 0;",
    "  const commEvents = events.filter((e) => e.eventType === \"communication\");",
    "  const accepted = agreements.filter((a) => a.status === \"Accepted\").length;",
    "  const activityEvents = events.filter((e) => e.eventType === \"school\" || e.eventType === \"medical\");",
    "  return [",
    "    {",
    '      category: "Parenting Time",',
    "      detail: exchanges.length > 0",
    '        ? `${completion}% schedule completion rate across ${exchanges.length} documented exchanges`',
    '        : "No exchanges documented yet"',
    "    },",
    "    {",
    '      category: "Communication",',
    "      detail: commEvents.length > 0",
    '        ? `${commEvents.length} communication events on record`',
    '        : "Most exchanges resolved without escalation"',
    "    },",
    "    {",
    '      category: "Activities",',
    "      detail: activityEvents.length > 0",
    '        ? `Shared participation documented across ${activityEvents.length} school/medical events`',
    '        : "Shared participation documented"',
    "    },",
    "    {",
    '      category: "Agreements",',
    "      detail: agreements.length > 0",
    '        ? `${accepted} of ${agreements.length} agreements accepted`',
    '        : "No agreements recorded yet"',
    "    }",
    "  ];",
    "}",
    "",
    "export function caseManagementEnabled(): boolean {",
    '  return process.env.FEATURE_CASES !== "false";',
    "}"
  ]);
}

// ---- src/app/api/cases/route.ts (list + create cases) ----------------------

function casesApiFile(): GeneratedModuleFile {
  return file("src/app/api/cases/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listCases, createCase, caseManagementEnabled } from "@/lib/db/case-management";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!caseManagementEnabled()) return NextResponse.json({ ok: false, message: "Case management is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  // Admins see every case; customers see only their own.",
    "  const ownerId = canAccessAdmin(user?.role) ? null : (user?.id ? String(user.id) : \"\");",
    "  const cases = await listCases(ownerId);",
    "  return NextResponse.json({ ok: true, cases });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const caseName = typeof body.caseName === "string" ? body.caseName.trim() : "";',
    "  if (caseName.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give the case a name." }, { status: 400 });',
    "  }",
    "  const created = await createCase({",
    "    ownerId: String(user.id),",
    "    caseName,",
    '    childName: typeof body.childName === "string" ? body.childName.trim() : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save cases." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, case: created });",
    "}"
  ]);
}

// ---- src/app/api/cases/[id]/events/route.ts (timeline) ---------------------

function eventsApiFile(): GeneratedModuleFile {
  return file("src/app/api/cases/[id]/events/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listEvents, addEvent, caseManagementEnabled } from "@/lib/db/case-management";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function scope(role?: string | null, id?: string): string | null {",
    "  return canAccessAdmin(role) ? null : (id ? String(id) : \"\");",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!caseManagementEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const events = await listEvents(id, scope(user?.role, user?.id));",
    "  return NextResponse.json({ ok: true, events });",
    "}",
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Describe what happened." }, { status: 400 });',
    "  }",
    "  const created = await addEvent({",
    "    caseId: id,",
    "    ownerId: scope(user?.role, user.id),",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    '    eventType: typeof body.eventType === "string" ? body.eventType : undefined,',
    '    occurredAt: typeof body.occurredAt === "string" ? body.occurredAt : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Could not add this event. Connect a database and confirm the case is yours." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, event: created });",
    "}"
  ]);
}

// ---- src/app/api/cases/[id]/documents/route.ts (document center) -----------

function documentsApiFile(): GeneratedModuleFile {
  return file("src/app/api/cases/[id]/documents/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listDocuments, addDocument, caseManagementEnabled } from "@/lib/db/case-management";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function scope(role?: string | null, id?: string): string | null {",
    "  return canAccessAdmin(role) ? null : (id ? String(id) : \"\");",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!caseManagementEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const documents = await listDocuments(id, scope(user?.role, user?.id));",
    "  return NextResponse.json({ ok: true, documents });",
    "}",
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    "  if (name.length < 1) {",
    '    return NextResponse.json({ ok: false, message: "Name the document." }, { status: 400 });',
    "  }",
    "  const created = await addDocument({",
    "    caseId: id,",
    "    ownerId: scope(user?.role, user.id),",
    "    name,",
    '    url: typeof body.url === "string" ? body.url : undefined,',
    '    docType: typeof body.docType === "string" ? body.docType : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Could not save this document. Connect a database and confirm the case is yours." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, document: created });",
    "}"
  ]);
}

// ---- src/app/api/cases/[id]/agreements/route.ts (tracker) ------------------

function agreementsApiFile(): GeneratedModuleFile {
  return file("src/app/api/cases/[id]/agreements/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listAgreements, addAgreement, setAgreementStatus, caseManagementEnabled } from "@/lib/db/case-management";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function scope(role?: string | null, id?: string): string | null {",
    "  return canAccessAdmin(role) ? null : (id ? String(id) : \"\");",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!caseManagementEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const agreements = await listAgreements(id, scope(user?.role, user?.id));",
    "  return NextResponse.json({ ok: true, agreements });",
    "}",
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const topic = typeof body.topic === "string" ? body.topic.trim() : "";',
    "  if (topic.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Name the agreement topic." }, { status: 400 });',
    "  }",
    "  const created = await addAgreement({",
    "    caseId: id,",
    "    ownerId: scope(user?.role, user.id),",
    "    topic,",
    '    status: typeof body.status === "string" ? body.status : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Could not save this agreement. Connect a database and confirm the case is yours." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, agreement: created });",
    "}",
    "",
    "// Advance an agreement's status (accept / decline), ported from the tracker's",
    "// Accepted / Pending Approval states.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const agreementId = typeof body.agreementId === "string" ? body.agreementId : "";',
    '  const status = typeof body.status === "string" ? body.status : "";',
    "  if (!agreementId || !status) {",
    '    return NextResponse.json({ ok: false, message: "An agreement and a status are required." }, { status: 400 });',
    "  }",
    "  const ok = await setAgreementStatus(agreementId, id, scope(user?.role, user.id), status);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Could not update this agreement." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/cases/page.tsx (case list + create) ---------------------------

function casesPageFile(): GeneratedModuleFile {
  return file("src/app/cases/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listCases, caseManagementEnabled } from "@/lib/db/case-management";',
    'import { NewCaseForm } from "./new-case-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CasesPage() {",
    "  if (!caseManagementEnabled()) {",
    '    return (<main className="shell"><h1>Cases</h1><p>Case management is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/cases");',
    "  const user = await getCurrentUser();",
    "  const ownerId = canAccessAdmin(user?.role) ? null : (user?.id ? String(user.id) : \"\");",
    "  const cases = await listCases(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Case management</p>',
    "      <h1>Your cases</h1>",
    "      <p>Keep timelines, documents, and agreements for each case in one child-centered workspace. Everything here is organized to be court-ready.</p>",
    "      {cases.length === 0 ? (",
    '        <p className="note">No cases yet. Create your first one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {cases.map((c) => (",
    '            <Link className="wide-card" key={c.id} href={`/cases/${c.id}`}>',
    "              <span>{c.childName || \"Case\"}</span>",
    "              <strong>{c.caseName}</strong>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Start a new case</h2>",
    "      <NewCaseForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/cases/new-case-form.tsx (client) ------------------------------

function newCaseFormFile(): GeneratedModuleFile {
  return file("src/app/cases/new-case-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function NewCaseForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/cases", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ caseName: form.get("caseName"), childName: form.get("childName") })',
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not create the case.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      if (data.case?.id) router.push(`/cases/${data.case.id}`);",
    "      else router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="caseName" placeholder="Case name (e.g. Our Family Parenting Plan)" aria-label="Case name" required />',
    '      <input className="input" name="childName" placeholder="Child\'s first name (optional)" aria-label="Child name" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Creating…" : "Create case"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/cases/[id]/page.tsx (timeline + documents + agreements + summary)

function caseDetailPageFile(): GeneratedModuleFile {
  return file("src/app/cases/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    "import {",
    "  getCase,",
    "  listEvents,",
    "  listDocuments,",
    "  listAgreements,",
    "  buildCourtSummary,",
    "  caseManagementEnabled",
    '} from "@/lib/db/case-management";',
    'import { CaseWorkspace } from "./workspace";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CaseDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!caseManagementEnabled()) {",
    '    return (<main className="shell"><h1>Cases</h1><p>Case management is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/cases");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const ownerId = canAccessAdmin(user?.role) ? null : (user?.id ? String(user.id) : \"\");",
    "  const parentCase = await getCase(id, ownerId);",
    "  if (!parentCase) notFound();",
    "  const [events, documents, agreements] = await Promise.all([",
    "    listEvents(id, ownerId),",
    "    listDocuments(id, ownerId),",
    "    listAgreements(id, ownerId)",
    "  ]);",
    "  const summary = buildCourtSummary(events, agreements);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Case</p>',
    "      <h1>{parentCase.caseName}</h1>",
    "      {parentCase.childName ? <p className=\"note\">For {parentCase.childName}</p> : null}",
    "",
    "      <h2>Court-ready summary</h2>",
    "      <p>A neutral snapshot drawn from the events and agreements on this case.</p>",
    '      <section className="grid">',
    "        {summary.map((row) => (",
    '          <article className="card" key={row.category}>',
    "            <span>{row.category}</span>",
    "            <strong>{row.detail}</strong>",
    "          </article>",
    "        ))}",
    "      </section>",
    "",
    "      <CaseWorkspace caseId={parentCase.id} events={events} documents={documents} agreements={agreements} />",
    "",
    '      <p><Link className="button" href="/cases">Back to cases</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/cases/[id]/workspace.tsx (client: timeline/docs/agreements) ----

function caseWorkspaceFile(): GeneratedModuleFile {
  return file("src/app/cases/[id]/workspace.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type TimelineEvent = { id: string; title: string; description: string; eventType: string; occurredAt: string };",
    "type CaseDocument = { id: string; name: string; docType: string; url: string; uploadedAt: string };",
    "type CaseAgreement = { id: string; topic: string; status: string; createdAt: string };",
    "",
    "const EVENT_TYPES = [\"exchange\", \"pickup\", \"school\", \"medical\", \"communication\", \"expense\", \"schedule\", \"request\", \"incident\", \"violation\"];",
    "const AGREEMENT_STATUSES = [\"Pending Approval\", \"Accepted\", \"Declined\"];",
    "",
    "export function CaseWorkspace({",
    "  caseId,",
    "  events,",
    "  documents,",
    "  agreements",
    "}: {",
    "  caseId: string;",
    "  events: TimelineEvent[];",
    "  documents: CaseDocument[];",
    "  agreements: CaseAgreement[];",
    "}) {",
    "  const router = useRouter();",
    '  const [error, setError] = useState<string>("");',
    "",
    "  async function send(path: string, method: string, payload: Record<string, unknown>) {",
    '    setError("");',
    "    try {",
    "      const response = await fetch(path, {",
    "        method,",
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(payload)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setError(data.message || "Something went wrong.");',
    "        return false;",
    "      }",
    "      router.refresh();",
    "      return true;",
    "    } catch {",
    '      setError("Could not reach the server.");',
    "      return false;",
    "    }",
    "  }",
    "",
    "  async function addEvent(e: React.FormEvent<HTMLFormElement>) {",
    "    e.preventDefault();",
    "    const form = new FormData(e.currentTarget);",
    "    const ok = await send(`/api/cases/${caseId}/events`, \"POST\", {",
    '      title: form.get("title"),',
    '      description: form.get("description"),',
    '      eventType: form.get("eventType")',
    "    });",
    "    if (ok) (e.target as HTMLFormElement).reset();",
    "  }",
    "",
    "  async function addDocument(e: React.FormEvent<HTMLFormElement>) {",
    "    e.preventDefault();",
    "    const form = new FormData(e.currentTarget);",
    "    const ok = await send(`/api/cases/${caseId}/documents`, \"POST\", {",
    '      name: form.get("name"),',
    '      url: form.get("url")',
    "    });",
    "    if (ok) (e.target as HTMLFormElement).reset();",
    "  }",
    "",
    "  async function addAgreement(e: React.FormEvent<HTMLFormElement>) {",
    "    e.preventDefault();",
    "    const form = new FormData(e.currentTarget);",
    "    const ok = await send(`/api/cases/${caseId}/agreements`, \"POST\", {",
    '      topic: form.get("topic"),',
    '      status: form.get("status")',
    "    });",
    "    if (ok) (e.target as HTMLFormElement).reset();",
    "  }",
    "",
    "  async function setStatus(agreementId: string, status: string) {",
    "    await send(`/api/cases/${caseId}/agreements`, \"PATCH\", { agreementId, status });",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    "",
    "      <h2>Case timeline</h2>",
    "      <p>Documented events, most recent first — neutral, factual, court-ready.</p>",
    "      {events.length === 0 ? (",
    '        <p className="note">No events documented yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {events.map((event) => (",
    '            <article className="wide-card" key={event.id}>',
    "              <span>{event.eventType}</span>",
    "              <strong>{event.title}</strong>",
    "              {event.description ? <p>{event.description}</p> : null}",
    '              <small className="note">{event.occurredAt ? new Date(event.occurredAt).toLocaleString() : ""}</small>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <form className="stack" onSubmit={addEvent}>',
    '        <input className="input" name="title" placeholder="What happened? (e.g. Parenting Exchange Completed)" aria-label="Event title" required />',
    '        <input className="input" name="description" placeholder="Neutral note (optional)" aria-label="Event description" />',
    '        <select className="input" name="eventType" aria-label="Event type" defaultValue="exchange">',
    "          {EVENT_TYPES.map((t) => (<option key={t} value={t}>{t}</option>))}",
    "        </select>",
    '        <button className="button primary" type="submit">Add event</button>',
    "      </form>",
    "",
    "      <h2>Document center</h2>",
    "      <p>Upload and organize parenting plans, schedules, reports, and supporting documents.</p>",
    "      {documents.length === 0 ? (",
    '        <p className="note">No documents yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {documents.map((doc) => (",
    '            <article className="wide-card" key={doc.id}>',
    "              <span>{doc.docType}</span>",
    "              {doc.url ? (",
    '                <strong><a href={doc.url} target="_blank" rel="noreferrer">{doc.name}</a></strong>',
    "              ) : (",
    "                <strong>{doc.name}</strong>",
    "              )}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <form className="stack" onSubmit={addDocument}>',
    '        <input className="input" name="name" placeholder="Document name (e.g. Parenting Plan.pdf)" aria-label="Document name" required />',
    '        <input className="input" name="url" placeholder="Link to the file (optional)" aria-label="Document link" />',
    '        <button className="button primary" type="submit">Add document</button>',
    "      </form>",
    "",
    "      <h2>Agreement tracker</h2>",
    "      <p>Track shared decisions and their status — Pending Approval, Accepted, or Declined.</p>",
    "      {agreements.length === 0 ? (",
    '        <p className="note">No agreements tracked yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {agreements.map((agreement) => (",
    '            <article className="wide-card" key={agreement.id}>',
    "              <span>{agreement.status}</span>",
    "              <strong>{agreement.topic}</strong>",
    '              {agreement.status === "Pending Approval" ? (',
    '                <div className="stack">',
    '                  <button className="button primary" type="button" onClick={() => setStatus(agreement.id, "Accepted")}>Accept</button>',
    '                  <button className="button" type="button" onClick={() => setStatus(agreement.id, "Declined")}>Decline</button>',
    "                </div>",
    "              ) : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <form className="stack" onSubmit={addAgreement}>',
    '        <input className="input" name="topic" placeholder="Agreement topic (e.g. Summer Vacation Week)" aria-label="Agreement topic" required />',
    '        <select className="input" name="status" aria-label="Agreement status" defaultValue="Pending Approval">',
    "          {AGREEMENT_STATUSES.map((s) => (<option key={s} value={s}>{s}</option>))}",
    "        </select>",
    '        <button className="button primary" type="submit">Add agreement</button>',
    "      </form>",
    "    </div>",
    "  );",
    "}"
  ]);
}

export const caseManagementModule: AppModule = {
  slug: "case-management",
  name: "Case Management",
  tier: "optional",
  featureFlagEnv: "FEATURE_CASES",
  files: () => [
    caseLibFile(),
    casesApiFile(),
    eventsApiFile(),
    documentsApiFile(),
    agreementsApiFile(),
    casesPageFile(),
    newCaseFormFile(),
    caseDetailPageFile(),
    caseWorkspaceFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists case_management_cases (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid not null references users(id) on delete cascade,",
      "  case_name text not null default '',",
      "  child_name text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists case_management_cases_owner_idx on case_management_cases (owner_id, created_at desc);",
      "",
      "create table if not exists case_management_events (",
      "  id uuid primary key default gen_random_uuid(),",
      "  case_id uuid not null references case_management_cases(id) on delete cascade,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  event_type text not null default 'exchange',",
      "  occurred_at timestamptz not null default now(),",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists case_management_events_case_idx on case_management_events (case_id, occurred_at desc);",
      "",
      "create table if not exists case_management_documents (",
      "  id uuid primary key default gen_random_uuid(),",
      "  case_id uuid not null references case_management_cases(id) on delete cascade,",
      "  name text not null default '',",
      "  doc_type text not null default 'File',",
      "  url text not null default '',",
      "  uploaded_at timestamptz not null default now()",
      ");",
      "create index if not exists case_management_documents_case_idx on case_management_documents (case_id, uploaded_at desc);",
      "",
      "create table if not exists case_management_agreements (",
      "  id uuid primary key default gen_random_uuid(),",
      "  case_id uuid not null references case_management_cases(id) on delete cascade,",
      "  topic text not null default '',",
      "  status text not null default 'Pending Approval',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists case_management_agreements_case_idx on case_management_agreements (case_id, created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Sample case data is only meaningful once a real owner exists; the graceful",
      "-- in-app fallback (fallbackCases/Events/Documents/Agreements) covers the",
      "-- no-database demo, so no owner-less seed rows are inserted here."
    ].join("\n"),
  envLines: () => [
    "",
    "# Case Management — set to false to switch case timelines, the document center,",
    "# court-ready summaries, and the agreement tracker off.",
    "FEATURE_CASES=true"
  ],
  homeLinks: () => ['        <a className="button" href="/cases">Cases</a>'],
  navLinks: () => [{ href: "/cases", label: "Cases" }]
};
