// checkin — secure check-in + staffing for events, kids, and services. Ported
// from ChurchConnect's real check-in + childcare staffing backend:
//   - backend/routes/checkin.py: the check-in SESSION model (a unique 6-char
//     code per service — create_checkin_session's random ascii+digits code —
//     service_name/service_type/date/start_time/speaker/sermon_title, an
//     is_active toggle, and the running attendance_count / first_time_visitors /
//     returning_visitors / feedback_count stats), the individual CHECK-IN record
//     (session_id, person name/email/phone, is_first_time_visitor derived by
//     looking up a prior check-in for the same email at the same owner, how_heard,
//     contact_requested/contact_reason), the public submit flow that bumps the
//     session stats (+attendance, +first_time OR +returning), get_session_by_code
//     (reject inactive sessions), toggle_session_active, and get_attendance_stats
//     (last-30-days totals, unique visitors by email, first-timer %, avg/session).
//   - backend/routes/childcare_staffing.py: per-owner nursery/childcare STAFFING —
//     the DEFAULT_RATIOS table (infant 1:4, toddler 1:5, preschool 1:7, pre_k 1:8,
//     elementary 1:10), staffing ROLES with clearance requirements
//     (requires_background_check / cpr / child_protection_training, min_age_to_serve),
//     SHIFTS (event_date, start/end time, room, role, slots_needed) that volunteers
//     self-sign-up for, the (shift,user) unique-signup guard + drop, and the
//     get_schedule composition that reports filled vs slots_needed, needs_more, and
//     an uncleared_alert when a signed-up volunteer is not background-check cleared.
// Generalized off the church framing into plain, warm copy so it drops into any
// app that runs events with kids/services. Runs on the app owner's own database
// with graceful sample-data fallback, feature-flagged (FEATURE_CHECKIN); customers
// create sessions + check people in + staff shifts (rows scoped to user.id), and
// mutating/admin controls (toggle a session, define staffing roles) are admin-gated.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/checkin.ts (model + queries, ported from the real sources) ---

function checkinLibFile(): GeneratedModuleFile {
  return file("src/lib/db/checkin.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A check-in SESSION, ported from checkin.py create_checkin_session: one live",
    "// window per service/event, addressed by a unique 6-character code attendees",
    "// enter (or scan) to check in. is_active gates whether the code still works, and",
    "// the counters mirror the session stats bumped on every check-in.",
    "export type CheckinSession = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  code: string;",
    "  serviceName: string;",
    "  serviceType: string;",
    "  date: string;",
    "  startTime: string;",
    "  speaker: string;",
    "  sermonTitle: string;",
    "  isActive: boolean;",
    "  attendanceCount: number;",
    "  firstTimeVisitors: number;",
    "  returningVisitors: number;",
    "  createdAt: string;",
    "};",
    "",
    "// An individual CHECK-IN record, ported from checkin.py public_checkin: who",
    "// showed up, whether they are a first-time visitor (derived by a prior check-in",
    "// lookup on the same email under the same owner), and whether they asked to be",
    "// contacted.",
    "export type Checkin = {",
    "  id: string;",
    "  sessionId: string;",
    "  ownerId: string | null;",
    "  personName: string;",
    "  personEmail: string;",
    "  personPhone: string;",
    "  isFirstTimeVisitor: boolean;",
    "  howHeard: string;",
    "  contactRequested: boolean;",
    "  contactReason: string;",
    "  createdAt: string;",
    "};",
    "",
    "// The service types a session can be, ported from checkin.py's service_type",
    "// (sunday_morning default), generalized to any recurring event.",
    "export const CHECKIN_SERVICE_TYPES = [",
    '  "sunday_morning",',
    '  "sunday_evening",',
    '  "wednesday",',
    '  "special",',
    '  "event"',
    "];",
    "",
    "// Generate a unique 6-character code, ported verbatim from create_checkin_session",
    "// (random.choices over ascii_uppercase + digits, k=6).",
    "export function generateCode(): string {",
    '  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";',
    '  let code = "";',
    "  for (let i = 0; i < 6; i += 1) {",
    "    code += alphabet[Math.floor(Math.random() * alphabet.length)];",
    "  }",
    "  return code;",
    "}",
    "",
    "const fallbackSessions: CheckinSession[] = [",
    "  {",
    '    id: "sample-session-1",',
    "    ownerId: null,",
    '    code: "SUN123",',
    '    serviceName: "Sunday Service",',
    '    serviceType: "sunday_morning",',
    '    date: "2025-01-05",',
    '    startTime: "10:00",',
    '    speaker: "Pastor Lee",',
    '    sermonTitle: "A place to belong",',
    "    isActive: true,",
    "    attendanceCount: 42,",
    "    firstTimeVisitors: 6,",
    "    returningVisitors: 36,",
    '    createdAt: "2025-01-05T09:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-session-2",',
    "    ownerId: null,",
    '    code: "WED456",',
    '    serviceName: "Midweek Gathering",',
    '    serviceType: "wednesday",',
    '    date: "2025-01-08",',
    '    startTime: "19:00",',
    '    speaker: "",',
    '    sermonTitle: "",',
    "    isActive: false,",
    "    attendanceCount: 18,",
    "    firstTimeVisitors: 2,",
    "    returningVisitors: 16,",
    '    createdAt: "2025-01-08T18:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackCheckins: Checkin[] = [",
    "  {",
    '    id: "sample-checkin-1",',
    '    sessionId: "sample-session-1",',
    "    ownerId: null,",
    '    personName: "Jordan P.",',
    '    personEmail: "jordan@example.com",',
    '    personPhone: "",',
    "    isFirstTimeVisitor: true,",
    '    howHeard: "A friend invited me",',
    "    contactRequested: true,",
    '    contactReason: "connect",',
    '    createdAt: "2025-01-05T10:02:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToSession(row: Record<string, unknown>): CheckinSession {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    code: String(row.code || ""),',
    '    serviceName: String(row.service_name || ""),',
    '    serviceType: String(row.service_type || "event"),',
    '    date: row.date ? String(row.date) : "",',
    '    startTime: String(row.start_time || ""),',
    '    speaker: String(row.speaker || ""),',
    '    sermonTitle: String(row.sermon_title || ""),',
    '    isActive: row.is_active === true || String(row.is_active) === "true",',
    "    attendanceCount: Number(row.attendance_count || 0),",
    "    firstTimeVisitors: Number(row.first_time_visitors || 0),",
    "    returningVisitors: Number(row.returning_visitors || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToCheckin(row: Record<string, unknown>): Checkin {",
    "  return {",
    "    id: String(row.id),",
    '    sessionId: String(row.session_id || ""),',
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    personName: String(row.person_name || "Anonymous"),',
    '    personEmail: String(row.person_email || ""),',
    '    personPhone: String(row.person_phone || ""),',
    '    isFirstTimeVisitor: row.is_first_time_visitor === true || String(row.is_first_time_visitor) === "true",',
    '    howHeard: String(row.how_heard || ""),',
    '    contactRequested: row.contact_requested === true || String(row.contact_requested) === "true",',
    '    contactReason: String(row.contact_reason || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// List sessions, ported from get_checkin_sessions: newest first, optionally only",
    "// the active ones, scoped to an owner.",
    "export async function listSessions(ownerId?: string, activeOnly = false, limit = 20): Promise<CheckinSession[]> {",
    "  const cap = Math.min(100, Math.max(1, limit));",
    "  if (!hasDatabase()) {",
    "    return fallbackSessions",
    "      .filter((s) => !ownerId || s.ownerId === ownerId)",
    "      .filter((s) => !activeOnly || s.isActive)",
    "      .slice(0, cap);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const active = activeOnly ? true : null;",
    "    const rows = await sql`",
    "      select id, owner_id, code, service_name, service_type, date, start_time,",
    "        speaker, sermon_title, is_active, attendance_count, first_time_visitors,",
    "        returning_visitors, created_at",
    "      from checkin_sessions",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${active}::boolean is null or is_active = ${active})",
    "      order by created_at desc limit ${cap}",
    "    `;",
    "    return rows.map(rowToSession);",
    "  } catch {",
    "    return fallbackSessions.slice(0, cap);",
    "  }",
    "}",
    "",
    "export async function getSession(id: string): Promise<CheckinSession | null> {",
    "  if (!hasDatabase()) return fallbackSessions.find((s) => s.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, code, service_name, service_type, date, start_time,",
    "        speaker, sermon_title, is_active, attendance_count, first_time_visitors,",
    "        returning_visitors, created_at",
    "      from checkin_sessions where id = ${id} limit 1`;",
    "    return rows[0] ? rowToSession(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Look a session up by its code, ported from get_session_by_code: codes are",
    "// matched upper-cased and an ended (inactive) session is reported so the caller",
    "// can refuse the check-in.",
    "export async function getSessionByCode(code: string): Promise<CheckinSession | null> {",
    '  const upper = (code || "").trim().toUpperCase();',
    "  if (!upper) return null;",
    "  if (!hasDatabase()) return fallbackSessions.find((s) => s.code === upper) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, code, service_name, service_type, date, start_time,",
    "        speaker, sermon_title, is_active, attendance_count, first_time_visitors,",
    "        returning_visitors, created_at",
    "      from checkin_sessions where code = ${upper} limit 1`;",
    "    return rows[0] ? rowToSession(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateSessionInput = {",
    "  ownerId: string | null;",
    "  serviceName?: string;",
    "  serviceType?: string;",
    "  date?: string;",
    "  startTime?: string;",
    "  speaker?: string;",
    "  sermonTitle?: string;",
    "};",
    "",
    "// Create a session, ported from create_checkin_session: mint a unique 6-char code",
    "// (retry a few times on the off chance of a collision), default the service name",
    "// and today's date, and start it active with zeroed counters.",
    "export async function createSession(input: CreateSessionInput): Promise<CheckinSession | null> {",
    "  if (!hasDatabase()) return null;",
    '  const serviceName = (input.serviceName || "Service").trim() || "Service";',
    '  const serviceType = input.serviceType || "event";',
    '  const date = (input.date || new Date().toISOString().slice(0, 10));',
    "  try {",
    "    const sql = getDatabase();",
    "    for (let attempt = 0; attempt < 5; attempt += 1) {",
    "      const code = generateCode();",
    "      const existing = await sql`select id from checkin_sessions where code = ${code} limit 1`;",
    "      if (existing[0]) continue;",
    "      const rows = await sql`",
    "        insert into checkin_sessions (",
    "          owner_id, code, service_name, service_type, date, start_time, speaker,",
    "          sermon_title, is_active",
    "        ) values (",
    "          ${input.ownerId || null}, ${code}, ${serviceName}, ${serviceType}, ${date},",
    '          ${input.startTime || ""}, ${input.speaker || ""}, ${input.sermonTitle || ""}, true',
    "        )",
    "        returning id, owner_id, code, service_name, service_type, date, start_time,",
    "          speaker, sermon_title, is_active, attendance_count, first_time_visitors,",
    "          returning_visitors, created_at`;",
    "      return rows[0] ? rowToSession(rows[0]) : null;",
    "    }",
    "    return null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Toggle a session on/off, ported from toggle_session_active: an ended session",
    "// stops accepting check-ins.",
    "export async function toggleSession(id: string): Promise<{ isActive: boolean } | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update checkin_sessions set is_active = not is_active where id = ${id}",
    "      returning is_active`;",
    "    if (!rows[0]) return null;",
    '    return { isActive: rows[0].is_active === true || String(rows[0].is_active) === "true" };',
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function listCheckins(sessionId: string, limit = 500): Promise<Checkin[]> {",
    "  const cap = Math.min(2000, Math.max(1, limit));",
    "  if (!hasDatabase()) return fallbackCheckins.filter((c) => c.sessionId === sessionId).slice(0, cap);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, session_id, owner_id, person_name, person_email, person_phone,",
    "        is_first_time_visitor, how_heard, contact_requested, contact_reason, created_at",
    "      from checkin_records where session_id = ${sessionId}",
    "      order by created_at desc limit ${cap}`;",
    "    return rows.map(rowToCheckin);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type SubmitCheckinInput = {",
    "  code: string;",
    "  name?: string;",
    "  email?: string;",
    "  phone?: string;",
    "  howHeard?: string;",
    "  contactRequested?: boolean;",
    "  contactReason?: string;",
    "};",
    "",
    "export type SubmitCheckinResult = {",
    "  ok: boolean;",
    "  message: string;",
    "  isFirstTime?: boolean;",
    "  welcomeMessage?: string;",
    "  session?: CheckinSession;",
    "  checkinId?: string;",
    "};",
    "",
    "// Check someone in, ported from public_checkin: verify the code exists AND the",
    "// session is still active, derive first-time vs returning by looking up a prior",
    "// check-in for the same email under the same owner, insert the record, and bump",
    "// the session stats (+attendance and +first_time OR +returning) in one update.",
    "export async function submitCheckin(input: SubmitCheckinInput): Promise<SubmitCheckinResult> {",
    '  const code = (input.code || "").trim().toUpperCase();',
    '  if (!code) return { ok: false, message: "A check-in code is required." };',
    "  const session = await getSessionByCode(code);",
    '  if (!session) return { ok: false, message: "That check-in code was not found." };',
    '  if (!session.isActive) return { ok: false, message: "This check-in session has ended." };',
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to record check-ins." };',
    '  const email = (input.email || "").trim().toLowerCase();',
    '  const name = (input.name || "").trim() || "Anonymous";',
    "  try {",
    "    const sql = getDatabase();",
    "    // First-time vs returning, ported from public_checkin's prior-visit lookup:",
    "    // a match on the same email under the same owner means they have been before.",
    "    let isFirstTime = true;",
    "    if (email) {",
    "      const owner = session.ownerId || null;",
    "      const prior = await sql`",
    "        select id from checkin_records",
    "        where person_email = ${email}",
    "          and (${owner}::uuid is null or owner_id = ${owner})",
    "        limit 1`;",
    "      isFirstTime = !prior[0];",
    "    }",
    "    const rows = await sql`",
    "      insert into checkin_records (",
    "        session_id, owner_id, person_name, person_email, person_phone,",
    "        is_first_time_visitor, how_heard, contact_requested, contact_reason",
    "      ) values (",
    "        ${session.id}, ${session.ownerId || null}, ${name}, ${email},",
    '        ${input.phone || ""}, ${isFirstTime}, ${input.howHeard || ""},',
    '        ${input.contactRequested === true}, ${input.contactReason || ""}',
    "      )",
    "      returning id`;",
    "    const checkinId = rows[0] ? String(rows[0].id) : undefined;",
    "    // Bump the session counters, ported from the $inc update in public_checkin.",
    "    if (isFirstTime) {",
    "      await sql`update checkin_sessions set attendance_count = attendance_count + 1, first_time_visitors = first_time_visitors + 1 where id = ${session.id}`;",
    "    } else {",
    "      await sql`update checkin_sessions set attendance_count = attendance_count + 1, returning_visitors = returning_visitors + 1 where id = ${session.id}`;",
    "    }",
    "    return {",
    "      ok: true,",
    '      message: "Checked in.",',
    "      isFirstTime,",
    "      welcomeMessage: isFirstTime",
    '        ? "Welcome! We are so glad you are here."',
    '        : "Welcome back! Great to see you again.",',
    "      session,",
    "      checkinId",
    "    };",
    "  } catch {",
    '    return { ok: false, message: "Could not record the check-in. Please try again." };',
    "  }",
    "}",
    "",
    "export type AttendanceStats = {",
    "  totalSessions: number;",
    "  totalAttendance: number;",
    "  uniqueVisitors: number;",
    "  firstTimeVisitors: number;",
    "  returningVisitors: number;",
    "  averagePerSession: number;",
    "  contactRequests: number;",
    "  firstTimerPercentage: number;",
    "};",
    "",
    "const emptyStats: AttendanceStats = {",
    "  totalSessions: 0, totalAttendance: 0, uniqueVisitors: 0, firstTimeVisitors: 0,",
    "  returningVisitors: 0, averagePerSession: 0, contactRequests: 0, firstTimerPercentage: 0",
    "};",
    "",
    "// Last-30-days attendance stats, ported from get_attendance_stats: total sessions",
    "// + check-ins, unique visitors by distinct email, first-timers and the first-timer",
    "// percentage, contact requests, and average attendance per session.",
    "export async function getAttendanceStats(ownerId?: string): Promise<AttendanceStats> {",
    "  if (!hasDatabase()) {",
    "    const sessions = fallbackSessions.filter((s) => !ownerId || s.ownerId === ownerId);",
    "    const checkins = fallbackCheckins.filter((c) => !ownerId || c.ownerId === ownerId);",
    "    const first = checkins.filter((c) => c.isFirstTimeVisitor).length;",
    "    const total = checkins.length;",
    "    return {",
    "      totalSessions: sessions.length,",
    "      totalAttendance: total,",
    "      uniqueVisitors: new Set(checkins.map((c) => c.personEmail).filter(Boolean)).size,",
    "      firstTimeVisitors: first,",
    "      returningVisitors: total - first,",
    "      averagePerSession: sessions.length ? Math.round((total / sessions.length) * 10) / 10 : 0,",
    "      contactRequests: checkins.filter((c) => c.contactRequested).length,",
    "      firstTimerPercentage: total ? Math.round((first / total) * 1000) / 10 : 0",
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const sessRows = await sql`",
    "      select count(*)::int as n from checkin_sessions",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and created_at >= now() - interval '30 days'`;",
    "    const chkRows = await sql`",
    "      select",
    "        count(*)::int as total,",
    "        count(*) filter (where is_first_time_visitor)::int as first_timers,",
    "        count(distinct nullif(person_email, ''))::int as unique_visitors,",
    "        count(*) filter (where contact_requested)::int as contact_requests",
    "      from checkin_records",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and created_at >= now() - interval '30 days'`;",
    "    const totalSessions = Number(sessRows[0]?.n || 0);",
    "    const total = Number(chkRows[0]?.total || 0);",
    "    const firstTimers = Number(chkRows[0]?.first_timers || 0);",
    "    return {",
    "      totalSessions,",
    "      totalAttendance: total,",
    "      uniqueVisitors: Number(chkRows[0]?.unique_visitors || 0),",
    "      firstTimeVisitors: firstTimers,",
    "      returningVisitors: total - firstTimers,",
    "      averagePerSession: totalSessions ? Math.round((total / totalSessions) * 10) / 10 : 0,",
    "      contactRequests: Number(chkRows[0]?.contact_requests || 0),",
    "      firstTimerPercentage: total ? Math.round((firstTimers / total) * 1000) / 10 : 0",
    "    };",
    "  } catch {",
    "    return emptyStats;",
    "  }",
    "}",
    "",
    "// ---- Childcare / event STAFFING (ported from childcare_staffing.py) --------",
    "",
    "// The standard adult-to-child ratios, ported verbatim from DEFAULT_RATIOS.",
    "export const DEFAULT_RATIOS = [",
    '  { ageBand: "infant", minAge: 0, maxAge: 1, ratio: "1:4", notes: "0-12 months" },',
    '  { ageBand: "toddler", minAge: 1, maxAge: 2, ratio: "1:5", notes: "1-2 years" },',
    '  { ageBand: "preschool", minAge: 3, maxAge: 4, ratio: "1:7", notes: "3-4 years" },',
    '  { ageBand: "pre_k", minAge: 4, maxAge: 5, ratio: "1:8", notes: "Pre-K" },',
    '  { ageBand: "elementary", minAge: 5, maxAge: 12, ratio: "1:10", notes: "K-5th grade" }',
    "];",
    "",
    "// A staffing role, ported from childcare_staffing.py RoleIn: what clearances a",
    "// volunteer must hold to serve in it.",
    "export type StaffRole = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  description: string;",
    "  requiresBackgroundCheck: boolean;",
    "  requiresCpr: boolean;",
    "  requiresChildProtectionTraining: boolean;",
    "  minAgeToServe: number;",
    "  createdAt: string;",
    "};",
    "",
    "// A shift volunteers self-sign-up for, ported from ShiftIn.",
    "export type Shift = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  eventDate: string;",
    "  startTime: string;",
    "  endTime: string;",
    "  roomName: string;",
    "  roleId: string | null;",
    "  slotsNeeded: number;",
    "  notes: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A volunteer's signup for a shift, ported from signup_for_shift: the clearance",
    "// flag is captured at signup time so the schedule can flag uncleared volunteers.",
    "export type ShiftSignup = {",
    "  id: string;",
    "  shiftId: string;",
    "  userId: string;",
    "  name: string;",
    "  email: string;",
    "  isClearedAtSignup: boolean;",
    "  signedUpAt: string;",
    "};",
    "",
    "// A shift composed with its role + signups + ratio analysis, ported from the",
    "// get_schedule dashboard composition.",
    "export type ScheduledShift = Shift & {",
    "  role: StaffRole | null;",
    "  signups: ShiftSignup[];",
    "  filled: number;",
    "  clearedFilled: number;",
    "  needsMore: number;",
    "  unclearedAlert: boolean;",
    "};",
    "",
    "const fallbackRoles: StaffRole[] = [",
    "  {",
    '    id: "sample-role-1",',
    "    ownerId: null,",
    '    name: "Nursery Lead",',
    '    description: "Leads the infant room and coordinates helpers.",',
    "    requiresBackgroundCheck: true,",
    "    requiresCpr: true,",
    "    requiresChildProtectionTraining: true,",
    "    minAgeToServe: 18,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-role-2",',
    "    ownerId: null,",
    '    name: "Toddler Helper",',
    '    description: "Supports the toddler room.",',
    "    requiresBackgroundCheck: true,",
    "    requiresCpr: false,",
    "    requiresChildProtectionTraining: true,",
    "    minAgeToServe: 16,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackShifts: Shift[] = [",
    "  {",
    '    id: "sample-shift-1",',
    "    ownerId: null,",
    '    eventDate: "2025-01-05",',
    '    startTime: "09:00",',
    '    endTime: "10:30",',
    '    roomName: "Infant Room",',
    '    roleId: "sample-role-1",',
    "    slotsNeeded: 2,",
    '    notes: "",',
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackSignups: ShiftSignup[] = [",
    "  {",
    '    id: "sample-signup-1",',
    '    shiftId: "sample-shift-1",',
    '    userId: "sample-user-1",',
    '    name: "Dana R.",',
    '    email: "dana@example.com",',
    "    isClearedAtSignup: true,",
    '    signedUpAt: "2025-01-02T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToRole(row: Record<string, unknown>): StaffRole {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    name: String(row.name || ""),',
    '    description: String(row.description || ""),',
    '    requiresBackgroundCheck: row.requires_background_check === true || String(row.requires_background_check) === "true",',
    '    requiresCpr: row.requires_cpr === true || String(row.requires_cpr) === "true",',
    '    requiresChildProtectionTraining: row.requires_child_protection_training === true || String(row.requires_child_protection_training) === "true",',
    "    minAgeToServe: Number(row.min_age_to_serve || 18),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToShift(row: Record<string, unknown>): Shift {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    eventDate: row.event_date ? String(row.event_date) : "",',
    '    startTime: String(row.start_time || ""),',
    '    endTime: String(row.end_time || ""),',
    '    roomName: String(row.room_name || ""),',
    "    roleId: row.role_id != null ? String(row.role_id) : null,",
    "    slotsNeeded: Number(row.slots_needed || 1),",
    '    notes: String(row.notes || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToSignup(row: Record<string, unknown>): ShiftSignup {",
    "  return {",
    "    id: String(row.id),",
    '    shiftId: String(row.shift_id || ""),',
    '    userId: String(row.user_id || ""),',
    '    name: String(row.name || ""),',
    '    email: String(row.email || ""),',
    '    isClearedAtSignup: row.is_cleared_at_signup === true || String(row.is_cleared_at_signup) === "true",',
    '    signedUpAt: row.signed_up_at ? String(row.signed_up_at) : ""',
    "  };",
    "}",
    "",
    "// List staffing roles, ported from list_roles (name order), scoped to an owner.",
    "export async function listRoles(ownerId?: string): Promise<StaffRole[]> {",
    "  if (!hasDatabase()) return fallbackRoles.filter((r) => !ownerId || r.ownerId === ownerId);",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve, created_at",
    "      from checkin_staff_roles",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "      order by name asc`;",
    "    return rows.map(rowToRole);",
    "  } catch {",
    "    return fallbackRoles;",
    "  }",
    "}",
    "",
    "export type CreateRoleInput = {",
    "  ownerId: string | null;",
    "  name: string;",
    "  description?: string;",
    "  requiresBackgroundCheck?: boolean;",
    "  requiresCpr?: boolean;",
    "  requiresChildProtectionTraining?: boolean;",
    "  minAgeToServe?: number;",
    "};",
    "",
    "// Create a staffing role, ported from create_role (church-admin-only in the",
    "// original; admin-gated at the API layer here).",
    "export async function createRole(input: CreateRoleInput): Promise<StaffRole | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into checkin_staff_roles (",
    "        owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.name}, ${input.description || ""},',
    "        ${input.requiresBackgroundCheck !== false}, ${input.requiresCpr === true},",
    "        ${input.requiresChildProtectionTraining !== false}, ${input.minAgeToServe || 18}",
    "      )",
    "      returning id, owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve, created_at`;",
    "    return rows[0] ? rowToRole(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// List shifts in a date range, ported from list_shifts (event_date/start_time",
    "// order), scoped to an owner.",
    "export async function listShifts(ownerId?: string, startDate?: string, endDate?: string): Promise<Shift[]> {",
    "  if (!hasDatabase()) return fallbackShifts.filter((s) => !ownerId || s.ownerId === ownerId);",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const from = startDate || null;",
    "    const to = endDate || null;",
    "    const rows = await sql`",
    "      select id, owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes, created_at",
    "      from checkin_shifts",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${from}::text is null or event_date >= ${from})",
    "        and (${to}::text is null or event_date <= ${to})",
    "      order by event_date asc, start_time asc`;",
    "    return rows.map(rowToShift);",
    "  } catch {",
    "    return fallbackShifts;",
    "  }",
    "}",
    "",
    "export type CreateShiftInput = {",
    "  ownerId: string | null;",
    "  eventDate: string;",
    "  startTime: string;",
    "  endTime: string;",
    "  roomName?: string;",
    "  roleId?: string | null;",
    "  slotsNeeded?: number;",
    "  notes?: string;",
    "};",
    "",
    "// Create a shift, ported from create_shift.",
    "export async function createShift(input: CreateShiftInput): Promise<Shift | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into checkin_shifts (",
    "        owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.eventDate}, ${input.startTime}, ${input.endTime},",
    '        ${input.roomName || ""}, ${input.roleId || null}, ${Math.max(1, input.slotsNeeded || 1)},',
    '        ${input.notes || ""}',
    "      )",
    "      returning id, owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes, created_at`;",
    "    return rows[0] ? rowToShift(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Sign a volunteer up for a shift, ported from signup_for_shift: the (shift,user)",
    "// unique guard means a repeat is a no-op, and the volunteer's cleared flag is",
    "// captured at signup time. Returns already=true if they were already on it.",
    "export async function signupForShift(",
    "  shiftId: string,",
    "  user: { id: string; name?: string; email?: string; cleared?: boolean }",
    "): Promise<{ ok: boolean; already?: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to sign up for shifts." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const shift = await sql`select id from checkin_shifts where id = ${shiftId} limit 1`;",
    '    if (!shift[0]) return { ok: false, message: "That shift was not found." };',
    "    const cleared = user.cleared === true;",
    "    const rows = await sql`",
    "      insert into checkin_shift_signups (shift_id, user_id, name, email, is_cleared_at_signup)",
    '      values (${shiftId}, ${user.id}, ${user.name || ""}, ${user.email || ""}, ${cleared})',
    "      on conflict (shift_id, user_id) do nothing",
    "      returning id`;",
    "    if (!rows[0]) return { ok: true, already: true };",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not sign up. Please try again." };',
    "  }",
    "}",
    "",
    "// Drop a volunteer from a shift, ported from drop_signup.",
    "export async function dropSignup(shiftId: string, userId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from checkin_shift_signups where shift_id = ${shiftId} and user_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// The schedule view for a date, ported from get_schedule: each shift composed",
    "// with its role and signups, plus filled vs slots_needed (needs_more) and an",
    "// uncleared_alert when a signed-up volunteer was not cleared at signup.",
    "export async function getSchedule(date: string, ownerId?: string): Promise<ScheduledShift[]> {",
    "  const shifts = await listShifts(ownerId, date, date);",
    "  if (shifts.length === 0) return [];",
    "  const roles = await listRoles(ownerId);",
    "  const roleById = new Map(roles.map((r) => [r.id, r]));",
    "  let signupsByShift = new Map<string, ShiftSignup[]>();",
    "  if (!hasDatabase()) {",
    "    for (const s of fallbackSignups) {",
    "      const list = signupsByShift.get(s.shiftId) || [];",
    "      list.push(s);",
    "      signupsByShift.set(s.shiftId, list);",
    "    }",
    "  } else {",
    "    try {",
    "      const sql = getDatabase();",
    "      const ids = shifts.map((s) => s.id);",
    "      const rows = await sql`",
    "        select id, shift_id, user_id, name, email, is_cleared_at_signup, signed_up_at",
    "        from checkin_shift_signups where shift_id = any(${ids})`;",
    "      const grouped = new Map<string, ShiftSignup[]>();",
    "      for (const row of rows) {",
    "        const signup = rowToSignup(row);",
    "        const list = grouped.get(signup.shiftId) || [];",
    "        list.push(signup);",
    "        grouped.set(signup.shiftId, list);",
    "      }",
    "      signupsByShift = grouped;",
    "    } catch {",
    "      signupsByShift = new Map();",
    "    }",
    "  }",
    "  return shifts.map((shift) => {",
    "    const signups = signupsByShift.get(shift.id) || [];",
    "    const clearedFilled = signups.filter((x) => x.isClearedAtSignup).length;",
    "    return {",
    "      ...shift,",
    "      role: shift.roleId ? roleById.get(shift.roleId) || null : null,",
    "      signups,",
    "      filled: signups.length,",
    "      clearedFilled,",
    "      needsMore: Math.max(0, shift.slotsNeeded - signups.length),",
    "      unclearedAlert: clearedFilled < signups.length",
    "    };",
    "  });",
    "}",
    "",
    "export function checkinEnabled(): boolean {",
    '  return process.env.FEATURE_CHECKIN !== "false";',
    "}"
  ]);
}

// ---- src/app/api/checkin/route.ts (list + create sessions) ------------------

function sessionsApiFile(): GeneratedModuleFile {
  return file("src/app/api/checkin/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listSessions, createSession, getAttendanceStats, checkinEnabled } from "@/lib/db/checkin";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!checkinEnabled()) return NextResponse.json({ ok: false, message: "Check-in is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    '  const activeOnly = url.searchParams.get("active") === "true";',
    "  const sessions = await listSessions(ownerId, activeOnly);",
    "  const stats = await getAttendanceStats(ownerId);",
    "  return NextResponse.json({ ok: true, sessions, stats });",
    "}",
    "",
    "// Create a check-in session, ported from create_checkin_session. Scoped to the",
    "// signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to open a session." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const serviceName = typeof body.serviceName === "string" ? body.serviceName.trim() : "";',
    "  if (serviceName.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give this session a name." }, { status: 400 });',
    "  }",
    "  const created = await createSession({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    serviceName,",
    '    serviceType: typeof body.serviceType === "string" ? body.serviceType : undefined,',
    '    date: typeof body.date === "string" ? body.date : undefined,',
    '    startTime: typeof body.startTime === "string" ? body.startTime : undefined,',
    '    speaker: typeof body.speaker === "string" ? body.speaker : undefined,',
    '    sermonTitle: typeof body.sermonTitle === "string" ? body.sermonTitle : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to open sessions." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, session: created, message: `Session open. Share code ${created.code}.` });',
    "}"
  ]);
}

// ---- src/app/api/checkin/[id]/route.ts (detail + toggle) --------------------

function sessionDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/checkin/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getSession, listCheckins, toggleSession, checkinEnabled } from "@/lib/db/checkin";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!checkinEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const session = await getSession(id);",
    '  if (!session) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Customers may only read their own sessions; admins read any.",
    "  if (!canAccessAdmin(user?.role) && session.ownerId && session.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const checkins = await listCheckins(session.id);",
    "  return NextResponse.json({ ok: true, session, checkins });",
    "}",
    "",
    "// Toggle a session active/ended, ported from toggle_session_active — admins only.",
    "export async function PATCH(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const result = await toggleSession(id);",
    '  if (!result) return NextResponse.json({ ok: false, message: "Connect a database to update sessions." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, isActive: result.isActive });",
    "}"
  ]);
}

// ---- src/app/api/checkin/submit/route.ts (public-style check-in) ------------

function submitApiFile(): GeneratedModuleFile {
  return file("src/app/api/checkin/submit/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { submitCheckin, checkinEnabled } from "@/lib/db/checkin";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Check someone in by code, ported from public_checkin. A signed-in helper enters",
    "// the code + the attendee's details; the lib verifies the code + active state and",
    "// derives first-time vs returning.",
    "export async function POST(request: Request) {",
    '  if (!checkinEnabled()) return NextResponse.json({ ok: false, message: "Check-in is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to check people in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const code = typeof body.code === "string" ? body.code : "";',
    "  const result = await submitCheckin({",
    "    code,",
    '    name: typeof body.name === "string" ? body.name : undefined,',
    '    email: typeof body.email === "string" ? body.email : undefined,',
    '    phone: typeof body.phone === "string" ? body.phone : undefined,',
    '    howHeard: typeof body.howHeard === "string" ? body.howHeard : undefined,',
    "    contactRequested: body.contactRequested === true,",
    '    contactReason: typeof body.contactReason === "string" ? body.contactReason : undefined',
    "  });",
    "  if (!result.ok) {",
    "    return NextResponse.json(result, { status: 400 });",
    "  }",
    "  return NextResponse.json(result);",
    "}"
  ]);
}

// ---- src/app/api/checkin/staffing/route.ts (roles + shifts + schedule) ------

function staffingApiFile(): GeneratedModuleFile {
  return file("src/app/api/checkin/staffing/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import {',
    "  listRoles, createRole, listShifts, createShift, getSchedule, DEFAULT_RATIOS, checkinEnabled",
    '} from "@/lib/db/checkin";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Roles, shifts, and the schedule view — ported from childcare_staffing.py's read",
    "// endpoints (list_roles / list_shifts / get_schedule + DEFAULT_RATIOS).",
    "export async function GET(request: Request) {",
    '  if (!checkinEnabled()) return NextResponse.json({ ok: false, message: "Check-in is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    '  const date = url.searchParams.get("date") || "";',
    "  const roles = await listRoles(ownerId);",
    "  if (date) {",
    "    const schedule = await getSchedule(date, ownerId);",
    "    return NextResponse.json({ ok: true, roles, schedule, ratios: DEFAULT_RATIOS });",
    "  }",
    "  const shifts = await listShifts(ownerId);",
    "  return NextResponse.json({ ok: true, roles, shifts, ratios: DEFAULT_RATIOS });",
    "}",
    "",
    "// Create a staffing role or a shift. Defining roles is an admin control (ported",
    "// from create_role's church-admin gate); creating shifts is open to any signed-in",
    "// owner (ported from create_shift). The body's `kind` selects which.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const kind = typeof body.kind === "string" ? body.kind : "shift";',
    "  const ownerId = user?.id ? String(user.id) : null;",
    "",
    '  if (kind === "role") {',
    "    // Defining staffing roles is admin-only, ported from create_role.",
    '    if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins define staffing roles." }, { status: 403 });',
    '    const name = typeof body.name === "string" ? body.name.trim() : "";',
    '    if (name.length < 2) return NextResponse.json({ ok: false, message: "Name the role." }, { status: 400 });',
    "    const role = await createRole({",
    "      ownerId,",
    "      name,",
    '      description: typeof body.description === "string" ? body.description : undefined,',
    "      requiresBackgroundCheck: body.requiresBackgroundCheck !== false,",
    "      requiresCpr: body.requiresCpr === true,",
    "      requiresChildProtectionTraining: body.requiresChildProtectionTraining !== false,",
    '      minAgeToServe: typeof body.minAgeToServe === "number" ? body.minAgeToServe : undefined',
    "    });",
    '    if (!role) return NextResponse.json({ ok: false, message: "Connect a database to define roles." }, { status: 503 });',
    "    return NextResponse.json({ ok: true, role });",
    "  }",
    "",
    '  const eventDate = typeof body.eventDate === "string" ? body.eventDate.trim() : "";',
    '  const startTime = typeof body.startTime === "string" ? body.startTime.trim() : "";',
    '  const endTime = typeof body.endTime === "string" ? body.endTime.trim() : "";',
    "  if (!eventDate || !startTime || !endTime) {",
    '    return NextResponse.json({ ok: false, message: "A date, start time, and end time are required." }, { status: 400 });',
    "  }",
    "  const shift = await createShift({",
    "    ownerId,",
    "    eventDate,",
    "    startTime,",
    "    endTime,",
    '    roomName: typeof body.roomName === "string" ? body.roomName : undefined,',
    '    roleId: typeof body.roleId === "string" ? body.roleId : null,',
    '    slotsNeeded: typeof body.slotsNeeded === "number" ? body.slotsNeeded : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined',
    "  });",
    '  if (!shift) return NextResponse.json({ ok: false, message: "Connect a database to schedule shifts." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, shift });",
    "}"
  ]);
}

// ---- src/app/api/checkin/staffing/[id]/route.ts (signup + drop) -------------

function staffingSignupApiFile(): GeneratedModuleFile {
  return file("src/app/api/checkin/staffing/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { signupForShift, dropSignup, checkinEnabled } from "@/lib/db/checkin";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Volunteer self-sign-up / drop, ported from signup_for_shift + drop_signup. Any",
    "// signed-in user signs themselves up (or off) — the volunteer scopes to user.id.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!checkinEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "signup";',
    '  if (action === "drop") {',
    "    const dropped = await dropSignup(id, String(user.id));",
    '    if (!dropped) return NextResponse.json({ ok: false, message: "Connect a database to update shifts." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    "  const result = await signupForShift(id, {",
    "    id: String(user.id),",
    '    name: user.name || "",',
    '    email: user.email || "",',
    "    // Clearance is captured at signup; wire a real background-check store to set this.",
    "    cleared: body.cleared === true",
    "  });",
    '  if (!result.ok) return NextResponse.json(result, { status: 400 });',
    "  return NextResponse.json(result);",
    "}"
  ]);
}

// ---- src/app/checkin/page.tsx (sessions dashboard + open a session) ---------

function checkinPageFile(): GeneratedModuleFile {
  return file("src/app/checkin/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listSessions, getAttendanceStats, checkinEnabled } from "@/lib/db/checkin";',
    'import { OpenSessionForm } from "./open-session-form";',
    'import { CheckInPanel } from "./check-in-panel";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CheckinPage() {",
    "  if (!checkinEnabled()) {",
    '    return (<main className="shell"><h1>Check-in</h1><p>Check-in is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/checkin");',
    "  const user = await getCurrentUser();",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    "  const sessions = await listSessions(ownerId);",
    "  const stats = await getAttendanceStats(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Check-in</p>',
    "      <h1>Sessions</h1>",
    "      <p>Open a session for each service or event, then share its code. People check in with the code — you get live attendance and who is here for the first time.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Attendance (30d)</span><strong>{stats.totalAttendance.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Unique visitors</span><strong>{stats.uniqueVisitors.toLocaleString()}</strong></article>',
    '        <article className="card"><span>First-timers</span><strong>{stats.firstTimeVisitors.toLocaleString()} ({stats.firstTimerPercentage}%)</strong></article>',
    '        <article className="card"><span>Avg / session</span><strong>{stats.averagePerSession}</strong></article>',
    "      </section>",
    "      <h2>Check someone in</h2>",
    "      <p>Have a code? Enter it with the attendee&apos;s details to check them in.</p>",
    "      <CheckInPanel />",
    "      <h2>Your sessions</h2>",
    "      {sessions.length === 0 ? (",
    '        <p className="note">No sessions yet. Open your first one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {sessions.map((s) => (",
    '            <Link className="wide-card" key={s.id} href={`/checkin/${s.id}`}>',
    '              <span>{s.isActive ? `Live · ${s.code}` : "Ended"}</span>',
    "              <strong>{s.serviceName}</strong>",
    "              <p>{[s.date, s.startTime].filter(Boolean).join(\" · \")}</p>",
    '              <p className="note">{s.attendanceCount} checked in · {s.firstTimeVisitors} first-time</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Open a session</h2>",
    "      <OpenSessionForm />",
    '      <p><Link className="button" href="/checkin/staffing">Staffing schedule</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/open-session-form.tsx (client) -------------------------

function openSessionFormFile(): GeneratedModuleFile {
  return file("src/app/checkin/open-session-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Open a check-in session, ported from create_checkin_session's fields.",
    "export function OpenSessionForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/checkin", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          serviceName: form.get("serviceName"),',
    '          serviceType: form.get("serviceType"),',
    '          date: form.get("date"),',
    '          startTime: form.get("startTime"),',
    '          speaker: form.get("speaker"),',
    '          sermonTitle: form.get("sermonTitle")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Session open.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Open</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="serviceName" placeholder="Session name (e.g. Sunday Service)" aria-label="Session name" required />',
    '      <select className="input" name="serviceType" aria-label="Type" defaultValue="event">',
    '        <option value="sunday_morning">Sunday morning</option>',
    '        <option value="sunday_evening">Sunday evening</option>',
    '        <option value="wednesday">Wednesday</option>',
    '        <option value="special">Special</option>',
    '        <option value="event">Event</option>',
    "      </select>",
    '      <input className="input" name="date" type="date" aria-label="Date" />',
    '      <input className="input" name="startTime" placeholder="Start time (e.g. 10:00)" aria-label="Start time" />',
    '      <input className="input" name="speaker" placeholder="Speaker (optional)" aria-label="Speaker" />',
    '      <input className="input" name="sermonTitle" placeholder="Message title (optional)" aria-label="Message title" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Opening…" : "Open session"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/check-in-panel.tsx (client) ----------------------------

function checkInPanelFile(): GeneratedModuleFile {
  return file("src/app/checkin/check-in-panel.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Check an attendee in by code, ported from public_checkin: enter the code + the",
    "// person's details, and the server tells us whether they are new or returning.",
    "export function CheckInPanel() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const formEl = event.currentTarget;",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(formEl);",
    "    try {",
    '      const response = await fetch("/api/checkin/submit", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          code: form.get("code"),',
    '          name: form.get("name"),',
    '          email: form.get("email"),',
    '          phone: form.get("phone"),',
    '          howHeard: form.get("howHeard"),',
    '          contactRequested: form.get("contactRequested") === "on"',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not check in. Check the code and try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.welcomeMessage || "Checked in.");',
    "      formEl.reset();",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="code" placeholder="Check-in code" aria-label="Check-in code" required style={{ textTransform: "uppercase" }} />',
    '      <input className="input" name="name" placeholder="Name" aria-label="Attendee name" required />',
    '      <input className="input" name="email" type="email" placeholder="Email (optional)" aria-label="Email" />',
    '      <input className="input" name="phone" placeholder="Phone (optional)" aria-label="Phone" />',
    '      <input className="input" name="howHeard" placeholder="How did you hear about us? (optional)" aria-label="How did you hear about us" />',
    '      <label className="check"><input type="checkbox" name="contactRequested" /> I would like someone to reach out</label>',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Checking in…" : "Check in"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/[id]/page.tsx (session detail + roster + toggle) -------

function sessionDetailPageFile(): GeneratedModuleFile {
  return file("src/app/checkin/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getSession, listCheckins, checkinEnabled } from "@/lib/db/checkin";',
    'import { SessionToggle } from "./session-toggle";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CheckinDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!checkinEnabled()) {",
    '    return (<main className="shell"><h1>Check-in</h1><p>Check-in is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/checkin");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const session = await getSession(id);",
    "  if (!session) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && session.ownerId && session.ownerId !== String(user?.id)) notFound();",
    "  const checkins = await listCheckins(session.id);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{session.isActive ? `Live · code ${session.code}` : "Ended"}</p>',
    "      <h1>{session.serviceName}</h1>",
    '      <p className="note">{[session.date, session.startTime, session.speaker].filter(Boolean).join(" · ")}</p>',
    "      {session.sermonTitle ? <p><strong>{session.sermonTitle}</strong></p> : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Checked in</span><strong>{session.attendanceCount}</strong></article>',
    '        <article className="card"><span>First-time</span><strong>{session.firstTimeVisitors}</strong></article>',
    '        <article className="card"><span>Returning</span><strong>{session.returningVisitors}</strong></article>',
    "      </section>",
    "      {isAdmin ? <SessionToggle id={session.id} isActive={session.isActive} /> : null}",
    "      <h2>Who is here</h2>",
    "      {checkins.length === 0 ? (",
    '        <p className="note">No one has checked in yet. Share the code above.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {checkins.map((c) => (",
    '            <article className="wide-card" key={c.id}>',
    '              <span>{c.isFirstTimeVisitor ? "First-time" : "Returning"}</span>',
    "              <strong>{c.personName}</strong>",
    "              {c.personEmail ? <p>{c.personEmail}</p> : null}",
    '              {c.contactRequested ? <p className="note">Asked to be contacted{c.contactReason ? ` · ${c.contactReason}` : ""}</p> : null}',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/checkin">Back to sessions</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/[id]/session-toggle.tsx (client, admin) ----------------

function sessionToggleFile(): GeneratedModuleFile {
  return file("src/app/checkin/[id]/session-toggle.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Start / end a session, ported from toggle_session_active — admins only.",
    "export function SessionToggle({ id, isActive }: { id: string; isActive: boolean }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function toggle() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/checkin/${id}`, { method: \"PATCH\" });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update the session.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className={isActive ? "button" : "button primary"} type="button" onClick={toggle} disabled={status === "working"}>',
    '        {isActive ? "End session" : "Reopen session"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/staffing/page.tsx (roles, ratios, shifts, schedule) ----

function staffingPageFile(): GeneratedModuleFile {
  return file("src/app/checkin/staffing/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listRoles, listShifts, DEFAULT_RATIOS, checkinEnabled } from "@/lib/db/checkin";',
    'import { StaffingForms } from "./staffing-forms";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function StaffingPage() {",
    "  if (!checkinEnabled()) {",
    '    return (<main className="shell"><h1>Staffing</h1><p>Check-in is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/checkin/staffing");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    "  const roles = await listRoles(ownerId);",
    "  const shifts = await listShifts(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Staffing</p>',
    "      <h1>Kids &amp; event staffing</h1>",
    "      <p>Define the roles people can serve in, post shifts, and let volunteers sign themselves up. The schedule flags any shift that is short-handed or has an uncleared volunteer.</p>",
    "      <h2>Adult-to-child ratios</h2>",
    "      <p>Standard safe ratios per age band — the baseline every room should staff to.</p>",
    '      <section className="panel-list">',
    "        {DEFAULT_RATIOS.map((r) => (",
    '          <article className="wide-card" key={r.ageBand}>',
    "            <span>{r.ratio}</span>",
    "            <strong>{r.ageBand.replace(\"_\", \" \")}</strong>",
    '            <p className="note">{r.notes}</p>',
    "          </article>",
    "        ))}",
    "      </section>",
    "      <h2>Roles</h2>",
    "      {roles.length === 0 ? (",
    '        <p className="note">No roles defined yet.{isAdmin ? " Add one below." : ""}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {roles.map((role) => (",
    '            <article className="wide-card" key={role.id}>',
    "              <strong>{role.name}</strong>",
    "              {role.description ? <p>{role.description}</p> : null}",
    '              <p className="note">{[',
    '                role.requiresBackgroundCheck ? "Background check" : "",',
    '                role.requiresCpr ? "CPR" : "",',
    '                role.requiresChildProtectionTraining ? "Child protection training" : "",',
    '                `Min age ${role.minAgeToServe}`',
    '              ].filter(Boolean).join(" · ")}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Upcoming shifts</h2>",
    "      {shifts.length === 0 ? (",
    '        <p className="note">No shifts posted yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {shifts.map((shift) => (",
    '            <article className="wide-card" key={shift.id}>',
    '              <span>{[shift.eventDate, `${shift.startTime}–${shift.endTime}`].filter(Boolean).join(" · ")}</span>',
    '              <strong>{shift.roomName || "Shift"}</strong>',
    '              <p className="note">Needs {shift.slotsNeeded}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <StaffingForms isAdmin={isAdmin} roles={roles.map((r) => ({ id: r.id, name: r.name }))} />",
    '      <p><Link className="button" href="/checkin">Back to sessions</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/checkin/staffing/staffing-forms.tsx (client) -------------------

function staffingFormsFile(): GeneratedModuleFile {
  return file("src/app/checkin/staffing/staffing-forms.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Post a shift (any owner) and — for admins — define a staffing role. Ported from",
    "// childcare_staffing.py create_shift + create_role.",
    "export function StaffingForms({ isAdmin, roles }: { isAdmin: boolean; roles: Array<{ id: string; name: string }> }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function post(url: string, payload: Record<string, unknown>) {",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(url, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(payload)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  async function submitShift(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = new FormData(event.currentTarget);",
    '    await post("/api/checkin/staffing", {',
    '      kind: "shift",',
    '      eventDate: form.get("eventDate"),',
    '      startTime: form.get("startTime"),',
    '      endTime: form.get("endTime"),',
    '      roomName: form.get("roomName"),',
    '      roleId: form.get("roleId") || null,',
    '      slotsNeeded: Number(form.get("slotsNeeded") || 1)',
    "    });",
    "  }",
    "",
    "  async function submitRole(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = new FormData(event.currentTarget);",
    '    await post("/api/checkin/staffing", {',
    '      kind: "role",',
    '      name: form.get("name"),',
    '      description: form.get("description"),',
    '      requiresBackgroundCheck: form.get("requiresBackgroundCheck") === "on",',
    '      requiresCpr: form.get("requiresCpr") === "on",',
    '      requiresChildProtectionTraining: form.get("requiresChildProtectionTraining") === "on",',
    '      minAgeToServe: Number(form.get("minAgeToServe") || 18)',
    "    });",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      <h2>Post a shift</h2>",
    '      <form className="stack" onSubmit={submitShift}>',
    '        <input className="input" name="eventDate" type="date" aria-label="Shift date" required />',
    '        <input className="input" name="startTime" placeholder="Start (e.g. 09:00)" aria-label="Start time" required />',
    '        <input className="input" name="endTime" placeholder="End (e.g. 10:30)" aria-label="End time" required />',
    '        <input className="input" name="roomName" placeholder="Room (e.g. Infant Room)" aria-label="Room" />',
    "        <select className=\"input\" name=\"roleId\" aria-label=\"Role\" defaultValue=\"\">",
    '          <option value="">Any role</option>',
    "          {roles.map((r) => (",
    "            <option key={r.id} value={r.id}>{r.name}</option>",
    "          ))}",
    "        </select>",
    '        <input className="input" name="slotsNeeded" type="number" min={1} defaultValue={1} aria-label="Slots needed" />',
    '        <button className="button primary" type="submit" disabled={status === "saving"}>Post shift</button>',
    "      </form>",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Define a role</h2>",
    '          <form className="stack" onSubmit={submitRole}>',
    '            <input className="input" name="name" placeholder="Role name (e.g. Nursery Lead)" aria-label="Role name" required />',
    '            <input className="input" name="description" placeholder="What this role does (optional)" aria-label="Role description" />',
    '            <label className="check"><input type="checkbox" name="requiresBackgroundCheck" defaultChecked /> Requires background check</label>',
    '            <label className="check"><input type="checkbox" name="requiresCpr" /> Requires CPR</label>',
    '            <label className="check"><input type="checkbox" name="requiresChildProtectionTraining" defaultChecked /> Requires child protection training</label>',
    '            <input className="input" name="minAgeToServe" type="number" min={0} defaultValue={18} aria-label="Minimum age to serve" />',
    '            <button className="button" type="submit" disabled={status === "saving"}>Add role</button>',
    "          </form>",
    "        </>",
    "      ) : null}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const checkinModule: AppModule = {
  slug: "checkin",
  name: "Check-in & Staffing",
  tier: "optional",
  featureFlagEnv: "FEATURE_CHECKIN",
  files: () => [
    checkinLibFile(),
    sessionsApiFile(),
    sessionDetailApiFile(),
    submitApiFile(),
    staffingApiFile(),
    staffingSignupApiFile(),
    checkinPageFile(),
    openSessionFormFile(),
    checkInPanelFile(),
    sessionDetailPageFile(),
    sessionToggleFile(),
    staffingPageFile(),
    staffingFormsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists checkin_sessions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  code text not null unique,",
      "  service_name text not null default 'Service',",
      "  service_type text not null default 'event',",
      "  date text not null default '',",
      "  start_time text not null default '',",
      "  speaker text not null default '',",
      "  sermon_title text not null default '',",
      "  is_active boolean not null default true,",
      "  attendance_count integer not null default 0,",
      "  first_time_visitors integer not null default 0,",
      "  returning_visitors integer not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists checkin_sessions_owner_idx on checkin_sessions (owner_id);",
      "create index if not exists checkin_sessions_code_idx on checkin_sessions (code);",
      "create index if not exists checkin_sessions_created_idx on checkin_sessions (created_at desc);",
      "",
      "create table if not exists checkin_records (",
      "  id uuid primary key default gen_random_uuid(),",
      "  session_id uuid not null references checkin_sessions(id) on delete cascade,",
      "  owner_id uuid references users(id) on delete set null,",
      "  person_name text not null default 'Anonymous',",
      "  person_email text not null default '',",
      "  person_phone text not null default '',",
      "  is_first_time_visitor boolean not null default true,",
      "  how_heard text not null default '',",
      "  contact_requested boolean not null default false,",
      "  contact_reason text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists checkin_records_session_idx on checkin_records (session_id);",
      "create index if not exists checkin_records_owner_email_idx on checkin_records (owner_id, person_email);",
      "create index if not exists checkin_records_created_idx on checkin_records (created_at desc);",
      "",
      "create table if not exists checkin_staff_roles (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  name text not null,",
      "  description text not null default '',",
      "  requires_background_check boolean not null default true,",
      "  requires_cpr boolean not null default false,",
      "  requires_child_protection_training boolean not null default true,",
      "  min_age_to_serve integer not null default 18,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists checkin_staff_roles_owner_idx on checkin_staff_roles (owner_id);",
      "",
      "create table if not exists checkin_shifts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  event_date text not null,",
      "  start_time text not null default '',",
      "  end_time text not null default '',",
      "  room_name text not null default '',",
      "  role_id uuid references checkin_staff_roles(id) on delete set null,",
      "  slots_needed integer not null default 1,",
      "  notes text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists checkin_shifts_owner_date_idx on checkin_shifts (owner_id, event_date);",
      "",
      "create table if not exists checkin_shift_signups (",
      "  id uuid primary key default gen_random_uuid(),",
      "  shift_id uuid not null references checkin_shifts(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  name text not null default '',",
      "  email text not null default '',",
      "  is_cleared_at_signup boolean not null default false,",
      "  signed_up_at timestamptz not null default now(),",
      "  unique (shift_id, user_id)",
      ");",
      "create index if not exists checkin_shift_signups_shift_idx on checkin_shift_signups (shift_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into checkin_sessions (code, service_name, service_type, date, start_time, speaker, sermon_title, is_active, attendance_count, first_time_visitors, returning_visitors) values",
      "  ('SUN123', 'Sunday Service', 'sunday_morning', '2025-01-05', '10:00', 'Pastor Lee', 'A place to belong', true, 42, 6, 36)",
      "on conflict (code) do nothing;",
      "",
      "insert into checkin_staff_roles (name, description, requires_background_check, requires_cpr, requires_child_protection_training, min_age_to_serve) values",
      "  ('Nursery Lead', 'Leads the infant room and coordinates helpers.', true, true, true, 18),",
      "  ('Toddler Helper', 'Supports the toddler room.', true, false, true, 16)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Check-in & Staffing — set to false to switch sessions, check-in, and staffing off.",
    "FEATURE_CHECKIN=true"
  ],
  homeLinks: () => ['        <a className="button" href="/checkin">Check-in</a>'],
  navLinks: () => [
    { href: "/checkin", label: "Check-in" },
    { href: "/checkin/staffing", label: "Staffing" }
  ]
};