// communication — messaging pipes: broadcasts + a queued notification pipeline
// (email/SMS to targeted recipients), ported from ChurchConnect's real
// Communication Command Center: src/components/BroadcastHub.tsx (the
// broadcast/newsletter tabs + History), backend/routes/broadcasting.py
// (event_broadcasts create/list/publish + notification_queue send-email/send-sms),
// backend/routes/email_service.py (send_email_smtp + /api/email/send-bulk +
// /api/email/process-queue + email_log) and backend/routes/church_sms.py
// (per-owner phone send + message_balance + sms_logs).
//
// We keep the actual model — a broadcast with title/date/time/location/
// description, a target audience, a status lifecycle (draft -> scheduled), and
// per-channel reach stats; plus a notification queue row (channel email|sms, a
// recipient, subject/body or message, status queued|sent|failed). Publishing a
// broadcast fans it out into queued notifications, exactly as
// publish_broadcast() does. The email/SMS providers are abstracted behind the
// app owner's own env keys (SMTP_* / SMS_*); when they are absent, sends are
// queued and clearly reported as "not configured yet" — never a provider name
// shown to end users. Runs on the app owner's own database with graceful
// sample-data fallback, feature-flagged (FEATURE_COMMS), customers browse,
// admins compose and publish.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/communication.ts (model + queries, ported from broadcasting.py
//      + email_service.py + church_sms.py) -------------------------------------

function communicationLibFile(): GeneratedModuleFile {
  return file("src/lib/db/communication.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// Ported from broadcasting.py event_broadcasts + BroadcastHub tabs. A broadcast",
    "// is an announcement about an event, sent across one or more channels.",
    'export type BroadcastStatus = "draft" | "scheduled";',
    'export type BroadcastChannel = "email" | "sms";',
    "",
    "export type BroadcastStats = {",
    "  emailSent: number;",
    "  smsSent: number;",
    "  totalReach: number;",
    "};",
    "",
    "export type Broadcast = {",
    "  id: string;",
    "  title: string;",
    "  eventDate: string;",
    "  eventTime: string;",
    "  location: string;",
    "  body: string;",
    "  targetAudience: string;",
    "  channels: BroadcastChannel[];",
    "  status: BroadcastStatus;",
    "  stats: BroadcastStats;",
    "  createdAt: string;",
    "  publishedAt: string | null;",
    "};",
    "",
    "// Ported from broadcasting.py notification_queue + email_service.py/church_sms.py:",
    "// one recipient-targeted message, queued then sent (or failed) via the owner's",
    "// own email/SMS provider.",
    'export type NotificationChannel = "email" | "sms";',
    'export type NotificationStatus = "queued" | "sent" | "failed";',
    "",
    "export type Notification = {",
    "  id: string;",
    "  broadcastId: string | null;",
    "  channel: NotificationChannel;",
    "  toEmail: string;",
    "  toPhone: string;",
    "  toName: string;",
    "  subject: string;",
    "  message: string;",
    "  status: NotificationStatus;",
    "  error: string;",
    "  createdAt: string;",
    "  sentAt: string | null;",
    "};",
    "",
    "export type BroadcastFilters = { q?: string; status?: string; limit?: number };",
    "",
    "// Provider readiness, abstracted behind the owner's own env keys. We never name",
    "// the provider to end users — we only report whether a channel can deliver.",
    "// Ported from email_service._smtp_from_env() + church_sms.get_twilio_client().",
    "export function emailConfigured(): boolean {",
    "  return Boolean(",
    "    (process.env.SMTP_HOST && process.env.SMTP_USERNAME && process.env.SMTP_PASSWORD) ||",
    "      process.env.EMAIL_API_KEY",
    "  );",
    "}",
    "",
    "export function smsConfigured(): boolean {",
    "  return Boolean(process.env.SMS_ACCOUNT_SID && process.env.SMS_AUTH_TOKEN);",
    "}",
    "",
    "export function channelConfigured(channel: NotificationChannel): boolean {",
    '  return channel === "email" ? emailConfigured() : smsConfigured();',
    "}",
    "",
    "const fallbackBroadcasts: Broadcast[] = [",
    "  {",
    '    id: "sample-1",',
    '    title: "Volunteer kickoff night",',
    '    eventDate: "2026-08-01",',
    '    eventTime: "6:30 PM",',
    '    location: "Main hall",',
    '    body: "Come meet the team and pick where you want to serve. Food provided.",',
    '    targetAudience: "All members",',
    '    channels: ["email", "sms"],',
    '    status: "scheduled",',
    '    stats: { emailSent: 48, smsSent: 22, totalReach: 70 },',
    '    createdAt: "2026-07-10T12:00:00.000Z",',
    '    publishedAt: "2026-07-11T09:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-2",',
    '    title: "Summer newsletter draft",',
    '    eventDate: "",',
    '    eventTime: "",',
    '    location: "",',
    '    body: "Highlights from the last month, ready to review before we send.",',
    '    targetAudience: "Newsletter list",',
    '    channels: ["email"],',
    '    status: "draft",',
    '    stats: { emailSent: 0, smsSent: 0, totalReach: 0 },',
    '    createdAt: "2026-07-14T15:00:00.000Z",',
    "    publishedAt: null",
    "  }",
    "];",
    "",
    "function parseChannels(value: unknown): BroadcastChannel[] {",
    "  let raw: unknown = value;",
    '  if (typeof value === "string") {',
    "    try {",
    "      raw = JSON.parse(value);",
    "    } catch {",
    "      raw = [];",
    "    }",
    "  }",
    "  if (!Array.isArray(raw)) return [];",
    '  return raw.filter((c): c is BroadcastChannel => c === "email" || c === "sms");',
    "}",
    "",
    "function rowToBroadcast(row: Record<string, unknown>): Broadcast {",
    "  return {",
    "    id: String(row.id),",
    '    title: String(row.title || ""),',
    '    eventDate: row.event_date ? String(row.event_date) : "",',
    '    eventTime: String(row.event_time || ""),',
    '    location: String(row.location || ""),',
    '    body: String(row.body || ""),',
    '    targetAudience: String(row.target_audience || "All members"),',
    "    channels: parseChannels(row.channels),",
    '    status: (row.status === "scheduled" ? "scheduled" : "draft"),',
    "    stats: {",
    "      emailSent: Number(row.email_sent || 0),",
    "      smsSent: Number(row.sms_sent || 0),",
    "      totalReach: Number(row.total_reach || 0)",
    "    },",
    "    createdAt: String(row.created_at || \"\"),",
    "    publishedAt: row.published_at ? String(row.published_at) : null",
    "  };",
    "}",
    "",
    "function rowToNotification(row: Record<string, unknown>): Notification {",
    "  return {",
    "    id: String(row.id),",
    "    broadcastId: row.broadcast_id ? String(row.broadcast_id) : null,",
    '    channel: (row.channel === "sms" ? "sms" : "email"),',
    '    toEmail: String(row.to_email || ""),',
    '    toPhone: String(row.to_phone || ""),',
    '    toName: String(row.to_name || ""),',
    '    subject: String(row.subject || ""),',
    '    message: String(row.message || ""),',
    '    status: (row.status === "sent" ? "sent" : row.status === "failed" ? "failed" : "queued"),',
    '    error: String(row.error || ""),',
    "    createdAt: String(row.created_at || \"\"),",
    "    sentAt: row.sent_at ? String(row.sent_at) : null",
    "  };",
    "}",
    "",
    "// List + search, ported from GET /api/broadcasts/{church_id} (newest first) with",
    "// the History drawer's optional status filter and a simple title/body search.",
    "export async function listBroadcasts(filters: BroadcastFilters = {}): Promise<Broadcast[]> {",
    "  const limit = Math.min(100, Math.max(1, filters.limit || 50));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const status = (filters.status || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackBroadcasts",
    "      .filter((b) => !q || (b.title + \" \" + b.body).toLowerCase().includes(q))",
    "      .filter((b) => !status || b.status === status)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    '    const statusFilter = status === "draft" || status === "scheduled" ? status : null;',
    "    const rows = (await sql`",
    "      select id, title, event_date, event_time, location, body, target_audience,",
    "        channels, status, email_sent, sms_sent, total_reach, created_at, published_at",
    "      from comms_broadcasts",
    "      where (${like}::text is null",
    "        or lower(title) like ${like}",
    "        or lower(body) like ${like})",
    "        and (${statusFilter}::text is null or status = ${statusFilter})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `) as Record<string, unknown>[];",
    "    return rows.map(rowToBroadcast);",
    "  } catch {",
    "    return fallbackBroadcasts.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getBroadcast(id: string): Promise<Broadcast | null> {",
    "  if (!hasDatabase()) return fallbackBroadcasts.find((b) => b.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`",
    "      select id, title, event_date, event_time, location, body, target_audience,",
    "        channels, status, email_sent, sms_sent, total_reach, created_at, published_at",
    "      from comms_broadcasts where id = ${id} limit 1`) as Record<string, unknown>[];",
    "    return rows[0] ? rowToBroadcast(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Recipients queued for a broadcast, ported from the notification_queue rows",
    "// created in publish_broadcast() + the /api/email/log + sms_logs views.",
    "export async function listNotifications(broadcastId: string): Promise<Notification[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = (await sql`",
    "      select id, broadcast_id, channel, to_email, to_phone, to_name, subject,",
    "        message, status, error, created_at, sent_at",
    "      from comms_notifications where broadcast_id = ${broadcastId}",
    "      order by created_at desc limit 500`) as Record<string, unknown>[];",
    "    return rows.map(rowToNotification);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type CreateBroadcastInput = {",
    "  title: string;",
    "  eventDate?: string;",
    "  eventTime?: string;",
    "  location?: string;",
    "  body?: string;",
    "  targetAudience?: string;",
    "  channels?: BroadcastChannel[];",
    "  createdBy?: string;",
    "};",
    "",
    "// Ported from POST /api/broadcasts/create — always starts life as a draft.",
    "export async function createBroadcast(input: CreateBroadcastInput): Promise<Broadcast | null> {",
    "  if (!hasDatabase()) return null;",
    "  const sql = getDatabase();",
    '  const channels = (input.channels && input.channels.length ? input.channels : ["email"]).filter(',
    '    (c) => c === "email" || c === "sms"',
    "  );",
    "  const rows = (await sql`",
    "    insert into comms_broadcasts",
    "      (title, event_date, event_time, location, body, target_audience, channels, status, created_by)",
    "    values (",
    '      ${input.title}, ${input.eventDate || null}, ${input.eventTime || ""},',
    '      ${input.location || ""}, ${input.body || ""}, ${input.targetAudience || "All members"},',
    '      ${JSON.stringify(channels)}, ${"draft"}, ${input.createdBy || null}',
    "    )",
    "    returning id, title, event_date, event_time, location, body, target_audience,",
    "      channels, status, email_sent, sms_sent, total_reach, created_at, published_at",
    "  `) as Record<string, unknown>[];",
    "  return rows[0] ? rowToBroadcast(rows[0]) : null;",
    "}",
    "",
    "// Recipient list resolution is app-specific; the source pulled it from the",
    "// people directory. We accept an explicit recipient list so the module stays",
    "// self-contained, defaulting to none when the app has not wired an audience yet.",
    "export type Recipient = { name?: string; email?: string; phone?: string };",
    "",
    "export type PublishResult = {",
    "  ok: boolean;",
    "  status: BroadcastStatus;",
    "  queued: number;",
    "  emailConfigured: boolean;",
    "  smsConfigured: boolean;",
    "  message: string;",
    "};",
    "",
    "// Ported from POST /api/broadcasts/{id}/publish: flip draft -> scheduled, then",
    "// fan the broadcast out into one queued notification per recipient per channel",
    "// (the touchpoint loop in publish_broadcast). Sends stay 'queued' until the",
    "// owner's provider actually delivers them (process-queue), so this is safe with",
    "// no keys configured — it just reports the channel as not ready.",
    "export async function publishBroadcast(",
    "  id: string,",
    "  recipients: Recipient[] = []",
    "): Promise<PublishResult> {",
    "  const email = emailConfigured();",
    "  const sms = smsConfigured();",
    "  if (!hasDatabase()) {",
    '    return { ok: false, status: "draft", queued: 0, emailConfigured: email, smsConfigured: sms, message: "Connect a database to publish broadcasts." };',
    "  }",
    "  const sql = getDatabase();",
    "  const broadcast = await getBroadcast(id);",
    "  if (!broadcast) {",
    '    return { ok: false, status: "draft", queued: 0, emailConfigured: email, smsConfigured: sms, message: "Broadcast not found." };',
    "  }",
    "",
    "  let queued = 0;",
    "  let emailQueued = 0;",
    "  let smsQueued = 0;",
    "  for (const recipient of recipients) {",
    "    for (const channel of broadcast.channels) {",
    '      if (channel === "email") {',
    "        const to = (recipient.email || \"\").trim();",
    "        if (!to) continue;",
    "        await sql`",
    "          insert into comms_notifications",
    "            (broadcast_id, channel, to_email, to_name, subject, message, status)",
    '          values (${id}, ${"email"}, ${to}, ${recipient.name || ""}, ${broadcast.title}, ${broadcast.body}, ${"queued"})',
    "        `;",
    "        emailQueued += 1;",
    "        queued += 1;",
    "      } else {",
    "        const to = (recipient.phone || \"\").trim();",
    "        if (!to) continue;",
    "        await sql`",
    "          insert into comms_notifications",
    "            (broadcast_id, channel, to_phone, to_name, message, status)",
    '          values (${id}, ${"sms"}, ${to}, ${recipient.name || ""}, ${broadcast.title + ": " + broadcast.body}, ${"queued"})',
    "        `;",
    "        smsQueued += 1;",
    "        queued += 1;",
    "      }",
    "    }",
    "  }",
    "",
    "  await sql`",
    "    update comms_broadcasts",
    '    set status = ${"scheduled"}, published_at = now(),',
    "      email_sent = email_sent + ${emailQueued},",
    "      sms_sent = sms_sent + ${smsQueued},",
    "      total_reach = total_reach + ${queued}",
    "    where id = ${id}",
    "  `;",
    "",
    "  const notReady: string[] = [];",
    '  if (emailQueued > 0 && !email) notReady.push("email");',
    '  if (smsQueued > 0 && !sms) notReady.push("text messages");',
    "  const message =",
    "    notReady.length > 0",
    '      ? `Scheduled. ${queued} message(s) queued — add ${notReady.join(" and ")} delivery keys to send them.`',
    "      : queued > 0",
    "      ? `Scheduled. ${queued} message(s) queued for delivery.`",
    '      : "Scheduled. Add recipients to reach people.";',
    '  return { ok: true, status: "scheduled", queued, emailConfigured: email, smsConfigured: sms, message };',
    "}",
    "",
    "export function commsEnabled(): boolean {",
    '  return process.env.FEATURE_COMMS !== "false";',
    "}"
  ]);
}

// ---- src/app/api/comms/route.ts (list + create) -----------------------------

function commsApiFile(): GeneratedModuleFile {
  return file("src/app/api/comms/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listBroadcasts, createBroadcast, commsEnabled } from "@/lib/db/communication";',
    'import type { BroadcastChannel } from "@/lib/db/communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!commsEnabled()) return NextResponse.json({ ok: false, message: "Communication is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const broadcasts = await listBroadcasts({",
    '    q: url.searchParams.get("q") || undefined,',
    '    status: url.searchParams.get("status") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, broadcasts });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  if (!commsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 1) {",
    '    return NextResponse.json({ ok: false, message: "A title is required." }, { status: 400 });',
    "  }",
    "  const channelsRaw = Array.isArray(body.channels) ? body.channels : [];",
    "  const channels = channelsRaw.filter(",
    '    (c): c is BroadcastChannel => c === "email" || c === "sms"',
    "  );",
    "  const created = await createBroadcast({",
    "    title,",
    '    eventDate: typeof body.eventDate === "string" ? body.eventDate : undefined,',
    '    eventTime: typeof body.eventTime === "string" ? body.eventTime : undefined,',
    '    location: typeof body.location === "string" ? body.location : undefined,',
    '    body: typeof body.body === "string" ? body.body : undefined,',
    '    targetAudience: typeof body.targetAudience === "string" ? body.targetAudience : undefined,',
    "    channels,",
    "    createdBy: user.email || undefined",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save broadcasts." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, broadcast: created });",
    "}"
  ]);
}

// ---- src/app/api/comms/[id]/route.ts (detail + publish) ---------------------

function commsDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/comms/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getBroadcast, listNotifications, publishBroadcast, commsEnabled } from "@/lib/db/communication";',
    'import type { Recipient } from "@/lib/db/communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  if (!commsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const broadcast = await getBroadcast(id);",
    '  if (!broadcast) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const recipients = await listNotifications(id);",
    "  return NextResponse.json({ ok: true, broadcast, recipients });",
    "}",
    "",
    "// Publish a broadcast: draft -> scheduled and fan out queued notifications.",
    "// Ported from POST /api/broadcasts/{id}/publish.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  if (!commsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const recipients = Array.isArray(body.recipients)",
    "    ? (body.recipients as unknown[])",
    '        .filter((r): r is Record<string, unknown> => typeof r === "object" && r !== null)',
    "        .map((r) => ({",
    '          name: typeof r.name === "string" ? r.name : undefined,',
    '          email: typeof r.email === "string" ? r.email : undefined,',
    '          phone: typeof r.phone === "string" ? r.phone : undefined',
    "        }) as Recipient)",
    "    : [];",
    "  const result = await publishBroadcast(id, recipients);",
    "  return NextResponse.json(result, { status: result.ok ? 200 : 400 });",
    "}"
  ]);
}

// ---- src/app/comms/page.tsx (list + search + compose) -----------------------

function commsPageFile(): GeneratedModuleFile {
  return file("src/app/comms/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listBroadcasts, emailConfigured, smsConfigured, commsEnabled } from "@/lib/db/communication";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CommsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; status?: string }>;",
    "}) {",
    "  if (!commsEnabled()) {",
    '    return (<main className="shell"><h1>Communication</h1><p>Communication is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/comms");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const status = (params?.status || "").trim();',
    "  const broadcasts = await listBroadcasts({ q: q || undefined, status: status || undefined });",
    "  const emailReady = emailConfigured();",
    "  const smsReady = smsConfigured();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Communication</p>',
    "      <h1>Broadcasts</h1>",
    "      <p>Announce events and send them to your people by email and text.</p>",
    "",
    "      {(!emailReady || !smsReady) ? (",
    '        <p className="note">',
    "          {!emailReady && !smsReady",
    '            ? "No delivery keys set yet — you can draft and schedule now; add email or text keys to actually send."',
    "            : !emailReady",
    '            ? "Text sending is ready. Add email keys to send by email too."',
    '            : "Email sending is ready. Add text keys to send by text too."}',
    "        </p>",
    "      ) : null}",
    "",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search broadcasts" aria-label="Search broadcasts" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "",
    "      {broadcasts.length === 0 ? (",
    '        <p className="note">{q ? `No broadcasts match "${q}" yet.` : "No broadcasts yet."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {broadcasts.map((b) => (",
    '            <Link className="wide-card" key={b.id} href={`/comms/${b.id}`}>',
    '              <span>{b.status === "scheduled" ? "Scheduled" : "Draft"}</span>',
    "              <strong>{b.title}</strong>",
    "              <p>",
    "                {[",
    '                  b.eventDate ? `${b.eventDate}${b.eventTime ? " · " + b.eventTime : ""}` : "",',
    "                  b.location,",
    '                  b.status === "scheduled" ? `${b.stats.totalReach} reached` : b.targetAudience',
    '                ].filter(Boolean).join(" · ")}',
    "              </p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      {isAdmin ? (",
    '        <section className="panel">',
    "          <h2>New broadcast</h2>",
    '          <form className="stack" method="post" action="/comms/new">',
    '            <label htmlFor="title">Title</label>',
    '            <input className="input" id="title" name="title" required placeholder="What is happening?" />',
    '            <label htmlFor="eventDate">Date</label>',
    '            <input className="input" id="eventDate" name="eventDate" type="date" />',
    '            <label htmlFor="eventTime">Time</label>',
    '            <input className="input" id="eventTime" name="eventTime" placeholder="6:30 PM" />',
    '            <label htmlFor="location">Location</label>',
    '            <input className="input" id="location" name="location" placeholder="Where?" />',
    '            <label htmlFor="body">Message</label>',
    '            <textarea className="input" id="body" name="body" rows={4} placeholder="What do you want people to know?" />',
    '            <label htmlFor="targetAudience">Audience</label>',
    '            <input className="input" id="targetAudience" name="targetAudience" placeholder="All members" />',
    '            <fieldset>',
    '              <legend>Send by</legend>',
    '              <label><input type="checkbox" name="channels" value="email" defaultChecked /> Email</label>',
    '              <label><input type="checkbox" name="channels" value="sms" /> Text message</label>',
    "            </fieldset>",
    '            <button className="button primary" type="submit">Save draft</button>',
    "          </form>",
    "        </section>",
    "      ) : null}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/comms/new/route.ts (form POST -> create) -----------------------

function commsNewFormFile(): GeneratedModuleFile {
  return file("src/app/comms/new/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { createBroadcast, commsEnabled } from "@/lib/db/communication";',
    'import type { BroadcastChannel } from "@/lib/db/communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Progressive-enhancement handler for the compose form on /comms.",
    "export async function POST(request: Request) {",
    "  if (!commsEnabled()) return NextResponse.redirect(new URL(\"/comms\", request.url));",
    "  const user = await getCurrentUser();",
    "  if (!user || !canAccessAdmin(user.role)) {",
    '    return NextResponse.redirect(new URL("/comms", request.url));',
    "  }",
    "  const form = await request.formData().catch(() => null);",
    '  const title = form ? String(form.get("title") || "").trim() : "";',
    "  if (!title) {",
    '    return NextResponse.redirect(new URL("/comms", request.url));',
    "  }",
    '  const channels = form ? (form.getAll("channels").map(String).filter(',
    '    (c): c is BroadcastChannel => c === "email" || c === "sms"',
    "  )) : [];",
    "  const created = await createBroadcast({",
    "    title,",
    '    eventDate: form ? String(form.get("eventDate") || "") || undefined : undefined,',
    '    eventTime: form ? String(form.get("eventTime") || "") || undefined : undefined,',
    '    location: form ? String(form.get("location") || "") || undefined : undefined,',
    '    body: form ? String(form.get("body") || "") || undefined : undefined,',
    '    targetAudience: form ? String(form.get("targetAudience") || "") || undefined : undefined,',
    "    channels,",
    "    createdBy: user.email || undefined",
    "  });",
    '  const dest = created ? `/comms/${created.id}` : "/comms";',
    "  return NextResponse.redirect(new URL(dest, request.url));",
    "}"
  ]);
}

// ---- src/app/comms/[id]/page.tsx (detail + publish) -------------------------

function commsDetailPageFile(): GeneratedModuleFile {
  return file("src/app/comms/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getBroadcast, listNotifications, emailConfigured, smsConfigured, commsEnabled } from "@/lib/db/communication";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function BroadcastDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!commsEnabled()) {",
    '    return (<main className="shell"><h1>Communication</h1><p>Communication is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/comms");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const { id } = await params;",
    "  const broadcast = await getBroadcast(id);",
    "  if (!broadcast) notFound();",
    "  const recipients = await listNotifications(id);",
    "  const emailReady = emailConfigured();",
    "  const smsReady = smsConfigured();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Communication</p>',
    "      <h1>{broadcast.title}</h1>",
    '      <p className="note">{broadcast.status === "scheduled" ? "Scheduled" : "Draft"} · {broadcast.targetAudience}</p>',
    "",
    '      <section className="grid">',
    '        {broadcast.eventDate ? (<article className="card"><span>Date</span><strong>{broadcast.eventDate}{broadcast.eventTime ? " · " + broadcast.eventTime : ""}</strong></article>) : null}',
    '        {broadcast.location ? (<article className="card"><span>Location</span><strong>{broadcast.location}</strong></article>) : null}',
    '        <article className="card"><span>Channels</span><strong>{broadcast.channels.map((c) => (c === "sms" ? "Text" : "Email")).join(", ") || "None"}</strong></article>',
    "      </section>",
    "",
    "      {broadcast.body ? <p>{broadcast.body}</p> : null}",
    "",
    '      {broadcast.status === "scheduled" ? (',
    '        <section className="grid">',
    '          <article className="card"><span>Email sent</span><strong>{broadcast.stats.emailSent}</strong></article>',
    '          <article className="card"><span>Texts sent</span><strong>{broadcast.stats.smsSent}</strong></article>',
    '          <article className="card"><span>Total reach</span><strong>{broadcast.stats.totalReach}</strong></article>',
    "        </section>",
    "      ) : null}",
    "",
    "      {isAdmin && broadcast.status === \"draft\" ? (",
    '        <section className="panel">',
    "          <h2>Publish</h2>",
    "          {(!emailReady && broadcast.channels.includes(\"email\")) || (!smsReady && broadcast.channels.includes(\"sms\")) ? (",
    '            <p className="note">Publishing will schedule this and queue messages. Add delivery keys to actually send them.</p>',
    "          ) : (",
    '            <p className="note">Publishing will schedule this broadcast and queue it for delivery.</p>',
    "          )}",
    '          <form className="stack" method="post" action={`/comms/${broadcast.id}/publish`}>',
    '            <button className="button primary" type="submit">Schedule broadcast</button>',
    "          </form>",
    "        </section>",
    "      ) : null}",
    "",
    "      {isAdmin && recipients.length > 0 ? (",
    '        <section className="panel">',
    "          <h2>Recipients</h2>",
    '          <ul className="plain-list">',
    "            {recipients.map((r) => (",
    "              <li key={r.id}>",
    '                {(r.channel === "sms" ? r.toPhone : r.toEmail) || r.toName || "Recipient"} · {r.status}',
    "              </li>",
    "            ))}",
    "          </ul>",
    "        </section>",
    "      ) : null}",
    "",
    '      <p><Link className="button" href="/comms">Back to broadcasts</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/comms/[id]/publish/route.ts (form POST -> publish) -------------

function commsPublishFormFile(): GeneratedModuleFile {
  return file("src/app/comms/[id]/publish/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { publishBroadcast, commsEnabled } from "@/lib/db/communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Progressive-enhancement handler for the Publish button on /comms/[id].",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const { id } = await params;",
    "  if (!commsEnabled()) return NextResponse.redirect(new URL(\"/comms\", request.url));",
    "  const user = await getCurrentUser();",
    "  if (!user || !canAccessAdmin(user.role)) {",
    "    return NextResponse.redirect(new URL(`/comms/${id}`, request.url));",
    "  }",
    "  await publishBroadcast(id, []);",
    "  return NextResponse.redirect(new URL(`/comms/${id}`, request.url));",
    "}"
  ]);
}

export const communicationModule: AppModule = {
  slug: "communication",
  name: "Communication",
  tier: "optional",
  featureFlagEnv: "FEATURE_COMMS",
  files: () => [
    communicationLibFile(),
    commsApiFile(),
    commsDetailApiFile(),
    commsPageFile(),
    commsNewFormFile(),
    commsDetailPageFile(),
    commsPublishFormFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists comms_broadcasts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  title text not null default '',",
      "  event_date date,",
      "  event_time text not null default '',",
      "  location text not null default '',",
      "  body text not null default '',",
      "  target_audience text not null default 'All members',",
      "  channels jsonb not null default '[]'::jsonb,",
      "  status text not null default 'draft',",
      "  email_sent integer not null default 0,",
      "  sms_sent integer not null default 0,",
      "  total_reach integer not null default 0,",
      "  created_by uuid references users(id),",
      "  created_at timestamptz not null default now(),",
      "  published_at timestamptz",
      ");",
      "create index if not exists comms_broadcasts_status_idx on comms_broadcasts (status, created_at desc);",
      "",
      "create table if not exists comms_notifications (",
      "  id uuid primary key default gen_random_uuid(),",
      "  broadcast_id uuid references comms_broadcasts(id) on delete cascade,",
      "  channel text not null default 'email',",
      "  to_email text not null default '',",
      "  to_phone text not null default '',",
      "  to_name text not null default '',",
      "  subject text not null default '',",
      "  message text not null default '',",
      "  status text not null default 'queued',",
      "  error text not null default '',",
      "  created_at timestamptz not null default now(),",
      "  sent_at timestamptz",
      ");",
      "create index if not exists comms_notifications_broadcast_idx on comms_notifications (broadcast_id, created_at desc);",
      "create index if not exists comms_notifications_status_idx on comms_notifications (status);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into comms_broadcasts (title, event_date, event_time, location, body, target_audience, channels, status, email_sent, sms_sent, total_reach, published_at) values",
      "  ('Volunteer kickoff night', '2026-08-01', '6:30 PM', 'Main hall', 'Come meet the team and pick where you want to serve. Food provided.', 'All members', '[\"email\",\"sms\"]'::jsonb, 'scheduled', 48, 22, 70, now())",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Communication — set to false to switch broadcasts + notifications off.",
    "FEATURE_COMMS=true",
    "# Email delivery (owner's own SMTP account). Leave blank to queue-only.",
    "SMTP_HOST=",
    "SMTP_PORT=587",
    "SMTP_USERNAME=",
    "SMTP_PASSWORD=",
    "SMTP_FROM_EMAIL=",
    "# Text/SMS delivery (owner's own account). Leave blank to queue-only.",
    "SMS_ACCOUNT_SID=",
    "SMS_AUTH_TOKEN=",
    "SMS_FROM_NUMBER="
  ],
  homeLinks: () => ['        <a className="button" href="/comms">Communication</a>'],
  navLinks: () => [{ href: "/comms", label: "Communication" }]
};
