// connection-engine — assess a person's relational posture + mindset/heartset,
// then match them with others and gather them into small groups (pods) before
// pairs. Ported from Kindred-Connection's real code:
//   - backend/routers/relational_posture.py — the 6 Likert questions (with their
//     axes + low/high labels), VALID_POSTURES, _heuristic_posture scoring, and the
//     _fallback_reading narratives (anchored / tender / guarded / whirling).
//   - backend/core.py compatibility_score — base 30, shared values x12, shared
//     growth goals x10, shared interests x4, clamped to 35..99.
//   - backend/routers/soul_match.py get_or_make_soul_match — score every other
//     person, sort desc, pick the highest-scoring one you are NOT already matched
//     with, produce a "why we picked them" line.
//   - backend/routers/pods.py — Growth Pods: create/list/discover/join, capped at
//     6 members ("groups/pods before pairs").
// Generalized off Kindred's Christian framing into plain, warm copy so it drops
// into any app. Runs on the app owner's own database with graceful sample-data
// fallback, feature-flagged (FEATURE_CONNECTION); customers assess/match/join,
// admins manage.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/connection.ts (model + queries, ported from the Python) ------

function connectionLibFile(): GeneratedModuleFile {
  return file("src/lib/db/connection.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The four relational postures, ported from relational_posture.py VALID_POSTURES.",
    "// Pastoral words, not clinical labels:",
    "//   anchored ~ secure       — at home with closeness AND with space",
    "//   tender   ~ anxious      — reaches hard, fears being too much / not enough",
    "//   guarded  ~ avoidant     — pulls back when things get close, prizes self-reliance",
    "//   whirling ~ disorganized — pull AND push, longs for closeness AND fears it",
    'export type Posture = "anchored" | "tender" | "guarded" | "whirling";',
    'export const POSTURES: Posture[] = ["anchored", "tender", "guarded", "whirling"];',
    "",
    "export type PostureQuestion = {",
    "  key: string;",
    "  prompt: string;",
    "  lowLabel: string;",
    "  highLabel: string;",
    "  axis: string;",
    "};",
    "",
    "// The 6 questions, ported verbatim from relational_posture.py QUESTIONS.",
    "// Each maps to a Likert 1..5 scale; answers feed the heuristic below.",
    "export const POSTURE_QUESTIONS: PostureQuestion[] = [",
    "  {",
    '    key: "closeness_comfort",',
    '    prompt: "When someone I care about wants to grow closer, my first feeling is more often…",',
    '    lowLabel: "I tense up — closeness feels risky",',
    '    highLabel: "I lean in — closeness feels good",',
    '    axis: "guarded_to_anchored"',
    "  },",
    "  {",
    '    key: "space_comfort",',
    '    prompt: "When someone I care about needs space, my first feeling is more often…",',
    '    lowLabel: "Something is wrong — I start watching for danger",',
    '    highLabel: "That\'s healthy — I trust we\'re still okay",',
    '    axis: "tender_to_anchored"',
    "  },",
    "  {",
    '    key: "ask_for_help",',
    '    prompt: "When I\'m hurting, asking someone close for help feels…",',
    '    lowLabel: "Hard — I\'d rather handle it alone",',
    '    highLabel: "Natural — that\'s what people are for",',
    '    axis: "guarded_to_anchored"',
    "  },",
    "  {",
    '    key: "conflict_response",',
    '    prompt: "In a hard conversation with someone I love, I\'m more likely to…",',
    '    lowLabel: "Get loud or chase the conversation until it\'s settled",',
    '    highLabel: "Go quiet or step away to cool down",',
    '    axis: "tender_to_guarded"',
    "  },",
    "  {",
    '    key: "trust_baseline",',
    '    prompt: "When someone new shows me kindness, my heart\'s first reaction is…",',
    '    lowLabel: "Wait — what do they want?",',
    '    highLabel: "I receive it — and trust it",',
    '    axis: "whirling_to_anchored"',
    "  },",
    "  {",
    '    key: "self_worth_in_love",',
    '    prompt: "When I imagine being deeply known by someone, the loudest voice in me says…",',
    '    lowLabel: "If they really saw me, they\'d leave",',
    '    highLabel: "Being known is what I was made for",',
    '    axis: "whirling_to_anchored"',
    "  }",
    "];",
    "",
    "export type PostureReading = {",
    "  summary: string;",
    "  growingToward: string;",
    "  healingInvitation: string;",
    "};",
    "",
    "// Lightweight first-pass posture estimate from the Likert answers, ported from",
    "// relational_posture.py _heuristic_posture. Missing answers default to 3 (neutral).",
    "export function heuristicPosture(answers: Record<string, number>): Posture {",
    "  const cc = answers.closeness_comfort ?? 3;",
    "  const sc = answers.space_comfort ?? 3;",
    "  const ah = answers.ask_for_help ?? 3;",
    "  const cr = answers.conflict_response ?? 3;",
    "  const tb = answers.trust_baseline ?? 3;",
    "  const sw = answers.self_worth_in_love ?? 3;",
    "  const spread = Math.max(cc, sc, ah, tb, sw) - Math.min(cc, sc, ah, tb, sw);",
    "  const scores: Record<Posture, number> = {",
    "    anchored: cc + sc + ah + tb + sw,",
    "    tender: (6 - sc) + (6 - cr) + (6 - sw),",
    "    guarded: (6 - cc) + (6 - ah) + cr,",
    "    whirling: (6 - tb) + (6 - sw) + spread",
    "  };",
    '  let best: Posture = "anchored";',
    "  for (const p of POSTURES) if (scores[p] > scores[best]) best = p;",
    "  return best;",
    "}",
    "",
    "// The reading narratives, ported from relational_posture.py _fallback_reading",
    "// (generalized off the Christian framing into plain, warm copy).",
    "const READINGS: Record<Posture, PostureReading> = {",
    "  anchored: {",
    '    summary: "You rest in a quiet trust — at home with closeness and at home with space. That doesn\'t mean you\'ve never been hurt; it means safe people have had room to do their slow work in you.",',
    '    growingToward: "Keep anchoring others — your steadiness is a gift to people who haven\'t found theirs yet.",',
    '    healingInvitation: "This week, look for one person who feels alone and bring them a small, undramatic kindness. Your steadiness is contagious."',
    "  },",
    "  tender: {",
    '    summary: "When you care about someone, you start watching for the small signs that they\'re pulling away — and you sometimes reach in ways that, paradoxically, push them back. That posture was forged in a season when you weren\'t sure your presence was wanted.",',
    '    growingToward: "Anchored — at home in both closeness and space, trusting that you are wanted even in silence.",',
    '    healingInvitation: "When the watchful feeling rises this week, name it to yourself, breathe once, and ask: is this them, or is this an old story? Sit with the answer before you act."',
    "  },",
    "  guarded: {",
    '    summary: "You\'ve learned that the safest place is the one you control alone. That instinct made sense once — it kept something tender in you safe when no one else would. But the walls that protected the child can keep the adult lonely.",',
    '    growingToward: "Anchored — letting one or two safe people past the wall, slowly, and learning that closeness can be safe.",',
    '    healingInvitation: "This week, when the urge to pull back rises with someone safe, try staying one beat longer. One honest sentence. One unhurried minute. See what happens."',
    "  },",
    "  whirling: {",
    '    summary: "You long for closeness AND fear it at the same time. You reach, then pull back. You trust, then question. That\'s not weakness — it\'s a heart that learned the people closest to it were also the ones who hurt it most.",',
    '    growingToward: "Anchored — slowly, one small experiment at a time, learning that some love is safe, and that you are not too much.",',
    '    healingInvitation: "Find one person this week who has been steadily, undramatically kind to you. Send a short message — no big confession, just contact. Notice what rises. That\'s the work."',
    "  }",
    "};",
    "",
    "export function readingFor(posture: Posture): PostureReading {",
    "  return READINGS[posture] || READINGS.tender;",
    "}",
    "",
    "export type ConnectionProfile = {",
    "  id: string;",
    "  userId: string | null;",
    "  name: string;",
    "  purpose: string;",
    "  posture: Posture | null;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  interests: string[];",
    "};",
    "",
    "export type MatchResult = { profile: ConnectionProfile; score: number; why: string };",
    "",
    "// Split a comma/newline list into a clean array.",
    "export function parseList(value: unknown): string[] {",
    '  if (Array.isArray(value)) return value.map((v) => String(v).trim()).filter(Boolean);',
    '  if (typeof value !== "string") return [];',
    "  return value",
    "    .split(/[,\\n;]+/)",
    "    .map((v) => v.trim())",
    "    .filter(Boolean);",
    "}",
    "",
    "// Compatibility score, ported from core.py compatibility_score:",
    "// base 30, shared core values x12, shared growth goals x10, shared interests x4,",
    "// clamped to 35..99. Case-insensitive set overlap.",
    "export function compatibilityScore(me: ConnectionProfile, other: ConnectionProfile): number {",
    "  const lower = (xs: string[]) => new Set(xs.map((x) => x.toLowerCase()));",
    "  const overlap = (a: Set<string>, b: Set<string>) => {",
    "    let n = 0;",
    "    a.forEach((x) => { if (b.has(x)) n += 1; });",
    "    return n;",
    "  };",
    "  let score = 30;",
    "  score += overlap(lower(me.coreValues), lower(other.coreValues)) * 12;",
    "  score += overlap(lower(me.growthGoals), lower(other.growthGoals)) * 10;",
    "  score += overlap(lower(me.interests), lower(other.interests)) * 4;",
    "  return Math.min(99, Math.max(35, score));",
    "}",
    "",
    "// A short, honest 'why we picked them', ported in spirit from soul_match.py's",
    "// fallback 'why' — names the shared ground rather than inventing facts.",
    "export function matchWhy(me: ConnectionProfile, other: ConnectionProfile): string {",
    "  const lower = (xs: string[]) => new Set(xs.map((x) => x.toLowerCase()));",
    "  const shared = (a: string[], b: string[]) => {",
    "    const bs = lower(b);",
    "    return a.filter((x) => bs.has(x.toLowerCase()));",
    "  };",
    "  const values = shared(me.coreValues, other.coreValues);",
    "  const goals = shared(me.growthGoals, other.growthGoals);",
    "  const bits: string[] = [];",
    '  if (values.length) bits.push(`you both hold ${values.slice(0, 3).join(", ")} close`);',
    '  if (goals.length) bits.push(`you\'re both working toward ${goals.slice(0, 2).join(" and ")}`);',
    "  if (me.posture && other.posture) {",
    "    bits.push(",
    "      me.posture === other.posture",
    '        ? `you share a ${me.posture} posture — the same invitation to grow`',
    '        : `your ${me.posture} and their ${other.posture} postures could steady each other`',
    "    );",
    "  }",
    "  if (!bits.length) {",
    '    return `You and ${other.name} share a rare kind of resonance — shaped by purpose, not appearance. Worth a conversation.`;',
    "  }",
    '  return `We paired you with ${other.name} because ${bits.join("; ")}.`;',
    "}",
    "",
    "const fallbackProfiles: ConnectionProfile[] = [",
    '  { id: "sample-1", userId: null, name: "Sam Rivera", purpose: "Help people find their footing again", posture: "anchored", coreValues: ["honesty", "growth", "faith"], growthGoals: ["listen better", "serve locally"], interests: ["hiking", "reading"] },',
    '  { id: "sample-2", userId: null, name: "Jordan Lee", purpose: "Build things that outlast me", posture: "tender", coreValues: ["growth", "creativity"], growthGoals: ["listen better"], interests: ["music", "hiking"] },',
    '  { id: "sample-3", userId: null, name: "Alex Okafor", purpose: "Walk with people through hard seasons", posture: "guarded", coreValues: ["faith", "loyalty"], growthGoals: ["open up more"], interests: ["reading"] }',
    "];",
    "",
    "function rowToProfile(row: Record<string, unknown>): ConnectionProfile {",
    "  const toArr = (v: unknown): string[] => {",
    "    if (Array.isArray(v)) return v.map((x) => String(x));",
    '    if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "    return [];",
    "  };",
    '  const posture = String(row.posture || "");',
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    name: String(row.name || "Unnamed"),',
    '    purpose: String(row.purpose || ""),',
    "    posture: (POSTURES as string[]).includes(posture) ? (posture as Posture) : null,",
    "    coreValues: toArr(row.core_values),",
    "    growthGoals: toArr(row.growth_goals),",
    "    interests: toArr(row.interests)",
    "  };",
    "}",
    "",
    "export async function getMyProfile(userId: string): Promise<ConnectionProfile | null> {",
    "  if (!hasDatabase()) return fallbackProfiles[0];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where user_id = ${userId} limit 1`;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function getProfile(id: string): Promise<ConnectionProfile | null> {",
    "  if (!hasDatabase()) return fallbackProfiles.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where id = ${id} limit 1`;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SaveProfileInput = {",
    "  userId: string;",
    "  name: string;",
    "  purpose?: string;",
    "  posture?: Posture | null;",
    "  coreValues?: string[];",
    "  growthGoals?: string[];",
    "  interests?: string[];",
    "};",
    "",
    "// Upsert the current user's profile (one profile per user).",
    "export async function saveMyProfile(input: SaveProfileInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const values = JSON.stringify(input.coreValues || []);",
    "  const goals = JSON.stringify(input.growthGoals || []);",
    "  const interests = JSON.stringify(input.interests || []);",
    "  const posture = input.posture || null;",
    "  const existing = await sql`select id from connection_profiles where user_id = ${input.userId} limit 1`;",
    "  if (existing[0]) {",
    '    await sql`update connection_profiles set name = ${input.name}, purpose = ${input.purpose || ""}, posture = ${posture}, core_values = ${values}, growth_goals = ${goals}, interests = ${interests}, updated_at = now() where user_id = ${input.userId}`;',
    "    return true;",
    "  }",
    '  await sql`insert into connection_profiles (user_id, name, purpose, posture, core_values, growth_goals, interests) values (${input.userId}, ${input.name}, ${input.purpose || ""}, ${posture}, ${values}, ${goals}, ${interests})`;',
    "  return true;",
    "}",
    "",
    "// Store the posture from an assessment onto the user's profile (creates a stub",
    "// profile if none exists yet).",
    "export async function saveMyPosture(userId: string, name: string, posture: Posture): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const existing = await sql`select id from connection_profiles where user_id = ${userId} limit 1`;",
    "  if (existing[0]) {",
    "    await sql`update connection_profiles set posture = ${posture}, updated_at = now() where user_id = ${userId}`;",
    "  } else {",
    "    await sql`insert into connection_profiles (user_id, name, posture) values (${userId}, ${name}, ${posture})`;",
    "  }",
    "  return true;",
    "}",
    "",
    "// Matching, ported from soul_match.py get_or_make_soul_match: score every other",
    "// profile, sort highest-first, skip anyone the receiver has no profile for. Groups",
    "// before pairs is enforced in the UX (pods first); this returns ranked candidates.",
    "export async function findMatches(userId: string, limit = 10): Promise<MatchResult[]> {",
    "  if (!hasDatabase()) {",
    "    const me = fallbackProfiles[0];",
    "    return fallbackProfiles",
    "      .filter((p) => p.id !== me.id)",
    "      .map((p) => ({ profile: p, score: compatibilityScore(me, p), why: matchWhy(me, p) }))",
    "      .sort((a, b) => b.score - a.score)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const me = await getMyProfile(userId);",
    "    if (!me) return [];",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where user_id is null or user_id <> ${userId} limit 500`;",
    "    return rows",
    "      .map(rowToProfile)",
    "      .map((p) => ({ profile: p, score: compatibilityScore(me, p), why: matchWhy(me, p) }))",
    "      .sort((a, b) => b.score - a.score)",
    "      .slice(0, limit);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// ---- Growth Pods (groups before pairs), ported from pods.py -----------------",
    "",
    "export const POD_MAX_MEMBERS = 6; // pods.py caps membership at 6",
    "",
    "export type Pod = {",
    "  id: string;",
    "  name: string;",
    "  description: string;",
    "  createdBy: string | null;",
    "  memberCount: number;",
    "  isMember: boolean;",
    "};",
    "",
    "const fallbackPods: Pod[] = [",
    '  { id: "pod-sample-1", name: "Monday Growth Circle", description: "A small group learning to show up for each other one week at a time.", createdBy: null, memberCount: 3, isMember: false },',
    '  { id: "pod-sample-2", name: "Companion Circle", description: "Three people finding their footing together. Small on purpose.", createdBy: null, memberCount: 2, isMember: false }',
    "];",
    "",
    "function rowToPod(row: Record<string, unknown>, userId: string): Pod {",
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || "Pod"),',
    '    description: String(row.description || ""),',
    "    createdBy: row.created_by != null ? String(row.created_by) : null,",
    "    memberCount: Number(row.member_count || 0),",
    '    isMember: row.is_member === true || String(row.is_member) === "true" || Number(row.is_member) > 0 || String(row.created_by) === userId',
    "  };",
    "}",
    "",
    "// List the pods the current user belongs to, ported from pods.py list_my_pods.",
    "export async function listMyPods(userId: string): Promise<Pod[]> {",
    "  if (!hasDatabase()) return fallbackPods.filter((p) => p.isMember);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select p.id, p.name, p.description, p.created_by,",
    "        (select count(*) from connection_pod_members m where m.pod_id = p.id) as member_count,",
    "        true as is_member",
    "      from connection_pods p",
    "      join connection_pod_members me on me.pod_id = p.id and me.user_id = ${userId}",
    "      order by p.created_at desc limit 100`;",
    "    return rows.map((r) => rowToPod(r, userId));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Discover joinable pods with room, ported from pods.py discover_pods:",
    "// pods you are NOT in that have fewer than POD_MAX_MEMBERS members.",
    "export async function discoverPods(userId: string): Promise<Pod[]> {",
    "  if (!hasDatabase()) return fallbackPods.filter((p) => !p.isMember);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select p.id, p.name, p.description, p.created_by,",
    "        (select count(*) from connection_pod_members m where m.pod_id = p.id) as member_count,",
    "        false as is_member",
    "      from connection_pods p",
    "      where not exists (select 1 from connection_pod_members me where me.pod_id = p.id and me.user_id = ${userId})",
    "        and (select count(*) from connection_pod_members m where m.pod_id = p.id) < ${POD_MAX_MEMBERS}",
    "      order by p.created_at desc limit 50`;",
    "    return rows.map((r) => rowToPod(r, userId));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Create a pod and make the creator its first member, ported from pods.py create_pod.",
    "export async function createPod(userId: string, name: string, description: string): Promise<Pod | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`insert into connection_pods (name, description, created_by) values (${name}, ${description}, ${userId}) returning id, name, description, created_by`;",
    "    const pod = rows[0];",
    "    if (!pod) return null;",
    "    await sql`insert into connection_pod_members (pod_id, user_id) values (${pod.id}, ${userId}) on conflict do nothing`;",
    '    return { id: String(pod.id), name: String(pod.name), description: String(pod.description || ""), createdBy: userId, memberCount: 1, isMember: true };',
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Join a pod if it has room, ported from pods.py join_pod (409-style guard at cap).",
    "export async function joinPod(userId: string, podId: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to join pods." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const exists = await sql`select id from connection_pods where id = ${podId} limit 1`;",
    '    if (!exists[0]) return { ok: false, message: "That pod no longer exists." };',
    "    const already = await sql`select 1 from connection_pod_members where pod_id = ${podId} and user_id = ${userId} limit 1`;",
    "    if (already[0]) return { ok: true };",
    "    const countRows = await sql`select count(*) as c from connection_pod_members where pod_id = ${podId}`;",
    '    if (Number(countRows[0]?.c || 0) >= POD_MAX_MEMBERS) return { ok: false, message: "This pod is full." };',
    "    await sql`insert into connection_pod_members (pod_id, user_id) values (${podId}, ${userId}) on conflict do nothing`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not join right now." };',
    "  }",
    "}",
    "",
    "export function connectionEnabled(): boolean {",
    '  return process.env.FEATURE_CONNECTION !== "false";',
    "}"
  ]);
}

// ---- src/app/api/connection/assessment/route.ts -----------------------------

function assessmentApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/assessment/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { POSTURE_QUESTIONS, heuristicPosture, readingFor, saveMyPosture, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  return NextResponse.json({ ok: true, questions: POSTURE_QUESTIONS });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const rawAnswers = (body.answers && typeof body.answers === "object") ? (body.answers as Record<string, unknown>) : {};',
    "  const answers: Record<string, number> = {};",
    "  for (const q of POSTURE_QUESTIONS) {",
    "    const v = Number(rawAnswers[q.key]);",
    "    if (Number.isInteger(v) && v >= 1 && v <= 5) answers[q.key] = v;",
    "  }",
    "  // Ported from relational_posture.py _validate_answers: at least 4 of 6.",
    "  if (Object.keys(answers).length < 4) {",
    '    return NextResponse.json({ ok: false, message: "Please answer at least 4 of the 6 questions." }, { status: 400 });',
    "  }",
    "  const posture = heuristicPosture(answers);",
    "  const reading = readingFor(posture);",
    '  const name = user?.name || user?.email || "Friend";',
    '  const saved = await saveMyPosture(String(user?.email || ""), name, posture);',
    "  return NextResponse.json({ ok: true, posture, reading, saved });",
    "}"
  ]);
}

// ---- src/app/api/connection/matches/route.ts --------------------------------

function matchesApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/matches/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { findMatches, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const matches = await findMatches(String(user?.email || ""));',
    "  return NextResponse.json({ ok: true, matches });",
    "}"
  ]);
}

// ---- src/app/api/connection/pods/route.ts -----------------------------------

function podsApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/pods/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listMyPods, discoverPods, createPod, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const userId = String(user?.email || "");',
    "  const [mine, discover] = await Promise.all([listMyPods(userId), discoverPods(userId)]);",
    "  return NextResponse.json({ ok: true, mine, discover });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    "  // Creating pods is an admin action (seeding the groups people join).",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    '  const description = typeof body.description === "string" ? body.description.trim() : "";',
    '  if (name.length < 2) return NextResponse.json({ ok: false, message: "A pod name is required." }, { status: 400 });',
    '  const pod = await createPod(String(user.email || ""), name, description);',
    '  if (!pod) return NextResponse.json({ ok: false, message: "Connect a database to create pods." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, pod });",
    "}"
  ]);
}

// ---- src/app/api/connection/pods/[id]/join/route.ts -------------------------

function podJoinApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/pods/[id]/join/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { joinPod, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    '  const result = await joinPod(String(user?.email || ""), id);',
    '  if (!result.ok) return NextResponse.json({ ok: false, message: result.message || "Could not join." }, { status: 409 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/connection/page.tsx (assessment + posture reading) -------------

function connectionPageFile(): GeneratedModuleFile {
  return file("src/app/connection/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { POSTURE_QUESTIONS, getMyProfile, readingFor, connectionEnabled } from "@/lib/db/connection";',
    'import { PostureAssessment } from "./assessment-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ConnectionPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection");',
    "  const user = await getCurrentUser();",
    "  const profile = user?.email ? await getMyProfile(String(user.email)) : null;",
    "  const reading = profile?.posture ? readingFor(profile.posture) : null;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>Find your people</h1>",
    "      <p>Start with a short check-in on how you show up in relationships. Then we help you join a small group — and, when you’re ready, meet one person at a time.</p>",
    "      {reading ? (",
    '        <section className="grid">',
    '          <article className="card"><span>Your posture</span><strong>{profile?.posture}</strong></article>',
    "        </section>",
    "      ) : null}",
    "      {reading ? (",
    '        <section className="panel">',
    "          <p>{reading.summary}</p>",
    "          <p><strong>Growing toward:</strong> {reading.growingToward}</p>",
    "          <p><strong>Try this week:</strong> {reading.healingInvitation}</p>",
    "        </section>",
    "      ) : (",
    '        <p className="note">You haven’t taken the check-in yet. It takes about a minute.</p>',
    "      )}",
    "      <PostureAssessment questions={POSTURE_QUESTIONS} />",
    '      <p className="stack">',
    '        <Link className="button primary" href="/connection/pods">Browse groups</Link>',
    '        <Link className="button" href="/connection/matches">See suggested people</Link>',
    "      </p>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/assessment-form.tsx (client) ------------------------

function assessmentFormFile(): GeneratedModuleFile {
  return file("src/app/connection/assessment-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "type Question = { key: string; prompt: string; lowLabel: string; highLabel: string; axis: string };",
    "type Reading = { summary: string; growingToward: string; healingInvitation: string };",
    "",
    "export function PostureAssessment({ questions }: { questions: Question[] }) {",
    "  const [answers, setAnswers] = useState<Record<string, number>>({});",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "  const [result, setResult] = useState<{ posture: string; reading: Reading } | null>(null);",
    "",
    "  async function submit(event: React.FormEvent) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/connection/assessment", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ answers })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    "      setResult({ posture: data.posture, reading: data.reading });",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  if (result) {",
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Your posture</p>',
    "        <h2>{result.posture}</h2>",
    "        <p>{result.reading.summary}</p>",
    "        <p><strong>Growing toward:</strong> {result.reading.growingToward}</p>",
    "        <p><strong>Try this week:</strong> {result.reading.healingInvitation}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    "      <h2>Relationship check-in</h2>",
    "      {questions.map((q) => (",
    '        <fieldset className="panel" key={q.key}>',
    "          <legend>{q.prompt}</legend>",
    '          <div className="scale" role="radiogroup" aria-label={q.prompt}>',
    "            {[1, 2, 3, 4, 5].map((n) => (",
    '              <label key={n} className="scale-option">',
    '                <input type="radio" name={q.key} value={n} checked={answers[q.key] === n} onChange={() => setAnswers((prev) => ({ ...prev, [q.key]: n }))} />',
    "                <span>{n}</span>",
    "              </label>",
    "            ))}",
    "          </div>",
    '          <p className="note">{q.lowLabel} &middot; {q.highLabel}</p>',
    "        </fieldset>",
    "      ))}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "See my posture"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/matches/page.tsx ------------------------------------

function matchesPageFile(): GeneratedModuleFile {
  return file("src/app/connection/matches/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { findMatches, getMyProfile, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MatchesPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection/matches");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.email ? String(user.email) : "";',
    "  const profile = userId ? await getMyProfile(userId) : null;",
    "  const matches = userId ? await findMatches(userId) : [];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>Suggested people</h1>",
    "      <p>We start you in a group first. When you’re ready for one-on-one, these are the people who share the most with you.</p>",
    "      {!profile ? (",
    '        <p className="note">Take the <Link href="/connection">relationship check-in</Link> first so we can match you well.</p>',
    "      ) : matches.length === 0 ? (",
    '        <p className="note">No one to suggest yet. Check back as more people join.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {matches.map((m) => (",
    '            <article className="wide-card" key={m.profile.id}>',
    "              <span>{m.score}% match</span>",
    "              <strong>{m.profile.name}</strong>",
    "              {m.profile.purpose ? <p>{m.profile.purpose}</p> : null}",
    '              <p className="note">{m.why}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/connection">Back to connection</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/pods/page.tsx (groups before pairs) -----------------

function podsPageFile(): GeneratedModuleFile {
  return file("src/app/connection/pods/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listMyPods, discoverPods, connectionEnabled, POD_MAX_MEMBERS } from "@/lib/db/connection";',
    'import { JoinPodButton } from "./join-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function PodsPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection/pods");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.email ? String(user.email) : "";',
    "  const [mine, discover] = userId ? await Promise.all([listMyPods(userId), discoverPods(userId)]) : [[], []];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>Groups</h1>",
    "      <p>Small groups come first here — up to {POD_MAX_MEMBERS} people. It’s easier to be known by a few than to meet a crowd.</p>",
    "",
    "      <h2>Your groups</h2>",
    "      {mine.length === 0 ? (",
    '        <p className="note">You haven’t joined a group yet. Find one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {mine.map((pod) => (",
    '            <article className="wide-card" key={pod.id}>',
    "              <span>{pod.memberCount} / {POD_MAX_MEMBERS} members</span>",
    "              <strong>{pod.name}</strong>",
    "              {pod.description ? <p>{pod.description}</p> : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Groups with room</h2>",
    "      {discover.length === 0 ? (",
    '        <p className="note">No open groups right now. Check back soon.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {discover.map((pod) => (",
    '            <article className="wide-card" key={pod.id}>',
    "              <span>{pod.memberCount} / {POD_MAX_MEMBERS} members</span>",
    "              <strong>{pod.name}</strong>",
    "              {pod.description ? <p>{pod.description}</p> : null}",
    "              <JoinPodButton podId={pod.id} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/connection">Back to connection</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/pods/join-button.tsx (client) -----------------------

function joinButtonFile(): GeneratedModuleFile {
  return file("src/app/connection/pods/join-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function JoinPodButton({ podId }: { podId: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "joining" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function join() {",
    '    setStatus("joining");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/connection/pods/${podId}/join`, { method: "POST" });',
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not join this group.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    "    <span>",
    '      <button className="button primary" type="button" onClick={join} disabled={status === "joining"}>',
    '        {status === "joining" ? "Joining…" : "Join this group"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert"> {message}</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

export const connectionEngineModule: AppModule = {
  slug: "connection-engine",
  name: "Connection Engine",
  tier: "optional",
  featureFlagEnv: "FEATURE_CONNECTION",
  files: () => [
    connectionLibFile(),
    assessmentApiFile(),
    matchesApiFile(),
    podsApiFile(),
    podJoinApiFile(),
    connectionPageFile(),
    assessmentFormFile(),
    matchesPageFile(),
    podsPageFile(),
    joinButtonFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists connection_profiles (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete cascade,",
      "  name text not null default '',",
      "  purpose text not null default '',",
      "  posture text,",
      "  core_values jsonb not null default '[]'::jsonb,",
      "  growth_goals jsonb not null default '[]'::jsonb,",
      "  interests jsonb not null default '[]'::jsonb,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists connection_profiles_user_idx on connection_profiles (user_id);",
      "",
      "create table if not exists connection_pods (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null,",
      "  description text not null default '',",
      "  created_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now()",
      ");",
      "",
      "create table if not exists connection_pod_members (",
      "  pod_id uuid not null references connection_pods(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  joined_at timestamptz not null default now(),",
      "  primary key (pod_id, user_id)",
      ");",
      "create index if not exists connection_pod_members_user_idx on connection_pod_members (user_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into connection_pods (name, description) values",
      "  ('Monday Growth Circle', 'A small group learning to show up for each other one week at a time.'),",
      "  ('Companion Circle', 'A few people finding their footing together. Small on purpose.')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Connection Engine — set to false to switch assessment + matching + groups off.",
    "FEATURE_CONNECTION=true"
  ],
  homeLinks: () => ['        <a className="button" href="/connection">Connection</a>'],
  navLinks: () => [{ href: "/connection", label: "Connection" }]
};
