// connection-engine — purpose-first belonging: match people who are becoming
// someone and building something together, not merely people who feel alone.
// Doctrine (Life Produces Life + Kindred "become first, meet second"):
//   1. Shared purpose and growth goals lead matching (hobbies are secondary).
//   2. Groups/pods before pairs — small circles oriented around a purpose.
//   3. Loneliness is welcomed, but healing routes through purpose, service, and
//      mutual growth — not by pairing lonely people with each other as the fix.
// Ported from Kindred-Connection's real code, then purpose-weighted:
//   - backend/routers/relational_posture.py — 6 Likert questions, postures,
//     heuristic scoring, healing-invitation readings.
//   - backend/core.py compatibility_score — extended: purpose tokens primary,
//     growth goals next, values, then interests last (was values/goals/interests only).
//   - backend/routers/soul_match.py — ranked candidates + plain "why" explanations.
//   - backend/routers/pods.py — Growth Pods capped at 6, now with a purpose field.
// Generalized off Kindred's Christian framing into plain, warm copy so it drops
// into friendship (Kindred), dating (Aligned Souls), and community (milstead.us)
// apps. Feature-flagged (FEATURE_CONNECTION); customers assess/match/join,
// admins manage.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/connection.ts (model + queries, ported from the Python) ------

function connectionLibFile(): GeneratedModuleFile {
  return file("src/lib/db/connection.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The four relational postures, ported from relational_posture.py VALID_POSTURES.",
    "// Pastoral words, not clinical labels:",
    "//   anchored ~ secure       — at home with closeness AND with space",
    "//   tender   ~ anxious      — reaches hard, fears being too much / not enough",
    "//   guarded  ~ avoidant     — pulls back when things get close, prizes self-reliance",
    "//   whirling ~ disorganized — pull AND push, longs for closeness AND fears it",
    'export type Posture = "anchored" | "tender" | "guarded" | "whirling";',
    'export const POSTURES: Posture[] = ["anchored", "tender", "guarded", "whirling"];',
    "",
    "export type PostureQuestion = {",
    "  key: string;",
    "  prompt: string;",
    "  lowLabel: string;",
    "  highLabel: string;",
    "  axis: string;",
    "};",
    "",
    "// The 6 questions, ported verbatim from relational_posture.py QUESTIONS.",
    "// Each maps to a Likert 1..5 scale; answers feed the heuristic below.",
    "export const POSTURE_QUESTIONS: PostureQuestion[] = [",
    "  {",
    '    key: "closeness_comfort",',
    '    prompt: "When someone I care about wants to grow closer, my first feeling is more often…",',
    '    lowLabel: "I tense up — closeness feels risky",',
    '    highLabel: "I lean in — closeness feels good",',
    '    axis: "guarded_to_anchored"',
    "  },",
    "  {",
    '    key: "space_comfort",',
    '    prompt: "When someone I care about needs space, my first feeling is more often…",',
    '    lowLabel: "Something is wrong — I start watching for danger",',
    '    highLabel: "That\'s healthy — I trust we\'re still okay",',
    '    axis: "tender_to_anchored"',
    "  },",
    "  {",
    '    key: "ask_for_help",',
    '    prompt: "When I\'m hurting, asking someone close for help feels…",',
    '    lowLabel: "Hard — I\'d rather handle it alone",',
    '    highLabel: "Natural — that\'s what people are for",',
    '    axis: "guarded_to_anchored"',
    "  },",
    "  {",
    '    key: "conflict_response",',
    '    prompt: "In a hard conversation with someone I love, I\'m more likely to…",',
    '    lowLabel: "Get loud or chase the conversation until it\'s settled",',
    '    highLabel: "Go quiet or step away to cool down",',
    '    axis: "tender_to_guarded"',
    "  },",
    "  {",
    '    key: "trust_baseline",',
    '    prompt: "When someone new shows me kindness, my heart\'s first reaction is…",',
    '    lowLabel: "Wait — what do they want?",',
    '    highLabel: "I receive it — and trust it",',
    '    axis: "whirling_to_anchored"',
    "  },",
    "  {",
    '    key: "self_worth_in_love",',
    '    prompt: "When I imagine being deeply known by someone, the loudest voice in me says…",',
    '    lowLabel: "If they really saw me, they\'d leave",',
    '    highLabel: "Being known is what I was made for",',
    '    axis: "whirling_to_anchored"',
    "  }",
    "];",
    "",
    "export type PostureReading = {",
    "  summary: string;",
    "  growingToward: string;",
    "  healingInvitation: string;",
    "};",
    "",
    "// Lightweight first-pass posture estimate from the Likert answers, ported from",
    "// relational_posture.py _heuristic_posture. Missing answers default to 3 (neutral).",
    "export function heuristicPosture(answers: Record<string, number>): Posture {",
    "  const cc = answers.closeness_comfort ?? 3;",
    "  const sc = answers.space_comfort ?? 3;",
    "  const ah = answers.ask_for_help ?? 3;",
    "  const cr = answers.conflict_response ?? 3;",
    "  const tb = answers.trust_baseline ?? 3;",
    "  const sw = answers.self_worth_in_love ?? 3;",
    "  const spread = Math.max(cc, sc, ah, tb, sw) - Math.min(cc, sc, ah, tb, sw);",
    "  const scores: Record<Posture, number> = {",
    "    anchored: cc + sc + ah + tb + sw,",
    "    tender: (6 - sc) + (6 - cr) + (6 - sw),",
    "    guarded: (6 - cc) + (6 - ah) + cr,",
    "    whirling: (6 - tb) + (6 - sw) + spread",
    "  };",
    '  let best: Posture = "anchored";',
    "  for (const p of POSTURES) if (scores[p] > scores[best]) best = p;",
    "  return best;",
    "}",
    "",
    "// The reading narratives, ported from relational_posture.py _fallback_reading",
    "// (generalized off the Christian framing into plain, warm copy).",
    "const READINGS: Record<Posture, PostureReading> = {",
    "  anchored: {",
    '    summary: "You rest in a quiet trust — at home with closeness and at home with space. That doesn\'t mean you\'ve never been hurt; it means safe people have had room to do their slow work in you.",',
    '    growingToward: "Keep anchoring others — your steadiness is a gift to people who haven\'t found theirs yet.",',
    '    healingInvitation: "This week, look for one person who feels alone and bring them a small, undramatic kindness. Your steadiness is contagious."',
    "  },",
    "  tender: {",
    '    summary: "When you care about someone, you start watching for the small signs that they\'re pulling away — and you sometimes reach in ways that, paradoxically, push them back. That posture was forged in a season when you weren\'t sure your presence was wanted.",',
    '    growingToward: "Anchored — at home in both closeness and space, trusting that you are wanted even in silence.",',
    '    healingInvitation: "When the watchful feeling rises this week, name it to yourself, breathe once, and ask: is this them, or is this an old story? Sit with the answer before you act."',
    "  },",
    "  guarded: {",
    '    summary: "You\'ve learned that the safest place is the one you control alone. That instinct made sense once — it kept something tender in you safe when no one else would. But the walls that protected the child can keep the adult lonely.",',
    '    growingToward: "Anchored — letting one or two safe people past the wall, slowly, and learning that closeness can be safe.",',
    '    healingInvitation: "This week, when the urge to pull back rises with someone safe, try staying one beat longer. One honest sentence. One unhurried minute. See what happens."',
    "  },",
    "  whirling: {",
    '    summary: "You long for closeness AND fear it at the same time. You reach, then pull back. You trust, then question. That\'s not weakness — it\'s a heart that learned the people closest to it were also the ones who hurt it most.",',
    '    growingToward: "Anchored — slowly, one small experiment at a time, learning that some love is safe, and that you are not too much.",',
    '    healingInvitation: "Find one person this week who has been steadily, undramatically kind to you. Send a short message — no big confession, just contact. Notice what rises. That\'s the work."',
    "  }",
    "};",
    "",
    "export function readingFor(posture: Posture): PostureReading {",
    "  return READINGS[posture] || READINGS.tender;",
    "}",
    "",
    "export type ConnectionProfile = {",
    "  id: string;",
    "  userId: string | null;",
    "  name: string;",
    "  purpose: string;",
    "  posture: Posture | null;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  interests: string[];",
    "};",
    "",
    "export type MatchResult = { profile: ConnectionProfile; score: number; why: string };",
    "",
    "// Split a comma/newline list into a clean array.",
    "export function parseList(value: unknown): string[] {",
    '  if (Array.isArray(value)) return value.map((v) => String(v).trim()).filter(Boolean);',
    '  if (typeof value !== "string") return [];',
    "  return value",
    "    .split(/[,\\n;]+/)",
    "    .map((v) => v.trim())",
    "    .filter(Boolean);",
    "}",
    "",
    "// Purpose tokens: strip stopwords so free-text purpose statements can overlap",
    "// meaningfully (e.g. \"help neighbors grow in faith\" ≈ \"grow faith in community\").",
    "const PURPOSE_STOPWORDS = new Set([",
    '  "the","a","an","and","or","to","of","in","for","with","my","i","that","this","is","be",',
    '  "on","at","as","from","by","it","we","you","our","their","who","what","how","when",',
    '  "while","into","about","not","do","doing","make","more","life","want","would","will",',
    '  "am","are","was","were","been","being","can","could","should","just","very","also"',
    "]);",
    "",
    "export function purposeTokens(purpose: string): string[] {",
    "  return purpose",
    "    .toLowerCase()",
    "    .replace(/[^a-z0-9\\s]/g, \" \")",
    "    .split(/\\s+/)",
    "    .filter((w) => w.length > 2 && !PURPOSE_STOPWORDS.has(w));",
    "}",
    "",
    "function setOverlap(a: Set<string>, b: Set<string>): number {",
    "  let n = 0;",
    "  a.forEach((x) => { if (b.has(x)) n += 1; });",
    "  return n;",
    "}",
    "",
    "function lowerSet(xs: string[]): Set<string> {",
    "  return new Set(xs.map((x) => x.toLowerCase().trim()).filter(Boolean));",
    "}",
    "",
    "// Purpose-first compatibility. Extends Kindred core.py compatibility_score:",
    "// purpose tokens lead, growth goals next, values, interests last. Intentional",
    "// people (both named a real purpose) get a small boost. Clamped 35..99.",
    "export function compatibilityScore(me: ConnectionProfile, other: ConnectionProfile): number {",
    "  let score = 25;",
    "  const purposeHits = setOverlap(new Set(purposeTokens(me.purpose)), new Set(purposeTokens(other.purpose)));",
    "  score += purposeHits * 14;",
    "  score += setOverlap(lowerSet(me.growthGoals), lowerSet(other.growthGoals)) * 12;",
    "  score += setOverlap(lowerSet(me.coreValues), lowerSet(other.coreValues)) * 10;",
    "  // Hobbies matter less than who you are becoming — keep them light.",
    "  score += setOverlap(lowerSet(me.interests), lowerSet(other.interests)) * 2;",
    "  if (me.purpose.trim().length > 10 && other.purpose.trim().length > 10) score += 5;",
    "  // Mild complementary-posture nudge: different postures can steady each other.",
    "  if (me.posture && other.posture && me.posture !== other.posture) {",
    '    const pairs = new Set(["anchored-tender", "anchored-guarded", "tender-guarded", "anchored-whirling"]);',
    '    const key = [me.posture, other.posture].sort().join("-");',
    "    if (pairs.has(key)) score += 3;",
    "  }",
    "  return Math.min(99, Math.max(35, score));",
    "}",
    "",
    "// A short, honest 'why we picked them' — leads with shared purpose and growth,",
    "// not hobbies or loneliness. Never invents facts.",
    "export function matchWhy(me: ConnectionProfile, other: ConnectionProfile): string {",
    "  const shared = (a: string[], b: string[]) => {",
    "    const bs = lowerSet(b);",
    "    return a.filter((x) => bs.has(x.toLowerCase()));",
    "  };",
    "  const purposeHits = [...new Set(purposeTokens(me.purpose))].filter((t) =>",
    "    new Set(purposeTokens(other.purpose)).has(t)",
    "  );",
    "  const values = shared(me.coreValues, other.coreValues);",
    "  const goals = shared(me.growthGoals, other.growthGoals);",
    "  const bits: string[] = [];",
    "  if (purposeHits.length) {",
    '    bits.push(`your purposes both lean into ${purposeHits.slice(0, 3).join(", ")}`);',
    "  } else if (me.purpose.trim() && other.purpose.trim()) {",
    '    bits.push(`you are both building something intentional — theirs: "${other.purpose.slice(0, 80)}${other.purpose.length > 80 ? "…" : ""}"`);',
    "  }",
    '  if (goals.length) bits.push(`you are both growing toward ${goals.slice(0, 2).join(" and ")}`);',
    '  if (values.length) bits.push(`you both hold ${values.slice(0, 3).join(", ")} close`);',
    "  if (me.posture && other.posture) {",
    "    bits.push(",
    "      me.posture === other.posture",
    '        ? `you share a ${me.posture} posture — the same invitation to grow`',
    '        : `your ${me.posture} and their ${other.posture} postures could steady each other`',
    "    );",
    "  }",
    "  if (!bits.length) {",
    '    return `You and ${other.name} share resonance shaped by purpose and growth, not appearance. Worth a real conversation about what you are each becoming.`;',
    "  }",
    '  return `We paired you with ${other.name} because ${bits.join("; ")}.`;',
    "}",
    "",
    "const fallbackProfiles: ConnectionProfile[] = [",
    '  { id: "sample-1", userId: null, name: "Sam Rivera", purpose: "Help neighbors find footing and serve the community together", posture: "anchored", coreValues: ["honesty", "growth", "faith", "service"], growthGoals: ["listen better", "serve locally", "lead one small group"], interests: ["hiking", "reading"] },',
    '  { id: "sample-2", userId: null, name: "Jordan Lee", purpose: "Build things that outlast me and grow people while building", posture: "tender", coreValues: ["growth", "creativity", "courage"], growthGoals: ["listen better", "take wiser risks"], interests: ["music", "hiking"] },',
    '  { id: "sample-3", userId: null, name: "Alex Okafor", purpose: "Walk with people through hard seasons toward the life they were made for", posture: "guarded", coreValues: ["faith", "loyalty", "compassion"], growthGoals: ["open up more", "serve locally"], interests: ["reading"] }',
    "];",
    "",
    "function rowToProfile(row: Record<string, unknown>): ConnectionProfile {",
    "  const toArr = (v: unknown): string[] => {",
    "    if (Array.isArray(v)) return v.map((x) => String(x));",
    '    if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "    return [];",
    "  };",
    '  const posture = String(row.posture || "");',
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    name: String(row.name || "Unnamed"),',
    '    purpose: String(row.purpose || ""),',
    "    posture: (POSTURES as string[]).includes(posture) ? (posture as Posture) : null,",
    "    coreValues: toArr(row.core_values),",
    "    growthGoals: toArr(row.growth_goals),",
    "    interests: toArr(row.interests)",
    "  };",
    "}",
    "",
    "// When purpose onboarding ran but connection_profiles is empty/stale, pull",
    "// purpose + values + goals from onboarding_profiles so matching stays purpose-first.",
    "async function hydrateFromOnboarding(userId: string, profile: ConnectionProfile | null): Promise<ConnectionProfile | null> {",
    "  if (!hasDatabase()) return profile;",
    "  const needsPurpose = !profile || !profile.purpose || profile.purpose.trim().length <= 10;",
    "  const needsGoals = !profile || profile.growthGoals.length === 0;",
    "  const needsValues = !profile || profile.coreValues.length === 0;",
    "  if (!needsPurpose && !needsGoals && !needsValues) return profile;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select purpose, core_values, growth_goals from onboarding_profiles",
    "      where user_id = ${userId} and onboarded = true limit 1`;",
    "    if (!rows[0]) return profile;",
    "    const purpose = String(rows[0].purpose || \"\");",
    "    const toArr = (v: unknown): string[] => {",
    "      if (Array.isArray(v)) return v.map((x) => String(x));",
    "      if (typeof v === \"string\" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }",
    "      return [];",
    "    };",
    "    const coreValues = toArr(rows[0].core_values);",
    "    const growthGoals = toArr(rows[0].growth_goals);",
    "    if (!profile) {",
    "      return {",
    '        id: "onboarding-hydrated",',
    "        userId,",
    '        name: "You",',
    "        purpose,",
    "        posture: null,",
    "        coreValues,",
    "        growthGoals,",
    "        interests: []",
    "      };",
    "    }",
    "    return {",
    "      ...profile,",
    "      purpose: needsPurpose && purpose ? purpose : profile.purpose,",
    "      coreValues: needsValues && coreValues.length ? coreValues : profile.coreValues,",
    "      growthGoals: needsGoals && growthGoals.length ? growthGoals : profile.growthGoals",
    "    };",
    "  } catch {",
    "    return profile;",
    "  }",
    "}",
    "",
    "export async function getMyProfile(userId: string): Promise<ConnectionProfile | null> {",
    "  if (!hasDatabase()) return fallbackProfiles[0];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where user_id = ${userId} limit 1`;",
    "    const base = rows[0] ? rowToProfile(rows[0]) : null;",
    "    return hydrateFromOnboarding(userId, base);",
    "  } catch {",
    "    return hydrateFromOnboarding(userId, null);",
    "  }",
    "}",
    "",
    "export async function getProfile(id: string): Promise<ConnectionProfile | null> {",
    "  if (!hasDatabase()) return fallbackProfiles.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where id = ${id} limit 1`;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SaveProfileInput = {",
    "  userId: string;",
    "  name: string;",
    "  purpose?: string;",
    "  posture?: Posture | null;",
    "  coreValues?: string[];",
    "  growthGoals?: string[];",
    "  interests?: string[];",
    "};",
    "",
    "// Upsert the current user's profile (one profile per user).",
    "export async function saveMyProfile(input: SaveProfileInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const values = JSON.stringify(input.coreValues || []);",
    "  const goals = JSON.stringify(input.growthGoals || []);",
    "  const interests = JSON.stringify(input.interests || []);",
    "  const posture = input.posture || null;",
    "  const existing = await sql`select id from connection_profiles where user_id = ${input.userId} limit 1`;",
    "  if (existing[0]) {",
    '    await sql`update connection_profiles set name = ${input.name}, purpose = ${input.purpose || ""}, posture = ${posture}, core_values = ${values}, growth_goals = ${goals}, interests = ${interests}, updated_at = now() where user_id = ${input.userId}`;',
    "    return true;",
    "  }",
    '  await sql`insert into connection_profiles (user_id, name, purpose, posture, core_values, growth_goals, interests) values (${input.userId}, ${input.name}, ${input.purpose || ""}, ${posture}, ${values}, ${goals}, ${interests})`;',
    "  return true;",
    "}",
    "",
    "// Store the posture from an assessment onto the user's profile (creates a stub",
    "// profile if none exists yet).",
    "export async function saveMyPosture(userId: string, name: string, posture: Posture): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const existing = await sql`select id from connection_profiles where user_id = ${userId} limit 1`;",
    "  if (existing[0]) {",
    "    await sql`update connection_profiles set posture = ${posture}, updated_at = now() where user_id = ${userId}`;",
    "  } else {",
    "    await sql`insert into connection_profiles (user_id, name, posture) values (${userId}, ${name}, ${posture})`;",
    "  }",
    "  return true;",
    "}",
    "",
    "// Matching: score every other profile, sort highest-first. Purpose-filled",
    "// profiles rank above empty ones when scores tie. Groups before pairs is",
    "// enforced in the UX (pods first); this returns ranked one-to-one candidates.",
    "export async function findMatches(userId: string, limit = 10): Promise<MatchResult[]> {",
    "  const rank = (me: ConnectionProfile, pool: ConnectionProfile[]) =>",
    "    pool",
    "      .map((p) => ({ profile: p, score: compatibilityScore(me, p), why: matchWhy(me, p) }))",
    "      .sort((a, b) => {",
    "        if (b.score !== a.score) return b.score - a.score;",
    "        // Tie-break: prefer people who named a real purpose (intentional over empty).",
    "        const aP = a.profile.purpose.trim().length > 10 ? 1 : 0;",
    "        const bP = b.profile.purpose.trim().length > 10 ? 1 : 0;",
    "        return bP - aP;",
    "      })",
    "      .slice(0, limit);",
    "",
    "  if (!hasDatabase()) {",
    "    const me = fallbackProfiles[0];",
    "    return rank(me, fallbackProfiles.filter((p) => p.id !== me.id));",
    "  }",
    "  try {",
    "    const me = await getMyProfile(userId);",
    "    if (!me) return [];",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, name, purpose, posture, core_values, growth_goals, interests from connection_profiles where user_id is null or user_id <> ${userId} limit 500`;",
    "    return rank(me, rows.map(rowToProfile));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// ---- Growth Pods (groups before pairs), ported from pods.py -----------------",
    "// Every pod carries a purpose — the reason the circle exists (community renewal,",
    "// mutual growth, service, faith, etc.). People join around that purpose.",
    "",
    "export const POD_MAX_MEMBERS = 6; // pods.py caps membership at 6",
    "",
    "// App flavor: growth (Kindred), dating (Aligned Souls), community (milstead.us).",
    "// Seeds and some copy tilt by mode; matching stays purpose-first in all three.",
    'export type ConnectionAppMode = "growth" | "dating" | "community";',
    "export function connectionAppMode(): ConnectionAppMode {",
    '  const m = (process.env.CONNECTION_APP_MODE || "growth").toLowerCase();',
    '  if (m === "dating" || m === "community") return m;',
    '  return "growth";',
    "}",
    "",
    "// milstead.us / Community Connections — local purpose circles (not lonely-only pods).",
    "export const COMMUNITY_POD_TEMPLATES: Array<{ name: string; description: string; purpose: string }> = [",
    "  {",
    '    name: "Block Party Builders",',
    '    description: "Neighbors who plan gatherings so streets know each other by name.",',
    '    purpose: "Host block parties and neighborhood welcome gatherings"',
    "  },",
    "  {",
    '    name: "Cleanup Crew",',
    '    description: "A small team that takes on parks, ditches, and shared spaces.",',
    '    purpose: "Keep public spaces clean and beautiful together"',
    "  },",
    "  {",
    '    name: "Prayer Walk Circle",',
    '    description: "Walk the streets, notice needs, and pray for the people who live there.",',
    '    purpose: "Pray for and walk with the community week by week"',
    "  },",
    "  {",
    '    name: "Local Project Partners",',
    '    description: "Pick one neighborhood problem and chip away until it moves.",',
    '    purpose: "Finish practical local projects that make the place stronger"',
    "  },",
    "  {",
    '    name: "Welcome Wagon",',
    '    description: "Meet new residents with a meal, a map, and a real invitation in.",',
    '    purpose: "Welcome newcomers so no one stays a stranger long"',
    "  }",
    "];",
    "",
    "export type Pod = {",
    "  id: string;",
    "  name: string;",
    "  description: string;",
    "  purpose: string;",
    "  createdBy: string | null;",
    "  memberCount: number;",
    "  isMember: boolean;",
    "};",
    "",
    "const fallbackPods: Pod[] = [",
    '  { id: "pod-sample-1", name: "Builders Who Serve", description: "A small group learning to show up for the neighborhood one week at a time.", purpose: "Strengthen the community through practical service and mutual accountability", createdBy: null, memberCount: 3, isMember: false },',
    '  { id: "pod-sample-2", name: "Purpose Partners", description: "A few people helping each other grow into the life they were made for.", purpose: "Personal growth, courage, and becoming who we are called to be", createdBy: null, memberCount: 2, isMember: false },',
    '  { id: "pod-sample-3", name: "Community Strength Circle", description: "Neighbors connecting so the place we live gets stronger and better connected.", purpose: "Local belonging, friendship, and community renewal", createdBy: null, memberCount: 2, isMember: false },',
    "  ...COMMUNITY_POD_TEMPLATES.slice(0, 2).map((t, i) => ({",
    '    id: `pod-community-${i + 1}`,',
    "    name: t.name,",
    "    description: t.description,",
    "    purpose: t.purpose,",
    "    createdBy: null,",
    "    memberCount: 1,",
    "    isMember: false",
    "  }))",
    "];",
    "",
    "// ---- Loneliness → service prescription (Kindred Slice D, generalized) --------",
    "// Loneliness is welcomed. The prescription is purpose and service — not pairing",
    "// lonely people with each other as the fix.",
    "",
    "export type ServiceEvent = {",
    "  id: string;",
    "  title: string;",
    "  city: string;",
    "  startsAt: string;",
    "  eventType: string;",
    "  description: string;",
    "};",
    "",
    "export type LonelinessPrescription = {",
    "  lonelyCountThisWeek: number;",
    "  needsPrescription: boolean;",
    "  message: string;",
    "  event: ServiceEvent | null;",
    "};",
    "",
    "const fallbackServiceEvents: ServiceEvent[] = [",
    '  { id: "svc-1", title: "Saturday park cleanup", city: "Local", startsAt: new Date(Date.now() + 3 * 86400000).toISOString(), eventType: "service", description: "One hour. Bring gloves. Leave the place better than you found it." },',
    '  { id: "svc-2", title: "Meal pack for neighbors", city: "Local", startsAt: new Date(Date.now() + 5 * 86400000).toISOString(), eventType: "volunteer", description: "Pack bags for families nearby. Small team, real need." },',
    '  { id: "svc-3", title: "Community prayer walk", city: "Local", startsAt: new Date(Date.now() + 7 * 86400000).toISOString(), eventType: "spiritual", description: "Walk a few blocks, notice people, pray for the place you live." }',
    "];",
    "",
    "export async function countLonelyThisWeek(userId: string): Promise<number> {",
    "  if (!hasDatabase()) return 0;",
    "  try {",
    "    const sql = getDatabase();",
    "    const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString();",
    "    const rows = await sql`",
    "      select count(*) as c from connection_checkins",
    "      where user_id = ${userId} and mood = 'lonely' and created_at >= ${weekAgo}`;",
    "    return Number(rows[0]?.c || 0);",
    "  } catch {",
    "    return 0;",
    "  }",
    "}",
    "",
    "export async function recordCheckin(userId: string, mood: string, note = \"\"): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    '  const allowed = new Set(["lonely", "restless", "content", "bursting"]);',
    "  if (!allowed.has(mood)) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into connection_checkins (user_id, mood, note) values (${userId}, ${mood}, ${note})`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function suggestServiceEvent(userId: string, cityHint = \"\"): Promise<ServiceEvent | null> {",
    "  if (!hasDatabase()) return fallbackServiceEvents[0];",
    "  try {",
    "    const sql = getDatabase();",
    "    const now = new Date().toISOString();",
    "    const horizon = new Date(Date.now() + 14 * 86400000).toISOString();",
    "    const rows = await sql`",
    "      select id, title, city, starts_at, event_type, description from connection_service_events",
    "      where starts_at >= ${now} and starts_at <= ${horizon}",
    "        and (event_type in ('service', 'volunteer', 'church', 'spiritual') or intent = 'serving')",
    "        and not exists (",
    "          select 1 from connection_event_rsvps r where r.event_id = connection_service_events.id and r.user_id = ${userId}",
    "        )",
    "      order by starts_at asc limit 20`;",
    "    if (!rows.length) return fallbackServiceEvents[0];",
    "    const city = cityHint.trim().toLowerCase();",
    "    const pick = city",
    "      ? rows.find((r) => String(r.city || \"\").toLowerCase().includes(city)) || rows[0]",
    "      : rows[0];",
    "    return {",
    "      id: String(pick.id),",
    "      title: String(pick.title || \"Service opportunity\"),",
    '      city: String(pick.city || ""),',
    '      startsAt: String(pick.starts_at || ""),',
    '      eventType: String(pick.event_type || "service"),',
    '      description: String(pick.description || "")',
    "    };",
    "  } catch {",
    "    return fallbackServiceEvents[0];",
    "  }",
    "}",
    "",
    "export async function getLonelinessPrescription(userId: string, cityHint = \"\"): Promise<LonelinessPrescription> {",
    "  const lonelyCountThisWeek = await countLonelyThisWeek(userId);",
    "  const needsPrescription = lonelyCountThisWeek >= 2;",
    "  const event = needsPrescription ? await suggestServiceEvent(userId, cityHint) : null;",
    "  return {",
    "    lonelyCountThisWeek,",
    "    needsPrescription,",
    "    message: needsPrescription",
    '      ? "We see you. Loneliness is real — and the way through is purpose, not just more people. One small place to serve can remind you that you are useful and loved."',
    '      : "Check in honestly. If loneliness stacks up, we will point you toward purpose and service — not a shallow fix."',
    "    ,",
    "    event",
    "  };",
    "}",
    "",
    "export async function rsvpServiceEvent(userId: string, eventId: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to RSVP." };',
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into connection_event_rsvps (event_id, user_id) values (${eventId}, ${userId}) on conflict do nothing`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not RSVP right now." };',
    "  }",
    "}",
    "",
    "function rowToPod(row: Record<string, unknown>, userId: string): Pod {",
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || "Pod"),',
    '    description: String(row.description || ""),',
    '    purpose: String(row.purpose || ""),',
    "    createdBy: row.created_by != null ? String(row.created_by) : null,",
    "    memberCount: Number(row.member_count || 0),",
    '    isMember: row.is_member === true || String(row.is_member) === "true" || Number(row.is_member) > 0 || String(row.created_by) === userId',
    "  };",
    "}",
    "",
    "// Score how well a pod's purpose aligns with a person's purpose + growth goals.",
    "export function podPurposeScore(me: ConnectionProfile, pod: Pod): number {",
    "  const meTokens = new Set([...purposeTokens(me.purpose), ...me.growthGoals.flatMap((g) => purposeTokens(g))]);",
    "  const podTokens = new Set(purposeTokens(`${pod.purpose} ${pod.name} ${pod.description}`));",
    "  return setOverlap(meTokens, podTokens);",
    "}",
    "",
    "// List the pods the current user belongs to, ported from pods.py list_my_pods.",
    "export async function listMyPods(userId: string): Promise<Pod[]> {",
    "  if (!hasDatabase()) return fallbackPods.filter((p) => p.isMember);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select p.id, p.name, p.description, p.purpose, p.created_by,",
    "        (select count(*) from connection_pod_members m where m.pod_id = p.id) as member_count,",
    "        true as is_member",
    "      from connection_pods p",
    "      join connection_pod_members me on me.pod_id = p.id and me.user_id = ${userId}",
    "      order by p.created_at desc limit 100`;",
    "    return rows.map((r) => rowToPod(r, userId));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Discover joinable pods with room. When the user has a profile, rank by how",
    "// well the pod's purpose overlaps their purpose and growth goals.",
    "export async function discoverPods(userId: string): Promise<Pod[]> {",
    "  if (!hasDatabase()) return fallbackPods.filter((p) => !p.isMember);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select p.id, p.name, p.description, p.purpose, p.created_by,",
    "        (select count(*) from connection_pod_members m where m.pod_id = p.id) as member_count,",
    "        false as is_member",
    "      from connection_pods p",
    "      where not exists (select 1 from connection_pod_members me where me.pod_id = p.id and me.user_id = ${userId})",
    "        and (select count(*) from connection_pod_members m where m.pod_id = p.id) < ${POD_MAX_MEMBERS}",
    "      order by p.created_at desc limit 50`;",
    "    const pods = rows.map((r) => rowToPod(r, userId));",
    "    const me = await getMyProfile(userId);",
    "    if (!me) return pods;",
    "    return pods.sort((a, b) => podPurposeScore(me, b) - podPurposeScore(me, a));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Create a pod with a required purpose and make the creator its first member.",
    "export async function createPod(userId: string, name: string, description: string, purpose = \"\"): Promise<Pod | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`insert into connection_pods (name, description, purpose, created_by) values (${name}, ${description}, ${purpose}, ${userId}) returning id, name, description, purpose, created_by`;",
    "    const pod = rows[0];",
    "    if (!pod) return null;",
    "    await sql`insert into connection_pod_members (pod_id, user_id) values (${pod.id}, ${userId}) on conflict do nothing`;",
    '    return { id: String(pod.id), name: String(pod.name), description: String(pod.description || ""), purpose: String(pod.purpose || ""), createdBy: userId, memberCount: 1, isMember: true };',
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Join a pod if it has room, ported from pods.py join_pod (409-style guard at cap).",
    "export async function joinPod(userId: string, podId: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to join pods." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const exists = await sql`select id from connection_pods where id = ${podId} limit 1`;",
    '    if (!exists[0]) return { ok: false, message: "That pod no longer exists." };',
    "    const already = await sql`select 1 from connection_pod_members where pod_id = ${podId} and user_id = ${userId} limit 1`;",
    "    if (already[0]) return { ok: true };",
    "    const countRows = await sql`select count(*) as c from connection_pod_members where pod_id = ${podId}`;",
    '    if (Number(countRows[0]?.c || 0) >= POD_MAX_MEMBERS) return { ok: false, message: "This pod is full." };',
    "    await sql`insert into connection_pod_members (pod_id, user_id) values (${podId}, ${userId}) on conflict do nothing`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not join right now." };',
    "  }",
    "}",
    "",
    "export function connectionEnabled(): boolean {",
    '  return process.env.FEATURE_CONNECTION !== "false";',
    "}"
  ]);
}

// ---- src/app/api/connection/assessment/route.ts -----------------------------

function assessmentApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/assessment/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { POSTURE_QUESTIONS, heuristicPosture, readingFor, saveMyPosture, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  return NextResponse.json({ ok: true, questions: POSTURE_QUESTIONS });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const rawAnswers = (body.answers && typeof body.answers === "object") ? (body.answers as Record<string, unknown>) : {};',
    "  const answers: Record<string, number> = {};",
    "  for (const q of POSTURE_QUESTIONS) {",
    "    const v = Number(rawAnswers[q.key]);",
    "    if (Number.isInteger(v) && v >= 1 && v <= 5) answers[q.key] = v;",
    "  }",
    "  // Ported from relational_posture.py _validate_answers: at least 4 of 6.",
    "  if (Object.keys(answers).length < 4) {",
    '    return NextResponse.json({ ok: false, message: "Please answer at least 4 of the 6 questions." }, { status: 400 });',
    "  }",
    "  const posture = heuristicPosture(answers);",
    "  const reading = readingFor(posture);",
    '  const name = user?.name || user?.email || "Friend";',
    '  const saved = await saveMyPosture(String(user?.id || ""), name, posture);',
    "  return NextResponse.json({ ok: true, posture, reading, saved });",
    "}"
  ]);
}

// ---- src/app/api/connection/matches/route.ts --------------------------------

function matchesApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/matches/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { findMatches, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const matches = await findMatches(String(user?.id || ""));',
    "  return NextResponse.json({ ok: true, matches });",
    "}"
  ]);
}

// ---- src/app/api/connection/pods/route.ts -----------------------------------

function podsApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/pods/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listMyPods, discoverPods, createPod, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false, message: "Connection is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const userId = String(user?.id || "");',
    "  const [mine, discover] = await Promise.all([listMyPods(userId), discoverPods(userId)]);",
    "  return NextResponse.json({ ok: true, mine, discover });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    "  // Creating pods is an admin action (seeding the groups people join).",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    '  const description = typeof body.description === "string" ? body.description.trim() : "";',
    '  const purpose = typeof body.purpose === "string" ? body.purpose.trim() : "";',
    '  if (name.length < 2) return NextResponse.json({ ok: false, message: "A pod name is required." }, { status: 400 });',
    '  if (purpose.length < 8) return NextResponse.json({ ok: false, message: "Name the purpose this group exists for — what you will grow or build together." }, { status: 400 });',
    '  const pod = await createPod(String(user?.id || ""), name, description, purpose);',
    '  if (!pod) return NextResponse.json({ ok: false, message: "Connect a database to create pods." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, pod });",
    "}"
  ]);
}

// ---- src/app/api/connection/pods/[id]/join/route.ts -------------------------

function podJoinApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/pods/[id]/join/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { joinPod, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    '  const result = await joinPod(String(user?.id || ""), id);',
    '  if (!result.ok) return NextResponse.json({ ok: false, message: result.message || "Could not join." }, { status: 409 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/connection/page.tsx (assessment + posture reading) -------------

function connectionPageFile(): GeneratedModuleFile {
  return file("src/app/connection/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { POSTURE_QUESTIONS, getMyProfile, readingFor, connectionEnabled, getLonelinessPrescription, connectionAppMode } from "@/lib/db/connection";',
    'import { PostureAssessment } from "./assessment-form";',
    'import { PrescriptionCard } from "./prescription-card";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ConnectionPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection");',
    "  const user = await getCurrentUser();",
    "  const userId = user?.id ? String(user.id) : \"\";",
    "  const profile = userId ? await getMyProfile(userId) : null;",
    "  const reading = profile?.posture ? readingFor(profile.posture) : null;",
    "  const prescription = userId ? await getLonelinessPrescription(userId) : null;",
    "  const mode = connectionAppMode();",
    "  const lede =",
    '    mode === "community"',
    '      ? "Neighbors connect around making this place stronger — friendship that serves the community, not only loneliness."',
    '      : mode === "dating"',
    '        ? "Find a companion who helps you become who you were made to be — purpose and growth first, not endless swiping."',
    '        : "We match people who are becoming someone and building something — not just people who feel alone.";',
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>Connect around purpose</h1>",
    "      <p>{lede} Name your purpose, check how you show up in relationships, join a small group oriented around growth, then meet one person at a time when you are ready.</p>",
    "      {prescription ? <PrescriptionCard initial={prescription} /> : null}",
    "      {profile?.purpose ? (",
    '        <section className="panel">',
    "          <p><strong>Your purpose:</strong> {profile.purpose}</p>",
    "          {profile.growthGoals.length > 0 ? (",
    '            <p><strong>Growing toward:</strong> {profile.growthGoals.join(", ")}</p>',
    "          ) : null}",
    "        </section>",
    "      ) : (",
    '        <p className="note">Add a purpose on your profile or through onboarding first — matching works best when we know what you are building toward.</p>',
    "      )}",
    "      {reading ? (",
    '        <section className="grid">',
    '          <article className="card"><span>Your posture</span><strong>{profile?.posture}</strong></article>',
    "        </section>",
    "      ) : null}",
    "      {reading ? (",
    '        <section className="panel">',
    "          <p>{reading.summary}</p>",
    "          <p><strong>Growing toward:</strong> {reading.growingToward}</p>",
    "          <p><strong>Try this week:</strong> {reading.healingInvitation}</p>",
    "        </section>",
    "      ) : (",
    '        <p className="note">You have not taken the relationship check-in yet. It takes about a minute and helps us pair you for mutual growth.</p>',
    "      )}",
    "      <PostureAssessment questions={POSTURE_QUESTIONS} />",
    '      <p className="stack">',
    '        <Link className="button primary" href="/connection/pods">Browse purpose groups</Link>',
    '        <Link className="button" href="/connection/matches">People on a similar path</Link>',
    "      </p>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/assessment-form.tsx (client) ------------------------

function assessmentFormFile(): GeneratedModuleFile {
  return file("src/app/connection/assessment-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "type Question = { key: string; prompt: string; lowLabel: string; highLabel: string; axis: string };",
    "type Reading = { summary: string; growingToward: string; healingInvitation: string };",
    "",
    "export function PostureAssessment({ questions }: { questions: Question[] }) {",
    "  const [answers, setAnswers] = useState<Record<string, number>>({});",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "  const [result, setResult] = useState<{ posture: string; reading: Reading } | null>(null);",
    "",
    "  async function submit(event: React.FormEvent) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/connection/assessment", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ answers })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    "      setResult({ posture: data.posture, reading: data.reading });",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  if (result) {",
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Your posture</p>',
    "        <h2>{result.posture}</h2>",
    "        <p>{result.reading.summary}</p>",
    "        <p><strong>Growing toward:</strong> {result.reading.growingToward}</p>",
    "        <p><strong>Try this week:</strong> {result.reading.healingInvitation}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    "      <h2>Relationship check-in</h2>",
    "      {questions.map((q) => (",
    '        <fieldset className="panel" key={q.key}>',
    "          <legend>{q.prompt}</legend>",
    '          <div className="scale" role="radiogroup" aria-label={q.prompt}>',
    "            {[1, 2, 3, 4, 5].map((n) => (",
    '              <label key={n} className="scale-option">',
    '                <input type="radio" name={q.key} value={n} checked={answers[q.key] === n} onChange={() => setAnswers((prev) => ({ ...prev, [q.key]: n }))} />',
    "                <span>{n}</span>",
    "              </label>",
    "            ))}",
    "          </div>",
    '          <p className="note">{q.lowLabel} &middot; {q.highLabel}</p>',
    "        </fieldset>",
    "      ))}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "See my posture"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/matches/page.tsx ------------------------------------

function matchesPageFile(): GeneratedModuleFile {
  return file("src/app/connection/matches/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { findMatches, getMyProfile, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MatchesPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection/matches");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const profile = userId ? await getMyProfile(userId) : null;",
    "  const matches = userId ? await findMatches(userId) : [];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>People on a similar path</h1>",
    "      <p>Matched by shared purpose and growth first — values next, hobbies last. Groups come before pairs; these are people you could help grow, and who could help you grow.</p>",
    "      {!profile ? (",
    '        <p className="note">Take the <Link href="/connection">relationship check-in</Link> and name your purpose so we can match you well.</p>',
    "      ) : !profile.purpose || profile.purpose.trim().length <= 10 ? (",
    '        <p className="note">Add a clear purpose on <Link href="/connection">Connection</Link> first. We connect around what you are becoming, not emptiness.</p>',
    "      ) : matches.length === 0 ? (",
    '        <p className="note">No one to suggest yet. Check back as more people join — or start in a purpose group.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {matches.map((m) => (",
    '            <article className="wide-card" key={m.profile.id}>',
    "              <span>{m.score}% purpose alignment</span>",
    "              <strong>{m.profile.name}</strong>",
    "              {m.profile.purpose ? <p><strong>Purpose:</strong> {m.profile.purpose}</p> : null}",
    "              {m.profile.growthGoals.length > 0 ? (",
    '                <p><strong>Growing toward:</strong> {m.profile.growthGoals.slice(0, 3).join(", ")}</p>',
    "              ) : null}",
    '              <p className="note">{m.why}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/connection">Back to connection</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/pods/page.tsx (groups before pairs) -----------------

function podsPageFile(): GeneratedModuleFile {
  return file("src/app/connection/pods/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listMyPods, discoverPods, connectionEnabled, POD_MAX_MEMBERS } from "@/lib/db/connection";',
    'import { JoinPodButton } from "./join-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function PodsPage() {",
    "  if (!connectionEnabled()) {",
    '    return (<main className="shell"><h1>Connection</h1><p>Connection is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/connection/pods");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const [mine, discover] = userId ? await Promise.all([listMyPods(userId), discoverPods(userId)]) : [[], []];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Connection</p>',
    "      <h1>Purpose groups</h1>",
    "      <p>Small groups come first — up to {POD_MAX_MEMBERS} people, each oriented around a shared purpose. Join people who are building and growing, so friendship serves improvement, not just company.</p>",
    "",
    "      <h2>Your groups</h2>",
    "      {mine.length === 0 ? (",
    '        <p className="note">You have not joined a group yet. Find one whose purpose matches what you are becoming.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {mine.map((pod) => (",
    '            <article className="wide-card" key={pod.id}>',
    "              <span>{pod.memberCount} / {POD_MAX_MEMBERS} members</span>",
    "              <strong>{pod.name}</strong>",
    "              {pod.purpose ? <p><strong>Purpose:</strong> {pod.purpose}</p> : null}",
    "              {pod.description ? <p>{pod.description}</p> : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Groups with room</h2>",
    "      {discover.length === 0 ? (",
    '        <p className="note">No open groups right now. Check back soon.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {discover.map((pod) => (",
    '            <article className="wide-card" key={pod.id}>',
    "              <span>{pod.memberCount} / {POD_MAX_MEMBERS} members</span>",
    "              <strong>{pod.name}</strong>",
    "              {pod.purpose ? <p><strong>Purpose:</strong> {pod.purpose}</p> : null}",
    "              {pod.description ? <p>{pod.description}</p> : null}",
    "              <JoinPodButton podId={pod.id} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/connection">Back to connection</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/connection/pods/join-button.tsx (client) -----------------------

function joinButtonFile(): GeneratedModuleFile {
  return file("src/app/connection/pods/join-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function JoinPodButton({ podId }: { podId: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "joining" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function join() {",
    '    setStatus("joining");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/connection/pods/${podId}/join`, { method: "POST" });',
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not join this group.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    "    <span>",
    '      <button className="button primary" type="button" onClick={join} disabled={status === "joining"}>',
    '        {status === "joining" ? "Joining…" : "Join this group"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert"> {message}</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

// ---- Loneliness prescription API -------------------------------------------

function prescriptionApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/prescription/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getLonelinessPrescription, recordCheckin, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const prescription = await getLonelinessPrescription(String(user?.id || ""));',
    "  return NextResponse.json({ ok: true, prescription });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const mood = typeof body.mood === "string" ? body.mood : "";',
    '  const note = typeof body.note === "string" ? body.note : "";',
    '  const saved = await recordCheckin(String(user?.id || ""), mood, note);',
    '  if (!saved) return NextResponse.json({ ok: false, message: "Could not save check-in." }, { status: 400 });',
    '  const prescription = await getLonelinessPrescription(String(user?.id || ""));',
    "  return NextResponse.json({ ok: true, prescription });",
    "}"
  ]);
}

function prescriptionRsvpApiFile(): GeneratedModuleFile {
  return file("src/app/api/connection/prescription/rsvp/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { rsvpServiceEvent, connectionEnabled } from "@/lib/db/connection";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(request: Request) {",
    '  if (!connectionEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const eventId = typeof body.eventId === "string" ? body.eventId : "";',
    '  if (!eventId) return NextResponse.json({ ok: false, message: "Event required." }, { status: 400 });',
    '  const result = await rsvpServiceEvent(String(user?.id || ""), eventId);',
    "  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 409 });",
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/connection/prescription-card.tsx (client) ----------------------

function prescriptionCardFile(): GeneratedModuleFile {
  return file("src/app/connection/prescription-card.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "type ServiceEvent = { id: string; title: string; city: string; startsAt: string; eventType: string; description: string };",
    "type Prescription = { lonelyCountThisWeek: number; needsPrescription: boolean; message: string; event: ServiceEvent | null };",
    "",
    "export function PrescriptionCard({ initial }: { initial: Prescription }) {",
    "  const [prescription, setPrescription] = useState(initial);",
    '  const [mood, setMood] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "rsvpd">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function checkIn(nextMood: string) {",
    "    setMood(nextMood);",
    '    setStatus("saving");',
    "    try {",
    '      const response = await fetch("/api/connection/prescription", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ mood: nextMood })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save.");',
    "        return;",
    "      }",
    "      setPrescription(data.prescription);",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function rsvp() {",
    "    if (!prescription.event) return;",
    '    setStatus("saving");',
    "    try {",
    '      const response = await fetch("/api/connection/prescription/rsvp", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ eventId: prescription.event.id })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not RSVP.");',
    "        return;",
    "      }",
    '      setStatus("rsvpd");',
    '      setMessage("You are on the list. Showing up is how purpose starts to heal.");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <section className="panel" data-testid="loneliness-prescription">',
    '      <p className="eyebrow">Connection check-in</p>',
    "      <h2>How are you feeling about connection this week?</h2>",
    '      <div className="chip-row">',
    '        {["lonely", "restless", "content", "bursting"].map((m) => (',
    "          <button",
    "            key={m}",
    '            type="button"',
    "            className={mood === m ? \"chip chip-on\" : \"chip\"}",
    "            onClick={() => checkIn(m)}",
    "            disabled={status === \"saving\"}",
    "          >",
    "            {m}",
    "          </button>",
    "        ))}",
    "      </div>",
    "      {prescription.needsPrescription ? (",
    "        <>",
    '          <p className="note" role="status">{prescription.message}</p>',
    "          <p><strong>{prescription.lonelyCountThisWeek}× lonely this week</strong> — purpose, not just people.</p>",
    "          {prescription.event ? (",
    '            <article className="card">',
    "              <span>A place to serve</span>",
    "              <strong>{prescription.event.title}</strong>",
    "              <p>{prescription.event.description}</p>",
    "              <p className=\"note\">{prescription.event.city} · {new Date(prescription.event.startsAt).toLocaleDateString()}</p>",
    '              <button className="button primary" type="button" onClick={rsvp} disabled={status === "saving" || status === "rsvpd"}>',
    '                {status === "rsvpd" ? "You\'re going" : "I\'ll be there"}',
    "              </button>",
    "            </article>",
    "          ) : null}",
    "        </>",
    "      ) : (",
    "        <p className=\"note\">{prescription.message}</p>",
    "      )}",
    '      {message ? <p className="note" role="status">{message}</p> : null}',
    "    </section>",
    "  );",
    "}"
  ]);
}

export const connectionEngineModule: AppModule = {
  slug: "connection-engine",
  name: "Connection Engine",
  tier: "optional",
  featureFlagEnv: "FEATURE_CONNECTION",
  files: () => [
    connectionLibFile(),
    assessmentApiFile(),
    matchesApiFile(),
    podsApiFile(),
    podJoinApiFile(),
    prescriptionApiFile(),
    prescriptionRsvpApiFile(),
    connectionPageFile(),
    assessmentFormFile(),
    matchesPageFile(),
    podsPageFile(),
    joinButtonFile(),
    prescriptionCardFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists connection_profiles (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete cascade,",
      "  name text not null default '',",
      "  purpose text not null default '',",
      "  posture text,",
      "  core_values jsonb not null default '[]'::jsonb,",
      "  growth_goals jsonb not null default '[]'::jsonb,",
      "  interests jsonb not null default '[]'::jsonb,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists connection_profiles_user_idx on connection_profiles (user_id);",
      "",
      "create table if not exists connection_pods (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null,",
      "  description text not null default '',",
      "  purpose text not null default '',",
      "  created_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now()",
      ");",
      "",
      "create table if not exists connection_pod_members (",
      "  pod_id uuid not null references connection_pods(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  joined_at timestamptz not null default now(),",
      "  primary key (pod_id, user_id)",
      ");",
      "create index if not exists connection_pod_members_user_idx on connection_pod_members (user_id);",
      "",
      "create table if not exists connection_checkins (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  mood text not null,",
      "  note text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists connection_checkins_user_created_idx on connection_checkins (user_id, created_at desc);",
      "",
      "create table if not exists connection_service_events (",
      "  id uuid primary key default gen_random_uuid(),",
      "  title text not null,",
      "  description text not null default '',",
      "  city text not null default '',",
      "  starts_at timestamptz not null,",
      "  event_type text not null default 'service',",
      "  intent text not null default 'serving',",
      "  created_at timestamptz not null default now()",
      ");",
      "",
      "create table if not exists connection_event_rsvps (",
      "  event_id uuid not null references connection_service_events(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  created_at timestamptz not null default now(),",
      "  primary key (event_id, user_id)",
      ");"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Purpose groups for growth apps (Kindred-style)",
      "insert into connection_pods (name, description, purpose) values",
      "  ('Builders Who Serve', 'A small group learning to show up for the neighborhood one week at a time.', 'Strengthen the community through practical service and mutual accountability'),",
      "  ('Purpose Partners', 'A few people helping each other grow into the life they were made for.', 'Personal growth, courage, and becoming who we are called to be'),",
      "  ('Community Strength Circle', 'Neighbors connecting so the place we live gets stronger and better connected.', 'Local belonging, friendship, and community renewal')",
      "on conflict do nothing;",
      "",
      "-- milstead.us / Community Connections purpose circles",
      "insert into connection_pods (name, description, purpose) values",
      "  ('Block Party Builders', 'Neighbors who plan gatherings so streets know each other by name.', 'Host block parties and neighborhood welcome gatherings'),",
      "  ('Cleanup Crew', 'A small team that takes on parks, ditches, and shared spaces.', 'Keep public spaces clean and beautiful together'),",
      "  ('Prayer Walk Circle', 'Walk the streets, notice needs, and pray for the people who live there.', 'Pray for and walk with the community week by week'),",
      "  ('Local Project Partners', 'Pick one neighborhood problem and chip away until it moves.', 'Finish practical local projects that make the place stronger'),",
      "  ('Welcome Wagon', 'Meet new residents with a meal, a map, and a real invitation in.', 'Welcome newcomers so no one stays a stranger long')",
      "on conflict do nothing;",
      "",
      "-- Service events for loneliness → purpose prescription",
      "insert into connection_service_events (title, description, city, starts_at, event_type, intent) values",
      "  ('Saturday park cleanup', 'One hour. Bring gloves. Leave the place better than you found it.', 'Local', now() + interval '3 days', 'service', 'serving'),",
      "  ('Meal pack for neighbors', 'Pack bags for families nearby. Small team, real need.', 'Local', now() + interval '5 days', 'volunteer', 'serving'),",
      "  ('Community prayer walk', 'Walk a few blocks, notice people, pray for the place you live.', 'Local', now() + interval '7 days', 'spiritual', 'serving')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Connection Engine — purpose-first matching + posture + purpose groups + service prescription.",
    "# Set FEATURE_CONNECTION=false to switch the whole module off.",
    "FEATURE_CONNECTION=true",
    "# growth | dating | community — tilts seeds/copy; matching stays purpose-first.",
    "CONNECTION_APP_MODE=growth"
  ],
  homeLinks: () => ['        <a className="button" href="/connection">Connect around purpose</a>'],
  navLinks: () => [{ href: "/connection", label: "Connection" }]
};
