// content-edit — Divi-style visual content editing (Phase 1), owner-requested
// 2026-07-10: "occasions where it would have been easier to click a text and
// change it than telling the agent what I am talking about."
//
// What it does: an owner/admin gets a floating "Edit page" toggle on every page.
// With it on, clicking any text element makes it editable in place; a small
// toolbar offers size (S/M/L/XL), weight, and color choices drawn from the app's
// design tokens (CSS variables) — never arbitrary CSS. Saving persists the edit
// to a content_overrides row keyed by (page, stable element path), and the same
// runtime applies stored overrides for EVERY visitor at render, so an edit made
// once shows for everyone. Anonymous visitors get zero edit affordances: the
// server decides canEdit from the session role, and the toggle/toolbar only
// render after that answer comes back true.
//
// How it mounts: the module emits src/app/template.tsx — the base generator does
// not emit one, so the root template is a collision-free hook that wraps every
// route (inside the root layout) without touching any base file. The runtime is
// a client component that (a) fetches this page's overrides + canEdit, (b)
// applies overrides to the DOM by resolving each stored element path, and (c)
// for editors only, layers on the click-to-edit interaction. Because templates
// remount per navigation, Edit mode is per-page and overrides re-apply on every
// route change.
//
// Stable element paths: a chain of tag:nth-of-type(i) segments from <body> down
// (e.g. "main:nth-of-type(1)>h1:nth-of-type(1)"). Type-position survives text
// changes and unrelated attribute churn; it does move if the page's structure is
// reordered — the /admin/content page lists every stored edit so a stranded one
// can be removed. Phase 2 (drag-reorder, spacing) extends this same schema; see
// docs/content-edit-phase-2-notes.md in the factory repo.
//
// Styling tokens, not CSS: the toolbar writes data-ce-size / data-ce-weight /
// data-ce-color attributes; a stylesheet the runtime ships maps those to the
// generated theme's CSS variables (--ink/--muted/--accent), with --ce-* override
// hooks so a ported/retrofitted app can supply its own palette without --accent
// existing. Text is written with textContent (never innerHTML) so an edit can
// never inject markup. Mixed-content elements (a <p> holding a <strong>) edit as
// flattened plain text — shown live in the element before saving, so what the
// owner sees is exactly what persists.
//
// Guards: reads are public on purpose (overrides ARE page content); writes and
// deletes require canAccessAdmin (owner/admin) server-side. Feature-flagged
// (FEATURE_CONTENT_EDIT); with no database the runtime stays silent and the API
// answers honestly instead of pretending to save.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/content-overrides.ts (model + queries) ----------------------

function overridesLibFile(): GeneratedModuleFile {
  return file("src/lib/db/content-overrides.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// One owner edit to one text element on one page: optional replacement text",
    "// plus optional style tokens. original_text is captured on the FIRST save and",
    "// never overwritten, so a reset can always restore what the code shipped.",
    "export type ContentOverride = {",
    "  id: string;",
    "  page: string;",
    "  elementPath: string;",
    "  text: string | null;",
    "  size: string | null;",
    "  weight: string | null;",
    "  color: string | null;",
    "  originalText: string;",
    "  updatedAt: string;",
    "};",
    "",
    "// The allowed style tokens. These are design-token names the runtime's",
    "// stylesheet maps onto the app's CSS variables — never raw CSS values.",
    'export const OVERRIDE_SIZES = ["s", "l", "xl"];',
    'export const OVERRIDE_WEIGHTS = ["normal", "semibold", "bold"];',
    'export const OVERRIDE_COLORS = ["ink", "muted", "accent"];',
    "",
    "export const MAX_TEXT_LENGTH = 4000;",
    "export const MAX_PAGE_LENGTH = 300;",
    "",
    "// A stored element path is strictly tag:nth-of-type(i) segments joined by",
    '// ">" — anything else is rejected at the API so a row can never hold a',
    "// selector we did not mint.",
    "const ELEMENT_PATH_PATTERN =",
    "  /^[a-z][a-z0-9-]*:nth-of-type\\(\\d{1,4}\\)(?:>[a-z][a-z0-9-]*:nth-of-type\\(\\d{1,4}\\)){0,39}$/;",
    "",
    "export function isValidElementPath(path: string): boolean {",
    "  return typeof path === \"string\" && path.length <= 600 && ELEMENT_PATH_PATTERN.test(path);",
    "}",
    "",
    "// Normalize a page path so the runtime and the API always key the same page",
    "// the same way: no query/hash, no duplicate or trailing slashes.",
    "export function normalizePage(raw: string): string | null {",
    '  let page = (raw || "").trim();',
    '  if (!page.startsWith("/")) return null;',
    "  const cut = page.search(/[?#]/);",
    "  if (cut >= 0) page = page.slice(0, cut);",
    '  page = page.replace(/\\/{2,}/g, "/");',
    '  if (page.length > 1 && page.endsWith("/")) page = page.slice(0, -1);',
    "  if (page.length === 0 || page.length > MAX_PAGE_LENGTH) return null;",
    "  return page;",
    "}",
    "",
    "// Plain-copy summary of an override's style tokens for the admin list.",
    "export function overrideStyleSummary(override: ContentOverride): string {",
    "  const parts: string[] = [];",
    "  if (override.size) parts.push(`size ${override.size.toUpperCase()}`);",
    "  if (override.weight) parts.push(`weight ${override.weight}`);",
    "  if (override.color) parts.push(`color ${override.color}`);",
    '  return parts.length ? parts.join(" · ") : "wording only";',
    "}",
    "",
    "function rowToOverride(row: Record<string, unknown>): ContentOverride {",
    "  return {",
    "    id: String(row.id),",
    '    page: String(row.page || "/"),',
    '    elementPath: String(row.element_path || ""),',
    "    text: row.text != null ? String(row.text) : null,",
    "    size: row.size != null ? String(row.size) : null,",
    "    weight: row.weight != null ? String(row.weight) : null,",
    "    color: row.color != null ? String(row.color) : null,",
    '    originalText: String(row.original_text || ""),',
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "// Overrides for one page. No sample fallback on purpose: with no database,",
    "// an empty set — the page exactly as coded — is the correct answer.",
    "export async function listOverrides(page: string): Promise<ContentOverride[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, page, element_path, text, size, weight, color, original_text, updated_at",
    "      from content_overrides where page = ${page}",
    "      order by element_path asc limit 500`;",
    "    return rows.map(rowToOverride);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Every stored edit across the app, for the /admin/content management page.",
    "export async function listAllOverrides(limit = 500): Promise<ContentOverride[]> {",
    "  const cap = Math.min(2000, Math.max(1, limit));",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, page, element_path, text, size, weight, color, original_text, updated_at",
    "      from content_overrides",
    "      order by page asc, element_path asc limit ${cap}`;",
    "    return rows.map(rowToOverride);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type UpsertOverrideInput = {",
    "  page: string;",
    "  elementPath: string;",
    "  text: string | null;",
    "  size: string | null;",
    "  weight: string | null;",
    "  color: string | null;",
    "  originalText: string;",
    "  updatedBy: string | null;",
    "};",
    "",
    "// Insert or update the one row for (page, element path). On update the stored",
    "// original_text is kept — the first capture is the truth a reset returns to.",
    "export async function upsertOverride(input: UpsertOverrideInput): Promise<ContentOverride | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into content_overrides (page, element_path, text, size, weight, color, original_text, updated_by)",
    "      values (",
    "        ${input.page}, ${input.elementPath}, ${input.text}, ${input.size},",
    "        ${input.weight}, ${input.color}, ${input.originalText}, ${input.updatedBy}",
    "      )",
    "      on conflict (page, element_path) do update set",
    "        text = excluded.text,",
    "        size = excluded.size,",
    "        weight = excluded.weight,",
    "        color = excluded.color,",
    "        updated_by = excluded.updated_by,",
    "        updated_at = now()",
    "      returning id, page, element_path, text, size, weight, color, original_text, updated_at`;",
    "    return rows[0] ? rowToOverride(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Remove one stored edit (idempotent — removing an already-clean element is ok).",
    "export async function deleteOverride(page: string, elementPath: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from content_overrides where page = ${page} and element_path = ${elementPath}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function contentEditEnabled(): boolean {",
    '  return process.env.FEATURE_CONTENT_EDIT !== "false";',
    "}"
  ]);
}

// ---- src/app/api/content-overrides/route.ts (read public, write admin) ------

function overridesApiFile(): GeneratedModuleFile {
  return file("src/app/api/content-overrides/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    "import {",
    "  MAX_TEXT_LENGTH,",
    "  OVERRIDE_COLORS,",
    "  OVERRIDE_SIZES,",
    "  OVERRIDE_WEIGHTS,",
    "  contentEditEnabled,",
    "  deleteOverride,",
    "  isValidElementPath,",
    "  listOverrides,",
    "  normalizePage,",
    "  upsertOverride",
    '} from "@/lib/db/content-overrides";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    'const NO_STORE = { "Cache-Control": "no-store" };',
    "",
    "// Reading is public on purpose: stored overrides ARE the page's content, so",
    "// every visitor needs them to render what the owner published. canEdit is",
    "// decided HERE from the server session role — the client never asserts it.",
    "export async function GET(request: Request) {",
    "  if (!contentEditEnabled()) {",
    "    return NextResponse.json({ ok: true, enabled: false, canEdit: false, overrides: [] }, { headers: NO_STORE });",
    "  }",
    "  const url = new URL(request.url);",
    '  const page = normalizePage(url.searchParams.get("page") || "");',
    '  if (!page) return NextResponse.json({ ok: false, message: "A page path is required." }, { status: 400 });',
    "  const user = await getCurrentUser();",
    "  const overrides = await listOverrides(page);",
    "  return NextResponse.json(",
    "    { ok: true, enabled: true, canEdit: canAccessAdmin(user?.role), overrides },",
    "    { headers: NO_STORE }",
    "  );",
    "}",
    "",
    "function tokenOrNull(value: unknown, allowed: string[]): string | null {",
    '  return typeof value === "string" && allowed.includes(value) ? value : null;',
    "}",
    "",
    "// Save an edit — owners and admins only, enforced on the server.",
    "export async function POST(request: Request) {",
    '  if (!contentEditEnabled()) return NextResponse.json({ ok: false, message: "Visual editing is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Owners and admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const page = normalizePage(typeof body.page === "string" ? body.page : "");',
    '  if (!page) return NextResponse.json({ ok: false, message: "A page path is required." }, { status: 400 });',
    '  const elementPath = typeof body.elementPath === "string" ? body.elementPath : "";',
    '  if (!isValidElementPath(elementPath)) return NextResponse.json({ ok: false, message: "That element cannot be edited." }, { status: 400 });',
    '  const text = typeof body.text === "string" ? body.text.slice(0, MAX_TEXT_LENGTH) : null;',
    "  const size = tokenOrNull(body.size, OVERRIDE_SIZES);",
    "  const weight = tokenOrNull(body.weight, OVERRIDE_WEIGHTS);",
    "  const color = tokenOrNull(body.color, OVERRIDE_COLORS);",
    "  if (text == null && !size && !weight && !color) {",
    '    return NextResponse.json({ ok: false, message: "Nothing changed — the text matches the original and no style is set." }, { status: 400 });',
    "  }",
    '  const originalText = typeof body.originalText === "string" ? body.originalText.slice(0, MAX_TEXT_LENGTH) : "";',
    "  const override = await upsertOverride({",
    "    page,",
    "    elementPath,",
    "    text,",
    "    size,",
    "    weight,",
    "    color,",
    "    originalText,",
    "    updatedBy: user.id ? String(user.id) : null",
    "  });",
    '  if (!override) return NextResponse.json({ ok: false, message: "Connect a database to keep edits." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, override });",
    "}",
    "",
    "// Remove an edit (restore the original) — owners and admins only.",
    "export async function DELETE(request: Request) {",
    '  if (!contentEditEnabled()) return NextResponse.json({ ok: false, message: "Visual editing is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Owners and admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const page = normalizePage(typeof body.page === "string" ? body.page : "");',
    '  const elementPath = typeof body.elementPath === "string" ? body.elementPath : "";',
    "  if (!page || !isValidElementPath(elementPath)) {",
    '    return NextResponse.json({ ok: false, message: "A page path and element path are required." }, { status: 400 });',
    "  }",
    "  const removed = await deleteOverride(page, elementPath);",
    '  if (!removed) return NextResponse.json({ ok: false, message: "Connect a database to manage edits." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/template.tsx (the collision-free every-page mount) --------------

function templateFile(): GeneratedModuleFile {
  return file("src/app/template.tsx", [
    'import { ContentEditRuntime } from "@/components/content-edit/runtime";',
    "",
    "// Root template: wraps every route inside the root layout, so the content-edit",
    "// runtime rides along on every page without the module touching any base file.",
    "// Templates remount per navigation — exactly what the runtime wants, since it",
    "// re-fetches and re-applies this page's overrides on each route change.",
    "export default function RootTemplate({ children }: { children: React.ReactNode }) {",
    "  return (",
    "    <>",
    "      {children}",
    "      <ContentEditRuntime />",
    "    </>",
    "  );",
    "}"
  ]);
}

// ---- src/components/content-edit/runtime.tsx (apply + click-to-edit) --------

function runtimeFile(): GeneratedModuleFile {
  return file("src/components/content-edit/runtime.tsx", [
    '"use client";',
    "",
    'import { useCallback, useEffect, useRef, useState } from "react";',
    'import { usePathname } from "next/navigation";',
    "",
    "// The visual-editing runtime. For every visitor it fetches this page's stored",
    "// overrides and applies them to the DOM (text via textContent — markup can",
    "// never be injected — and style tokens via data-ce-* attributes). For owners",
    "// and admins ONLY (the server says so via canEdit) it also renders the Edit",
    "// mode toggle: click any text to edit it in place, style it with the token",
    "// toolbar, and save. Anonymous visitors get zero edit affordances — the",
    "// toggle and toolbar exist only after the server answers canEdit: true.",
    "",
    "type Override = {",
    "  page: string;",
    "  elementPath: string;",
    "  text: string | null;",
    "  size: string | null;",
    "  weight: string | null;",
    "  color: string | null;",
    "  originalText: string;",
    "};",
    "",
    "type Selected = {",
    "  el: HTMLElement;",
    "  path: string;",
    "  beforeText: string;",
    "  beforeSize: string;",
    "  beforeWeight: string;",
    "  beforeColor: string;",
    "};",
    "",
    '// Token choices. An empty value means "back to the stylesheet default" —',
    "// picking it removes the attribute instead of writing a value.",
    'const SIZE_CHOICES: Array<[string, string]> = [["s", "S"], ["", "M"], ["l", "L"], ["xl", "XL"]];',
    'const WEIGHT_CHOICES: Array<[string, string]> = [["", "Auto"], ["normal", "Normal"], ["semibold", "Semibold"], ["bold", "Bold"]];',
    'const COLOR_CHOICES: Array<[string, string]> = [["", "Auto"], ["ink", "Ink"], ["muted", "Muted"], ["accent", "Accent"]];',
    "",
    "const SKIP_TAGS = new Set([",
    '  "SCRIPT", "STYLE", "NOSCRIPT", "TEMPLATE", "INPUT", "TEXTAREA", "SELECT",',
    '  "OPTION", "IFRAME", "CANVAS", "VIDEO", "AUDIO", "SVG", "PATH", "HTML", "HEAD", "BODY"',
    "]);",
    "",
    "// The runtime's own stylesheet: token attributes map to the app's theme",
    "// variables (--ink/--muted/--accent), with --ce-* hooks so a host app can",
    "// supply its own palette; sizes are em-relative so they scale any element.",
    "const EDITOR_CSS = [",
    '  \'[data-ce-size="s"] { font-size: calc(var(--ce-size-base, 1em) * .85); }\',',
    '  \'[data-ce-size="l"] { font-size: calc(var(--ce-size-base, 1em) * 1.15); }\',',
    '  \'[data-ce-size="xl"] { font-size: calc(var(--ce-size-base, 1em) * 1.35); }\',',
    '  \'[data-ce-weight="normal"] { font-weight: 400; }\',',
    '  \'[data-ce-weight="semibold"] { font-weight: 600; }\',',
    '  \'[data-ce-weight="bold"] { font-weight: 700; }\',',
    '  \'[data-ce-color="ink"] { color: var(--ce-ink, var(--ink, inherit)); }\',',
    '  \'[data-ce-color="muted"] { color: var(--ce-muted, var(--muted, inherit)); }\',',
    '  \'[data-ce-color="accent"] { color: var(--ce-accent, var(--accent, inherit)); }\',',
    "  'html.ce-editing :where(h1,h2,h3,h4,h5,h6,p,li,a,button,span,strong,em,b,i,small,blockquote,figcaption,label,legend,dt,dd,th,td,summary):not([data-ce-ui] *):hover { outline: 2px dashed var(--ce-accent, var(--accent, #888)); outline-offset: 2px; cursor: text; }',",
    "  '[data-ce-selected] { outline: 2px solid var(--ce-accent, var(--accent, #888)) !important; outline-offset: 2px; }',",
    "  '.ce-toggle { position: fixed; right: 16px; bottom: 16px; z-index: 2147483000; min-height: 44px; padding: 0 18px; border-radius: 999px; border: 1px solid var(--ce-line, var(--line, #d0d0d0)); background: var(--ce-accent, var(--accent, #14453d)); color: var(--ce-accent-ink, var(--accent-ink, #ffffff)); font: inherit; font-weight: 700; cursor: pointer; box-shadow: 0 6px 18px rgba(0, 0, 0, .18); }',",
    "  '.ce-toggle[aria-pressed=\"true\"] { background: var(--ce-ink, var(--ink, #111111)); color: var(--ce-paper, var(--paper, #ffffff)); }',",
    "  '.ce-hint, .ce-status { position: fixed; right: 16px; bottom: 72px; z-index: 2147483000; margin: 0; max-width: 280px; padding: 8px 12px; border: 1px solid var(--ce-line, var(--line, #d0d0d0)); border-radius: 10px; background: var(--ce-panel, var(--panel, #ffffff)); color: var(--ce-ink, var(--ink, #111111)); font-size: .85rem; box-shadow: 0 6px 18px rgba(0, 0, 0, .12); }',",
    "  '.ce-status.ce-error { border-color: #b3372a; color: #b3372a; }',",
    "  '.ce-toolbar { position: fixed; z-index: 2147483001; width: 280px; padding: 10px; border: 1px solid var(--ce-line, var(--line, #d0d0d0)); border-radius: 12px; background: var(--ce-panel, var(--panel, #ffffff)); color: var(--ce-ink, var(--ink, #111111)); box-shadow: 0 10px 30px rgba(0, 0, 0, .22); display: grid; gap: 6px; font-size: .85rem; }',",
    "  '.ce-row { display: flex; align-items: center; gap: 4px; flex-wrap: wrap; }',",
    "  '.ce-row > span { width: 52px; color: var(--ce-muted, var(--muted, #666666)); font-size: .72rem; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; }',",
    "  '.ce-row button { min-height: 30px; padding: 0 10px; border: 1px solid var(--ce-line, var(--line, #d0d0d0)); border-radius: 8px; background: var(--ce-paper, var(--paper, #f7f7f7)); color: var(--ce-ink, var(--ink, #111111)); font: inherit; font-size: .8rem; cursor: pointer; }',",
    "  '.ce-row button[aria-pressed=\"true\"] { background: var(--ce-accent, var(--accent, #14453d)); color: var(--ce-accent-ink, var(--accent-ink, #ffffff)); border-color: var(--ce-accent, var(--accent, #14453d)); }',",
    "  '.ce-actions { display: flex; gap: 6px; margin-top: 2px; }',",
    "  '.ce-actions button { flex: 1; min-height: 34px; border: 1px solid var(--ce-line, var(--line, #d0d0d0)); border-radius: 8px; background: var(--ce-paper, var(--paper, #f7f7f7)); color: var(--ce-ink, var(--ink, #111111)); font: inherit; font-size: .82rem; cursor: pointer; }',",
    "  '.ce-actions button.ce-save { background: var(--ce-accent, var(--accent, #14453d)); color: var(--ce-accent-ink, var(--accent-ink, #ffffff)); border-color: var(--ce-accent, var(--accent, #14453d)); font-weight: 700; }',",
    "  '.ce-manage { color: var(--ce-muted, var(--muted, #666666)); font-size: .75rem; }'",
    '].join("\\n");',
    "",
    "// The stable path for an element: tag:nth-of-type(i) segments from <body>",
    "// down. Type-position survives text edits and class churn; the admin page",
    "// covers the rare stranded path after a structural redesign.",
    "function pathFor(el: Element): string | null {",
    "  const segments: string[] = [];",
    "  let node: Element | null = el;",
    "  while (node && node !== document.body) {",
    "    const tag = node.tagName.toLowerCase();",
    "    if (!/^[a-z][a-z0-9-]*$/.test(tag)) return null;",
    "    let index = 1;",
    "    let sibling = node.previousElementSibling;",
    "    while (sibling) {",
    "      if (sibling.tagName === node.tagName) index += 1;",
    "      sibling = sibling.previousElementSibling;",
    "    }",
    "    segments.unshift(`${tag}:nth-of-type(${index})`);",
    "    node = node.parentElement;",
    "  }",
    "  if (!node || segments.length === 0 || segments.length > 40) return null;",
    '  return segments.join(">");',
    "}",
    "",
    "function resolvePath(path: string): HTMLElement | null {",
    "  try {",
    '    const el = document.body.querySelector(":scope>" + path);',
    "    return el instanceof HTMLElement ? el : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Editable = the element itself holds visible text (a direct non-empty text",
    "// node), not just text somewhere in its subtree — that keeps the click target",
    "// on the deepest element that owns the words.",
    "function hasOwnText(el: Element): boolean {",
    "  if (SKIP_TAGS.has(el.tagName)) return false;",
    "  return Array.from(el.childNodes).some(",
    '    (child) => child.nodeType === Node.TEXT_NODE && (child.textContent || "").trim().length > 0',
    "  );",
    "}",
    "",
    "function editableFrom(start: Element): HTMLElement | null {",
    '  if (start.closest("[data-ce-ui]")) return null;',
    "  let node: Element | null = start;",
    "  while (node && node !== document.body) {",
    "    if (node instanceof HTMLElement && hasOwnText(node)) return node;",
    "    node = node.parentElement;",
    "  }",
    "  return null;",
    "}",
    "",
    "function syncAttr(el: Element, name: string, value: string | null) {",
    "  if (value) {",
    "    if (el.getAttribute(name) !== value) el.setAttribute(name, value);",
    "  } else if (el.hasAttribute(name)) {",
    "    el.removeAttribute(name);",
    "  }",
    "}",
    "",
    "// Size tokens scale the element's OWN rendered size (an em would scale the",
    '// parent\'s — "XL" on a large heading must grow it, not shrink it). Measure',
    "// the pre-token size once and expose it to the CSS calc() via an inline var.",
    "function ensureSizeBase(el: HTMLElement) {",
    '  if (el.style.getPropertyValue("--ce-size-base")) return;',
    '  const token = el.getAttribute("data-ce-size");',
    '  if (token) el.removeAttribute("data-ce-size");',
    '  el.style.setProperty("--ce-size-base", getComputedStyle(el).fontSize);',
    '  if (token) el.setAttribute("data-ce-size", token);',
    "}",
    "",
    "// Apply a size token (or clear it) with its measured base kept in step.",
    "function syncSize(el: HTMLElement, value: string | null) {",
    "  if (value) ensureSizeBase(el);",
    '  syncAttr(el, "data-ce-size", value);',
    '  if (!value) el.style.removeProperty("--ce-size-base");',
    "}",
    "",
    "export function ContentEditRuntime() {",
    "  const pathname = usePathname();",
    "  const [canEdit, setCanEdit] = useState(false);",
    "  const [editMode, setEditMode] = useState(false);",
    "  const [selected, setSelected] = useState<Selected | null>(null);",
    '  const [draft, setDraft] = useState({ size: "", weight: "", color: "" });',
    '  const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "  const [toolbarPos, setToolbarPos] = useState({ top: 8, left: 8 });",
    "  const overridesRef = useRef<Map<string, Override>>(new Map());",
    "  // Original text per path, captured BEFORE any override or edit touches the",
    "  // element — reset restores this, and the first save records it server-side.",
    "  const originalsRef = useRef<Map<string, string>>(new Map());",
    "  const selectedRef = useRef<Selected | null>(null);",
    "",
    "  useEffect(() => {",
    "    selectedRef.current = selected;",
    "  }, [selected]);",
    "",
    "  const applyAll = useCallback(() => {",
    "    overridesRef.current.forEach((override) => {",
    "      const el = resolvePath(override.elementPath);",
    '      if (!el || el.closest("[data-ce-ui]")) return;',
    "      if (!originalsRef.current.has(override.elementPath)) {",
    '        originalsRef.current.set(override.elementPath, el.textContent || "");',
    "      }",
    "      // Never touch the element mid-edit — the live draft wins until saved.",
    "      if (selectedRef.current && selectedRef.current.el === el) return;",
    "      if (override.text != null && el.textContent !== override.text) el.textContent = override.text;",
    "      syncSize(el, override.size);",
    '      syncAttr(el, "data-ce-weight", override.weight);',
    '      syncAttr(el, "data-ce-color", override.color);',
    "    });",
    "  }, []);",
    "",
    "  // Fetch this page's overrides + the server's canEdit verdict, then apply.",
    "  // A few delayed re-applies catch content that hydrates in after us.",
    "  useEffect(() => {",
    "    let cancelled = false;",
    "    const timers: Array<ReturnType<typeof setTimeout>> = [];",
    '    fetch("/api/content-overrides?page=" + encodeURIComponent(pathname || "/"), { cache: "no-store" })',
    "      .then((res) => (res.ok ? res.json() : null))",
    "      .then((data) => {",
    "        if (cancelled || !data || data.ok !== true || data.enabled !== true) return;",
    "        setCanEdit(data.canEdit === true);",
    "        const map = new Map<string, Override>();",
    "        (Array.isArray(data.overrides) ? data.overrides : []).forEach((entry: Override) => {",
    "          if (entry && typeof entry.elementPath === \"string\") map.set(entry.elementPath, entry);",
    "        });",
    "        overridesRef.current = map;",
    "        applyAll();",
    "        [150, 400, 1000, 2200].forEach((delay) => timers.push(setTimeout(applyAll, delay)));",
    "      })",
    "      .catch(() => {",
    "        // The page must render fine even if the overrides fetch fails.",
    "      });",
    "    return () => {",
    "      cancelled = true;",
    "      timers.forEach(clearTimeout);",
    "    };",
    "  }, [pathname, applyAll]);",
    "",
    "  useEffect(() => {",
    '    document.documentElement.classList.toggle("ce-editing", editMode);',
    '    return () => document.documentElement.classList.remove("ce-editing");',
    "  }, [editMode]);",
    "",
    "  // Deselect, optionally restoring the element to how it looked beforehand.",
    "  const clearSelection = useCallback((restore: boolean) => {",
    "    const current = selectedRef.current;",
    "    if (!current) return;",
    '    current.el.removeAttribute("contenteditable");',
    '    current.el.removeAttribute("data-ce-selected");',
    "    if (restore) {",
    "      current.el.textContent = current.beforeText;",
    "      syncSize(current.el, current.beforeSize || null);",
    '      syncAttr(current.el, "data-ce-weight", current.beforeWeight || null);',
    '      syncAttr(current.el, "data-ce-color", current.beforeColor || null);',
    "    }",
    "    setSelected(null);",
    '    setStatus("idle");',
    '    setMessage("");',
    "  }, []);",
    "",
    "  const selectElement = useCallback(",
    "    (el: HTMLElement) => {",
    "      const path = pathFor(el);",
    "      if (!path) {",
    '        setStatus("error");',
    '        setMessage("This element cannot be edited.");',
    "        return;",
    "      }",
    "      clearSelection(true);",
    "      if (!originalsRef.current.has(path)) {",
    '        originalsRef.current.set(path, el.textContent || "");',
    "      }",
    "      const next: Selected = {",
    "        el,",
    "        path,",
    '        beforeText: el.textContent || "",',
    '        beforeSize: el.getAttribute("data-ce-size") || "",',
    '        beforeWeight: el.getAttribute("data-ce-weight") || "",',
    '        beforeColor: el.getAttribute("data-ce-color") || ""',
    "      };",
    '      el.setAttribute("data-ce-selected", "true");',
    '      el.setAttribute("contenteditable", "plaintext-only");',
    "      // Browsers without plaintext-only fall back to a plain contenteditable;",
    "      // saves still persist plain text because we read textContent.",
    '      if (!el.isContentEditable) el.setAttribute("contenteditable", "true");',
    "      const rect = el.getBoundingClientRect();",
    "      setToolbarPos({",
    "        top: Math.min(Math.max(8, rect.bottom + 10), Math.max(8, window.innerHeight - 200)),",
    "        left: Math.min(Math.max(8, rect.left), Math.max(8, window.innerWidth - 296))",
    "      });",
    "      setDraft({ size: next.beforeSize, weight: next.beforeWeight, color: next.beforeColor });",
    "      setSelected(next);",
    '      setStatus("idle");',
    '      setMessage("");',
    "      el.focus();",
    "    },",
    "    [clearSelection]",
    "  );",
    "",
    "  const save = useCallback(async () => {",
    "    const current = selectedRef.current;",
    "    if (!current) return;",
    "    const original = originalsRef.current.get(current.path) ?? current.beforeText;",
    '    const text = current.el.textContent || "";',
    '    const size = current.el.getAttribute("data-ce-size");',
    '    const weight = current.el.getAttribute("data-ce-weight");',
    '    const color = current.el.getAttribute("data-ce-color");',
    '    const page = pathname || "/";',
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    "      if (text === original && !size && !weight && !color) {",
    "        // Everything matches the original again — drop the stored row.",
    '        const res = await fetch("/api/content-overrides", {',
    '          method: "DELETE",',
    '          headers: { "Content-Type": "application/json" },',
    "          body: JSON.stringify({ page, elementPath: current.path })",
    "        });",
    '        if (!res.ok) throw new Error("delete failed");',
    "        overridesRef.current.delete(current.path);",
    "      } else {",
    '        const res = await fetch("/api/content-overrides", {',
    '          method: "POST",',
    '          headers: { "Content-Type": "application/json" },',
    "          body: JSON.stringify({",
    "            page,",
    "            elementPath: current.path,",
    "            text: text === original ? null : text,",
    "            size,",
    "            weight,",
    "            color,",
    "            originalText: original",
    "          })",
    "        });",
    "        const data = (await res.json().catch(() => null)) as { ok?: boolean; override?: Override } | null;",
    '        if (!res.ok || !data || data.ok !== true || !data.override) throw new Error("save failed");',
    "        overridesRef.current.set(current.path, data.override);",
    "      }",
    '      current.el.removeAttribute("contenteditable");',
    '      current.el.removeAttribute("data-ce-selected");',
    "      setSelected(null);",
    '      setStatus("saved");',
    '      setMessage("Saved. Everyone sees this now.");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not save. Please try again.");',
    "    }",
    "  }, [pathname]);",
    "",
    "  // Restore the true original (pre-any-override) and remove the stored row.",
    "  const reset = useCallback(async () => {",
    "    const current = selectedRef.current;",
    "    if (!current) return;",
    "    const original = originalsRef.current.get(current.path) ?? current.beforeText;",
    '    setStatus("saving");',
    "    try {",
    '      const res = await fetch("/api/content-overrides", {',
    '        method: "DELETE",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ page: pathname || "/", elementPath: current.path })',
    "      });",
    '      if (!res.ok) throw new Error("delete failed");',
    "      overridesRef.current.delete(current.path);",
    "      current.el.textContent = original;",
    "      syncSize(current.el, null);",
    '      current.el.removeAttribute("data-ce-weight");',
    '      current.el.removeAttribute("data-ce-color");',
    '      current.el.removeAttribute("contenteditable");',
    '      current.el.removeAttribute("data-ce-selected");',
    "      setSelected(null);",
    '      setStatus("saved");',
    '      setMessage("Restored the original.");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reset. Please try again.");',
    "    }",
    "  }, [pathname]);",
    "",
    "  // Style tokens preview live on the element itself, so what the owner sees",
    "  // while choosing is exactly what saving will persist.",
    '  const setStyle = useCallback((kind: "size" | "weight" | "color", value: string) => {',
    "    const current = selectedRef.current;",
    "    if (!current) return;",
    '    if (kind === "size") syncSize(current.el, value || null);',
    '    else syncAttr(current.el, "data-ce-" + kind, value || null);',
    "    setDraft((prev) => ({ ...prev, [kind]: value }));",
    "  }, []);",
    "",
    "  const toggleEditMode = useCallback(() => {",
    "    if (editMode) clearSelection(true);",
    "    setEditMode(!editMode);",
    '    setStatus("idle");',
    '    setMessage("");',
    "  }, [editMode, clearSelection]);",
    "",
    "  // Edit-mode interaction: capture-phase listeners so clicks select text for",
    "  // editing instead of following links or pressing buttons. Clicks inside the",
    "  // editor UI or the element being edited pass through untouched.",
    "  useEffect(() => {",
    "    if (!editMode) return;",
    "    const onClick = (event: MouseEvent) => {",
    "      const target = event.target;",
    "      if (!(target instanceof Element)) return;",
    '      if (target.closest("[data-ce-ui]")) return;',
    "      const current = selectedRef.current;",
    "      if (current && (target === current.el || current.el.contains(target))) return;",
    "      event.preventDefault();",
    "      event.stopPropagation();",
    "      const el = editableFrom(target);",
    "      if (el) selectElement(el);",
    "    };",
    "    const onKeyDown = (event: KeyboardEvent) => {",
    "      const current = selectedRef.current;",
    '      if (event.key === "Escape") {',
    "        event.preventDefault();",
    "        if (current) clearSelection(true);",
    "        else setEditMode(false);",
    "        return;",
    "      }",
    '      if (event.key === "Enter" && current && event.target instanceof Node && current.el.contains(event.target)) {',
    "        event.preventDefault();",
    "        void save();",
    "      }",
    "    };",
    '    document.addEventListener("click", onClick, true);',
    '    document.addEventListener("keydown", onKeyDown, true);',
    "    return () => {",
    '      document.removeEventListener("click", onClick, true);',
    '      document.removeEventListener("keydown", onKeyDown, true);',
    "    };",
    "  }, [editMode, selectElement, clearSelection, save]);",
    "",
    "  return (",
    "    <>",
    "      <style>{EDITOR_CSS}</style>",
    "      {canEdit ? (",
    '        <div data-ce-ui="true">',
    "          <button",
    '            className="ce-toggle"',
    '            type="button"',
    "            aria-pressed={editMode}",
    "            onClick={toggleEditMode}",
    "          >",
    '            {editMode ? "Done editing" : "Edit page"}',
    "          </button>",
    "          {editMode && !selected && !message ? (",
    '            <p className="ce-hint" role="status">Click any text to edit it.</p>',
    "          ) : null}",
    "          {selected ? (",
    "            <div",
    '              className="ce-toolbar"',
    '              role="toolbar"',
    '              aria-label="Text style"',
    "              style={{ top: toolbarPos.top, left: toolbarPos.left }}",
    "            >",
    '              <div className="ce-row">',
    "                <span>Size</span>",
    "                {SIZE_CHOICES.map(([value, label]) => (",
    "                  <button",
    "                    key={label}",
    '                    type="button"',
    "                    aria-pressed={draft.size === value}",
    '                    onClick={() => setStyle("size", value)}',
    "                  >",
    "                    {label}",
    "                  </button>",
    "                ))}",
    "              </div>",
    '              <div className="ce-row">',
    "                <span>Weight</span>",
    "                {WEIGHT_CHOICES.map(([value, label]) => (",
    "                  <button",
    "                    key={label}",
    '                    type="button"',
    "                    aria-pressed={draft.weight === value}",
    '                    onClick={() => setStyle("weight", value)}',
    "                  >",
    "                    {label}",
    "                  </button>",
    "                ))}",
    "              </div>",
    '              <div className="ce-row">',
    "                <span>Color</span>",
    "                {COLOR_CHOICES.map(([value, label]) => (",
    "                  <button",
    "                    key={label}",
    '                    type="button"',
    "                    aria-pressed={draft.color === value}",
    '                    onClick={() => setStyle("color", value)}',
    "                  >",
    "                    {label}",
    "                  </button>",
    "                ))}",
    "              </div>",
    '              <div className="ce-actions">',
    '                <button className="ce-save" type="button" onClick={() => void save()} disabled={status === "saving"}>',
    '                  {status === "saving" ? "Saving…" : "Save"}',
    "                </button>",
    '                <button type="button" onClick={() => void reset()} disabled={status === "saving"}>Reset</button>',
    '                <button type="button" onClick={() => clearSelection(true)} disabled={status === "saving"}>Cancel</button>',
    "              </div>",
    '              <a className="ce-manage" href="/admin/content">All edits on this app</a>',
    "            </div>",
    "          ) : null}",
    "          {message ? (",
    '            <p className={status === "error" ? "ce-status ce-error" : "ce-status"} role="status">{message}</p>',
    "          ) : null}",
    "        </div>",
    "      ) : null}",
    "    </>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin/content/page.tsx (manage every stored edit) --------------

function adminPageFile(): GeneratedModuleFile {
  return file("src/app/admin/content/page.tsx", [
    'import { requireAdminAccess } from "@/lib/auth/session";',
    'import { hasDatabase } from "@/lib/db/client";',
    'import { contentEditEnabled, listAllOverrides, overrideStyleSummary } from "@/lib/db/content-overrides";',
    'import { OverrideDeleteButton } from "./override-delete-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AdminContentPage() {",
    "  if (!contentEditEnabled()) {",
    "    return (",
    '      <main className="shell">',
    "        <h1>Content edits</h1>",
    "        <p>Visual editing is turned off for this app.</p>",
    "      </main>",
    "    );",
    "  }",
    '  await requireAdminAccess("/admin/content");',
    "  const overrides = await listAllOverrides();",
    "  const pages = [...new Set(overrides.map((override) => override.page))];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Content edits</h1>",
    "      <p>Every inline edit made with Edit mode, grouped by page. Removing one restores the original wording and style for everyone.</p>",
    "      {!hasDatabase() ? (",
    '        <p className="note">Connect a database to keep edits — without one, nothing can be saved.</p>',
    "      ) : null}",
    "      {overrides.length === 0 ? (",
    '        <p className="note">No edits yet. Open any page, press Edit page, and click text to change it.</p>',
    "      ) : (",
    "        pages.map((page) => (",
    "          <section key={page}>",
    "            <h2>{page}</h2>",
    '            <section className="panel-list">',
    "              {overrides",
    "                .filter((override) => override.page === page)",
    "                .map((override) => (",
    '                  <article className="wide-card" key={override.elementPath}>',
    "                    <span>{override.elementPath}</span>",
    "                    <strong>{override.text ?? override.originalText}</strong>",
    "                    {override.text != null ? (",
    '                      <p className="note">Original: {override.originalText || "(empty)"}</p>',
    "                    ) : null}",
    '                    <p className="note">{overrideStyleSummary(override)}</p>',
    "                    <OverrideDeleteButton page={override.page} elementPath={override.elementPath} />",
    "                  </article>",
    "                ))}",
    "            </section>",
    "          </section>",
    "        ))",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin/content/override-delete-button.tsx -----------------------

function deleteButtonFile(): GeneratedModuleFile {
  return file("src/app/admin/content/override-delete-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function OverrideDeleteButton({ page, elementPath }: { page: string; elementPath: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "confirm" | "working" | "error">("idle");',
    "",
    "  async function remove() {",
    '    setStatus("working");',
    "    try {",
    '      const res = await fetch("/api/content-overrides", {',
    '        method: "DELETE",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ page, elementPath })",
    "      });",
    '      if (!res.ok) throw new Error("delete failed");',
    "      router.refresh();",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    "    }",
    "  }",
    "",
    '  if (status === "confirm" || status === "working") {',
    "    return (",
    '      <span className="action-row">',
    '        <button className="button" type="button" onClick={() => void remove()} disabled={status === "working"}>',
    '          {status === "working" ? "Removing…" : "Yes, restore the original"}',
    "        </button>",
    '        <button className="button" type="button" onClick={() => setStatus("idle")} disabled={status === "working"}>',
    "          Keep the edit",
    "        </button>",
    "      </span>",
    "    );",
    "  }",
    "  return (",
    '    <span className="action-row">',
    '      <button className="button" type="button" onClick={() => setStatus("confirm")}>Remove edit</button>',
    '      {status === "error" ? <span className="note" role="alert">Could not remove it. Try again.</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

export const contentEditModule: AppModule = {
  slug: "content-edit",
  name: "Visual Content Editing",
  tier: "optional",
  featureFlagEnv: "FEATURE_CONTENT_EDIT",
  files: () => [
    overridesLibFile(),
    overridesApiFile(),
    templateFile(),
    runtimeFile(),
    adminPageFile(),
    deleteButtonFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists content_overrides (",
      "  id uuid primary key default gen_random_uuid(),",
      "  page text not null,",
      "  element_path text not null,",
      "  text text,",
      "  size text,",
      "  weight text,",
      "  color text,",
      "  original_text text not null default '',",
      "  updated_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now(),",
      "  unique (page, element_path)",
      ");",
      "create index if not exists content_overrides_page_idx on content_overrides (page);"
    ].join("\n"),
  envLines: () => [
    "",
    "# Visual content editing — owner/admin click-to-edit for page text. Set to false to switch it off.",
    "FEATURE_CONTENT_EDIT=true"
  ]
};
