// content-publishing-scheduler — plan, schedule, publish, and repurpose content
// across creator channels from one workflow. Ported from Snip's real smart
// scheduler (emergent/backend/services/scheduler_service.py, routes/
// scheduler_routes.py + auto_scheduler_routes.py, services/
// multi_platform_publisher.py, frontend/src/pages/AutoSchedulerPage.js):
//   - the scheduled_post model (id, user_id, content_type [clip/remix/repurpose],
//     content_id, platform, title, scheduled_live_time, scheduled_upload_time,
//     upload_buffer_minutes, status [scheduled/uploading/processing/live/failed/
//     cancelled], created_at/updated_at) — schedule_post derives the upload time
//     by subtracting the platform UPLOAD_BUFFERS from the live time.
//   - UPLOAD_BUFFERS + MIN_POST_GAP per platform, and the _check_conflict window
//     (target ± min_gap on the same platform) that rejects too-close posts (409).
//   - schedule_batch: stagger one piece of content across platforms, finding the
//     next available slot per platform (_find_next_available_slot).
//   - get_schedule (date-range filtered, live-time ascending), get_queue_stats
//     (totals by status + by platform + next_post), reschedule_post (drag-and-drop
//     to a new live time, conflict-checked excluding self), cancel_post.
//   - multi_platform_publisher PLATFORM_LIMITS + get_connected_platforms (which
//     channels have owner keys configured) + optimize_for_platform (truncate
//     title/description, format hashtags per channel).
//   - the auto-scheduler settings + suggestion review queue (AutoSchedulerPage.js):
//     enabled/mode(auto|review)/trigger, per-platform enabled+max_per_day, posting
//     time window, and pending suggestions the creator approves/rejects one-click.
// Generalized off Snip's neon branding into plain copy so it drops into any app.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_SCHEDULER); customers plan + schedule + review their
// own queue (rows scoped by user id), admins can act across the workspace.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/scheduler.ts (model + queries, ported from scheduler_service.py)

function schedulerLibFile(): GeneratedModuleFile {
  return file("src/lib/db/scheduler.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A scheduled post, ported from scheduler_service.py schedule_post. Content is",
    "// scheduled at a LIVE time; the UPLOAD time is derived by subtracting the",
    "// platform's upload buffer so processing finishes right as it should go live.",
    "export type ScheduledPost = {",
    "  id: string;",
    "  userId: string | null;",
    "  contentType: string; // clip, remix, repurpose",
    "  contentId: string;",
    "  platform: string;",
    "  title: string;",
    "  scheduledLiveTime: string;",
    "  scheduledUploadTime: string;",
    "  uploadBufferMinutes: number;",
    "  status: string; // scheduled, uploading, processing, live, failed, cancelled",
    "  createdAt: string;",
    "  updatedAt: string;",
    "};",
    "",
    "// The channels content can be published to, ported from multi_platform_publisher",
    "// Platform + the scheduler's per-platform buffer/gap maps.",
    "export const PLATFORMS = [",
    '  "youtube",',
    '  "youtube_shorts",',
    '  "tiktok",',
    '  "instagram_reels",',
    '  "instagram_story"',
    "] as const;",
    "",
    "export const CONTENT_TYPES = [\"clip\", \"remix\", \"repurpose\"] as const;",
    "",
    "// Human labels, ported from AutoSchedulerPage platformConfig.",
    "export const PLATFORM_LABELS: Record<string, string> = {",
    '  youtube: "YouTube",',
    '  youtube_shorts: "YT Shorts",',
    '  tiktok: "TikTok",',
    '  instagram_reels: "IG Reels",',
    '  instagram_story: "IG Story"',
    "};",
    "",
    "// Platform-specific upload processing delays (minutes), ported verbatim from",
    "// scheduler_service.py UPLOAD_BUFFERS.",
    "export const UPLOAD_BUFFERS: Record<string, number> = {",
    "  youtube: 15,",
    "  youtube_shorts: 10,",
    "  tiktok: 5,",
    "  instagram_reels: 3,",
    "  instagram_story: 2",
    "};",
    "",
    "// Minimum gap between posts on the same platform (minutes), ported verbatim from",
    "// scheduler_service.py MIN_POST_GAP.",
    "export const MIN_POST_GAP: Record<string, number> = {",
    "  youtube: 240,",
    "  youtube_shorts: 120,",
    "  tiktok: 90,",
    "  instagram_reels: 120,",
    "  instagram_story: 30",
    "};",
    "",
    "export function uploadBufferFor(platform: string): number {",
    "  return UPLOAD_BUFFERS[platform] ?? 5;",
    "}",
    "",
    "export function minGapFor(platform: string): number {",
    "  return MIN_POST_GAP[platform] ?? 60;",
    "}",
    "",
    "export function platformLabel(platform: string): string {",
    "  return PLATFORM_LABELS[platform] || platform;",
    "}",
    "",
    "export type ScheduleFilters = {",
    "  startDate?: string;",
    "  endDate?: string;",
    "  status?: string;",
    "  limit?: number;",
    "};",
    "",
    "const fallbackPosts: ScheduledPost[] = [",
    "  {",
    '    id: "sample-1",',
    "    userId: null,",
    '    contentType: "clip",',
    '    contentId: "clip-001",',
    '    platform: "youtube_shorts",',
    '    title: "Top 3 takeaways from this week",',
    '    scheduledLiveTime: "2025-06-02T15:00:00.000Z",',
    '    scheduledUploadTime: "2025-06-02T14:50:00.000Z",',
    "    uploadBufferMinutes: 10,",
    '    status: "scheduled",',
    '    createdAt: "2025-06-01T00:00:00.000Z",',
    '    updatedAt: "2025-06-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-2",',
    "    userId: null,",
    '    contentType: "repurpose",',
    '    contentId: "clip-001",',
    '    platform: "tiktok",',
    '    title: "Top 3 takeaways from this week",',
    '    scheduledLiveTime: "2025-06-02T18:00:00.000Z",',
    '    scheduledUploadTime: "2025-06-02T17:55:00.000Z",',
    "    uploadBufferMinutes: 5,",
    '    status: "scheduled",',
    '    createdAt: "2025-06-01T00:00:00.000Z",',
    '    updatedAt: "2025-06-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToPost(row: Record<string, unknown>): ScheduledPost {",
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    contentType: String(row.content_type || "clip"),',
    '    contentId: String(row.content_id || ""),',
    '    platform: String(row.platform || ""),',
    '    title: String(row.title || ""),',
    '    scheduledLiveTime: row.scheduled_live_time ? String(row.scheduled_live_time) : "",',
    '    scheduledUploadTime: row.scheduled_upload_time ? String(row.scheduled_upload_time) : "",',
    "    uploadBufferMinutes: Number(row.upload_buffer_minutes || 0),",
    '    status: String(row.status || "scheduled"),',
    '    createdAt: row.created_at ? String(row.created_at) : "",',
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "// Derive the upload time from a live time, ported from schedule_post: live minus",
    "// the platform's upload buffer.",
    "export function uploadTimeFor(liveIso: string, platform: string): string {",
    "  const live = new Date(liveIso);",
    "  const buffer = uploadBufferFor(platform);",
    "  return new Date(live.getTime() - buffer * 60_000).toISOString();",
    "}",
    "",
    "export type ScheduleConflict = {",
    "  status: \"conflict\";",
    "  message: string;",
    "  conflictingPost: { id: string; title: string; scheduledLiveTime: string };",
    "};",
    "",
    "// Check if a post would conflict with an existing one on the same platform,",
    "// ported from scheduler_service.py _check_conflict / _check_conflict_excluding:",
    "// any scheduled post within ± MIN_POST_GAP minutes of the target time collides.",
    "export async function checkConflict(",
    "  userId: string,",
    "  platform: string,",
    "  targetIso: string,",
    "  excludeId?: string",
    "): Promise<ScheduleConflict | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const gap = minGapFor(platform);",
    "    const target = new Date(targetIso);",
    "    const windowStart = new Date(target.getTime() - gap * 60_000).toISOString();",
    "    const windowEnd = new Date(target.getTime() + gap * 60_000).toISOString();",
    "    const exclude = excludeId || null;",
    "    const rows = await sql`",
    "      select id, title, scheduled_live_time",
    "      from content_publishing_scheduler_posts",
    "      where user_id = ${userId}",
    "        and platform = ${platform}",
    "        and status = 'scheduled'",
    "        and (${exclude}::uuid is null or id <> ${exclude})",
    "        and scheduled_live_time >= ${windowStart}",
    "        and scheduled_live_time <= ${windowEnd}",
    "      limit 1`;",
    "    const row = rows[0];",
    "    if (!row) return null;",
    "    return {",
    '      status: "conflict",',
    "      message: `Too close to an existing post on ${platformLabel(platform)}. Minimum gap is ${gap} minutes.`,",
    "      conflictingPost: {",
    "        id: String(row.id),",
    '        title: String(row.title || ""),',
    '        scheduledLiveTime: row.scheduled_live_time ? String(row.scheduled_live_time) : ""',
    "      }",
    "    };",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SchedulePostInput = {",
    "  userId: string;",
    "  contentType: string;",
    "  contentId: string;",
    "  platform: string;",
    "  scheduledLiveTime: string;",
    "  title?: string;",
    "};",
    "",
    "// Schedule a single post, ported from schedule_post: reject on conflict, else",
    "// store scheduled with a derived upload time.",
    "export async function schedulePost(",
    "  input: SchedulePostInput",
    "): Promise<ScheduledPost | ScheduleConflict | null> {",
    "  if (!hasDatabase()) return null;",
    "  const liveIso = new Date(input.scheduledLiveTime).toISOString();",
    "  const conflict = await checkConflict(input.userId, input.platform, liveIso);",
    "  if (conflict) return conflict;",
    "  const uploadIso = uploadTimeFor(liveIso, input.platform);",
    "  const buffer = uploadBufferFor(input.platform);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into content_publishing_scheduler_posts (",
    "        user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status",
    "      ) values (",
    "        ${input.userId}, ${input.contentType}, ${input.contentId}, ${input.platform},",
    '        ${input.title || ""}, ${liveIso}, ${uploadIso}, ${buffer}, \'scheduled\'',
    "      )",
    "      returning id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status,",
    "        created_at, updated_at`;",
    "    return rows[0] ? rowToPost(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Find the next open slot for a platform after a given time, ported from",
    "// _find_next_available_slot: step forward by MIN_POST_GAP until no conflict.",
    "async function findNextSlot(userId: string, platform: string, afterIso: string): Promise<string> {",
    "  let candidate = new Date(afterIso);",
    "  const gap = minGapFor(platform);",
    "  for (let i = 0; i < 10; i++) {",
    "    const conflict = await checkConflict(userId, platform, candidate.toISOString());",
    "    if (!conflict) return candidate.toISOString();",
    "    candidate = new Date(candidate.getTime() + gap * 60_000);",
    "  }",
    "  return candidate.toISOString();",
    "}",
    "",
    "export type ScheduleBatchInput = {",
    "  userId: string;",
    "  contentType: string;",
    "  contentId: string;",
    "  platforms: string[];",
    "  baseLiveTime: string;",
    "  title?: string;",
    "};",
    "",
    "// Stagger one piece of content across platforms, ported from schedule_batch:",
    "// each platform gets its next available slot, then the cursor jumps +2 hours.",
    "export async function scheduleBatch(input: ScheduleBatchInput): Promise<{ scheduled: ScheduledPost[]; count: number }> {",
    "  const scheduled: ScheduledPost[] = [];",
    "  if (!hasDatabase()) return { scheduled, count: 0 };",
    "  let cursor = new Date(input.baseLiveTime).toISOString();",
    "  for (const platform of input.platforms) {",
    "    const slot = await findNextSlot(input.userId, platform, cursor);",
    "    const created = await schedulePost({",
    "      userId: input.userId,",
    "      contentType: input.contentType,",
    "      contentId: input.contentId,",
    "      platform,",
    "      scheduledLiveTime: slot,",
    "      title: input.title",
    "    });",
    '    if (created && "id" in created) scheduled.push(created);',
    "    // Next platform is staggered by 2 hours from this slot.",
    "    cursor = new Date(new Date(slot).getTime() + 2 * 60 * 60_000).toISOString();",
    "  }",
    "  return { scheduled, count: scheduled.length };",
    "}",
    "",
    "// List a creator's schedule, ported from get_schedule: optional date range on the",
    "// live time, live-time ascending. Always scoped to the owning user.",
    "export async function listSchedule(userId: string, filters: ScheduleFilters = {}): Promise<ScheduledPost[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 200));",
    "  if (!hasDatabase()) {",
    "    return fallbackPosts",
    "      .filter((p) => (!filters.status || p.status === filters.status))",
    "      .filter((p) => (!filters.startDate || p.scheduledLiveTime >= filters.startDate!))",
    "      .filter((p) => (!filters.endDate || p.scheduledLiveTime <= filters.endDate!))",
    "      .sort((a, b) => a.scheduledLiveTime.localeCompare(b.scheduledLiveTime))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const start = filters.startDate || null;",
    "    const end = filters.endDate || null;",
    "    const status = filters.status || null;",
    "    const rows = await sql`",
    "      select id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status,",
    "        created_at, updated_at",
    "      from content_publishing_scheduler_posts",
    "      where user_id = ${userId}",
    "        and (${status}::text is null or status = ${status})",
    "        and (${start}::text is null or scheduled_live_time >= ${start})",
    "        and (${end}::text is null or scheduled_live_time <= ${end})",
    "      order by scheduled_live_time asc",
    "      limit ${limit}`;",
    "    return rows.map(rowToPost);",
    "  } catch {",
    "    return fallbackPosts.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getPost(id: string, userId: string): Promise<ScheduledPost | null> {",
    "  if (!hasDatabase()) return fallbackPosts.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status,",
    "        created_at, updated_at",
    "      from content_publishing_scheduler_posts",
    "      where id = ${id} and user_id = ${userId} limit 1`;",
    "    return rows[0] ? rowToPost(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Reschedule a post to a new live time (drag-and-drop), ported from",
    "// reschedule_post: conflict-check excluding self, re-derive the upload time.",
    "export async function reschedulePost(",
    "  id: string,",
    "  userId: string,",
    "  newLiveTime: string",
    "): Promise<ScheduledPost | ScheduleConflict | null> {",
    "  if (!hasDatabase()) return null;",
    "  const existing = await getPost(id, userId);",
    '  if (!existing || existing.status !== "scheduled") return null;',
    "  const liveIso = new Date(newLiveTime).toISOString();",
    "  const conflict = await checkConflict(userId, existing.platform, liveIso, id);",
    "  if (conflict) return conflict;",
    "  const uploadIso = uploadTimeFor(liveIso, existing.platform);",
    "  const buffer = uploadBufferFor(existing.platform);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update content_publishing_scheduler_posts",
    "      set scheduled_live_time = ${liveIso},",
    "          scheduled_upload_time = ${uploadIso},",
    "          upload_buffer_minutes = ${buffer},",
    "          updated_at = now()",
    "      where id = ${id} and user_id = ${userId} and status = 'scheduled'",
    "      returning id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status,",
    "        created_at, updated_at`;",
    "    return rows[0] ? rowToPost(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Cancel a scheduled post, ported from cancel_post: only ones still scheduled.",
    "export async function cancelPost(id: string, userId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update content_publishing_scheduler_posts",
    "      set status = 'cancelled', updated_at = now()",
    "      where id = ${id} and user_id = ${userId} and status = 'scheduled'",
    "      returning id`;",
    "    return rows.length > 0;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export type QueueStats = {",
    "  total: number;",
    "  scheduled: number;",
    "  live: number;",
    "  cancelled: number;",
    "  failed: number;",
    "  byPlatform: Record<string, number>;",
    "  nextPost: ScheduledPost | null;",
    "};",
    "",
    "// Queue statistics, ported from get_queue_stats: totals by status, a breakdown by",
    "// platform for still-scheduled posts, and the next post up.",
    "export async function getQueueStats(userId: string): Promise<QueueStats> {",
    "  const empty: QueueStats = { total: 0, scheduled: 0, live: 0, cancelled: 0, failed: 0, byPlatform: {}, nextPost: null };",
    "  if (!hasDatabase()) {",
    "    const byPlatform: Record<string, number> = {};",
    '    for (const p of fallbackPosts.filter((x) => x.status === "scheduled")) {',
    "      byPlatform[p.platform] = (byPlatform[p.platform] || 0) + 1;",
    "    }",
    "    return {",
    "      total: fallbackPosts.length,",
    '      scheduled: fallbackPosts.filter((p) => p.status === "scheduled").length,',
    "      live: 0, cancelled: 0, failed: 0,",
    "      byPlatform,",
    '      nextPost: fallbackPosts.filter((p) => p.status === "scheduled").sort((a, b) => a.scheduledLiveTime.localeCompare(b.scheduledLiveTime))[0] || null',
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const counts = await sql`",
    "      select status, count(*)::int as n",
    "      from content_publishing_scheduler_posts",
    "      where user_id = ${userId}",
    "      group by status`;",
    "    const stats = { ...empty, byPlatform: {} as Record<string, number> };",
    "    for (const row of counts as Array<Record<string, unknown>>) {",
    "      const n = Number(row.n || 0);",
    "      stats.total += n;",
    '      const s = String(row.status || "");',
    '      if (s === "scheduled") stats.scheduled = n;',
    '      else if (s === "live") stats.live = n;',
    '      else if (s === "cancelled") stats.cancelled = n;',
    '      else if (s === "failed") stats.failed = n;',
    "    }",
    "    const byPlat = await sql`",
    "      select platform, count(*)::int as n",
    "      from content_publishing_scheduler_posts",
    "      where user_id = ${userId} and status = 'scheduled'",
    "      group by platform`;",
    "    for (const row of byPlat as Array<Record<string, unknown>>) {",
    '      stats.byPlatform[String(row.platform || "")] = Number(row.n || 0);',
    "    }",
    "    const nextRows = await sql`",
    "      select id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, scheduled_upload_time, upload_buffer_minutes, status,",
    "        created_at, updated_at",
    "      from content_publishing_scheduler_posts",
    "      where user_id = ${userId} and status = 'scheduled'",
    "      order by scheduled_live_time asc limit 1`;",
    "    stats.nextPost = nextRows[0] ? rowToPost(nextRows[0]) : null;",
    "    return stats;",
    "  } catch {",
    "    return empty;",
    "  }",
    "}",
    "",
    "// ---- Auto-scheduler settings (ported from auto_scheduler_routes SettingsUpdate",
    "// + AutoSchedulerPage): enabled, mode(auto|review), trigger, per-platform prefs,",
    "// and the posting time window.",
    "export type PlatformPref = { enabled: boolean; maxPerDay: number };",
    "export type AutoSchedulerSettings = {",
    "  enabled: boolean;",
    '  mode: "auto" | "review";',
    '  trigger: "immediate" | "daily" | "manual";',
    "  platforms: Record<string, PlatformPref>;",
    "  timeWindow: { startHour: number; endHour: number };",
    "};",
    "",
    "export const DEFAULT_SETTINGS: AutoSchedulerSettings = {",
    "  enabled: false,",
    '  mode: "review",',
    '  trigger: "daily",',
    "  platforms: {",
    "    youtube: { enabled: false, maxPerDay: 3 },",
    "    youtube_shorts: { enabled: true, maxPerDay: 3 },",
    "    tiktok: { enabled: true, maxPerDay: 3 },",
    "    instagram_reels: { enabled: true, maxPerDay: 3 },",
    "    instagram_story: { enabled: false, maxPerDay: 3 }",
    "  },",
    "  timeWindow: { startHour: 8, endHour: 22 }",
    "};",
    "",
    "function rowToSettings(row: Record<string, unknown>): AutoSchedulerSettings {",
    "  const parse = <T,>(v: unknown, fallback: T): T => {",
    '    if (v && typeof v === "object") return v as T;',
    '    if (typeof v === "string" && v.trim()) { try { return JSON.parse(v) as T; } catch { return fallback; } }',
    "    return fallback;",
    "  };",
    "  return {",
    "    enabled: row.enabled === true || String(row.enabled) === \"true\",",
    '    mode: (String(row.mode || "review") === "auto" ? "auto" : "review"),',
    '    trigger: ((): AutoSchedulerSettings["trigger"] => {',
    '      const t = String(row.trigger || "daily");',
    '      return t === "immediate" || t === "manual" ? t : "daily";',
    "    })(),",
    "    platforms: parse(row.platforms, DEFAULT_SETTINGS.platforms),",
    "    timeWindow: parse(row.time_window, DEFAULT_SETTINGS.timeWindow)",
    "  };",
    "}",
    "",
    "// Get (or lazily default) a creator's auto-scheduler settings, ported from",
    "// auto_scheduler get_settings.",
    "export async function getSettings(userId: string): Promise<AutoSchedulerSettings> {",
    "  if (!hasDatabase()) return DEFAULT_SETTINGS;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select enabled, mode, trigger, platforms, time_window",
    "      from content_publishing_scheduler_settings",
    "      where user_id = ${userId} limit 1`;",
    "    return rows[0] ? rowToSettings(rows[0]) : DEFAULT_SETTINGS;",
    "  } catch {",
    "    return DEFAULT_SETTINGS;",
    "  }",
    "}",
    "",
    "// Upsert settings, ported from auto_scheduler update_settings (merges non-null",
    "// fields onto the existing/default settings).",
    "export async function updateSettings(userId: string, updates: Partial<AutoSchedulerSettings>): Promise<AutoSchedulerSettings> {",
    "  const current = await getSettings(userId);",
    "  const merged: AutoSchedulerSettings = {",
    "    enabled: updates.enabled ?? current.enabled,",
    "    mode: updates.mode ?? current.mode,",
    "    trigger: updates.trigger ?? current.trigger,",
    "    platforms: updates.platforms ?? current.platforms,",
    "    timeWindow: updates.timeWindow ?? current.timeWindow",
    "  };",
    "  if (!hasDatabase()) return merged;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into content_publishing_scheduler_settings (user_id, enabled, mode, trigger, platforms, time_window, updated_at)",
    "      values (${userId}, ${merged.enabled}, ${merged.mode}, ${merged.trigger},",
    "        ${JSON.stringify(merged.platforms)}, ${JSON.stringify(merged.timeWindow)}, now())",
    "      on conflict (user_id) do update set",
    "        enabled = excluded.enabled, mode = excluded.mode, trigger = excluded.trigger,",
    "        platforms = excluded.platforms, time_window = excluded.time_window, updated_at = now()`;",
    "    return merged;",
    "  } catch {",
    "    return merged;",
    "  }",
    "}",
    "",
    "// ---- Auto-schedule suggestions (ported from AutoSchedulerPage review queue +",
    "// auto_scheduler suggestions endpoints): AI-proposed slots the creator approves",
    "// or rejects one-click, and on approval become real scheduled posts.",
    "export type Suggestion = {",
    "  id: string;",
    "  userId: string | null;",
    "  contentType: string;",
    "  contentId: string;",
    "  platform: string;",
    "  title: string;",
    "  scheduledLiveTime: string;",
    "  reason: string;",
    "  status: string; // pending, approved, rejected",
    "  createdAt: string;",
    "};",
    "",
    "function rowToSuggestion(row: Record<string, unknown>): Suggestion {",
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    contentType: String(row.content_type || "clip"),',
    '    contentId: String(row.content_id || ""),',
    '    platform: String(row.platform || ""),',
    '    title: String(row.title || ""),',
    '    scheduledLiveTime: row.scheduled_live_time ? String(row.scheduled_live_time) : "",',
    '    reason: String(row.reason || ""),',
    '    status: String(row.status || "pending"),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "const fallbackSuggestions: Suggestion[] = [",
    "  {",
    '    id: "sug-1",',
    "    userId: null,",
    '    contentType: "clip",',
    '    contentId: "clip-002",',
    '    platform: "tiktok",',
    '    title: "Behind the scenes of the launch",',
    '    scheduledLiveTime: "2025-06-03T18:00:00.000Z",',
    '    reason: "Peak audience window on TikTok",',
    '    status: "pending",',
    '    createdAt: "2025-06-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "// Auto-schedule a piece of content, ported from auto_scheduler auto_schedule_content:",
    "// pick the enabled platforms, propose optimal slots. In review mode these land as",
    "// pending suggestions; in auto mode they become scheduled posts directly.",
    "export async function autoScheduleContent(",
    "  userId: string,",
    "  contentType: string,",
    "  contentId: string,",
    "  title: string,",
    "  forcePlatforms?: string[]",
    "): Promise<{ mode: string; suggestions: Suggestion[]; scheduled: ScheduledPost[] }> {",
    "  const settings = await getSettings(userId);",
    "  const platforms = forcePlatforms && forcePlatforms.length",
    "    ? forcePlatforms",
    "    : Object.entries(settings.platforms).filter(([, p]) => p.enabled).map(([k]) => k);",
    "  const empty = { mode: settings.mode, suggestions: [] as Suggestion[], scheduled: [] as ScheduledPost[] };",
    "  if (!hasDatabase() || platforms.length === 0) return empty;",
    "  // Propose a slot per platform starting from the next window open, staggered.",
    "  const now = new Date();",
    "  const base = new Date(now.getTime());",
    "  base.setUTCHours(settings.timeWindow.startHour, 0, 0, 0);",
    "  if (base <= now) base.setUTCDate(base.getUTCDate() + 1);",
    "  let cursor = base.toISOString();",
    "  if (settings.mode === \"auto\") {",
    "    const result = await scheduleBatch({ userId, contentType, contentId, platforms, baseLiveTime: cursor, title });",
    "    return { mode: \"auto\", suggestions: [], scheduled: result.scheduled };",
    "  }",
    "  const suggestions: Suggestion[] = [];",
    "  try {",
    "    const sql = getDatabase();",
    "    for (const platform of platforms) {",
    "      const slot = await findNextSlot(userId, platform, cursor);",
    "      const rows = await sql`",
    "        insert into content_publishing_scheduler_suggestions (",
    "          user_id, content_type, content_id, platform, title, scheduled_live_time, reason, status",
    "        ) values (",
    "          ${userId}, ${contentType}, ${contentId}, ${platform}, ${title}, ${slot},",
    "          ${`Optimal ${platformLabel(platform)} window`}, 'pending'",
    "        )",
    "        returning id, user_id, content_type, content_id, platform, title,",
    "          scheduled_live_time, reason, status, created_at`;",
    "      if (rows[0]) suggestions.push(rowToSuggestion(rows[0]));",
    "      cursor = new Date(new Date(slot).getTime() + 2 * 60 * 60_000).toISOString();",
    "    }",
    "  } catch {",
    "    return empty;",
    "  }",
    "  return { mode: \"review\", suggestions, scheduled: [] };",
    "}",
    "",
    "// Pending suggestions for the review queue, ported from get_pending_suggestions.",
    "export async function listPendingSuggestions(userId: string): Promise<Suggestion[]> {",
    "  if (!hasDatabase()) return fallbackSuggestions;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, reason, status, created_at",
    "      from content_publishing_scheduler_suggestions",
    "      where user_id = ${userId} and status = 'pending'",
    "      order by scheduled_live_time asc`;",
    "    return rows.map(rowToSuggestion);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Approve a suggestion, ported from approve_suggestion: mark approved and create",
    "// the real scheduled post from it.",
    "export async function approveSuggestion(userId: string, id: string): Promise<ScheduledPost | ScheduleConflict | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, content_type, content_id, platform, title,",
    "        scheduled_live_time, reason, status, created_at",
    "      from content_publishing_scheduler_suggestions",
    "      where id = ${id} and user_id = ${userId} and status = 'pending' limit 1`;",
    "    const sug = rows[0] ? rowToSuggestion(rows[0]) : null;",
    "    if (!sug) return null;",
    "    const post = await schedulePost({",
    "      userId,",
    "      contentType: sug.contentType,",
    "      contentId: sug.contentId,",
    "      platform: sug.platform,",
    "      scheduledLiveTime: sug.scheduledLiveTime,",
    "      title: sug.title",
    "    });",
    "    await sql`update content_publishing_scheduler_suggestions set status = 'approved' where id = ${id} and user_id = ${userId}`;",
    "    return post;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Reject a suggestion, ported from reject_suggestion.",
    "export async function rejectSuggestion(userId: string, id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update content_publishing_scheduler_suggestions set status = 'rejected'",
    "      where id = ${id} and user_id = ${userId} and status = 'pending' returning id`;",
    "    return rows.length > 0;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Approve all pending suggestions, ported from approve_all_suggestions.",
    "export async function approveAllSuggestions(userId: string): Promise<number> {",
    "  const pending = await listPendingSuggestions(userId);",
    "  let approved = 0;",
    "  for (const sug of pending) {",
    "    const post = await approveSuggestion(userId, sug.id);",
    '    if (post && "id" in post) approved++;',
    "  }",
    "  return approved;",
    "}",
    "",
    "// Reject all pending suggestions, ported from reject_all_suggestions.",
    "export async function rejectAllSuggestions(userId: string): Promise<number> {",
    "  if (!hasDatabase()) return 0;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update content_publishing_scheduler_suggestions set status = 'rejected'",
    "      where user_id = ${userId} and status = 'pending' returning id`;",
    "    return rows.length;",
    "  } catch {",
    "    return 0;",
    "  }",
    "}",
    "",
    "// ---- Publishing channels (ported from multi_platform_publisher",
    "// get_connected_platforms + PLATFORM_LIMITS): which channels have owner keys",
    "// configured, and the per-channel content limits used to optimize a post.",
    "export type PlatformLimits = {",
    "  maxDuration: number;",
    "  maxTitleLength: number;",
    "  maxDescriptionLength: number;",
    "  maxHashtags: number;",
    "  aspectRatio: string;",
    "  maxFileSizeMb: number;",
    "};",
    "",
    "export const PLATFORM_LIMITS: Record<string, PlatformLimits> = {",
    "  youtube: { maxDuration: 60, maxTitleLength: 100, maxDescriptionLength: 5000, maxHashtags: 30, aspectRatio: \"9:16\", maxFileSizeMb: 256 },",
    "  youtube_shorts: { maxDuration: 60, maxTitleLength: 100, maxDescriptionLength: 5000, maxHashtags: 30, aspectRatio: \"9:16\", maxFileSizeMb: 256 },",
    "  tiktok: { maxDuration: 180, maxTitleLength: 150, maxDescriptionLength: 2200, maxHashtags: 30, aspectRatio: \"9:16\", maxFileSizeMb: 287 },",
    "  instagram_reels: { maxDuration: 90, maxTitleLength: 100, maxDescriptionLength: 2200, maxHashtags: 30, aspectRatio: \"9:16\", maxFileSizeMb: 250 },",
    "  instagram_story: { maxDuration: 60, maxTitleLength: 100, maxDescriptionLength: 2200, maxHashtags: 30, aspectRatio: \"9:16\", maxFileSizeMb: 250 }",
    "};",
    "",
    "// Which channels are connected, ported from get_connected_platforms: a channel is",
    "// connected when its owner key pair is set. Names are the app owner's, never a",
    "// provider brand shown to the customer beyond the channel label.",
    "export function connectedChannels(): string[] {",
    "  const connected: string[] = [];",
    "  if (process.env.SCHEDULER_YOUTUBE_KEY && process.env.SCHEDULER_YOUTUBE_SECRET) {",
    '    connected.push("youtube");',
    '    connected.push("youtube_shorts");',
    "  }",
    "  if (process.env.SCHEDULER_TIKTOK_KEY && process.env.SCHEDULER_TIKTOK_SECRET) {",
    '    connected.push("tiktok");',
    "  }",
    "  if (process.env.SCHEDULER_INSTAGRAM_KEY && process.env.SCHEDULER_INSTAGRAM_SECRET) {",
    '    connected.push("instagram_reels");',
    '    connected.push("instagram_story");',
    "  }",
    "  return connected;",
    "}",
    "",
    "export function schedulerEnabled(): boolean {",
    '  return process.env.FEATURE_SCHEDULER !== "false";',
    "}"
  ]);
}

// ---- src/app/api/scheduler/route.ts (list + schedule) -----------------------

function scheduleApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listSchedule, schedulePost, scheduleBatch, schedulerEnabled } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false, message: "The scheduler is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const posts = await listSchedule(String(user.id), {",
    '    startDate: url.searchParams.get("start") || undefined,',
    '    endDate: url.searchParams.get("end") || undefined,',
    '    status: url.searchParams.get("status") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, posts });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in to schedule content." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const contentId = typeof body.contentId === "string" ? body.contentId.trim() : "";',
    '  const contentType = typeof body.contentType === "string" ? body.contentType : "clip";',
    '  const title = typeof body.title === "string" ? body.title : "";',
    '  const liveTime = typeof body.scheduledLiveTime === "string" ? body.scheduledLiveTime : "";',
    "  if (!contentId || !liveTime) {",
    '    return NextResponse.json({ ok: false, message: "Pick content and a go-live time." }, { status: 400 });',
    "  }",
    "  // Batch across platforms when an array is given, else a single platform.",
    "  const platforms = Array.isArray(body.platforms) ? body.platforms.map((p) => String(p)).filter(Boolean) : [];",
    "  if (platforms.length > 0) {",
    "    const result = await scheduleBatch({",
    "      userId: String(user.id), contentType, contentId, platforms, baseLiveTime: liveTime, title",
    "    });",
    "    return NextResponse.json({ ok: true, scheduled: result.scheduled, count: result.count });",
    "  }",
    '  const platform = typeof body.platform === "string" ? body.platform : "";',
    '  if (!platform) return NextResponse.json({ ok: false, message: "Pick a channel to publish to." }, { status: 400 });',
    "  const result = await schedulePost({ userId: String(user.id), contentType, contentId, platform, scheduledLiveTime: liveTime, title });",
    '  if (!result) return NextResponse.json({ ok: false, message: "Connect a database to schedule content." }, { status: 503 });',
    '  if ("conflictingPost" in result) {',
    "    return NextResponse.json({ ok: false, message: result.message, conflictingPost: result.conflictingPost }, { status: 409 });",
    "  }",
    "  return NextResponse.json({ ok: true, post: result });",
    "}"
  ]);
}

// ---- src/app/api/scheduler/stats/route.ts (queue stats) ---------------------

function statsApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/stats/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getQueueStats, schedulerEnabled } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const stats = await getQueueStats(String(user.id));",
    "  return NextResponse.json({ ok: true, stats });",
    "}"
  ]);
}

// ---- src/app/api/scheduler/[id]/route.ts (detail + reschedule + cancel) -----

function scheduleDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getPost, reschedulePost, cancelPost, schedulerEnabled } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const post = await getPost(id, String(user.id));",
    '  if (!post) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, post });",
    "}",
    "",
    "// Reschedule to a new go-live time (drag-and-drop), ported from reschedule_post.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const newLiveTime = typeof body.scheduledLiveTime === "string" ? body.scheduledLiveTime : "";',
    '  if (!newLiveTime) return NextResponse.json({ ok: false, message: "A new go-live time is required." }, { status: 400 });',
    "  const result = await reschedulePost(id, String(user.id), newLiveTime);",
    '  if (!result) return NextResponse.json({ ok: false, message: "Post not found or already processed." }, { status: 404 });',
    '  if ("conflictingPost" in result) {',
    "    return NextResponse.json({ ok: false, message: result.message, conflictingPost: result.conflictingPost }, { status: 409 });",
    "  }",
    "  return NextResponse.json({ ok: true, post: result });",
    "}",
    "",
    "// Cancel a scheduled post, ported from cancel_post.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const ok = await cancelPost(id, String(user.id));",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Post not found or already processed." }, { status: 404 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/scheduler/auto/route.ts (settings + auto-schedule trigger) -

function autoApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/auto/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getSettings, updateSettings, autoScheduleContent, schedulerEnabled } from "@/lib/db/scheduler";',
    'import type { AutoSchedulerSettings } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const settings = await getSettings(String(user.id));",
    "  return NextResponse.json({ ok: true, settings });",
    "}",
    "",
    "// Update auto-scheduler settings, ported from auto_scheduler update_settings.",
    "export async function PUT(request: Request) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const updates: Partial<AutoSchedulerSettings> = {};",
    '  if (typeof body.enabled === "boolean") updates.enabled = body.enabled;',
    '  if (body.mode === "auto" || body.mode === "review") updates.mode = body.mode;',
    '  if (body.trigger === "immediate" || body.trigger === "daily" || body.trigger === "manual") updates.trigger = body.trigger;',
    '  if (body.platforms && typeof body.platforms === "object") updates.platforms = body.platforms as AutoSchedulerSettings["platforms"];',
    '  if (body.timeWindow && typeof body.timeWindow === "object") updates.timeWindow = body.timeWindow as AutoSchedulerSettings["timeWindow"];',
    "  const settings = await updateSettings(String(user.id), updates);",
    "  return NextResponse.json({ ok: true, settings });",
    "}",
    "",
    "// Trigger auto-scheduling for a piece of content, ported from auto_schedule.",
    "export async function POST(request: Request) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const contentId = typeof body.contentId === "string" ? body.contentId.trim() : "";',
    '  const contentType = typeof body.contentType === "string" ? body.contentType : "clip";',
    '  const title = typeof body.title === "string" ? body.title : "";',
    '  if (!contentId) return NextResponse.json({ ok: false, message: "Pick content to auto-schedule." }, { status: 400 });',
    "  const platforms = Array.isArray(body.platforms) ? body.platforms.map((p) => String(p)).filter(Boolean) : undefined;",
    "  const result = await autoScheduleContent(String(user.id), contentType, contentId, title, platforms);",
    "  return NextResponse.json({ ok: true, ...result });",
    "}"
  ]);
}

// ---- src/app/api/scheduler/suggestions/route.ts (list + bulk approve/reject) -

function suggestionsApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/suggestions/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listPendingSuggestions, approveAllSuggestions, rejectAllSuggestions, schedulerEnabled } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const suggestions = await listPendingSuggestions(String(user.id));",
    "  return NextResponse.json({ ok: true, suggestions, count: suggestions.length });",
    "}",
    "",
    "// Bulk approve/reject, ported from approve-all / reject-all endpoints.",
    "export async function POST(request: Request) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "";',
    '  if (action === "approve-all") {',
    "    const count = await approveAllSuggestions(String(user.id));",
    "    return NextResponse.json({ ok: true, approvedCount: count });",
    "  }",
    '  if (action === "reject-all") {',
    "    const count = await rejectAllSuggestions(String(user.id));",
    "    return NextResponse.json({ ok: true, rejectedCount: count });",
    "  }",
    '  return NextResponse.json({ ok: false, message: "Unknown action." }, { status: 400 });',
    "}"
  ]);
}

// ---- src/app/api/scheduler/suggestions/[id]/route.ts (approve/reject one) ----

function suggestionDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/scheduler/suggestions/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { approveSuggestion, rejectSuggestion, schedulerEnabled } from "@/lib/db/scheduler";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Approve or reject a single suggestion, ported from suggestions/{id}/approve|reject.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!schedulerEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "approve";',
    '  if (action === "reject") {',
    "    const ok = await rejectSuggestion(String(user.id), id);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Suggestion not found." }, { status: 404 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    "  const post = await approveSuggestion(String(user.id), id);",
    '  if (!post) return NextResponse.json({ ok: false, message: "Suggestion not found or database not connected." }, { status: 404 });',
    '  if ("conflictingPost" in post) {',
    "    return NextResponse.json({ ok: false, message: post.message, conflictingPost: post.conflictingPost }, { status: 409 });",
    "  }",
    '  return NextResponse.json({ ok: true, post, message: "Post scheduled." });',
    "}"
  ]);
}

// ---- src/app/scheduler/page.tsx (calendar/queue + schedule form) ------------

function schedulerPageFile(): GeneratedModuleFile {
  return file("src/app/scheduler/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listSchedule, getQueueStats, platformLabel, connectedChannels, schedulerEnabled } from "@/lib/db/scheduler";',
    'import { ScheduleForm } from "./schedule-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SchedulerPage() {",
    "  if (!schedulerEnabled()) {",
    '    return (<main className="shell"><h1>Scheduler</h1><p>The scheduler is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scheduler");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const posts = await listSchedule(userId, {});",
    "  const stats = await getQueueStats(userId);",
    "  const connected = connectedChannels();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Content</p>',
    "      <h1>Publishing schedule</h1>",
    "      <p>Plan, schedule, and repurpose your content across every channel from one place. Go-live times account for each channel&apos;s upload buffer so your post lands right on time.</p>",
    "",
    '      <section className="stat-row">',
    '        <div className="stat"><strong>{stats.scheduled}</strong><span>Scheduled</span></div>',
    '        <div className="stat"><strong>{stats.live}</strong><span>Live</span></div>',
    '        <div className="stat"><strong>{stats.total}</strong><span>Total</span></div>',
    "      </section>",
    "      {stats.nextPost ? (",
    '        <p className="note">Next up: <strong>{stats.nextPost.title || stats.nextPost.contentId}</strong> on {platformLabel(stats.nextPost.platform)} at {new Date(stats.nextPost.scheduledLiveTime).toLocaleString()}.</p>',
    "      ) : null}",
    "",
    "      <h2>Schedule content</h2>",
    "      {connected.length === 0 ? (",
    '        <p className="note">No channels are connected yet. You can still plan posts — connect channel keys to publish live.</p>',
    "      ) : (",
    '        <p className="note">Connected channels: {connected.map(platformLabel).join(", ")}.</p>',
    "      )}",
    "      <ScheduleForm />",
    "",
    "      <h2>Your queue</h2>",
    "      {posts.length === 0 ? (",
    '        <p className="note">Nothing scheduled yet. Add your first post above.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {posts.map((p) => (",
    '            <Link className="wide-card" key={p.id} href={`/scheduler/${p.id}`}>',
    "              <span>{platformLabel(p.platform)} · {p.status}</span>",
    "              <strong>{p.title || p.contentId}</strong>",
    '              <p className="note">{p.contentType} · goes live {new Date(p.scheduledLiveTime).toLocaleString()}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/scheduler/auto">Auto-scheduler settings</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scheduler/schedule-form.tsx (client) ---------------------------

function scheduleFormFile(): GeneratedModuleFile {
  return file("src/app/scheduler/schedule-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "const PLATFORM_OPTIONS = [",
    '  { value: "youtube", label: "YouTube" },',
    '  { value: "youtube_shorts", label: "YT Shorts" },',
    '  { value: "tiktok", label: "TikTok" },',
    '  { value: "instagram_reels", label: "IG Reels" },',
    '  { value: "instagram_story", label: "IG Story" }',
    "];",
    "",
    "export function ScheduleForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    '    const rawTime = String(form.get("scheduledLiveTime") || "");',
    '    const scheduledLiveTime = rawTime ? new Date(rawTime).toISOString() : "";',
    "    try {",
    '      const response = await fetch("/api/scheduler", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          contentId: form.get("contentId"),',
    '          contentType: form.get("contentType"),',
    '          title: form.get("title"),',
    '          platform: form.get("platform"),',
    "          scheduledLiveTime",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not schedule this post.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Scheduled.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Post title" aria-label="Post title" />',
    '      <input className="input" name="contentId" placeholder="Content reference (e.g. a clip id)" aria-label="Content reference" required />',
    '      <select className="input" name="contentType" aria-label="Content type" defaultValue="clip">',
    '        <option value="clip">Clip</option>',
    '        <option value="remix">Remix</option>',
    '        <option value="repurpose">Repurpose</option>',
    "      </select>",
    '      <select className="input" name="platform" aria-label="Channel" defaultValue="youtube_shorts">',
    "        {PLATFORM_OPTIONS.map((o) => (",
    "          <option key={o.value} value={o.value}>{o.label}</option>",
    "        ))}",
    "      </select>",
    '      <input className="input" name="scheduledLiveTime" type="datetime-local" aria-label="Go-live time" required />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Scheduling…" : "Schedule post"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scheduler/[id]/page.tsx (detail + reschedule/cancel) -----------

function scheduleDetailPageFile(): GeneratedModuleFile {
  return file("src/app/scheduler/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getPost, platformLabel, uploadBufferFor, schedulerEnabled } from "@/lib/db/scheduler";',
    'import { PostActions } from "./post-actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ScheduledPostPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!schedulerEnabled()) {",
    '    return (<main className="shell"><h1>Scheduler</h1><p>The scheduler is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scheduler");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const { id } = await params;",
    "  const post = await getPost(id, userId);",
    "  if (!post) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{platformLabel(post.platform)} · {post.status}</p>',
    "      <h1>{post.title || post.contentId}</h1>",
    '      <p className="note">{post.contentType} · content ref {post.contentId}</p>',
    "      <dl className=\"detail-grid\">",
    "        <div><dt>Goes live</dt><dd>{new Date(post.scheduledLiveTime).toLocaleString()}</dd></div>",
    "        <div><dt>Uploads at</dt><dd>{new Date(post.scheduledUploadTime).toLocaleString()}</dd></div>",
    "        <div><dt>Upload buffer</dt><dd>{post.uploadBufferMinutes || uploadBufferFor(post.platform)} min</dd></div>",
    "      </dl>",
    '      {post.status === "scheduled" ? (',
    "        <PostActions id={post.id} liveTime={post.scheduledLiveTime} />",
    "      ) : (",
    '        <p className="note">This post is {post.status} and can no longer be changed.</p>',
    "      )}",
    '      <p><Link className="button" href="/scheduler">Back to schedule</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scheduler/[id]/post-actions.tsx (client) -----------------------

function postActionsFile(): GeneratedModuleFile {
  return file("src/app/scheduler/[id]/post-actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function PostActions({ id, liveTime }: { id: string; liveTime: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "  const local = liveTime ? new Date(liveTime).toISOString().slice(0, 16) : \"\";",
    '  const [when, setWhen] = useState<string>(local);',
    "",
    "  async function reschedule() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/scheduler/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ scheduledLiveTime: when ? new Date(when).toISOString() : \"\" })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not reschedule.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function cancel() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/scheduler/${id}`, { method: \"DELETE\" });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not cancel.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <label className="note" htmlFor="reschedule-when">Move go-live time</label>',
    '      <input className="input" id="reschedule-when" type="datetime-local" value={when} onChange={(e) => setWhen(e.target.value)} />',
    '      <button className="button primary" type="button" onClick={reschedule} disabled={status === "working"}>Reschedule</button>',
    '      <button className="button" type="button" onClick={cancel} disabled={status === "working"}>Cancel this post</button>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scheduler/auto/page.tsx (auto-scheduler + review queue) --------

function autoPageFile(): GeneratedModuleFile {
  return file("src/app/scheduler/auto/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getSettings, listPendingSuggestions, platformLabel, schedulerEnabled } from "@/lib/db/scheduler";',
    'import { AutoSchedulerPanel } from "./auto-panel";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AutoSchedulerPage() {",
    "  if (!schedulerEnabled()) {",
    '    return (<main className="shell"><h1>Auto-scheduler</h1><p>The scheduler is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scheduler/auto");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const settings = await getSettings(userId);",
    "  const suggestions = await listPendingSuggestions(userId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Content</p>',
    "      <h1>Auto-scheduler</h1>",
    "      <p>Let the app handle your posting schedule. It finds good posting times, respects each channel&apos;s limits, and spreads content across days so you never spam a feed.</p>",
    "      <AutoSchedulerPanel",
    "        initialSettings={settings}",
    "        initialSuggestions={suggestions.map((s) => ({",
    "          id: s.id,",
    "          title: s.title || s.contentId,",
    "          platform: platformLabel(s.platform),",
    "          scheduledLiveTime: s.scheduledLiveTime,",
    "          reason: s.reason",
    "        }))}",
    "      />",
    '      <p><Link className="button" href="/scheduler">Back to schedule</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scheduler/auto/auto-panel.tsx (client) -------------------------

function autoPanelFile(): GeneratedModuleFile {
  return file("src/app/scheduler/auto/auto-panel.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Pref = { enabled: boolean; maxPerDay: number };",
    "type Settings = {",
    "  enabled: boolean;",
    '  mode: "auto" | "review";',
    '  trigger: "immediate" | "daily" | "manual";',
    "  platforms: Record<string, Pref>;",
    "  timeWindow: { startHour: number; endHour: number };",
    "};",
    "type SuggestionView = { id: string; title: string; platform: string; scheduledLiveTime: string; reason: string };",
    "",
    "const PLATFORM_KEYS: Array<{ key: string; label: string }> = [",
    '  { key: "youtube", label: "YouTube" },',
    '  { key: "youtube_shorts", label: "YT Shorts" },',
    '  { key: "tiktok", label: "TikTok" },',
    '  { key: "instagram_reels", label: "IG Reels" },',
    '  { key: "instagram_story", label: "IG Story" }',
    "];",
    "",
    "export function AutoSchedulerPanel({",
    "  initialSettings,",
    "  initialSuggestions",
    "}: {",
    "  initialSettings: Settings;",
    "  initialSuggestions: SuggestionView[];",
    "}) {",
    "  const router = useRouter();",
    "  const [settings, setSettings] = useState<Settings>(initialSettings);",
    "  const [suggestions, setSuggestions] = useState<SuggestionView[]>(initialSuggestions);",
    '  const [message, setMessage] = useState<string>("");',
    "  const [saving, setSaving] = useState(false);",
    "",
    "  async function save(updates: Partial<Settings>) {",
    "    setSaving(true);",
    '    setMessage("");',
    "    const next = { ...settings, ...updates };",
    "    setSettings(next);",
    "    try {",
    '      const response = await fetch("/api/scheduler/auto", {',
    '        method: "PUT",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(updates)",
    "      });",
    "      const data = await response.json();",
    '      if (data.ok && data.settings) setSettings(data.settings as Settings);',
    "    } catch {",
    '      setMessage("Could not save settings.");',
    "    } finally {",
    "      setSaving(false);",
    "    }",
    "  }",
    "",
    "  function togglePlatform(key: string) {",
    "    const current = settings.platforms[key] || { enabled: false, maxPerDay: 3 };",
    "    save({ platforms: { ...settings.platforms, [key]: { ...current, enabled: !current.enabled } } });",
    "  }",
    "",
    "  function setMaxPerDay(key: string, value: number) {",
    "    const current = settings.platforms[key] || { enabled: true, maxPerDay: 3 };",
    "    save({ platforms: { ...settings.platforms, [key]: { ...current, maxPerDay: value } } });",
    "  }",
    "",
    "  async function reviewOne(id: string, action: \"approve\" | \"reject\") {",
    "    try {",
    "      await fetch(`/api/scheduler/suggestions/${id}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      setSuggestions((s) => s.filter((x) => x.id !== id));",
    "      router.refresh();",
    "    } catch {",
    '      setMessage("Could not update that suggestion.");',
    "    }",
    "  }",
    "",
    "  async function reviewAll(action: \"approve-all\" | \"reject-all\") {",
    "    try {",
    '      await fetch("/api/scheduler/suggestions", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      setSuggestions([]);",
    "      router.refresh();",
    "    } catch {",
    '      setMessage("Could not update suggestions.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <section className="panel">',
    '        <label className="check">',
    '          <input type="checkbox" checked={settings.enabled} disabled={saving} onChange={() => save({ enabled: !settings.enabled })} />',
    "          {\" \"}Turn auto-scheduling on",
    "        </label>",
    '        <p className="note">{settings.enabled ? "New content will be scheduled for you." : "Turn on to automate your posting schedule."}</p>',
    "      </section>",
    "",
    "      {settings.enabled ? (",
    "        <>",
    '          <section className="panel">',
    "            <h3>Automation mode</h3>",
    '            <div className="stack">',
    '              <label className="check"><input type="radio" name="mode" checked={settings.mode === "auto"} onChange={() => save({ mode: "auto" })} /> Full auto — content is scheduled automatically</label>',
    '              <label className="check"><input type="radio" name="mode" checked={settings.mode === "review"} onChange={() => save({ mode: "review" })} /> Review first — you approve each suggested time</label>',
    "            </div>",
    "          </section>",
    "",
    '          <section className="panel">',
    "            <h3>When to schedule</h3>",
    '            <div className="stack">',
    '              <label className="check"><input type="radio" name="trigger" checked={settings.trigger === "immediate"} onChange={() => save({ trigger: "immediate" })} /> Immediately as content is created</label>',
    '              <label className="check"><input type="radio" name="trigger" checked={settings.trigger === "daily"} onChange={() => save({ trigger: "daily" })} /> Daily batch</label>',
    '              <label className="check"><input type="radio" name="trigger" checked={settings.trigger === "manual"} onChange={() => save({ trigger: "manual" })} /> Only when I trigger it</label>',
    "            </div>",
    "          </section>",
    "",
    '          <section className="panel">',
    "            <h3>Channel preferences</h3>",
    "            {PLATFORM_KEYS.map(({ key, label }) => {",
    "              const pref = settings.platforms[key] || { enabled: false, maxPerDay: 3 };",
    "              return (",
    '                <div className="row" key={key}>',
    '                  <label className="check">',
    '                    <input type="checkbox" checked={pref.enabled} onChange={() => togglePlatform(key)} /> {label}',
    "                  </label>",
    "                  {pref.enabled ? (",
    '                    <label className="note">Max/day{" "}',
    '                      <select className="input" value={pref.maxPerDay} onChange={(e) => setMaxPerDay(key, parseInt(e.target.value, 10) || 1)}>',
    "                        {[1, 2, 3, 4, 5, 6, 8, 10].map((n) => (<option key={n} value={n}>{n}</option>))}",
    "                      </select>",
    "                    </label>",
    "                  ) : null}",
    "                </div>",
    "              );",
    "            })}",
    "          </section>",
    "",
    '          <section className="panel">',
    "            <h3>Posting window</h3>",
    '            <div className="row">',
    '              <label className="note">Start{" "}',
    '                <select className="input" value={settings.timeWindow.startHour} onChange={(e) => save({ timeWindow: { ...settings.timeWindow, startHour: parseInt(e.target.value, 10) } })}>',
    "                  {Array.from({ length: 24 }, (_, i) => (<option key={i} value={i}>{i === 0 ? \"12 AM\" : i < 12 ? `${i} AM` : i === 12 ? \"12 PM\" : `${i - 12} PM`}</option>))}",
    "                </select>",
    "              </label>",
    '              <label className="note">End{" "}',
    '                <select className="input" value={settings.timeWindow.endHour} onChange={(e) => save({ timeWindow: { ...settings.timeWindow, endHour: parseInt(e.target.value, 10) } })}>',
    "                  {Array.from({ length: 24 }, (_, i) => (<option key={i} value={i}>{i === 0 ? \"12 AM\" : i < 12 ? `${i} AM` : i === 12 ? \"12 PM\" : `${i - 12} PM`}</option>))}",
    "                </select>",
    "              </label>",
    "            </div>",
    '            <p className="note">Posts are only scheduled within this window.</p>',
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    "      {settings.mode === \"review\" && suggestions.length > 0 ? (",
    '        <section className="panel">',
    "          <div className=\"row\">",
    "            <h3>Pending review ({suggestions.length})</h3>",
    '            <div className="stack">',
    '              <button className="button primary" type="button" onClick={() => reviewAll("approve-all")}>Approve all</button>',
    '              <button className="button" type="button" onClick={() => reviewAll("reject-all")}>Dismiss all</button>',
    "            </div>",
    "          </div>",
    '          <section className="panel-list">',
    "            {suggestions.map((sug) => (",
    '              <article className="wide-card" key={sug.id}>',
    "                <span>{sug.platform}</span>",
    "                <strong>{sug.title}</strong>",
    '                <p className="note">{new Date(sug.scheduledLiveTime).toLocaleString()} — {sug.reason}</p>',
    '                <div className="stack">',
    '                  <button className="button primary" type="button" onClick={() => reviewOne(sug.id, "approve")}>Approve</button>',
    '                  <button className="button" type="button" onClick={() => reviewOne(sug.id, "reject")}>Dismiss</button>',
    "                </div>",
    "              </article>",
    "            ))}",
    "          </section>",
    "        </section>",
    "      ) : null}",
    "",
    '      {message ? <p className="note" role="alert">{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const contentSchedulerModule: AppModule = {
  slug: "content-publishing-scheduler",
  name: "Content Publishing Scheduler",
  tier: "optional",
  featureFlagEnv: "FEATURE_SCHEDULER",
  files: () => [
    schedulerLibFile(),
    scheduleApiFile(),
    statsApiFile(),
    scheduleDetailApiFile(),
    autoApiFile(),
    suggestionsApiFile(),
    suggestionDetailApiFile(),
    schedulerPageFile(),
    scheduleFormFile(),
    scheduleDetailPageFile(),
    postActionsFile(),
    autoPageFile(),
    autoPanelFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists content_publishing_scheduler_posts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete cascade,",
      "  content_type text not null default 'clip',",
      "  content_id text not null default '',",
      "  platform text not null default '',",
      "  title text not null default '',",
      "  scheduled_live_time timestamptz not null,",
      "  scheduled_upload_time timestamptz not null,",
      "  upload_buffer_minutes integer not null default 5,",
      "  status text not null default 'scheduled',",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists content_publishing_scheduler_posts_user_idx on content_publishing_scheduler_posts (user_id);",
      "create index if not exists content_publishing_scheduler_posts_platform_idx on content_publishing_scheduler_posts (user_id, platform, status);",
      "create index if not exists content_publishing_scheduler_posts_live_idx on content_publishing_scheduler_posts (user_id, scheduled_live_time);",
      "",
      "create table if not exists content_publishing_scheduler_settings (",
      "  user_id uuid primary key references users(id) on delete cascade,",
      "  enabled boolean not null default false,",
      "  mode text not null default 'review',",
      "  trigger text not null default 'daily',",
      "  platforms jsonb not null default '{}'::jsonb,",
      "  time_window jsonb not null default '{\"startHour\":8,\"endHour\":22}'::jsonb,",
      "  updated_at timestamptz not null default now()",
      ");",
      "",
      "create table if not exists content_publishing_scheduler_suggestions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete cascade,",
      "  content_type text not null default 'clip',",
      "  content_id text not null default '',",
      "  platform text not null default '',",
      "  title text not null default '',",
      "  scheduled_live_time timestamptz not null,",
      "  reason text not null default '',",
      "  status text not null default 'pending',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists content_publishing_scheduler_suggestions_user_idx on content_publishing_scheduler_suggestions (user_id, status);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Sample rows are only meaningful once a real user id exists; the app seeds its",
      "-- own once a creator schedules their first post. No cross-user seed here.",
      ""
    ].join("\n"),
  envLines: () => [
    "",
    "# Content Publishing Scheduler — set to false to switch scheduling off.",
    "FEATURE_SCHEDULER=true",
    "# Optional channel keys. A channel only shows as connected (able to publish",
    "# live) when its key + secret pair is set; scheduling/planning works without them.",
    "SCHEDULER_YOUTUBE_KEY=",
    "SCHEDULER_YOUTUBE_SECRET=",
    "SCHEDULER_TIKTOK_KEY=",
    "SCHEDULER_TIKTOK_SECRET=",
    "SCHEDULER_INSTAGRAM_KEY=",
    "SCHEDULER_INSTAGRAM_SECRET="
  ],
  homeLinks: () => ['        <a className="button" href="/scheduler">Publishing schedule</a>'],
  navLinks: () => [{ href: "/scheduler", label: "Scheduler" }]
};
