// creator-analytics-coaching — analyze content performance, algorithm signals,
// growth patterns, and the next best actions for a creator. Ported from the real
// Snip / Emergent creator-intelligence stack (repo: emergent + snip.show):
//   - backend/services/growth_analytics_service.py get_growth_dashboard +
//     get_clipforge_impact_summary: the per-creator overview (total views/likes/
//     revenue/clips/videos), the baseline→incremental revenue + revenue-share ROI
//     math (15% share, creator earnings, value multiplier), the value-delivered
//     breakdown (clips, videos, posts, platforms, time saved), and the impact
//     headline/subheadline copy — generalized off Snip's brand into "this app".
//   - backend/services/advanced_analytics.py _calculate_growth_rate +
//     _calculate_health_score + predictive_analytics: compound growth-rate,
//     the 0-100 health score (growth 0-40 + retention 0-30 + efficiency 0-30 →
//     excellent/good/fair/needs_attention), and the recommendation rules
//     ("growth below 5%", "declining 10%+").
//   - backend/services/algorithm_tracker.py: the tracked algorithm SIGNALS
//     (engagement_rate_drop/reach_decline/... with thresholds + severity), the
//     engagement-rate + reach change detection with its recommendation strings,
//     the default best-posting-times per platform, and the trending content-type
//     table (types / optimal_length / trending_topics per platform).
//   - backend/services/algorithm_insights_service.py: the per-platform ranking-
//     signal insight record (platform, algorithm_summary, key_ranking_signals
//     [signal/weight/description/optimization_tip], best posting times) cached
//     one row per platform — generalized so it degrades to built-in defaults when
//     no LLM key is set.
//   - backend/services/coaching_service.py + backend/routes/coaching_routes.py
//     (/coaching/progress): the coaching-report model (overall_score, summary,
//     the five category_scores delivery/content_structure/emotional_connection/
//     audience_retention/production_value, strengths, improvements w/ priority +
//     difficulty, quick_wins) and the progress timeline (per-report scores +
//     category averages + first→last improvement).
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_CREATOR_ANALYTICS); creators read/track their own
// content + reports (rows scoped to user.id), admins see the cross-account roll-up
// and publish per-platform algorithm insights.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/creator-analytics.ts (model + queries, ported) --------------

function analyticsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/creator-analytics.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The platforms we track, ported from algorithm_tracker.py PLATFORMS +",
    "// algorithm_insights_service.py PLATFORMS.",
    'export const PLATFORMS = ["youtube", "tiktok", "instagram", "twitter", "linkedin", "facebook"] as const;',
    "export type Platform = (typeof PLATFORMS)[number];",
    "",
    "// A single piece of content the creator has published (ported from the clips /",
    "// videos + analytics_snapshots the growth dashboard reads: views, likes,",
    "// comments, shares, revenue, primary topic, viral score, platform, created_at).",
    "export type ContentPiece = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  platform: Platform;",
    "  primaryTopic: string;",
    "  views: number;",
    "  likes: number;",
    "  comments: number;",
    "  shares: number;",
    "  revenue: number;",
    "  viralScore: number;",
    "  createdAt: string;",
    "};",
    "",
    "export type ContentFilters = { ownerId?: string; platform?: string; q?: string; limit?: number };",
    "",
    "// The tracked algorithm signals + thresholds, ported verbatim from",
    "// algorithm_tracker.py SIGNALS. A drop past the threshold fires the signal.",
    "export const ALGORITHM_SIGNALS: Record<string, { threshold: number; severity: \"high\" | \"medium\" | \"low\" }> = {",
    "  engagement_rate_drop: { threshold: -15, severity: \"high\" },",
    "  reach_decline: { threshold: -20, severity: \"high\" },",
    "  hashtag_effectiveness_change: { threshold: -10, severity: \"medium\" },",
    "  posting_time_shift: { threshold: 30, severity: \"medium\" },",
    "  content_type_preference: { threshold: 15, severity: \"low\" },",
    "  video_length_preference: { threshold: 10, severity: \"medium\" }",
    "};",
    "",
    "// Default best posting times per platform, ported from",
    "// algorithm_tracker.get_best_posting_times' defaults.",
    "export const DEFAULT_POSTING_TIMES: Record<string, Array<{ hour: number; day: string }>> = {",
    "  youtube: [{ hour: 14, day: \"wednesday\" }, { hour: 18, day: \"friday\" }],",
    "  tiktok: [{ hour: 19, day: \"tuesday\" }, { hour: 21, day: \"thursday\" }],",
    "  instagram: [{ hour: 11, day: \"wednesday\" }, { hour: 19, day: \"friday\" }],",
    "  twitter: [{ hour: 9, day: \"wednesday\" }, { hour: 12, day: \"thursday\" }],",
    "  linkedin: [{ hour: 8, day: \"tuesday\" }, { hour: 17, day: \"thursday\" }],",
    "  facebook: [{ hour: 13, day: \"wednesday\" }, { hour: 19, day: \"thursday\" }]",
    "};",
    "",
    "// Trending content-type table per platform, ported verbatim from",
    "// algorithm_tracker.get_trending_content_types.",
    "export type TrendingContent = { types: string[]; optimalLength: string; trendingTopics: string[] };",
    "export const TRENDING_CONTENT: Record<string, TrendingContent> = {",
    "  youtube: { types: [\"shorts\", \"tutorials\", \"reactions\"], optimalLength: \"30-60s for Shorts, 8-12min for long-form\", trendingTopics: [\"AI tools\", \"productivity\", \"tech reviews\"] },",
    "  tiktok: { types: [\"trends\", \"storytelling\", \"quick-tips\"], optimalLength: \"15-30s\", trendingTopics: [\"life hacks\", \"behind-the-scenes\", \"day-in-life\"] },",
    "  instagram: { types: [\"reels\", \"carousel\", \"stories\"], optimalLength: \"15-60s for Reels\", trendingTopics: [\"aesthetic\", \"motivation\", \"educational\"] },",
    "  twitter: { types: [\"threads\", \"video\", \"polls\"], optimalLength: \"30-90s for video\", trendingTopics: [\"tech news\", \"hot takes\", \"tips\"] },",
    "  linkedin: { types: [\"carousel\", \"video\", \"articles\"], optimalLength: \"60-90s for video\", trendingTopics: [\"career growth\", \"industry insights\", \"leadership\"] },",
    "  facebook: { types: [\"video\", \"live\", \"groups\"], optimalLength: \"60-180s\", trendingTopics: [\"community\", \"entertainment\", \"how-to\"] }",
    "};",
    "",
    "export function trendingFor(platform: string): TrendingContent {",
    "  return TRENDING_CONTENT[platform] || TRENDING_CONTENT.youtube;",
    "}",
    "",
    "export function postingTimesFor(platform: string): Array<{ hour: number; day: string }> {",
    "  return DEFAULT_POSTING_TIMES[platform] || [];",
    "}",
    "",
    "// --- math helpers, ported from advanced_analytics.py + algorithm_tracker.py ---",
    "",
    "// Compound (period-over-period) growth rate, ported from",
    "// advanced_analytics._calculate_growth_rate.",
    "export function calculateGrowthRate(values: number[]): number {",
    "  if (values.length < 2 || values[0] === 0) return 0;",
    "  const rates: number[] = [];",
    "  for (let i = 1; i < values.length; i++) {",
    "    if (values[i - 1] > 0) rates.push(((values[i] - values[i - 1]) / values[i - 1]) * 100);",
    "  }",
    "  if (!rates.length) return 0;",
    "  return rates.reduce((a, b) => a + b, 0) / rates.length;",
    "}",
    "",
    "// Average engagement rate across snapshots, ported from",
    "// algorithm_tracker._calculate_engagement_rate: (likes+comments+shares)/views.",
    "export function engagementRate(pieces: Pick<ContentPiece, \"views\" | \"likes\" | \"comments\" | \"shares\">[]): number {",
    "  let totalViews = 0;",
    "  let totalEngagement = 0;",
    "  for (const p of pieces) {",
    "    if (p.views > 0) { totalViews += p.views; totalEngagement += p.likes + p.comments + p.shares; }",
    "  }",
    "  if (totalViews === 0) return 0;",
    "  return (totalEngagement / totalViews) * 100;",
    "}",
    "",
    "export type HealthScore = {",
    "  score: number;",
    "  status: \"excellent\" | \"good\" | \"fair\" | \"needs_attention\";",
    "  breakdown: { growth: number; retention: number; efficiency: number };",
    "};",
    "",
    "// The 0-100 creator health score, ported from",
    "// advanced_analytics._calculate_health_score: growth (0-40) + retention (0-30)",
    "// + efficiency (0-30), bucketed into excellent/good/fair/needs_attention.",
    "export function healthScore(growthRate: number, churnProb: number, ltvCac: number): HealthScore {",
    "  const growth = Math.min(40, Math.max(0, growthRate * 2));",
    "  const retention = Math.max(0, 30 - churnProb * 100);",
    "  const efficiency = Math.min(30, ltvCac * 5);",
    "  const total = growth + retention + efficiency;",
    "  let status: HealthScore[\"status\"] = \"needs_attention\";",
    "  if (total >= 80) status = \"excellent\";",
    "  else if (total >= 60) status = \"good\";",
    "  else if (total >= 40) status = \"fair\";",
    "  return {",
    "    score: Math.round(total * 10) / 10,",
    "    status,",
    "    breakdown: {",
    "      growth: Math.round(growth * 10) / 10,",
    "      retention: Math.round(retention * 10) / 10,",
    "      efficiency: Math.round(efficiency * 10) / 10",
    "    }",
    "  };",
    "}",
    "",
    "// --- fallback content (used when no DB is connected) ---",
    "",
    "const fallbackContent: ContentPiece[] = [",
    "  {",
    "    id: \"sample-1\",",
    "    ownerId: null,",
    "    title: \"How I edit in half the time\",",
    "    platform: \"youtube\",",
    "    primaryTopic: \"productivity\",",
    "    views: 42000,",
    "    likes: 2100,",
    "    comments: 180,",
    "    shares: 320,",
    "    revenue: 210.5,",
    "    viralScore: 78,",
    "    createdAt: \"2025-04-01T00:00:00.000Z\"",
    "  },",
    "  {",
    "    id: \"sample-2\",",
    "    ownerId: null,",
    "    title: \"3 hooks that stop the scroll\",",
    "    platform: \"tiktok\",",
    "    primaryTopic: \"growth\",",
    "    views: 128000,",
    "    likes: 9400,",
    "    comments: 640,",
    "    shares: 1500,",
    "    revenue: 95.0,",
    "    viralScore: 91,",
    "    createdAt: \"2025-04-14T00:00:00.000Z\"",
    "  },",
    "  {",
    "    id: \"sample-3\",",
    "    ownerId: null,",
    "    title: \"Behind the scenes of a shoot\",",
    "    platform: \"instagram\",",
    "    primaryTopic: \"behind-the-scenes\",",
    "    views: 18500,",
    "    likes: 1600,",
    "    comments: 210,",
    "    shares: 140,",
    "    revenue: 40.0,",
    "    viralScore: 64,",
    "    createdAt: \"2025-05-02T00:00:00.000Z\"",
    "  }",
    "];",
    "",
    "function rowToContent(row: Record<string, unknown>): ContentPiece {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    "    title: String(row.title || \"Untitled\"),",
    "    platform: (String(row.platform || \"youtube\") as Platform),",
    "    primaryTopic: String(row.primary_topic || \"General\"),",
    "    views: Number(row.views || 0),",
    "    likes: Number(row.likes || 0),",
    "    comments: Number(row.comments || 0),",
    "    shares: Number(row.shares || 0),",
    "    revenue: Number(row.revenue || 0),",
    "    viralScore: Number(row.viral_score || 0),",
    "    createdAt: row.created_at ? String(row.created_at) : \"\"",
    "  };",
    "}",
    "",
    "// List content, scoped to an owner when ownerId is given; newest first, mirroring",
    "// the growth dashboard's clip/video load.",
    "export async function listContent(filters: ContentFilters = {}): Promise<ContentPiece[]> {",
    "  const limit = Math.min(500, Math.max(1, filters.limit || 200));",
    "  const q = (filters.q || \"\").trim().toLowerCase();",
    "  const platform = (filters.platform || \"\").trim();",
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackContent",
    "      .filter((c) => !ownerId || c.ownerId === ownerId)",
    "      .filter((c) => !platform || platform === \"all\" || c.platform === platform)",
    "      .filter((c) => !q || (c.title + \" \" + c.primaryTopic).toLowerCase().includes(q))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const plat = platform && platform !== \"all\" ? platform : null;",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, title, platform, primary_topic, views, likes, comments,",
    "        shares, revenue, viral_score, created_at",
    "      from creator_analytics_coaching_content",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${plat}::text is null or platform = ${plat})",
    "        and (${like}::text is null",
    "          or lower(title) like ${like}",
    "          or lower(primary_topic) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToContent);",
    "  } catch {",
    "    return fallbackContent.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getContent(id: string, ownerId?: string): Promise<ContentPiece | null> {",
    "  if (!hasDatabase()) {",
    "    const found = fallbackContent.find((c) => c.id === id) || null;",
    "    if (found && ownerId && found.ownerId && found.ownerId !== ownerId) return null;",
    "    return found;",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, title, platform, primary_topic, views, likes, comments,",
    "        shares, revenue, viral_score, created_at",
    "      from creator_analytics_coaching_content",
    "      where id = ${id} and (${owner}::uuid is null or owner_id = ${owner})",
    "      limit 1`;",
    "    return rows[0] ? rowToContent(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateContentInput = {",
    "  ownerId: string | null;",
    "  title: string;",
    "  platform?: string;",
    "  primaryTopic?: string;",
    "  views?: number;",
    "  likes?: number;",
    "  comments?: number;",
    "  shares?: number;",
    "  revenue?: number;",
    "  viralScore?: number;",
    "};",
    "",
    "// Log a piece of content the creator published so it flows into the dashboard.",
    "export async function createContent(input: CreateContentInput): Promise<ContentPiece | null> {",
    "  if (!hasDatabase()) return null;",
    "  const platform = (PLATFORMS as readonly string[]).includes(input.platform || \"\") ? input.platform : \"youtube\";",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into creator_analytics_coaching_content (",
    "        owner_id, title, platform, primary_topic, views, likes, comments, shares,",
    "        revenue, viral_score",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.title}, ${platform},",
    "        ${input.primaryTopic || \"General\"}, ${input.views || 0}, ${input.likes || 0},",
    "        ${input.comments || 0}, ${input.shares || 0}, ${input.revenue || 0},",
    "        ${input.viralScore || 0}",
    "      )",
    "      returning id, owner_id, title, platform, primary_topic, views, likes, comments,",
    "        shares, revenue, viral_score, created_at`;",
    "    return rows[0] ? rowToContent(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// --- growth dashboard, ported from growth_analytics_service.get_growth_dashboard ---",
    "",
    "export type GrowthDashboard = {",
    "  overview: { totalViews: number; totalLikes: number; totalRevenue: number; totalContent: number };",
    "  growth: { baselineRevenue: number; currentMonthlyAvg: number; incrementalRevenue: number; growthPercentage: number };",
    "  roi: { appShare: number; creatorEarnings: number; shareRatePercentage: number; valueMultiplier: number };",
    "  health: HealthScore;",
    "  monthlyTrend: Array<{ month: string; monthLabel: string; revenue: number; incremental: number; views: number; count: number }>;",
    "  platformDistribution: Array<{ platform: string; count: number; views: number }>;",
    "  productivity: { avgViralScore: number; engagementRate: number };",
    "  topContent: Array<{ id: string; title: string; views: number; likes: number; topic: string; platform: string }>;",
    "  valueDelivered: { contentTracked: number; platformsReached: number; estimatedTimeSavedHours: number };",
    "  monthsActive: number;",
    "};",
    "",
    "function monthKey(iso: string): string {",
    "  const d = new Date(iso);",
    "  if (Number.isNaN(d.getTime())) return \"\";",
    "  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, \"0\")}`;",
    "}",
    "",
    "function monthLabel(key: string): string {",
    "  const [y, m] = key.split(\"-\").map((n) => Number(n));",
    "  if (!y || !m) return key;",
    "  const months = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\"];",
    "  return `${months[m - 1]} ${y}`;",
    "}",
    "",
    "// Assemble the growth dashboard from the creator's content. Ports the revenue-",
    "// share ROI math (15% share, creator earnings, value multiplier), the",
    "// baseline→incremental revenue calc, the monthly trend (last 6 months), the",
    "// platform distribution, and the value-delivered breakdown. The health score",
    "// comes from advanced_analytics' growth-rate + health-score formulas.",
    "export async function buildGrowthDashboard(ownerId: string | undefined, baselineMonthlyRevenue = 0): Promise<GrowthDashboard> {",
    "  const content = await listContent({ ownerId, limit: 500 });",
    "  const totalViews = content.reduce((s, c) => s + c.views, 0);",
    "  const totalLikes = content.reduce((s, c) => s + c.likes, 0);",
    "  const totalRevenue = content.reduce((s, c) => s + c.revenue, 0);",
    "",
    "  // Months active from the earliest piece of content (>=1).",
    "  const dates = content.map((c) => new Date(c.createdAt).getTime()).filter((t) => !Number.isNaN(t));",
    "  const earliest = dates.length ? Math.min(...dates) : Date.now();",
    "  const monthsActive = Math.max(1, Math.floor((Date.now() - earliest) / (1000 * 60 * 60 * 24 * 30)));",
    "",
    "  // baseline→incremental, ported from get_growth_dashboard.",
    "  const estimatedBaselineTotal = baselineMonthlyRevenue * monthsActive;",
    "  const incrementalRevenue = Math.max(0, totalRevenue - estimatedBaselineTotal);",
    "  const growthPercentage = estimatedBaselineTotal > 0",
    "    ? ((totalRevenue - estimatedBaselineTotal) / estimatedBaselineTotal) * 100",
    "    : 0;",
    "",
    "  // Revenue share (unified 15% rate), ported from get_growth_dashboard.",
    "  const shareRate = 0.15;",
    "  const appShare = incrementalRevenue * shareRate;",
    "  const creatorEarnings = incrementalRevenue * (1 - shareRate);",
    "  const valueMultiplier = creatorEarnings / Math.max(appShare, 1);",
    "",
    "  // Monthly trend (last 6 months), ported from _calculate_monthly_trend.",
    "  const monthly: Record<string, { revenue: number; views: number; count: number }> = {};",
    "  for (const c of content) {",
    "    const key = monthKey(c.createdAt);",
    "    if (!key) continue;",
    "    if (!monthly[key]) monthly[key] = { revenue: 0, views: 0, count: 0 };",
    "    monthly[key].revenue += c.revenue;",
    "    monthly[key].views += c.views;",
    "    monthly[key].count += 1;",
    "  }",
    "  const monthlyTrend = Object.keys(monthly)",
    "    .sort()",
    "    .slice(-6)",
    "    .map((key) => {",
    "      const d = monthly[key];",
    "      return {",
    "        month: key,",
    "        monthLabel: monthLabel(key),",
    "        revenue: Math.round(d.revenue * 100) / 100,",
    "        incremental: Math.round(Math.max(0, d.revenue - baselineMonthlyRevenue) * 100) / 100,",
    "        views: d.views,",
    "        count: d.count",
    "      };",
    "    });",
    "",
    "  // Platform distribution.",
    "  const platMap: Record<string, { count: number; views: number }> = {};",
    "  for (const c of content) {",
    "    if (!platMap[c.platform]) platMap[c.platform] = { count: 0, views: 0 };",
    "    platMap[c.platform].count += 1;",
    "    platMap[c.platform].views += c.views;",
    "  }",
    "  const platformDistribution = Object.keys(platMap)",
    "    .map((p) => ({ platform: p, count: platMap[p].count, views: platMap[p].views }))",
    "    .sort((a, b) => b.views - a.views);",
    "",
    "  const avgViralScore = content.length ? content.reduce((s, c) => s + c.viralScore, 0) / content.length : 0;",
    "  const engRate = engagementRate(content);",
    "",
    "  const topContent = [...content]",
    "    .sort((a, b) => b.views - a.views)",
    "    .slice(0, 5)",
    "    .map((c) => ({ id: c.id, title: c.title, views: c.views, likes: c.likes, topic: c.primaryTopic, platform: c.platform }));",
    "",
    "  // Value delivered, ported from value_breakdown (2 hours saved per piece).",
    "  const valueDelivered = {",
    "    contentTracked: content.length,",
    "    platformsReached: platformDistribution.length,",
    "    estimatedTimeSavedHours: content.length * 2",
    "  };",
    "",
    "  // Health score: churn proxied off the last-3-months revenue trend (declining →",
    "  // 30% churn, otherwise 10%), matching advanced_analytics.calculate_ltv.",
    "  const recentRevenues = monthlyTrend.slice(-3).map((m) => m.revenue);",
    "  let declining = recentRevenues.length >= 2;",
    "  for (let i = 1; i < recentRevenues.length; i++) if (recentRevenues[i] >= recentRevenues[i - 1]) declining = false;",
    "  const churnProbability = declining ? 0.3 : 0.1;",
    "  const growthRate = calculateGrowthRate(monthlyTrend.map((m) => m.revenue));",
    "  const cac = 50; // $50 referral bonus, ported from calculate_ltv.",
    "  const expectedLifetime = churnProbability > 0 ? 1 / churnProbability : 36;",
    "  const avgMonthlyRevenue = monthlyTrend.length ? recentRevenues.reduce((a, b) => a + b, 0) / Math.max(recentRevenues.length, 1) : 0;",
    "  const predictedLtv = avgMonthlyRevenue * expectedLifetime;",
    "  const ltvCac = cac > 0 ? predictedLtv / cac : 0;",
    "  const health = healthScore(growthRate, churnProbability, ltvCac);",
    "",
    "  return {",
    "    overview: { totalViews, totalLikes, totalRevenue: Math.round(totalRevenue * 100) / 100, totalContent: content.length },",
    "    growth: {",
    "      baselineRevenue: baselineMonthlyRevenue,",
    "      currentMonthlyAvg: Math.round((totalRevenue / Math.max(monthsActive, 1)) * 100) / 100,",
    "      incrementalRevenue: Math.round(incrementalRevenue * 100) / 100,",
    "      growthPercentage: Math.round(growthPercentage * 10) / 10",
    "    },",
    "    roi: {",
    "      appShare: Math.round(appShare * 100) / 100,",
    "      creatorEarnings: Math.round(creatorEarnings * 100) / 100,",
    "      shareRatePercentage: shareRate * 100,",
    "      valueMultiplier: Math.round(valueMultiplier * 10) / 10",
    "    },",
    "    health,",
    "    monthlyTrend,",
    "    platformDistribution,",
    "    productivity: { avgViralScore: Math.round(avgViralScore * 10) / 10, engagementRate: Math.round(engRate * 100) / 100 },",
    "    topContent,",
    "    valueDelivered,",
    "    monthsActive",
    "  };",
    "}",
    "",
    "// The next-best-actions, ported from advanced_analytics.predictive_analytics'",
    "// recommendation rules + algorithm_tracker's signal recommendations.",
    "export type NextAction = { priority: \"high\" | \"medium\" | \"low\"; category: string; message: string };",
    "",
    "export function nextBestActions(dashboard: GrowthDashboard): NextAction[] {",
    "  const actions: NextAction[] = [];",
    "  const growthRate = calculateGrowthRate(dashboard.monthlyTrend.map((m) => m.revenue));",
    "",
    "  // Ported: 'Growth rate is below 5%...'.",
    "  if (growthRate < 5) {",
    "    actions.push({",
    "      priority: \"high\",",
    "      category: \"growth\",",
    "      message: \"Growth is below 5%. Republish your best-performing content in a fresh format to reach new viewers.\"",
    "    });",
    "  }",
    "",
    "  // Ported: 'Revenue declining 10%+ recently. Check Algorithm Insights...'.",
    "  const revenues = dashboard.monthlyTrend.map((m) => m.revenue);",
    "  if (revenues.length >= 6) {",
    "    const recentAvg = revenues.slice(-3).reduce((a, b) => a + b, 0) / 3;",
    "    const olderAvg = revenues.slice(-6, -3).reduce((a, b) => a + b, 0) / 3;",
    "    if (olderAvg > 0 && recentAvg < olderAvg * 0.9) {",
    "      actions.push({",
    "        priority: \"high\",",
    "        category: \"retention\",",
    "        message: \"Revenue is down 10%+ recently. Review the algorithm insights for platform changes and adjust your posting cadence.\"",
    "      });",
    "    }",
    "  }",
    "",
    "  // Ported from algorithm_tracker: low engagement → shorter, stronger hooks.",
    "  if (dashboard.productivity.engagementRate > 0 && dashboard.productivity.engagementRate < 3) {",
    "    actions.push({",
    "      priority: \"medium\",",
    "      category: \"engagement\",",
    "      message: \"Engagement is under 3%. Try shorter videos with a stronger hook in the first 3 seconds.\"",
    "    });",
    "  }",
    "",
    "  if (dashboard.health.status === \"needs_attention\") {",
    "    actions.push({",
    "      priority: \"high\",",
    "      category: \"health\",",
    "      message: \"Your channel health needs attention. Focus on consistency: publish on your best days and lean into your top topic.\"",
    "    });",
    "  }",
    "",
    "  if (!actions.length) {",
    "    actions.push({",
    "      priority: \"low\",",
    "      category: \"growth\",",
    "      message: \"Things look healthy. Keep publishing on your best-performing platform and double down on what is working.\"",
    "    });",
    "  }",
    "",
    "  return actions;",
    "}",
    "",
    "// --- algorithm signals, ported from algorithm_tracker.track_platform_changes ---",
    "",
    "export type DetectedSignal = { type: string; severity: \"high\" | \"medium\" | \"low\"; changePercent: number; recommendation: string };",
    "",
    "export type PlatformTracking = {",
    "  platform: string;",
    "  status: \"tracked\" | \"insufficient_data\";",
    "  signals: DetectedSignal[];",
    "  recentEngagementRate: number;",
    "  recentAvgViews: number;",
    "  postingTimes: Array<{ hour: number; day: string }>;",
    "  trending: TrendingContent;",
    "};",
    "",
    "// Detect algorithm changes for a platform by comparing the most recent window of",
    "// content against the prior window (ported from track_platform_changes: needs 7+",
    "// pieces; fires engagement_rate_drop / reach_decline past their thresholds).",
    "export async function trackPlatform(platform: string, ownerId: string | undefined): Promise<PlatformTracking> {",
    "  const content = (await listContent({ ownerId, platform, limit: 60 }));",
    "  const postingTimes = postingTimesFor(platform);",
    "  const trending = trendingFor(platform);",
    "  if (content.length < 7) {",
    "    return { platform, status: \"insufficient_data\", signals: [], recentEngagementRate: 0, recentAvgViews: 0, postingTimes, trending };",
    "  }",
    "  const recent = content.slice(0, 7);",
    "  const previous = content.slice(7, 14);",
    "  const signals: DetectedSignal[] = [];",
    "",
    "  const recentEngagement = engagementRate(recent);",
    "  const previousEngagement = engagementRate(previous);",
    "  if (previousEngagement > 0) {",
    "    const change = ((recentEngagement - previousEngagement) / previousEngagement) * 100;",
    "    if (change < ALGORITHM_SIGNALS.engagement_rate_drop.threshold) {",
    "      signals.push({",
    "        type: \"engagement_rate_drop\",",
    "        severity: \"high\",",
    "        changePercent: Math.round(change * 100) / 100,",
    "        recommendation: `Engagement dropped ${Math.abs(change).toFixed(1)}%. Try shorter videos with stronger hooks.`",
    "      });",
    "    }",
    "  }",
    "",
    "  const recentReach = recent.reduce((s, c) => s + c.views, 0) / 7;",
    "  const previousReach = previous.length ? previous.reduce((s, c) => s + c.views, 0) / previous.length : 0;",
    "  if (previousReach > 0) {",
    "    const change = ((recentReach - previousReach) / previousReach) * 100;",
    "    if (change < ALGORITHM_SIGNALS.reach_decline.threshold) {",
    "      signals.push({",
    "        type: \"reach_decline\",",
    "        severity: \"high\",",
    "        changePercent: Math.round(change * 100) / 100,",
    "        recommendation: `Reach declined ${Math.abs(change).toFixed(1)}%. Post at different times and use trending hashtags.`",
    "      });",
    "    }",
    "  }",
    "",
    "  return {",
    "    platform,",
    "    status: \"tracked\",",
    "    signals,",
    "    recentEngagementRate: Math.round(recentEngagement * 100) / 100,",
    "    recentAvgViews: Math.round(recentReach),",
    "    postingTimes,",
    "    trending",
    "  };",
    "}",
    "",
    "// --- per-platform algorithm insight records, ported from ---",
    "// --- algorithm_insights_service.py (one row per platform, admin-published) ---",
    "",
    "export type RankingSignal = { signal: string; weight: \"high\" | \"medium\" | \"low\"; description: string; optimizationTip: string };",
    "",
    "export type AlgorithmInsight = {",
    "  id: string;",
    "  platform: string;",
    "  algorithmSummary: string;",
    "  rankingSignals: RankingSignal[];",
    "  updatedAt: string;",
    "};",
    "",
    "// Built-in defaults, so the panel is never empty even before an admin publishes",
    "// fresh insights (the graceful-degradation path when no LLM key is set).",
    "export const DEFAULT_RANKING_SIGNALS: Record<string, RankingSignal[]> = {",
    "  youtube: [",
    "    { signal: \"Average view duration\", weight: \"high\", description: \"How long viewers stay drives how widely a video is shown.\", optimizationTip: \"Open with a 5-second promise and pay it off; cut dead air.\" },",
    "    { signal: \"Click-through rate\", weight: \"high\", description: \"Thumbnail + title decide whether an impression becomes a view.\", optimizationTip: \"Test two thumbnails; make the title a curiosity gap.\" },",
    "    { signal: \"Session time\", weight: \"medium\", description: \"Videos that keep people on the platform get recommended more.\", optimizationTip: \"End screens should point to your most-watched related video.\" }",
    "  ],",
    "  tiktok: [",
    "    { signal: \"Completion rate\", weight: \"high\", description: \"Finishing (and re-watching) a short is the strongest positive signal.\", optimizationTip: \"Keep it under 30s and loop the ending back to the hook.\" },",
    "    { signal: \"Shares & saves\", weight: \"high\", description: \"Shares tell the algorithm the content is worth spreading.\", optimizationTip: \"Give viewers a reason to send it to a friend.\" }",
    "  ],",
    "  instagram: [",
    "    { signal: \"Sends per reach\", weight: \"high\", description: \"DMs/shares of a Reel weigh heavily in distribution.\", optimizationTip: \"Make relatable content people tag friends in.\" },",
    "    { signal: \"Watch time\", weight: \"medium\", description: \"Reels that hold attention get pushed to non-followers.\", optimizationTip: \"Front-load the payoff; keep captions tight.\" }",
    "  ]",
    "};",
    "",
    "export function defaultInsightFor(platform: string): AlgorithmInsight {",
    "  const signals = DEFAULT_RANKING_SIGNALS[platform] || DEFAULT_RANKING_SIGNALS.youtube;",
    "  return {",
    "    id: `default-${platform}`,",
    "    platform,",
    "    algorithmSummary: `${platform} currently rewards content that holds attention early and earns shares. Hook fast, keep it tight, and give viewers a reason to pass it on.`,",
    "    rankingSignals: signals,",
    "    updatedAt: \"\"",
    "  };",
    "}",
    "",
    "function rowToInsight(row: Record<string, unknown>): AlgorithmInsight {",
    "  const toSignals = (v: unknown): RankingSignal[] => {",
    "    let arr: unknown = v;",
    "    if (typeof v === \"string\" && v.trim()) { try { arr = JSON.parse(v); } catch { arr = []; } }",
    "    if (!Array.isArray(arr)) return [];",
    "    return arr.map((s) => {",
    "      const o = (s || {}) as Record<string, unknown>;",
    "      const weight = String(o.weight || \"medium\");",
    "      return {",
    "        signal: String(o.signal || \"\"),",
    "        weight: (weight === \"high\" || weight === \"low\" ? weight : \"medium\") as RankingSignal[\"weight\"],",
    "        description: String(o.description || \"\"),",
    "        optimizationTip: String(o.optimizationTip || o.optimization_tip || \"\")",
    "      };",
    "    });",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    platform: String(row.platform || \"\"),",
    "    algorithmSummary: String(row.algorithm_summary || \"\"),",
    "    rankingSignals: toSignals(row.ranking_signals),",
    "    updatedAt: row.updated_at ? String(row.updated_at) : \"\"",
    "  };",
    "}",
    "",
    "export async function getInsight(platform: string): Promise<AlgorithmInsight> {",
    "  if (!hasDatabase()) return defaultInsightFor(platform);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, platform, algorithm_summary, ranking_signals, updated_at",
    "      from creator_analytics_coaching_algorithm_insights",
    "      where platform = ${platform}",
    "      order by updated_at desc limit 1`;",
    "    return rows[0] ? rowToInsight(rows[0]) : defaultInsightFor(platform);",
    "  } catch {",
    "    return defaultInsightFor(platform);",
    "  }",
    "}",
    "",
    "export async function getAllInsights(): Promise<AlgorithmInsight[]> {",
    "  const out: AlgorithmInsight[] = [];",
    "  for (const p of PLATFORMS) out.push(await getInsight(p));",
    "  return out;",
    "}",
    "",
    "// Admin publishes / updates a platform's insight (ported from",
    "// algorithm_insights_service.refresh_insights' one-row-per-platform upsert).",
    "export async function publishInsight(platform: string, algorithmSummary: string, rankingSignals: RankingSignal[]): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const signals = JSON.stringify(rankingSignals || []);",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into creator_analytics_coaching_algorithm_insights (platform, algorithm_summary, ranking_signals, updated_at)",
    "      values (${platform}, ${algorithmSummary}, ${signals}, now())",
    "      on conflict (platform) do update set",
    "        algorithm_summary = excluded.algorithm_summary,",
    "        ranking_signals = excluded.ranking_signals,",
    "        updated_at = now()`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// --- coaching reports, ported from coaching_service.py + /coaching/progress ---",
    "",
    "export type CategoryScore = { score: number; label: string; details: string };",
    "export type CoachingStrength = { area: string; detail: string; impact: string };",
    "export type CoachingImprovement = { area: string; recommendedChange: string; whyItMatters: string; difficulty: \"easy\" | \"medium\" | \"hard\"; priority: \"high\" | \"medium\" | \"low\" };",
    "export type QuickWin = { action: string; expectedImpact: string; timeToImplement: string };",
    "",
    "// A coaching report, ported from coaching_service.generate_report's report_doc:",
    "// an overall score + summary, the five category scores, strengths, improvements,",
    "// and quick wins.",
    "export type CoachingReport = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  contentId: string | null;",
    "  contentTitle: string;",
    "  overallScore: number;",
    "  summary: string;",
    "  categoryScores: Record<string, CategoryScore>;",
    "  strengths: CoachingStrength[];",
    "  improvements: CoachingImprovement[];",
    "  quickWins: QuickWin[];",
    "  createdAt: string;",
    "};",
    "",
    "// The five coaching categories, ported verbatim from REPORT_PROMPT_TEMPLATE's",
    "// category_scores block.",
    "export const COACHING_CATEGORIES: Array<{ key: string; label: string }> = [",
    "  { key: \"delivery\", label: \"Delivery & Presentation\" },",
    "  { key: \"content_structure\", label: \"Content Structure & Flow\" },",
    "  { key: \"emotional_connection\", label: \"Emotional Connection\" },",
    "  { key: \"audience_retention\", label: \"Audience Retention\" },",
    "  { key: \"production_value\", label: \"Production & Polish\" }",
    "];",
    "",
    "const fallbackReports: CoachingReport[] = [",
    "  {",
    "    id: \"sample-report-1\",",
    "    ownerId: null,",
    "    contentId: \"sample-1\",",
    "    contentTitle: \"How I edit in half the time\",",
    "    overallScore: 74,",
    "    summary: \"A strong, useful walkthrough with a clear payoff. Tighten the open and vary your pacing and this jumps a tier.\",",
    "    categoryScores: {",
    "      delivery: { score: 72, label: \"Delivery & Presentation\", details: \"Confident and clear; a little flat in the middle third.\" },",
    "      content_structure: { score: 80, label: \"Content Structure & Flow\", details: \"Logical steps that are easy to follow.\" },",
    "      emotional_connection: { score: 65, label: \"Emotional Connection\", details: \"Informative but could open with a personal stake.\" },",
    "      audience_retention: { score: 70, label: \"Audience Retention\", details: \"Good, but the intro runs long before the first payoff.\" },",
    "      production_value: { score: 82, label: \"Production & Polish\", details: \"Clean edit, good audio, readable captions.\" }",
    "    },",
    "    strengths: [",
    "      { area: \"Content Structure & Flow\", detail: \"Every step builds on the last\", impact: \"Viewers always know where they are, which keeps them watching.\" }",
    "    ],",
    "    improvements: [",
    "      { area: \"Audience Retention\", recommendedChange: \"Cut the intro to under 10 seconds and lead with the result\", whyItMatters: \"The first 15 seconds decide whether the algorithm keeps showing your video.\", difficulty: \"easy\", priority: \"high\" }",
    "    ],",
    "    quickWins: [",
    "      { action: \"Add a one-line hook promising the outcome\", expectedImpact: \"Higher retention in the first 15s\", timeToImplement: \"next video\" }",
    "    ],",
    "    createdAt: \"2025-04-02T00:00:00.000Z\"",
    "  }",
    "];",
    "",
    "function rowToReport(row: Record<string, unknown>): CoachingReport {",
    "  const parse = <T,>(v: unknown, fallback: T): T => {",
    "    if (v == null) return fallback;",
    "    if (typeof v === \"string\") { try { return JSON.parse(v) as T; } catch { return fallback; } }",
    "    return v as T;",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    "    contentId: row.content_id != null ? String(row.content_id) : null,",
    "    contentTitle: String(row.content_title || \"Untitled\"),",
    "    overallScore: Number(row.overall_score || 0),",
    "    summary: String(row.summary || \"\"),",
    "    categoryScores: parse<Record<string, CategoryScore>>(row.category_scores, {}),",
    "    strengths: parse<CoachingStrength[]>(row.strengths, []),",
    "    improvements: parse<CoachingImprovement[]>(row.improvements, []),",
    "    quickWins: parse<QuickWin[]>(row.quick_wins, []),",
    "    createdAt: row.created_at ? String(row.created_at) : \"\"",
    "  };",
    "}",
    "",
    "export async function listReports(ownerId: string | undefined, limit = 100): Promise<CoachingReport[]> {",
    "  const cap = Math.min(200, Math.max(1, limit));",
    "  if (!hasDatabase()) return fallbackReports.filter((r) => !ownerId || r.ownerId === ownerId).slice(0, cap);",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, content_id, content_title, overall_score, summary,",
    "        category_scores, strengths, improvements, quick_wins, created_at",
    "      from creator_analytics_coaching_reports",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "      order by created_at desc limit ${cap}`;",
    "    return rows.map(rowToReport);",
    "  } catch {",
    "    return fallbackReports.slice(0, cap);",
    "  }",
    "}",
    "",
    "export async function getReport(id: string, ownerId?: string): Promise<CoachingReport | null> {",
    "  if (!hasDatabase()) {",
    "    const found = fallbackReports.find((r) => r.id === id) || null;",
    "    if (found && ownerId && found.ownerId && found.ownerId !== ownerId) return null;",
    "    return found;",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, content_id, content_title, overall_score, summary,",
    "        category_scores, strengths, improvements, quick_wins, created_at",
    "      from creator_analytics_coaching_reports",
    "      where id = ${id} and (${owner}::uuid is null or owner_id = ${owner})",
    "      limit 1`;",
    "    return rows[0] ? rowToReport(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateReportInput = {",
    "  ownerId: string | null;",
    "  contentId?: string | null;",
    "  contentTitle: string;",
    "  overallScore: number;",
    "  summary: string;",
    "  categoryScores: Record<string, CategoryScore>;",
    "  strengths: CoachingStrength[];",
    "  improvements: CoachingImprovement[];",
    "  quickWins: QuickWin[];",
    "};",
    "",
    "export async function createReport(input: CreateReportInput): Promise<CoachingReport | null> {",
    "  if (!hasDatabase()) return null;",
    "  const score = Math.min(100, Math.max(0, Math.round(input.overallScore)));",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into creator_analytics_coaching_reports (",
    "        owner_id, content_id, content_title, overall_score, summary,",
    "        category_scores, strengths, improvements, quick_wins",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.contentId || null}, ${input.contentTitle}, ${score},",
    "        ${input.summary}, ${JSON.stringify(input.categoryScores || {})},",
    "        ${JSON.stringify(input.strengths || [])}, ${JSON.stringify(input.improvements || [])},",
    "        ${JSON.stringify(input.quickWins || [])}",
    "      )",
    "      returning id, owner_id, content_id, content_title, overall_score, summary,",
    "        category_scores, strengths, improvements, quick_wins, created_at`;",
    "    return rows[0] ? rowToReport(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// A quick baseline coaching report generated from a content piece's own metrics,",
    "// so the feature works without an LLM key. It scores the five categories off",
    "// engagement/viral signals and produces the strengths/improvements/quick-wins in",
    "// the exact shape coaching_service.generate_report returns.",
    "export function baselineReportFor(content: ContentPiece): CreateReportInput {",
    "  const eng = engagementRate([content]);",
    "  const clamp = (n: number) => Math.min(100, Math.max(0, Math.round(n)));",
    "  const retention = clamp(50 + content.viralScore * 0.4);",
    "  const emotional = clamp(40 + eng * 6);",
    "  const delivery = clamp(55 + content.viralScore * 0.3);",
    "  const structure = clamp(60 + content.viralScore * 0.25);",
    "  const production = clamp(60 + content.viralScore * 0.3);",
    "  const overall = Math.round((retention + emotional + delivery + structure + production) / 5);",
    "  const strengths: CoachingStrength[] = [];",
    "  const improvements: CoachingImprovement[] = [];",
    "  if (content.viralScore >= 70) {",
    "    strengths.push({ area: \"Audience Retention\", detail: \"This piece held attention well\", impact: \"High retention is what earns broader distribution.\" });",
    "  }",
    "  if (eng < 3) {",
    "    improvements.push({ area: \"Emotional Connection\", recommendedChange: \"Open with a personal stake or a bold claim\", whyItMatters: \"Engagement under 3% signals the audience is not reacting; a stronger hook fixes it.\", difficulty: \"easy\", priority: \"high\" });",
    "  } else {",
    "    improvements.push({ area: \"Content Structure & Flow\", recommendedChange: \"Trim the middle third and get to the payoff sooner\", whyItMatters: \"Tighter pacing keeps the retention curve high.\", difficulty: \"medium\", priority: \"medium\" });",
    "  }",
    "  return {",
    "    ownerId: content.ownerId,",
    "    contentId: content.id,",
    "    contentTitle: content.title,",
    "    overallScore: overall,",
    "    summary: overall >= 75",
    "      ? \"Strong piece. Keep the format and sharpen the open to push it higher.\"",
    "      : \"Solid foundation. The biggest lever is a faster, stronger hook.\",",
    "    categoryScores: {",
    "      delivery: { score: delivery, label: \"Delivery & Presentation\", details: \"Based on how this piece performed against your other content.\" },",
    "      content_structure: { score: structure, label: \"Content Structure & Flow\", details: \"Pacing inferred from viral score and engagement.\" },",
    "      emotional_connection: { score: emotional, label: \"Emotional Connection\", details: `Engagement rate of ${eng.toFixed(1)}% drives this score.` },",
    "      audience_retention: { score: retention, label: \"Audience Retention\", details: \"Estimated from the viral score.\" },",
    "      production_value: { score: production, label: \"Production & Polish\", details: \"Estimated; connect richer data for a precise read.\" }",
    "    },",
    "    strengths,",
    "    improvements,",
    "    quickWins: [",
    "      { action: \"Add a 3-second hook that promises the payoff\", expectedImpact: \"Higher early retention\", timeToImplement: \"next video\" },",
    "      { action: `Post on your best day for ${content.platform}`, expectedImpact: \"More reach on publish\", timeToImplement: \"5 minutes\" }",
    "    ]",
    "  };",
    "}",
    "",
    "// Coaching progress over time, ported from coaching_routes.py /coaching/progress:",
    "// the per-report timeline, category averages, and first→last improvement.",
    "export type CoachingProgress = {",
    "  reportsCount: number;",
    "  timeline: Array<{ reportId: string; contentTitle: string; overallScore: number; categories: Record<string, number>; date: string }>;",
    "  categoryAverages: Record<string, number>;",
    "  improvement: number;",
    "  latestScore: number;",
    "  firstScore: number;",
    "};",
    "",
    "export async function coachingProgress(ownerId: string | undefined): Promise<CoachingProgress> {",
    "  const reports = (await listReports(ownerId, 200)).slice().sort((a, b) => a.createdAt.localeCompare(b.createdAt));",
    "  if (!reports.length) {",
    "    return { reportsCount: 0, timeline: [], categoryAverages: {}, improvement: 0, latestScore: 0, firstScore: 0 };",
    "  }",
    "  const timeline = reports.map((r) => {",
    "    const categories: Record<string, number> = {};",
    "    for (const key of Object.keys(r.categoryScores)) categories[key] = r.categoryScores[key]?.score || 0;",
    "    return { reportId: r.id, contentTitle: r.contentTitle, overallScore: r.overallScore, categories, date: r.createdAt };",
    "  });",
    "  const catTotals: Record<string, number> = {};",
    "  const catCounts: Record<string, number> = {};",
    "  for (const entry of timeline) {",
    "    for (const cat of Object.keys(entry.categories)) {",
    "      catTotals[cat] = (catTotals[cat] || 0) + entry.categories[cat];",
    "      catCounts[cat] = (catCounts[cat] || 0) + 1;",
    "    }",
    "  }",
    "  const categoryAverages: Record<string, number> = {};",
    "  for (const cat of Object.keys(catTotals)) categoryAverages[cat] = Math.round((catTotals[cat] / catCounts[cat]) * 10) / 10;",
    "  const improvement = timeline.length >= 2 ? timeline[timeline.length - 1].overallScore - timeline[0].overallScore : 0;",
    "  return {",
    "    reportsCount: reports.length,",
    "    timeline,",
    "    categoryAverages,",
    "    improvement,",
    "    latestScore: timeline[timeline.length - 1].overallScore,",
    "    firstScore: timeline[0].overallScore",
    "  };",
    "}",
    "",
    "// An LLM key is optional; without it we serve built-in algorithm insights +",
    "// metric-based baseline coaching reports (never blocks the UI).",
    "export function llmConfigured(): boolean {",
    "  return Boolean((process.env.CREATOR_ANALYTICS_LLM_KEY || \"\").trim());",
    "}",
    "",
    "export function creatorAnalyticsEnabled(): boolean {",
    "  return process.env.FEATURE_CREATOR_ANALYTICS !== \"false\";",
    "}"
  ]);
}

// ---- src/app/api/creator-analytics/content/route.ts (list + log content) ----

function contentApiFile(): GeneratedModuleFile {
  return file("src/app/api/creator-analytics/content/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listContent, createContent, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!creatorAnalyticsEnabled()) return NextResponse.json({ ok: false, message: "Creator analytics are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  // Creators see only their own content; admins see the whole account.",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const content = await listContent({",
    '    q: url.searchParams.get("q") || undefined,',
    '    platform: url.searchParams.get("platform") || undefined,',
    "    ownerId",
    "  });",
    "  return NextResponse.json({ ok: true, content });",
    "}",
    "",
    "// Log a published piece of content, scoped to the signed-in creator via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to track content." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give this content a title." }, { status: 400 });',
    "  }",
    "  const num = (v: unknown) => (typeof v === \"number\" ? v : Number(v) || 0);",
    "  const created = await createContent({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    title,",
    '    platform: typeof body.platform === "string" ? body.platform : undefined,',
    '    primaryTopic: typeof body.primaryTopic === "string" ? body.primaryTopic : undefined,',
    "    views: num(body.views),",
    "    likes: num(body.likes),",
    "    comments: num(body.comments),",
    "    shares: num(body.shares),",
    "    revenue: num(body.revenue),",
    "    viralScore: num(body.viralScore)",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to track content." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, content: created });',
    "}"
  ]);
}

// ---- src/app/api/creator-analytics/reports/route.ts (list + generate) -------

function reportsApiFile(): GeneratedModuleFile {
  return file("src/app/api/creator-analytics/reports/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listReports, getContent, createReport, baselineReportFor, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!creatorAnalyticsEnabled()) return NextResponse.json({ ok: false, message: "Creator analytics are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const reports = await listReports(ownerId);",
    "  return NextResponse.json({ ok: true, reports });",
    "}",
    "",
    "// Generate a coaching report for one of the creator's content pieces, ported",
    "// from POST /coaching/reports. Uses a metric-based baseline so it works without",
    "// an LLM key; scoped to the signed-in creator via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to generate a report." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const contentId = typeof body.contentId === "string" ? body.contentId : "";',
    '  if (!contentId) return NextResponse.json({ ok: false, message: "Choose a piece of content to analyze." }, { status: 400 });',
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    "  const content = await getContent(contentId, canAccessAdmin(user?.role) ? undefined : ownerId);",
    '  if (!content) return NextResponse.json({ ok: false, message: "That content was not found." }, { status: 404 });',
    "  const report = await createReport(baselineReportFor(content));",
    '  if (!report) return NextResponse.json({ ok: false, message: "Connect a database to save reports." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, report });",
    "}"
  ]);
}

// ---- src/app/api/creator-analytics/insights/route.ts (list + admin publish) -

function insightsApiFile(): GeneratedModuleFile {
  return file("src/app/api/creator-analytics/insights/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getAllInsights, publishInsight, PLATFORMS, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    'import type { RankingSignal } from "@/lib/db/creator-analytics";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!creatorAnalyticsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const insights = await getAllInsights();",
    "  return NextResponse.json({ ok: true, insights });",
    "}",
    "",
    "// Publish a platform's algorithm insight — admins only (the operator control",
    "// behind algorithm_insights_service.refresh_insights).",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const platform = typeof body.platform === "string" ? body.platform : "";',
    "  if (!(PLATFORMS as readonly string[]).includes(platform)) {",
    '    return NextResponse.json({ ok: false, message: "Unknown platform." }, { status: 400 });',
    "  }",
    '  const summary = typeof body.algorithmSummary === "string" ? body.algorithmSummary.trim() : "";',
    "  const rawSignals = Array.isArray(body.rankingSignals) ? body.rankingSignals : [];",
    "  const rankingSignals: RankingSignal[] = rawSignals.map((s) => {",
    "    const o = (s || {}) as Record<string, unknown>;",
    '    const weight = String(o.weight || "medium");',
    "    return {",
    '      signal: String(o.signal || ""),',
    '      weight: (weight === "high" || weight === "low" ? weight : "medium") as RankingSignal["weight"],',
    '      description: String(o.description || ""),',
    '      optimizationTip: String(o.optimizationTip || "")',
    "    };",
    "  }).filter((s) => s.signal);",
    "  if (!summary && !rankingSignals.length) {",
    '    return NextResponse.json({ ok: false, message: "Add a summary or at least one ranking signal." }, { status: 400 });',
    "  }",
    "  const ok = await publishInsight(platform, summary, rankingSignals);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to publish insights." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/creator-analytics/page.tsx (growth dashboard + next actions) ---

function dashboardPageFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { buildGrowthDashboard, nextBestActions, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    'import { LogContentForm } from "./log-content-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CreatorAnalyticsPage() {",
    "  if (!creatorAnalyticsEnabled()) {",
    '    return (<main className="shell"><h1>Creator analytics</h1><p>Creator analytics are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/creator-analytics");',
    "  const user = await getCurrentUser();",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const dashboard = await buildGrowthDashboard(ownerId);",
    "  const actions = nextBestActions(dashboard);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Creator analytics</p>',
    "      <h1>Your growth at a glance</h1>",
    "      <p>See how your content is performing, where the algorithm is moving, and the next best action to grow.</p>",
    "",
    '      <section className="grid">',
    '        <article className="card"><span>Total views</span><strong>{dashboard.overview.totalViews.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Total likes</span><strong>{dashboard.overview.totalLikes.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Revenue</span><strong>${dashboard.overview.totalRevenue.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Content tracked</span><strong>{dashboard.overview.totalContent}</strong></article>',
    "      </section>",
    "",
    '      <section className="grid">',
    '        <article className="card"><span>Channel health</span><strong>{dashboard.health.score} · {dashboard.health.status.replace("_", " ")}</strong></article>',
    '        <article className="card"><span>Incremental revenue</span><strong>${dashboard.growth.incrementalRevenue.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Value multiplier</span><strong>{dashboard.roi.valueMultiplier}x</strong></article>',
    '        <article className="card"><span>Engagement rate</span><strong>{dashboard.productivity.engagementRate}%</strong></article>',
    "      </section>",
    "",
    "      <h2>Next best actions</h2>",
    '      <section className="panel-list">',
    "        {actions.map((a, i) => (",
    '          <article className="wide-card" key={i}>',
    "            <span>{a.priority} · {a.category}</span>",
    "            <p>{a.message}</p>",
    "          </article>",
    "        ))}",
    "      </section>",
    "",
    "      {dashboard.monthlyTrend.length > 0 ? (",
    "        <>",
    "          <h2>Monthly trend</h2>",
    '          <section className="panel-list">',
    "            {dashboard.monthlyTrend.map((m) => (",
    '              <article className="wide-card" key={m.month}>',
    "                <span>{m.monthLabel}</span>",
    "                <strong>${m.revenue.toLocaleString()}</strong>",
    '                <p className="note">{m.views.toLocaleString()} views · {m.count} posts</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    "      {dashboard.topContent.length > 0 ? (",
    "        <>",
    "          <h2>Top content</h2>",
    '          <section className="panel-list">',
    "            {dashboard.topContent.map((c) => (",
    '              <article className="wide-card" key={c.id}>',
    "                <span>{c.platform} · {c.topic}</span>",
    "                <strong>{c.title}</strong>",
    '                <p className="note">{c.views.toLocaleString()} views · {c.likes.toLocaleString()} likes</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    '      <p className="stack">',
    '        <Link className="button" href="/creator-analytics/algorithm">Algorithm insights</Link>',
    '        <Link className="button" href="/creator-analytics/coaching">Coaching reports</Link>',
    "      </p>",
    "",
    "      <h2>Log content</h2>",
    "      <p>Add a piece you published so it flows into your growth dashboard.</p>",
    "      <LogContentForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/log-content-form.tsx (client) ----------------

function logContentFormFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/log-content-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    'const PLATFORMS = ["youtube", "tiktok", "instagram", "twitter", "linkedin", "facebook"];',
    "",
    "export function LogContentForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/creator-analytics/content", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          platform: form.get("platform"),',
    '          primaryTopic: form.get("primaryTopic"),',
    '          views: Number(form.get("views") || 0),',
    '          likes: Number(form.get("likes") || 0),',
    '          comments: Number(form.get("comments") || 0),',
    '          shares: Number(form.get("shares") || 0),',
    '          revenue: Number(form.get("revenue") || 0),',
    '          viralScore: Number(form.get("viralScore") || 0)',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Content logged.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Logged</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Content title" aria-label="Content title" required />',
    '      <select className="input" name="platform" aria-label="Platform" defaultValue="youtube">',
    "        {PLATFORMS.map((p) => (",
    "          <option key={p} value={p}>{p}</option>",
    "        ))}",
    "      </select>",
    '      <input className="input" name="primaryTopic" placeholder="Primary topic (e.g. productivity)" aria-label="Primary topic" />',
    '      <input className="input" name="views" type="number" min="0" placeholder="Views" aria-label="Views" />',
    '      <input className="input" name="likes" type="number" min="0" placeholder="Likes" aria-label="Likes" />',
    '      <input className="input" name="comments" type="number" min="0" placeholder="Comments" aria-label="Comments" />',
    '      <input className="input" name="shares" type="number" min="0" placeholder="Shares" aria-label="Shares" />',
    '      <input className="input" name="revenue" type="number" min="0" step="0.01" placeholder="Revenue ($)" aria-label="Revenue" />',
    '      <input className="input" name="viralScore" type="number" min="0" max="100" placeholder="Viral score (0-100)" aria-label="Viral score" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Log content"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/algorithm/page.tsx (algorithm insights) ------

function algorithmPageFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/algorithm/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getAllInsights, trackPlatform, PLATFORMS, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    'import { PublishInsightForm } from "./publish-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AlgorithmInsightsPage() {",
    "  if (!creatorAnalyticsEnabled()) {",
    '    return (<main className="shell"><h1>Algorithm insights</h1><p>Creator analytics are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/creator-analytics/algorithm");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = isAdmin ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const insights = await getAllInsights();",
    "  // Signal tracking for the creator's own content, per platform.",
    "  const tracking = await Promise.all(PLATFORMS.map((p) => trackPlatform(p, ownerId)));",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Algorithm insights</p>',
    "      <h1>What each algorithm favors right now</h1>",
    "      <p>Ranking signals to optimize for, plus a read on how your own recent content is trending.</p>",
    "",
    '      <section className="panel-list">',
    "        {insights.map((ins) => (",
    '          <article className="wide-card" key={ins.id}>',
    "            <span>{ins.platform}</span>",
    "            <strong>{ins.algorithmSummary}</strong>",
    "            {ins.rankingSignals.length > 0 ? (",
    '              <ul className="stack">',
    "                {ins.rankingSignals.map((s, i) => (",
    "                  <li key={i}>",
    "                    <strong>{s.signal}</strong> <span className=\"note\">({s.weight})</span>",
    '                    <p className="note">{s.description}</p>',
    '                    <p className="note">Tip: {s.optimizationTip}</p>',
    "                  </li>",
    "                ))}",
    "              </ul>",
    "            ) : null}",
    "          </article>",
    "        ))}",
    "      </section>",
    "",
    "      <h2>How your content is trending</h2>",
    '      <section className="panel-list">',
    "        {tracking.map((t) => (",
    '          <article className="wide-card" key={t.platform}>',
    "            <span>{t.platform}</span>",
    "            {t.status === \"insufficient_data\" ? (",
    '              <p className="note">Not enough content on this platform yet to detect algorithm shifts.</p>',
    "            ) : (",
    "              <>",
    '                <p className="note">Engagement {t.recentEngagementRate}% · {t.recentAvgViews.toLocaleString()} avg views</p>',
    "                {t.signals.length > 0 ? (",
    "                  t.signals.map((s, i) => (",
    '                    <p className="note" role="status" key={i}>{s.severity}: {s.recommendation}</p>',
    "                  ))",
    "                ) : (",
    '                  <p className="note">No warning signals — steady as she goes.</p>',
    "                )}",
    "              </>",
    "            )}",
    "            <p className=\"note\">Trending: {t.trending.types.join(\", \")} · {t.trending.optimalLength}</p>",
    "          </article>",
    "        ))}",
    "      </section>",
    "",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Publish algorithm insight</h2>",
    "          <p>Update the ranking-signal guidance a platform shows to creators.</p>",
    "          <PublishInsightForm />",
    "        </>",
    "      ) : null}",
    "",
    '      <p><Link className="button" href="/creator-analytics">Back to dashboard</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/algorithm/publish-form.tsx (client, admin) ---

function publishFormFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/algorithm/publish-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    'const PLATFORMS = ["youtube", "tiktok", "instagram", "twitter", "linkedin", "facebook"];',
    "",
    "// Publish one ranking signal + a summary for a platform. Ported in spirit from",
    "// algorithm_insights_service.refresh_insights (one row per platform).",
    "export function PublishInsightForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    '    const signal = String(form.get("signal") || "").trim();',
    "    const rankingSignals = signal",
    "      ? [{",
    "          signal,",
    '          weight: String(form.get("weight") || "medium"),',
    '          description: String(form.get("description") || ""),',
    '          optimizationTip: String(form.get("optimizationTip") || "")',
    "        }]",
    "      : [];",
    "    try {",
    '      const response = await fetch("/api/creator-analytics/insights", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          platform: form.get("platform"),',
    '          algorithmSummary: form.get("algorithmSummary"),',
    "          rankingSignals",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not publish this insight.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Insight published.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Published</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <select className="input" name="platform" aria-label="Platform" defaultValue="youtube">',
    "        {PLATFORMS.map((p) => (",
    "          <option key={p} value={p}>{p}</option>",
    "        ))}",
    "      </select>",
    '      <textarea className="input" name="algorithmSummary" rows={2} placeholder="What the algorithm favors right now" aria-label="Algorithm summary" />',
    '      <input className="input" name="signal" placeholder="Ranking signal name" aria-label="Ranking signal" />',
    '      <select className="input" name="weight" aria-label="Weight" defaultValue="high">',
    '        <option value="high">high</option>',
    '        <option value="medium">medium</option>',
    '        <option value="low">low</option>',
    "      </select>",
    '      <input className="input" name="description" placeholder="How it affects distribution" aria-label="Signal description" />',
    '      <input className="input" name="optimizationTip" placeholder="How to optimize for it" aria-label="Optimization tip" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Publishing…" : "Publish insight"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/coaching/page.tsx (reports + progress) -------

function coachingPageFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/coaching/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listReports, listContent, coachingProgress, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    'import { GenerateReportForm } from "./generate-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CoachingReportsPage() {",
    "  if (!creatorAnalyticsEnabled()) {",
    '    return (<main className="shell"><h1>Coaching</h1><p>Creator analytics are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/creator-analytics/coaching");',
    "  const user = await getCurrentUser();",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const [reports, content, progress] = await Promise.all([",
    "    listReports(ownerId),",
    "    listContent({ ownerId, limit: 100 }),",
    "    coachingProgress(ownerId)",
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Coaching</p>',
    "      <h1>Coaching reports</h1>",
    "      <p>Get an honest, actionable read on each piece — what worked, what to change, and quick wins for next time.</p>",
    "",
    "      {progress.reportsCount >= 2 ? (",
    '        <section className="grid">',
    '          <article className="card"><span>Latest score</span><strong>{progress.latestScore}</strong></article>',
    '          <article className="card"><span>First score</span><strong>{progress.firstScore}</strong></article>',
    '          <article className="card"><span>Improvement</span><strong>{progress.improvement >= 0 ? "+" : ""}{progress.improvement}</strong></article>',
    '          <article className="card"><span>Reports</span><strong>{progress.reportsCount}</strong></article>',
    "        </section>",
    "      ) : null}",
    "",
    "      <h2>Generate a report</h2>",
    "      {content.length === 0 ? (",
    '        <p className="note">Log some content on your dashboard first, then generate a report on it.</p>',
    "      ) : (",
    "        <GenerateReportForm content={content.map((c) => ({ id: c.id, title: c.title }))} />",
    "      )}",
    "",
    "      <h2>Your reports</h2>",
    "      {reports.length === 0 ? (",
    '        <p className="note">No reports yet. Generate your first one above.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {reports.map((r) => (",
    '            <Link className="wide-card" key={r.id} href={`/creator-analytics/coaching/${r.id}`}>',
    "              <span>Score {r.overallScore}</span>",
    "              <strong>{r.contentTitle}</strong>",
    '              <p className="note">{r.summary}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    '      <p><Link className="button" href="/creator-analytics">Back to dashboard</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/coaching/generate-form.tsx (client) ----------

function generateFormFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/coaching/generate-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function GenerateReportForm({ content }: { content: Array<{ id: string; title: string }> }) {",
    "  const router = useRouter();",
    '  const [contentId, setContentId] = useState(content[0]?.id || "");',
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    if (!contentId) return;",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/creator-analytics/reports", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ contentId })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not generate a report.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      if (data.report?.id) {",
    "        router.push(`/creator-analytics/coaching/${data.report.id}`);",
    "      } else {",
    "        router.refresh();",
    "      }",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <select className="input" aria-label="Choose content" value={contentId} onChange={(e) => setContentId(e.target.value)}>',
    "        {content.map((c) => (",
    "          <option key={c.id} value={c.id}>{c.title}</option>",
    "        ))}",
    "      </select>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "working" || !contentId}>',
    '        {status === "working" ? "Analyzing…" : "Generate report"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/creator-analytics/coaching/[id]/page.tsx (report detail) -------

function coachingDetailPageFile(): GeneratedModuleFile {
  return file("src/app/creator-analytics/coaching/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getReport, COACHING_CATEGORIES, creatorAnalyticsEnabled } from "@/lib/db/creator-analytics";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CoachingReportDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!creatorAnalyticsEnabled()) {",
    '    return (<main className="shell"><h1>Coaching</h1><p>Creator analytics are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/creator-analytics/coaching");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const report = await getReport(id, ownerId);",
    "  if (!report) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Coaching report</p>',
    "      <h1>{report.contentTitle}</h1>",
    '      <p className="note">Overall score {report.overallScore}/100</p>',
    "      <p>{report.summary}</p>",
    "",
    "      <h2>Category scores</h2>",
    '      <section className="grid">',
    "        {COACHING_CATEGORIES.map((cat) => {",
    "          const c = report.categoryScores[cat.key];",
    "          if (!c) return null;",
    "          return (",
    '            <article className="card" key={cat.key}>',
    "              <span>{c.label || cat.label}</span>",
    "              <strong>{c.score}</strong>",
    "              {c.details ? <p className=\"note\">{c.details}</p> : null}",
    "            </article>",
    "          );",
    "        })}",
    "      </section>",
    "",
    "      {report.strengths.length > 0 ? (",
    "        <>",
    "          <h2>Strengths</h2>",
    '          <section className="panel-list">',
    "            {report.strengths.map((s, i) => (",
    '              <article className="wide-card" key={i}>',
    "                <span>{s.area}</span>",
    "                <strong>{s.detail}</strong>",
    '                <p className="note">{s.impact}</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    "      {report.improvements.length > 0 ? (",
    "        <>",
    "          <h2>What to improve</h2>",
    '          <section className="panel-list">',
    "            {report.improvements.map((imp, i) => (",
    '              <article className="wide-card" key={i}>',
    "                <span>{imp.priority} · {imp.difficulty} · {imp.area}</span>",
    "                <strong>{imp.recommendedChange}</strong>",
    '                <p className="note">{imp.whyItMatters}</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    "      {report.quickWins.length > 0 ? (",
    "        <>",
    "          <h2>Quick wins</h2>",
    '          <section className="panel-list">',
    "            {report.quickWins.map((w, i) => (",
    '              <article className="wide-card" key={i}>',
    "                <strong>{w.action}</strong>",
    '                <p className="note">{w.expectedImpact} · {w.timeToImplement}</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    "",
    '      <p><Link className="button" href="/creator-analytics/coaching">Back to reports</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const creatorAnalyticsModule: AppModule = {
  slug: "creator-analytics-coaching",
  name: "Creator Analytics & Coaching",
  tier: "optional",
  featureFlagEnv: "FEATURE_CREATOR_ANALYTICS",
  files: () => [
    analyticsLibFile(),
    contentApiFile(),
    reportsApiFile(),
    insightsApiFile(),
    dashboardPageFile(),
    logContentFormFile(),
    algorithmPageFile(),
    publishFormFile(),
    coachingPageFile(),
    generateFormFile(),
    coachingDetailPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists creator_analytics_coaching_content (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  title text not null default 'Untitled',",
      "  platform text not null default 'youtube',",
      "  primary_topic text not null default 'General',",
      "  views integer not null default 0,",
      "  likes integer not null default 0,",
      "  comments integer not null default 0,",
      "  shares integer not null default 0,",
      "  revenue numeric not null default 0,",
      "  viral_score integer not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists creator_analytics_coaching_content_owner_idx on creator_analytics_coaching_content (owner_id);",
      "create index if not exists creator_analytics_coaching_content_platform_idx on creator_analytics_coaching_content (platform);",
      "create index if not exists creator_analytics_coaching_content_created_idx on creator_analytics_coaching_content (created_at desc);",
      "",
      "create table if not exists creator_analytics_coaching_reports (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  content_id uuid references creator_analytics_coaching_content(id) on delete set null,",
      "  content_title text not null default 'Untitled',",
      "  overall_score integer not null default 0,",
      "  summary text not null default '',",
      "  category_scores jsonb not null default '{}'::jsonb,",
      "  strengths jsonb not null default '[]'::jsonb,",
      "  improvements jsonb not null default '[]'::jsonb,",
      "  quick_wins jsonb not null default '[]'::jsonb,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists creator_analytics_coaching_reports_owner_idx on creator_analytics_coaching_reports (owner_id);",
      "create index if not exists creator_analytics_coaching_reports_created_idx on creator_analytics_coaching_reports (created_at desc);",
      "",
      "create table if not exists creator_analytics_coaching_algorithm_insights (",
      "  id uuid primary key default gen_random_uuid(),",
      "  platform text not null unique,",
      "  algorithm_summary text not null default '',",
      "  ranking_signals jsonb not null default '[]'::jsonb,",
      "  updated_at timestamptz not null default now()",
      ");"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into creator_analytics_coaching_content (title, platform, primary_topic, views, likes, comments, shares, revenue, viral_score) values",
      "  ('How I edit in half the time', 'youtube', 'productivity', 42000, 2100, 180, 320, 210.50, 78),",
      "  ('3 hooks that stop the scroll', 'tiktok', 'growth', 128000, 9400, 640, 1500, 95.00, 91)",
      "on conflict do nothing;",
      "",
      "insert into creator_analytics_coaching_algorithm_insights (platform, algorithm_summary, ranking_signals) values",
      "  ('youtube', 'YouTube rewards content that holds attention early and keeps viewers on the platform.', '[{\"signal\":\"Average view duration\",\"weight\":\"high\",\"description\":\"How long viewers stay drives how widely a video is shown.\",\"optimizationTip\":\"Open with a 5-second promise and pay it off; cut dead air.\"}]'::jsonb)",
      "on conflict (platform) do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Creator Analytics & Coaching — set to false to switch the growth dashboard,",
    "# algorithm insights, and coaching reports off.",
    "FEATURE_CREATOR_ANALYTICS=true",
    "# Optional: an LLM key enables richer AI-written algorithm insights + coaching",
    "# reports. Without it, the module serves built-in insights + metric-based",
    "# baseline reports (it never blocks the UI).",
    "# CREATOR_ANALYTICS_LLM_KEY="
  ],
  homeLinks: () => ['        <a className="button" href="/creator-analytics">Creator analytics</a>'],
  navLinks: () => [{ href: "/creator-analytics", label: "Creator analytics" }]
};