// crm-follow-up — track people (guests, members, leads) through a pipeline and
// never let a follow-up fall through the cracks. Ported from ChurchConnect's real
// CRM code:
//   - backend/routes/church_crm.py — the PIPELINE_STAGES workflow (new →
//     contacted → interested → demo_scheduled → proposal_sent → negotiating →
//     won → lost), the lead model (name, contact, priority, notes, next action +
//     next-action date, source, last_contact), lead create/list/update with
//     status-change activity logging, the /leads/actionable buckets (overdue /
//     hot / new) and /analytics pipeline counts + needs-action-overdue count.
//   - src/components/GuestManagement.tsx — guest_status lifecycle, the
//     next_follow_up_date overdue check ("Needs Follow-up"), the follow-up
//     sequence template (Day 1 welcome, Day 3 call, Day 7 invite, Day 14
//     check-in, Day 30 resources), and how_they_heard sources.
//   - src/components/ConnectionInbox.tsx — the activity_log / followup_count
//     model and per-lead activity timeline.
// Generalized off the church framing into plain CRM copy so it drops into any
// app. Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_CRM); customers browse the pipeline, admins mutate.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/crm.ts (model + queries, ported from church_crm.py) ----------

function crmLibFile(): GeneratedModuleFile {
  return file("src/lib/db/crm.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The pipeline stages, ported from church_crm.py PIPELINE_STAGES. Generalized",
    "// off the church-sales framing into plain CRM language that fits guests,",
    "// members and leads alike.",
    "export type PipelineStage = { id: string; name: string; color: string };",
    "export const PIPELINE_STAGES: PipelineStage[] = [",
    '  { id: "new", name: "New", color: "blue" },',
    '  { id: "contacted", name: "Contacted", color: "purple" },',
    '  { id: "interested", name: "Interested", color: "amber" },',
    '  { id: "meeting_scheduled", name: "Meeting Scheduled", color: "orange" },',
    '  { id: "proposal_sent", name: "Proposal Sent", color: "pink" },',
    '  { id: "negotiating", name: "Negotiating", color: "indigo" },',
    '  { id: "won", name: "Won", color: "green" },',
    '  { id: "lost", name: "Lost", color: "gray" }',
    "];",
    'export const OPEN_STAGES = PIPELINE_STAGES.map((s) => s.id).filter((id) => id !== "won" && id !== "lost");',
    "export function stageName(id: string): string {",
    "  return PIPELINE_STAGES.find((s) => s.id === id)?.name || id;",
    "}",
    "",
    "// Priority levels, ported from church_crm.py crm_priority (high/medium/low)",
    "// with the same 3/2/1 priority_score mapping.",
    'export type Priority = "high" | "medium" | "low";',
    'export const PRIORITIES: Priority[] = ["high", "medium", "low"];',
    "export function priorityScore(priority: Priority): number {",
    '  return { high: 3, medium: 2, low: 1 }[priority] ?? 2;',
    "}",
    "",
    "// How-they-heard sources, ported from GuestManagement.tsx how_they_heard +",
    "// the ConnectionInbox source labels.",
    'export const SOURCES = ["referral", "social_media", "website", "walk_in", "event", "other"] as const;',
    "",
    "export type Lead = {",
    "  id: string;",
    "  name: string;",
    "  contactName: string;",
    "  email: string;",
    "  phone: string;",
    "  city: string;",
    "  state: string;",
    "  stage: string;",
    "  priority: Priority;",
    "  priorityScore: number;",
    "  source: string;",
    "  notes: string;",
    "  nextAction: string;",
    "  nextActionDate: string | null;",
    "  lastContact: string | null;",
    "  followupCount: number;",
    "  createdAt: string | null;",
    "};",
    "",
    "export type LeadFilters = { q?: string; stage?: string; priority?: string; limit?: number };",
    "",
    "// Ported from church_crm.py church_to_lead_format: normalize a stored row into",
    "// the shape the UI reads, defaulting priority to medium.",
    "function rowToLead(row: Record<string, unknown>): Lead {",
    '  const priority = (["high", "medium", "low"].includes(String(row.priority)) ? String(row.priority) : "medium") as Priority;',
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || "Unnamed"),',
    '    contactName: String(row.contact_name || ""),',
    '    email: String(row.email || ""),',
    '    phone: String(row.phone || ""),',
    '    city: String(row.city || ""),',
    '    state: String(row.state || ""),',
    '    stage: String(row.stage || "new"),',
    "    priority,",
    "    priorityScore: priorityScore(priority),",
    '    source: String(row.source || "other"),',
    '    notes: String(row.notes || ""),',
    '    nextAction: String(row.next_action || ""),',
    "    nextActionDate: row.next_action_date ? String(row.next_action_date) : null,",
    "    lastContact: row.last_contact ? String(row.last_contact) : null,",
    "    followupCount: Number(row.followup_count || 0),",
    "    createdAt: row.created_at ? String(row.created_at) : null",
    "  };",
    "}",
    "",
    "const fallbackLeads: Lead[] = [",
    '  { id: "sample-1", name: "Riverstone Group", contactName: "Dana Cole", email: "dana@example.com", phone: "555-0134", city: "Austin", state: "TX", stage: "interested", priority: "high", priorityScore: 3, source: "referral", notes: "Warm intro from an existing customer.", nextAction: "Send proposal", nextActionDate: "2000-01-01", lastContact: "2000-01-01", followupCount: 2, createdAt: null },',
    '  { id: "sample-2", name: "Maple & Co.", contactName: "Sam Ortiz", email: "sam@example.com", phone: "", city: "Denver", state: "CO", stage: "new", priority: "medium", priorityScore: 2, source: "website", notes: "", nextAction: "First call", nextActionDate: null, lastContact: null, followupCount: 0, createdAt: null }',
    "];",
    "",
    "// List + filter leads, ported from church_crm.py get_church_leads: optional",
    "// stage/priority filters and a name/contact/email/city search, sorted by",
    "// priority (high first) then most-recent.",
    "export async function listLeads(filters: LeadFilters = {}): Promise<Lead[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const stage = (filters.stage || "").trim();',
    '  const priority = (filters.priority || "").trim();',
    "  if (!hasDatabase()) {",
    "    return fallbackLeads",
    '      .filter((l) => !q || (l.name + " " + l.contactName + " " + l.email + " " + l.city).toLowerCase().includes(q))',
    "      .filter((l) => !stage || l.stage === stage)",
    "      .filter((l) => !priority || l.priority === priority)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const stageFilter = stage || null;",
    "    const priorityFilter = priority || null;",
    "    const rows = await sql`",
    "      select id, name, contact_name, email, phone, city, state, stage, priority,",
    "        source, notes, next_action, next_action_date, last_contact, followup_count, created_at",
    "      from crm_leads",
    "      where (${like}::text is null",
    "        or lower(name) like ${like}",
    "        or lower(contact_name) like ${like}",
    "        or lower(email) like ${like}",
    "        or lower(city) like ${like})",
    "        and (${stageFilter}::text is null or stage = ${stageFilter})",
    "        and (${priorityFilter}::text is null or priority = ${priorityFilter})",
    "      order by",
    "        case priority when 'high' then 3 when 'medium' then 2 else 1 end desc,",
    "        created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToLead);",
    "  } catch {",
    "    return fallbackLeads.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getLead(id: string): Promise<Lead | null> {",
    "  if (!hasDatabase()) return fallbackLeads.find((l) => l.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, name, contact_name, email, phone, city, state, stage, priority,",
    "        source, notes, next_action, next_action_date, last_contact, followup_count, created_at",
    "      from crm_leads where id = ${id} limit 1`;",
    "    return rows[0] ? rowToLead(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// A lead's activity timeline, ported from church_crm.py get_lead_activities /",
    "// ConnectionInbox activity_log.",
    "export type LeadActivity = {",
    "  id: string;",
    "  leadId: string;",
    "  type: string;",
    "  description: string;",
    "  createdAt: string | null;",
    "};",
    "",
    "function rowToActivity(row: Record<string, unknown>): LeadActivity {",
    "  return {",
    "    id: String(row.id),",
    "    leadId: String(row.lead_id),",
    '    type: String(row.type || "note"),',
    '    description: String(row.description || ""),',
    "    createdAt: row.created_at ? String(row.created_at) : null",
    "  };",
    "}",
    "",
    "export async function getLeadActivities(leadId: string, limit = 50): Promise<LeadActivity[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, lead_id, type, description, created_at from crm_lead_activities where lead_id = ${leadId} order by created_at desc limit ${limit}`;",
    "    return rows.map(rowToActivity);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type UpsertLeadInput = {",
    "  name: string;",
    "  contactName?: string;",
    "  email?: string;",
    "  phone?: string;",
    "  city?: string;",
    "  state?: string;",
    "  priority?: Priority;",
    "  source?: string;",
    "  notes?: string;",
    "  nextAction?: string;",
    "  nextActionDate?: string | null;",
    "  createdBy?: string | null;",
    "};",
    "",
    "// Create a lead, ported from church_crm.py create_church_lead: de-dupe on",
    "// name + city, start in the 'new' stage, and log a 'created' activity.",
    "export async function createLead(input: UpsertLeadInput): Promise<Lead | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    '    const name = input.name.trim();',
    '    const city = (input.city || "").trim();',
    "    const existing = await sql`select id from crm_leads where lower(name) = ${name.toLowerCase()} and lower(city) = ${city.toLowerCase()} limit 1`;",
    "    if (existing[0]) return getLead(String(existing[0].id));",
    '    const priority: Priority = input.priority || "medium";',
    "    const rows = await sql`",
    "      insert into crm_leads (name, contact_name, email, phone, city, state, stage, priority, source, notes, next_action, next_action_date)",
    '      values (${name}, ${input.contactName || ""}, ${input.email || ""}, ${input.phone || ""}, ${city}, ${input.state || ""}, ${"new"}, ${priority}, ${input.source || "other"}, ${input.notes || ""}, ${input.nextAction || ""}, ${input.nextActionDate || null})',
    "      returning id`;",
    "    const id = rows[0] ? String(rows[0].id) : null;",
    "    if (!id) return null;",
    '    await sql`insert into crm_lead_activities (lead_id, type, description, created_by) values (${id}, ${"created"}, ${`Lead “${name}” added`}, ${input.createdBy || "system"})`;',
    "    return getLead(id);",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Move a lead to a new pipeline stage, ported from church_crm.py update_lead's",
    "// status-change branch: log a 'status_change' activity, and when it becomes",
    "// 'won' stamp the conversion.",
    "export async function updateLeadStage(id: string, stage: string, updatedBy?: string | null): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  if (!PIPELINE_STAGES.some((s) => s.id === stage)) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select stage from crm_leads where id = ${id} limit 1`;",
    "    if (!rows[0]) return false;",
    "    const oldStage = String(rows[0].stage);",
    "    if (oldStage === stage) return true;",
    '    const converted = stage === "won" ? new Date().toISOString() : null;',
    "    await sql`update crm_leads set stage = ${stage}, converted_at = ${converted}, updated_at = now() where id = ${id}`;",
    "    await sql`insert into crm_lead_activities (lead_id, type, description, created_by) values (${id}, ${\"status_change\"}, ${`Stage changed from “${stageName(oldStage)}” to “${stageName(stage)}”`}, ${updatedBy || \"system\"})`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Log a follow-up touch, ported from church_crm.py add_activity: record the",
    "// activity, bump last_contact + followup_count for contact types, and set the",
    "// next action when supplied.",
    "export type LogActivityInput = {",
    "  leadId: string;",
    "  type: string;",
    "  description: string;",
    "  nextAction?: string;",
    "  nextActionDate?: string | null;",
    "  createdBy?: string | null;",
    "};",
    "",
    'export const CONTACT_TYPES = ["call", "email", "meeting", "text"];',
    "",
    "export async function logActivity(input: LogActivityInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const exists = await sql`select id from crm_leads where id = ${input.leadId} limit 1`;",
    "    if (!exists[0]) return false;",
    '    await sql`insert into crm_lead_activities (lead_id, type, description, created_by) values (${input.leadId}, ${input.type || "note"}, ${input.description || ""}, ${input.createdBy || "system"})`;',
    "    if (CONTACT_TYPES.includes(input.type)) {",
    "      await sql`update crm_leads set last_contact = now(), followup_count = followup_count + 1, updated_at = now() where id = ${input.leadId}`;",
    "    }",
    "    if (input.nextAction) {",
    "      await sql`update crm_leads set next_action = ${input.nextAction}, next_action_date = ${input.nextActionDate || null}, updated_at = now() where id = ${input.leadId}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// The 'who needs attention now' buckets, ported from church_crm.py",
    "// get_actionable_leads: overdue next-actions, hot (high-priority open) leads,",
    "// and brand-new never-contacted leads.",
    "export type Actionable = { overdue: Lead[]; hot: Lead[]; newLeads: Lead[] };",
    "",
    "export async function getActionable(limit = 20): Promise<Actionable> {",
    "  if (!hasDatabase()) {",
    "    const now = new Date().toISOString();",
    "    return {",
    "      overdue: fallbackLeads.filter((l) => l.nextActionDate && l.nextActionDate < now && !['won', 'lost'].includes(l.stage)).slice(0, limit),",
    "      hot: fallbackLeads.filter((l) => l.priority === 'high' && !['won', 'lost', 'new'].includes(l.stage)).slice(0, limit),",
    "      newLeads: fallbackLeads.filter((l) => l.stage === 'new' && !l.lastContact).slice(0, limit)",
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const now = new Date().toISOString();",
    "    const overdueRows = await sql`",
    "      select id, name, contact_name, email, phone, city, state, stage, priority, source, notes, next_action, next_action_date, last_contact, followup_count, created_at",
    "      from crm_leads",
    "      where stage not in ('won','lost') and next_action_date is not null and next_action_date < ${now}",
    "      order by next_action_date asc limit ${limit}`;",
    "    const hotRows = await sql`",
    "      select id, name, contact_name, email, phone, city, state, stage, priority, source, notes, next_action, next_action_date, last_contact, followup_count, created_at",
    "      from crm_leads",
    "      where stage not in ('won','lost','new') and priority = 'high'",
    "      order by updated_at desc limit ${limit}`;",
    "    const newRows = await sql`",
    "      select id, name, contact_name, email, phone, city, state, stage, priority, source, notes, next_action, next_action_date, last_contact, followup_count, created_at",
    "      from crm_leads",
    "      where stage = 'new' and last_contact is null",
    "      order by created_at desc limit ${limit}`;",
    "    return { overdue: overdueRows.map(rowToLead), hot: hotRows.map(rowToLead), newLeads: newRows.map(rowToLead) };",
    "  } catch {",
    "    return { overdue: [], hot: [], newLeads: [] };",
    "  }",
    "}",
    "",
    "// Pipeline analytics, ported from church_crm.py get_crm_analytics: a count per",
    "// stage plus the overdue-next-action 'needs action' number.",
    "export type Analytics = { total: number; stageCounts: Record<string, number>; needsAction: number; won: number };",
    "",
    "export async function getAnalytics(): Promise<Analytics> {",
    "  if (!hasDatabase()) {",
    "    const stageCounts: Record<string, number> = {};",
    "    for (const s of PIPELINE_STAGES) stageCounts[s.id] = fallbackLeads.filter((l) => l.stage === s.id).length;",
    "    const now = new Date().toISOString();",
    "    return {",
    "      total: fallbackLeads.length,",
    "      stageCounts,",
    "      needsAction: fallbackLeads.filter((l) => l.nextActionDate && l.nextActionDate < now && !['won', 'lost'].includes(l.stage)).length,",
    "      won: fallbackLeads.filter((l) => l.stage === 'won').length",
    "    };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const now = new Date().toISOString();",
    "    const byStage = await sql`select stage, count(*)::int as c from crm_leads group by stage`;",
    "    const stageCounts: Record<string, number> = {};",
    "    for (const s of PIPELINE_STAGES) stageCounts[s.id] = 0;",
    "    for (const r of byStage) stageCounts[String(r.stage)] = Number(r.c || 0);",
    "    const totalRow = await sql`select count(*)::int as c from crm_leads`;",
    "    const needsRow = await sql`select count(*)::int as c from crm_leads where stage not in ('won','lost') and next_action_date is not null and next_action_date < ${now}`;",
    "    return {",
    "      total: Number(totalRow[0]?.c || 0),",
    '      stageCounts,',
    "      needsAction: Number(needsRow[0]?.c || 0),",
    "      won: stageCounts.won || 0",
    "    };",
    "  } catch {",
    "    return { total: 0, stageCounts: {}, needsAction: 0, won: 0 };",
    "  }",
    "}",
    "",
    "export function crmEnabled(): boolean {",
    '  return process.env.FEATURE_CRM !== "false";',
    "}"
  ]);
}

// ---- src/app/api/crm/route.ts (list + create) -------------------------------

function crmApiFile(): GeneratedModuleFile {
  return file("src/app/api/crm/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listLeads, createLead, crmEnabled, type Priority } from "@/lib/db/crm";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!crmEnabled()) return NextResponse.json({ ok: false, message: "The CRM is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const leads = await listLeads({",
    '    q: url.searchParams.get("q") || undefined,',
    '    stage: url.searchParams.get("stage") || undefined,',
    '    priority: url.searchParams.get("priority") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, leads });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    '  if (name.length < 1) return NextResponse.json({ ok: false, message: "A name is required." }, { status: 400 });',
    '  const priority = (["high", "medium", "low"].includes(String(body.priority)) ? String(body.priority) : "medium") as Priority;',
    "  const lead = await createLead({",
    "    name,",
    '    contactName: typeof body.contactName === "string" ? body.contactName : undefined,',
    '    email: typeof body.email === "string" ? body.email : undefined,',
    '    phone: typeof body.phone === "string" ? body.phone : undefined,',
    '    city: typeof body.city === "string" ? body.city : undefined,',
    '    state: typeof body.state === "string" ? body.state : undefined,',
    "    priority,",
    '    source: typeof body.source === "string" ? body.source : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined,',
    '    nextAction: typeof body.nextAction === "string" ? body.nextAction : undefined,',
    '    nextActionDate: typeof body.nextActionDate === "string" ? body.nextActionDate : undefined,',
    '    createdBy: String(user.email || "admin")',
    "  });",
    '  if (!lead) return NextResponse.json({ ok: false, message: "Connect a database to save leads." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, lead });",
    "}"
  ]);
}

// ---- src/app/api/crm/[id]/route.ts (detail + stage move / log activity) -----

function crmDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/crm/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getLead, getLeadActivities, updateLeadStage, logActivity, crmEnabled } from "@/lib/db/crm";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!crmEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const lead = await getLead(id);",
    '  if (!lead) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const activities = await getLeadActivities(id);",
    "  return NextResponse.json({ ok: true, lead, activities });",
    "}",
    "",
    "// Mutations (moving a lead's stage, logging a follow-up) are admin actions.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!crmEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const actor = String(user.email || "admin");',
    "",
    '  if (typeof body.stage === "string" && body.stage.trim()) {',
    "    const moved = await updateLeadStage(id, body.stage.trim(), actor);",
    '    if (!moved) return NextResponse.json({ ok: false, message: "Could not move this lead." }, { status: 400 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    "",
    '  const type = typeof body.type === "string" ? body.type.trim() : "";',
    '  const description = typeof body.description === "string" ? body.description.trim() : "";',
    '  if (!type && !description) return NextResponse.json({ ok: false, message: "Nothing to log." }, { status: 400 });',
    "  const logged = await logActivity({",
    "    leadId: id,",
    '    type: type || "note",',
    "    description,",
    '    nextAction: typeof body.nextAction === "string" ? body.nextAction : undefined,',
    '    nextActionDate: typeof body.nextActionDate === "string" ? body.nextActionDate : undefined,',
    "    createdBy: actor",
    "  });",
    '  if (!logged) return NextResponse.json({ ok: false, message: "Connect a database to log follow-ups." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/crm/page.tsx (pipeline list + search + attention buckets) ------

function crmPageFile(): GeneratedModuleFile {
  return file("src/app/crm/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listLeads, getActionable, getAnalytics, PIPELINE_STAGES, stageName, crmEnabled } from "@/lib/db/crm";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CrmPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; stage?: string }>;",
    "}) {",
    "  if (!crmEnabled()) {",
    '    return (<main className="shell"><h1>Pipeline</h1><p>The CRM is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/crm");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const stage = (params?.stage || "").trim();',
    "  const [leads, actionable, analytics] = await Promise.all([",
    "    listLeads({ q: q || undefined, stage: stage || undefined }),",
    "    getActionable(),",
    "    getAnalytics()",
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Pipeline</p>',
    "      <h1>Follow-ups &amp; leads</h1>",
    "      <p>Track everyone — guests, members, leads — through a pipeline so no one falls through the cracks.</p>",
    "",
    '      <section className="grid">',
    '        <article className="card"><span>People</span><strong>{analytics.total}</strong></article>',
    '        <article className="card"><span>Needs follow-up</span><strong>{analytics.needsAction}</strong></article>',
    '        <article className="card"><span>Won</span><strong>{analytics.won}</strong></article>',
    "      </section>",
    "",
    "      {actionable.overdue.length > 0 ? (",
    '        <section className="panel">',
    "          <h2>Overdue follow-ups</h2>",
    '          <p className="note">These are past their next-action date. Reach out first.</p>',
    '          <div className="panel-list">',
    "            {actionable.overdue.map((lead) => (",
    '              <Link className="wide-card" key={lead.id} href={`/crm/${lead.id}`}>',
    "                <span>{lead.nextAction || \"Follow up\"}</span>",
    "                <strong>{lead.name}</strong>",
    '                <p className="note">Due {lead.nextActionDate ? new Date(lead.nextActionDate).toLocaleDateString() : ""}</p>',
    "              </Link>",
    "            ))}",
    "          </div>",
    "        </section>",
    "      ) : null}",
    "",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search by name, contact, email or city" aria-label="Search the pipeline" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "",
    '      <nav className="stack" aria-label="Filter by stage">',
    '        <Link className="button" href="/crm">All</Link>',
    "        {PIPELINE_STAGES.map((s) => (",
    '          <Link className="button" key={s.id} href={`/crm?stage=${s.id}`}>{s.name}</Link>',
    "        ))}",
    "      </nav>",
    "",
    "      {leads.length === 0 ? (",
    '        <p className="note">{q || stage ? "No one matches those filters yet." : "No one is in the pipeline yet."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {leads.map((lead) => (",
    '            <Link className="wide-card" key={lead.id} href={`/crm/${lead.id}`}>',
    "              <span>{stageName(lead.stage)} &middot; {lead.priority} priority</span>",
    "              <strong>{lead.name}</strong>",
    "              <p>{[lead.contactName, lead.email, [lead.city, lead.state].filter(Boolean).join(\", \")].filter(Boolean).join(\" · \")}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/crm/[id]/page.tsx (lead detail + activity timeline + actions) --

function crmDetailPageFile(): GeneratedModuleFile {
  return file("src/app/crm/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getLead, getLeadActivities, PIPELINE_STAGES, stageName, crmEnabled } from "@/lib/db/crm";',
    'import { LeadActions } from "./lead-actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function CrmDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!crmEnabled()) {",
    '    return (<main className="shell"><h1>Pipeline</h1><p>The CRM is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/crm");',
    "  const { id } = await params;",
    "  const [lead, activities, user] = await Promise.all([getLead(id), getLeadActivities(id), getCurrentUser()]);",
    "  if (!lead) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Pipeline</p>',
    "      <h1>{lead.name}</h1>",
    '      <p className="note">{stageName(lead.stage)} &middot; {lead.priority} priority</p>',
    "",
    '      <section className="grid">',
    "        {lead.contactName ? (<article className=\"card\"><span>Contact</span><strong>{lead.contactName}</strong></article>) : null}",
    "        {lead.email ? (<article className=\"card\"><span>Email</span><strong>{lead.email}</strong></article>) : null}",
    "        {lead.phone ? (<article className=\"card\"><span>Phone</span><strong>{lead.phone}</strong></article>) : null}",
    "        {(lead.city || lead.state) ? (<article className=\"card\"><span>Location</span><strong>{[lead.city, lead.state].filter(Boolean).join(\", \")}</strong></article>) : null}",
    "        {lead.nextAction ? (<article className=\"card\"><span>Next action</span><strong>{lead.nextAction}{lead.nextActionDate ? ` (${new Date(lead.nextActionDate).toLocaleDateString()})` : \"\"}</strong></article>) : null}",
    "        <article className=\"card\"><span>Follow-ups logged</span><strong>{lead.followupCount}</strong></article>",
    "      </section>",
    "",
    "      {lead.notes ? <p>{lead.notes}</p> : null}",
    "",
    "      {isAdmin ? <LeadActions leadId={lead.id} currentStage={lead.stage} stages={PIPELINE_STAGES} /> : null}",
    "",
    "      <h2>Activity</h2>",
    "      {activities.length === 0 ? (",
    '        <p className="note">No follow-ups logged yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {activities.map((a) => (",
    '            <article className="wide-card" key={a.id}>',
    "              <span>{a.type.replace(/_/g, \" \")}{a.createdAt ? ` · ${new Date(a.createdAt).toLocaleDateString()}` : \"\"}</span>",
    "              <p>{a.description}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/crm">Back to pipeline</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/crm/[id]/lead-actions.tsx (client: move stage + log follow-up) --

function leadActionsFile(): GeneratedModuleFile {
  return file("src/app/crm/[id]/lead-actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Stage = { id: string; name: string; color: string };",
    "",
    "export function LeadActions({ leadId, currentStage, stages }: { leadId: string; currentStage: string; stages: Stage[] }) {",
    "  const router = useRouter();",
    "  const [stage, setStage] = useState(currentStage);",
    '  const [type, setType] = useState("call");',
    '  const [description, setDescription] = useState("");',
    '  const [nextAction, setNextAction] = useState("");',
    '  const [nextActionDate, setNextActionDate] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function post(payload: Record<string, unknown>) {",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/crm/${leadId}`, {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(payload)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return false;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "      return true;",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "      return false;",
    "    }",
    "  }",
    "",
    "  async function moveStage(next: string) {",
    "    setStage(next);",
    "    await post({ stage: next });",
    "  }",
    "",
    "  async function submitLog(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    const ok = await post({",
    "      type,",
    "      description,",
    "      nextAction: nextAction || undefined,",
    "      nextActionDate: nextActionDate || undefined",
    "    });",
    "    if (ok) {",
    '      setDescription("");',
    '      setNextAction("");',
    '      setNextActionDate("");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <section className="panel">',
    "      <h2>Move &amp; follow up</h2>",
    '      <div className="stack" role="group" aria-label="Move to stage">',
    "        {stages.map((s) => (",
    "          <button",
    "            key={s.id}",
    "            type=\"button\"",
    '            className={s.id === stage ? "button primary" : "button"}',
    '            disabled={status === "saving"}',
    "            onClick={() => moveStage(s.id)}",
    "          >",
    "            {s.name}",
    "          </button>",
    "        ))}",
    "      </div>",
    "",
    '      <form className="stack" onSubmit={submitLog}>',
    '        <label className="stack">',
    "          <span>Log a follow-up</span>",
    '          <select className="input" value={type} onChange={(e) => setType(e.target.value)} aria-label="Follow-up type">',
    '            <option value="call">Call</option>',
    '            <option value="email">Email</option>',
    '            <option value="meeting">Meeting</option>',
    '            <option value="text">Text</option>',
    '            <option value="note">Note</option>',
    "          </select>",
    "        </label>",
    '        <textarea className="input" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What happened?" aria-label="Follow-up details" rows={2} />',
    '        <input className="input" value={nextAction} onChange={(e) => setNextAction(e.target.value)} placeholder="Next action (optional)" aria-label="Next action" />',
    '        <input className="input" type="date" value={nextActionDate} onChange={(e) => setNextActionDate(e.target.value)} aria-label="Next action date" />',
    '        {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '        <button className="button primary" type="submit" disabled={status === "saving"}>',
    '          {status === "saving" ? "Saving…" : "Log follow-up"}',
    "        </button>",
    "      </form>",
    "    </section>",
    "  );",
    "}"
  ]);
}

export const crmFollowUpModule: AppModule = {
  slug: "crm-follow-up",
  name: "CRM & Follow-up",
  tier: "optional",
  featureFlagEnv: "FEATURE_CRM",
  files: () => [
    crmLibFile(),
    crmApiFile(),
    crmDetailApiFile(),
    crmPageFile(),
    crmDetailPageFile(),
    leadActionsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists crm_leads (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null default '',",
      "  contact_name text not null default '',",
      "  email text,",
      "  phone text,",
      "  city text,",
      "  state text,",
      "  stage text not null default 'new',",
      "  priority text not null default 'medium',",
      "  source text not null default 'other',",
      "  notes text,",
      "  next_action text,",
      "  next_action_date timestamptz,",
      "  last_contact timestamptz,",
      "  followup_count integer not null default 0,",
      "  converted_at timestamptz,",
      "  created_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists crm_leads_stage_idx on crm_leads (stage, priority);",
      "create index if not exists crm_leads_next_action_idx on crm_leads (next_action_date);",
      "create index if not exists crm_leads_name_idx on crm_leads (lower(name));",
      "",
      "create table if not exists crm_lead_activities (",
      "  id uuid primary key default gen_random_uuid(),",
      "  lead_id uuid not null references crm_leads(id) on delete cascade,",
      "  type text not null default 'note',",
      "  description text not null default '',",
      "  created_by uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists crm_lead_activities_lead_idx on crm_lead_activities (lead_id, created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into crm_leads (name, contact_name, email, phone, city, state, stage, priority, source, notes, next_action) values",
      "  ('Riverstone Group', 'Dana Cole', 'dana@example.com', '555-0134', 'Austin', 'TX', 'interested', 'high', 'referral', 'Warm intro from an existing customer.', 'Send proposal'),",
      "  ('Maple & Co.', 'Sam Ortiz', 'sam@example.com', '', 'Denver', 'CO', 'new', 'medium', 'website', '', 'First call')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# CRM & Follow-up — set to false to switch the pipeline + reminders off.",
    "FEATURE_CRM=true"
  ],
  homeLinks: () => ['        <a className="button" href="/crm">Pipeline</a>'],
  navLinks: () => [{ href: "/crm", label: "Pipeline" }]
};
