// directory-community — a people directory + profiles + search, ported from
// ChurchConnect's real "universal people" system (backend/routes/people.py
// register/search/stats + src/components/ChurchDirectory.tsx). We keep its actual
// model — first/last name, email, phone, city/state, a completeness-based data
// quality score, sorted by quality then name — generalized from "church members"
// to any app's people directory. Runs on the app owner's own database with graceful
// sample-data fallback, feature-flagged (FEATURE_DIRECTORY), customers browse,
// admins manage.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/directory.ts (model + queries, ported from people.py) -------

function directoryLibFile(): GeneratedModuleFile {
  return file("src/lib/db/directory.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "export type DirectoryPerson = {",
    "  id: string;",
    "  firstName: string;",
    "  lastName: string;",
    "  email: string;",
    "  phone: string;",
    "  title: string;",
    "  city: string;",
    "  state: string;",
    "  bio: string;",
    "  dataQualityScore: number;",
    "};",
    "",
    "export type DirectoryFilters = { q?: string; city?: string; limit?: number };",
    "",
    "export function fullName(person: Pick<DirectoryPerson, \"firstName\" | \"lastName\">): string {",
    '  return [person.firstName, person.lastName].filter(Boolean).join(" ").trim() || "Unnamed";',
    "}",
    "",
    "// Completeness-based quality score, ported from people.py _calculate_data_quality:",
    "// the more of a person's record is filled in, the higher the score (max 100).",
    "export function calculateDataQuality(person: Partial<DirectoryPerson>): number {",
    "  let score = 0;",
    "  if (person.email && person.email.trim()) score += 30;",
    "  if (person.phone && person.phone.trim()) score += 20;",
    "  if (person.firstName && person.lastName) score += 30;",
    "  if (person.city && person.city.trim()) score += 10;",
    "  if (person.bio && person.bio.trim()) score += 10;",
    "  return Math.min(100, score);",
    "}",
    "",
    "const fallbackPeople: DirectoryPerson[] = [",
    '  { id: "sample-1", firstName: "Ada", lastName: "Lovelace", email: "ada@example.com", phone: "555-0100", title: "Founding member", city: "London", state: "", bio: "First to see where the work could go.", dataQualityScore: 100 },',
    '  { id: "sample-2", firstName: "Grace", lastName: "Hopper", email: "grace@example.com", phone: "", title: "Volunteer lead", city: "New York", state: "NY", bio: "", dataQualityScore: 70 }',
    "];",
    "",
    "function rowToPerson(row: Record<string, unknown>): DirectoryPerson {",
    "  return {",
    "    id: String(row.id),",
    '    firstName: String(row.first_name || ""),',
    '    lastName: String(row.last_name || ""),',
    '    email: String(row.email || ""),',
    '    phone: String(row.phone || ""),',
    '    title: String(row.title || ""),',
    '    city: String(row.city || ""),',
    '    state: String(row.state || ""),',
    '    bio: String(row.bio || ""),',
    "    dataQualityScore: Number(row.data_quality_score || 0)",
    "  };",
    "}",
    "",
    "// List + search, ported from people.py /universal/search: match name or email",
    "// (and optionally city), highest-quality records first.",
    "export async function listDirectory(filters: DirectoryFilters = {}): Promise<DirectoryPerson[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    "  const q = (filters.q || \"\").trim().toLowerCase();",
    "  const city = (filters.city || \"\").trim().toLowerCase();",
    "  if (!hasDatabase()) {",
    "    return fallbackPeople",
    "      .filter((person) => !q || (person.firstName + \" \" + person.lastName + \" \" + person.email).toLowerCase().includes(q))",
    "      .filter((person) => !city || person.city.toLowerCase().includes(city))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const cityLike = city ? `%${city}%` : null;",
    "    const rows = await sql`",
    "      select id, first_name, last_name, email, phone, title, city, state, bio, data_quality_score",
    "      from directory_people",
    "      where (${like}::text is null",
    "        or lower(first_name) like ${like}",
    "        or lower(last_name) like ${like}",
    "        or lower(email) like ${like})",
    "        and (${cityLike}::text is null or lower(city) like ${cityLike})",
    "      order by data_quality_score desc, last_name asc, first_name asc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToPerson);",
    "  } catch {",
    "    return fallbackPeople.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getPerson(id: string): Promise<DirectoryPerson | null> {",
    "  if (!hasDatabase()) return fallbackPeople.find((person) => person.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, first_name, last_name, email, phone, title, city, state, bio, data_quality_score from directory_people where id = ${id} limit 1`;",
    "    return rows[0] ? rowToPerson(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type UpsertPersonInput = {",
    "  firstName: string; lastName: string; email?: string; phone?: string;",
    "  title?: string; city?: string; state?: string; bio?: string;",
    "};",
    "",
    "export async function upsertPerson(input: UpsertPersonInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const score = calculateDataQuality(input);",
    "  const sql = getDatabase();",
    "  // Ported from /universal/register: de-dupe on email when present.",
    "  const email = (input.email || \"\").trim().toLowerCase();",
    "  if (email) {",
    "    const existing = await sql`select id from directory_people where lower(email) = ${email} limit 1`;",
    "    if (existing[0]) {",
    "      await sql`update directory_people set first_name = ${input.firstName}, last_name = ${input.lastName}, phone = ${input.phone || \"\"}, title = ${input.title || \"\"}, city = ${input.city || \"\"}, state = ${input.state || \"\"}, bio = ${input.bio || \"\"}, data_quality_score = ${score}, updated_at = now() where id = ${existing[0].id}`;",
    "      return true;",
    "    }",
    "  }",
    "  await sql`insert into directory_people (first_name, last_name, email, phone, title, city, state, bio, data_quality_score) values (${input.firstName}, ${input.lastName}, ${input.email || \"\"}, ${input.phone || \"\"}, ${input.title || \"\"}, ${input.city || \"\"}, ${input.state || \"\"}, ${input.bio || \"\"}, ${score})`;",
    "  return true;",
    "}",
    "",
    "export function directoryEnabled(): boolean {",
    '  return process.env.FEATURE_DIRECTORY !== "false";',
    "}"
  ]);
}

// ---- src/app/api/directory/route.ts -----------------------------------------

function directoryApiFile(): GeneratedModuleFile {
  return file("src/app/api/directory/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listDirectory, upsertPerson, directoryEnabled } from "@/lib/db/directory";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!directoryEnabled()) return NextResponse.json({ ok: false, message: "The directory is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const people = await listDirectory({ q: url.searchParams.get("q") || undefined, city: url.searchParams.get("city") || undefined });',
    "  return NextResponse.json({ ok: true, people });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const firstName = typeof body.firstName === "string" ? body.firstName.trim() : "";',
    '  const lastName = typeof body.lastName === "string" ? body.lastName.trim() : "";',
    "  if (firstName.length < 1 && lastName.length < 1) {",
    '    return NextResponse.json({ ok: false, message: "A name is required." }, { status: 400 });',
    "  }",
    "  const created = await upsertPerson({",
    "    firstName,",
    "    lastName,",
    '    email: typeof body.email === "string" ? body.email : undefined,',
    '    phone: typeof body.phone === "string" ? body.phone : undefined,',
    '    title: typeof body.title === "string" ? body.title : undefined,',
    '    city: typeof body.city === "string" ? body.city : undefined,',
    '    state: typeof body.state === "string" ? body.state : undefined,',
    '    bio: typeof body.bio === "string" ? body.bio : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save people." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/directory/[id]/route.ts ------------------------------------

function directoryDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/directory/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getPerson, directoryEnabled } from "@/lib/db/directory";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!directoryEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const person = await getPerson(id);",
    '  if (!person) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, person });",
    "}"
  ]);
}

// ---- src/app/directory/page.tsx (list + search) -----------------------------

function directoryPageFile(): GeneratedModuleFile {
  return file("src/app/directory/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listDirectory, fullName, directoryEnabled } from "@/lib/db/directory";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function DirectoryPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string }>;",
    "}) {",
    "  if (!directoryEnabled()) {",
    '    return (<main className="shell"><h1>Directory</h1><p>The directory is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/directory");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    "  const people = await listDirectory({ q: q || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Directory</p>',
    "      <h1>People</h1>",
    "      <p>Browse and search everyone in the directory.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search by name or email" aria-label="Search the directory" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {people.length === 0 ? (",
    '        <p className="note">{q ? `No one matches "${q}" yet.` : "No one is in the directory yet."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {people.map((person) => (",
    '            <Link className="wide-card" key={person.id} href={`/directory/${person.id}`}>',
    "              <span>{person.title || \"Member\"}</span>",
    "              <strong>{fullName(person)}</strong>",
    "              <p>{[person.email, [person.city, person.state].filter(Boolean).join(\", \")].filter(Boolean).join(\" · \")}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/directory/[id]/page.tsx (profile) ------------------------------

function directoryProfilePageFile(): GeneratedModuleFile {
  return file("src/app/directory/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getPerson, fullName, directoryEnabled } from "@/lib/db/directory";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function DirectoryProfilePage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!directoryEnabled()) {",
    '    return (<main className="shell"><h1>Directory</h1><p>The directory is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/directory");',
    "  const { id } = await params;",
    "  const person = await getPerson(id);",
    "  if (!person) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Directory</p>',
    "      <h1>{fullName(person)}</h1>",
    "      {person.title ? <p className=\"note\">{person.title}</p> : null}",
    '      <section className="grid">',
    "        {person.email ? (<article className=\"card\"><span>Email</span><strong>{person.email}</strong></article>) : null}",
    "        {person.phone ? (<article className=\"card\"><span>Phone</span><strong>{person.phone}</strong></article>) : null}",
    "        {(person.city || person.state) ? (<article className=\"card\"><span>Location</span><strong>{[person.city, person.state].filter(Boolean).join(\", \")}</strong></article>) : null}",
    "      </section>",
    "      {person.bio ? <p>{person.bio}</p> : null}",
    '      <p><Link className="button" href="/directory">Back to directory</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const directoryCommunityModule: AppModule = {
  slug: "directory-community",
  name: "Directory & Community",
  tier: "optional",
  featureFlagEnv: "FEATURE_DIRECTORY",
  files: () => [
    directoryLibFile(),
    directoryApiFile(),
    directoryDetailApiFile(),
    directoryPageFile(),
    directoryProfilePageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists directory_people (",
      "  id uuid primary key default gen_random_uuid(),",
      "  first_name text not null default '',",
      "  last_name text not null default '',",
      "  email text,",
      "  phone text,",
      "  title text,",
      "  city text,",
      "  state text,",
      "  bio text,",
      "  data_quality_score integer not null default 0,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists directory_people_name_idx on directory_people (lower(last_name), lower(first_name));",
      "create index if not exists directory_people_email_idx on directory_people (lower(email));"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into directory_people (first_name, last_name, email, phone, title, city, state, bio, data_quality_score) values",
      "  ('Ada', 'Lovelace', 'ada@example.com', '555-0100', 'Founding member', 'London', '', 'First to see where the work could go.', 100)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Directory & Community — set to false to switch the people directory off.",
    "FEATURE_DIRECTORY=true"
  ],
  homeLinks: () => ['        <a className="button" href="/directory">Directory</a>'],
  navLinks: () => [{ href: "/directory", label: "Directory" }]
};
