// event-curation-service-loop — activities & events with RSVP, attendance
// verification, admin curation, and a deterministic "become first, serve second,
// meet third" recommendation loop. Ported from Kindred-Connection's real events
// system (backend/routers/events.py + event_curation.py; frontend Events.js /
// EventCreate.js / EventDetail.js). We keep its actual model — six event types
// (service/sport/social/spiritual/volunteer/church/other) and three intents
// (serving/participating/either), source (user/admin/curated), featured flag,
// active/cancelled/draft status, capacity, host auto-attending, RSVP with a
// full-check, host-can't-cancel-own-RSVP, first-time attendance verification that
// bumps a service score, admin curation (feature/publish/cancel), and the
// deterministic feed scorer (_score_event_for_user → match_score + reasons that
// move a person's growth need into a real place to serve). Runs on the app
// owner's own database with a graceful sample-data fallback, feature-flagged
// (FEATURE_EVENTS); customers browse + RSVP, admins curate.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/events.ts (model + queries, ported from events.py) ----------

function eventsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/events.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// Six event types and three intents — ported verbatim from events.py",
    "// (EVENT_TYPES / EVENT_INTENTS). 'serving' = showing up to give;",
    "// 'participating' = showing up to receive/attend; 'either' = both.",
    'export const EVENT_TYPES = ["service", "sport", "social", "spiritual", "volunteer", "church", "other"] as const;',
    'export const EVENT_INTENTS = ["serving", "participating", "either"] as const;',
    "export type EventType = (typeof EVENT_TYPES)[number];",
    "export type EventIntent = (typeof EVENT_INTENTS)[number];",
    "",
    "// Which types/intents earn a service-score bump on verified attendance —",
    "// ported from mark_attended: service/volunteer/church OR intent 'serving'.",
    'const SERVICE_TYPES: EventType[] = ["service", "volunteer", "church"];',
    "",
    "export type EventRecord = {",
    "  id: string;",
    "  title: string;",
    "  description: string;",
    "  type: EventType;",
    "  intent: EventIntent;",
    "  startsAt: string;",
    "  endsAt: string;",
    "  location: string;",
    "  city: string;",
    "  capacity: number | null;",
    "  tags: string[];",
    "  externalUrl: string;",
    "  hostUserId: string | null;",
    "  hostName: string;",
    "  source: string;",
    "  featured: boolean;",
    "  status: string;",
    "  attendeeCount: number;",
    "  isAttending: boolean;",
    "  isFull: boolean;",
    "  // Curation / becoming-vector fields (used by the recommendation loop).",
    "  cultivates: string[];",
    "  stretchLevel: string;",
    "  pastoralBlurb: string;",
    "};",
    "",
    "export type EventFilters = {",
    "  type?: string;",
    "  intent?: string;",
    "  city?: string;",
    "  q?: string;",
    "  mine?: boolean;",
    "  upcoming?: boolean;",
    "  limit?: number;",
    "  viewerId?: string | null;",
    "};",
    "",
    "export function eventsEnabled(): boolean {",
    '  return process.env.FEATURE_EVENTS !== "false";',
    "}",
    "",
    "export function isValidType(value: string): value is EventType {",
    "  return (EVENT_TYPES as readonly string[]).includes(value);",
    "}",
    "",
    "export function isValidIntent(value: string): value is EventIntent {",
    "  return (EVENT_INTENTS as readonly string[]).includes(value);",
    "}",
    "",
    'export function typeLabel(type: string): string {',
    "  return type ? type.charAt(0).toUpperCase() + type.slice(1) : \"Event\";",
    "}",
    "",
    "// A place is a service opportunity when it asks a person to give, not just",
    "// attend — ported from the service_score rule in mark_attended.",
    "export function isServiceOpportunity(event: Pick<EventRecord, \"type\" | \"intent\">): boolean {",
    '  return SERVICE_TYPES.includes(event.type) || event.intent === "serving";',
    "}",
    "",
    "const fallbackEvents: EventRecord[] = [",
    "  {",
    '    id: "sample-1", title: "Saturday food bank shift", description: "Sort and hand out groceries for two hours. No experience needed — we will show you.",',
    '    type: "volunteer", intent: "serving", startsAt: futureIso(3), endsAt: "", location: "Community Pantry", city: "Springfield",',
    '    capacity: 12, tags: ["service", "weekly"], externalUrl: "", hostUserId: null, hostName: "Curated by the team", source: "curated",',
    '    featured: true, status: "active", attendeeCount: 4, isAttending: false, isFull: false,',
    '    cultivates: ["service", "generosity"], stretchLevel: "gentle", pastoralBlurb: "You do not have to fix anyone. Just show up and hand someone their week." ',
    "  },",
    "  {",
    '    id: "sample-2", title: "Sunday morning pickleball", description: "Beginners welcome. Bring water, borrow a paddle.",',
    '    type: "sport", intent: "either", startsAt: futureIso(5), endsAt: "", location: "Riverside Courts", city: "Springfield",',
    '    capacity: null, tags: ["pickleball", "beginner"], externalUrl: "", hostUserId: null, hostName: "Community", source: "user",',
    '    featured: false, status: "active", attendeeCount: 6, isAttending: false, isFull: false,',
    '    cultivates: ["playfulness", "joy"], stretchLevel: "comfort", pastoralBlurb: "" ',
    "  }",
    "];",
    "",
    "function futureIso(daysFromNow: number): string {",
    "  return new Date(Date.now() + daysFromNow * 86400000).toISOString();",
    "}",
    "",
    "function parseList(value: unknown): string[] {",
    "  if (Array.isArray(value)) return value.map((entry) => String(entry)).filter(Boolean);",
    '  if (typeof value === "string" && value.trim()) {',
    "    try {",
    "      const parsed = JSON.parse(value);",
    "      if (Array.isArray(parsed)) return parsed.map((entry) => String(entry)).filter(Boolean);",
    "    } catch {",
    "      return value.split(\",\").map((entry) => entry.trim()).filter(Boolean);",
    "    }",
    "  }",
    "  return [];",
    "}",
    "",
    "function rowToEvent(row: Record<string, unknown>, viewerId?: string | null): EventRecord {",
    "  const attendeeCount = Number(row.attendee_count || 0);",
    "  const capacity = row.capacity === null || row.capacity === undefined ? null : Number(row.capacity);",
    "  return {",
    "    id: String(row.id),",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    type: (isValidType(String(row.type)) ? String(row.type) : "social") as EventType,',
    '    intent: (isValidIntent(String(row.intent)) ? String(row.intent) : "either") as EventIntent,',
    '    startsAt: String(row.starts_at || ""),',
    '    endsAt: String(row.ends_at || ""),',
    '    location: String(row.location || ""),',
    '    city: String(row.city || ""),',
    "    capacity,",
    "    tags: parseList(row.tags),",
    '    externalUrl: String(row.external_url || ""),',
    "    hostUserId: row.host_user_id ? String(row.host_user_id) : null,",
    '    hostName: String(row.host_name || ""),',
    '    source: String(row.source || "user"),',
    "    featured: Boolean(row.featured),",
    '    status: String(row.status || "active"),',
    "    attendeeCount,",
    "    isAttending: viewerId ? Boolean(row.is_attending) : false,",
    "    isFull: capacity !== null && attendeeCount >= capacity,",
    "    cultivates: parseList(row.cultivates),",
    '    stretchLevel: String(row.stretch_level || ""),',
    '    pastoralBlurb: String(row.pastoral_blurb || "")',
    "  };",
    "}",
    "",
    "// List + filter events. Ported from list_events: default to active + upcoming,",
    "// filter by type/intent/city/free-text or 'mine' (events the viewer RSVP'd to),",
    "// featured first then soonest.",
    "export async function listEvents(filters: EventFilters = {}): Promise<EventRecord[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const type = (filters.type || "").trim().toLowerCase();',
    '  const intent = (filters.intent || "").trim().toLowerCase();',
    '  const city = (filters.city || "").trim().toLowerCase();',
    '  const q = (filters.q || "").trim().toLowerCase();',
    "  const upcoming = filters.upcoming !== false;",
    "  const mine = Boolean(filters.mine);",
    "  const viewerId = filters.viewerId || null;",
    "",
    "  if (!hasDatabase()) {",
    "    const nowIso = new Date().toISOString();",
    "    return fallbackEvents",
    '      .filter((event) => event.status === "active")',
    "      .filter((event) => !upcoming || event.startsAt >= nowIso)",
    "      .filter((event) => !type || type === \"all\" || event.type === type)",
    "      .filter((event) => !intent || event.intent === intent)",
    "      .filter((event) => !city || event.city.toLowerCase().includes(city))",
    "      .filter((event) => !q || (event.title + \" \" + event.description + \" \" + event.tags.join(\" \")).toLowerCase().includes(q))",
    "      .sort((a, b) => (a.featured === b.featured ? a.startsAt.localeCompare(b.startsAt) : a.featured ? -1 : 1))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const typeFilter = type && type !== \"all\" ? type : null;",
    "    const intentFilter = intent || null;",
    "    const cityLike = city ? `%${city}%` : null;",
    "    const qLike = q ? `%${q}%` : null;",
    "    const nowIso = upcoming ? new Date().toISOString() : null;",
    "    const rows = await sql`",
    "      select e.id, e.title, e.description, e.type, e.intent, e.starts_at, e.ends_at,",
    "        e.location, e.city, e.capacity, e.tags, e.external_url, e.host_user_id, e.host_name,",
    "        e.source, e.featured, e.status, e.cultivates, e.stretch_level, e.pastoral_blurb,",
    "        (select count(*) from event_rsvps r where r.event_id = e.id) as attendee_count,",
    "        (${viewerId}::text is not null and exists (select 1 from event_rsvps r2 where r2.event_id = e.id and r2.user_id = ${viewerId})) as is_attending",
    "      from events_activities e",
    "      where e.status = 'active'",
    "        and (${typeFilter}::text is null or e.type = ${typeFilter})",
    "        and (${intentFilter}::text is null or e.intent = ${intentFilter})",
    "        and (${cityLike}::text is null or lower(e.city) like ${cityLike})",
    "        and (${qLike}::text is null or lower(e.title) like ${qLike} or lower(e.description) like ${qLike})",
    "        and (${nowIso}::text is null or e.starts_at >= ${nowIso})",
    "        and (not ${mine} or exists (select 1 from event_rsvps r3 where r3.event_id = e.id and r3.user_id = ${viewerId}))",
    "      order by e.featured desc, e.starts_at asc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map((row) => rowToEvent(row, viewerId));",
    "  } catch {",
    "    return fallbackEvents.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getEvent(id: string, viewerId?: string | null): Promise<EventRecord | null> {",
    "  if (!hasDatabase()) return fallbackEvents.find((event) => event.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select e.id, e.title, e.description, e.type, e.intent, e.starts_at, e.ends_at,",
    "        e.location, e.city, e.capacity, e.tags, e.external_url, e.host_user_id, e.host_name,",
    "        e.source, e.featured, e.status, e.cultivates, e.stretch_level, e.pastoral_blurb,",
    "        (select count(*) from event_rsvps r where r.event_id = e.id) as attendee_count,",
    "        (${viewerId}::text is not null and exists (select 1 from event_rsvps r2 where r2.event_id = e.id and r2.user_id = ${viewerId})) as is_attending",
    "      from events_activities e where e.id = ${id} limit 1",
    "    `;",
    "    return rows[0] ? rowToEvent(rows[0], viewerId) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateEventInput = {",
    "  title: string;",
    "  description?: string;",
    "  type?: string;",
    "  intent?: string;",
    "  startsAt: string;",
    "  endsAt?: string;",
    "  location?: string;",
    "  city?: string;",
    "  capacity?: number | null;",
    "  tags?: string[];",
    "  externalUrl?: string;",
    "  hostUserId?: string | null;",
    "  hostName?: string;",
    "  isAdmin?: boolean;",
    "};",
    "",
    "// Create an event. Ported from create_event: source is 'admin' when the creator",
    "// is an admin else 'user'; the host is auto-RSVP'd (host is auto-attending).",
    "export async function createEvent(input: CreateEventInput): Promise<string | null> {",
    "  if (!hasDatabase()) return null;",
    "  const sql = getDatabase();",
    '  const type = input.type && isValidType(input.type) ? input.type : "social";',
    '  const intent = input.intent && isValidIntent(input.intent) ? input.intent : "either";',
    "  const tags = (input.tags || []).map((tag) => tag.trim()).filter(Boolean).slice(0, 10);",
    '  const source = input.isAdmin ? "admin" : "user";',
    "  const rows = await sql`",
    "    insert into events_activities",
    "      (title, description, type, intent, starts_at, ends_at, location, city, capacity, tags, external_url, host_user_id, host_name, source, featured, status)",
    "    values (",
    "      ${input.title.trim()}, ${(input.description || \"\").trim()}, ${type}, ${intent}, ${input.startsAt}, ${input.endsAt || \"\"},",
    "      ${input.location || \"\"}, ${input.city || \"\"}, ${input.capacity ?? null}, ${JSON.stringify(tags)}, ${input.externalUrl || \"\"},",
    "      ${input.hostUserId ?? null}, ${input.hostName || \"\"}, ${source}, false, 'active'",
    "    ) returning id",
    "  `;",
    "  const id = rows[0] ? String(rows[0].id) : null;",
    "  if (id && input.hostUserId) {",
    "    // Host is auto-attending.",
    "    await sql`insert into event_rsvps (event_id, user_id) values (${id}, ${input.hostUserId}) on conflict do nothing`;",
    "  }",
    "  return id;",
    "}",
    "",
    "export type RsvpResult = { ok: boolean; message?: string; attending?: boolean };",
    "",
    "// RSVP. Ported from rsvp: reject inactive events, no-op if already in, enforce",
    "// capacity ('This event is full'), else add the attendee.",
    "export async function rsvpToEvent(eventId: string, userId: string): Promise<RsvpResult> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to RSVP." };',
    "  const sql = getDatabase();",
    "  const rows = await sql`",
    "    select e.status, e.capacity,",
    "      (select count(*) from event_rsvps r where r.event_id = e.id) as attendee_count,",
    "      exists (select 1 from event_rsvps r2 where r2.event_id = e.id and r2.user_id = ${userId}) as is_attending",
    "    from events_activities e where e.id = ${eventId} limit 1",
    "  `;",
    '  if (!rows[0]) return { ok: false, message: "Not found." };',
    '  const status = String(rows[0].status);',
    '  if (status !== "active") return { ok: false, message: "Event is not active." };',
    "  if (rows[0].is_attending) return { ok: true, attending: true };",
    "  const capacity = rows[0].capacity === null ? null : Number(rows[0].capacity);",
    "  const count = Number(rows[0].attendee_count || 0);",
    '  if (capacity !== null && count >= capacity) return { ok: false, message: "This event is full." };',
    "  await sql`insert into event_rsvps (event_id, user_id) values (${eventId}, ${userId}) on conflict do nothing`;",
    "  return { ok: true, attending: true };",
    "}",
    "",
    "// Cancel RSVP. Ported from cancel_rsvp: the host cannot cancel their own RSVP",
    "// (they must cancel/delete the event instead).",
    "export async function cancelRsvp(eventId: string, userId: string): Promise<RsvpResult> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to RSVP." };',
    "  const sql = getDatabase();",
    "  const rows = await sql`select host_user_id from events_activities where id = ${eventId} limit 1`;",
    '  if (!rows[0]) return { ok: false, message: "Not found." };',
    "  if (rows[0].host_user_id && String(rows[0].host_user_id) === userId) {",
    '    return { ok: false, message: "The host cannot cancel their own RSVP — cancel or delete the event instead." };',
    "  }",
    "  await sql`delete from event_rsvps where event_id = ${eventId} and user_id = ${userId}`;",
    "  return { ok: true, attending: false };",
    "}",
    "",
    "// Verify attendance. Ported from mark_attended: only host/admin may verify; the",
    "// user must have RSVP'd; and the service score is bumped only on the FIRST",
    "// verify for a service/volunteer/church or 'serving' event.",
    "export async function markAttended(eventId: string, userId: string): Promise<RsvpResult> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database first." };',
    "  const sql = getDatabase();",
    "  const rows = await sql`select type, intent from events_activities where id = ${eventId} limit 1`;",
    '  if (!rows[0]) return { ok: false, message: "Not found." };',
    "  const rsvp = await sql`select attended from event_rsvps where event_id = ${eventId} and user_id = ${userId} limit 1`;",
    '  if (!rsvp[0]) return { ok: false, message: "User did not RSVP to this event." };',
    "  const alreadyAttended = Boolean(rsvp[0].attended);",
    "  await sql`update event_rsvps set attended = true where event_id = ${eventId} and user_id = ${userId}`;",
    "  const type = String(rows[0].type) as EventType;",
    "  const intent = String(rows[0].intent) as EventIntent;",
    "  if (!alreadyAttended && isServiceOpportunity({ type, intent })) {",
    "    await sql`insert into event_service_scores (user_id, score) values (${userId}, 1)",
    "      on conflict (user_id) do update set score = event_service_scores.score + 1, updated_at = now()`;",
    "  }",
    "  return { ok: true };",
    "}",
    "",
    "// Admin curation. Ported from patch_event / event_curation: feature a place so",
    "// it rises to the top, cancel it, or publish a draft.",
    "export async function setEventFeatured(eventId: string, featured: boolean): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  await sql`update events_activities set featured = ${featured}, updated_at = now() where id = ${eventId}`;",
    "  return true;",
    "}",
    "",
    "export async function setEventStatus(eventId: string, status: string): Promise<RsvpResult> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database first." };',
    '  if (!["active", "cancelled"].includes(status)) return { ok: false, message: "status must be active or cancelled" };',
    "  const sql = getDatabase();",
    "  await sql`update events_activities set status = ${status}, updated_at = now() where id = ${eventId}`;",
    "  return { ok: true };",
    "}",
    "",
    "// ---- Recommendation loop -----------------------------------------------",
    "// Ported from _score_event_for_user + /feed/for-me: a deterministic score in",
    "// [0,100] that moves a person's growth need into a real place to serve. No LLM",
    "// call — runs in microseconds so the whole feed can be scored cheaply.",
    "export type ViewerProfile = { growthGoals?: string[]; coreValues?: string[]; city?: string };",
    "export type ScoredEvent = EventRecord & { matchScore: number; matchReasons: string[] };",
    "",
    "export function scoreEventForViewer(event: EventRecord, viewer: ViewerProfile): { score: number; reasons: string[] } {",
    "  let score = 0;",
    "  const reasons: string[] = [];",
    "  const cultivates = (event.cultivates || []).map((c) => c.toLowerCase());",
    "  const tags = (event.tags || []).map((t) => t.toLowerCase());",
    "  const goals = (viewer.growthGoals || []).map((g) => (g || \"\").toLowerCase()).filter(Boolean);",
    "  const values = (viewer.coreValues || []).map((v) => (v || \"\").toLowerCase()).filter(Boolean);",
    "",
    "  // 1. Growth goals -> cultivates (highest weight).",
    "  const matchedGoal = cultivates.find((c) => goals.some((g) => c.includes(g) || g.includes(c)));",
    "  if (matchedGoal) {",
    "    score += 30;",
    "    reasons.push(`Grows your ${matchedGoal}`);",
    "  }",
    "",
    "  // 2. Core values -> cultivates / tags.",
    "  const matchedValue = values.find((v) => cultivates.some((c) => c.includes(v) || v.includes(c)) || tags.some((t) => t.includes(v) || v.includes(t)));",
    "  if (matchedValue && reasons.length < 2) {",
    "    score += 20;",
    "    reasons.push(`Honors your value of ${matchedValue}`);",
    "  } else if (matchedValue) {",
    "    score += 20;",
    "  }",
    "",
    "  // 3. A real place to serve — the core of the service loop.",
    "  if (isServiceOpportunity(event)) {",
    "    score += 15;",
    "    if (reasons.length < 2) reasons.push(\"A real place to serve\");",
    "  }",
    "",
    "  // 4. City match (small bonus).",
    "  const viewerCity = (viewer.city || \"\").toLowerCase();",
    "  const eventCity = (event.city || \"\").toLowerCase();",
    "  if (viewerCity && eventCity && (viewerCity.includes(eventCity) || eventCity.includes(viewerCity))) {",
    "    score += 10;",
    "    if (reasons.length < 2) reasons.push(`Near you in ${event.city}`);",
    "  }",
    "",
    "  return { score, reasons: reasons.slice(0, 2) };",
    "}",
    "",
    "// Top-N events scored to who the viewer is becoming — excludes events they host",
    "// or already RSVP'd to; falls back to soonest-upcoming so the rail is never",
    "// empty (ported from events_for_me).",
    "export async function eventsForViewer(viewerId: string | null, viewer: ViewerProfile, limit = 3): Promise<ScoredEvent[]> {",
    "  const candidates = (await listEvents({ upcoming: true, limit: 200, viewerId })).filter(",
    "    (event) => event.hostUserId !== viewerId && !event.isAttending",
    "  );",
    "  const scored: ScoredEvent[] = [];",
    "  for (const event of candidates) {",
    "    const match = scoreEventForViewer(event, viewer);",
    "    if (match.score <= 0 && match.reasons.length === 0) continue;",
    "    scored.push({ ...event, matchScore: match.score, matchReasons: match.reasons });",
    "  }",
    "  if (scored.length === 0) {",
    "    return candidates",
    "      .slice()",
    "      .sort((a, b) => a.startsAt.localeCompare(b.startsAt))",
    "      .slice(0, limit)",
    '      .map((event) => ({ ...event, matchScore: 0, matchReasons: ["Upcoming"] }));',
    "  }",
    "  scored.sort((a, b) => (b.matchScore - a.matchScore) || a.startsAt.localeCompare(b.startsAt));",
    "  return scored.slice(0, limit);",
    "}"
  ]);
}

// ---- src/app/api/events/route.ts (list + create) ----------------------------

function eventsApiFile(): GeneratedModuleFile {
  return file("src/app/api/events/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listEvents, createEvent, eventsEnabled, isValidType, isValidIntent } from "@/lib/db/events";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false, message: "Events are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const events = await listEvents({",
    '    type: url.searchParams.get("type") || undefined,',
    '    intent: url.searchParams.get("intent") || undefined,',
    '    city: url.searchParams.get("city") || undefined,',
    '    q: url.searchParams.get("q") || undefined,',
    '    mine: url.searchParams.get("mine") === "true",',
    "    viewerId: user?.id || null",
    "  });",
    "  return NextResponse.json({ ok: true, events });",
    "}",
    "",
    "// Any signed-in customer may post an activity (ported from create_event, which",
    "// is open to any authenticated user); admins are recorded as source 'admin'.",
    "export async function POST(request: Request) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false, message: "Events are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  const startsAt = typeof body.startsAt === "string" ? body.startsAt.trim() : "";',
    '  if (title.length < 3) return NextResponse.json({ ok: false, message: "Give it a title (at least 3 characters)." }, { status: 400 });',
    '  if (!startsAt) return NextResponse.json({ ok: false, message: "When is it? A start date and time is required." }, { status: 400 });',
    '  const type = typeof body.type === "string" && isValidType(body.type) ? body.type : "social";',
    '  const intent = typeof body.intent === "string" && isValidIntent(body.intent) ? body.intent : "either";',
    '  const capacityRaw = body.capacity;',
    '  const capacity = typeof capacityRaw === "number" && Number.isFinite(capacityRaw) ? Math.trunc(capacityRaw) : null;',
    "  const id = await createEvent({",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    "    type,",
    "    intent,",
    "    startsAt,",
    '    location: typeof body.location === "string" ? body.location : undefined,',
    '    city: typeof body.city === "string" ? body.city : undefined,',
    "    capacity,",
    "    tags: Array.isArray(body.tags) ? body.tags.map((tag) => String(tag)) : undefined,",
    "    hostUserId: user.id || null,",
    "    hostName: user.name || user.email || \"\",",
    "    isAdmin: canAccessAdmin(user.role)",
    "  });",
    '  if (!id) return NextResponse.json({ ok: false, message: "Connect a database to post activities." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, id });",
    "}"
  ]);
}

// ---- src/app/api/events/[id]/route.ts (detail) ------------------------------

function eventDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/events/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getEvent, setEventFeatured, setEventStatus, eventsEnabled } from "@/lib/db/events";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const event = await getEvent(id, user?.id || null);",
    '  if (!event) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, event });",
    "}",
    "",
    "// Admin curation: feature/unfeature or cancel/publish an event.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  if (typeof body.featured === "boolean") {',
    "    const ok = await setEventFeatured(id, body.featured);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database first." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  if (typeof body.status === "string") {',
    "    const result = await setEventStatus(id, body.status);",
    "    if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 400 });",
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  return NextResponse.json({ ok: false, message: "Nothing to update." }, { status: 400 });',
    "}"
  ]);
}

// ---- src/app/api/events/[id]/rsvp/route.ts ----------------------------------

function eventRsvpApiFile(): GeneratedModuleFile {
  return file("src/app/api/events/[id]/rsvp/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { rsvpToEvent, cancelRsvp, eventsEnabled } from "@/lib/db/events";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// POST = RSVP; DELETE = cancel RSVP. Both require a signed-in customer.",
    "export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const result = await rsvpToEvent(id, user.id);",
    "  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 400 });",
    "  return NextResponse.json({ ok: true, attending: result.attending });",
    "}",
    "",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const result = await cancelRsvp(id, user.id);",
    "  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 400 });",
    "  return NextResponse.json({ ok: true, attending: result.attending });",
    "}"
  ]);
}

// ---- src/app/api/events/[id]/attended/route.ts ------------------------------

function eventAttendedApiFile(): GeneratedModuleFile {
  return file("src/app/api/events/[id]/attended/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getEvent, markAttended, eventsEnabled } from "@/lib/db/events";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Verify who actually showed up. Ported from mark_attended: only the host or an",
    "// admin can verify attendance.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!eventsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const event = await getEvent(id, user.id);",
    '  if (!event) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const isHost = event.hostUserId !== null && event.hostUserId === user.id;",
    '  if (!isHost && !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Only the host or an admin can verify attendance." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const attendeeId = typeof body.userId === "string" ? body.userId.trim() : "";',
    '  if (!attendeeId) return NextResponse.json({ ok: false, message: "A userId is required." }, { status: 400 });',
    "  const result = await markAttended(id, attendeeId);",
    "  if (!result.ok) return NextResponse.json({ ok: false, message: result.message }, { status: 400 });",
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/events/page.tsx (list + filters + for-you rail) ----------------

function eventsPageFile(): GeneratedModuleFile {
  return file("src/app/events/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listEvents, eventsForViewer, typeLabel, EVENT_TYPES, eventsEnabled } from "@/lib/db/events";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function formatWhen(iso: string): string {",
    '  if (!iso) return "";',
    "  const date = new Date(iso);",
    "  if (Number.isNaN(date.getTime())) return iso;",
    '  return date.toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });',
    "}",
    "",
    "export default async function EventsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ type?: string; city?: string; q?: string }>;",
    "}) {",
    "  if (!eventsEnabled()) {",
    '    return (<main className="shell"><h1>Activities &amp; events</h1><p>Events are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/events");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const type = (params?.type || "").trim();',
    '  const city = (params?.city || "").trim();',
    '  const q = (params?.q || "").trim();',
    "  const events = await listEvents({ type: type || undefined, city: city || undefined, q: q || undefined, viewerId: user?.id || null });",
    "  const forYou = await eventsForViewer(user?.id || null, {}, 3);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Show up. Serve. Be witnessed.</p>',
    "      <h1>Activities &amp; events</h1>",
    "      <p>You will not find your people by hunting. You will find them at a food bank, a hike, a Sunday service. Walk into something good.</p>",
    '      <p><Link className="button primary" href="/events/new">Post an activity</Link></p>',
    "",
    '      <form className="stack" method="get" role="search">',
    '        <label htmlFor="events-q">Search</label>',
    '        <input id="events-q" className="input" type="search" name="q" defaultValue={q} placeholder="Search by title, description, or tag" aria-label="Search events" />',
    '        <label htmlFor="events-type">Type</label>',
    '        <select id="events-type" className="input" name="type" defaultValue={type} aria-label="Filter by type">',
    '          <option value="">All types</option>',
    "          {EVENT_TYPES.map((option) => (",
    "            <option key={option} value={option}>{typeLabel(option)}</option>",
    "          ))}",
    "        </select>",
    '        <label htmlFor="events-city">City</label>',
    '        <input id="events-city" className="input" type="text" name="city" defaultValue={city} placeholder="City" aria-label="Filter by city" />',
    '        <button className="button primary" type="submit">Filter</button>',
    "      </form>",
    "",
    "      {forYou.length > 0 ? (",
    '        <section className="panel">',
    '          <p className="eyebrow">For you, this week</p>',
    "          <h2>Three places to become.</h2>",
    '          <div className="grid">',
    "            {forYou.map((event) => (",
    '              <Link className="card" key={event.id} href={`/events/${event.id}`}>',
    "                <span>{typeLabel(event.type)}{event.stretchLevel ? ` · ${event.stretchLevel}` : \"\"}</span>",
    "                <strong>{event.title}</strong>",
    "                <p>{formatWhen(event.startsAt)}{event.city ? ` · ${event.city}` : \"\"}</p>",
    "                {event.matchReasons.filter((reason) => reason && reason !== \"Upcoming\").length > 0 ? (",
    "                  <p className=\"note\">{event.matchReasons.filter((reason) => reason && reason !== \"Upcoming\").join(\" · \")}</p>",
    "                ) : null}",
    "              </Link>",
    "            ))}",
    "          </div>",
    "        </section>",
    "      ) : null}",
    "",
    "      {events.length === 0 ? (",
    '        <p className="note">{q || type || city ? "Nothing matches those filters yet." : "Nothing here yet. Be the first — post the activity you would do anyway. Three people will show up; that is how it starts."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {events.map((event) => (",
    '            <Link className="wide-card" key={event.id} href={`/events/${event.id}`}>',
    "              <span>",
    "                {typeLabel(event.type)}",
    "                {event.intent === \"serving\" ? \" · serving\" : \"\"}",
    "                {event.featured ? \" · featured\" : \"\"}",
    "              </span>",
    "              <strong>{event.title}</strong>",
    "              <p>",
    "                {formatWhen(event.startsAt)}",
    "                {event.location ? ` · ${event.location}` : \"\"}",
    "                {event.city ? `, ${event.city}` : \"\"}",
    "              </p>",
    "              <p className=\"note\">",
    "                {event.attendeeCount}{event.capacity ? ` / ${event.capacity}` : \"\"} going",
    "                {event.isAttending ? \" · you're going\" : \"\"}",
    "                {event.isFull && !event.isAttending ? \" · full\" : \"\"}",
    "              </p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/events/new/page.tsx (create form) ------------------------------

function eventCreatePageFile(): GeneratedModuleFile {
  return file("src/app/events/new/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { EVENT_TYPES, typeLabel, eventsEnabled } from "@/lib/db/events";',
    'import { CreateEventForm } from "./create-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function EventCreatePage() {",
    "  if (!eventsEnabled()) {",
    '    return (<main className="shell"><h1>Post an activity</h1><p>Events are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/events/new");',
    "  return (",
    '    <main className="shell">',
    '      <p><Link href="/events">Back to events</Link></p>',
    '      <p className="eyebrow">Post an activity</p>',
    "      <h1>The smallest thing you would do anyway is enough</h1>",
    "      <p>A walk after church. Pickleball Saturday. Volunteer at the food bank Tuesday. Three people will show up — that is how it starts.</p>",
    "      <CreateEventForm types={EVENT_TYPES.map((type) => ({ value: type, label: typeLabel(type) }))} />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/events/new/create-form.tsx (client form) -----------------------

function eventCreateFormFile(): GeneratedModuleFile {
  return file("src/app/events/new/create-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type TypeOption = { value: string; label: string };",
    "",
    "export function CreateEventForm({ types }: { types: TypeOption[] }) {",
    "  const router = useRouter();",
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function onSubmit(formEvent: React.FormEvent<HTMLFormElement>) {",
    "    formEvent.preventDefault();",
    "    setError(null);",
    "    const form = new FormData(formEvent.currentTarget);",
    '    const date = String(form.get("date") || "");',
    '    const time = String(form.get("time") || "");',
    '    const title = String(form.get("title") || "").trim();',
    "    if (title.length < 3) { setError(\"Give it a title (at least 3 characters).\"); return; }",
    "    if (!date || !time) { setError(\"When is it? Pick a date and time.\"); return; }",
    "    let startsAt = \"\";",
    "    try {",
    "      startsAt = new Date(`${date}T${time}`).toISOString();",
    "    } catch {",
    "      setError(\"That date and time did not parse.\"); return;",
    "    }",
    "    const capacityRaw = String(form.get(\"capacity\") || \"\").trim();",
    '    const tags = String(form.get("tags") || "").split(",").map((tag) => tag.trim()).filter(Boolean);',
    "    setBusy(true);",
    "    try {",
    '      const response = await fetch("/api/events", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          title,",
    '          description: String(form.get("description") || "").trim() || undefined,',
    '          type: String(form.get("type") || "social"),',
    '          intent: String(form.get("intent") || "either"),',
    "          startsAt,",
    '          location: String(form.get("location") || "").trim() || undefined,',
    '          city: String(form.get("city") || "").trim() || undefined,',
    "          capacity: capacityRaw ? Number(capacityRaw) : undefined,",
    "          tags",
    "        })",
    "      });",
    "      const data = await response.json().catch(() => ({}));",
    "      if (!response.ok || !data.ok) {",
    '        setError(data.message || "Could not post the activity.");',
    "        setBusy(false);",
    "        return;",
    "      }",
    "      router.push(`/events/${data.id}`);",
    "    } catch {",
    '      setError("Could not reach the server. Try again.");',
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={onSubmit}>',
    "      {error ? <p className=\"note error\" role=\"alert\">{error}</p> : null}",
    '      <label htmlFor="title">Title</label>',
    '      <input id="title" className="input" name="title" type="text" required minLength={3} maxLength={140} placeholder="e.g. Pickleball at Riverside Park" />',
    '      <label htmlFor="description">Description</label>',
    '      <textarea id="description" className="input" name="description" rows={4} placeholder="What is it, who is it for, what should they bring?" />',
    '      <label htmlFor="type">Type</label>',
    '      <select id="type" className="input" name="type" defaultValue="social">',
    "        {types.map((option) => (",
    "          <option key={option.value} value={option.value}>{option.label}</option>",
    "        ))}",
    "      </select>",
    '      <label htmlFor="intent">Intent</label>',
    '      <select id="intent" className="input" name="intent" defaultValue="either">',
    '        <option value="either">Either — both fine</option>',
    '        <option value="serving">Serving — coming to give</option>',
    '        <option value="participating">Participating — coming to attend</option>',
    "      </select>",
    '      <label htmlFor="date">Date</label>',
    '      <input id="date" className="input" name="date" type="date" required />',
    '      <label htmlFor="time">Time</label>',
    '      <input id="time" className="input" name="time" type="time" required />',
    '      <label htmlFor="location">Place</label>',
    '      <input id="location" className="input" name="location" type="text" placeholder="Riverside Park · Calvary Chapel · my house" />',
    '      <label htmlFor="city">City</label>',
    '      <input id="city" className="input" name="city" type="text" placeholder="Springfield" />',
    '      <label htmlFor="capacity">Capacity (optional)</label>',
    '      <input id="capacity" className="input" name="capacity" type="number" min={1} max={10000} placeholder="Leave blank for no cap" />',
    '      <label htmlFor="tags">Tags (comma separated)</label>',
    '      <input id="tags" className="input" name="tags" type="text" placeholder="pickleball, beginner, weekly" />',
    '      <button className="button primary" type="submit" disabled={busy}>{busy ? "Posting…" : "Post it"}</button>',
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/events/[id]/page.tsx (detail + RSVP + admin curation) ----------

function eventDetailPageFile(): GeneratedModuleFile {
  return file("src/app/events/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getEvent, typeLabel, eventsEnabled } from "@/lib/db/events";',
    'import { EventActions } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function formatWhen(iso: string): string {",
    '  if (!iso) return "";',
    "  const date = new Date(iso);",
    "  if (Number.isNaN(date.getTime())) return iso;",
    '  return date.toLocaleString(undefined, { weekday: "long", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });',
    "}",
    "",
    "export default async function EventDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!eventsEnabled()) {",
    '    return (<main className="shell"><h1>Events</h1><p>Events are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/events");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const event = await getEvent(id, user?.id || null);",
    "  if (!event) notFound();",
    "",
    "  const isHost = event.hostUserId !== null && event.hostUserId === user?.id;",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p><Link href="/events">All events</Link></p>',
    "      <p className=\"eyebrow\">{typeLabel(event.type)}{event.intent !== \"either\" ? ` · ${event.intent}` : \"\"}{event.featured ? \" · featured\" : \"\"}{event.status === \"cancelled\" ? \" · cancelled\" : \"\"}</p>",
    "      <h1>{event.title}</h1>",
    "      {event.pastoralBlurb ? <p className=\"note\">{event.pastoralBlurb}</p> : null}",
    '      <section className="grid">',
    "        <article className=\"card\"><span>When</span><strong>{formatWhen(event.startsAt)}</strong></article>",
    "        <article className=\"card\"><span>Where</span><strong>{event.location ? `${event.location}${event.city ? `, ${event.city}` : \"\"}` : \"—\"}</strong></article>",
    "        <article className=\"card\"><span>Going</span><strong>{event.attendeeCount}{event.capacity ? ` / ${event.capacity}` : \"\"}</strong></article>",
    "      </section>",
    "      {event.description ? (<section className=\"panel\"><p className=\"eyebrow\">About</p><p>{event.description}</p></section>) : null}",
    "      {event.hostName ? <p className=\"note\">Hosted by {event.hostName}</p> : null}",
    "      <EventActions",
    "        eventId={event.id}",
    "        status={event.status}",
    "        isHost={isHost}",
    "        isAdmin={isAdmin}",
    "        isAttending={event.isAttending}",
    "        isFull={event.isFull}",
    "        featured={event.featured}",
    "      />",
    "      {event.tags.length > 0 ? (",
    '        <div className="tag-row">',
    "          {event.tags.map((tag) => (<span className=\"tag\" key={tag}>#{tag}</span>))}",
    "        </div>",
    "      ) : null}",
    "      {event.externalUrl ? (<p><a className=\"button\" href={event.externalUrl} target=\"_blank\" rel=\"noopener noreferrer\">External page</a></p>) : null}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/events/[id]/actions.tsx (client RSVP + curation) ---------------

function eventActionsFile(): GeneratedModuleFile {
  return file("src/app/events/[id]/actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Props = {",
    "  eventId: string;",
    "  status: string;",
    "  isHost: boolean;",
    "  isAdmin: boolean;",
    "  isAttending: boolean;",
    "  isFull: boolean;",
    "  featured: boolean;",
    "};",
    "",
    "export function EventActions(props: Props) {",
    "  const router = useRouter();",
    "  const [busy, setBusy] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  async function call(url: string, method: string, body?: Record<string, unknown>) {",
    "    setBusy(true);",
    "    setError(null);",
    "    try {",
    "      const response = await fetch(url, {",
    "        method,",
    '        headers: body ? { "Content-Type": "application/json" } : undefined,',
    "        body: body ? JSON.stringify(body) : undefined",
    "      });",
    "      const data = await response.json().catch(() => ({}));",
    "      if (!response.ok || !data.ok) {",
    '        setError(data.message || "Something went wrong.");',
    "        setBusy(false);",
    "        return;",
    "      }",
    "      router.refresh();",
    "      setBusy(false);",
    "    } catch {",
    '      setError("Could not reach the server. Try again.");',
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  const active = props.status === \"active\";",
    "",
    "  return (",
    '    <section className="stack">',
    "      {error ? <p className=\"note error\" role=\"alert\">{error}</p> : null}",
    "      {active && !props.isHost && !props.isAttending && !props.isFull ? (",
    "        <button className=\"button primary\" disabled={busy} onClick={() => call(`/api/events/${props.eventId}/rsvp`, \"POST\")}>{busy ? \"…\" : \"I will be there\"}</button>",
    "      ) : null}",
    "      {props.isAttending && !props.isHost ? (",
    "        <button className=\"button\" disabled={busy} onClick={() => call(`/api/events/${props.eventId}/rsvp`, \"DELETE\")}>Cancel my RSVP</button>",
    "      ) : null}",
    "      {props.isFull && !props.isAttending ? <p className=\"note\">This event is full.</p> : null}",
    "      {props.isAdmin ? (",
    '        <div className="stack">',
    "          <button className=\"button\" disabled={busy} onClick={() => call(`/api/events/${props.eventId}`, \"PATCH\", { featured: !props.featured })}>{props.featured ? \"Unfeature\" : \"Feature\"}</button>",
    "          {active ? (",
    "            <button className=\"button\" disabled={busy} onClick={() => call(`/api/events/${props.eventId}`, \"PATCH\", { status: \"cancelled\" })}>Cancel event</button>",
    "          ) : (",
    "            <button className=\"button\" disabled={busy} onClick={() => call(`/api/events/${props.eventId}`, \"PATCH\", { status: \"active\" })}>Publish</button>",
    "          )}",
    "        </div>",
    "      ) : null}",
    "    </section>",
    "  );",
    "}"
  ]);
}

export const eventCurationModule: AppModule = {
  slug: "event-curation-service-loop",
  name: "Events & Service Loop",
  tier: "optional",
  featureFlagEnv: "FEATURE_EVENTS",
  files: () => [
    eventsLibFile(),
    eventsApiFile(),
    eventDetailApiFile(),
    eventRsvpApiFile(),
    eventAttendedApiFile(),
    eventsPageFile(),
    eventCreatePageFile(),
    eventCreateFormFile(),
    eventDetailPageFile(),
    eventActionsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists events_activities (",
      "  id uuid primary key default gen_random_uuid(),",
      "  title text not null,",
      "  description text not null default '',",
      "  type text not null default 'social',",
      "  intent text not null default 'either',",
      "  starts_at text not null,",
      "  ends_at text not null default '',",
      "  location text not null default '',",
      "  city text not null default '',",
      "  capacity integer,",
      "  tags jsonb not null default '[]'::jsonb,",
      "  external_url text not null default '',",
      "  host_user_id uuid references users(id) on delete set null,",
      "  host_name text not null default '',",
      "  source text not null default 'user',",
      "  featured boolean not null default false,",
      "  status text not null default 'active',",
      "  cultivates jsonb not null default '[]'::jsonb,",
      "  stretch_level text not null default '',",
      "  pastoral_blurb text not null default '',",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists events_activities_upcoming_idx on events_activities (status, starts_at);",
      "create index if not exists events_activities_type_idx on events_activities (type);",
      "create index if not exists events_activities_city_idx on events_activities (lower(city));",
      "",
      "create table if not exists event_rsvps (",
      "  event_id uuid not null references events_activities(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  attended boolean not null default false,",
      "  created_at timestamptz not null default now(),",
      "  primary key (event_id, user_id)",
      ");",
      "create index if not exists event_rsvps_user_idx on event_rsvps (user_id);",
      "",
      "create table if not exists event_service_scores (",
      "  user_id uuid primary key references users(id) on delete cascade,",
      "  score integer not null default 0,",
      "  updated_at timestamptz not null default now()",
      ");"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into events_activities (title, description, type, intent, starts_at, location, city, capacity, tags, source, featured, status, cultivates, stretch_level, pastoral_blurb) values",
      "  ('Saturday food bank shift', 'Sort and hand out groceries for two hours. No experience needed — we will show you.', 'volunteer', 'serving', to_char(now() + interval '3 days', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"'), 'Community Pantry', 'Springfield', 12, '[\"service\",\"weekly\"]'::jsonb, 'curated', true, 'active', '[\"service\",\"generosity\"]'::jsonb, 'gentle', 'You do not have to fix anyone. Just show up and hand someone their week.')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Events & Service Loop — set to false to switch activities/events off.",
    "FEATURE_EVENTS=true"
  ],
  homeLinks: () => ['        <a className="button" href="/events">Activities &amp; events</a>'],
  navLinks: () => [{ href: "/events", label: "Events" }]
};
