// finance-accounting — budgets, expense tracking, and giving/financial reports
// for an organization. Ported from the Association app's real finance system
// (src/components/BudgetOverview.tsx + ExpenseTracking.tsx + GivingReports.tsx +
// Finances.tsx, with the models from src/lib/supabase.ts):
//   - a BUDGET record (id, category, allocated_amount, period
//     [monthly/quarterly/annually], year) plus BudgetOverview.tsx's budget
//     performance math: annualBudget = allocated × (12 monthly / 4 quarterly /
//     1 annually), spent = sum of PAID expenses in that category for the year,
//     percentage, remaining, and a status of over (>100%) / warning (>80%) /
//     good — the exact thresholds from the component.
//   - an EXPENSE record (id, vendor, amount, date, category, payment_status
//     [Pending/Paid/Overdue], payment_method, check_number, notes) with
//     ExpenseTracking.tsx's search + category + status filtering, the paid /
//     pending / overdue totals, and the inline payment-status update.
//   - a GIVING record (id, donor_name, amount, date, fund, payment_method,
//     check_number, notes) — ported from the Donation model + GivingReports.tsx:
//     total giving, unique givers, average gift, giving-by-fund grouping, and
//     top givers.
//   - the FINANCES overview (Finances.tsx fetchFinancialData): total income
//     (giving), total expenses, net income, and period-over-period growth for a
//     week/month/quarter/year window, plus recent transactions (giving +
//     expenses merged, newest first) and upcoming bills (pending expenses dated
//     today or later).
//   - the twelve expense categories from the components, generalized off the
//     church framing so they read for any organization.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_FINANCE). Rows are scoped to the signed-in owner via
// user.id; customers see + manage their own finances, admins see everything.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/finance.ts (model + queries, ported from the real sources) ---

function financeLibFile(): GeneratedModuleFile {
  return file("src/lib/db/finance.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The expense categories, ported verbatim from ExpenseTracking.tsx +",
    "// BudgetOverview.tsx's expenseCategories list, generalized off the church",
    "// framing so they read for any organization.",
    "export const EXPENSE_CATEGORIES = [",
    '  "Utilities",',
    '  "Salaries & Benefits",',
    '  "Building Maintenance",',
    '  "Office Supplies",',
    '  "Insurance",',
    '  "Equipment",',
    '  "Programs",',
    '  "Community Support",',
    '  "Professional Services",',
    '  "Communications",',
    '  "Transportation",',
    '  "Other"',
    "];",
    "",
    "// Budget periods, ported from BudgetOverview.tsx's period select.",
    'export type BudgetPeriod = "monthly" | "quarterly" | "annually";',
    "export const BUDGET_PERIODS: BudgetPeriod[] = [\"monthly\", \"quarterly\", \"annually\"];",
    "",
    "// Payment statuses, ported from ExpenseTracking.tsx's status options.",
    'export type PaymentStatus = "Pending" | "Paid" | "Overdue";',
    "export const PAYMENT_STATUSES: PaymentStatus[] = [\"Pending\", \"Paid\", \"Overdue\"];",
    "",
    "// A budget record, ported from the Budget model (supabase.ts) + BudgetOverview.",
    "export type Budget = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  category: string;",
    "  allocatedAmount: number;",
    "  period: BudgetPeriod;",
    "  year: number;",
    "  createdAt: string;",
    "};",
    "",
    "// An expense record, ported from the Expense model (supabase.ts) + ExpenseTracking.",
    "export type Expense = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  vendor: string;",
    "  amount: number;",
    "  date: string;",
    "  category: string;",
    "  paymentStatus: PaymentStatus;",
    "  paymentMethod: string;",
    "  checkNumber: string;",
    "  notes: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A giving/donation record, ported from the Donation model (supabase.ts) +",
    "// GivingReports.tsx. donor_name generalizes the church member reference.",
    "export type Giving = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  donorName: string;",
    "  amount: number;",
    "  date: string;",
    "  fund: string;",
    "  paymentMethod: string;",
    "  checkNumber: string;",
    "  notes: string;",
    "  createdAt: string;",
    "};",
    "",
    "// Budget performance, ported from BudgetOverview.tsx's budgetPerformance map:",
    "// annualBudget from the period, spent from PAID expenses in the category,",
    "// percentage, remaining, and the over/warning/good status thresholds.",
    "export type BudgetPerformance = Budget & {",
    "  spent: number;",
    "  annualBudget: number;",
    "  percentage: number;",
    "  remaining: number;",
    '  status: "over" | "warning" | "good";',
    "};",
    "",
    "// A merged transaction row for the overview, ported from Finances.tsx.",
    "export type Transaction = {",
    "  id: string;",
    '  type: "income" | "expense";',
    "  description: string;",
    "  amount: number;",
    "  date: string;",
    "  method: string;",
    "  status: string;",
    "};",
    "",
    "export type UpcomingBill = {",
    "  id: string;",
    "  vendor: string;",
    "  amount: number;",
    "  dueDate: string;",
    "  category: string;",
    "  status: string;",
    "};",
    "",
    "export type FinancialStats = {",
    "  totalIncome: number;",
    "  totalExpenses: number;",
    "  netIncome: number;",
    "  monthlyGrowth: number;",
    "};",
    "",
    'export type Period = "week" | "month" | "quarter" | "year";',
    "",
    "// Annualise an allocation, ported from BudgetOverview.tsx: monthly × 12,",
    "// quarterly × 4, annually × 1.",
    "export function annualizeBudget(allocatedAmount: number, period: BudgetPeriod): number {",
    '  if (period === "monthly") return allocatedAmount * 12;',
    '  if (period === "quarterly") return allocatedAmount * 4;',
    "  return allocatedAmount;",
    "}",
    "",
    "// The over/warning/good status, ported from BudgetOverview.tsx's thresholds.",
    'export function budgetStatus(percentage: number): "over" | "warning" | "good" {',
    '  if (percentage > 100) return "over";',
    '  if (percentage > 80) return "warning";',
    '  return "good";',
    "}",
    "",
    "export function financeEnabled(): boolean {",
    '  return process.env.FEATURE_FINANCE !== "false";',
    "}",
    "",
    "// ---- Fallback sample data (used when no DB is connected) -------------------",
    "",
    "const fallbackBudgets: Budget[] = [",
    '  { id: "sample-b1", ownerId: null, category: "Utilities", allocatedAmount: 1200, period: "monthly", year: new Date().getFullYear(), createdAt: "2025-01-01T00:00:00.000Z" },',
    '  { id: "sample-b2", ownerId: null, category: "Programs", allocatedAmount: 5000, period: "quarterly", year: new Date().getFullYear(), createdAt: "2025-01-01T00:00:00.000Z" },',
    '  { id: "sample-b3", ownerId: null, category: "Office Supplies", allocatedAmount: 3000, period: "annually", year: new Date().getFullYear(), createdAt: "2025-01-01T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackExpenses: Expense[] = [",
    '  { id: "sample-e1", ownerId: null, vendor: "City Power & Light", amount: 980, date: `${new Date().getFullYear()}-01-15`, category: "Utilities", paymentStatus: "Paid", paymentMethod: "ACH", checkNumber: "", notes: "January electricity", createdAt: "2025-01-15T00:00:00.000Z" },',
    '  { id: "sample-e2", ownerId: null, vendor: "Print Supply Co", amount: 240, date: `${new Date().getFullYear()}-02-03`, category: "Office Supplies", paymentStatus: "Pending", paymentMethod: "Card", checkNumber: "", notes: "Paper + toner", createdAt: "2025-02-03T00:00:00.000Z" },',
    '  { id: "sample-e3", ownerId: null, vendor: "Community Events", amount: 1500, date: `${new Date().getFullYear()}-02-20`, category: "Programs", paymentStatus: "Overdue", paymentMethod: "Check", checkNumber: "1042", notes: "Spring program deposit", createdAt: "2025-02-20T00:00:00.000Z" }',
    "];",
    "",
    "const fallbackGiving: Giving[] = [",
    '  { id: "sample-g1", ownerId: null, donorName: "Alex R.", amount: 250, date: `${new Date().getFullYear()}-01-05`, fund: "General", paymentMethod: "Card", checkNumber: "", notes: "", createdAt: "2025-01-05T00:00:00.000Z" },',
    '  { id: "sample-g2", ownerId: null, donorName: "Jordan P.", amount: 500, date: `${new Date().getFullYear()}-01-19`, fund: "Building", paymentMethod: "Check", checkNumber: "204", notes: "Building fund", createdAt: "2025-01-19T00:00:00.000Z" },',
    '  { id: "sample-g3", ownerId: null, donorName: "Alex R.", amount: 150, date: `${new Date().getFullYear()}-02-02`, fund: "General", paymentMethod: "Card", checkNumber: "", notes: "", createdAt: "2025-02-02T00:00:00.000Z" }',
    "];",
    "",
    "function rowToBudget(row: Record<string, unknown>): Budget {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    category: String(row.category || ""),',
    "    allocatedAmount: Number(row.allocated_amount || 0),",
    '    period: (String(row.period || "monthly") as BudgetPeriod),',
    "    year: Number(row.year || new Date().getFullYear()),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToExpense(row: Record<string, unknown>): Expense {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    vendor: String(row.vendor || ""),',
    "    amount: Number(row.amount || 0),",
    '    date: row.date ? String(row.date) : "",',
    '    category: String(row.category || "Other"),',
    '    paymentStatus: (String(row.payment_status || "Pending") as PaymentStatus),',
    '    paymentMethod: String(row.payment_method || ""),',
    '    checkNumber: String(row.check_number || ""),',
    '    notes: String(row.notes || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToGiving(row: Record<string, unknown>): Giving {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    donorName: String(row.donor_name || "Anonymous"),',
    "    amount: Number(row.amount || 0),",
    '    date: row.date ? String(row.date) : "",',
    '    fund: String(row.fund || "General"),',
    '    paymentMethod: String(row.payment_method || ""),',
    '    checkNumber: String(row.check_number || ""),',
    '    notes: String(row.notes || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- Budgets --------------------------------------------------------------",
    "",
    "export type BudgetFilters = { year?: number; ownerId?: string };",
    "",
    "// List budgets for a year, ported from BudgetOverview.tsx fetchBudgets",
    "// (.eq('year', year).order('category')), scoped to an owner when given.",
    "export async function listBudgets(filters: BudgetFilters = {}): Promise<Budget[]> {",
    "  const year = filters.year || new Date().getFullYear();",
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackBudgets",
    "      .filter((b) => b.year === year)",
    "      .filter((b) => !ownerId || b.ownerId === ownerId)",
    "      .sort((a, b) => a.category.localeCompare(b.category));",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, category, allocated_amount, period, year, created_at",
    "      from finance_accounting_budgets",
    "      where year = ${year}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "      order by category asc",
    "    `;",
    "    return rows.map(rowToBudget);",
    "  } catch {",
    "    return fallbackBudgets.filter((b) => b.year === year);",
    "  }",
    "}",
    "",
    "export async function getBudget(id: string): Promise<Budget | null> {",
    "  if (!hasDatabase()) return fallbackBudgets.find((b) => b.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, category, allocated_amount, period, year, created_at",
    "      from finance_accounting_budgets where id = ${id} limit 1`;",
    "    return rows[0] ? rowToBudget(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SaveBudgetInput = {",
    "  ownerId: string | null;",
    "  category: string;",
    "  allocatedAmount: number;",
    "  period: BudgetPeriod;",
    "  year: number;",
    "};",
    "",
    "// Create a budget item, ported from BudgetOverview.tsx handleSubmit (insert).",
    "export async function createBudget(input: SaveBudgetInput): Promise<Budget | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into finance_accounting_budgets (owner_id, category, allocated_amount, period, year)",
    "      values (${input.ownerId || null}, ${input.category}, ${input.allocatedAmount}, ${input.period}, ${input.year})",
    "      returning id, owner_id, category, allocated_amount, period, year, created_at`;",
    "    return rows[0] ? rowToBudget(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Update a budget item, ported from BudgetOverview.tsx handleSubmit (update).",
    "export async function updateBudget(id: string, input: Omit<SaveBudgetInput, \"ownerId\" | \"year\">): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      update finance_accounting_budgets",
    "      set category = ${input.category}, allocated_amount = ${input.allocatedAmount}, period = ${input.period}",
    "      where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Delete a budget item, ported from BudgetOverview.tsx handleDelete.",
    "export async function deleteBudget(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from finance_accounting_budgets where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Budget performance for a year, ported from BudgetOverview.tsx: spent is the",
    "// sum of PAID expenses per category for the year (spendingByCategory), then",
    "// annualBudget / percentage / remaining / status per budget item.",
    "export async function budgetPerformance(year: number, ownerId?: string): Promise<BudgetPerformance[]> {",
    "  const budgets = await listBudgets({ year, ownerId });",
    "  const expenses = await listExpenses({ year, ownerId, status: \"Paid\" });",
    "  const spendingByCategory: Record<string, number> = {};",
    "  for (const e of expenses) {",
    "    spendingByCategory[e.category] = (spendingByCategory[e.category] || 0) + e.amount;",
    "  }",
    "  return budgets.map((b) => {",
    "    const spent = spendingByCategory[b.category] || 0;",
    "    const annualBudget = annualizeBudget(b.allocatedAmount, b.period);",
    "    const percentage = annualBudget > 0 ? (spent / annualBudget) * 100 : 0;",
    "    return {",
    "      ...b,",
    "      spent,",
    "      annualBudget,",
    "      percentage,",
    "      remaining: annualBudget - spent,",
    "      status: budgetStatus(percentage)",
    "    };",
    "  });",
    "}",
    "",
    "// ---- Expenses -------------------------------------------------------------",
    "",
    "export type ExpenseFilters = { year?: number; category?: string; status?: string; search?: string; ownerId?: string; limit?: number };",
    "",
    "// List + filter expenses, ported from ExpenseTracking.tsx: a year window",
    "// (gte/lte on date), then category / status / search filtering over",
    "// vendor / category / notes; newest first. Search + category + status are",
    "// applied in SQL when a DB is present, mirroring filteredExpenses in memory.",
    "export async function listExpenses(filters: ExpenseFilters = {}): Promise<Expense[]> {",
    "  const year = filters.year || new Date().getFullYear();",
    "  const limit = Math.min(500, Math.max(1, filters.limit || 500));",
    '  const search = (filters.search || "").trim().toLowerCase();',
    '  const category = (filters.category || "").trim();',
    '  const status = (filters.status || "").trim();',
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackExpenses",
    "      .filter((e) => !ownerId || e.ownerId === ownerId)",
    "      .filter((e) => e.date >= `${year}-01-01` && e.date <= `${year}-12-31`)",
    "      .filter((e) => !category || category === \"all\" || e.category === category)",
    "      .filter((e) => !status || status === \"all\" || e.paymentStatus === status)",
    "      .filter((e) => !search",
    '        || (e.vendor + " " + e.category + " " + e.notes).toLowerCase().includes(search))',
    "      .sort((a, b) => (a.date < b.date ? 1 : -1))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const cat = category && category !== \"all\" ? category : null;",
    "    const st = status && status !== \"all\" ? status : null;",
    "    const like = search ? `%${search}%` : null;",
    "    const rows = await sql`",
    "      select id, owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes, created_at",
    "      from finance_accounting_expenses",
    "      where date >= ${`${year}-01-01`} and date <= ${`${year}-12-31`}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${cat}::text is null or category = ${cat})",
    "        and (${st}::text is null or payment_status = ${st})",
    "        and (${like}::text is null",
    "          or lower(vendor) like ${like}",
    "          or lower(category) like ${like}",
    "          or lower(notes) like ${like})",
    "      order by date desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToExpense);",
    "  } catch {",
    "    return fallbackExpenses.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getExpense(id: string): Promise<Expense | null> {",
    "  if (!hasDatabase()) return fallbackExpenses.find((e) => e.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes, created_at",
    "      from finance_accounting_expenses where id = ${id} limit 1`;",
    "    return rows[0] ? rowToExpense(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateExpenseInput = {",
    "  ownerId: string | null;",
    "  vendor: string;",
    "  amount: number;",
    "  date: string;",
    "  category?: string;",
    "  paymentStatus?: PaymentStatus;",
    "  paymentMethod?: string;",
    "  checkNumber?: string;",
    "  notes?: string;",
    "};",
    "",
    "// Record an expense (the RecordExpenseForm insert path in the Association app).",
    "export async function createExpense(input: CreateExpenseInput): Promise<Expense | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into finance_accounting_expenses (",
    "        owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.vendor}, ${input.amount}, ${input.date},",
    '        ${input.category || "Other"}, ${input.paymentStatus || "Pending"},',
    '        ${input.paymentMethod || ""}, ${input.checkNumber || ""}, ${input.notes || ""}',
    "      )",
    "      returning id, owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes, created_at`;",
    "    return rows[0] ? rowToExpense(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Update an expense's payment status, ported from ExpenseTracking.tsx",
    "// updatePaymentStatus.",
    "export async function updateExpenseStatus(id: string, status: PaymentStatus): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update finance_accounting_expenses set payment_status = ${status} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Delete an expense, ported from ExpenseTracking.tsx handleDelete.",
    "export async function deleteExpense(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from finance_accounting_expenses where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Paid / pending / overdue totals, ported from ExpenseTracking.tsx's summary.",
    "export function expenseTotals(expenses: Expense[]): { total: number; paid: number; pending: number; overdue: number } {",
    "  const total = expenses.reduce((s, e) => s + e.amount, 0);",
    '  const paid = expenses.filter((e) => e.paymentStatus === "Paid").reduce((s, e) => s + e.amount, 0);',
    '  const pending = expenses.filter((e) => e.paymentStatus === "Pending").reduce((s, e) => s + e.amount, 0);',
    '  const overdue = expenses.filter((e) => e.paymentStatus === "Overdue").reduce((s, e) => s + e.amount, 0);',
    "  return { total, paid, pending, overdue };",
    "}",
    "",
    "// ---- Giving ---------------------------------------------------------------",
    "",
    "export type GivingFilters = { year?: number; fund?: string; search?: string; ownerId?: string; limit?: number };",
    "",
    "// List + filter giving, ported from GivingReports.tsx fetchDonations (year",
    "// window, newest first) + filteredDonations (fund + search over donor / fund /",
    "// notes).",
    "export async function listGiving(filters: GivingFilters = {}): Promise<Giving[]> {",
    "  const year = filters.year || new Date().getFullYear();",
    "  const limit = Math.min(1000, Math.max(1, filters.limit || 1000));",
    '  const search = (filters.search || "").trim().toLowerCase();',
    '  const fund = (filters.fund || "").trim();',
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackGiving",
    "      .filter((g) => !ownerId || g.ownerId === ownerId)",
    "      .filter((g) => g.date >= `${year}-01-01` && g.date <= `${year}-12-31`)",
    "      .filter((g) => !fund || fund === \"all\" || g.fund === fund)",
    "      .filter((g) => !search",
    '        || (g.donorName + " " + g.fund + " " + g.notes).toLowerCase().includes(search))',
    "      .sort((a, b) => (a.date < b.date ? 1 : -1))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const fnd = fund && fund !== \"all\" ? fund : null;",
    "    const like = search ? `%${search}%` : null;",
    "    const rows = await sql`",
    "      select id, owner_id, donor_name, amount, date, fund, payment_method,",
    "        check_number, notes, created_at",
    "      from finance_accounting_giving",
    "      where date >= ${`${year}-01-01`} and date <= ${`${year}-12-31`}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${fnd}::text is null or fund = ${fnd})",
    "        and (${like}::text is null",
    "          or lower(donor_name) like ${like}",
    "          or lower(fund) like ${like}",
    "          or lower(notes) like ${like})",
    "      order by date desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToGiving);",
    "  } catch {",
    "    return fallbackGiving.slice(0, limit);",
    "  }",
    "}",
    "",
    "export type CreateGivingInput = {",
    "  ownerId: string | null;",
    "  donorName?: string;",
    "  amount: number;",
    "  date: string;",
    "  fund?: string;",
    "  paymentMethod?: string;",
    "  checkNumber?: string;",
    "  notes?: string;",
    "};",
    "",
    "// Record a gift (the donation insert path in the Association app).",
    "export async function createGiving(input: CreateGivingInput): Promise<Giving | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into finance_accounting_giving (",
    "        owner_id, donor_name, amount, date, fund, payment_method, check_number, notes",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.donorName || "Anonymous"}, ${input.amount},',
    '        ${input.date}, ${input.fund || "General"}, ${input.paymentMethod || ""},',
    '        ${input.checkNumber || ""}, ${input.notes || ""}',
    "      )",
    "      returning id, owner_id, donor_name, amount, date, fund, payment_method,",
    "        check_number, notes, created_at`;",
    "    return rows[0] ? rowToGiving(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function deleteGiving(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from finance_accounting_giving where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Giving report stats, ported from GivingReports.tsx: total, unique givers",
    "// (distinct donor names with a value), average gift, giving-by-fund, and top",
    "// givers grouped by donor.",
    "export type GivingReport = {",
    "  totalGiving: number;",
    "  uniqueGivers: number;",
    "  averageGift: number;",
    "  totalGifts: number;",
    "  givingByFund: Array<{ fund: string; amount: number }>;",
    "  topGivers: Array<{ donorName: string; total: number; gifts: number }>;",
    "};",
    "",
    "export function givingReport(giving: Giving[]): GivingReport {",
    "  const totalGiving = giving.reduce((s, g) => s + g.amount, 0);",
    "  const totalGifts = giving.length;",
    "  const averageGift = totalGifts > 0 ? totalGiving / totalGifts : 0;",
    "  const uniqueGivers = new Set(",
    '    giving.filter((g) => g.donorName && g.donorName !== "Anonymous").map((g) => g.donorName)',
    "  ).size;",
    "  const fundMap: Record<string, number> = {};",
    "  for (const g of giving) fundMap[g.fund] = (fundMap[g.fund] || 0) + g.amount;",
    "  const givingByFund = Object.entries(fundMap)",
    "    .map(([fund, amount]) => ({ fund, amount }))",
    "    .sort((a, b) => b.amount - a.amount);",
    "  const donorMap: Record<string, { total: number; gifts: number }> = {};",
    "  for (const g of giving) {",
    '    if (!g.donorName || g.donorName === "Anonymous") continue;',
    "    if (!donorMap[g.donorName]) donorMap[g.donorName] = { total: 0, gifts: 0 };",
    "    donorMap[g.donorName].total += g.amount;",
    "    donorMap[g.donorName].gifts += 1;",
    "  }",
    "  const topGivers = Object.entries(donorMap)",
    "    .map(([donorName, v]) => ({ donorName, total: v.total, gifts: v.gifts }))",
    "    .sort((a, b) => b.total - a.total)",
    "    .slice(0, 10);",
    "  return { totalGiving, uniqueGivers, averageGift, totalGifts, givingByFund, topGivers };",
    "}",
    "",
    "// ---- Finances overview ----------------------------------------------------",
    "",
    "function periodStart(period: Period): Date {",
    "  const now = new Date();",
    "  const start = new Date();",
    '  if (period === "week") start.setDate(now.getDate() - 7);',
    '  else if (period === "quarter") start.setMonth(now.getMonth() - 3);',
    '  else if (period === "year") start.setFullYear(now.getFullYear() - 1);',
    "  else start.setMonth(now.getMonth() - 1);",
    "  return start;",
    "}",
    "",
    "function toDateString(d: Date): string {",
    '  return d.toISOString().split("T")[0];',
    "}",
    "",
    "// The financial overview, ported from Finances.tsx fetchFinancialData: sum",
    "// giving (income) and expenses over the window, net = income - expenses, and",
    "// period-over-period growth against the immediately preceding window.",
    'export async function financialStats(period: Period = "month", ownerId?: string): Promise<FinancialStats> {',
    "  const now = new Date();",
    "  const start = periodStart(period);",
    "  const startStr = toDateString(start);",
    "  const givingInRange = await givingBetween(startStr, toDateString(now), ownerId);",
    "  const expensesInRange = await expensesBetween(startStr, toDateString(now), ownerId);",
    "  const totalIncome = givingInRange.reduce((s, g) => s + g.amount, 0);",
    "  const totalExpenses = expensesInRange.reduce((s, e) => s + e.amount, 0);",
    "  const netIncome = totalIncome - totalExpenses;",
    "  // Growth vs the previous equal-length window, ported from the component.",
    "  const periodLength = now.getTime() - start.getTime();",
    "  const prevStart = new Date(start.getTime() - periodLength);",
    "  const prevGiving = await givingBetween(toDateString(prevStart), startStr, ownerId);",
    "  const previousIncome = prevGiving.reduce((s, g) => s + g.amount, 0);",
    "  const monthlyGrowth = previousIncome > 0 ? ((totalIncome - previousIncome) / previousIncome) * 100 : 0;",
    "  return { totalIncome, totalExpenses, netIncome, monthlyGrowth };",
    "}",
    "",
    "async function givingBetween(startStr: string, endStr: string, ownerId?: string): Promise<Giving[]> {",
    "  if (!hasDatabase()) {",
    "    return fallbackGiving",
    "      .filter((g) => !ownerId || g.ownerId === ownerId)",
    "      .filter((g) => g.date >= startStr && g.date < endStr);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, donor_name, amount, date, fund, payment_method,",
    "        check_number, notes, created_at",
    "      from finance_accounting_giving",
    "      where date >= ${startStr} and date < ${endStr}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "      order by date desc`;",
    "    return rows.map(rowToGiving);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "async function expensesBetween(startStr: string, endStr: string, ownerId?: string): Promise<Expense[]> {",
    "  if (!hasDatabase()) {",
    "    return fallbackExpenses",
    "      .filter((e) => !ownerId || e.ownerId === ownerId)",
    "      .filter((e) => e.date >= startStr && e.date < endStr);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes, created_at",
    "      from finance_accounting_expenses",
    "      where date >= ${startStr} and date < ${endStr}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "      order by date desc`;",
    "    return rows.map(rowToExpense);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Recent transactions, ported from Finances.tsx: merge giving (income) and",
    "// expenses, newest first, top 10.",
    'export async function recentTransactions(period: Period = "month", ownerId?: string, limit = 10): Promise<Transaction[]> {',
    "  const now = new Date();",
    "  const start = periodStart(period);",
    "  const giving = await givingBetween(toDateString(start), toDateString(now), ownerId);",
    "  const expenses = await expensesBetween(toDateString(start), toDateString(now), ownerId);",
    "  const transactions: Transaction[] = [",
    "    ...giving.map((g) => ({",
    "      id: g.id,",
    '      type: "income" as const,',
    "      description: `Gift - ${g.fund}`,",
    "      amount: g.amount,",
    "      date: g.date,",
    "      method: g.paymentMethod,",
    '      status: "completed"',
    "    })),",
    "    ...expenses.map((e) => ({",
    "      id: e.id,",
    '      type: "expense" as const,',
    "      description: `${e.vendor} - ${e.category}`,",
    "      amount: e.amount,",
    "      date: e.date,",
    "      method: e.paymentMethod,",
    "      status: e.paymentStatus.toLowerCase()",
    "    }))",
    "  ].sort((a, b) => (a.date < b.date ? 1 : -1)).slice(0, limit);",
    "  return transactions;",
    "}",
    "",
    "// Upcoming bills, ported from Finances.tsx: pending expenses dated today or",
    "// later, soonest first, top 5.",
    "export async function upcomingBills(ownerId?: string, limit = 5): Promise<UpcomingBill[]> {",
    "  const today = toDateString(new Date());",
    "  if (!hasDatabase()) {",
    "    return fallbackExpenses",
    "      .filter((e) => !ownerId || e.ownerId === ownerId)",
    '      .filter((e) => e.paymentStatus === "Pending" && e.date >= today)',
    "      .sort((a, b) => (a.date < b.date ? -1 : 1))",
    "      .slice(0, limit)",
    '      .map((e) => ({ id: e.id, vendor: e.vendor, amount: e.amount, dueDate: e.date, category: e.category, status: "pending" }));',
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, vendor, amount, date, category, payment_status,",
    "        payment_method, check_number, notes, created_at",
    "      from finance_accounting_expenses",
    "      where payment_status = 'Pending' and date >= ${today}",
    "        and (${owner}::uuid is null or owner_id = ${owner})",
    "      order by date asc limit ${limit}`;",
    "    return rows.map(rowToExpense).map((e) => ({",
    "      id: e.id, vendor: e.vendor, amount: e.amount, dueDate: e.date, category: e.category, status: \"pending\"",
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}"
  ]);
}

// ---- src/app/api/finance/budgets/route.ts (list + create) -------------------

function budgetApiFile(): GeneratedModuleFile {
  return file("src/app/api/finance/budgets/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { budgetPerformance, createBudget, BUDGET_PERIODS, financeEnabled } from "@/lib/db/finance";',
    'import type { BudgetPeriod } from "@/lib/db/finance";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!financeEnabled()) return NextResponse.json({ ok: false, message: "Finance is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const year = Number(url.searchParams.get("year")) || new Date().getFullYear();',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const budgets = await budgetPerformance(year, ownerId);",
    "  return NextResponse.json({ ok: true, budgets });",
    "}",
    "",
    "// Create a budget item — scoped to the signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const category = typeof body.category === "string" ? body.category.trim() : "";',
    "  const allocatedAmount = Number(body.allocatedAmount);",
    '  const period = BUDGET_PERIODS.includes(body.period as BudgetPeriod) ? (body.period as BudgetPeriod) : "monthly";',
    "  const year = Number(body.year) || new Date().getFullYear();",
    "  if (category.length < 2 || !Number.isFinite(allocatedAmount) || allocatedAmount <= 0) {",
    '    return NextResponse.json({ ok: false, message: "A category and a positive amount are required." }, { status: 400 });',
    "  }",
    "  const created = await createBudget({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    category,",
    "    allocatedAmount,",
    "    period,",
    "    year",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save budgets." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, budget: created });",
    "}"
  ]);
}

// ---- src/app/api/finance/budgets/[id]/route.ts (update + delete) ------------

function budgetDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/finance/budgets/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getBudget, updateBudget, deleteBudget, BUDGET_PERIODS, financeEnabled } from "@/lib/db/finance";',
    'import type { BudgetPeriod } from "@/lib/db/finance";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function ownsOrAdmin(id: string, user: { id: string; role: string } | null): Promise<boolean> {",
    "  if (!user) return false;",
    "  if (canAccessAdmin(user.role)) return true;",
    "  const budget = await getBudget(id);",
    "  return Boolean(budget && budget.ownerId && budget.ownerId === user.id);",
    "}",
    "",
    "// Update a budget item — admins, or the owner of the row.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const scoped = { id: String(user.id), role: String(user.role) };",
    '  if (!(await ownsOrAdmin(id, scoped))) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const category = typeof body.category === "string" ? body.category.trim() : "";',
    "  const allocatedAmount = Number(body.allocatedAmount);",
    '  const period = BUDGET_PERIODS.includes(body.period as BudgetPeriod) ? (body.period as BudgetPeriod) : "monthly";',
    "  if (category.length < 2 || !Number.isFinite(allocatedAmount) || allocatedAmount <= 0) {",
    '    return NextResponse.json({ ok: false, message: "A category and a positive amount are required." }, { status: 400 });',
    "  }",
    "  const ok = await updateBudget(id, { category, allocatedAmount, period });",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update budgets." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "// Delete a budget item — admins, or the owner of the row.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const scoped = { id: String(user.id), role: String(user.role) };",
    '  if (!(await ownsOrAdmin(id, scoped))) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const ok = await deleteBudget(id);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to delete budgets." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/finance/expenses/route.ts (list + create) ------------------

function expenseApiFile(): GeneratedModuleFile {
  return file("src/app/api/finance/expenses/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listExpenses, createExpense, expenseTotals, PAYMENT_STATUSES, financeEnabled } from "@/lib/db/finance";',
    'import type { PaymentStatus } from "@/lib/db/finance";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!financeEnabled()) return NextResponse.json({ ok: false, message: "Finance is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const expenses = await listExpenses({",
    '    year: Number(url.searchParams.get("year")) || new Date().getFullYear(),',
    '    category: url.searchParams.get("category") || undefined,',
    '    status: url.searchParams.get("status") || undefined,',
    '    search: url.searchParams.get("search") || undefined,',
    "    ownerId",
    "  });",
    "  return NextResponse.json({ ok: true, expenses, totals: expenseTotals(expenses) });",
    "}",
    "",
    "// Record an expense — scoped to the signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const vendor = typeof body.vendor === "string" ? body.vendor.trim() : "";',
    "  const amount = Number(body.amount);",
    '  const date = typeof body.date === "string" ? body.date.trim() : "";',
    "  if (vendor.length < 2 || !Number.isFinite(amount) || amount <= 0 || !date) {",
    '    return NextResponse.json({ ok: false, message: "A vendor, amount, and date are required." }, { status: 400 });',
    "  }",
    '  const paymentStatus = PAYMENT_STATUSES.includes(body.paymentStatus as PaymentStatus) ? (body.paymentStatus as PaymentStatus) : "Pending";',
    "  const created = await createExpense({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    vendor,",
    "    amount,",
    "    date,",
    '    category: typeof body.category === "string" ? body.category : undefined,',
    "    paymentStatus,",
    '    paymentMethod: typeof body.paymentMethod === "string" ? body.paymentMethod : undefined,',
    '    checkNumber: typeof body.checkNumber === "string" ? body.checkNumber : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save expenses." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, expense: created });",
    "}"
  ]);
}

// ---- src/app/api/finance/expenses/[id]/route.ts (status update + delete) ----

function expenseDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/finance/expenses/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getExpense, updateExpenseStatus, deleteExpense, PAYMENT_STATUSES, financeEnabled } from "@/lib/db/finance";',
    'import type { PaymentStatus } from "@/lib/db/finance";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function ownsOrAdmin(id: string, user: { id: string; role: string } | null): Promise<boolean> {",
    "  if (!user) return false;",
    "  if (canAccessAdmin(user.role)) return true;",
    "  const expense = await getExpense(id);",
    "  return Boolean(expense && expense.ownerId && expense.ownerId === user.id);",
    "}",
    "",
    "// Update payment status, ported from ExpenseTracking.tsx updatePaymentStatus.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const scoped = { id: String(user.id), role: String(user.role) };",
    '  if (!(await ownsOrAdmin(id, scoped))) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  if (!PAYMENT_STATUSES.includes(body.paymentStatus as PaymentStatus)) {",
    '    return NextResponse.json({ ok: false, message: "Unknown status." }, { status: 400 });',
    "  }",
    "  const ok = await updateExpenseStatus(id, body.paymentStatus as PaymentStatus);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update expenses." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "// Delete an expense, ported from ExpenseTracking.tsx handleDelete.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const scoped = { id: String(user.id), role: String(user.role) };",
    '  if (!(await ownsOrAdmin(id, scoped))) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const ok = await deleteExpense(id);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to delete expenses." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/finance/giving/route.ts (list + create) --------------------

function givingApiFile(): GeneratedModuleFile {
  return file("src/app/api/finance/giving/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listGiving, createGiving, givingReport, financeEnabled } from "@/lib/db/finance";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!financeEnabled()) return NextResponse.json({ ok: false, message: "Finance is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const giving = await listGiving({",
    '    year: Number(url.searchParams.get("year")) || new Date().getFullYear(),',
    '    fund: url.searchParams.get("fund") || undefined,',
    '    search: url.searchParams.get("search") || undefined,',
    "    ownerId",
    "  });",
    "  return NextResponse.json({ ok: true, giving, report: givingReport(giving) });",
    "}",
    "",
    "// Record a gift — scoped to the signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const amount = Number(body.amount);",
    '  const date = typeof body.date === "string" ? body.date.trim() : "";',
    "  if (!Number.isFinite(amount) || amount <= 0 || !date) {",
    '    return NextResponse.json({ ok: false, message: "An amount and a date are required." }, { status: 400 });',
    "  }",
    "  const created = await createGiving({",
    "    ownerId: user?.id ? String(user.id) : null,",
    '    donorName: typeof body.donorName === "string" ? body.donorName : undefined,',
    "    amount,",
    "    date,",
    '    fund: typeof body.fund === "string" ? body.fund : undefined,',
    '    paymentMethod: typeof body.paymentMethod === "string" ? body.paymentMethod : undefined,',
    '    checkNumber: typeof body.checkNumber === "string" ? body.checkNumber : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save giving." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, giving: created });",
    "}"
  ]);
}

// ---- src/app/finance/page.tsx (overview: stats + transactions + bills) ------

function financePageFile(): GeneratedModuleFile {
  return file("src/app/finance/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { financialStats, recentTransactions, upcomingBills, financeEnabled } from "@/lib/db/finance";',
    'import type { Period } from "@/lib/db/finance";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function money(amount: number): string {",
    '  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);',
    "}",
    "",
    "export default async function FinancePage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ period?: string }>;",
    "}) {",
    "  if (!financeEnabled()) {",
    '    return (<main className="shell"><h1>Finances</h1><p>Finance is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/finance");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const allowed: Period[] = ["week", "month", "quarter", "year"];',
    '  const period: Period = allowed.includes((params?.period || "") as Period) ? (params?.period as Period) : "month";',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const stats = await financialStats(period, ownerId);",
    "  const transactions = await recentTransactions(period, ownerId);",
    "  const bills = await upcomingBills(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Finances</p>',
    "      <h1>Financial overview</h1>",
    "      <p>Track giving, expenses, and financial health in one place.</p>",
    '      <form className="stack" method="get">',
    '        <label className="note" htmlFor="period">Period</label>',
    '        <select className="input" id="period" name="period" defaultValue={period}>',
    '          <option value="week">Last week</option>',
    '          <option value="month">Last month</option>',
    '          <option value="quarter">Last quarter</option>',
    '          <option value="year">Last year</option>',
    "        </select>",
    '        <button className="button primary" type="submit">Update</button>',
    "      </form>",
    '      <section className="grid">',
    '        <article className="card"><span>Total income</span><strong>{money(stats.totalIncome)}</strong></article>',
    '        <article className="card"><span>Total expenses</span><strong>{money(stats.totalExpenses)}</strong></article>',
    '        <article className="card"><span>Net income</span><strong>{money(stats.netIncome)}</strong></article>',
    '        <article className="card"><span>Growth</span><strong>{stats.monthlyGrowth >= 0 ? "+" : ""}{stats.monthlyGrowth.toFixed(1)}%</strong></article>',
    "      </section>",
    "      <h2>Recent transactions</h2>",
    "      {transactions.length === 0 ? (",
    '        <p className="note">No transactions in this period yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {transactions.map((t) => (",
    '            <article className="wide-card" key={`${t.type}-${t.id}`}>',
    '              <span>{t.type === "income" ? "Income" : "Expense"}</span>',
    "              <strong>{t.description}</strong>",
    '              <p className="note">{t.date} · {t.type === "income" ? "+" : "-"}{money(t.amount)} · {t.status}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Upcoming bills</h2>",
    "      {bills.length === 0 ? (",
    '        <p className="note">No upcoming bills. All caught up.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {bills.map((b) => (",
    '            <article className="wide-card" key={b.id}>',
    "              <span>{b.category}</span>",
    "              <strong>{b.vendor}</strong>",
    '              <p className="note">Due {b.dueDate} · {money(b.amount)}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p className="stack">',
    '        <Link className="button" href="/finance/budgets">Budgets</Link>',
    '        <Link className="button" href="/finance/expenses">Expenses</Link>',
    '        <Link className="button" href="/finance/giving">Giving reports</Link>',
    "      </p>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/budgets/page.tsx (budget overview + add/edit) ----------

function budgetsPageFile(): GeneratedModuleFile {
  return file("src/app/finance/budgets/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { budgetPerformance, EXPENSE_CATEGORIES, financeEnabled } from "@/lib/db/finance";',
    'import { BudgetManager } from "./budget-manager";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function money(amount: number): string {",
    '  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);',
    "}",
    "",
    "export default async function BudgetsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ year?: string }>;",
    "}) {",
    "  if (!financeEnabled()) {",
    '    return (<main className="shell"><h1>Budgets</h1><p>Finance is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/finance/budgets");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    "  const year = Number(params?.year) || new Date().getFullYear();",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const budgets = await budgetPerformance(year, ownerId);",
    "  const totalBudget = budgets.reduce((s, b) => s + b.annualBudget, 0);",
    "  const totalSpent = budgets.reduce((s, b) => s + b.spent, 0);",
    "  const totalRemaining = totalBudget - totalSpent;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Budgets</p>',
    "      <h1>Budget overview</h1>",
    "      <p>Track spending against your budget. Amounts are annualised from each item's period.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Total budget</span><strong>{money(totalBudget)}</strong></article>',
    '        <article className="card"><span>Total spent</span><strong>{money(totalSpent)}</strong></article>',
    '        <article className="card"><span>Remaining</span><strong>{money(totalRemaining)}</strong></article>',
    "      </section>",
    "      <h2>Budget performance ({year})</h2>",
    "      {budgets.length === 0 ? (",
    '        <p className="note">No budget items for {year}. Add your first one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {budgets.map((b) => (",
    '            <article className="wide-card" key={b.id}>',
    '              <span>{b.status === "over" ? "Over budget" : b.status === "warning" ? "Near limit" : "On track"}</span>',
    "              <strong>{b.category}</strong>",
    '              <p className="note">Budget {money(b.annualBudget)} · Spent {money(b.spent)} · Remaining {money(b.remaining)}</p>',
    '              <p className="note">{b.percentage.toFixed(1)}% of budget used</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Add a budget item</h2>",
    "      <BudgetManager year={year} categories={EXPENSE_CATEGORIES} />",
    '      <p><Link className="button" href="/finance">Back to overview</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/budgets/budget-manager.tsx (client) --------------------

function budgetManagerFile(): GeneratedModuleFile {
  return file("src/app/finance/budgets/budget-manager.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The add-budget form, ported from BudgetOverview.tsx's add/edit modal:",
    "// category, allocated amount, and period.",
    "export function BudgetManager({ year, categories }: { year: number; categories: string[] }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/finance/budgets", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          category: form.get("category"),',
    '          allocatedAmount: Number(form.get("allocatedAmount")),',
    '          period: form.get("period"),',
    "          year",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Budget item added.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <select className="input" name="category" aria-label="Category" required defaultValue="">',
    '        <option value="" disabled>Select a category</option>',
    "        {categories.map((c) => (",
    "          <option key={c} value={c}>{c}</option>",
    "        ))}",
    "      </select>",
    '      <input className="input" name="allocatedAmount" type="number" step="0.01" min="0.01" placeholder="Allocated amount" aria-label="Allocated amount" required />',
    '      <select className="input" name="period" aria-label="Period" defaultValue="monthly">',
    '        <option value="monthly">Monthly</option>',
    '        <option value="quarterly">Quarterly</option>',
    '        <option value="annually">Annually</option>',
    "      </select>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Add budget item"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/expenses/page.tsx (expense tracking + record) ----------

function expensesPageFile(): GeneratedModuleFile {
  return file("src/app/finance/expenses/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listExpenses, expenseTotals, EXPENSE_CATEGORIES, financeEnabled } from "@/lib/db/finance";',
    'import { RecordExpenseForm } from "./record-expense-form";',
    'import { ExpenseStatus } from "./expense-status";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function money(amount: number): string {",
    '  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);',
    "}",
    "",
    "export default async function ExpensesPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ year?: string; category?: string; status?: string; q?: string }>;",
    "}) {",
    "  if (!financeEnabled()) {",
    '    return (<main className="shell"><h1>Expenses</h1><p>Finance is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/finance/expenses");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    "  const year = Number(params?.year) || new Date().getFullYear();",
    '  const category = (params?.category || "").trim();',
    '  const statusFilter = (params?.status || "").trim();',
    '  const q = (params?.q || "").trim();',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const expenses = await listExpenses({ year, category: category || undefined, status: statusFilter || undefined, search: q || undefined, ownerId });",
    "  const totals = expenseTotals(expenses);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Expenses</p>',
    "      <h1>Expense tracking</h1>",
    "      <p>Monitor and manage expenses, and keep payment status up to date.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Total</span><strong>{money(totals.total)}</strong></article>',
    '        <article className="card"><span>Paid</span><strong>{money(totals.paid)}</strong></article>',
    '        <article className="card"><span>Pending</span><strong>{money(totals.pending)}</strong></article>',
    '        <article className="card"><span>Overdue</span><strong>{money(totals.overdue)}</strong></article>',
    "      </section>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" name="year" type="number" defaultValue={year} aria-label="Year" />',
    '        <select className="input" name="category" defaultValue={category} aria-label="Category">',
    '          <option value="">All categories</option>',
    "          {EXPENSE_CATEGORIES.map((c) => (",
    "            <option key={c} value={c}>{c}</option>",
    "          ))}",
    "        </select>",
    '        <select className="input" name="status" defaultValue={statusFilter} aria-label="Status">',
    '          <option value="">All status</option>',
    '          <option value="Pending">Pending</option>',
    '          <option value="Paid">Paid</option>',
    '          <option value="Overdue">Overdue</option>',
    "        </select>",
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search expenses" aria-label="Search expenses" />',
    '        <button className="button primary" type="submit">Filter</button>',
    "      </form>",
    "      {expenses.length === 0 ? (",
    '        <p className="note">No expenses match these filters yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {expenses.map((e) => (",
    '            <article className="wide-card" key={e.id}>',
    "              <span>{e.category}</span>",
    "              <strong>{e.vendor}</strong>",
    '              <p className="note">{e.date} · {money(e.amount)}{e.notes ? ` · ${e.notes}` : ""}</p>',
    "              <ExpenseStatus id={e.id} current={e.paymentStatus} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Record an expense</h2>",
    "      <RecordExpenseForm categories={EXPENSE_CATEGORIES} />",
    '      <p><Link className="button" href="/finance">Back to overview</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/expenses/record-expense-form.tsx (client) --------------

function recordExpenseFormFile(): GeneratedModuleFile {
  return file("src/app/finance/expenses/record-expense-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Record-expense form, ported from the Association app's RecordExpenseForm:",
    "// vendor, amount, date, category, payment status, method, check number, notes.",
    "export function RecordExpenseForm({ categories }: { categories: string[] }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/finance/expenses", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          vendor: form.get("vendor"),',
    '          amount: Number(form.get("amount")),',
    '          date: form.get("date"),',
    '          category: form.get("category"),',
    '          paymentStatus: form.get("paymentStatus"),',
    '          paymentMethod: form.get("paymentMethod"),',
    '          checkNumber: form.get("checkNumber"),',
    '          notes: form.get("notes")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Expense recorded.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="vendor" placeholder="Vendor" aria-label="Vendor" required />',
    '      <input className="input" name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" aria-label="Amount" required />',
    '      <input className="input" name="date" type="date" aria-label="Date" required />',
    '      <select className="input" name="category" aria-label="Category" defaultValue="Other">',
    "        {categories.map((c) => (",
    "          <option key={c} value={c}>{c}</option>",
    "        ))}",
    "      </select>",
    '      <select className="input" name="paymentStatus" aria-label="Payment status" defaultValue="Pending">',
    '        <option value="Pending">Pending</option>',
    '        <option value="Paid">Paid</option>',
    '        <option value="Overdue">Overdue</option>',
    "      </select>",
    '      <input className="input" name="paymentMethod" placeholder="Payment method (optional)" aria-label="Payment method" />',
    '      <input className="input" name="checkNumber" placeholder="Check number (optional)" aria-label="Check number" />',
    '      <input className="input" name="notes" placeholder="Notes (optional)" aria-label="Notes" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Record expense"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/expenses/expense-status.tsx (client) -------------------

function expenseStatusFile(): GeneratedModuleFile {
  return file("src/app/finance/expenses/expense-status.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Inline payment-status control, ported from ExpenseTracking.tsx's status",
    "// select + updatePaymentStatus.",
    'const STATUSES = ["Pending", "Paid", "Overdue"] as const;',
    "",
    "export function ExpenseStatus({ id, current }: { id: string; current: string }) {",
    "  const router = useRouter();",
    "  const [value, setValue] = useState(current);",
    '  const [working, setWorking] = useState(false);',
    '  const [error, setError] = useState("");',
    "",
    "  async function change(next: string) {",
    "    setValue(next);",
    "    setWorking(true);",
    '    setError("");',
    "    try {",
    "      const response = await fetch(`/api/finance/expenses/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ paymentStatus: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    "        setValue(current);",
    '        setError(data.message || "Could not update.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    "      setValue(current);",
    '      setError("Could not reach the server.");',
    "    } finally {",
    "      setWorking(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <select className="input" value={value} onChange={(e) => change(e.target.value)} disabled={working} aria-label="Payment status">',
    "        {STATUSES.map((s) => (",
    "          <option key={s} value={s}>{s}</option>",
    "        ))}",
    "      </select>",
    '      {error ? <span className="note" role="alert">{error}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/giving/page.tsx (giving reports + record) --------------

function givingPageFile(): GeneratedModuleFile {
  return file("src/app/finance/giving/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listGiving, givingReport, financeEnabled } from "@/lib/db/finance";',
    'import { RecordGivingForm } from "./record-giving-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "function money(amount: number): string {",
    '  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount);',
    "}",
    "",
    "export default async function GivingPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ year?: string; fund?: string; q?: string }>;",
    "}) {",
    "  if (!financeEnabled()) {",
    '    return (<main className="shell"><h1>Giving</h1><p>Finance is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/finance/giving");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    "  const year = Number(params?.year) || new Date().getFullYear();",
    '  const fund = (params?.fund || "").trim();',
    '  const q = (params?.q || "").trim();',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const giving = await listGiving({ year, fund: fund || undefined, search: q || undefined, ownerId });",
    "  const report = givingReport(giving);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Giving</p>',
    "      <h1>Giving reports</h1>",
    "      <p>View giving statistics and where support is coming from.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" name="year" type="number" defaultValue={year} aria-label="Year" />',
    '        <input className="input" name="fund" defaultValue={fund} placeholder="Fund (optional)" aria-label="Fund" />',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search giving" aria-label="Search giving" />',
    '        <button className="button primary" type="submit">Filter</button>',
    "      </form>",
    '      <section className="grid">',
    '        <article className="card"><span>Total giving</span><strong>{money(report.totalGiving)}</strong></article>',
    '        <article className="card"><span>Unique givers</span><strong>{report.uniqueGivers}</strong></article>',
    '        <article className="card"><span>Average gift</span><strong>{money(report.averageGift)}</strong></article>',
    '        <article className="card"><span>Total gifts</span><strong>{report.totalGifts}</strong></article>',
    "      </section>",
    "      <h2>Giving by fund</h2>",
    "      {report.givingByFund.length === 0 ? (",
    '        <p className="note">No giving recorded for this period yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {report.givingByFund.map((f) => (",
    '            <article className="wide-card" key={f.fund}>',
    "              <strong>{f.fund}</strong>",
    '              <p className="note">{money(f.amount)}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Top givers ({year})</h2>",
    "      {report.topGivers.length === 0 ? (",
    '        <p className="note">No named givers yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {report.topGivers.map((g) => (",
    '            <article className="wide-card" key={g.donorName}>',
    "              <strong>{g.donorName}</strong>",
    '              <p className="note">{money(g.total)} · {g.gifts} gifts</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Record a gift</h2>",
    "      <RecordGivingForm />",
    '      <p><Link className="button" href="/finance">Back to overview</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/finance/giving/record-giving-form.tsx (client) -----------------

function recordGivingFormFile(): GeneratedModuleFile {
  return file("src/app/finance/giving/record-giving-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Record-giving form, ported from the Association app's donation model:",
    "// donor name, amount, date, fund, payment method, check number, notes.",
    "export function RecordGivingForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/finance/giving", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          donorName: form.get("donorName"),',
    '          amount: Number(form.get("amount")),',
    '          date: form.get("date"),',
    '          fund: form.get("fund"),',
    '          paymentMethod: form.get("paymentMethod"),',
    '          checkNumber: form.get("checkNumber"),',
    '          notes: form.get("notes")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Gift recorded.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="donorName" placeholder="Donor name (optional)" aria-label="Donor name" />',
    '      <input className="input" name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" aria-label="Amount" required />',
    '      <input className="input" name="date" type="date" aria-label="Date" required />',
    '      <input className="input" name="fund" placeholder="Fund (e.g. General)" aria-label="Fund" defaultValue="General" />',
    '      <input className="input" name="paymentMethod" placeholder="Payment method (optional)" aria-label="Payment method" />',
    '      <input className="input" name="checkNumber" placeholder="Check number (optional)" aria-label="Check number" />',
    '      <input className="input" name="notes" placeholder="Notes (optional)" aria-label="Notes" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Record gift"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

export const financeAccountingModule: AppModule = {
  slug: "finance-accounting",
  name: "Finance & Accounting",
  tier: "optional",
  featureFlagEnv: "FEATURE_FINANCE",
  files: () => [
    financeLibFile(),
    budgetApiFile(),
    budgetDetailApiFile(),
    expenseApiFile(),
    expenseDetailApiFile(),
    givingApiFile(),
    financePageFile(),
    budgetsPageFile(),
    budgetManagerFile(),
    expensesPageFile(),
    recordExpenseFormFile(),
    expenseStatusFile(),
    givingPageFile(),
    recordGivingFormFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists finance_accounting_budgets (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  category text not null default 'Other',",
      "  allocated_amount numeric(14,2) not null default 0,",
      "  period text not null default 'monthly',",
      "  year integer not null default extract(year from now()),",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists finance_accounting_budgets_year_idx on finance_accounting_budgets (year);",
      "create index if not exists finance_accounting_budgets_owner_idx on finance_accounting_budgets (owner_id);",
      "",
      "create table if not exists finance_accounting_expenses (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  vendor text not null default '',",
      "  amount numeric(14,2) not null default 0,",
      "  date date not null default current_date,",
      "  category text not null default 'Other',",
      "  payment_status text not null default 'Pending',",
      "  payment_method text not null default '',",
      "  check_number text not null default '',",
      "  notes text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists finance_accounting_expenses_date_idx on finance_accounting_expenses (date desc);",
      "create index if not exists finance_accounting_expenses_status_idx on finance_accounting_expenses (payment_status);",
      "create index if not exists finance_accounting_expenses_owner_idx on finance_accounting_expenses (owner_id);",
      "",
      "create table if not exists finance_accounting_giving (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  donor_name text not null default 'Anonymous',",
      "  amount numeric(14,2) not null default 0,",
      "  date date not null default current_date,",
      "  fund text not null default 'General',",
      "  payment_method text not null default '',",
      "  check_number text not null default '',",
      "  notes text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists finance_accounting_giving_date_idx on finance_accounting_giving (date desc);",
      "create index if not exists finance_accounting_giving_fund_idx on finance_accounting_giving (fund);",
      "create index if not exists finance_accounting_giving_owner_idx on finance_accounting_giving (owner_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into finance_accounting_budgets (category, allocated_amount, period, year) values",
      "  ('Utilities', 1200, 'monthly', extract(year from now())),",
      "  ('Programs', 5000, 'quarterly', extract(year from now())),",
      "  ('Office Supplies', 3000, 'annually', extract(year from now()))",
      "on conflict do nothing;",
      "",
      "insert into finance_accounting_giving (donor_name, amount, date, fund) values",
      "  ('Alex R.', 250, current_date, 'General'),",
      "  ('Jordan P.', 500, current_date, 'Building')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Finance & Accounting — set to false to switch budgets + expenses + giving off.",
    "FEATURE_FINANCE=true"
  ],
  homeLinks: () => ['        <a className="button" href="/finance">Finances</a>'],
  navLinks: () => [{ href: "/finance", label: "Finances" }]
};
