// growth-tracking — the per-user progress + streak layer. Track habits, goals,
// reading progress, skills, and milestones over time and keep the momentum with
// calendar-based streaks. This is deliberately the TRACKING layer, NOT a content
// library: it never stores lessons or readings, only a user's own trackables and
// their day-by-day progress.
//
// Ported from ChurchConnect's real progress-tracking code:
//   - backend/routes/reading_plans.py — the per-user progress record
//     (user_id, plan_id, started_at, current_day, completed_days[],
//     last_completed_at, streak, longest_streak, paused), the calendar-based
//     streak math in complete_day (same-day = no change, +1 day = increment,
//     gap > 1 = reset to 1), longest = max(longest, streak), the "advance
//     current_day to the smallest day not yet completed" progression, the
//     uncomplete-day undo, and pause/abandon lifecycle, plus _update_streak
//     (break the streak if the last completion was more than one day ago).
//   - backend/routes/challenges.py — the user_streaks model (current_streak,
//     longest_streak, last_completion_date, total_completions) and the
//     streak_active derivation (last completion >= yesterday), plus the
//     completion-history + by-category rollups and the streak bonus idea.
// Generalized off the church/reading framing into a plain "trackable" model with a
// type (habit / goal / reading / skill / milestone), a target of steps ("days" in
// the source become generic step numbers), and a per-user progress record that
// carries the exact same fields + streak logic. A milestone log (ported from the
// completion history) records each step as it lands.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_TRACKING); customers track their own goals (rows scoped
// to user.id), admins can seed shared trackables and see everyone's activity.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/growth-tracking.ts (model + queries, ported) -----------------

function trackingLibFile(): GeneratedModuleFile {
  return file("src/lib/db/growth-tracking.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The kind of thing a person is tracking. Ported in spirit from the reading-plan",
    '// idea (a "plan" is one of these) and generalized to any app: a habit to keep, a',
    "// goal to reach, a reading/course to work through, a skill to build, or a one-off",
    "// milestone. The step numbers below stand in for reading_plans.py's day numbers.",
    'export type TrackableType = "habit" | "goal" | "reading" | "skill" | "milestone";',
    "",
    "export const TRACKABLE_TYPES: TrackableType[] = [",
    '  "habit",',
    '  "goal",',
    '  "reading",',
    '  "skill",',
    '  "milestone"',
    "];",
    "",
    "// A trackable — the thing being tracked. Owner-scoped when ownerId is set; a null",
    "// ownerId means an admin-seeded shared trackable anyone can start (ported from the",
    "// static reading-plan catalog, which was shared across all users).",
    "export type Trackable = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  description: string;",
    "  type: TrackableType;",
    "  category: string;",
    "  targetSteps: number;",
    "  isShared: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "// A user's progress on a trackable — ported field-for-field from",
    "// reading_plans.py's reading_plan_progress document: startedAt, currentStep",
    "// (=current_day), completedSteps (=completed_days, sorted ascending),",
    "// lastCompletedAt, streak, longestStreak, paused. totalCompletions is carried",
    "// over from challenges.py's user_streaks.",
    "export type Progress = {",
    "  id: string;",
    "  userId: string;",
    "  trackableId: string;",
    "  startedAt: string;",
    "  currentStep: number;",
    "  completedSteps: number[];",
    "  lastCompletedAt: string | null;",
    "  streak: number;",
    "  longestStreak: number;",
    "  totalCompletions: number;",
    "  paused: boolean;",
    "  updatedAt: string;",
    "};",
    "",
    "// A single logged step, ported from the challenge completion history: which step",
    "// landed, an optional note, and when. This is the milestone log.",
    "export type Milestone = {",
    "  id: string;",
    "  userId: string;",
    "  trackableId: string;",
    "  step: number;",
    "  note: string;",
    "  completedAt: string;",
    "};",
    "",
    "// Progress joined with its trackable + a live streak_active flag (ported from",
    "// challenges.py get_user_streak's streak_active = last completion >= yesterday).",
    "export type TrackedItem = {",
    "  progress: Progress;",
    "  trackable: Trackable;",
    "  streakActive: boolean;",
    "  finished: boolean;",
    "};",
    "",
    "export type TrackableFilters = {",
    "  ownerId?: string;",
    "  includeShared?: boolean;",
    "  type?: string;",
    "  q?: string;",
    "  limit?: number;",
    "};",
    "",
    "// Same-calendar-day check used by the streak math, ported from reading_plans.py's",
    "// use of datetime.date() comparisons.",
    "function toDateKey(iso: string | null): string | null {",
    "  if (!iso) return null;",
    "  const ts = new Date(iso).getTime();",
    "  if (Number.isNaN(ts)) return null;",
    "  return new Date(ts).toISOString().slice(0, 10);",
    "}",
    "",
    "// Whole-day difference between two ISO instants (b - a), calendar based.",
    "function dayDiff(aIso: string, bIso: string): number {",
    "  const a = new Date(toDateKey(aIso) + \"T00:00:00.000Z\").getTime();",
    "  const b = new Date(toDateKey(bIso) + \"T00:00:00.000Z\").getTime();",
    "  return Math.round((b - a) / (1000 * 60 * 60 * 24));",
    "}",
    "",
    "// Recompute the streak on completing a step, ported verbatim from",
    "// reading_plans.py complete_day: same calendar day => no change; exactly one day",
    "// later => +1; a bigger gap => reset to 1; first ever completion => 1.",
    "export function nextStreak(lastCompletedAt: string | null, current: number, nowIso: string): number {",
    "  if (!lastCompletedAt) return 1;",
    "  const delta = dayDiff(lastCompletedAt, nowIso);",
    "  if (delta <= 0) return current;",
    "  if (delta === 1) return current + 1;",
    "  return 1;",
    "}",
    "",
    "// Break a stale streak on read, ported from reading_plans.py _update_streak: if",
    "// the last completion was more than one day ago the streak is 0.",
    "export function streakOnRead(streak: number, lastCompletedAt: string | null, nowIso: string): number {",
    "  if (!lastCompletedAt) return streak;",
    "  const diff = dayDiff(lastCompletedAt, nowIso);",
    "  return diff > 1 ? 0 : streak;",
    "}",
    "",
    "// The streak is 'active' if the last completion was today or yesterday, ported",
    "// from challenges.py get_user_streak (last_date >= yesterday).",
    "export function isStreakActive(lastCompletedAt: string | null, nowIso: string): boolean {",
    "  if (!lastCompletedAt) return false;",
    "  return dayDiff(lastCompletedAt, nowIso) <= 1;",
    "}",
    "",
    "// Advance currentStep to the smallest step not yet completed, ported from the",
    "// 'for d in range(1, total+1): if d not in completed' loop in complete_day.",
    "export function nextStep(completed: number[], targetSteps: number): number {",
    "  const done = new Set(completed);",
    "  for (let d = 1; d <= targetSteps; d += 1) {",
    "    if (!done.has(d)) return d;",
    "  }",
    "  return targetSteps + 1; // finished",
    "}",
    "",
    "const fallbackTrackables: Trackable[] = [",
    "  {",
    '    id: "sample-habit",',
    "    ownerId: null,",
    '    title: "Daily 10-minute walk",',
    '    description: "A short walk every day to build a steady habit.",',
    '    type: "habit",',
    '    category: "wellbeing",',
    "    targetSteps: 30,",
    "    isShared: true,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-reading",',
    "    ownerId: null,",
    '    title: "Read a chapter a day",',
    '    description: "Work through a book one chapter at a time and keep the streak.",',
    '    type: "reading",',
    '    category: "learning",',
    "    targetSteps: 21,",
    "    isShared: true,",
    '    createdAt: "2025-01-02T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackProgress: Progress[] = [",
    "  {",
    '    id: "sample-progress",',
    '    userId: "sample-user",',
    '    trackableId: "sample-habit",',
    '    startedAt: "2025-01-01T00:00:00.000Z",',
    "    currentStep: 4,",
    "    completedSteps: [1, 2, 3],",
    '    lastCompletedAt: "2025-01-03T00:00:00.000Z",',
    "    streak: 3,",
    "    longestStreak: 3,",
    "    totalCompletions: 3,",
    "    paused: false,",
    '    updatedAt: "2025-01-03T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function toSteps(v: unknown): number[] {",
    "  if (Array.isArray(v)) return v.map((x) => Number(x)).filter((n) => Number.isFinite(n));",
    '  if (typeof v === "string" && v.trim()) {',
    "    try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => Number(x)).filter((n) => Number.isFinite(n)) : []; } catch { return []; }",
    "  }",
    "  return [];",
    "}",
    "",
    "function rowToTrackable(row: Record<string, unknown>): Trackable {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    type: (String(row.type || "goal") as TrackableType),',
    '    category: String(row.category || "general"),',
    "    targetSteps: Math.max(1, Number(row.target_steps || 1)),",
    '    isShared: row.is_shared === true || String(row.is_shared) === "true",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToProgress(row: Record<string, unknown>): Progress {",
    "  return {",
    "    id: String(row.id),",
    "    userId: String(row.user_id),",
    "    trackableId: String(row.trackable_id),",
    '    startedAt: row.started_at ? String(row.started_at) : "",',
    "    currentStep: Math.max(1, Number(row.current_step || 1)),",
    "    completedSteps: toSteps(row.completed_steps),",
    "    lastCompletedAt: row.last_completed_at != null ? String(row.last_completed_at) : null,",
    "    streak: Number(row.streak || 0),",
    "    longestStreak: Number(row.longest_streak || 0),",
    "    totalCompletions: Number(row.total_completions || 0),",
    '    paused: row.paused === true || String(row.paused) === "true",',
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "function rowToMilestone(row: Record<string, unknown>): Milestone {",
    "  return {",
    "    id: String(row.id),",
    "    userId: String(row.user_id),",
    "    trackableId: String(row.trackable_id),",
    "    step: Number(row.step || 0),",
    '    note: String(row.note || ""),',
    '    completedAt: row.completed_at ? String(row.completed_at) : ""',
    "  };",
    "}",
    "",
    "// The columns we always select for a trackable, kept as one static fragment so we",
    "// never interpolate identifiers into a query string.",
    'const TRACKABLE_COLS = "id, owner_id, title, description, type, category, target_steps, is_shared, created_at";',
    'const PROGRESS_COLS = "id, user_id, trackable_id, started_at, current_step, completed_steps, last_completed_at, streak, longest_streak, total_completions, paused, updated_at";',
    "",
    "// List the trackables a user can start: their own, plus (optionally) the shared",
    "// admin-seeded catalog. Ported from the reading-plan catalog + my-plans split.",
    "export async function listTrackables(filters: TrackableFilters = {}): Promise<Trackable[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const type = (filters.type || "").trim();',
    "  const ownerId = filters.ownerId;",
    "  const includeShared = filters.includeShared !== false;",
    "  if (!hasDatabase()) {",
    "    return fallbackTrackables",
    "      .filter((t) => (ownerId ? t.ownerId === ownerId : true) || (includeShared && t.isShared))",
    "      .filter((t) => !type || t.type === type)",
    '      .filter((t) => !q || (t.title + " " + t.description + " " + t.category).toLowerCase().includes(q))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const like = q ? `%${q}%` : null;",
    "    const ty = type || null;",
    "    // Static tagged template — every dynamic value is parameterized ($n).",
    "    const rows = await sql`",
    "      select id, owner_id, title, description, type, category, target_steps, is_shared, created_at",
    "      from growth_tracking_trackables",
    "      where (",
    "        (${owner}::uuid is not null and owner_id = ${owner})",
    "        or (${includeShared}::boolean and is_shared = true)",
    "        or (${owner}::uuid is null and ${includeShared}::boolean)",
    "      )",
    "        and (${ty}::text is null or type = ${ty})",
    "        and (${like}::text is null",
    "          or lower(title) like ${like}",
    "          or lower(description) like ${like}",
    "          or lower(category) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToTrackable);",
    "  } catch {",
    "    return fallbackTrackables.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getTrackable(id: string): Promise<Trackable | null> {",
    "  if (!hasDatabase()) return fallbackTrackables.find((t) => t.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, title, description, type, category, target_steps, is_shared, created_at",
    "      from growth_tracking_trackables where id = ${id} limit 1`;",
    "    return rows[0] ? rowToTrackable(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateTrackableInput = {",
    "  ownerId: string | null;",
    "  title: string;",
    "  description?: string;",
    "  type?: TrackableType;",
    "  category?: string;",
    "  targetSteps?: number;",
    "  isShared?: boolean;",
    "};",
    "",
    "// Create a trackable. Owner-scoped by default; only an admin passes isShared to",
    "// seed the shared catalog (ownerId null + is_shared true).",
    "export async function createTrackable(input: CreateTrackableInput): Promise<Trackable | null> {",
    "  if (!hasDatabase()) return null;",
    '  const type: TrackableType = TRACKABLE_TYPES.includes(input.type as TrackableType) ? (input.type as TrackableType) : "goal";',
    "  const target = Math.min(3660, Math.max(1, Math.round(input.targetSteps || 30)));",
    "  const isShared = input.isShared === true;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into growth_tracking_trackables (",
    "        owner_id, title, description, type, category, target_steps, is_shared",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.title}, ${input.description || ""}, ${type},',
    '        ${input.category || "general"}, ${target}, ${isShared}',
    "      )",
    "      returning id, owner_id, title, description, type, category, target_steps, is_shared, created_at`;",
    "    return rows[0] ? rowToTrackable(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Start (or re-activate) tracking a trackable for a user. Ported from",
    "// reading_plans.py start_plan: if an active record exists, return it; if a paused",
    "// record exists, reactivate it and preserve completedSteps + streak; otherwise",
    "// create a fresh record at step 1.",
    "export async function startTracking(userId: string, trackableId: string): Promise<Progress | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const existingRows = await sql`",
    "      select id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "        last_completed_at, streak, longest_streak, total_completions, paused, updated_at",
    "      from growth_tracking_progress",
    "      where user_id = ${userId} and trackable_id = ${trackableId} limit 1`;",
    "    if (existingRows[0]) {",
    "      const existing = rowToProgress(existingRows[0]);",
    "      if (!existing.paused) return existing; // already active",
    "      // Reactivate a paused record, preserving progress + streak.",
    "      const rows = await sql`",
    "        update growth_tracking_progress set paused = false, updated_at = now()",
    "        where user_id = ${userId} and trackable_id = ${trackableId}",
    "        returning id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "          last_completed_at, streak, longest_streak, total_completions, paused, updated_at`;",
    "      return rows[0] ? rowToProgress(rows[0]) : existing;",
    "    }",
    "    const rows = await sql`",
    "      insert into growth_tracking_progress (",
    "        user_id, trackable_id, started_at, current_step, completed_steps,",
    "        last_completed_at, streak, longest_streak, total_completions, paused",
    "      ) values (",
    "        ${userId}, ${trackableId}, now(), 1, '[]'::jsonb, null, 0, 0, 0, false",
    "      )",
    "      returning id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "        last_completed_at, streak, longest_streak, total_completions, paused, updated_at`;",
    "    return rows[0] ? rowToProgress(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "async function getProgressRow(userId: string, trackableId: string): Promise<Progress | null> {",
    "  const sql = getDatabase();",
    "  const rows = await sql`",
    "    select id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "      last_completed_at, streak, longest_streak, total_completions, paused, updated_at",
    "    from growth_tracking_progress",
    "    where user_id = ${userId} and trackable_id = ${trackableId} limit 1`;",
    "  return rows[0] ? rowToProgress(rows[0]) : null;",
    "}",
    "",
    "// Mark a step complete + recompute the streak. Ported from reading_plans.py",
    "// complete_day: add the step (idempotent), run the calendar streak math, bump",
    "// longestStreak, advance currentStep to the next incomplete step, log a milestone,",
    "// and increment totalCompletions (from challenges.py). Same-day re-taps do not",
    "// change the streak and are not re-logged.",
    "export async function completeStep(userId: string, trackableId: string, step: number, note = \"\"): Promise<Progress | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const trackable = await getTrackable(trackableId);",
    "    if (!trackable) return null;",
    "    const target = trackable.targetSteps;",
    "    if (step < 1 || step > target) return null;",
    "    const doc = await getProgressRow(userId, trackableId);",
    "    if (!doc) return null;",
    "",
    "    const alreadyDone = doc.completedSteps.includes(step);",
    "    const completed = alreadyDone ? doc.completedSteps.slice() : [...doc.completedSteps, step].sort((a, b) => a - b);",
    "    const nowIso = new Date().toISOString();",
    "    const streak = nextStreak(doc.lastCompletedAt, doc.streak || 0, nowIso);",
    "    const longest = Math.max(doc.longestStreak || 0, streak);",
    "    const current = nextStep(completed, target);",
    "    const totalCompletions = alreadyDone ? doc.totalCompletions : doc.totalCompletions + 1;",
    "    const stepsJson = JSON.stringify(completed);",
    "",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update growth_tracking_progress set",
    "        completed_steps = ${stepsJson}::jsonb,",
    "        current_step = ${current},",
    "        last_completed_at = ${nowIso},",
    "        streak = ${streak},",
    "        longest_streak = ${longest},",
    "        total_completions = ${totalCompletions},",
    "        paused = false,",
    "        updated_at = now()",
    "      where user_id = ${userId} and trackable_id = ${trackableId}",
    "      returning id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "        last_completed_at, streak, longest_streak, total_completions, paused, updated_at`;",
    "",
    "    // Log the milestone (ported from the challenge completion history). Best-effort:",
    "    // never break the completion flow. Only log genuinely new steps.",
    "    if (!alreadyDone) {",
    "      try {",
    "        await sql`",
    "          insert into growth_tracking_milestones (user_id, trackable_id, step, note, completed_at)",
    "          values (${userId}, ${trackableId}, ${step}, ${note || \"\"}, ${nowIso})`;",
    "      } catch {",
    "        // milestone log is a nice-to-have.",
    "      }",
    "    }",
    "    return rows[0] ? rowToProgress(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Undo a completed step. Ported from reading_plans.py uncomplete_day: drop the",
    "// step, recompute currentStep, and delete the matching milestone.",
    "export async function uncompleteStep(userId: string, trackableId: string, step: number): Promise<Progress | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const trackable = await getTrackable(trackableId);",
    "    const doc = await getProgressRow(userId, trackableId);",
    "    if (!doc) return null;",
    "    const target = trackable ? trackable.targetSteps : Math.max(...doc.completedSteps, 1);",
    "    const completed = doc.completedSteps.filter((d) => d !== step);",
    "    const current = nextStep(completed, target);",
    "    const stepsJson = JSON.stringify(completed);",
    "    const total = Math.max(0, doc.totalCompletions - (doc.completedSteps.includes(step) ? 1 : 0));",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update growth_tracking_progress set",
    "        completed_steps = ${stepsJson}::jsonb,",
    "        current_step = ${current},",
    "        total_completions = ${total},",
    "        updated_at = now()",
    "      where user_id = ${userId} and trackable_id = ${trackableId}",
    "      returning id, user_id, trackable_id, started_at, current_step, completed_steps,",
    "        last_completed_at, streak, longest_streak, total_completions, paused, updated_at`;",
    "    try {",
    "      await sql`delete from growth_tracking_milestones where user_id = ${userId} and trackable_id = ${trackableId} and step = ${step}`;",
    "    } catch {",
    "      // best-effort.",
    "    }",
    "    return rows[0] ? rowToProgress(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Pause tracking (ported from reading_plans.py pause_plan). The record + progress",
    "// are preserved; it just stops counting as active.",
    "export async function pauseTracking(userId: string, trackableId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update growth_tracking_progress set paused = true, updated_at = now() where user_id = ${userId} and trackable_id = ${trackableId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Stop tracking entirely (ported from reading_plans.py abandon_plan). Removes the",
    "// progress record + its milestones for this user.",
    "export async function abandonTracking(userId: string, trackableId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from growth_tracking_progress where user_id = ${userId} and trackable_id = ${trackableId}`;",
    "    try {",
    "      await sql`delete from growth_tracking_milestones where user_id = ${userId} and trackable_id = ${trackableId}`;",
    "    } catch {",
    "      // best-effort.",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Everything a user is tracking, joined with the trackable + a live streak_active",
    "// flag and a finished flag. Ported from reading_plans.py my_reading_plans, which",
    "// re-ran _update_streak on read — we do the same so stale streaks show as broken.",
    "export async function listTracked(userId: string): Promise<TrackedItem[]> {",
    "  const nowIso = new Date().toISOString();",
    "  if (!hasDatabase()) {",
    "    return fallbackProgress",
    "      .filter((p) => p.userId === userId || userId === \"sample-user\")",
    "      .map((p) => {",
    "        const trackable = fallbackTrackables.find((t) => t.id === p.trackableId) || fallbackTrackables[0];",
    "        const streak = streakOnRead(p.streak, p.lastCompletedAt, nowIso);",
    "        return {",
    "          progress: { ...p, streak },",
    "          trackable,",
    "          streakActive: isStreakActive(p.lastCompletedAt, nowIso),",
    "          finished: p.currentStep > trackable.targetSteps",
    "        };",
    "      });",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select p.id, p.user_id, p.trackable_id, p.started_at, p.current_step, p.completed_steps,",
    "        p.last_completed_at, p.streak, p.longest_streak, p.total_completions, p.paused, p.updated_at,",
    "        t.id as t_id, t.owner_id as t_owner_id, t.title as t_title, t.description as t_description,",
    "        t.type as t_type, t.category as t_category, t.target_steps as t_target_steps,",
    "        t.is_shared as t_is_shared, t.created_at as t_created_at",
    "      from growth_tracking_progress p",
    "      join growth_tracking_trackables t on t.id = p.trackable_id",
    "      where p.user_id = ${userId}",
    "      order by p.updated_at desc`;",
    "    return rows.map((row: Record<string, unknown>) => {",
    "      const progress = rowToProgress(row);",
    "      const trackable = rowToTrackable({",
    "        id: row.t_id, owner_id: row.t_owner_id, title: row.t_title, description: row.t_description,",
    "        type: row.t_type, category: row.t_category, target_steps: row.t_target_steps,",
    "        is_shared: row.t_is_shared, created_at: row.t_created_at",
    "      });",
    "      const streak = streakOnRead(progress.streak, progress.lastCompletedAt, nowIso);",
    "      return {",
    "        progress: { ...progress, streak },",
    "        trackable,",
    "        streakActive: isStreakActive(progress.lastCompletedAt, nowIso),",
    "        finished: progress.currentStep > trackable.targetSteps",
    "      };",
    "    });",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// One tracked item for a user (ported from my_reading_plan).",
    "export async function getTracked(userId: string, trackableId: string): Promise<TrackedItem | null> {",
    "  const trackable = await getTrackable(trackableId);",
    "  if (!trackable) return null;",
    "  const nowIso = new Date().toISOString();",
    "  if (!hasDatabase()) {",
    "    const p = fallbackProgress.find((x) => x.trackableId === trackableId) || null;",
    "    if (!p) return null;",
    "    return {",
    "      progress: { ...p, streak: streakOnRead(p.streak, p.lastCompletedAt, nowIso) },",
    "      trackable,",
    "      streakActive: isStreakActive(p.lastCompletedAt, nowIso),",
    "      finished: p.currentStep > trackable.targetSteps",
    "    };",
    "  }",
    "  try {",
    "    const progress = await getProgressRow(userId, trackableId);",
    "    if (!progress) return null;",
    "    const streak = streakOnRead(progress.streak, progress.lastCompletedAt, nowIso);",
    "    return {",
    "      progress: { ...progress, streak },",
    "      trackable,",
    "      streakActive: isStreakActive(progress.lastCompletedAt, nowIso),",
    "      finished: progress.currentStep > trackable.targetSteps",
    "    };",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// A user's milestone log for a trackable, newest first (ported from",
    "// challenges.py get_user_completions' sorted history).",
    "export async function listMilestones(userId: string, trackableId: string, limit = 100): Promise<Milestone[]> {",
    "  const cap = Math.min(500, Math.max(1, limit));",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, trackable_id, step, note, completed_at",
    "      from growth_tracking_milestones",
    "      where user_id = ${userId} and trackable_id = ${trackableId}",
    "      order by completed_at desc limit ${cap}`;",
    "    return rows.map(rowToMilestone);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// A compact stat rollup for a user, ported from challenges.py get_user_completions",
    "// (total completions + best streak across everything they track).",
    "export type TrackingSummary = { activeCount: number; totalCompletions: number; bestStreak: number; currentStreak: number };",
    "",
    "export async function summarize(userId: string): Promise<TrackingSummary> {",
    "  const items = await listTracked(userId);",
    "  const active = items.filter((i) => !i.progress.paused && !i.finished);",
    "  const totalCompletions = items.reduce((sum, i) => sum + i.progress.totalCompletions, 0);",
    "  const bestStreak = items.reduce((best, i) => Math.max(best, i.progress.longestStreak), 0);",
    "  const currentStreak = items.reduce((best, i) => Math.max(best, i.streakActive ? i.progress.streak : 0), 0);",
    "  return { activeCount: active.length, totalCompletions, bestStreak, currentStreak };",
    "}",
    "",
    "export function trackingEnabled(): boolean {",
    '  return process.env.FEATURE_TRACKING !== "false";',
    "}"
  ]);
}

// ---- src/app/api/tracking/trackables/route.ts (list + create) ---------------

function trackablesApiFile(): GeneratedModuleFile {
  return file("src/app/api/tracking/trackables/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listTrackables, createTrackable, trackingEnabled } from "@/lib/db/growth-tracking";',
    'import type { TrackableType } from "@/lib/db/growth-tracking";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// The trackables a user can start: their own plus the shared catalog.",
    "export async function GET(request: Request) {",
    '  if (!trackingEnabled()) return NextResponse.json({ ok: false, message: "Tracking is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const trackables = await listTrackables({",
    "    ownerId: user?.id ? String(user.id) : undefined,",
    "    includeShared: true,",
    '    type: url.searchParams.get("type") || undefined,',
    '    q: url.searchParams.get("q") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, trackables });",
    "}",
    "",
    "// Create a trackable. Any signed-in customer can create a personal one; only an",
    "// admin may seed a shared catalog trackable (isShared).",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to add a goal." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give your goal a name." }, { status: 400 });',
    "  }",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const wantsShared = body.isShared === true;",
    "  const created = await createTrackable({",
    "    // Shared catalog items are owner-less; a shared request from a non-admin is",
    "    // downgraded to a personal trackable.",
    "    ownerId: wantsShared && isAdmin ? null : (user?.id ? String(user.id) : null),",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    "    type: (body.type as TrackableType) || undefined,",
    '    category: typeof body.category === "string" ? body.category : undefined,',
    '    targetSteps: typeof body.targetSteps === "number" ? body.targetSteps : Number(body.targetSteps) || undefined,',
    "    isShared: wantsShared && isAdmin",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save goals." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, trackable: created });",
    "}"
  ]);
}

// ---- src/app/api/tracking/route.ts (list what I track + start) --------------

function trackingApiFile(): GeneratedModuleFile {
  return file("src/app/api/tracking/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listTracked, startTracking, summarize, trackingEnabled } from "@/lib/db/growth-tracking";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Everything the signed-in user is tracking + a stat summary. Scoped to user.id.",
    "export async function GET() {",
    '  if (!trackingEnabled()) return NextResponse.json({ ok: false, message: "Tracking is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const userId = user?.id ? String(user.id) : "";',
    "  const items = await listTracked(userId);",
    "  const summary = await summarize(userId);",
    "  return NextResponse.json({ ok: true, items, summary });",
    "}",
    "",
    "// Start tracking a trackable, ported from reading_plans.py start_plan.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to start tracking." }, { status: 401 });',
    '  const userId = user?.id ? String(user.id) : "";',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const trackableId = typeof body.trackableId === "string" ? body.trackableId : "";',
    '  if (!trackableId) return NextResponse.json({ ok: false, message: "Pick something to track." }, { status: 400 });',
    "  const progress = await startTracking(userId, trackableId);",
    '  if (!progress) return NextResponse.json({ ok: false, message: "Connect a database to track progress." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, progress });",
    "}"
  ]);
}

// ---- src/app/api/tracking/[id]/route.ts (detail + complete/uncomplete/pause/abandon)

function trackingDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/tracking/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import {',
    "  getTracked,",
    "  listMilestones,",
    "  completeStep,",
    "  uncompleteStep,",
    "  pauseTracking,",
    "  abandonTracking,",
    "  trackingEnabled",
    '} from "@/lib/db/growth-tracking";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// A single tracked item + its milestone log, scoped to the signed-in user.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!trackingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const userId = user?.id ? String(user.id) : "";',
    "  const { id } = await params;",
    "  const item = await getTracked(userId, id);",
    '  if (!item) return NextResponse.json({ ok: false, message: "Not tracked yet." }, { status: 404 });',
    "  const milestones = await listMilestones(userId, id);",
    "  return NextResponse.json({ ok: true, item, milestones });",
    "}",
    "",
    "// The progress actions, ported from reading_plans.py complete-day / uncomplete-day",
    "// / pause / abandon. All scoped to user.id — a user can only move their own rows.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!trackingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const userId = user?.id ? String(user.id) : "";',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "complete";',
    '  const step = typeof body.step === "number" ? body.step : Number(body.step);',
    "",
    '  if (action === "pause") {',
    "    const ok = await pauseTracking(userId, id);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update progress." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  if (action === "abandon") {',
    "    const ok = await abandonTracking(userId, id);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update progress." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    "  if (!Number.isFinite(step) || step < 1) {",
    '    return NextResponse.json({ ok: false, message: "Which step?" }, { status: 400 });',
    "  }",
    '  if (action === "uncomplete") {',
    "    const progress = await uncompleteStep(userId, id, step);",
    '    if (!progress) return NextResponse.json({ ok: false, message: "Connect a database to update progress." }, { status: 503 });',
    "    return NextResponse.json({ ok: true, progress });",
    "  }",
    '  const note = typeof body.note === "string" ? body.note : "";',
    "  const progress = await completeStep(userId, id, step, note);",
    '  if (!progress) return NextResponse.json({ ok: false, message: "Connect a database to track progress." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, progress, finished: progress.currentStep > step && progress.completedSteps.length >= step });",
    "}"
  ]);
}

// ---- src/app/tracking/page.tsx (dashboard: streaks + what I track + catalog) -

function trackingPageFile(): GeneratedModuleFile {
  return file("src/app/tracking/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listTracked, listTrackables, summarize, trackingEnabled } from "@/lib/db/growth-tracking";',
    'import { StartForm } from "./start-form";',
    'import { NewTrackableForm } from "./new-trackable-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TrackingPage() {",
    "  if (!trackingEnabled()) {",
    '    return (<main className="shell"><h1>Progress</h1><p>Tracking is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/tracking");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const items = await listTracked(userId);",
    "  const summary = await summarize(userId);",
    "  const trackedIds = new Set(items.map((i) => i.trackable.id));",
    "  const catalog = (await listTrackables({ ownerId: userId, includeShared: true })).filter((t) => !trackedIds.has(t.id));",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Progress</p>',
    "      <h1>Your growth</h1>",
    "      <p>Track habits, goals, reading, skills, and milestones — and keep the streak going. Progress is yours alone.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Active</span><strong>{summary.activeCount}</strong></article>',
    '        <article className="card"><span>Current streak</span><strong>{summary.currentStreak} {summary.currentStreak === 1 ? "day" : "days"}</strong></article>',
    '        <article className="card"><span>Best streak</span><strong>{summary.bestStreak} {summary.bestStreak === 1 ? "day" : "days"}</strong></article>',
    '        <article className="card"><span>Steps done</span><strong>{summary.totalCompletions}</strong></article>',
    "      </section>",
    "      <h2>What you are tracking</h2>",
    "      {items.length === 0 ? (",
    '        <p className="note">Nothing yet. Start one from the list below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {items.map((item) => {",
    "            const t = item.trackable;",
    "            const pct = Math.min(100, Math.round((item.progress.completedSteps.length / t.targetSteps) * 100));",
    "            return (",
    '              <Link className="wide-card" key={t.id} href={`/tracking/${t.id}`}>',
    "                <span>{t.type}{item.progress.paused ? \" · paused\" : \"\"}</span>",
    "                <strong>{t.title}</strong>",
    "                <p>{item.progress.completedSteps.length} of {t.targetSteps} steps · {pct}%</p>",
    '                <p className="note">',
    "                  {item.finished",
    '                    ? "Finished — well done"',
    "                    : item.streakActive",
    "                      ? `🔥 ${item.progress.streak}-day streak`",
    "                      : (item.progress.streak > 0 ? \"Streak paused — pick it back up\" : \"No streak yet\")}",
    "                </p>",
    "              </Link>",
    "            );",
    "          })}",
    "        </section>",
    "      )}",
    "      <h2>Start tracking something</h2>",
    "      {catalog.length === 0 ? (",
    '        <p className="note">You are tracking everything available. Add a new goal below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {catalog.map((t) => (",
    '            <article className="wide-card" key={t.id}>',
    "              <span>{t.type}{t.isShared ? \" · shared\" : \"\"}</span>",
    "              <strong>{t.title}</strong>",
    "              {t.description ? <p>{t.description}</p> : null}",
    '              <p className="note">{t.targetSteps} steps · {t.category}</p>',
    "              <StartForm trackableId={t.id} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Add your own goal</h2>",
    "      <p>Name something you want to build or reach, set how many steps it takes, and start tracking it.</p>",
    "      <NewTrackableForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/tracking/start-form.tsx (client: start tracking) ---------------

function startFormFile(): GeneratedModuleFile {
  return file("src/app/tracking/start-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function StartForm({ trackableId }: { trackableId: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function start() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/tracking", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ trackableId })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not start tracking.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className="button primary" type="button" onClick={start} disabled={status === "working"}>',
    '        {status === "working" ? "Starting…" : "Start tracking"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/tracking/new-trackable-form.tsx (client: create a goal) --------

function newTrackableFormFile(): GeneratedModuleFile {
  return file("src/app/tracking/new-trackable-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function NewTrackableForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/tracking/trackables", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          description: form.get("description"),',
    '          type: form.get("type"),',
    '          category: form.get("category"),',
    '          targetSteps: Number(form.get("targetSteps")) || 30',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Added. Start tracking it from the list above.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Added</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Name your goal (e.g. Read a chapter a day)" aria-label="Goal title" required />',
    '      <input className="input" name="description" placeholder="Optional: a line about it" aria-label="Description" />',
    '      <select className="input" name="type" aria-label="Type" defaultValue="habit">',
    '        <option value="habit">Habit</option>',
    '        <option value="goal">Goal</option>',
    '        <option value="reading">Reading</option>',
    '        <option value="skill">Skill</option>',
    '        <option value="milestone">Milestone</option>',
    "      </select>",
    '      <input className="input" name="category" placeholder="Category (e.g. wellbeing)" aria-label="Category" />',
    '      <input className="input" name="targetSteps" type="number" min={1} max={3660} defaultValue={30} aria-label="Number of steps" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Adding…" : "Add goal"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/tracking/[id]/page.tsx (detail: progress + step grid + log) ----

function trackingDetailPageFile(): GeneratedModuleFile {
  return file("src/app/tracking/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getTracked, listMilestones, startTracking, getTrackable, trackingEnabled } from "@/lib/db/growth-tracking";',
    'import { ProgressControls } from "./progress-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TrackingDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!trackingEnabled()) {",
    '    return (<main className="shell"><h1>Progress</h1><p>Tracking is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/tracking");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const { id } = await params;",
    "  let item = await getTracked(userId, id);",
    "  // Not tracked yet? Auto-start it (ported from start_plan being idempotent).",
    "  if (!item) {",
    "    const trackable = await getTrackable(id);",
    "    if (!trackable) notFound();",
    "    await startTracking(userId, id);",
    "    item = await getTracked(userId, id);",
    "  }",
    "  if (!item) notFound();",
    "  const milestones = await listMilestones(userId, id);",
    "  const t = item.trackable;",
    "  const done = new Set(item.progress.completedSteps);",
    "  const pct = Math.min(100, Math.round((item.progress.completedSteps.length / t.targetSteps) * 100));",
    "  const steps = Array.from({ length: t.targetSteps }, (_, i) => i + 1);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{t.type}</p>',
    "      <h1>{t.title}</h1>",
    "      {t.description ? <p>{t.description}</p> : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Progress</span><strong>{pct}%</strong></article>',
    '        <article className="card"><span>Streak</span><strong>{item.streakActive ? item.progress.streak : 0} {(item.streakActive ? item.progress.streak : 0) === 1 ? "day" : "days"}</strong></article>',
    '        <article className="card"><span>Best</span><strong>{item.progress.longestStreak} days</strong></article>',
    '        <article className="card"><span>Done</span><strong>{item.progress.completedSteps.length} / {t.targetSteps}</strong></article>',
    "      </section>",
    "      {item.finished ? (",
    '        <p className="note" role="status">You have completed every step. Well done.</p>',
    "      ) : (",
    '        <p className="note">Next up: step {item.progress.currentStep}.</p>',
    "      )}",
    "      <h2>Steps</h2>",
    '      <ProgressControls trackableId={t.id} steps={steps} completed={Array.from(done)} nextStep={item.progress.currentStep} paused={item.progress.paused} />',
    "      {milestones.length > 0 ? (",
    "        <>",
    "          <h2>Milestone log</h2>",
    '          <section className="panel-list">',
    "            {milestones.map((m) => (",
    '              <article className="wide-card" key={m.id}>',
    "                <span>Step {m.step}</span>",
    "                {m.note ? <strong>{m.note}</strong> : <strong>Completed step {m.step}</strong>}",
    '                <p className="note">{m.completedAt ? new Date(m.completedAt).toLocaleString() : ""}</p>',
    "              </article>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    '      <p><Link className="button" href="/tracking">Back to progress</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/tracking/[id]/progress-controls.tsx (client: mark steps) -------

function progressControlsFile(): GeneratedModuleFile {
  return file("src/app/tracking/[id]/progress-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The step grid + pause/stop controls, ported from reading_plans.py's per-day",
    "// complete/uncomplete taps and the pause/abandon lifecycle. Tapping an incomplete",
    "// step completes it (and bumps the streak); tapping a completed one undoes it.",
    "export function ProgressControls({",
    "  trackableId,",
    "  steps,",
    "  completed,",
    "  nextStep,",
    "  paused",
    "}: {",
    "  trackableId: string;",
    "  steps: number[];",
    "  completed: number[];",
    "  nextStep: number;",
    "  paused: boolean;",
    "}) {",
    "  const router = useRouter();",
    "  const done = new Set(completed);",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function act(action: string, step?: number) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/tracking/${trackableId}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action, step })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update progress.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <div className="step-grid" role="group" aria-label="Steps">',
    "        {steps.map((step) => {",
    "          const isDone = done.has(step);",
    "          const isNext = step === nextStep && !isDone;",
    "          return (",
    "            <button",
    "              key={step}",
    "              type=\"button\"",
    "              className={isDone ? \"step done\" : isNext ? \"step next\" : \"step\"}",
    '              aria-pressed={isDone}',
    "              aria-label={isDone ? `Step ${step}, done — tap to undo` : `Step ${step} — tap to complete`}",
    '              onClick={() => act(isDone ? "uncomplete" : "complete", step)}',
    '              disabled={status === "working"}',
    "            >",
    "              {step}",
    "            </button>",
    "          );",
    "        })}",
    "      </div>",
    '      <div className="stack">',
    "        <button",
    '          className="button"',
    "          type=\"button\"",
    '          onClick={() => act("pause")}',
    '          disabled={status === "working" || paused}',
    "        >",
    '          {paused ? "Paused" : "Pause"}',
    "        </button>",
    "        <button",
    '          className="button"',
    "          type=\"button\"",
    '          onClick={() => act("abandon")}',
    '          disabled={status === "working"}',
    "        >",
    "          Stop tracking",
    "        </button>",
    "      </div>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const growthTrackingModule: AppModule = {
  slug: "growth-tracking",
  name: "Growth Tracking",
  tier: "optional",
  featureFlagEnv: "FEATURE_TRACKING",
  files: () => [
    trackingLibFile(),
    trackablesApiFile(),
    trackingApiFile(),
    trackingDetailApiFile(),
    trackingPageFile(),
    startFormFile(),
    newTrackableFormFile(),
    trackingDetailPageFile(),
    progressControlsFile()
  ],
  schemaSql: () =>
    [
      "",
      "-- growth-tracking: the per-user progress + streak layer. Every table is",
      "-- prefixed growth_tracking_ so it can never collide with another module.",
      "create table if not exists growth_tracking_trackables (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  type text not null default 'goal',",
      "  category text not null default 'general',",
      "  target_steps integer not null default 30,",
      "  is_shared boolean not null default false,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_tracking_trackables_owner_idx on growth_tracking_trackables (owner_id);",
      "create index if not exists growth_tracking_trackables_shared_idx on growth_tracking_trackables (is_shared);",
      "",
      "-- The per-user progress record, ported from reading_plan_progress. One row per",
      "-- (user, trackable) — the unique index mirrors the source's ux_user_plan.",
      "create table if not exists growth_tracking_progress (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  trackable_id uuid not null references growth_tracking_trackables(id) on delete cascade,",
      "  started_at timestamptz not null default now(),",
      "  current_step integer not null default 1,",
      "  completed_steps jsonb not null default '[]'::jsonb,",
      "  last_completed_at timestamptz,",
      "  streak integer not null default 0,",
      "  longest_streak integer not null default 0,",
      "  total_completions integer not null default 0,",
      "  paused boolean not null default false,",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists growth_tracking_progress_user_trackable_idx",
      "  on growth_tracking_progress (user_id, trackable_id);",
      "",
      "-- The milestone log, ported from the challenge completion history.",
      "create table if not exists growth_tracking_milestones (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  trackable_id uuid not null references growth_tracking_trackables(id) on delete cascade,",
      "  step integer not null,",
      "  note text not null default '',",
      "  completed_at timestamptz not null default now()",
      ");",
      "create index if not exists growth_tracking_milestones_user_trackable_idx",
      "  on growth_tracking_milestones (user_id, trackable_id);",
      "create index if not exists growth_tracking_milestones_completed_idx",
      "  on growth_tracking_milestones (completed_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- A couple of shared, owner-less trackables anyone can start (ported in spirit",
      "-- from the static reading-plan catalog).",
      "insert into growth_tracking_trackables (owner_id, title, description, type, category, target_steps, is_shared) values",
      "  (null, 'Daily 10-minute walk', 'A short walk every day to build a steady habit.', 'habit', 'wellbeing', 30, true),",
      "  (null, 'Read a chapter a day', 'Work through a book one chapter at a time and keep the streak.', 'reading', 'learning', 21, true)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Growth Tracking — set to false to switch the progress + streak tracker off.",
    "FEATURE_TRACKING=true"
  ],
  homeLinks: () => ['        <a className="button" href="/tracking">Progress</a>'],
  navLinks: () => [{ href: "/tracking", label: "Progress" }]
};
