// marketplace-orders — a real marketplace layer over a product catalog: browse +
// filter products, place an order through a checkout (with bulk-discount pricing),
// manage a roster of makers/vendors, and allocate paid orders to the best-matched
// maker. Ported from the LaserEngraving repo's actual marketplace code:
//   - the PRODUCT model (name, description, base_price, engraving_price, material,
//     category_id, sku, stock_quantity, active, bulk_discount_eligible, image_url,
//     max_engraving_width/height) — ported from src/lib/api.ts `Product` +
//     ProductCatalogEnhanced.tsx's search/category filtering.
//   - the CATEGORY model (name, slug, display_order, active) — ported from
//     src/lib/api.ts `Category`.
//   - bulk-discount pricing (BULK_PRICING_TIERS 100→7%, 500→12% + the
//     calculateBulkDiscount tier walk) — ported verbatim from src/lib/api.ts.
//   - the ORDER model (order_number, product_snapshot, quantity, unit_price,
//     subtotal, bulk_discount_percent/amount, total_amount, status pipeline
//     pending→paid→assigned→in_production→completed→shipped/cancelled,
//     fulfillment_type shipping|pickup, shipping_address, customer info,
//     maker_id + maker_earnings) — ported from src/lib/api.ts `Order` +
//     CheckoutForm.tsx's Orders.create flow.
//   - the MAKER (vendor) model (business_name, status active|probation|suspended,
//     average_rating, completed_orders, total_earnings, acceptance_rate,
//     average_completion_hours, platform_email, location) — ported from
//     MakerManagement.tsx's Maker type + the flagged/status filters + AddMaker
//     upsert.
//   - order allocation: the maker-matching SCORE (rating / completed_orders /
//     acceptance_rate + geographic proximity) and the 70% maker-earnings split —
//     ported verbatim from OrderAllocation.tsx's findBestMakers + allocate flow.
// This is the marketplace layer, distinct from the foundation product catalog:
// it adds ordering, checkout, and maker/vendor management on top. Runs on the
// app owner's own database with graceful sample-data fallback, feature-flagged
// (FEATURE_MARKETPLACE). Customers browse + order + track their own orders;
// admins manage makers, review orders, and allocate them.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/marketplace.ts (model + queries, ported from the real sources) -

function marketplaceLibFile(): GeneratedModuleFile {
  return file("src/lib/db/marketplace.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A product, ported from LaserEngraving src/lib/api.ts `Product`: a base price",
    "// plus an add-on price, a material, a category, stock, sku, and a",
    "// bulk-discount-eligible flag. Generalized off the laser-engraving framing so it",
    "// drops into any marketplace.",
    "export type Product = {",
    "  id: string;",
    "  name: string;",
    "  description: string;",
    "  basePrice: number;",
    "  addOnPrice: number;",
    "  imageUrl: string;",
    "  material: string;",
    "  categoryId: string | null;",
    "  sku: string;",
    "  stockQuantity: number;",
    "  active: boolean;",
    "  bulkDiscountEligible: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "// A category, ported from src/lib/api.ts `Category`.",
    "export type Category = {",
    "  id: string;",
    "  name: string;",
    "  slug: string;",
    "  description: string;",
    "  displayOrder: number;",
    "  active: boolean;",
    "};",
    "",
    "// A maker/vendor, ported from MakerManagement.tsx `Maker`: a business name, a",
    "// lifecycle status, and the performance metrics the roster + allocation read.",
    'export type MakerStatus = "active" | "probation" | "suspended" | "inactive";',
    "",
    "export type Maker = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  businessName: string;",
    "  platformEmail: string;",
    "  location: string;",
    "  bio: string;",
    "  status: MakerStatus;",
    "  acceptingOrders: boolean;",
    "  averageRating: number;",
    "  completedOrders: number;",
    "  totalEarnings: number;",
    "  acceptanceRate: number;",
    "  averageCompletionHours: number;",
    "  createdAt: string;",
    "};",
    "",
    "// An order, ported from src/lib/api.ts `Order` + CheckoutForm.tsx: a snapshot of",
    "// the product at purchase time, quantity, the bulk-discount breakdown, a total,",
    "// the fulfillment choice + shipping address, and the assigned maker + earnings.",
    'export type OrderStatus =',
    '  | "pending"',
    '  | "paid"',
    '  | "assigned"',
    '  | "in_production"',
    '  | "completed"',
    '  | "shipped"',
    '  | "cancelled";',
    "",
    'export type FulfillmentType = "shipping" | "pickup";',
    "",
    "export type ShippingAddress = {",
    "  name: string;",
    "  street: string;",
    "  city: string;",
    "  state: string;",
    "  zip: string;",
    "  country: string;",
    "};",
    "",
    "export type Order = {",
    "  id: string;",
    "  orderNumber: string;",
    "  customerId: string | null;",
    "  customerEmail: string;",
    "  customerName: string;",
    "  productId: string | null;",
    "  productName: string;",
    "  material: string;",
    "  quantity: number;",
    "  unitPrice: number;",
    "  subtotal: number;",
    "  bulkDiscountPercent: number;",
    "  bulkDiscountAmount: number;",
    "  totalAmount: number;",
    "  status: OrderStatus;",
    "  fulfillmentType: FulfillmentType;",
    "  shippingAddress: ShippingAddress | null;",
    "  notes: string;",
    "  makerId: string | null;",
    "  makerEarnings: number;",
    "  createdAt: string;",
    "};",
    "",
    "export type ProductFilters = { q?: string; categoryId?: string; activeOnly?: boolean; limit?: number };",
    "",
    "// Bulk-discount tiers, ported VERBATIM from src/lib/api.ts BULK_PRICING_TIERS:",
    "// 100+ units → 7% off, 500+ units → 12% off.",
    "export const BULK_PRICING_TIERS = [",
    "  { minQuantity: 100, discountPercent: 7 },",
    "  { minQuantity: 500, discountPercent: 12 }",
    "] as const;",
    "",
    "// The share of an order that goes to the maker, ported from OrderAllocation.tsx",
    "// (order.total_price * 0.70 = maker earnings; the platform keeps 30%).",
    "export const MAKER_EARNINGS_SHARE = 0.7;",
    "",
    "// calculateBulkDiscount, ported VERBATIM from src/lib/api.ts: below the first",
    "// tier there is no discount; otherwise walk to the highest tier the quantity",
    "// qualifies for and apply that percent to the subtotal.",
    "export function calculateBulkDiscount(",
    "  quantity: number,",
    "  unitPrice: number,",
    "  bulkDiscountEligible = true",
    "): { discountPercent: number; discountAmount: number; finalPrice: number } {",
    "  if (!bulkDiscountEligible || quantity < BULK_PRICING_TIERS[0].minQuantity) {",
    "    return { discountPercent: 0, discountAmount: 0, finalPrice: unitPrice * quantity };",
    "  }",
    "  let tier: { minQuantity: number; discountPercent: number } = BULK_PRICING_TIERS[0];",
    "  for (const t of BULK_PRICING_TIERS) if (quantity >= t.minQuantity) tier = t;",
    "  const subtotal = unitPrice * quantity;",
    "  const discountAmount = subtotal * (tier.discountPercent / 100);",
    "  return { discountPercent: tier.discountPercent, discountAmount, finalPrice: subtotal - discountAmount };",
    "}",
    "",
    "// A ranked maker match, ported from OrderAllocation.tsx `MakerMatch`.",
    "export type MakerMatch = {",
    "  makerId: string;",
    "  businessName: string;",
    "  matchScore: number;",
    "  rating: number;",
    "  completedOrders: number;",
    "  estimatedEarnings: number;",
    "  reasons: string[];",
    "};",
    "",
    "// Rank makers for an order, ported VERBATIM from OrderAllocation.tsx",
    "// findBestMakers: score by rating (>=4.5 → +30, >=4.0 → +20, else +10),",
    "// experience (>50 → +20, >20 → +15, >5 → +10), acceptance rate (>=90 → +15,",
    "// >=75 → +10), plus a flat +10 for geographic proximity; top 5, highest first.",
    "export function rankMakersForOrder(orderTotal: number, makers: Maker[]): MakerMatch[] {",
    "  const makerEarnings = orderTotal * MAKER_EARNINGS_SHARE;",
    "  const ranked: MakerMatch[] = makers.map((maker) => {",
    "    let score = 0;",
    "    const reasons: string[] = [];",
    "    if (maker.averageRating >= 4.5) { score += 30; reasons.push(\"Top-rated maker\"); }",
    "    else if (maker.averageRating >= 4.0) { score += 20; reasons.push(\"Highly rated\"); }",
    "    else score += 10;",
    "    if (maker.completedOrders > 50) { score += 20; reasons.push(\"Very experienced\"); }",
    "    else if (maker.completedOrders > 20) { score += 15; reasons.push(\"Experienced\"); }",
    "    else if (maker.completedOrders > 5) { score += 10; reasons.push(\"Growing portfolio\"); }",
    "    if (maker.acceptanceRate >= 90) { score += 15; reasons.push(\"Reliable acceptance rate\"); }",
    "    else if (maker.acceptanceRate >= 75) { score += 10; }",
    "    score += 10;",
    "    reasons.push(\"Geographic proximity\");",
    "    return {",
    "      makerId: maker.id,",
    "      businessName: maker.businessName,",
    "      matchScore: score,",
    "      rating: maker.averageRating,",
    "      completedOrders: maker.completedOrders,",
    "      estimatedEarnings: makerEarnings,",
    "      reasons",
    "    };",
    "  });",
    "  ranked.sort((a, b) => b.matchScore - a.matchScore);",
    "  return ranked.slice(0, 5);",
    "}",
    "",
    "export function makerStatusOptions(): MakerStatus[] {",
    '  return ["active", "probation", "suspended", "inactive"];',
    "}",
    "",
    "export function orderStatusOptions(): OrderStatus[] {",
    '  return ["pending", "paid", "assigned", "in_production", "completed", "shipped", "cancelled"];',
    "}",
    "",
    "// ---- Fallback sample data (used when no database is connected) -------------",
    "",
    "const fallbackCategories: Category[] = [",
    '  { id: "cat-signs", name: "Signs & Plaques", slug: "signs", description: "Custom signage", displayOrder: 1, active: true },',
    '  { id: "cat-gifts", name: "Personalized Gifts", slug: "gifts", description: "One-of-a-kind gifts", displayOrder: 2, active: true }',
    "];",
    "",
    "const fallbackProducts: Product[] = [",
    "  {",
    '    id: "prod-1",',
    '    name: "Engraved Oak Sign",',
    '    description: "A solid oak sign, personalized with your name or message.",',
    "    basePrice: 34.0,",
    "    addOnPrice: 6.0,",
    '    imageUrl: "",',
    '    material: "Oak",',
    '    categoryId: "cat-signs",',
    '    sku: "OAK-SIGN-01",',
    "    stockQuantity: 25,",
    "    active: true,",
    "    bulkDiscountEligible: true,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "prod-2",',
    '    name: "Slate Coaster Set",',
    '    description: "A set of natural slate coasters, engraved to order.",',
    "    basePrice: 22.0,",
    "    addOnPrice: 4.0,",
    '    imageUrl: "",',
    '    material: "Slate",',
    '    categoryId: "cat-gifts",',
    '    sku: "SLATE-COAST-04",',
    "    stockQuantity: 60,",
    "    active: true,",
    "    bulkDiscountEligible: true,",
    '    createdAt: "2025-01-02T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackMakers: Maker[] = [",
    "  {",
    '    id: "maker-1",',
    "    ownerId: null,",
    '    businessName: "Acme Laser Works",',
    '    platformEmail: "hello@acmelaser.example.com",',
    '    location: "Portland, OR",',
    '    bio: "Professional laser engraving.",',
    '    status: "active",',
    "    acceptingOrders: true,",
    "    averageRating: 4.8,",
    "    completedOrders: 214,",
    "    totalEarnings: 18240,",
    "    acceptanceRate: 96,",
    "    averageCompletionHours: 38.5,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "maker-2",',
    "    ownerId: null,",
    '    businessName: "Northside Makers",',
    '    platformEmail: "team@northside.example.com",',
    '    location: "Austin, TX",',
    '    bio: "Small-batch custom engraving.",',
    '    status: "probation",',
    "    acceptingOrders: true,",
    "    averageRating: 3.9,",
    "    completedOrders: 12,",
    "    totalEarnings: 640,",
    "    acceptanceRate: 72,",
    "    averageCompletionHours: 64.0,",
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackOrders: Order[] = [",
    "  {",
    '    id: "order-1",',
    '    orderNumber: "MP-100001",',
    "    customerId: null,",
    '    customerEmail: "jordan@example.com",',
    '    customerName: "Jordan P.",',
    '    productId: "prod-1",',
    '    productName: "Engraved Oak Sign",',
    '    material: "Oak",',
    "    quantity: 2,",
    "    unitPrice: 40.0,",
    "    subtotal: 80.0,",
    "    bulkDiscountPercent: 0,",
    "    bulkDiscountAmount: 0,",
    "    totalAmount: 80.0,",
    '    status: "paid",',
    '    fulfillmentType: "shipping",',
    '    shippingAddress: { name: "Jordan P.", street: "1 Main St", city: "Portland", state: "OR", zip: "97201", country: "US" },',
    '    notes: "",',
    "    makerId: null,",
    "    makerEarnings: 0,",
    '    createdAt: "2025-03-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "// ---- Row mappers ----------------------------------------------------------",
    "",
    "function rowToProduct(row: Record<string, unknown>): Product {",
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || ""),',
    '    description: String(row.description || ""),',
    "    basePrice: Number(row.base_price || 0),",
    "    addOnPrice: Number(row.add_on_price || 0),",
    '    imageUrl: String(row.image_url || ""),',
    '    material: String(row.material || ""),',
    "    categoryId: row.category_id != null ? String(row.category_id) : null,",
    '    sku: String(row.sku || ""),',
    "    stockQuantity: Number(row.stock_quantity || 0),",
    '    active: row.active === true || String(row.active) === "true",',
    '    bulkDiscountEligible: row.bulk_discount_eligible === true || String(row.bulk_discount_eligible) === "true",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToCategory(row: Record<string, unknown>): Category {",
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || ""),',
    '    slug: String(row.slug || ""),',
    '    description: String(row.description || ""),',
    "    displayOrder: Number(row.display_order || 0),",
    '    active: row.active === true || String(row.active) === "true"',
    "  };",
    "}",
    "",
    "function rowToMaker(row: Record<string, unknown>): Maker {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    businessName: String(row.business_name || ""),',
    '    platformEmail: String(row.platform_email || ""),',
    '    location: String(row.location || ""),',
    '    bio: String(row.bio || ""),',
    '    status: (String(row.status || "active") as MakerStatus),',
    '    acceptingOrders: row.accepting_orders === true || String(row.accepting_orders) === "true",',
    "    averageRating: Number(row.average_rating || 0),",
    "    completedOrders: Number(row.completed_orders || 0),",
    "    totalEarnings: Number(row.total_earnings || 0),",
    "    acceptanceRate: Number(row.acceptance_rate || 0),",
    "    averageCompletionHours: Number(row.average_completion_hours || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToOrder(row: Record<string, unknown>): Order {",
    "  const toAddress = (v: unknown): ShippingAddress | null => {",
    "    if (!v) return null;",
    '    let obj: Record<string, unknown> | null = null;',
    '    if (typeof v === "object") obj = v as Record<string, unknown>;',
    '    else if (typeof v === "string" && v.trim()) { try { obj = JSON.parse(v); } catch { obj = null; } }',
    "    if (!obj) return null;",
    "    return {",
    '      name: String(obj.name || ""),',
    '      street: String(obj.street || ""),',
    '      city: String(obj.city || ""),',
    '      state: String(obj.state || ""),',
    '      zip: String(obj.zip || ""),',
    '      country: String(obj.country || "US")',
    "    };",
    "  };",
    "  return {",
    "    id: String(row.id),",
    '    orderNumber: String(row.order_number || ""),',
    "    customerId: row.customer_id != null ? String(row.customer_id) : null,",
    '    customerEmail: String(row.customer_email || ""),',
    '    customerName: String(row.customer_name || ""),',
    "    productId: row.product_id != null ? String(row.product_id) : null,",
    '    productName: String(row.product_name || ""),',
    '    material: String(row.material || ""),',
    "    quantity: Number(row.quantity || 1),",
    "    unitPrice: Number(row.unit_price || 0),",
    "    subtotal: Number(row.subtotal || 0),",
    "    bulkDiscountPercent: Number(row.bulk_discount_percent || 0),",
    "    bulkDiscountAmount: Number(row.bulk_discount_amount || 0),",
    "    totalAmount: Number(row.total_amount || 0),",
    '    status: (String(row.status || "pending") as OrderStatus),',
    '    fulfillmentType: (String(row.fulfillment_type || "shipping") as FulfillmentType),',
    "    shippingAddress: toAddress(row.shipping_address),",
    '    notes: String(row.notes || ""),',
    "    makerId: row.maker_id != null ? String(row.maker_id) : null,",
    "    makerEarnings: Number(row.maker_earnings || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- Products (ported from ProductCatalogEnhanced.tsx search/filter) --------",
    "",
    "// List + filter products, ported from ProductCatalogEnhanced.tsx's filteredProducts",
    "// (match name/description/material) + category filter; newest first.",
    "export async function listProducts(filters: ProductFilters = {}): Promise<Product[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    "  const categoryId = filters.categoryId;",
    "  const activeOnly = filters.activeOnly !== false;",
    "  if (!hasDatabase()) {",
    "    return fallbackProducts",
    "      .filter((p) => !activeOnly || p.active)",
    "      .filter((p) => !categoryId || p.categoryId === categoryId)",
    '      .filter((p) => !q || (p.name + " " + p.description + " " + p.material).toLowerCase().includes(q))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const cat = categoryId || null;",
    "    const rows = await sql`",
    "      select id, name, description, base_price, add_on_price, image_url, material,",
    "        category_id, sku, stock_quantity, active, bulk_discount_eligible, created_at",
    "      from marketplace_orders_products",
    "      where (${activeOnly}::boolean is not true or active = true)",
    "        and (${cat}::uuid is null or category_id = ${cat})",
    "        and (${like}::text is null",
    "          or lower(name) like ${like}",
    "          or lower(description) like ${like}",
    "          or lower(material) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToProduct);",
    "  } catch {",
    "    return fallbackProducts.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getProduct(id: string): Promise<Product | null> {",
    "  if (!hasDatabase()) return fallbackProducts.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, name, description, base_price, add_on_price, image_url, material,",
    "        category_id, sku, stock_quantity, active, bulk_discount_eligible, created_at",
    "      from marketplace_orders_products where id = ${id} limit 1`;",
    "    return rows[0] ? rowToProduct(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateProductInput = {",
    "  name: string;",
    "  description?: string;",
    "  basePrice: number;",
    "  addOnPrice?: number;",
    "  imageUrl?: string;",
    "  material?: string;",
    "  categoryId?: string | null;",
    "  sku?: string;",
    "  stockQuantity?: number;",
    "  bulkDiscountEligible?: boolean;",
    "};",
    "",
    "// Create a product, ported from Catalog.createProduct.",
    "export async function createProduct(input: CreateProductInput): Promise<Product | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into marketplace_orders_products (",
    "        name, description, base_price, add_on_price, image_url, material,",
    "        category_id, sku, stock_quantity, active, bulk_discount_eligible",
    "      ) values (",
    '        ${input.name}, ${input.description || ""}, ${input.basePrice}, ${input.addOnPrice || 0},',
    '        ${input.imageUrl || ""}, ${input.material || ""}, ${input.categoryId || null},',
    '        ${input.sku || ""}, ${input.stockQuantity || 0}, true, ${input.bulkDiscountEligible !== false}',
    "      )",
    "      returning id, name, description, base_price, add_on_price, image_url, material,",
    "        category_id, sku, stock_quantity, active, bulk_discount_eligible, created_at`;",
    "    return rows[0] ? rowToProduct(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export async function listCategories(): Promise<Category[]> {",
    "  if (!hasDatabase()) return fallbackCategories.slice();",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, name, slug, description, display_order, active",
    "      from marketplace_orders_categories",
    "      where active = true",
    "      order by display_order asc, name asc`;",
    "    return rows.map(rowToCategory);",
    "  } catch {",
    "    return fallbackCategories.slice();",
    "  }",
    "}",
    "",
    "// ---- Makers / vendors (ported from MakerManagement.tsx) --------------------",
    "",
    "export type MakerFilters = { status?: string; flagged?: boolean; limit?: number };",
    "",
    "// List makers, ported from MakerManagement.tsx loadMakers: an 'all'/status filter",
    "// plus the 'flagged' (Needs Review) filter = rating < 4 OR acceptance_rate < 75.",
    "export async function listMakers(filters: MakerFilters = {}): Promise<Maker[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const status = (filters.status || "").trim();',
    "  if (!hasDatabase()) {",
    "    let rows = fallbackMakers.slice();",
    "    if (filters.flagged) rows = rows.filter((m) => m.averageRating < 4 || m.acceptanceRate < 75);",
    '    else if (status && status !== "all") rows = rows.filter((m) => m.status === status);',
    "    return rows.slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    if (filters.flagged) {",
    "      const rows = await sql`",
    "        select id, owner_id, business_name, platform_email, location, bio, status,",
    "          accepting_orders, average_rating, completed_orders, total_earnings,",
    "          acceptance_rate, average_completion_hours, created_at",
    "        from marketplace_orders_makers",
    "        where average_rating < 4 or acceptance_rate < 75",
    "        order by created_at desc limit ${limit}`;",
    "      return rows.map(rowToMaker);",
    "    }",
    '    const st = status && status !== "all" ? status : null;',
    "    const rows = await sql`",
    "      select id, owner_id, business_name, platform_email, location, bio, status,",
    "        accepting_orders, average_rating, completed_orders, total_earnings,",
    "        acceptance_rate, average_completion_hours, created_at",
    "      from marketplace_orders_makers",
    "      where (${st}::text is null or status = ${st})",
    "      order by created_at desc limit ${limit}`;",
    "    return rows.map(rowToMaker);",
    "  } catch {",
    "    return fallbackMakers.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getMaker(id: string): Promise<Maker | null> {",
    "  if (!hasDatabase()) return fallbackMakers.find((m) => m.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, business_name, platform_email, location, bio, status,",
    "        accepting_orders, average_rating, completed_orders, total_earnings,",
    "        acceptance_rate, average_completion_hours, created_at",
    "      from marketplace_orders_makers where id = ${id} limit 1`;",
    "    return rows[0] ? rowToMaker(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type UpsertMakerInput = {",
    "  ownerId?: string | null;",
    "  businessName: string;",
    "  platformEmail?: string;",
    "  location?: string;",
    "  bio?: string;",
    "  acceptingOrders?: boolean;",
    "};",
    "",
    "// Add a maker, ported from MakerManagement.tsx AddMakerModal → Makers.upsertProfile:",
    "// an admin creates a placeholder profile the maker can later claim. Starts active.",
    "export async function createMaker(input: UpsertMakerInput): Promise<Maker | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into marketplace_orders_makers (",
    "        owner_id, business_name, platform_email, location, bio, status,",
    "        accepting_orders, average_rating, completed_orders, total_earnings,",
    "        acceptance_rate, average_completion_hours",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.businessName}, ${input.platformEmail || ""},',
    '        ${input.location || ""}, ${input.bio || ""}, ${"active"},',
    "        ${input.acceptingOrders !== false}, 0, 0, 0, 100, 0",
    "      )",
    "      returning id, owner_id, business_name, platform_email, location, bio, status,",
    "        accepting_orders, average_rating, completed_orders, total_earnings,",
    "        acceptance_rate, average_completion_hours, created_at`;",
    "    return rows[0] ? rowToMaker(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Set a maker's status, ported from MakerManagement.tsx's Status Actions",
    "// (active / probation / suspended).",
    "export async function setMakerStatus(id: string, status: MakerStatus): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update marketplace_orders_makers set status = ${status} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Orders + checkout (ported from CheckoutForm.tsx Orders.create) --------",
    "",
    "export type OrderFilters = { status?: string; customerId?: string; makerId?: string; limit?: number };",
    "",
    "// List orders, ported from Orders.list(status). Scoped to a customer or maker",
    "// when given; newest first.",
    "export async function listOrders(filters: OrderFilters = {}): Promise<Order[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const status = (filters.status || "").trim();',
    "  const customerId = filters.customerId;",
    "  const makerId = filters.makerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackOrders",
    "      .filter((o) => !status || o.status === status)",
    "      .filter((o) => !customerId || o.customerId === customerId)",
    "      .filter((o) => !makerId || o.makerId === makerId)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const st = status || null;",
    "    const cust = customerId || null;",
    "    const mkr = makerId || null;",
    "    const rows = await sql`",
    "      select id, order_number, customer_id, customer_email, customer_name, product_id,",
    "        product_name, material, quantity, unit_price, subtotal, bulk_discount_percent,",
    "        bulk_discount_amount, total_amount, status, fulfillment_type, shipping_address,",
    "        notes, maker_id, maker_earnings, created_at",
    "      from marketplace_orders_orders",
    "      where (${st}::text is null or status = ${st})",
    "        and (${cust}::uuid is null or customer_id = ${cust})",
    "        and (${mkr}::uuid is null or maker_id = ${mkr})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToOrder);",
    "  } catch {",
    "    return fallbackOrders.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getOrder(id: string): Promise<Order | null> {",
    "  if (!hasDatabase()) return fallbackOrders.find((o) => o.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, order_number, customer_id, customer_email, customer_name, product_id,",
    "        product_name, material, quantity, unit_price, subtotal, bulk_discount_percent,",
    "        bulk_discount_amount, total_amount, status, fulfillment_type, shipping_address,",
    "        notes, maker_id, maker_earnings, created_at",
    "      from marketplace_orders_orders where id = ${id} limit 1`;",
    "    return rows[0] ? rowToOrder(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type PlaceOrderInput = {",
    "  productId: string;",
    "  customerId?: string | null;",
    "  customerEmail?: string;",
    "  customerName?: string;",
    "  quantity?: number;",
    "  fulfillmentType?: FulfillmentType;",
    "  shippingAddress?: ShippingAddress | null;",
    "  notes?: string;",
    "};",
    "",
    "function generateOrderNumber(): string {",
    "  const n = Math.floor(100000 + Math.random() * 900000);",
    "  return `MP-${n}`;",
    "}",
    "",
    "// Place an order, ported from CheckoutForm.tsx handleSubmit → Orders.create: price",
    "// the item (base + add-on), apply the bulk discount, snapshot the product name +",
    "// material, and store it 'pending' (payment happens next). This is the marketplace",
    "// ordering flow the foundation catalog does not have.",
    "export async function placeOrder(input: PlaceOrderInput): Promise<Order | null> {",
    "  if (!hasDatabase()) return null;",
    "  const product = await getProduct(input.productId);",
    "  if (!product) return null;",
    "  const quantity = Math.max(1, input.quantity || 1);",
    "  const unitPrice = product.basePrice + product.addOnPrice;",
    "  const bulk = calculateBulkDiscount(quantity, unitPrice, product.bulkDiscountEligible);",
    "  const subtotal = unitPrice * quantity;",
    "  const totalAmount = Math.max(0, bulk.finalPrice);",
    "  const orderNumber = generateOrderNumber();",
    '  const fulfillmentType: FulfillmentType = input.fulfillmentType === "pickup" ? "pickup" : "shipping";',
    '  const shippingAddress = fulfillmentType === "shipping" && input.shippingAddress ? JSON.stringify(input.shippingAddress) : null;',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into marketplace_orders_orders (",
    "        order_number, customer_id, customer_email, customer_name, product_id,",
    "        product_name, material, quantity, unit_price, subtotal, bulk_discount_percent,",
    "        bulk_discount_amount, total_amount, status, fulfillment_type, shipping_address,",
    "        notes, maker_earnings",
    "      ) values (",
    "        ${orderNumber}, ${input.customerId || null}, ${input.customerEmail || \"\"},",
    "        ${input.customerName || \"\"}, ${product.id}, ${product.name}, ${product.material},",
    "        ${quantity}, ${unitPrice}, ${subtotal}, ${bulk.discountPercent},",
    "        ${bulk.discountAmount}, ${totalAmount}, ${\"pending\"}, ${fulfillmentType},",
    "        ${shippingAddress}, ${input.notes || \"\"}, 0",
    "      )",
    "      returning id, order_number, customer_id, customer_email, customer_name, product_id,",
    "        product_name, material, quantity, unit_price, subtotal, bulk_discount_percent,",
    "        bulk_discount_amount, total_amount, status, fulfillment_type, shipping_address,",
    "        notes, maker_id, maker_earnings, created_at`;",
    "    return rows[0] ? rowToOrder(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Advance an order's status, ported from Orders.updateStatus.",
    "export async function setOrderStatus(id: string, status: OrderStatus): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update marketplace_orders_orders set status = ${status} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Order allocation (ported from OrderAllocation.tsx) --------------------",
    "",
    "// The unassigned queue, ported from OrderAllocation.tsx loadUnassignedOrders:",
    "// paid orders with no maker yet, waiting to be matched + assigned.",
    "export async function listUnassignedOrders(limit = 50): Promise<Order[]> {",
    "  const orders = await listOrders({ status: \"paid\", limit });",
    "  return orders.filter((o) => !o.makerId);",
    "}",
    "",
    "// Suggest the best makers for an order, ported from OrderAllocation.tsx",
    "// findBestMakers: rank the active, order-accepting makers by the match score.",
    "export async function suggestMakersForOrder(order: Order): Promise<MakerMatch[]> {",
    "  const makers = (await listMakers({ status: \"active\", limit: 200 })).filter((m) => m.acceptingOrders);",
    "  return rankMakersForOrder(order.totalAmount, makers);",
    "}",
    "",
    "// Allocate an order to a maker, ported from OrderAllocation.tsx",
    "// allocateOrderToMaker + OrdersApi.assignMaker: stamp the maker, set the 70%",
    "// earnings, and move the order to 'assigned'.",
    "export async function allocateOrder(orderId: string, makerId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const order = await getOrder(orderId);",
    "  if (!order) return false;",
    "  const makerEarnings = order.totalAmount * MAKER_EARNINGS_SHARE;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      update marketplace_orders_orders",
    "      set maker_id = ${makerId}, maker_earnings = ${makerEarnings}, status = ${\"assigned\"}",
    "      where id = ${orderId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function marketplaceEnabled(): boolean {",
    '  return process.env.FEATURE_MARKETPLACE !== "false";',
    "}"
  ]);
}

// ---- src/app/api/marketplace/products/route.ts (list + create product) ------

function productsApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/products/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listProducts, createProduct, marketplaceEnabled } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false, message: "The marketplace is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const products = await listProducts({",
    '    q: url.searchParams.get("q") || undefined,',
    '    categoryId: url.searchParams.get("category") || undefined,',
    "    activeOnly: true",
    "  });",
    "  return NextResponse.json({ ok: true, products });",
    "}",
    "",
    "// Admins add products to the catalog, ported from Catalog.createProduct.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    "  const basePrice = Number(body.basePrice);",
    "  if (name.length < 2 || !Number.isFinite(basePrice) || basePrice < 0) {",
    '    return NextResponse.json({ ok: false, message: "A product name and a valid base price are required." }, { status: 400 });',
    "  }",
    "  const created = await createProduct({",
    "    name,",
    "    basePrice,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    "    addOnPrice: Number.isFinite(Number(body.addOnPrice)) ? Number(body.addOnPrice) : undefined,",
    '    imageUrl: typeof body.imageUrl === "string" ? body.imageUrl : undefined,',
    '    material: typeof body.material === "string" ? body.material : undefined,',
    '    categoryId: typeof body.categoryId === "string" ? body.categoryId : null,',
    '    sku: typeof body.sku === "string" ? body.sku : undefined,',
    "    stockQuantity: Number.isFinite(Number(body.stockQuantity)) ? Number(body.stockQuantity) : undefined,",
    "    bulkDiscountEligible: body.bulkDiscountEligible !== false",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to add products." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, product: created });",
    "}"
  ]);
}

// ---- src/app/api/marketplace/orders/route.ts (list + place order) -----------

function ordersApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/orders/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listOrders, placeOrder, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import type { FulfillmentType, ShippingAddress } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false, message: "The marketplace is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  // Customers see only their own orders; admins see every order.",
    "  const customerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const orders = await listOrders({",
    '    status: url.searchParams.get("status") || undefined,',
    "    customerId",
    "  });",
    "  return NextResponse.json({ ok: true, orders });",
    "}",
    "",
    "// Place an order, ported from CheckoutForm.tsx Orders.create. Scoped to the",
    "// signed-in customer via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to place an order." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const productId = typeof body.productId === "string" ? body.productId.trim() : "";',
    "  if (!productId) {",
    '    return NextResponse.json({ ok: false, message: "Choose a product to order." }, { status: 400 });',
    "  }",
    '  const fulfillmentType: FulfillmentType = body.fulfillmentType === "pickup" ? "pickup" : "shipping";',
    "  let shippingAddress: ShippingAddress | null = null;",
    '  if (fulfillmentType === "shipping" && body.shippingAddress && typeof body.shippingAddress === "object") {',
    "    const a = body.shippingAddress as Record<string, unknown>;",
    "    shippingAddress = {",
    '      name: String(a.name || body.customerName || ""),',
    '      street: String(a.street || ""),',
    '      city: String(a.city || ""),',
    '      state: String(a.state || ""),',
    '      zip: String(a.zip || ""),',
    '      country: String(a.country || "US")',
    "    };",
    "  }",
    "  const created = await placeOrder({",
    "    productId,",
    "    customerId: user?.id ? String(user.id) : null,",
    '    customerEmail: user?.email ? String(user.email) : (typeof body.customerEmail === "string" ? body.customerEmail : undefined),',
    '    customerName: typeof body.customerName === "string" ? body.customerName : (user?.name || ""),',
    "    quantity: Number.isFinite(Number(body.quantity)) ? Number(body.quantity) : 1,",
    "    fulfillmentType,",
    "    shippingAddress,",
    '    notes: typeof body.notes === "string" ? body.notes : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database (and pick a real product) to place orders." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, order: created, message: "Your order is placed and awaiting payment." });',
    "}"
  ]);
}

// ---- src/app/api/marketplace/orders/[id]/route.ts (detail + status/allocate) -

function orderDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/orders/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getOrder, setOrderStatus, allocateOrder, orderStatusOptions, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import type { OrderStatus } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const order = await getOrder(id);",
    '  if (!order) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Customers may only read their own orders.",
    "  if (!canAccessAdmin(user?.role) && order.customerId && order.customerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, order });",
    "}",
    "",
    "// Admin actions: advance the order status, or allocate it to a maker (ported",
    "// from Orders.updateStatus + OrderAllocation.tsx's assign flow).",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const makerId = typeof body.makerId === "string" ? body.makerId.trim() : "";',
    "  if (makerId) {",
    "    const ok = await allocateOrder(id, makerId);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to allocate orders." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  const status = typeof body.status === "string" ? body.status : "";',
    "  if (!orderStatusOptions().includes(status as OrderStatus)) {",
    '    return NextResponse.json({ ok: false, message: "Unknown order status." }, { status: 400 });',
    "  }",
    "  const ok = await setOrderStatus(id, status as OrderStatus);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update orders." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/marketplace/orders/[id]/matches/route.ts (maker suggestions) -

function orderMatchesApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/orders/[id]/matches/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getOrder, suggestMakersForOrder, marketplaceEnabled } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// The best-maker suggestions for an order, ported from OrderAllocation.tsx",
    "// findBestMakers. Admin-only — this is the operator allocation surface.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const order = await getOrder(id);",
    '  if (!order) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const matches = await suggestMakersForOrder(order);",
    "  return NextResponse.json({ ok: true, matches });",
    "}"
  ]);
}

// ---- src/app/api/marketplace/makers/route.ts (list + add maker) -------------

function makersApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/makers/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listMakers, createMaker, marketplaceEnabled } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false, message: "The marketplace is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const flagged = url.searchParams.get("filter") === "flagged";',
    "  const makers = await listMakers({",
    '    status: url.searchParams.get("status") || undefined,',
    "    flagged",
    "  });",
    "  return NextResponse.json({ ok: true, makers });",
    "}",
    "",
    "// Add a maker, ported from MakerManagement.tsx AddMakerModal. Admins only.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const businessName = typeof body.businessName === "string" ? body.businessName.trim() : "";',
    '  const platformEmail = typeof body.platformEmail === "string" ? body.platformEmail.trim().toLowerCase() : "";',
    "  if (businessName.length < 2 || !platformEmail) {",
    '    return NextResponse.json({ ok: false, message: "A business name and an email are required." }, { status: 400 });',
    "  }",
    "  const created = await createMaker({",
    "    businessName,",
    "    platformEmail,",
    '    location: typeof body.location === "string" ? body.location : undefined,',
    '    bio: typeof body.bio === "string" ? body.bio : `Professional work by ${businessName}`,',
    "    acceptingOrders: body.acceptingOrders !== false",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to add makers." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, maker: created });",
    "}"
  ]);
}

// ---- src/app/api/marketplace/makers/[id]/route.ts (detail + status) ---------

function makerDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/marketplace/makers/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getMaker, setMakerStatus, makerStatusOptions, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import type { MakerStatus } from "@/lib/db/marketplace";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!marketplaceEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const maker = await getMaker(id);",
    '  if (!maker) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, maker });",
    "}",
    "",
    "// Set a maker's status (active/probation/suspended/inactive) — admins only,",
    "// ported from MakerManagement.tsx's Status Actions.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = typeof body.status === "string" ? body.status : "";',
    "  if (!makerStatusOptions().includes(status as MakerStatus)) {",
    '    return NextResponse.json({ ok: false, message: "Unknown maker status." }, { status: 400 });',
    "  }",
    "  const ok = await setMakerStatus(id, status as MakerStatus);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update makers." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/marketplace/page.tsx (product catalog + order form) ------------

function marketplacePageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listProducts, listCategories, marketplaceEnabled } from "@/lib/db/marketplace";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MarketplacePage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; category?: string }>;",
    "}) {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Marketplace</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const category = (params?.category || "").trim();',
    "  const [products, categories] = await Promise.all([",
    "    listProducts({ q: q || undefined, categoryId: category || undefined, activeOnly: true }),",
    "    listCategories()",
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Marketplace</p>',
    "      <h1>Shop</h1>",
    "      <p>Browse the catalog, personalize what you like, and place an order. Local makers bring it to life.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search products" aria-label="Search products" />',
    "        {categories.length > 0 ? (",
    '          <select className="input" name="category" defaultValue={category} aria-label="Category">',
    '            <option value="">All categories</option>',
    "            {categories.map((c) => (",
    "              <option key={c.id} value={c.id}>{c.name}</option>",
    "            ))}",
    "          </select>",
    "        ) : null}",
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {products.length === 0 ? (",
    '        <p className="note">{q ? `No products match "${q}" yet.` : "No products in the catalog yet."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {products.map((p) => (",
    '            <Link className="wide-card" key={p.id} href={`/marketplace/${p.id}`}>',
    "              <span>{p.material || \"Product\"}</span>",
    "              <strong>{p.name}</strong>",
    "              {p.description ? <p>{p.description}</p> : null}",
    '              <p className="note">${(p.basePrice + p.addOnPrice).toFixed(2)}{p.stockQuantity > 0 ? ` · ${p.stockQuantity} in stock` : " · Made to order"}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p className="stack">',
    '        <Link className="button" href="/marketplace/orders">My orders</Link>',
    "        {isAdmin ? <Link className=\"button\" href=\"/marketplace/makers\">Makers</Link> : null}",
    "        {isAdmin ? <Link className=\"button\" href=\"/marketplace/allocate\">Allocate orders</Link> : null}",
    "      </p>",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/[id]/page.tsx (product detail + checkout) ----------

function productDetailPageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getProduct, BULK_PRICING_TIERS, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import { CheckoutForm } from "./checkout-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ProductDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Marketplace</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace");',
    "  const { id } = await params;",
    "  const product = await getProduct(id);",
    "  if (!product) notFound();",
    "  const unitPrice = product.basePrice + product.addOnPrice;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{product.material || "Product"}</p>',
    "      <h1>{product.name}</h1>",
    "      {product.description ? <p>{product.description}</p> : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Price</span><strong>${unitPrice.toFixed(2)}</strong></article>',
    '        <article className="card"><span>Stock</span><strong>{product.stockQuantity > 0 ? product.stockQuantity : "Made to order"}</strong></article>',
    "        {product.sku ? <article className=\"card\"><span>SKU</span><strong>{product.sku}</strong></article> : null}",
    "      </section>",
    "      {product.bulkDiscountEligible ? (",
    '        <p className="note">Bulk discounts: {BULK_PRICING_TIERS.map((t) => `${t.minQuantity}+ → ${t.discountPercent}% off`).join(" · ")}</p>',
    "      ) : null}",
    "      <h2>Order this</h2>",
    "      <CheckoutForm productId={product.id} unitPrice={unitPrice} bulkEligible={product.bulkDiscountEligible} />",
    '      <p><Link className="button" href="/marketplace">Back to shop</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/[id]/checkout-form.tsx (client checkout) -----------

function checkoutFormFile(): GeneratedModuleFile {
  return file("src/app/marketplace/[id]/checkout-form.tsx", [
    '"use client";',
    "",
    'import { useMemo, useState } from "react";',
    'import { useRouter } from "next/navigation";',
    'import { calculateBulkDiscount } from "@/lib/db/marketplace";',
    "",
    "// The checkout, ported from CheckoutForm.tsx: quantity + fulfillment choice +",
    "// shipping address, with the live bulk-discount total computed the same way.",
    "export function CheckoutForm({ productId, unitPrice, bulkEligible }: { productId: string; unitPrice: number; bulkEligible: boolean }) {",
    "  const router = useRouter();",
    "  const [quantity, setQuantity] = useState(1);",
    '  const [fulfillmentType, setFulfillmentType] = useState<"shipping" | "pickup">("shipping");',
    '  const [address, setAddress] = useState({ name: "", street: "", city: "", state: "", zip: "", country: "US" });',
    '  const [notes, setNotes] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  const pricing = useMemo(() => calculateBulkDiscount(quantity, unitPrice, bulkEligible), [quantity, unitPrice, bulkEligible]);",
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/marketplace/orders", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          productId,",
    "          quantity,",
    "          fulfillmentType,",
    '          shippingAddress: fulfillmentType === "shipping" ? address : undefined,',
    "          customerName: address.name || undefined,",
    "          notes",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Your order is placed.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Order placed</p>',
    "        <p>{message}</p>",
    '        <p><a className="button" href="/marketplace/orders">View my orders</a></p>',
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <label className="stack">',
    "        <span>Quantity</span>",
    '        <input className="input" type="number" min={1} value={quantity} onChange={(e) => setQuantity(Math.max(1, parseInt(e.target.value) || 1))} aria-label="Quantity" />',
    "      </label>",
    '      <fieldset className="stack">',
    "        <legend>Fulfillment</legend>",
    '        <label className="check"><input type="radio" name="fulfillment" checked={fulfillmentType === "shipping"} onChange={() => setFulfillmentType("shipping")} /> Ship to me</label>',
    '        <label className="check"><input type="radio" name="fulfillment" checked={fulfillmentType === "pickup"} onChange={() => setFulfillmentType("pickup")} /> Local pickup</label>',
    "      </fieldset>",
    '      {fulfillmentType === "shipping" ? (',
    '        <div className="stack">',
    '          <input className="input" value={address.name} onChange={(e) => setAddress({ ...address, name: e.target.value })} placeholder="Full name" aria-label="Full name" required />',
    '          <input className="input" value={address.street} onChange={(e) => setAddress({ ...address, street: e.target.value })} placeholder="Street" aria-label="Street" required />',
    '          <input className="input" value={address.city} onChange={(e) => setAddress({ ...address, city: e.target.value })} placeholder="City" aria-label="City" required />',
    '          <input className="input" value={address.state} onChange={(e) => setAddress({ ...address, state: e.target.value })} placeholder="State" aria-label="State" required />',
    '          <input className="input" value={address.zip} onChange={(e) => setAddress({ ...address, zip: e.target.value })} placeholder="Zip" aria-label="Zip" required />',
    "        </div>",
    "      ) : null}",
    '      <textarea className="input" value={notes} onChange={(e) => setNotes(e.target.value)} rows={2} placeholder="Notes (optional)" aria-label="Notes" />',
    '      <div className="panel">',
    "        <p>{quantity} × ${unitPrice.toFixed(2)} = ${(unitPrice * quantity).toFixed(2)}</p>",
    "        {pricing.discountPercent > 0 ? (",
    '          <p className="note">Bulk discount ({pricing.discountPercent}%): −${pricing.discountAmount.toFixed(2)}</p>',
    "        ) : null}",
    "        <p><strong>Total: ${pricing.finalPrice.toFixed(2)}</strong></p>",
    "      </div>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Placing order…" : `Place order — $${pricing.finalPrice.toFixed(2)}`}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/orders/page.tsx (customer/admin order list) --------

function ordersPageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/orders/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listOrders, marketplaceEnabled } from "@/lib/db/marketplace";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OrdersPage() {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Orders</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace/orders");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const orders = await listOrders({ customerId: isAdmin ? undefined : (user?.id ? String(user.id) : undefined) });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Orders</p>',
    "      <h1>{isAdmin ? \"All orders\" : \"My orders\"}</h1>",
    "      {orders.length === 0 ? (",
    '        <p className="note">No orders yet. Browse the shop to place your first one.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {orders.map((o) => (",
    '            <Link className="wide-card" key={o.id} href={`/marketplace/orders/${o.id}`}>',
    "              <span>{o.status}</span>",
    "              <strong>{o.orderNumber} · {o.productName}</strong>",
    '              <p className="note">Qty {o.quantity} · ${o.totalAmount.toFixed(2)}{o.makerId ? " · assigned" : ""}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/marketplace">Back to shop</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/orders/[id]/page.tsx (order detail + admin status) --

function orderDetailPageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/orders/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getOrder, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import { OrderStatusControls } from "./order-status-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Order</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace/orders");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const order = await getOrder(id);",
    "  if (!order) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && order.customerId && order.customerId !== String(user?.id)) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{order.status}</p>',
    "      <h1>{order.orderNumber}</h1>",
    "      <p>{order.productName}{order.material ? ` · ${order.material}` : \"\"}</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Quantity</span><strong>{order.quantity}</strong></article>',
    '        <article className="card"><span>Unit price</span><strong>${order.unitPrice.toFixed(2)}</strong></article>',
    '        <article className="card"><span>Subtotal</span><strong>${order.subtotal.toFixed(2)}</strong></article>',
    '        <article className="card"><span>Total</span><strong>${order.totalAmount.toFixed(2)}</strong></article>',
    "      </section>",
    "      {order.bulkDiscountPercent > 0 ? (",
    '        <p className="note">Bulk discount ({order.bulkDiscountPercent}%): −${order.bulkDiscountAmount.toFixed(2)}</p>',
    "      ) : null}",
    "      {order.shippingAddress ? (",
    "        <p className=\"note\">Ship to: {[order.shippingAddress.name, order.shippingAddress.street, order.shippingAddress.city, order.shippingAddress.state, order.shippingAddress.zip].filter(Boolean).join(\", \")}</p>",
    "      ) : (",
    '        <p className="note">Local pickup</p>',
    "      )}",
    "      {order.notes ? <p>{order.notes}</p> : null}",
    "      {order.makerId ? (",
    '        <p className="note">Assigned to a maker · maker earns ${order.makerEarnings.toFixed(2)}</p>',
    "      ) : null}",
    "      {isAdmin ? <OrderStatusControls id={order.id} current={order.status} /> : null}",
    "      {isAdmin && !order.makerId ? (",
    '        <p><Link className="button" href="/marketplace/allocate">Allocate to a maker</Link></p>',
    "      ) : null}",
    '      <p><Link className="button" href="/marketplace/orders">Back to orders</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/orders/[id]/order-status-controls.tsx (client) -----

function orderStatusControlsFile(): GeneratedModuleFile {
  return file("src/app/marketplace/orders/[id]/order-status-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Order status pipeline, ported from src/lib/api.ts Order.status.",
    'const STATUSES = ["pending", "paid", "assigned", "in_production", "completed", "shipped", "cancelled"] as const;',
    "",
    "export function OrderStatusControls({ id, current }: { id: string; current: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function apply(next: string) {",
    "    if (next === current) return;",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/marketplace/orders/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ status: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update the order.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '        setStatus("error");',
    '        setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <p className="eyebrow">Set status</p>',
    '      <div className="stack">',
    "        {STATUSES.map((s) => (",
    '          <button key={s} type="button" className={s === current ? "button primary" : "button"} onClick={() => apply(s)} disabled={status === "working"}>{s.replace("_", " ")}</button>',
    "        ))}",
    "      </div>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/makers/page.tsx (admin maker roster) ---------------

function makersPageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/makers/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listMakers, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import { AddMakerForm } from "./add-maker-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MakersPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ filter?: string }>;",
    "}) {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Makers</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace/makers");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Makers</h1><p className="note">The maker roster is for admins only.</p></main>);',
    "  }",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const flagged = (params?.filter || "") === "flagged";',
    "  const makers = await listMakers({ flagged });",
    "  const totalEarnings = makers.reduce((s, m) => s + m.totalEarnings, 0);",
    "  const totalOrders = makers.reduce((s, m) => s + m.completedOrders, 0);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Maker management</h1>",
    "      <p>Add makers, track performance, and manage quality. Flagged makers have a rating under 4 or an acceptance rate under 75%.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Makers</span><strong>{makers.length}</strong></article>',
    '        <article className="card"><span>Completed orders</span><strong>{totalOrders}</strong></article>',
    '        <article className="card"><span>Total payouts</span><strong>${totalEarnings.toLocaleString()}</strong></article>',
    "      </section>",
    '      <p className="stack">',
    '        <Link className="button" href="/marketplace/makers">All makers</Link>',
    '        <Link className="button" href="/marketplace/makers?filter=flagged">Needs review</Link>',
    "      </p>",
    "      {makers.length === 0 ? (",
    '        <p className="note">{flagged ? "No makers need review right now." : "No makers yet. Add your first one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {makers.map((m) => (",
    '            <Link className="wide-card" key={m.id} href={`/marketplace/makers/${m.id}`}>',
    "              <span>{m.status}</span>",
    "              <strong>{m.businessName}</strong>",
    '              <p className="note">{m.platformEmail}{m.location ? ` · ${m.location}` : ""}</p>',
    '              <p className="note">{m.completedOrders > 0 ? `${m.averageRating.toFixed(1)}★` : "No ratings"} · {m.completedOrders} orders · {m.acceptanceRate.toFixed(0)}% accept · ${m.totalEarnings.toFixed(0)}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Add a maker</h2>",
    "      <AddMakerForm />",
    '      <p><Link className="button" href="/marketplace">Back to shop</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/makers/add-maker-form.tsx (client) -----------------

function addMakerFormFile(): GeneratedModuleFile {
  return file("src/app/marketplace/makers/add-maker-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Add-maker form, ported from MakerManagement.tsx AddMakerModal: business name +",
    "// email (required) and an optional location; the maker can later claim the profile.",
    "export function AddMakerForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/marketplace/makers", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          businessName: form.get("businessName"),',
    '          platformEmail: form.get("platformEmail"),',
    '          location: form.get("location")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not add the maker.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Maker added.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Added</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="businessName" placeholder="Business name" aria-label="Business name" required />',
    '      <input className="input" name="platformEmail" type="email" placeholder="Email address" aria-label="Email address" required />',
    '      <input className="input" name="location" placeholder="Location (city, state)" aria-label="Location" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Adding…" : "Add maker"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/makers/[id]/page.tsx (maker detail + status) -------

function makerDetailPageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/makers/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getMaker, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import { MakerStatusControls } from "./maker-status-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MakerDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Maker</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace/makers");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Maker</h1><p className="note">Maker profiles are for admins only.</p></main>);',
    "  }",
    "  const { id } = await params;",
    "  const maker = await getMaker(id);",
    "  if (!maker) notFound();",
    "  const hasRatings = maker.completedOrders > 0;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{maker.status}</p>',
    "      <h1>{maker.businessName}</h1>",
    "      {maker.bio ? <p>{maker.bio}</p> : null}",
    "      {maker.platformEmail ? (",
    '        <p><a className="link" href={`mailto:${maker.platformEmail}`}>{maker.platformEmail}</a>{maker.location ? ` · ${maker.location}` : ""}</p>',
    "      ) : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Rating</span><strong>{hasRatings ? `${maker.averageRating.toFixed(1)}/5.0` : "No ratings"}</strong></article>',
    '        <article className="card"><span>Orders</span><strong>{maker.completedOrders}</strong></article>',
    '        <article className="card"><span>Acceptance</span><strong>{maker.acceptanceRate.toFixed(0)}%</strong></article>',
    '        <article className="card"><span>Earnings</span><strong>${maker.totalEarnings.toFixed(0)}</strong></article>',
    '        <article className="card"><span>Avg time</span><strong>{maker.averageCompletionHours > 0 ? `${maker.averageCompletionHours.toFixed(1)}h` : "N/A"}</strong></article>',
    '        <article className="card"><span>Accepting</span><strong>{maker.acceptingOrders ? "Yes" : "No"}</strong></article>',
    "      </section>",
    "      {!hasRatings ? (",
    '        <p className="note" role="status">New maker: no completed orders or ratings yet.</p>',
    "      ) : null}",
    "      <MakerStatusControls id={maker.id} current={maker.status} />",
    '      <p><Link className="button" href="/marketplace/makers">Back to makers</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/makers/[id]/maker-status-controls.tsx (client) -----

function makerStatusControlsFile(): GeneratedModuleFile {
  return file("src/app/marketplace/makers/[id]/maker-status-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Maker status actions, ported from MakerManagement.tsx OverviewTab Status Actions.",
    'const STATUSES = ["active", "probation", "suspended", "inactive"] as const;',
    "",
    "export function MakerStatusControls({ id, current }: { id: string; current: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function apply(next: string) {",
    "    if (next === current) return;",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/marketplace/makers/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ status: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update the maker.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <p className="eyebrow">Set status</p>',
    '      <div className="stack">',
    "        {STATUSES.map((s) => (",
    '          <button key={s} type="button" className={s === current ? "button primary" : "button"} onClick={() => apply(s)} disabled={status === "working"}>{s}</button>',
    "        ))}",
    "      </div>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/allocate/page.tsx (admin order allocation) ---------

function allocatePageFile(): GeneratedModuleFile {
  return file("src/app/marketplace/allocate/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listUnassignedOrders, marketplaceEnabled } from "@/lib/db/marketplace";',
    'import { AllocatePanel } from "./allocate-panel";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AllocatePage() {",
    "  if (!marketplaceEnabled()) {",
    '    return (<main className="shell"><h1>Allocate</h1><p>The marketplace is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/marketplace/allocate");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Allocate</h1><p className="note">Order allocation is for admins only.</p></main>);',
    "  }",
    "  const orders = await listUnassignedOrders();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Order allocation</h1>",
    "      <p>Smart matching finds the best maker for each paid order based on rating, experience, acceptance rate, and proximity.</p>",
    "      {orders.length === 0 ? (",
    '        <p className="note">All paid orders have been assigned. The queue is clear.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {orders.map((o) => (",
    "            <AllocatePanel key={o.id} order={{ id: o.id, orderNumber: o.orderNumber, productName: o.productName, material: o.material, quantity: o.quantity, totalAmount: o.totalAmount }} />",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/marketplace">Back to shop</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/marketplace/allocate/allocate-panel.tsx (client) ---------------

function allocatePanelFile(): GeneratedModuleFile {
  return file("src/app/marketplace/allocate/allocate-panel.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The allocation panel, ported from OrderAllocation.tsx: pick an order, fetch the",
    "// ranked maker matches, and assign (top match or a specific maker).",
    "type OrderLite = { id: string; orderNumber: string; productName: string; material: string; quantity: number; totalAmount: number };",
    "type MakerMatch = { makerId: string; businessName: string; matchScore: number; rating: number; completedOrders: number; estimatedEarnings: number; reasons: string[] };",
    "",
    "export function AllocatePanel({ order }: { order: OrderLite }) {",
    "  const router = useRouter();",
    "  const [matches, setMatches] = useState<MakerMatch[]>([]);",
    "  const [loading, setLoading] = useState(false);",
    "  const [allocating, setAllocating] = useState(false);",
    '  const [message, setMessage] = useState("");',
    "  const [open, setOpen] = useState(false);",
    "",
    "  async function findMakers() {",
    "    setOpen(true);",
    "    setLoading(true);",
    '    setMessage("");',
    "    setMatches([]);",
    "    try {",
    "      const response = await fetch(`/api/marketplace/orders/${order.id}/matches`);",
    "      const data = await response.json();",
    "      if (data.ok) setMatches(data.matches || []);",
    '      else setMessage(data.message || "Could not load maker matches.");',
    "    } catch {",
    '      setMessage("Could not reach the server.");',
    "    } finally {",
    "      setLoading(false);",
    "    }",
    "  }",
    "",
    "  async function allocate(makerId: string) {",
    "    setAllocating(true);",
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/marketplace/orders/${order.id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ makerId })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setMessage(data.message || "Could not allocate the order.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setMessage("Could not reach the server.");',
    "    } finally {",
    "      setAllocating(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <article className="wide-card">',
    "      <span>{order.material || \"Order\"}</span>",
    "      <strong>{order.orderNumber} · {order.productName}</strong>",
    '      <p className="note">Qty {order.quantity} · ${order.totalAmount.toFixed(2)} · ${(order.totalAmount * 0.7).toFixed(2)} to maker</p>',
    "      {!open ? (",
    '        <button className="button primary" type="button" onClick={findMakers}>Find best makers</button>',
    "      ) : loading ? (",
    '        <p className="note">Finding best makers…</p>',
    "      ) : matches.length === 0 ? (",
    '        <p className="note">{message || "No available makers found."}</p>',
    "      ) : (",
    '        <div className="stack">',
    "          {matches.map((m, index) => (",
    '            <div className="panel" key={m.makerId}>',
    "              <strong>{m.businessName}{index === 0 ? \" · Best match\" : \"\"}</strong>",
    '              <p className="note">Score {m.matchScore} · {m.rating.toFixed(1)}★ · {m.completedOrders} orders · earns ${m.estimatedEarnings.toFixed(2)}</p>',
    '              <p className="note">{m.reasons.join(" · ")}</p>',
    '              <button className="button" type="button" onClick={() => allocate(m.makerId)} disabled={allocating}>',
    '                {allocating ? "Assigning…" : `Assign to ${m.businessName}`}',
    "              </button>",
    "            </div>",
    "          ))}",
    '          {message ? <p className="note" role="alert">{message}</p> : null}',
    "        </div>",
    "      )}",
    "    </article>",
    "  );",
    "}"
  ]);
}

export const marketplaceOrdersModule: AppModule = {
  slug: "marketplace-orders",
  name: "Marketplace & Orders",
  tier: "optional",
  featureFlagEnv: "FEATURE_MARKETPLACE",
  files: () => [
    marketplaceLibFile(),
    productsApiFile(),
    ordersApiFile(),
    orderDetailApiFile(),
    orderMatchesApiFile(),
    makersApiFile(),
    makerDetailApiFile(),
    marketplacePageFile(),
    productDetailPageFile(),
    checkoutFormFile(),
    ordersPageFile(),
    orderDetailPageFile(),
    orderStatusControlsFile(),
    makersPageFile(),
    addMakerFormFile(),
    makerDetailPageFile(),
    makerStatusControlsFile(),
    allocatePageFile(),
    allocatePanelFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists marketplace_orders_categories (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null default '',",
      "  slug text not null default '',",
      "  description text not null default '',",
      "  display_order integer not null default 0,",
      "  active boolean not null default true,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists marketplace_orders_categories_order_idx on marketplace_orders_categories (display_order);",
      "",
      "create table if not exists marketplace_orders_products (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null default '',",
      "  description text not null default '',",
      "  base_price numeric(10,2) not null default 0,",
      "  add_on_price numeric(10,2) not null default 0,",
      "  image_url text not null default '',",
      "  material text not null default '',",
      "  category_id uuid references marketplace_orders_categories(id) on delete set null,",
      "  sku text not null default '',",
      "  stock_quantity integer not null default 0,",
      "  active boolean not null default true,",
      "  bulk_discount_eligible boolean not null default true,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists marketplace_orders_products_category_idx on marketplace_orders_products (category_id);",
      "create index if not exists marketplace_orders_products_active_idx on marketplace_orders_products (active);",
      "create index if not exists marketplace_orders_products_created_idx on marketplace_orders_products (created_at desc);",
      "",
      "create table if not exists marketplace_orders_makers (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  business_name text not null default '',",
      "  platform_email text not null default '',",
      "  location text not null default '',",
      "  bio text not null default '',",
      "  status text not null default 'active',",
      "  accepting_orders boolean not null default true,",
      "  average_rating numeric(3,2) not null default 0,",
      "  completed_orders integer not null default 0,",
      "  total_earnings numeric(12,2) not null default 0,",
      "  acceptance_rate numeric(5,2) not null default 100,",
      "  average_completion_hours numeric(8,2) not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists marketplace_orders_makers_owner_idx on marketplace_orders_makers (owner_id);",
      "create index if not exists marketplace_orders_makers_status_idx on marketplace_orders_makers (status);",
      "",
      "create table if not exists marketplace_orders_orders (",
      "  id uuid primary key default gen_random_uuid(),",
      "  order_number text not null default '',",
      "  customer_id uuid references users(id) on delete set null,",
      "  customer_email text not null default '',",
      "  customer_name text not null default '',",
      "  product_id uuid references marketplace_orders_products(id) on delete set null,",
      "  product_name text not null default '',",
      "  material text not null default '',",
      "  quantity integer not null default 1,",
      "  unit_price numeric(10,2) not null default 0,",
      "  subtotal numeric(12,2) not null default 0,",
      "  bulk_discount_percent numeric(5,2) not null default 0,",
      "  bulk_discount_amount numeric(12,2) not null default 0,",
      "  total_amount numeric(12,2) not null default 0,",
      "  status text not null default 'pending',",
      "  fulfillment_type text not null default 'shipping',",
      "  shipping_address jsonb,",
      "  notes text not null default '',",
      "  maker_id uuid references marketplace_orders_makers(id) on delete set null,",
      "  maker_earnings numeric(12,2) not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists marketplace_orders_orders_customer_idx on marketplace_orders_orders (customer_id);",
      "create index if not exists marketplace_orders_orders_maker_idx on marketplace_orders_orders (maker_id);",
      "create index if not exists marketplace_orders_orders_status_idx on marketplace_orders_orders (status);",
      "create index if not exists marketplace_orders_orders_created_idx on marketplace_orders_orders (created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into marketplace_orders_categories (name, slug, description, display_order, active) values",
      "  ('Signs & Plaques', 'signs', 'Custom signage', 1, true),",
      "  ('Personalized Gifts', 'gifts', 'One-of-a-kind gifts', 2, true)",
      "on conflict do nothing;",
      "",
      "insert into marketplace_orders_products (name, description, base_price, add_on_price, material, sku, stock_quantity, active, bulk_discount_eligible) values",
      "  ('Engraved Oak Sign', 'A solid oak sign, personalized with your name or message.', 34.00, 6.00, 'Oak', 'OAK-SIGN-01', 25, true, true),",
      "  ('Slate Coaster Set', 'A set of natural slate coasters, engraved to order.', 22.00, 4.00, 'Slate', 'SLATE-COAST-04', 60, true, true)",
      "on conflict do nothing;",
      "",
      "insert into marketplace_orders_makers (business_name, platform_email, location, bio, status, accepting_orders, average_rating, completed_orders, total_earnings, acceptance_rate, average_completion_hours) values",
      "  ('Acme Laser Works', 'hello@acmelaser.example.com', 'Portland, OR', 'Professional laser engraving.', 'active', true, 4.80, 214, 18240, 96, 38.5),",
      "  ('Northside Makers', 'team@northside.example.com', 'Austin, TX', 'Small-batch custom engraving.', 'probation', true, 3.90, 12, 640, 72, 64.0)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Marketplace & Orders — set to false to switch the catalog, ordering, checkout,",
    "# and maker/vendor management off.",
    "FEATURE_MARKETPLACE=true"
  ],
  homeLinks: () => ['        <a className="button" href="/marketplace">Marketplace</a>'],
  navLinks: () => [{ href: "/marketplace", label: "Marketplace" }],
  requiredEnv: []
};