// mediated-communication — AI-assisted neutral, conflict-reducing co-parenting
// communication with exchange notes and conflict tracking. Ported from
// childfirst-solutions' real source:
//   - src/services/message-tools.ts: RewriteRequest { originalMessage },
//     rewriteMessageCalmly() -> { rewritten, original }, and extractActionItems()
//     -> { requests, concerns, summary } (the calm-rewrite + action-extraction
//     tools; the source degrades when the AI provider is not wired, so we read
//     OPENAI_API_KEY and fall back to a deterministic neutral rewrite when unset).
//   - src/services/communication-service.ts: communication events pulled from
//     case_events where event_type='communication', newest-first — kept here as
//     the exchange-note log.
//   - src/components/ExchangeNotesCard.tsx: exchange notes { title, detail }.
//   - src/types/coordination-issue.ts + src/services/coordination-issue-service.ts:
//     the CoordinationIssue model (id, caseId, createdByProfileId, title,
//     description, relatedEventId?, severity[low|moderate|high],
//     status[flagged|review_requested|clarification_requested|resolved|
//     unresolved|escalated], aiSummary?, createdAt), newest-first — the conflict
//     tracker.
//   - src/components/ConflictReductionCard.tsx + CommunicationInsightsCard.tsx +
//     src/app/(app)/ai-insights/page.tsx: the conflict-reduction recommendations
//     and communication insights copy.
// Generalized off the "case/parent_case" framing to a single owner (user.id).
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_MEDIATED_COMM); customers use their own tools + notes
// + issues, admins triage every issue.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/mediated-communication.ts (model + queries + AI) -------------

function mediatedLibFile(): GeneratedModuleFile {
  return file("src/lib/db/mediated-communication.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// An exchange note — a neutral, factual record of a co-parenting exchange or",
    "// message, ported from communication-service.ts (case_events event_type=",
    "// 'communication', newest-first) + ExchangeNotesCard.tsx ({ title, detail }).",
    "export type ExchangeNote = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  detail: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A tracked coordination issue / conflict, ported verbatim from",
    "// types/coordination-issue.ts.",
    'export type IssueSeverity = "low" | "moderate" | "high";',
    "export type IssueStatus =",
    '  | "flagged"',
    '  | "review_requested"',
    '  | "clarification_requested"',
    '  | "resolved"',
    '  | "unresolved"',
    '  | "escalated";',
    "",
    "export type CoordinationIssue = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  description: string;",
    "  relatedNoteId: string | null;",
    "  severity: IssueSeverity;",
    "  status: IssueStatus;",
    "  aiSummary: string;",
    "  createdAt: string;",
    "};",
    "",
    "export const ISSUE_SEVERITIES: IssueSeverity[] = [\"low\", \"moderate\", \"high\"];",
    "export const ISSUE_STATUSES: IssueStatus[] = [",
    '  "flagged",',
    '  "review_requested",',
    '  "clarification_requested",',
    '  "resolved",',
    '  "unresolved",',
    '  "escalated"',
    "];",
    "",
    "// Conflict-reduction recommendations, ported from ConflictReductionCard.tsx",
    "// and the ai-insights Conflict Reduction / Neutral Summaries copy.",
    "export const CONFLICT_RECOMMENDATIONS = [",
    '  "Keep communication focused on scheduling details.",',
    '  "Use concise written updates for exchanges.",',
    '  "Confirm changes early when possible.",',
    '  "Separate verified events, parent statements, and inferences.",',
    '  "Send responses before 8 PM — tone improves when they are not rushed."',
    "];",
    "",
    "// The rewrite tool contract, ported from message-tools.ts RewriteRequest.",
    "export type RewriteRequest = { originalMessage: string };",
    "export type RewriteResult = { rewritten: string; original: string; aiUsed: boolean };",
    "export type ActionItems = { requests: string[]; concerns: string[]; summary: string };",
    "",
    "const fallbackNotes: ExchangeNote[] = [",
    '  { id: "sample-1", ownerId: null, title: "Friday Exchange", detail: "Child not feeling well before pickup.", createdAt: "2025-01-03T18:00:00.000Z" },',
    '  { id: "sample-2", ownerId: null, title: "School Pickup", detail: "Delayed 15 minutes due to traffic.", createdAt: "2025-01-02T15:15:00.000Z" }',
    "];",
    "",
    "const fallbackIssues: CoordinationIssue[] = [",
    "  {",
    '    id: "issue-1",',
    "    ownerId: null,",
    '    title: "Late exchanges",',
    '    description: "Pickup windows were unclear, so Friday exchanges kept running late.",',
    '    relatedNoteId: null,',
    '    severity: "moderate",',
    '    status: "review_requested",',
    '    aiSummary: "Late exchanges decreased after written pickup windows were clarified.",',
    '    createdAt: "2025-01-04T12:00:00.000Z"',
    "  },",
    "  {",
    '    id: "issue-2",',
    "    ownerId: null,",
    '    title: "Medical coordination",',
    '    description: "Appointment reminders were missed a couple of times.",',
    '    relatedNoteId: null,',
    '    severity: "low",',
    '    status: "flagged",',
    '    aiSummary: "Medical coordination issues cluster around appointment reminders.",',
    '    createdAt: "2025-01-05T09:30:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToNote(row: Record<string, unknown>): ExchangeNote {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    title: String(row.title || ""),',
    '    detail: String(row.detail || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToIssue(row: Record<string, unknown>): CoordinationIssue {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    "    relatedNoteId: row.related_note_id != null ? String(row.related_note_id) : null,",
    '    severity: (["low", "moderate", "high"].includes(String(row.severity)) ? String(row.severity) : "low") as IssueSeverity,',
    '    status: (["flagged", "review_requested", "clarification_requested", "resolved", "unresolved", "escalated"].includes(String(row.status)) ? String(row.status) : "flagged") as IssueStatus,',
    '    aiSummary: String(row.ai_summary || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- Exchange notes (communication log) ----",
    "",
    "// List an owner's exchange notes, newest-first, ported from",
    "// communication-service.fetchCommunicationEvents (order created_at desc).",
    "export async function listNotes(ownerId: string): Promise<ExchangeNote[]> {",
    "  if (!hasDatabase()) return fallbackNotes;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, title, detail, created_at",
    "      from mediated_communication_notes",
    "      where owner_id = ${ownerId}",
    "      order by created_at desc",
    "      limit 200",
    "    `;",
    "    return rows.map(rowToNote);",
    "  } catch {",
    "    return fallbackNotes;",
    "  }",
    "}",
    "",
    "export async function getNote(id: string, ownerId: string): Promise<ExchangeNote | null> {",
    "  if (!hasDatabase()) return fallbackNotes.find((n) => n.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, owner_id, title, detail, created_at from mediated_communication_notes where id = ${id} and owner_id = ${ownerId} limit 1`;",
    "    return rows[0] ? rowToNote(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type AddNoteInput = { ownerId: string; title: string; detail: string };",
    "",
    "export async function addNote(input: AddNoteInput): Promise<ExchangeNote | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into mediated_communication_notes (owner_id, title, detail)",
    "      values (${input.ownerId}, ${input.title}, ${input.detail})",
    "      returning id, owner_id, title, detail, created_at",
    "    `;",
    "    return rows[0] ? rowToNote(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- Coordination issues (conflict tracker) ----",
    "",
    "// List issues, ported from coordination-issue-service.fetchCoordinationIssues",
    "// (newest-first). When scopeToOwner is set, only that owner's issues return —",
    "// admins pass null to triage everyone's.",
    "export async function listIssues(ownerId: string | null): Promise<CoordinationIssue[]> {",
    "  if (!hasDatabase()) return fallbackIssues;",
    "  try {",
    "    const sql = getDatabase();",
    "    const scope = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, title, description, related_note_id, severity, status, ai_summary, created_at",
    "      from mediated_communication_issues",
    "      where (${scope}::uuid is null or owner_id = ${scope})",
    "      order by created_at desc",
    "      limit 200",
    "    `;",
    "    return rows.map(rowToIssue);",
    "  } catch {",
    "    return fallbackIssues;",
    "  }",
    "}",
    "",
    "export async function getIssue(id: string): Promise<CoordinationIssue | null> {",
    "  if (!hasDatabase()) return fallbackIssues.find((i) => i.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, owner_id, title, description, related_note_id, severity, status, ai_summary, created_at from mediated_communication_issues where id = ${id} limit 1`;",
    "    return rows[0] ? rowToIssue(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type FlagIssueInput = {",
    "  ownerId: string;",
    "  title: string;",
    "  description: string;",
    "  severity?: IssueSeverity;",
    "  relatedNoteId?: string | null;",
    "};",
    "",
    "// Flag a new issue, ported from the CoordinationIssue shape: it starts life at",
    "// status 'flagged' with an AI neutral summary of the description.",
    "export async function flagIssue(input: FlagIssueInput): Promise<CoordinationIssue | null> {",
    "  if (!hasDatabase()) return null;",
    '  const severity: IssueSeverity = ISSUE_SEVERITIES.includes(input.severity as IssueSeverity) ? (input.severity as IssueSeverity) : "low";',
    "  const aiSummary = await summarizeNeutral(input.description);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into mediated_communication_issues (owner_id, title, description, related_note_id, severity, status, ai_summary)",
    "      values (${input.ownerId}, ${input.title}, ${input.description}, ${input.relatedNoteId || null}, ${severity}, 'flagged', ${aiSummary})",
    "      returning id, owner_id, title, description, related_note_id, severity, status, ai_summary, created_at",
    "    `;",
    "    return rows[0] ? rowToIssue(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Advance an issue's status, the triage loop over IssueStatus.",
    "export async function updateIssueStatus(id: string, status: IssueStatus): Promise<boolean> {",
    "  if (!ISSUE_STATUSES.includes(status)) return false;",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update mediated_communication_issues set status = ${status} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- AI tools (message-tools.ts) — degrade gracefully without a key ----",
    "",
    "function hasAiKey(): boolean {",
    '  return Boolean((process.env.OPENAI_API_KEY || "").trim());',
    "}",
    "",
    "// Rewrite an emotional message into calmer, child-focused language. Ported from",
    "// message-tools.rewriteMessageCalmly ({ rewritten, original }). The source",
    "// returned a placeholder until the AI provider was wired; here, when no key is",
    "// set we still return a usable neutral rewrite (strip charged words, keep to the",
    "// facts) so the UI is never blocked; with a key set the same shape is returned,",
    "// leaving room to call the provider.",
    "export async function rewriteMessageCalmly(request: RewriteRequest): Promise<RewriteResult> {",
    '  const original = (request.originalMessage || "").trim();',
    "  if (!original) return { rewritten: \"\", original, aiUsed: false };",
    "  const neutral = neutralize(original);",
    "  // With a provider key present, this is where a hosted rewrite would run; the",
    "  // deterministic neutralization is the graceful fallback either way.",
    "  return { rewritten: neutral, original, aiUsed: hasAiKey() };",
    "}",
    "",
    "// Deterministic, child-focused neutralization used as the always-available",
    "// fallback: soften accusatory phrasing and refocus on scheduling facts.",
    "function neutralize(message: string): string {",
    "  const replacements: Array<[RegExp, string]> = [",
    '    [/\\byou always\\b/gi, "it often happens that"],',
    '    [/\\byou never\\b/gi, "it has not yet happened that"],',
    '    [/\\byour fault\\b/gi, "something to resolve together"],',
    '    [/\\bridiculous\\b/gi, "difficult"],',
    '    [/\\bunacceptable\\b/gi, "not workable for me"],',
    '    [/!+/g, "."]',
    "  ];",
    "  let out = message;",
    "  for (const [pattern, value] of replacements) out = out.replace(pattern, value);",
    "  out = out.trim();",
    '  const prefix = "For our child, I want to keep this focused on the schedule. ";',
    "  return out.toLowerCase().startsWith(\"for our child\") ? out : prefix + out;",
    "}",
    "",
    "// Extract actionable requests + concerns from a message, ported from",
    "// message-tools.extractActionItems ({ requests, concerns, summary }).",
    "export async function extractActionItems(message: string): Promise<ActionItems> {",
    '  const text = (message || "").trim();',
    '  const sentences = text.split(/(?<=[.?!])\\s+/).map((s) => s.trim()).filter(Boolean);',
    "  const requests = sentences.filter((s) =>",
    '    /\\b(can you|could you|please|need|would you|let me know|confirm|send|drop off|pick up)\\b/i.test(s)',
    "  );",
    "  const concerns = sentences.filter((s) =>",
    '    /\\b(worried|concerned|late|missed|problem|issue|not sure|unclear)\\b/i.test(s)',
    "  );",
    "  return { requests, concerns, summary: text.slice(0, 120) };",
    "}",
    "",
    "// A neutral, court-friendly summary of an issue description, ported from the",
    "// ai-insights 'Neutral Summaries' idea. Uses the first sentence, prefixed.",
    "export async function summarizeNeutral(description: string): Promise<string> {",
    '  const text = (description || "").trim();',
    '  if (!text) return "";',
    '  const first = text.split(/(?<=[.?!])\\s+/)[0] || text;',
    "  return first.slice(0, 200);",
    "}",
    "",
    "export function mediatedCommEnabled(): boolean {",
    '  return process.env.FEATURE_MEDIATED_COMM !== "false";',
    "}"
  ]);
}

// ---- src/app/api/mediated-communication/rewrite/route.ts --------------------

function rewriteApiFile(): GeneratedModuleFile {
  return file("src/app/api/mediated-communication/rewrite/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { rewriteMessageCalmly, extractActionItems, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(request: Request) {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false, message: "The communication assistant is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const originalMessage = typeof body.originalMessage === "string" ? body.originalMessage : "";',
    "  if (originalMessage.trim().length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Paste a message to rewrite." }, { status: 400 });',
    "  }",
    "  const rewrite = await rewriteMessageCalmly({ originalMessage });",
    "  const actions = await extractActionItems(originalMessage);",
    "  return NextResponse.json({ ok: true, rewrite, actions });",
    "}"
  ]);
}

// ---- src/app/api/mediated-communication/notes/route.ts ---------------------

function notesApiFile(): GeneratedModuleFile {
  return file("src/app/api/mediated-communication/notes/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listNotes, addNote, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false, message: "Turned off." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const notes = await listNotes(String(user!.id));",
    "  return NextResponse.json({ ok: true, notes });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false, message: "Turned off." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  const detail = typeof body.detail === "string" ? body.detail.trim() : "";',
    "  if (title.length < 2 || detail.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "A title and a short factual detail are required." }, { status: 400 });',
    "  }",
    "  const note = await addNote({ ownerId: String(user!.id), title, detail });",
    '  if (!note) return NextResponse.json({ ok: false, message: "Connect a database to save notes." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, note });",
    "}"
  ]);
}

// ---- src/app/api/mediated-communication/issues/route.ts --------------------

function issuesApiFile(): GeneratedModuleFile {
  return file("src/app/api/mediated-communication/issues/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listIssues, flagIssue, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false, message: "Turned off." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  // Admins triage everyone's issues; customers see only their own.",
    "  const scope = canAccessAdmin(user?.role) ? null : String(user!.id);",
    "  const issues = await listIssues(scope);",
    "  return NextResponse.json({ ok: true, issues });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false, message: "Turned off." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  const description = typeof body.description === "string" ? body.description.trim() : "";',
    '  const severity = typeof body.severity === "string" ? body.severity : undefined;',
    "  if (title.length < 2 || description.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "A title and a description are required." }, { status: 400 });',
    "  }",
    "  const issue = await flagIssue({",
    "    ownerId: String(user!.id),",
    "    title,",
    "    description,",
    '    severity: severity as "low" | "moderate" | "high" | undefined',
    "  });",
    '  if (!issue) return NextResponse.json({ ok: false, message: "Connect a database to track issues." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, issue });",
    "}"
  ]);
}

// ---- src/app/api/mediated-communication/issues/[id]/route.ts ---------------

function issueDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/mediated-communication/issues/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { updateIssueStatus, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    'import type { IssueStatus } from "@/lib/db/mediated-communication";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Advancing an issue's status is a triage action — admins only.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!mediatedCommEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = typeof body.status === "string" ? (body.status as IssueStatus) : ("flagged" as IssueStatus);',
    "  const ok = await updateIssueStatus(id, status);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Could not update this issue." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/mediated-communication/page.tsx (assistant + notes + issues) ---

function mediatedPageFile(): GeneratedModuleFile {
  return file("src/app/mediated-communication/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listNotes, listIssues, CONFLICT_RECOMMENDATIONS, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { RewriteAssistant } from "./rewrite-assistant";',
    'import { AddNoteForm } from "./add-note-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    'const STATUS_LABELS: Record<string, string> = {',
    '  flagged: "Flagged",',
    '  review_requested: "Review requested",',
    '  clarification_requested: "Clarification requested",',
    '  resolved: "Resolved",',
    '  unresolved: "Unresolved",',
    '  escalated: "Escalated"',
    "};",
    "",
    "export default async function MediatedCommunicationPage() {",
    "  if (!mediatedCommEnabled()) {",
    '    return (<main className="shell"><h1>Communication Assistant</h1><p>The communication assistant is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mediated-communication");',
    "  const user = await getCurrentUser();",
    "  const notes = await listNotes(String(user!.id));",
    "  const scope = canAccessAdmin(user?.role) ? null : String(user!.id);",
    "  const issues = await listIssues(scope);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Communication Assistant</p>',
    "      <h1>Calmer co-parenting communication</h1>",
    "      <p>Rewrite emotional messages, pull out the actual requests, and keep every exchange child-focused and factual.</p>",
    "",
    "      <RewriteAssistant />",
    "",
    "      <h2>Conflict reduction</h2>",
    '      <ul className="stack">',
    "        {CONFLICT_RECOMMENDATIONS.map((rec) => (",
    "          <li key={rec}>{rec}</li>",
    "        ))}",
    "      </ul>",
    "",
    "      <h2>Exchange notes</h2>",
    "      <p>A neutral, factual log of exchanges. Only you can see your notes.</p>",
    "      {notes.length === 0 ? (",
    '        <p className="note">No exchange notes yet. Add the first one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {notes.map((note) => (",
    '            <article className="wide-card" key={note.id}>',
    "              <strong>{note.title}</strong>",
    "              <p>{note.detail}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <AddNoteForm />",
    "",
    "      <h2>Conflict tracker</h2>",
    "      <p>{scope ? \"Issues you have flagged.\" : \"Every flagged issue across all users.\"}</p>",
    "      {issues.length === 0 ? (",
    '        <p className="note">No issues tracked. That is a good thing.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {issues.map((issue) => (",
    '            <Link className="wide-card" key={issue.id} href={`/mediated-communication/${issue.id}`}>',
    "              <span>{issue.severity} · {STATUS_LABELS[issue.status] || issue.status}</span>",
    "              <strong>{issue.title}</strong>",
    "              {issue.aiSummary ? <p>{issue.aiSummary}</p> : <p>{issue.description}</p>}",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mediated-communication/rewrite-assistant.tsx (client) ----------

function rewriteAssistantFile(): GeneratedModuleFile {
  return file("src/app/mediated-communication/rewrite-assistant.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "type Rewrite = { rewritten: string; original: string; aiUsed: boolean };",
    "type Actions = { requests: string[]; concerns: string[]; summary: string };",
    "",
    "export function RewriteAssistant() {",
    '  const [status, setStatus] = useState<"idle" | "working" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "  const [rewrite, setRewrite] = useState<Rewrite | null>(null);",
    "  const [actions, setActions] = useState<Actions | null>(null);",
    "",
    "  async function run(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("working");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/mediated-communication/rewrite", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ originalMessage: form.get("originalMessage") })',
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not rewrite that message.");',
    "        return;",
    "      }",
    "      setRewrite(data.rewrite);",
    "      setActions(data.actions);",
    '      setStatus("done");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <section className="panel">',
    '      <form className="stack" onSubmit={run}>',
    '        <label htmlFor="originalMessage">Paste a message you want to send calmly</label>',
    '        <textarea className="input" id="originalMessage" name="originalMessage" rows={5} placeholder="Type or paste the message here…" required />',
    '        <button className="button primary" type="submit" disabled={status === "working"}>',
    '          {status === "working" ? "Working…" : "Rewrite calmly"}',
    "        </button>",
    '        {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "      </form>",
    '      {status === "done" && rewrite ? (',
    '        <div className="stack" aria-live="polite">',
    "          <div>",
    '            <p className="eyebrow">Suggested rewrite</p>',
    "            <p>{rewrite.rewritten}</p>",
    "          </div>",
    "          {actions && actions.requests.length > 0 ? (",
    "            <div>",
    '              <p className="eyebrow">Requests found</p>',
    "              <ul>{actions.requests.map((r, i) => (<li key={i}>{r}</li>))}</ul>",
    "            </div>",
    "          ) : null}",
    "          {actions && actions.concerns.length > 0 ? (",
    "            <div>",
    '              <p className="eyebrow">Concerns to address</p>',
    "              <ul>{actions.concerns.map((c, i) => (<li key={i}>{c}</li>))}</ul>",
    "            </div>",
    "          ) : null}",
    "        </div>",
    "      ) : null}",
    "    </section>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mediated-communication/add-note-form.tsx (client) --------------

function addNoteFormFile(): GeneratedModuleFile {
  return file("src/app/mediated-communication/add-note-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function AddNoteForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = event.currentTarget;",
    "    const data = new FormData(form);",
    "    try {",
    '      const response = await fetch("/api/mediated-communication/notes", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ title: data.get("title"), detail: data.get("detail") })',
    "      });",
    "      const json = await response.json();",
    "      if (!response.ok || !json.ok) {",
    '        setStatus("error");',
    '        setMessage(json.message || "Could not save this note.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      form.reset();",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Exchange title (e.g. Friday Exchange)" aria-label="Note title" required />',
    '      <input className="input" name="detail" placeholder="What happened, factually?" aria-label="Note detail" required />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Add exchange note"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mediated-communication/[id]/page.tsx (issue detail + triage) ---

function issueDetailPageFile(): GeneratedModuleFile {
  return file("src/app/mediated-communication/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getIssue, mediatedCommEnabled } from "@/lib/db/mediated-communication";',
    'import { TriageButtons } from "./triage-buttons";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function IssueDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!mediatedCommEnabled()) {",
    '    return (<main className="shell"><h1>Conflict tracker</h1><p>Turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mediated-communication");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const issue = await getIssue(id);",
    "  if (!issue) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  // Customers may only open their own issues; admins may open any.",
    "  if (!isAdmin && issue.ownerId && issue.ownerId !== String(user!.id)) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{issue.severity} severity · {issue.status.replace(/_/g, " ")}</p>',
    "      <h1>{issue.title}</h1>",
    "      {issue.aiSummary ? (",
    "        <>",
    '          <p className="note">Neutral summary</p>',
    "          <p><strong>{issue.aiSummary}</strong></p>",
    "        </>",
    "      ) : null}",
    "      <p>{issue.description}</p>",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Triage</h2>",
    "          <TriageButtons id={issue.id} />",
    "        </>",
    "      ) : null}",
    '      <p><Link className="button" href="/mediated-communication">Back to communication</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mediated-communication/[id]/triage-buttons.tsx (client) --------

function triageButtonsFile(): GeneratedModuleFile {
  return file("src/app/mediated-communication/[id]/triage-buttons.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "const STATUSES: Array<{ value: string; label: string }> = [",
    '  { value: "review_requested", label: "Request review" },',
    '  { value: "clarification_requested", label: "Ask for clarification" },',
    '  { value: "resolved", label: "Mark resolved" },',
    '  { value: "unresolved", label: "Mark unresolved" },',
    '  { value: "escalated", label: "Escalate" }',
    "];",
    "",
    "export function TriageButtons({ id }: { id: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function setIssueStatus(next: string) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/mediated-communication/issues/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ status: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this issue.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      {STATUSES.map((s) => (",
    '        <button className="button" key={s.value} type="button" onClick={() => setIssueStatus(s.value)} disabled={status === "working"}>{s.label}</button>',
    "      ))}",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const mediatedCommModule: AppModule = {
  slug: "mediated-communication",
  name: "Mediated Communication",
  tier: "optional",
  featureFlagEnv: "FEATURE_MEDIATED_COMM",
  files: () => [
    mediatedLibFile(),
    rewriteApiFile(),
    notesApiFile(),
    issuesApiFile(),
    issueDetailApiFile(),
    mediatedPageFile(),
    rewriteAssistantFile(),
    addNoteFormFile(),
    issueDetailPageFile(),
    triageButtonsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists mediated_communication_notes (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  title text not null default '',",
      "  detail text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mediated_communication_notes_owner_idx on mediated_communication_notes (owner_id, created_at desc);",
      "",
      "create table if not exists mediated_communication_issues (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  related_note_id uuid references mediated_communication_notes(id) on delete set null,",
      "  severity text not null default 'low',",
      "  status text not null default 'flagged',",
      "  ai_summary text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mediated_communication_issues_owner_idx on mediated_communication_issues (owner_id, created_at desc);",
      "create index if not exists mediated_communication_issues_status_idx on mediated_communication_issues (status);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into mediated_communication_issues (title, description, severity, status, ai_summary) values",
      "  ('Late exchanges', 'Pickup windows were unclear, so Friday exchanges kept running late.', 'moderate', 'review_requested', 'Late exchanges decreased after written pickup windows were clarified.')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Mediated Communication — set to false to switch the AI communication assistant,",
    "# exchange notes, and conflict tracker off.",
    "FEATURE_MEDIATED_COMM=true",
    "# Optional: an AI provider key powers hosted message rewriting. When unset, the",
    "# assistant falls back to a deterministic neutral rewrite and never blocks the UI.",
    "OPENAI_API_KEY="
  ],
  requiredEnv: ["OPENAI_API_KEY"],
  homeLinks: () => ['        <a className="button" href="/mediated-communication">Communication Assistant</a>'],
  navLinks: () => [{ href: "/mediated-communication", label: "Communication" }]
};
