// membership-registry — a free membership program with a verifiable seal,
// factored from the United Under God SEAL built 2026-07-10 on the live
// uug-website repo (src/lib/seal.ts, /join, /members/[slug], /badge/[slug],
// public/seal.js, the /admin membership queue) against the shared LPL
// Supabase. Generalized here to the factory's Next+Neon shape: organizations
// apply through a statement-of-intent join flow, the app owner approves each
// one from a review queue, approved members get a public verification page,
// a directory listing, and an embeddable badge that renders ONLY while
// membership is active and always links back to the member page — the link
// is the verification. The owner is the gate on who displays the seal.
// Membership is free by design; the statement-of-intent copy emitted below is
// a neutral placeholder for the app owner to make their own (doctrine never
// ships from the factory).

import type { AppModule, AppModuleContext, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/membership.ts (model, queries, badge, snippets) -------------

function membershipLibFile(ctx: AppModuleContext): GeneratedModuleFile {
  const appName = JSON.stringify(ctx.projectName);
  return file("src/lib/db/membership.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    `export const MEMBERSHIP_APP_NAME = ${appName};`,
    "",
    "// What a member organization affirms when it joins. Placeholder wording —",
    "// the app owner should make this statement their own before launch.",
    "export const STATEMENT_OF_INTENT = [",
    `  \`Our organization chooses to stand with the \${MEMBERSHIP_APP_NAME} community.\`,`,
    "  \"We choose to operate openly and treat others the way we want to be treated.\",",
    "  \"We choose to be counted publicly among the organizations that share this intent.\"",
    "];",
    "",
    "export const ORG_TYPES = [\"church\", \"business\", \"charity\", \"association\", \"other\"] as const;",
    "",
    "export const ORG_TYPE_LABELS: Record<string, string> = {",
    "  church: \"Church\",",
    "  business: \"Business\",",
    "  charity: \"Charity\",",
    "  association: \"Association\",",
    "  other: \"Organization\"",
    "};",
    "",
    "export type MemberOrganization = {",
    "  id: string;",
    "  name: string;",
    "  orgType: string;",
    "  website: string;",
    "  contactName: string;",
    "  contactEmail: string;",
    "  message: string;",
    "  status: \"pending\" | \"member\";",
    "  slug: string;",
    "  createdAt: string;",
    "  joinedAt: string | null;",
    "};",
    "",
    "const fallbackMembers: MemberOrganization[] = [",
    "  { id: \"sample-1\", name: \"First Sample Fellowship\", orgType: \"church\", website: \"https://example.org\", contactName: \"Sample Contact\", contactEmail: \"sample@example.org\", message: \"\", status: \"member\", slug: \"first-sample-fellowship\", createdAt: new Date(0).toISOString(), joinedAt: new Date(0).toISOString() }",
    "];",
    "",
    "function rowToOrganization(row: Record<string, unknown>): MemberOrganization {",
    "  return {",
    "    id: String(row.id),",
    "    name: String(row.name || \"\"),",
    "    orgType: String(row.org_type || \"other\"),",
    "    website: String(row.website || \"\"),",
    "    contactName: String(row.contact_name || \"\"),",
    "    contactEmail: String(row.contact_email || \"\"),",
    "    message: String(row.message || \"\"),",
    "    status: row.status === \"member\" ? \"member\" : \"pending\",",
    "    slug: String(row.slug || \"\"),",
    "    createdAt: String(row.created_at || \"\"),",
    "    joinedAt: row.joined_at ? String(row.joined_at) : null",
    "  };",
    "}",
    "",
    "export function membershipEnabled(): boolean {",
    "  return process.env.FEATURE_MEMBERSHIP !== \"false\";",
    "}",
    "",
    "export function memberSince(joinedAt: string | null): string {",
    "  if (!joinedAt) return \"\";",
    "  return new Date(joinedAt).toLocaleDateString(\"en-US\", { month: \"long\", year: \"numeric\" });",
    "}",
    "",
    "function slugify(name: string): string {",
    "  const base = name.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/(^-+|-+$)/g, \"\").slice(0, 80);",
    "  return base || \"organization\";",
    "}",
    "",
    "// Public read: approved members only, newest-joined last (founding first).",
    "export async function listMembers(): Promise<MemberOrganization[]> {",
    "  if (!hasDatabase()) return fallbackMembers;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, name, org_type, website, slug, status, created_at, joined_at, '' as contact_name, '' as contact_email, '' as message from membership_registry_organizations where status = 'member' order by joined_at asc, name asc limit 1000`;",
    "    return rows.map(rowToOrganization);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Public read of one member by slug — contact details deliberately withheld.",
    "export async function getMemberBySlug(slug: string): Promise<MemberOrganization | null> {",
    "  if (!hasDatabase()) return fallbackMembers.find((member) => member.slug === slug) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, name, org_type, website, slug, status, created_at, joined_at, '' as contact_name, '' as contact_email, '' as message from membership_registry_organizations where slug = ${slug} and status = 'member' limit 1`;",
    "    return rows[0] ? rowToOrganization(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Owner read: everything, applications first.",
    "export async function listAllOrganizations(): Promise<MemberOrganization[]> {",
    "  if (!hasDatabase()) return fallbackMembers;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select * from membership_registry_organizations order by (status = 'pending') desc, created_at desc limit 2000`;",
    "    return rows.map(rowToOrganization);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type MembershipApplication = {",
    "  name: string; orgType: string; website?: string;",
    "  contactName: string; contactEmail: string; message?: string;",
    "};",
    "",
    "// Applications always arrive pending — approval is the owner's alone. The",
    "// slug is minted here with a dedupe loop so every member page URL is stable",
    "// and collision-free.",
    "export async function applyForMembership(input: MembershipApplication): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  const base = slugify(input.name);",
    "  let slug = base;",
    "  for (let n = 2; n < 200; n += 1) {",
    "    const existing = await sql`select id from membership_registry_organizations where slug = ${slug} limit 1`;",
    "    if (!existing[0]) break;",
    "    slug = `${base}-${n}`;",
    "  }",
    "  const orgType = (ORG_TYPES as readonly string[]).includes(input.orgType) ? input.orgType : \"other\";",
    "  await sql`insert into membership_registry_organizations (name, org_type, website, contact_name, contact_email, message, status, slug) values (${input.name}, ${orgType}, ${input.website || \"\"}, ${input.contactName}, ${input.contactEmail}, ${input.message || \"\"}, 'pending', ${slug})`;",
    "  return true;",
    "}",
    "",
    "// Approve (member page + badge go live) or revoke (both die immediately).",
    "export async function setMembershipStatus(id: string, status: \"pending\" | \"member\"): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  if (status === \"member\") {",
    "    await sql`update membership_registry_organizations set status = 'member', joined_at = now() where id = ${id}`;",
    "  } else {",
    "    await sql`update membership_registry_organizations set status = 'pending', joined_at = null where id = ${id}`;",
    "  }",
    "  return true;",
    "}",
    "",
    "export async function removeOrganization(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  const sql = getDatabase();",
    "  await sql`delete from membership_registry_organizations where id = ${id}`;",
    "  return true;",
    "}",
    "",
    "// Origin for embed snippets; empty string falls back to relative URLs.",
    "export function siteOrigin(): string {",
    "  return (process.env.APP_URL || process.env.AUTH_URL || \"\").replace(/\\/$/, \"\");",
    "}",
    "",
    "// The badge itself — self-contained colors so it reads on any host site.",
    "// Served only for active members; the link back to the member page is the",
    "// verification.",
    "export function badgeSvg(): string {",
    "  const ring = MEMBERSHIP_APP_NAME.toUpperCase().slice(0, 26);",
    "  return `<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\" role=\"img\" aria-label=\"Verified member\">",
    "  <title>Verified member of ${ring}</title>",
    "  <circle cx=\"100\" cy=\"100\" r=\"100\" fill=\"#101a33\"/>",
    "  <circle cx=\"100\" cy=\"100\" r=\"96\" fill=\"none\" stroke=\"#faf9f6\" stroke-width=\"2.5\"/>",
    "  <circle cx=\"100\" cy=\"100\" r=\"66\" fill=\"none\" stroke=\"#faf9f6\" stroke-width=\"1\"/>",
    "  <defs>",
    "    <path id=\"badge-arc-top\" d=\"M 18 100 A 82 82 0 0 1 182 100\" fill=\"none\"/>",
    "    <path id=\"badge-arc-bottom\" d=\"M 24 100 A 76 76 0 0 0 176 100\" fill=\"none\"/>",
    "  </defs>",
    "  <text font-size=\"12\" font-weight=\"700\" letter-spacing=\"2\" fill=\"#faf9f6\" font-family=\"system-ui, sans-serif\">",
    "    <textPath href=\"#badge-arc-top\" startOffset=\"50%\" text-anchor=\"middle\">${ring}</textPath>",
    "  </text>",
    "  <text font-size=\"10.5\" font-weight=\"600\" letter-spacing=\"2.2\" fill=\"#faf9f6\" font-family=\"system-ui, sans-serif\">",
    "    <textPath href=\"#badge-arc-bottom\" startOffset=\"50%\" text-anchor=\"middle\">VERIFIED MEMBER</textPath>",
    "  </text>",
    "  <g stroke=\"#faf9f6\" stroke-width=\"6\" fill=\"none\">",
    "    <circle cx=\"89\" cy=\"112\" r=\"23\"/>",
    "    <circle cx=\"111\" cy=\"112\" r=\"23\"/>",
    "    <path d=\"M100 62v25M88.5 74h23\" stroke-linecap=\"round\"/>",
    "  </g>",
    "</svg>`;",
    "}",
    "",
    "export function htmlSnippet(slug: string): string {",
    "  const origin = siteOrigin();",
    "  return `<a href=\"${origin}/members/${slug}\" target=\"_blank\" rel=\"noopener\">\\n  <img src=\"${origin}/badge/${slug}\" alt=\"Verified member — click to verify\" width=\"140\" height=\"140\" style=\"display:block\" />\\n</a>`;",
    "}"
  ]);
}

// ---- src/app/api/membership/route.ts (public apply + owner list) ------------

function membershipApiFile(): GeneratedModuleFile {
  return file("src/app/api/membership/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { applyForMembership, listAllOrganizations, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!membershipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const organizations = await listAllOrganizations();",
    "  return NextResponse.json({ ok: true, organizations });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!membershipEnabled()) return NextResponse.json({ ok: false, message: "Membership is turned off for this app." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  // Honeypot: bots that fill the hidden field get a quiet yes and no row.",
    '  if (typeof body.hp === "string" && body.hp.trim().length > 0) return NextResponse.json({ ok: true });',
    '  const name = typeof body.name === "string" ? body.name.trim().slice(0, 300) : "";',
    '  const contactName = typeof body.contactName === "string" ? body.contactName.trim().slice(0, 200) : "";',
    '  const contactEmail = typeof body.contactEmail === "string" ? body.contactEmail.trim().slice(0, 320) : "";',
    "  if (name.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Please add your organization\'s name." }, { status: 400 });',
    "  }",
    '  if (!contactName || !contactEmail.includes("@")) {',
    '    return NextResponse.json({ ok: false, message: "Please add a contact name and a real email." }, { status: 400 });',
    "  }",
    "  const created = await applyForMembership({",
    "    name,",
    "    contactName,",
    "    contactEmail,",
    '    orgType: typeof body.orgType === "string" ? body.orgType : "other",',
    '    website: typeof body.website === "string" ? body.website.trim().slice(0, 500) : undefined,',
    '    message: typeof body.message === "string" ? body.message.trim().slice(0, 4000) : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to accept applications." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/membership/[id]/route.ts (owner approve/revoke/remove) -----

function membershipDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/membership/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { removeOrganization, setMembershipStatus, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!membershipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = body.status === "member" ? "member" : "pending";',
    "  const updated = await setMembershipStatus(id, status);",
    '  if (!updated) return NextResponse.json({ ok: false, message: "Connect a database first." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!membershipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const removed = await removeOrganization(id);",
    '  if (!removed) return NextResponse.json({ ok: false, message: "Connect a database first." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/badge/[slug]/route.ts (the verifiable badge) --------------------

function badgeRouteFile(): GeneratedModuleFile {
  return file("src/app/badge/[slug]/route.ts", [
    'import { badgeSvg, getMemberBySlug, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Serves the badge ONLY for approved members, so an embedded badge stops",
    "// rendering the moment membership is revoked. Short cache keeps that honest.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ slug: string }> }) {",
    "  const { slug } = await params;",
    "  const member = membershipEnabled() ? await getMemberBySlug(slug) : null;",
    "  if (!member) {",
    '    return new Response("Not a verified member.", { status: 404, headers: { "Cache-Control": "public, max-age=60, s-maxage=60" } });',
    "  }",
    "  return new Response(badgeSvg(), {",
    "    headers: {",
    '      "Content-Type": "image/svg+xml; charset=utf-8",',
    '      "Cache-Control": "public, max-age=300, s-maxage=300, stale-while-revalidate=600",',
    '      "Access-Control-Allow-Origin": "*"',
    "    }",
    "  });",
    "}"
  ]);
}

// ---- src/components/membership/join-form.tsx (client) ------------------------

function joinFormFile(): GeneratedModuleFile {
  return file("src/components/membership/join-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "const ORG_TYPES = [",
    '  { value: "church", label: "A church" },',
    '  { value: "business", label: "A business" },',
    '  { value: "charity", label: "A charity" },',
    '  { value: "association", label: "An association" },',
    '  { value: "other", label: "Another kind of organization" }',
    "];",
    "",
    "export function MembershipJoinForm() {",
    '  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = event.currentTarget;",
    "    const data = new FormData(form);",
    '    const affirmed = data.get("affirm") === "on";',
    "    if (!affirmed) {",
    '      setStatus("error");',
    '      setMessage("Please check the box to make the statement of intent yours.");',
    "      return;",
    "    }",
    '    setStatus("sending");',
    '    setMessage("");',
    '    const response = await fetch("/api/membership", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    "      body: JSON.stringify({",
    '        name: String(data.get("name") || ""),',
    '        orgType: String(data.get("orgType") || "other"),',
    '        website: String(data.get("website") || ""),',
    '        contactName: String(data.get("contactName") || ""),',
    '        contactEmail: String(data.get("contactEmail") || ""),',
    '        message: String(data.get("message") || ""),',
    '        hp: String(data.get("hp") || "")',
    "      })",
    "    }).catch(() => null);",
    "    const payload = response ? await response.json().catch(() => null) : null;",
    "    if (!response || !response.ok || !payload?.ok) {",
    '      setStatus("error");',
    '      setMessage(payload?.message || "Something went wrong saving that. Please try again.");',
    "      return;",
    "    }",
    "    form.reset();",
    '    setStatus("sent");',
    "  }",
    "",
    '  if (status === "sent") {',
    "    return (",
    '      <div className="card" role="status">',
    "        <strong>Your application is in.</strong>",
    "        <p>Every application is reviewed personally. Once your organization is welcomed in, your member page and badge go live.</p>",
    '        <button className="button" type="button" onClick={() => setStatus("idle")}>Add another organization</button>',
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={handleSubmit} noValidate>',
    '      <input className="input" name="name" type="text" maxLength={300} placeholder="Your organization\'s name" aria-label="Organization name" required />',
    '      <select className="input" name="orgType" defaultValue="church" aria-label="Organization type">',
    "        {ORG_TYPES.map((option) => (",
    "          <option key={option.value} value={option.value}>{option.label}</option>",
    "        ))}",
    "      </select>",
    '      <input className="input" name="website" type="url" maxLength={500} placeholder="https:// (optional website)" aria-label="Website" />',
    '      <input className="input" name="contactName" type="text" maxLength={200} placeholder="Your name" aria-label="Contact name" required />',
    '      <input className="input" name="contactEmail" type="email" maxLength={320} placeholder="Email" aria-label="Contact email" required />',
    '      <textarea className="input" name="message" maxLength={4000} placeholder="Anything you want us to know? (optional)" aria-label="Message" />',
    "      <label>",
    '        <input name="affirm" type="checkbox" required /> Our organization makes this statement of intent.',
    "      </label>",
    "      {/* honeypot — humans never see it; bots fill it and the server quietly declines */}",
    '      <input name="hp" type="text" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{ position: "absolute", left: "-9999px" }} />',
    '      <button className="button primary" type="submit" disabled={status === "sending"}>',
    '        {status === "sending" ? "Sending…" : "Make the statement of intent"}',
    "      </button>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/join/page.tsx (the join flow) ------------------------------------

function joinPageFile(ctx: AppModuleContext): GeneratedModuleFile {
  return file("src/app/join/page.tsx", [
    'import { MembershipJoinForm } from "@/components/membership/join-form";',
    'import { STATEMENT_OF_INTENT, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default function JoinPage() {",
    "  if (!membershipEnabled()) {",
    '    return (<main className="shell"><h1>Membership</h1><p>Membership is turned off for this app.</p></main>);',
    "  }",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Membership — free</p>',
    "      <h1>Make the statement of intent.</h1>",
    `      <p>Membership in ${ctx.projectName.replace(/</g, "")} is free. It is a statement of intent your organization chooses to make — and a badge you can stand behind.</p>`,
    '      <blockquote className="card">',
    "        {STATEMENT_OF_INTENT.map((line) => (<p key={line}>{line}</p>))}",
    "      </blockquote>",
    "      <p>Every application is reviewed personally. Once your organization is welcomed in, your public member page goes live and the badge is yours to display — it always links back to your member page, so it can always be verified.</p>",
    "      <MembershipJoinForm />",
    '      <p className="note"><a href="/members">See the member organizations &rarr;</a></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/members/page.tsx (public directory) ------------------------------

function membersPageFile(): GeneratedModuleFile {
  return file("src/app/members/page.tsx", [
    'import Link from "next/link";',
    'import { ORG_TYPE_LABELS, listMembers, memberSince, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MembersPage() {",
    "  if (!membershipEnabled()) {",
    '    return (<main className="shell"><h1>Members</h1><p>Membership is turned off for this app.</p></main>);',
    "  }",
    "  const members = await listMembers();",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">The registry</p>',
    "      <h1>Member organizations</h1>",
    "      <p>Every member&rsquo;s page is public: when an organization displays the badge, it links here, so anyone can verify it.</p>",
    "      {members.length === 0 ? (",
    '        <p className="note">No member organizations yet — yours could be the first.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {members.map((member) => (",
    '            <Link className="wide-card" key={member.id} href={`/members/${member.slug}`}>',
    "              <span>{ORG_TYPE_LABELS[member.orgType] || \"Organization\"}{member.joinedAt ? ` · Member since ${memberSince(member.joinedAt)}` : \"\"}</span>",
    "              <strong>{member.name}</strong>",
    "              <p>Verify membership &rarr;</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button primary" href="/join">Join free</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/members/[slug]/page.tsx (verification page) ----------------------

function memberPageFile(ctx: AppModuleContext): GeneratedModuleFile {
  const safeName = ctx.projectName.replace(/</g, "");
  return file("src/app/members/[slug]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { ORG_TYPE_LABELS, STATEMENT_OF_INTENT, getMemberBySlug, htmlSnippet, memberSince, membershipEnabled } from "@/lib/db/membership";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MemberPage({ params }: { params: Promise<{ slug: string }> }) {",
    "  if (!membershipEnabled()) {",
    '    return (<main className="shell"><h1>Members</h1><p>Membership is turned off for this app.</p></main>);',
    "  }",
    "  const { slug } = await params;",
    "  const member = await getMemberBySlug(slug);",
    "  if (!member) notFound();",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Verified member</p>',
    "      <h1>{member.name}</h1>",
    '      <p className="note">',
    "        {ORG_TYPE_LABELS[member.orgType] || \"Organization\"}",
    "        {member.joinedAt ? ` · Member since ${memberSince(member.joinedAt)}` : \"\"}",
    "        {member.website ? <> · <a href={member.website} target=\"_blank\" rel=\"noopener\">Visit their site</a></> : null}",
    "      </p>",
    "      {/* the live badge route itself — the same image an embed shows */}",
    "      {/* eslint-disable-next-line @next/next/no-img-element */}",
    '      <img src={`/badge/${member.slug}`} alt="Verified member badge" width={160} height={160} />',
    `      <p><strong>This page is the verification.</strong> {member.name} is a member of ${safeName}. Wherever this organization displays the badge, the badge links back to this page. If a badge doesn&rsquo;t link here, it isn&rsquo;t ours.</p>`,
    "      <p>As a member, {member.name} has made this statement of intent:</p>",
    '      <blockquote className="card">',
    "        {STATEMENT_OF_INTENT.map((line) => (<p key={line}>{line}</p>))}",
    "      </blockquote>",
    '      <section className="card">',
    "        <strong>Display the badge on your site</strong>",
    "        <p>The badge is served only while membership is active, and it always links back to this page.</p>",
    "        <pre><code>{htmlSnippet(member.slug)}</code></pre>",
    "      </section>",
    '      <p><Link className="button primary" href="/join">Join free</Link> <Link className="button" href="/members">All members</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/membership-queue/page.tsx (owner review queue) -------------------

function queuePageFile(): GeneratedModuleFile {
  return file("src/app/membership-queue/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { ORG_TYPE_LABELS, listAllOrganizations, membershipEnabled } from "@/lib/db/membership";',
    'import { MembershipQueueActions } from "./actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MembershipQueuePage() {",
    "  if (!membershipEnabled()) {",
    '    return (<main className="shell"><h1>Membership</h1><p>Membership is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/membership-queue");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Membership queue</h1><p className="note">Only admins can review membership applications.</p></main>);',
    "  }",
    "  const organizations = await listAllOrganizations();",
    '  const pending = organizations.filter((org) => org.status === "pending").length;',
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Membership</p>',
    "      <h1>Review queue{pending > 0 ? ` (${pending} waiting)` : \"\"}</h1>",
    "      <p>You are the gate on who displays the badge. Approving an organization publishes its member page and turns on its badge immediately; revoking pulls both back.</p>",
    "      {organizations.length === 0 ? (",
    '        <p className="note">No applications yet. They arrive from /join.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {organizations.map((org) => (",
    '            <article className="wide-card" key={org.id}>',
    "              <span>{ORG_TYPE_LABELS[org.orgType] || \"Organization\"}{org.status === \"member\" ? \" · ✓ member\" : \" · pending\"}</span>",
    "              <strong>{org.name}</strong>",
    "              <p>{org.contactName} · {org.contactEmail}{org.website ? ` · ${org.website}` : \"\"}</p>",
    "              {org.message ? <p>&ldquo;{org.message}&rdquo;</p> : null}",
    "              <p>{org.status === \"member\" ? <a href={`/members/${org.slug}`}>/members/{org.slug}</a> : `/members/${org.slug} (goes live on approval)`}</p>",
    "              <MembershipQueueActions id={org.id} status={org.status} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/membership-queue/actions.tsx (client approve/revoke/remove) ------

function queueActionsFile(): GeneratedModuleFile {
  return file("src/app/membership-queue/actions.tsx", [
    '"use client";',
    "",
    'import { useRouter } from "next/navigation";',
    'import { useState } from "react";',
    "",
    "export function MembershipQueueActions({ id, status }: { id: string; status: \"pending\" | \"member\" }) {",
    "  const router = useRouter();",
    "  const [working, setWorking] = useState(false);",
    "",
    '  async function update(next: "member" | "pending" | "remove") {',
    "    setWorking(true);",
    '    if (next === "remove") {',
    '      await fetch(`/api/membership/${id}`, { method: "DELETE" }).catch(() => null);',
    "    } else {",
    '      await fetch(`/api/membership/${id}`, {',
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ status: next })",
    "      }).catch(() => null);",
    "    }",
    "    setWorking(false);",
    "    router.refresh();",
    "  }",
    "",
    "  return (",
    '    <p className="stack">',
    '      {status === "pending" ? (',
    '        <button className="button primary" type="button" disabled={working} onClick={() => void update("member")}>Welcome them in</button>',
    "      ) : (",
    '        <button className="button" type="button" disabled={working} onClick={() => void update("pending")}>Revoke the badge</button>',
    "      )}",
    '      <button className="button" type="button" disabled={working} onClick={() => void update("remove")}>Remove</button>',
    "    </p>",
    "  );",
    "}"
  ]);
}

export const membershipRegistryModule: AppModule = {
  slug: "membership-registry",
  name: "Membership Registry & Verifiable Badge",
  tier: "optional",
  featureFlagEnv: "FEATURE_MEMBERSHIP",
  files: (ctx: AppModuleContext) => [
    membershipLibFile(ctx),
    membershipApiFile(),
    membershipDetailApiFile(),
    badgeRouteFile(),
    joinFormFile(),
    joinPageFile(ctx),
    membersPageFile(),
    memberPageFile(ctx),
    queuePageFile(),
    queueActionsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists membership_registry_organizations (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null,",
      "  org_type text not null default 'other',",
      "  website text not null default '',",
      "  contact_name text not null default '',",
      "  contact_email text not null default '',",
      "  message text not null default '',",
      "  status text not null default 'pending',",
      "  slug text not null unique,",
      "  created_at timestamptz not null default now(),",
      "  joined_at timestamptz",
      ");",
      "create index if not exists membership_registry_orgs_status_idx on membership_registry_organizations (status, joined_at);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into membership_registry_organizations (name, org_type, website, contact_name, contact_email, status, slug, joined_at) values",
      "  ('First Sample Fellowship', 'church', 'https://example.org', 'Sample Contact', 'sample@example.org', 'member', 'first-sample-fellowship', now())",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Membership Registry — set to false to switch the membership program off.",
    "# APP_URL (or AUTH_URL) is used as the origin in embeddable badge snippets.",
    "FEATURE_MEMBERSHIP=true"
  ],
  homeLinks: () => [
    '        <a className="button" href="/join">Join free</a>',
    '        <a className="button" href="/members">Members</a>'
  ],
  navLinks: () => [
    { href: "/members", label: "Members" },
    { href: "/join", label: "Join" }
  ]
};
