// mentorship-coaching — one-on-one guidance/coaching sessions that end with ONE
// small, sized "commitment" (a specific next step), then follow up next time to
// ask how it went. Ported from Kindred-Connection's real code:
//   - backend/routers/coaching.py — the whole "Coaching with Covenants" model:
//     * coaching_sessions / coaching_messages / covenants collections
//     * _get_or_open_session (reuse the user's one open session, else open one)
//     * _check_throttle (5 coach turns / 7 rolling days, 429 at cap)
//     * the four honest response paths did_it | retry | defer | decline
//       (respond_to_covenant): did_it→done, retry→stays open + attempts++ + new
//       7-day runway, defer→"give me something easier", decline→pivot
//     * _decline_streak / pattern naming: 3 declines in a theme → gently name it
//     * _readiness_hint (confidence × willingness → baby-step / modest / real)
//     * _extract_proposed_covenant ("COVENANT: ..." line → a button)
//     * /coaching/state one-shot (open commitments w/ overdue flag, weekly budget,
//       surfaced pattern)
//   - ChurchConnect backend/routes/counselor.py — the per-person guidance view +
//     counselor notes (note_type general|session|follow_up|concern) an authorized
//     mentor keeps about the person they walk with.
// Generalized off Kindred's Christian/"covenant"/Scripture framing into plain,
// warm coaching copy ("commitment", "mentor", "check-in") so it drops into any app.
// The Claude/LLM turn is replaced with a deterministic, offline coach reply +
// readiness-sized suggestion so the module needs no external key. Runs on the app
// owner's own database with graceful sample-data fallback, feature-flagged
// (FEATURE_MENTORSHIP); customers coach + respond, admins/mentors keep notes.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/mentorship.ts (model + queries, ported from coaching.py) -----

function mentorshipLibFile(): GeneratedModuleFile {
  return file("src/lib/db/mentorship.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A coaching session is a private, multi-turn thread. A user has at most one",
    '// OPEN session at a time (ported from coaching.py _get_or_open_session).',
    "export type CoachingSession = {",
    "  id: string;",
    "  userId: string;",
    '  status: "open" | "closed";',
    "  openedAt: string;",
    "  lastMessageAt: string | null;",
    "};",
    "",
    'export type CoachRole = "user" | "coach";',
    "",
    "export type CoachingMessage = {",
    "  id: string;",
    "  sessionId: string;",
    "  role: CoachRole;",
    "  content: string;",
    "  proposedCommitment: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "// The four honest response paths, ported verbatim from coaching.py",
    "// respond_to_covenant: celebrate / carry over without shame / smaller version /",
    "// pivot the area entirely.",
    'export type CommitmentPath = "did_it" | "retry" | "defer" | "decline";',
    'export const COMMITMENT_PATHS: CommitmentPath[] = ["did_it", "retry", "defer", "decline"];',
    "",
    'export type CommitmentStatus = "open" | "did_it" | "deferred" | "decline";',
    "",
    "export type Commitment = {",
    "  id: string;",
    "  userId: string;",
    "  sessionId: string | null;",
    "  action: string;",
    "  theme: string | null;",
    "  status: CommitmentStatus;",
    "  attempts: number;",
    "  createdAt: string;",
    "  dueAt: string | null;",
    "  resolvedAt: string | null;",
    "  overdue?: boolean;",
    "};",
    "",
    "// 5 coach turns / 7 rolling days (coaching.py _check_throttle free-tier cap).",
    "export const WEEKLY_TURN_LIMIT = 5;",
    "",
    "function daysFromNow(days: number): string {",
    "  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();",
    "}",
    "",
    "// Readiness calibration, ported from coaching.py _readiness_hint: confidence ×",
    "// willingness (each 1..5) averaged → baby-step / modest / real challenge tier.",
    'export type ReadinessTier = "baby_step" | "modest" | "real";',
    "export function readinessTier(confidence?: number | null, willingness?: number | null): ReadinessTier {",
    '  if (confidence == null || willingness == null) return "modest";',
    "  const avg = (confidence + willingness) / 2;",
    '  if (avg <= 2.0) return "baby_step";',
    '  if (avg <= 3.5) return "modest";',
    '  return "real";',
    "}",
    "",
    "// A deterministic, offline coach reply + one readiness-sized suggested next step,",
    "// standing in for coaching.py's Claude turn (no external key required). The reply",
    "// asks ONE thing and proposes ONE commitment — never a list of three (the",
    "// avoidance trap coaching.py warns about). The suggestion line is what the API",
    "// surfaces as a 'proposed commitment' button, mirroring _extract_proposed_covenant.",
    "const SUGGESTIONS: Record<ReadinessTier, string[]> = {",
    "  baby_step: [",
    '    "Spend three quiet minutes with this before you do anything else.",',
    '    "Send one short, honest message to someone about it this week.",',
    '    "Write one sentence about what you actually want here."',
    "  ],",
    "  modest: [",
    '    "Have one honest conversation about this before the week is out.",',
    '    "Take one small concrete step toward it and note how it felt.",',
    '    "Show up once to something low-pressure that moves this forward."',
    "  ],",
    "  real: [",
    '    "Have the hard conversation you have been putting off this week.",',
    '    "Take the visible step here — the one that costs a little.",',
    '    "Commit to one thing others can see, and follow through."',
    "  ]",
    "};",
    "",
    "export type CoachTurnResult = { reply: string; proposedCommitment: string | null; patternNamed: boolean };",
    "",
    "// Compose the coach's reply from the user's message + readiness + any observed",
    "// pattern. Ported in spirit from coaching.py _system_prompt + coaching_turn: when a",
    "// pattern is present, name it gently and DO NOT propose a commitment this turn.",
    "export function composeCoachReply(userMessage: string, tier: ReadinessTier, patternNote: string | null): CoachTurnResult {",
    "  const trimmed = userMessage.trim();",
    "  const first = trimmed.length > 140 ? trimmed.slice(0, 140).trim() + \"…\" : trimmed;",
    "  if (patternNote) {",
    "    return {",
    "      reply:",
    '        `I want to name something gently before we go further. ${patternNote} ` +',
    '        "There\'s no shame in it — but the pattern is real. Is there something underneath this that\'s hard to look at? " +',
    '        "Take your time. We don\'t need a next step today.",',
    "      proposedCommitment: null,",
    "      patternNamed: true",
    "    };",
    "  }",
    "  const bank = SUGGESTIONS[tier];",
    "  const pick = bank[Math.abs(hashString(first)) % bank.length];",
    "  const reply =",
    '    `Thank you for saying that. I hear you when you say "${first}". ` +',
    '    "Let\'s not solve everything at once — one honest step is worth more than three good intentions. " +',
    "    `Here's one thing to try: ${pick}`;",
    "  return { reply, proposedCommitment: pick, patternNamed: false };",
    "}",
    "",
    "function hashString(value: string): number {",
    "  let h = 0;",
    "  for (let i = 0; i < value.length; i += 1) {",
    "    h = (h * 31 + value.charCodeAt(i)) | 0;",
    "  }",
    "  return h;",
    "}",
    "",
    "// ---- fallback sample data (no DB) ------------------------------------------",
    "",
    "const fallbackSession: CoachingSession = {",
    '  id: "sample-session-1",',
    '  userId: "sample-user",',
    '  status: "open",',
    "  openedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),",
    "  lastMessageAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()",
    "};",
    "",
    "const fallbackCommitments: Commitment[] = [",
    '  { id: "sample-c1", userId: "sample-user", sessionId: "sample-session-1", action: "Send one honest message to a friend I have been avoiding.", theme: "connection", status: "open", attempts: 1, createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), dueAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), resolvedAt: null }',
    "];",
    "",
    "function rowToSession(row: Record<string, unknown>): CoachingSession {",
    "  return {",
    "    id: String(row.id),",
    '    userId: String(row.user_id || ""),',
    '    status: String(row.status || "open") === "closed" ? "closed" : "open",',
    '    openedAt: String(row.opened_at || ""),',
    "    lastMessageAt: row.last_message_at != null ? String(row.last_message_at) : null",
    "  };",
    "}",
    "",
    "function rowToMessage(row: Record<string, unknown>): CoachingMessage {",
    "  return {",
    "    id: String(row.id),",
    '    sessionId: String(row.session_id || ""),',
    '    role: String(row.role || "user") === "coach" ? "coach" : "user",',
    '    content: String(row.content || ""),',
    "    proposedCommitment: row.proposed_commitment != null ? String(row.proposed_commitment) : null,",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "function rowToCommitment(row: Record<string, unknown>): Commitment {",
    "  const status = String(row.status || \"open\");",
    "  const dueAt = row.due_at != null ? String(row.due_at) : null;",
    "  return {",
    "    id: String(row.id),",
    '    userId: String(row.user_id || ""),',
    "    sessionId: row.session_id != null ? String(row.session_id) : null,",
    '    action: String(row.action || ""),',
    "    theme: row.theme != null && String(row.theme).trim() ? String(row.theme) : null,",
    '    status: (["open", "did_it", "deferred", "decline"].includes(status) ? status : "open") as CommitmentStatus,',
    "    attempts: Number(row.attempts || 1),",
    '    createdAt: String(row.created_at || ""),',
    "    dueAt,",
    "    resolvedAt: row.resolved_at != null ? String(row.resolved_at) : null,",
    "    overdue: Boolean(dueAt && dueAt < new Date().toISOString() && status === \"open\")",
    "  };",
    "}",
    "",
    "// Reuse the user's one open session, else open a new one (coaching.py",
    "// _get_or_open_session).",
    "export async function getOrOpenSession(userId: string): Promise<CoachingSession> {",
    "  if (!hasDatabase()) return fallbackSession;",
    "  const sql = getDatabase();",
    "  const open = await sql`select id, user_id, status, opened_at, last_message_at from mentorship_sessions where user_id = ${userId} and status = 'open' order by opened_at desc limit 1`;",
    "  if (open[0]) return rowToSession(open[0]);",
    "  const created = await sql`insert into mentorship_sessions (user_id, status) values (${userId}, 'open') returning id, user_id, status, opened_at, last_message_at`;",
    "  return rowToSession(created[0]);",
    "}",
    "",
    "// 5 user turns per rolling 7 days (coaching.py _check_throttle).",
    "export async function turnsUsedThisWeek(userId: string): Promise<number> {",
    "  if (!hasDatabase()) return 1;",
    "  try {",
    "    const sql = getDatabase();",
    "    const cutoff = daysFromNow(-7);",
    "    const rows = await sql`select count(*)::int as c from mentorship_messages where user_id = ${userId} and role = 'user' and created_at >= ${cutoff}`;",
    "    return Number(rows[0]?.c || 0);",
    "  } catch {",
    "    return 0;",
    "  }",
    "}",
    "",
    "export async function listSessionMessages(sessionId: string): Promise<CoachingMessage[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, session_id, role, content, proposed_commitment, created_at from mentorship_messages where session_id = ${sessionId} order by created_at asc limit 500`;",
    "    return rows.map(rowToMessage);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Consecutive declines in a theme, most-recent backward (coaching.py",
    "// _decline_streak). A streak of 3+ is the trigger to gently name the pattern.",
    "export async function declineStreak(userId: string, theme: string | null): Promise<number> {",
    "  if (!theme || !hasDatabase()) return 0;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select status from mentorship_commitments where user_id = ${userId} and theme = ${theme} order by created_at desc limit 20`;",
    "    let streak = 0;",
    "    for (const r of rows) {",
    '      if (String(r.status) === "decline") streak += 1;',
    "      else break;",
    "    }",
    "    return streak;",
    "  } catch {",
    "    return 0;",
    "  }",
    "}",
    "",
    "// Find any theme where the user has declined 3+ in a row → a pattern note",
    "// (coaching.py coaching_turn pattern-detection loop).",
    "export async function findPatternNote(userId: string, firstName: string): Promise<string | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const themes = await sql`select distinct theme from mentorship_commitments where user_id = ${userId} and status = 'decline' and theme is not null`;",
    "    for (const t of themes) {",
    "      const theme = t.theme != null ? String(t.theme) : null;",
    "      if (!theme) continue;",
    "      const streak = await declineStreak(userId, theme);",
    "      if (streak >= 3) {",
    "        return `This is at least the third time ${firstName || \"you\"} have stepped away from a commitment around \\u201c${theme}\\u201d.`;",
    "      }",
    "    }",
    "    return null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Take a user message, store it, compose + store the coach reply. Enforces the",
    "// weekly throttle. Ported from coaching.py coaching_turn.",
    "export type TurnOutcome = {",
    "  ok: boolean;",
    "  message?: string;",
    "  sessionId?: string;",
    "  reply?: string;",
    "  proposedCommitment?: string | null;",
    "  patternNamed?: boolean;",
    "  turnsUsedThisWeek?: number;",
    "  turnsLimit?: number;",
    "};",
    "",
    "export async function coachingTurn(userId: string, firstName: string, content: string, tier: ReadinessTier): Promise<TurnOutcome> {",
    "  const text = content.trim();",
    '  if (text.length < 1) return { ok: false, message: "Please write something first." };',
    "  if (!hasDatabase()) {",
    "    const composed = composeCoachReply(text, tier, null);",
    '    return { ok: true, sessionId: fallbackSession.id, reply: composed.reply, proposedCommitment: composed.proposedCommitment, patternNamed: false, turnsUsedThisWeek: 1, turnsLimit: WEEKLY_TURN_LIMIT };',
    "  }",
    "  const used = await turnsUsedThisWeek(userId);",
    "  if (used >= WEEKLY_TURN_LIMIT) {",
    "    return {",
    "      ok: false,",
    '      message: "You\'ve used all " + WEEKLY_TURN_LIMIT + " coaching turns this week. Rest and come back in a few days — sometimes the next step becomes clear in the quiet.",',
    "      turnsUsedThisWeek: used,",
    "      turnsLimit: WEEKLY_TURN_LIMIT",
    "    };",
    "  }",
    "  const sql = getDatabase();",
    "  const session = await getOrOpenSession(userId);",
    "  const patternNote = await findPatternNote(userId, firstName);",
    "  await sql`insert into mentorship_messages (user_id, session_id, role, content) values (${userId}, ${session.id}, 'user', ${text})`;",
    "  const composed = composeCoachReply(text, tier, patternNote);",
    "  await sql`insert into mentorship_messages (user_id, session_id, role, content, proposed_commitment) values (${userId}, ${session.id}, 'coach', ${composed.reply}, ${composed.proposedCommitment})`;",
    "  await sql`update mentorship_sessions set last_message_at = now() where id = ${session.id}`;",
    "  return {",
    "    ok: true,",
    "    sessionId: session.id,",
    "    reply: composed.reply,",
    "    proposedCommitment: composed.proposedCommitment,",
    "    patternNamed: composed.patternNamed,",
    "    turnsUsedThisWeek: used + 1,",
    "    turnsLimit: WEEKLY_TURN_LIMIT",
    "  };",
    "}",
    "",
    "// User accepts a commitment (coaching.py create_covenant): one specific action,",
    "// optional theme, a 7-day runway.",
    "export async function createCommitment(userId: string, action: string, theme: string | null): Promise<Commitment | null> {",
    "  const cleanAction = action.trim();",
    "  if (cleanAction.length < 3) return null;",
    "  const cleanTheme = theme && theme.trim() ? theme.trim().toLowerCase() : null;",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const session = await getOrOpenSession(userId);",
    "    const dueAt = daysFromNow(7);",
    "    const rows = await sql`insert into mentorship_commitments (user_id, session_id, action, theme, status, attempts, due_at) values (${userId}, ${session.id}, ${cleanAction}, ${cleanTheme}, 'open', 1, ${dueAt}) returning id, user_id, session_id, action, theme, status, attempts, created_at, due_at, resolved_at`;",
    "    return rows[0] ? rowToCommitment(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Open commitments with an overdue flag (coaching.py _open_covenants + state).",
    "export async function listOpenCommitments(userId: string): Promise<Commitment[]> {",
    "  if (!hasDatabase()) return fallbackCommitments;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, session_id, action, theme, status, attempts, created_at, due_at, resolved_at from mentorship_commitments where user_id = ${userId} and status = 'open' order by created_at asc limit 20`;",
    "    return rows.map(rowToCommitment);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function listAllCommitments(userId: string): Promise<Commitment[]> {",
    "  if (!hasDatabase()) return fallbackCommitments;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, user_id, session_id, action, theme, status, attempts, created_at, due_at, resolved_at from mentorship_commitments where user_id = ${userId} order by created_at desc limit 200`;",
    "    return rows.map(rowToCommitment);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type RespondOutcome = { ok: boolean; message?: string; status?: CommitmentStatus; attempts?: number; patternNamed?: boolean };",
    "",
    "// Respond to a commitment, ported from coaching.py respond_to_covenant:",
    "//   did_it → done; retry → stays open, attempts++, fresh 7-day runway (not a guilt",
    "//   trip); defer → deferred (\"give me something easier\"); decline → decline (pivot).",
    "//   A decline that makes a 3-in-a-row streak in a theme flags patternNamed.",
    "export async function respondToCommitment(userId: string, commitmentId: string, path: CommitmentPath): Promise<RespondOutcome> {",
    '  if (!COMMITMENT_PATHS.includes(path)) return { ok: false, message: "Unknown response." };',
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to track commitments." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, theme, status, attempts from mentorship_commitments where id = ${commitmentId} and user_id = ${userId} limit 1`;",
    "    const cov = rows[0];",
    '    if (!cov) return { ok: false, message: "Not found." };',
    '    if (String(cov.status) !== "open") return { ok: false, message: "This commitment is already resolved." };',
    "    const theme = cov.theme != null ? String(cov.theme) : null;",
    "    const attempts = Number(cov.attempts || 1);",
    '    if (path === "retry") {',
    "      const dueAt = daysFromNow(7);",
    "      await sql`update mentorship_commitments set attempts = ${attempts + 1}, due_at = ${dueAt}, status = 'open', resolved_at = null where id = ${commitmentId}`;",
    '      return { ok: true, status: "open", attempts: attempts + 1, patternNamed: false };',
    "    }",
    '    const newStatus: CommitmentStatus = path === "did_it" ? "did_it" : path === "defer" ? "deferred" : "decline";',
    "    await sql`update mentorship_commitments set status = ${newStatus}, resolved_at = now() where id = ${commitmentId}`;",
    "    let patternNamed = false;",
    '    if (newStatus === "decline" && theme) {',
    "      const streak = await declineStreak(userId, theme);",
    "      if (streak >= 3) patternNamed = true;",
    "    }",
    "    return { ok: true, status: newStatus, attempts, patternNamed };",
    "  } catch {",
    '    return { ok: false, message: "Could not save that right now." };',
    "  }",
    "}",
    "",
    "// Per-theme pattern summary + the single most-actionable surfaced pattern,",
    "// ported from coaching.py covenants_patterns. 3+ declines → 'decline'; 3+ made",
    "// with none completed → 'stuck'.",
    "export type ThemeSummary = { theme: string; total: number; didIt: number; open: number; deferred: number; decline: number };",
    "export type SurfacedPattern = { theme: string; kind: \"decline\" | \"stuck\"; message: string };",
    "",
    "export async function commitmentPatterns(userId: string): Promise<{ themes: ThemeSummary[]; surfaced: SurfacedPattern | null }> {",
    "  if (!hasDatabase()) return { themes: [], surfaced: null };",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select theme,",
    "        count(*)::int as total,",
    "        sum(case when status = 'did_it' then 1 else 0 end)::int as did_it,",
    "        sum(case when status = 'open' then 1 else 0 end)::int as open,",
    "        sum(case when status = 'deferred' then 1 else 0 end)::int as deferred,",
    "        sum(case when status = 'decline' then 1 else 0 end)::int as decline",
    "      from mentorship_commitments",
    "      where user_id = ${userId} and theme is not null",
    "      group by theme",
    "      order by total desc`;",
    "    const themes: ThemeSummary[] = rows.map((r) => ({",
    "      theme: String(r.theme),",
    "      total: Number(r.total || 0),",
    "      didIt: Number(r.did_it || 0),",
    "      open: Number(r.open || 0),",
    "      deferred: Number(r.deferred || 0),",
    "      decline: Number(r.decline || 0)",
    "    }));",
    "    let surfaced: SurfacedPattern | null = null;",
    "    for (const r of themes) {",
    "      if (r.decline >= 3) {",
    '        surfaced = { theme: r.theme, kind: "decline", message: `You\'ve stepped away from ${r.decline} commitments around \\u201c${r.theme}\\u201d. There\'s no shame in that — but it\'s worth talking through.` };',
    "        break;",
    "      }",
    "      if (r.total >= 3 && r.didIt === 0) {",
    '        surfaced = { theme: r.theme, kind: "stuck", message: `You\'ve made ${r.total} commitments around \\u201c${r.theme}\\u201d and none have closed yet. That\'s a place worth bringing into coaching.` };',
    "        break;",
    "      }",
    "    }",
    "    return { themes, surfaced };",
    "  } catch {",
    "    return { themes: [], surfaced: null };",
    "  }",
    "}",
    "",
    "// ---- Mentor notes (ChurchConnect counselor.py per-person view) --------------",
    "",
    'export type MentorNoteType = "general" | "session" | "follow_up" | "concern";',
    'export const MENTOR_NOTE_TYPES: MentorNoteType[] = ["general", "session", "follow_up", "concern"];',
    "",
    "export type MentorNote = {",
    "  id: string;",
    "  personId: string;",
    "  mentorId: string | null;",
    "  noteType: MentorNoteType;",
    "  content: string;",
    "  followUpDate: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "function rowToNote(row: Record<string, unknown>): MentorNote {",
    "  const noteType = String(row.note_type || \"general\");",
    "  return {",
    "    id: String(row.id),",
    '    personId: String(row.person_id || ""),',
    "    mentorId: row.mentor_id != null ? String(row.mentor_id) : null,",
    '    noteType: (["general", "session", "follow_up", "concern"].includes(noteType) ? noteType : "general") as MentorNoteType,',
    '    content: String(row.content || ""),',
    "    followUpDate: row.follow_up_date != null ? String(row.follow_up_date) : null,",
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "// Notes a mentor keeps about a person they walk with (counselor.py get_counselor_notes).",
    "export async function listMentorNotes(personId: string): Promise<MentorNote[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, person_id, mentor_id, note_type, content, follow_up_date, created_at from mentorship_notes where person_id = ${personId} order by created_at desc limit 200`;",
    "    return rows.map(rowToNote);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Add a mentor note (counselor.py add_counselor_note).",
    "export async function addMentorNote(personId: string, mentorId: string, noteType: MentorNoteType, content: string, followUpDate: string | null): Promise<boolean> {",
    "  const clean = content.trim();",
    "  if (clean.length < 1) return false;",
    '  const type: MentorNoteType = MENTOR_NOTE_TYPES.includes(noteType) ? noteType : "general";',
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into mentorship_notes (person_id, mentor_id, note_type, content, follow_up_date) values (${personId}, ${mentorId}, ${type}, ${clean}, ${followUpDate})`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// One-shot state for the coaching page (coaching.py /coaching/state).",
    "export type CoachingState = {",
    "  sessionId: string;",
    "  openCommitments: Commitment[];",
    "  turnsUsedThisWeek: number;",
    "  turnsLimit: number;",
    "  surfaced: SurfacedPattern | null;",
    "};",
    "",
    "export async function coachingState(userId: string): Promise<CoachingState> {",
    "  const session = await getOrOpenSession(userId);",
    "  const [openCommitments, used, patterns] = await Promise.all([",
    "    listOpenCommitments(userId),",
    "    turnsUsedThisWeek(userId),",
    "    commitmentPatterns(userId)",
    "  ]);",
    "  return {",
    "    sessionId: session.id,",
    "    openCommitments,",
    "    turnsUsedThisWeek: used,",
    "    turnsLimit: WEEKLY_TURN_LIMIT,",
    "    surfaced: patterns.surfaced",
    "  };",
    "}",
    "",
    "export function mentorshipEnabled(): boolean {",
    '  return process.env.FEATURE_MENTORSHIP !== "false";',
    "}"
  ]);
}

// ---- src/app/api/mentorship/turn/route.ts -----------------------------------

function turnApiFile(): GeneratedModuleFile {
  return file("src/app/api/mentorship/turn/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { coachingTurn, readinessTier, mentorshipEnabled } from "@/lib/db/mentorship";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(request: Request) {",
    '  if (!mentorshipEnabled()) return NextResponse.json({ ok: false, message: "Coaching is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const content = typeof body.content === "string" ? body.content : "";',
    '  const confidence = typeof body.confidence === "number" ? body.confidence : null;',
    '  const willingness = typeof body.willingness === "number" ? body.willingness : null;',
    "  const tier = readinessTier(confidence, willingness);",
    '  const userId = String(user?.email || "");',
    '  const firstName = String(user?.name || user?.email || "Friend").split(" ")[0];',
    "  const outcome = await coachingTurn(userId, firstName, content, tier);",
    "  if (!outcome.ok) {",
    '    const status = (outcome.turnsUsedThisWeek || 0) >= (outcome.turnsLimit || 5) ? 429 : 400;',
    "    return NextResponse.json(outcome, { status });",
    "  }",
    "  return NextResponse.json(outcome);",
    "}"
  ]);
}

// ---- src/app/api/mentorship/commitments/route.ts ----------------------------

function commitmentsApiFile(): GeneratedModuleFile {
  return file("src/app/api/mentorship/commitments/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listOpenCommitments, createCommitment, mentorshipEnabled } from "@/lib/db/mentorship";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!mentorshipEnabled()) return NextResponse.json({ ok: false, message: "Coaching is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    '  const commitments = await listOpenCommitments(String(user?.email || ""));',
    "  return NextResponse.json({ ok: true, commitments });",
    "}",
    "",
    "export async function POST(request: Request) {",
    '  if (!mentorshipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "";',
    '  const theme = typeof body.theme === "string" ? body.theme : null;',
    '  if (action.trim().length < 3) return NextResponse.json({ ok: false, message: "Write the step you\'re committing to." }, { status: 400 });',
    '  const commitment = await createCommitment(String(user?.email || ""), action, theme);',
    '  if (!commitment) return NextResponse.json({ ok: false, message: "Connect a database to save commitments." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, commitment });",
    "}"
  ]);
}

// ---- src/app/api/mentorship/commitments/[id]/route.ts (respond) -------------

function commitmentRespondApiFile(): GeneratedModuleFile {
  return file("src/app/api/mentorship/commitments/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { respondToCommitment, mentorshipEnabled, COMMITMENT_PATHS, type CommitmentPath } from "@/lib/db/mentorship";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!mentorshipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const path = typeof body.path === "string" ? body.path : "";',
    '  if (!COMMITMENT_PATHS.includes(path as CommitmentPath)) {',
    '    return NextResponse.json({ ok: false, message: "path must be did_it, retry, defer, or decline." }, { status: 400 });',
    "  }",
    '  const result = await respondToCommitment(String(user?.email || ""), id, path as CommitmentPath);',
    '  if (!result.ok) return NextResponse.json(result, { status: 400 });',
    "  return NextResponse.json(result);",
    "}"
  ]);
}

// ---- src/app/api/mentorship/notes/[id]/route.ts (mentor notes, admin) -------

function notesApiFile(): GeneratedModuleFile {
  return file("src/app/api/mentorship/notes/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listMentorNotes, addMentorNote, mentorshipEnabled, MENTOR_NOTE_TYPES, type MentorNoteType } from "@/lib/db/mentorship";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!mentorshipEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Mentors only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const notes = await listMentorNotes(id);",
    "  return NextResponse.json({ ok: true, notes });",
    "}",
    "",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Mentors only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const content = typeof body.content === "string" ? body.content : "";',
    '  const rawType = typeof body.noteType === "string" ? body.noteType : "general";',
    '  const noteType = (MENTOR_NOTE_TYPES.includes(rawType as MentorNoteType) ? rawType : "general") as MentorNoteType;',
    '  const followUpDate = typeof body.followUpDate === "string" && body.followUpDate.trim() ? body.followUpDate.trim() : null;',
    '  if (content.trim().length < 1) return NextResponse.json({ ok: false, message: "Write a note first." }, { status: 400 });',
    '  const saved = await addMentorNote(id, String(user.email || ""), noteType, content, followUpDate);',
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save notes." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/mentorship/page.tsx (coach chat + commitments) -----------------

function mentorshipPageFile(): GeneratedModuleFile {
  return file("src/app/mentorship/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { coachingState, listSessionMessages, mentorshipEnabled } from "@/lib/db/mentorship";',
    'import { CoachChat } from "./coach-chat";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MentorshipPage() {",
    "  if (!mentorshipEnabled()) {",
    '    return (<main className="shell"><h1>Coaching</h1><p>Coaching is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mentorship");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.email ? String(user.email) : "";',
    '  const state = userId ? await coachingState(userId) : { sessionId: "", openCommitments: [], turnsUsedThisWeek: 0, turnsLimit: 5, surfaced: null };',
    "  const history = state.sessionId ? await listSessionMessages(state.sessionId) : [];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Coaching</p>',
    "      <h1>Your next small step</h1>",
    "      <p>This is a private, one-on-one space. We talk it through, and when the time is right we land on ONE small commitment — not a to-do list. Next time, we pick up with how it went.</p>",
    "      {state.surfaced ? (",
    '        <section className="panel" aria-live="polite">',
    '          <p className="eyebrow">Something we’ve noticed</p>',
    "          <p>{state.surfaced.message}</p>",
    "        </section>",
    "      ) : null}",
    "      <CoachChat",
    "        initialMessages={history.map((m) => ({ role: m.role, content: m.content, proposedCommitment: m.proposedCommitment }))}",
    "        openCommitments={state.openCommitments.map((c) => ({ id: c.id, action: c.action, attempts: c.attempts, overdue: Boolean(c.overdue) }))}",
    "        turnsUsedThisWeek={state.turnsUsedThisWeek}",
    "        turnsLimit={state.turnsLimit}",
    "      />",
    '      <p><Link className="button" href="/mentorship/commitments">See all my commitments</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mentorship/coach-chat.tsx (client) -----------------------------

function coachChatFile(): GeneratedModuleFile {
  return file("src/app/mentorship/coach-chat.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    'type Msg = { role: "user" | "coach"; content: string; proposedCommitment: string | null };',
    "type OpenCommitment = { id: string; action: string; attempts: number; overdue: boolean };",
    "",
    "export function CoachChat({",
    "  initialMessages,",
    "  openCommitments,",
    "  turnsUsedThisWeek,",
    "  turnsLimit",
    "}: {",
    "  initialMessages: Msg[];",
    "  openCommitments: OpenCommitment[];",
    "  turnsUsedThisWeek: number;",
    "  turnsLimit: number;",
    "}) {",
    "  const router = useRouter();",
    "  const [messages, setMessages] = useState<Msg[]>(initialMessages);",
    '  const [draft, setDraft] = useState("");',
    "  const [used, setUsed] = useState(turnsUsedThisWeek);",
    "  const [proposed, setProposed] = useState<string | null>(null);",
    '  const [status, setStatus] = useState<"idle" | "sending" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  const atLimit = used >= turnsLimit;",
    "",
    "  async function send(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    const content = draft.trim();",
    "    if (!content) return;",
    '    setStatus("sending");',
    '    setMessage("");',
    "    setMessages((prev) => [...prev, { role: \"user\", content, proposedCommitment: null }]);",
    '    setDraft("");',
    "    try {",
    '      const response = await fetch("/api/mentorship/turn", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ content })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        if (typeof data.turnsUsedThisWeek === \"number\") setUsed(data.turnsUsedThisWeek);",
    "        return;",
    "      }",
    "      setMessages((prev) => [...prev, { role: \"coach\", content: data.reply, proposedCommitment: data.proposedCommitment || null }]);",
    "      setProposed(data.proposedCommitment || null);",
    "      if (typeof data.turnsUsedThisWeek === \"number\") setUsed(data.turnsUsedThisWeek);",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  async function acceptCommitment(action: string) {",
    "    try {",
    '      const response = await fetch("/api/mentorship/commitments", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save that commitment.");',
    "        return;",
    "      }",
    "      setProposed(null);",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function respond(id: string, path: string) {",
    "    try {",
    "      const response = await fetch(`/api/mentorship/commitments/${id}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ path })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save that.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <section className="stack">',
    "      {openCommitments.length > 0 ? (",
    '        <div className="panel">',
    "          <h2>Last time you said you would…</h2>",
    "          {openCommitments.map((c) => (",
    '            <div className="wide-card" key={c.id}>',
    "              <strong>{c.action}</strong>",
    "              {c.overdue ? <span className=\"note\">A little overdue — that's okay.</span> : null}",
    '              <div className="stack">',
    '                <button className="button primary" type="button" onClick={() => respond(c.id, "did_it")}>I did it</button>',
    '                <button className="button" type="button" onClick={() => respond(c.id, "retry")}>Still working on it</button>',
    '                <button className="button" type="button" onClick={() => respond(c.id, "defer")}>Give me something easier</button>',
    '                <button className="button" type="button" onClick={() => respond(c.id, "decline")}>This isn’t for me right now</button>',
    "              </div>",
    "            </div>",
    "          ))}",
    "        </div>",
    "      ) : null}",
    "",
    '      <div className="panel-list" aria-live="polite">',
    "        {messages.length === 0 ? (",
    '          <p className="note">Start wherever you are. What’s on your mind this week?</p>',
    "        ) : (",
    "          messages.map((m, i) => (",
    '            <div className={m.role === "coach" ? "wide-card" : "card"} key={i}>',
    '              <span>{m.role === "coach" ? "Coach" : "You"}</span>',
    "              <p>{m.content}</p>",
    "            </div>",
    "          ))",
    "        )}",
    "      </div>",
    "",
    "      {proposed ? (",
    '        <div className="panel">',
    "          <p><strong>Ready to commit to this?</strong></p>",
    "          <p>{proposed}</p>",
    '          <button className="button primary" type="button" onClick={() => acceptCommitment(proposed)}>Yes, I commit to this</button>',
    "        </div>",
    "      ) : null}",
    "",
    "      {atLimit ? (",
    '        <p className="note">You’ve used all {turnsLimit} coaching turns this week. Rest and come back in a few days — sometimes the next step becomes clear in the quiet.</p>',
    "      ) : (",
    '        <form className="stack" onSubmit={send}>',
    '          <label htmlFor="coach-draft">Say what’s true right now</label>',
    '          <textarea id="coach-draft" className="input" rows={3} value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="What’s on your mind?" />',
    '          <button className="button primary" type="submit" disabled={status === "sending" || !draft.trim()}>',
    '            {status === "sending" ? "Sending…" : `Talk it through (${turnsLimit - used} left this week)`}',
    "          </button>",
    "        </form>",
    "      )}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </section>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mentorship/commitments/page.tsx (all commitments) --------------

function commitmentsPageFile(): GeneratedModuleFile {
  return file("src/app/mentorship/commitments/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listAllCommitments, commitmentPatterns, mentorshipEnabled } from "@/lib/db/mentorship";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "const STATUS_LABEL: Record<string, string> = {",
    '  open: "In progress",',
    '  did_it: "Done",',
    '  deferred: "Made easier",',
    '  decline: "Pivoted"',
    "};",
    "",
    "export default async function CommitmentsPage() {",
    "  if (!mentorshipEnabled()) {",
    '    return (<main className="shell"><h1>Coaching</h1><p>Coaching is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mentorship/commitments");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.email ? String(user.email) : "";',
    "  const [commitments, patterns] = userId",
    "    ? await Promise.all([listAllCommitments(userId), commitmentPatterns(userId)])",
    "    : [[], { themes: [], surfaced: null }];",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Coaching</p>',
    "      <h1>Your commitments</h1>",
    "      <p>Every small step you’ve taken on, and where each one landed. Faithfulness in small things counts.</p>",
    "      {patterns.themes.length > 0 ? (",
    '        <section className="grid">',
    "          {patterns.themes.map((t) => (",
    '            <article className="card" key={t.theme}>',
    "              <span>{t.theme}</span>",
    "              <strong>{t.didIt} of {t.total} done</strong>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      ) : null}",
    "      {commitments.length === 0 ? (",
    '        <p className="note">No commitments yet. Head to <Link href="/mentorship">coaching</Link> to talk through your next small step.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {commitments.map((c) => (",
    '            <article className="wide-card" key={c.id}>',
    "              <span>{STATUS_LABEL[c.status] || c.status}{c.attempts > 1 ? ` · attempt ${c.attempts}` : \"\"}</span>",
    "              <strong>{c.action}</strong>",
    "              {c.theme ? <p className=\"note\">{c.theme}</p> : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/mentorship">Back to coaching</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const mentorshipCoachingModule: AppModule = {
  slug: "mentorship-coaching",
  name: "Mentorship & Coaching",
  tier: "optional",
  featureFlagEnv: "FEATURE_MENTORSHIP",
  files: () => [
    mentorshipLibFile(),
    turnApiFile(),
    commitmentsApiFile(),
    commitmentRespondApiFile(),
    notesApiFile(),
    mentorshipPageFile(),
    coachChatFile(),
    commitmentsPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists mentorship_sessions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  status text not null default 'open',",
      "  opened_at timestamptz not null default now(),",
      "  last_message_at timestamptz",
      ");",
      "create index if not exists mentorship_sessions_user_idx on mentorship_sessions (user_id, status);",
      "",
      "create table if not exists mentorship_messages (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  session_id uuid not null references mentorship_sessions(id) on delete cascade,",
      "  role text not null default 'user',",
      "  content text not null,",
      "  proposed_commitment text,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mentorship_messages_session_idx on mentorship_messages (session_id, created_at);",
      "create index if not exists mentorship_messages_turn_idx on mentorship_messages (user_id, role, created_at);",
      "",
      "create table if not exists mentorship_commitments (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  session_id uuid references mentorship_sessions(id) on delete set null,",
      "  action text not null,",
      "  theme text,",
      "  status text not null default 'open',",
      "  attempts integer not null default 1,",
      "  created_at timestamptz not null default now(),",
      "  due_at timestamptz,",
      "  resolved_at timestamptz",
      ");",
      "create index if not exists mentorship_commitments_user_idx on mentorship_commitments (user_id, status);",
      "create index if not exists mentorship_commitments_theme_idx on mentorship_commitments (user_id, theme);",
      "",
      "create table if not exists mentorship_notes (",
      "  id uuid primary key default gen_random_uuid(),",
      "  person_id uuid not null references users(id) on delete cascade,",
      "  mentor_id uuid references users(id) on delete set null,",
      "  note_type text not null default 'general',",
      "  content text not null,",
      "  follow_up_date timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mentorship_notes_person_idx on mentorship_notes (person_id, created_at);"
    ].join("\n"),
  envLines: () => [
    "",
    "# Mentorship & Coaching — set to false to switch coaching sessions + commitments off.",
    "FEATURE_MENTORSHIP=true"
  ],
  homeLinks: () => ['        <a className="button" href="/mentorship">Coaching</a>'],
  navLinks: () => [{ href: "/mentorship", label: "Coaching" }]
};