// multi-org-association — manage many organizations under one association, with
// per-org profiles and association-level rollups. Ported from the real "Church
// Association" product (Association repo):
//   - src/components/AssociationManagement.tsx — the association record (name,
//     slug, primary_contact_*, address/city/state/zip, subscription_tier,
//     subscription_status, active_churches_count, pricing_discount_percentage,
//     monthly_price, is_free_tier, churches_needed_for_next_tier,
//     next_tier_discount_percentage) + the rollup cards (total associations, total
//     member orgs, free/partner tier count, total MRR) + the tier badge + the
//     add-association form + search.
//   - supabase/migrations/20251113173900_create_complete_three_tier_system.sql —
//     the incentive pricing ladder (association_pricing_tiers: Starter 0-4 / 0%,
//     Growth 5-9 / 10%, Professional 10-14 / 25%, Premium 15-19 / 50%, Partner
//     20+ / 100% free), the base $49 price, and calculate_association_pricing_tier
//     (count active member orgs → pick the tier by min/max churches → derive
//     discount %, monthly price = round(49 * (1 - discount/100)), is_free, and the
//     "N more orgs → next discount%" incentive). Ported verbatim into TS.
//   - src/components/ChurchManagement.tsx — the member-org record
//     (church_organizations: name, primary_contact_email, subscription_status,
//     subscription_tier) linked to an association via church_associations, the
//     add-org flow, and per-org detail.
//   - src/components/ChurchProfileFields.tsx — custom per-org profile fields
//     (field_name, field_label, field_type, is_required, display_order, help_text)
//     that an association defines to collect specific info from its member orgs.
// Generalized off the church framing into plain "association / organization" copy
// so it drops into any app. Runs on the app owner's own database with graceful
// sample-data fallback, feature-flagged (FEATURE_MULTI_ORG); the signed-in owner
// manages their own associations (rows scoped to user.id), admins see all.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/multi-org.ts (model + queries + tier logic) -----------------

function multiOrgLibFile(): GeneratedModuleFile {
  return file("src/lib/db/multi-org.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// An association, ported from AssociationManagement.tsx's Association interface",
    "// + the associations table: identity (name/slug), a primary contact, an address,",
    "// and the subscription/incentive rollup (tier, active member-org count, discount,",
    "// monthly price, is_free_tier, and the 'N more orgs to next tier' incentive).",
    "export type Association = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  slug: string;",
    "  primaryContactName: string;",
    "  primaryContactEmail: string;",
    "  primaryContactPhone: string;",
    "  address: string;",
    "  city: string;",
    "  state: string;",
    "  zipCode: string;",
    "  subscriptionTier: string;",
    "  subscriptionStatus: string;",
    "  activeOrgsCount: number;",
    "  pricingDiscountPercentage: number;",
    "  monthlyPrice: number;",
    "  isFreeTier: boolean;",
    "  orgsNeededForNextTier: number | null;",
    "  nextTierDiscountPercentage: number | null;",
    "  createdAt: string;",
    "};",
    "",
    "// A member organization under an association, ported from ChurchManagement.tsx +",
    "// church_organizations: identity + a primary contact + its own subscription",
    "// status/tier. Linked to exactly one association (church_associations UNIQUE).",
    "export type MemberOrg = {",
    "  id: string;",
    "  associationId: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  primaryContactName: string;",
    "  primaryContactEmail: string;",
    "  primaryContactPhone: string;",
    "  subscriptionStatus: string;",
    "  subscriptionTier: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A custom per-org profile field an association defines, ported from",
    "// ChurchProfileFields.tsx's CustomField (association_custom_fields).",
    "export type ProfileField = {",
    "  id: string;",
    "  associationId: string;",
    "  fieldName: string;",
    "  fieldLabel: string;",
    "  fieldType: string;",
    "  isRequired: boolean;",
    "  displayOrder: number;",
    "  helpText: string;",
    "};",
    "",
    'export const PROFILE_FIELD_TYPES = ["text", "textarea", "number", "date", "email", "phone", "url", "dropdown", "checkbox"];',
    "",
    "export const ORG_SUBSCRIPTION_STATUSES = [\"active\", \"inactive\", \"trial\", \"suspended\"];",
    "",
    "// The incentive pricing ladder, ported VERBATIM from the association_pricing_tiers",
    "// seed in create_complete_three_tier_system.sql: the more member orgs an",
    "// association brings, the deeper the discount — reaching Partner (free) at 20+.",
    "export type PricingTier = { name: string; minOrgs: number; maxOrgs: number | null; discountPercentage: number; isFree: boolean };",
    "",
    "export const PRICING_TIERS: PricingTier[] = [",
    '  { name: "Starter", minOrgs: 0, maxOrgs: 4, discountPercentage: 0, isFree: false },',
    '  { name: "Growth", minOrgs: 5, maxOrgs: 9, discountPercentage: 10, isFree: false },',
    '  { name: "Professional", minOrgs: 10, maxOrgs: 14, discountPercentage: 25, isFree: false },',
    '  { name: "Premium", minOrgs: 15, maxOrgs: 19, discountPercentage: 50, isFree: false },',
    '  { name: "Partner", minOrgs: 20, maxOrgs: null, discountPercentage: 100, isFree: true }',
    "];",
    "",
    "// The base monthly price before any incentive discount, ported from the tier",
    "// function's ROUND(49.00 * (1 - discount/100), 2).",
    "export const BASE_MONTHLY_PRICE = 49.0;",
    "",
    "// A url-friendly slug, ported from AssociationManagement's",
    "// value.toLowerCase().replace(/\\s+/g, '-').",
    "export function slugify(value: string): string {",
    '  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "association";',
    "}",
    "",
    "// The full incentive computation, ported verbatim from",
    "// calculate_association_pricing_tier: given the active member-org count, pick the",
    "// tier by min/max, derive the discount %, the monthly price, is_free, and how",
    "// many more orgs reach the next tier (+ that tier's discount).",
    "export type TierComputation = {",
    "  tier: string;",
    "  discountPercentage: number;",
    "  monthlyPrice: number;",
    "  isFreeTier: boolean;",
    "  orgsNeededForNextTier: number | null;",
    "  nextTierDiscountPercentage: number | null;",
    "};",
    "",
    "export function computeTier(activeOrgCount: number): TierComputation {",
    "  // Pick the highest tier whose min <= count and (max is null or max >= count),",
    "  // mirroring 'ORDER BY min_churches DESC LIMIT 1'.",
    "  const current = PRICING_TIERS",
    "    .filter((t) => t.minOrgs <= activeOrgCount && (t.maxOrgs === null || t.maxOrgs >= activeOrgCount))",
    "    .sort((a, b) => b.minOrgs - a.minOrgs)[0] || PRICING_TIERS[0];",
    "  // The next tier up, mirroring 'WHERE min_churches > count ORDER BY min_churches ASC LIMIT 1'.",
    "  const next = PRICING_TIERS",
    "    .filter((t) => t.minOrgs > activeOrgCount)",
    "    .sort((a, b) => a.minOrgs - b.minOrgs)[0];",
    "  const monthlyPrice = current.isFree",
    "    ? 0",
    "    : Math.round(BASE_MONTHLY_PRICE * (1 - current.discountPercentage / 100) * 100) / 100;",
    "  return {",
    "    tier: current.name,",
    "    discountPercentage: current.discountPercentage,",
    "    monthlyPrice,",
    "    isFreeTier: current.isFree,",
    "    orgsNeededForNextTier: next ? next.minOrgs - activeOrgCount : null,",
    "    nextTierDiscountPercentage: next ? next.discountPercentage : null",
    "  };",
    "}",
    "",
    "// Sample associations for when no database is connected (graceful fallback).",
    "const fallbackAssociations: Association[] = [",
    "  {",
    '    id: "sample-assoc-1",',
    "    ownerId: null,",
    '    name: "Riverside Network",',
    '    slug: "riverside-network",',
    '    primaryContactName: "Dana Ellis",',
    '    primaryContactEmail: "dana@riverside.example.com",',
    '    primaryContactPhone: "(555) 100-2000",',
    '    address: "12 River Rd",',
    '    city: "Springfield",',
    '    state: "IL",',
    '    zipCode: "62701",',
    '    subscriptionTier: "Growth",',
    '    subscriptionStatus: "active",',
    "    activeOrgsCount: 6,",
    "    pricingDiscountPercentage: 10,",
    "    monthlyPrice: 44.1,",
    "    isFreeTier: false,",
    "    orgsNeededForNextTier: 4,",
    "    nextTierDiscountPercentage: 25,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-assoc-2",',
    "    ownerId: null,",
    '    name: "Coastal Partners",',
    '    slug: "coastal-partners",',
    '    primaryContactName: "Sam Ortega",',
    '    primaryContactEmail: "sam@coastal.example.com",',
    '    primaryContactPhone: "",',
    '    address: "",',
    '    city: "Savannah",',
    '    state: "GA",',
    '    zipCode: "",',
    '    subscriptionTier: "Partner",',
    '    subscriptionStatus: "active",',
    "    activeOrgsCount: 22,",
    "    pricingDiscountPercentage: 100,",
    "    monthlyPrice: 0,",
    "    isFreeTier: true,",
    "    orgsNeededForNextTier: null,",
    "    nextTierDiscountPercentage: null,",
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackOrgs: MemberOrg[] = [",
    "  {",
    '    id: "sample-org-1",',
    '    associationId: "sample-assoc-1",',
    "    ownerId: null,",
    '    name: "First Community",',
    '    primaryContactName: "Pat Lin",',
    '    primaryContactEmail: "pat@firstcommunity.example.com",',
    '    primaryContactPhone: "",',
    '    subscriptionStatus: "active",',
    '    subscriptionTier: "basic",',
    '    createdAt: "2025-01-05T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-org-2",',
    '    associationId: "sample-assoc-1",',
    "    ownerId: null,",
    '    name: "Grace Fellowship",',
    '    primaryContactName: "Robin Vale",',
    '    primaryContactEmail: "robin@grace.example.com",',
    '    primaryContactPhone: "",',
    '    subscriptionStatus: "active",',
    '    subscriptionTier: "basic",',
    '    createdAt: "2025-01-06T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackFields: ProfileField[] = [",
    "  {",
    '    id: "sample-field-1",',
    '    associationId: "sample-assoc-1",',
    '    fieldName: "weekly_attendance",',
    '    fieldLabel: "Weekly Attendance",',
    '    fieldType: "number",',
    "    isRequired: false,",
    "    displayOrder: 0,",
    '    helpText: "Average people attending each week"',
    "  }",
    "];",
    "",
    "function rowToAssociation(row: Record<string, unknown>): Association {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    name: String(row.name || ""),',
    '    slug: String(row.slug || ""),',
    '    primaryContactName: String(row.primary_contact_name || ""),',
    '    primaryContactEmail: String(row.primary_contact_email || ""),',
    '    primaryContactPhone: String(row.primary_contact_phone || ""),',
    '    address: String(row.address || ""),',
    '    city: String(row.city || ""),',
    '    state: String(row.state || ""),',
    '    zipCode: String(row.zip_code || ""),',
    '    subscriptionTier: String(row.subscription_tier || "Starter"),',
    '    subscriptionStatus: String(row.subscription_status || "active"),',
    "    activeOrgsCount: Number(row.active_orgs_count || 0),",
    "    pricingDiscountPercentage: Number(row.pricing_discount_percentage || 0),",
    "    monthlyPrice: Number(row.monthly_price || 0),",
    '    isFreeTier: row.is_free_tier === true || String(row.is_free_tier) === "true",',
    "    orgsNeededForNextTier: row.orgs_needed_for_next_tier != null ? Number(row.orgs_needed_for_next_tier) : null,",
    "    nextTierDiscountPercentage: row.next_tier_discount_percentage != null ? Number(row.next_tier_discount_percentage) : null,",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToOrg(row: Record<string, unknown>): MemberOrg {",
    "  return {",
    "    id: String(row.id),",
    "    associationId: String(row.association_id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    name: String(row.name || ""),',
    '    primaryContactName: String(row.primary_contact_name || ""),',
    '    primaryContactEmail: String(row.primary_contact_email || ""),',
    '    primaryContactPhone: String(row.primary_contact_phone || ""),',
    '    subscriptionStatus: String(row.subscription_status || "active"),',
    '    subscriptionTier: String(row.subscription_tier || "basic"),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToField(row: Record<string, unknown>): ProfileField {",
    "  return {",
    "    id: String(row.id),",
    "    associationId: String(row.association_id),",
    '    fieldName: String(row.field_name || ""),',
    '    fieldLabel: String(row.field_label || ""),',
    '    fieldType: String(row.field_type || "text"),',
    '    isRequired: row.is_required === true || String(row.is_required) === "true",',
    "    displayOrder: Number(row.display_order || 0),",
    '    helpText: String(row.help_text || "")',
    "  };",
    "}",
    "",
    "export type AssociationFilters = { q?: string; ownerId?: string; limit?: number };",
    "",
    "// List + search associations, ported from AssociationManagement's",
    "// filteredAssociations (match name / primary_contact_email); newest first,",
    "// mirroring the .order('created_at', { ascending: false }) load. Scoped to an",
    "// owner when ownerId is given.",
    "export async function listAssociations(filters: AssociationFilters = {}): Promise<Association[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackAssociations",
    "      .filter((a) => !ownerId || a.ownerId === ownerId)",
    '      .filter((a) => !q || (a.name + " " + a.primaryContactEmail).toLowerCase().includes(q))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, name, slug, primary_contact_name, primary_contact_email,",
    "        primary_contact_phone, address, city, state, zip_code, subscription_tier,",
    "        subscription_status, active_orgs_count, pricing_discount_percentage,",
    "        monthly_price, is_free_tier, orgs_needed_for_next_tier,",
    "        next_tier_discount_percentage, created_at",
    "      from multi_org_association_associations",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${like}::text is null",
    "          or lower(name) like ${like}",
    "          or lower(primary_contact_email) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToAssociation);",
    "  } catch {",
    "    return fallbackAssociations.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getAssociation(id: string): Promise<Association | null> {",
    "  if (!hasDatabase()) return fallbackAssociations.find((a) => a.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, name, slug, primary_contact_name, primary_contact_email,",
    "        primary_contact_phone, address, city, state, zip_code, subscription_tier,",
    "        subscription_status, active_orgs_count, pricing_discount_percentage,",
    "        monthly_price, is_free_tier, orgs_needed_for_next_tier,",
    "        next_tier_discount_percentage, created_at",
    "      from multi_org_association_associations where id = ${id} limit 1`;",
    "    return rows[0] ? rowToAssociation(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateAssociationInput = {",
    "  ownerId: string | null;",
    "  name: string;",
    "  slug?: string;",
    "  primaryContactName?: string;",
    "  primaryContactEmail?: string;",
    "  primaryContactPhone?: string;",
    "  address?: string;",
    "  city?: string;",
    "  state?: string;",
    "  zipCode?: string;",
    "};",
    "",
    "// Create an association, ported from AssociationManagement's handleSubmit insert.",
    "// A brand-new association has zero member orgs, so its tier starts at Starter with",
    "// the base price (computeTier(0)) — the same starting point the SQL trigger lands.",
    "export async function createAssociation(input: CreateAssociationInput): Promise<Association | null> {",
    "  if (!hasDatabase()) return null;",
    "  const slug = slugify(input.slug || input.name);",
    "  const tier = computeTier(0);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into multi_org_association_associations (",
    "        owner_id, name, slug, primary_contact_name, primary_contact_email,",
    "        primary_contact_phone, address, city, state, zip_code,",
    "        subscription_tier, subscription_status, active_orgs_count,",
    "        pricing_discount_percentage, monthly_price, is_free_tier,",
    "        orgs_needed_for_next_tier, next_tier_discount_percentage",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.name}, ${slug},",
    '        ${input.primaryContactName || ""}, ${input.primaryContactEmail || ""},',
    '        ${input.primaryContactPhone || ""}, ${input.address || ""},',
    '        ${input.city || ""}, ${input.state || ""}, ${input.zipCode || ""},',
    '        ${tier.tier}, ${"active"}, ${0},',
    "        ${tier.discountPercentage}, ${tier.monthlyPrice}, ${tier.isFreeTier},",
    "        ${tier.orgsNeededForNextTier}, ${tier.nextTierDiscountPercentage}",
    "      )",
    "      returning id, owner_id, name, slug, primary_contact_name, primary_contact_email,",
    "        primary_contact_phone, address, city, state, zip_code, subscription_tier,",
    "        subscription_status, active_orgs_count, pricing_discount_percentage,",
    "        monthly_price, is_free_tier, orgs_needed_for_next_tier,",
    "        next_tier_discount_percentage, created_at`;",
    "    return rows[0] ? rowToAssociation(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Recalculate an association's tier from its live member-org count, ported from",
    "// calculate_association_pricing_tier: count active orgs, computeTier, and write the",
    "// rollup fields back. Called whenever an org is added/updated/removed (the SQL",
    "// trigger's job, done here in application code).",
    "export async function recalcAssociationTier(associationId: string): Promise<Association | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    // Count active member orgs, mirroring the trigger's status IN ('active','trial').",
    "    const countRows = await sql`",
    "      select count(*)::int as n from multi_org_association_member_orgs",
    "      where association_id = ${associationId}",
    "        and subscription_status in ('active', 'trial')`;",
    "    const activeCount = Number(countRows[0]?.n || 0);",
    "    const tier = computeTier(activeCount);",
    "    const rows = await sql`",
    "      update multi_org_association_associations set",
    "        active_orgs_count = ${activeCount},",
    "        subscription_tier = ${tier.tier},",
    "        pricing_discount_percentage = ${tier.discountPercentage},",
    "        monthly_price = ${tier.monthlyPrice},",
    "        is_free_tier = ${tier.isFreeTier},",
    "        orgs_needed_for_next_tier = ${tier.orgsNeededForNextTier},",
    "        next_tier_discount_percentage = ${tier.nextTierDiscountPercentage},",
    "        updated_at = now()",
    "      where id = ${associationId}",
    "      returning id, owner_id, name, slug, primary_contact_name, primary_contact_email,",
    "        primary_contact_phone, address, city, state, zip_code, subscription_tier,",
    "        subscription_status, active_orgs_count, pricing_discount_percentage,",
    "        monthly_price, is_free_tier, orgs_needed_for_next_tier,",
    "        next_tier_discount_percentage, created_at`;",
    "    return rows[0] ? rowToAssociation(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- Member orgs (ported from ChurchManagement.tsx) ------------------------",
    "",
    "export async function listMemberOrgs(associationId: string, limit = 200): Promise<MemberOrg[]> {",
    "  const cap = Math.min(500, Math.max(1, limit));",
    "  if (!hasDatabase()) return fallbackOrgs.filter((o) => o.associationId === associationId).slice(0, cap);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, association_id, owner_id, name, primary_contact_name,",
    "        primary_contact_email, primary_contact_phone, subscription_status,",
    "        subscription_tier, created_at",
    "      from multi_org_association_member_orgs",
    "      where association_id = ${associationId}",
    "      order by created_at desc limit ${cap}`;",
    "    return rows.map(rowToOrg);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function getMemberOrg(id: string): Promise<MemberOrg | null> {",
    "  if (!hasDatabase()) return fallbackOrgs.find((o) => o.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, association_id, owner_id, name, primary_contact_name,",
    "        primary_contact_email, primary_contact_phone, subscription_status,",
    "        subscription_tier, created_at",
    "      from multi_org_association_member_orgs where id = ${id} limit 1`;",
    "    return rows[0] ? rowToOrg(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateOrgInput = {",
    "  associationId: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  primaryContactName?: string;",
    "  primaryContactEmail?: string;",
    "  primaryContactPhone?: string;",
    "  subscriptionStatus?: string;",
    "};",
    "",
    "// Add a member org under an association, ported from ChurchManagement's add flow.",
    "// After inserting we recalc the association's tier (the church_associations",
    "// trigger's effect) so the rollup + incentive stay in sync.",
    "export async function createMemberOrg(input: CreateOrgInput): Promise<MemberOrg | null> {",
    "  if (!hasDatabase()) return null;",
    '  const status = ORG_SUBSCRIPTION_STATUSES.includes(input.subscriptionStatus || "") ? input.subscriptionStatus : "active";',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into multi_org_association_member_orgs (",
    "        association_id, owner_id, name, primary_contact_name,",
    "        primary_contact_email, primary_contact_phone, subscription_status",
    "      ) values (",
    "        ${input.associationId}, ${input.ownerId || null}, ${input.name},",
    '        ${input.primaryContactName || ""}, ${input.primaryContactEmail || ""},',
    '        ${input.primaryContactPhone || ""}, ${status}',
    "      )",
    "      returning id, association_id, owner_id, name, primary_contact_name,",
    "        primary_contact_email, primary_contact_phone, subscription_status,",
    "        subscription_tier, created_at`;",
    "    const created = rows[0] ? rowToOrg(rows[0]) : null;",
    "    if (created) await recalcAssociationTier(input.associationId);",
    "    return created;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Set a member org's subscription status, ported from ChurchManagement's",
    "// saveChurchEdit / toggle-status. Because the active count can change, we recalc",
    "// the parent association's tier afterward.",
    "export async function setOrgStatus(id: string, status: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    '  if (!ORG_SUBSCRIPTION_STATUSES.includes(status)) return false;',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update multi_org_association_member_orgs set subscription_status = ${status}, updated_at = now()",
    "      where id = ${id} returning association_id`;",
    "    if (!rows[0]) return false;",
    "    await recalcAssociationTier(String(rows[0].association_id));",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Remove a member org, ported from ChurchManagement's delete; recalc after.",
    "export async function deleteMemberOrg(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      delete from multi_org_association_member_orgs where id = ${id} returning association_id`;",
    "    if (!rows[0]) return false;",
    "    await recalcAssociationTier(String(rows[0].association_id));",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Custom profile fields (ported from ChurchProfileFields.tsx) -----------",
    "",
    "export async function listProfileFields(associationId: string): Promise<ProfileField[]> {",
    "  if (!hasDatabase()) return fallbackFields.filter((f) => f.associationId === associationId);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, association_id, field_name, field_label, field_type,",
    "        is_required, display_order, help_text",
    "      from multi_org_association_profile_fields",
    "      where association_id = ${associationId}",
    "      order by display_order asc`;",
    "    return rows.map(rowToField);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type CreateFieldInput = {",
    "  associationId: string;",
    "  fieldName: string;",
    "  fieldLabel: string;",
    "  fieldType?: string;",
    "  isRequired?: boolean;",
    "  helpText?: string;",
    "};",
    "",
    "// Add a custom profile field, ported from ChurchProfileFields' handleSaveField",
    "// insert: field_name is normalised to snake_case, display_order is the next slot.",
    "export async function createProfileField(input: CreateFieldInput): Promise<ProfileField | null> {",
    "  if (!hasDatabase()) return null;",
    '  const fieldName = input.fieldName.trim().toLowerCase().replace(/\\s+/g, "_");',
    '  const fieldType = PROFILE_FIELD_TYPES.includes(input.fieldType || "") ? input.fieldType : "text";',
    "  try {",
    "    const sql = getDatabase();",
    "    const orderRows = await sql`",
    "      select coalesce(max(display_order), -1) + 1 as next from multi_org_association_profile_fields",
    "      where association_id = ${input.associationId}`;",
    "    const displayOrder = Number(orderRows[0]?.next || 0);",
    "    const rows = await sql`",
    "      insert into multi_org_association_profile_fields (",
    "        association_id, field_name, field_label, field_type, is_required, display_order, help_text",
    "      ) values (",
    "        ${input.associationId}, ${fieldName}, ${input.fieldLabel}, ${fieldType},",
    '        ${input.isRequired === true}, ${displayOrder}, ${input.helpText || ""}',
    "      )",
    "      returning id, association_id, field_name, field_label, field_type,",
    "        is_required, display_order, help_text`;",
    "    return rows[0] ? rowToField(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Delete a custom profile field, ported from ChurchProfileFields' handleDeleteField.",
    "export async function deleteProfileField(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from multi_org_association_profile_fields where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// The association-level rollup, ported from AssociationManagement's summary cards:",
    "// total associations, total member orgs across them, how many are on the free",
    "// (Partner) tier, and total monthly recurring revenue.",
    "export type AssociationRollup = {",
    "  totalAssociations: number;",
    "  totalMemberOrgs: number;",
    "  freeTierCount: number;",
    "  totalMonthlyRevenue: number;",
    "};",
    "",
    "export function rollup(associations: Association[]): AssociationRollup {",
    "  return {",
    "    totalAssociations: associations.length,",
    "    totalMemberOrgs: associations.reduce((sum, a) => sum + a.activeOrgsCount, 0),",
    "    freeTierCount: associations.filter((a) => a.isFreeTier).length,",
    "    totalMonthlyRevenue: Math.round(associations.reduce((sum, a) => sum + (a.monthlyPrice || 0), 0) * 100) / 100",
    "  };",
    "}",
    "",
    "export function multiOrgEnabled(): boolean {",
    '  return process.env.FEATURE_MULTI_ORG !== "false";',
    "}"
  ]);
}

// ---- src/app/api/associations/route.ts (list + create) ----------------------

function associationsApiFile(): GeneratedModuleFile {
  return file("src/app/api/associations/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listAssociations, createAssociation, rollup, multiOrgEnabled } from "@/lib/db/multi-org";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!multiOrgEnabled()) return NextResponse.json({ ok: false, message: "Association management is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  // Customers see only their own associations; admins see every association.",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    '  const associations = await listAssociations({ q: url.searchParams.get("q") || undefined, ownerId });',
    "  return NextResponse.json({ ok: true, associations, rollup: rollup(associations) });",
    "}",
    "",
    "// Create an association, ported from AssociationManagement's handleSubmit. Scoped",
    "// to the signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to create an association." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    "  if (name.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give your association a name." }, { status: 400 });',
    "  }",
    "  const created = await createAssociation({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    name,",
    '    slug: typeof body.slug === "string" ? body.slug : undefined,',
    '    primaryContactName: typeof body.primaryContactName === "string" ? body.primaryContactName : undefined,',
    '    primaryContactEmail: typeof body.primaryContactEmail === "string" ? body.primaryContactEmail : undefined,',
    '    primaryContactPhone: typeof body.primaryContactPhone === "string" ? body.primaryContactPhone : undefined,',
    '    address: typeof body.address === "string" ? body.address : undefined,',
    '    city: typeof body.city === "string" ? body.city : undefined,',
    '    state: typeof body.state === "string" ? body.state : undefined,',
    '    zipCode: typeof body.zipCode === "string" ? body.zipCode : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save associations." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, association: created });',
    "}"
  ]);
}

// ---- src/app/api/associations/[id]/route.ts (detail + member orgs) ----------

function associationDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/associations/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getAssociation, listMemberOrgs, createMemberOrg, listProfileFields, multiOrgEnabled } from "@/lib/db/multi-org";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function ownedOr404(id: string, userId: string | undefined, isAdmin: boolean) {",
    "  const association = await getAssociation(id);",
    "  if (!association) return { association: null, denied: false };",
    "  if (!isAdmin && association.ownerId && association.ownerId !== String(userId)) {",
    "    return { association: null, denied: true };",
    "  }",
    "  return { association, denied: false };",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!multiOrgEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const { association } = await ownedOr404(id, user?.id ? String(user.id) : undefined, isAdmin);",
    '  if (!association) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const [orgs, fields] = await Promise.all([listMemberOrgs(association.id), listProfileFields(association.id)]);",
    "  return NextResponse.json({ ok: true, association, orgs, fields });",
    "}",
    "",
    "// Add a member org under this association, ported from ChurchManagement's add flow.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const { association } = await ownedOr404(id, user?.id ? String(user.id) : undefined, isAdmin);",
    '  if (!association) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    "  if (name.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give the organization a name." }, { status: 400 });',
    "  }",
    "  const created = await createMemberOrg({",
    "    associationId: association.id,",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    name,",
    '    primaryContactName: typeof body.primaryContactName === "string" ? body.primaryContactName : undefined,',
    '    primaryContactEmail: typeof body.primaryContactEmail === "string" ? body.primaryContactEmail : undefined,',
    '    primaryContactPhone: typeof body.primaryContactPhone === "string" ? body.primaryContactPhone : undefined,',
    '    subscriptionStatus: typeof body.subscriptionStatus === "string" ? body.subscriptionStatus : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save organizations." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, org: created });',
    "}"
  ]);
}

// ---- src/app/api/associations/[id]/orgs/[orgId]/route.ts (status + delete) --

function orgDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/associations/[id]/orgs/[orgId]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getAssociation, getMemberOrg, setOrgStatus, deleteMemberOrg, multiOrgEnabled } from "@/lib/db/multi-org";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function guard(id: string, orgId: string, userId: string | undefined, isAdmin: boolean) {",
    "  const association = await getAssociation(id);",
    "  if (!association) return { ok: false as const };",
    "  if (!isAdmin && association.ownerId && association.ownerId !== String(userId)) return { ok: false as const };",
    "  const org = await getMemberOrg(orgId);",
    "  if (!org || org.associationId !== association.id) return { ok: false as const };",
    "  return { ok: true as const, org };",
    "}",
    "",
    "// Set a member org's subscription status — this shifts the association's active",
    "// count, so the lib recalculates the incentive tier + MRR afterward.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string; orgId: string }> }) {",
    '  if (!multiOrgEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id, orgId } = await params;",
    "  const guarded = await guard(id, orgId, user?.id ? String(user.id) : undefined, canAccessAdmin(user?.role));",
    '  if (!guarded.ok) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = typeof body.subscriptionStatus === "string" ? body.subscriptionStatus : "";',
    "  const ok = await setOrgStatus(orgId, status);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Could not update this organization." }, { status: 400 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "// Remove a member org from the association — admins only (a destructive rollup",
    "// change). The lib recalculates the tier after deletion.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string; orgId: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id, orgId } = await params;",
    "  const guarded = await guard(id, orgId, user.id ? String(user.id) : undefined, true);",
    '  if (!guarded.ok) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const ok = await deleteMemberOrg(orgId);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Could not remove this organization." }, { status: 400 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/associations/[id]/fields/route.ts (custom fields) ----------

function fieldsApiFile(): GeneratedModuleFile {
  return file("src/app/api/associations/[id]/fields/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getAssociation, listProfileFields, createProfileField, deleteProfileField, multiOrgEnabled } from "@/lib/db/multi-org";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "async function ownedAssociation(id: string, userId: string | undefined, isAdmin: boolean) {",
    "  const association = await getAssociation(id);",
    "  if (!association) return null;",
    "  if (!isAdmin && association.ownerId && association.ownerId !== String(userId)) return null;",
    "  return association;",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!multiOrgEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const association = await ownedAssociation(id, user?.id ? String(user.id) : undefined, canAccessAdmin(user?.role));",
    '  if (!association) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const fields = await listProfileFields(association.id);",
    "  return NextResponse.json({ ok: true, fields });",
    "}",
    "",
    "// Define a custom profile field, ported from ChurchProfileFields' handleSaveField.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const association = await ownedAssociation(id, user?.id ? String(user.id) : undefined, canAccessAdmin(user?.role));",
    '  if (!association) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const fieldLabel = typeof body.fieldLabel === "string" ? body.fieldLabel.trim() : "";',
    '  const fieldName = typeof body.fieldName === "string" ? body.fieldName.trim() : "";',
    "  if (fieldLabel.length < 1 || fieldName.length < 1) {",
    '    return NextResponse.json({ ok: false, message: "A field label and name are required." }, { status: 400 });',
    "  }",
    "  const created = await createProfileField({",
    "    associationId: association.id,",
    "    fieldName,",
    "    fieldLabel,",
    '    fieldType: typeof body.fieldType === "string" ? body.fieldType : undefined,',
    "    isRequired: body.isRequired === true,",
    '    helpText: typeof body.helpText === "string" ? body.helpText : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save fields." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, field: created });",
    "}",
    "",
    "export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const association = await ownedAssociation(id, user?.id ? String(user.id) : undefined, canAccessAdmin(user?.role));",
    '  if (!association) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const url = new URL(request.url);",
    '  const fieldId = url.searchParams.get("fieldId") || "";',
    '  if (!fieldId) return NextResponse.json({ ok: false, message: "Which field?" }, { status: 400 });',
    "  const ok = await deleteProfileField(fieldId);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Could not delete this field." }, { status: 400 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/associations/page.tsx (rollup + list + add) --------------------

function associationsPageFile(): GeneratedModuleFile {
  return file("src/app/associations/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listAssociations, rollup, multiOrgEnabled } from "@/lib/db/multi-org";',
    'import { AddAssociationForm } from "./add-association-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AssociationsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string }>;",
    "}) {",
    "  if (!multiOrgEnabled()) {",
    '    return (<main className="shell"><h1>Associations</h1><p>Association management is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/associations");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const associations = await listAssociations({ q: q || undefined, ownerId });",
    "  const totals = rollup(associations);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Associations</p>',
    "      <h1>Association management</h1>",
    "      <p>Manage many organizations under one association and track your incentive-tier progress. The more member organizations you bring on, the deeper your discount — reaching a free Partner tier at 20.</p>",
    '      <section className="grid">',
    '        <article className="card"><span>Associations</span><strong>{totals.totalAssociations}</strong></article>',
    '        <article className="card"><span>Member orgs</span><strong>{totals.totalMemberOrgs}</strong></article>',
    '        <article className="card"><span>Free (Partner) tier</span><strong>{totals.freeTierCount}</strong></article>',
    '        <article className="card"><span>Monthly revenue</span><strong>${totals.totalMonthlyRevenue.toFixed(2)}</strong></article>',
    "      </section>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search by name or contact email" aria-label="Search associations" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {associations.length === 0 ? (",
    '        <p className="note">{q ? `No associations match "${q}" yet.` : "No associations yet. Create your first one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {associations.map((a) => (",
    '            <Link className="wide-card" key={a.id} href={`/associations/${a.id}`}>',
    '              <span>{a.subscriptionTier}{a.isFreeTier ? " · Partner" : ""}</span>',
    "              <strong>{a.name}</strong>",
    "              {a.primaryContactEmail ? <p>{a.primaryContactEmail}</p> : null}",
    '              <p className="note">',
    '                {`${a.activeOrgsCount} member org${a.activeOrgsCount === 1 ? "" : "s"}`}',
    '                {a.isFreeTier ? " · FREE" : ` · $${a.monthlyPrice.toFixed(2)}/mo`}',
    '                {a.pricingDiscountPercentage > 0 && !a.isFreeTier ? ` · -${a.pricingDiscountPercentage}%` : ""}',
    "              </p>",
    "              {a.orgsNeededForNextTier && a.orgsNeededForNextTier > 0 && a.nextTierDiscountPercentage != null ? (",
    '                <p className="note">{`${a.orgsNeededForNextTier} more org${a.orgsNeededForNextTier === 1 ? "" : "s"} → ${a.nextTierDiscountPercentage}% discount`}</p>',
    "              ) : null}",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Create an association</h2>",
    "      <AddAssociationForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/associations/add-association-form.tsx (client) -----------------

function addAssociationFormFile(): GeneratedModuleFile {
  return file("src/app/associations/add-association-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The add-association form, ported from AssociationManagement's add modal:",
    "// name + slug (auto-derived) + a primary contact + an address.",
    "export function AddAssociationForm() {",
    "  const router = useRouter();",
    '  const [name, setName] = useState("");',
    '  const [slug, setSlug] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  function onName(value: string) {",
    "    setName(value);",
    "    // Auto-slug, ported from the modal's onChange derivation.",
    '    setSlug(value.toLowerCase().replace(/\\s+/g, "-").replace(/[^a-z0-9-]/g, ""));',
    "  }",
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/associations", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          name,",
    "          slug,",
    '          primaryContactName: form.get("primaryContactName"),',
    '          primaryContactEmail: form.get("primaryContactEmail"),',
    '          primaryContactPhone: form.get("primaryContactPhone"),',
    '          address: form.get("address"),',
    '          city: form.get("city"),',
    '          state: form.get("state"),',
    '          zipCode: form.get("zipCode")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Created</p>',
    "        <p>Your association was created. Add member organizations to unlock incentive tiers.</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" value={name} onChange={(e) => onName(e.target.value)} placeholder="Association name" aria-label="Association name" required />',
    '      <input className="input" value={slug} onChange={(e) => setSlug(e.target.value.toLowerCase().replace(/\\s+/g, "-"))} placeholder="url-friendly-slug" aria-label="Slug" required />',
    '      <input className="input" name="primaryContactName" placeholder="Primary contact name" aria-label="Contact name" />',
    '      <input className="input" name="primaryContactEmail" type="email" placeholder="Primary contact email" aria-label="Contact email" />',
    '      <input className="input" name="primaryContactPhone" type="tel" placeholder="Primary contact phone" aria-label="Contact phone" />',
    '      <input className="input" name="address" placeholder="Address" aria-label="Address" />',
    '      <input className="input" name="city" placeholder="City" aria-label="City" />',
    '      <input className="input" name="state" placeholder="State" aria-label="State" />',
    '      <input className="input" name="zipCode" placeholder="Zip code" aria-label="Zip code" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving" || name.trim().length < 2}>',
    '        {status === "saving" ? "Creating…" : "Create association"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/associations/[id]/page.tsx (detail: rollup + orgs + fields) ----

function associationDetailPageFile(): GeneratedModuleFile {
  return file("src/app/associations/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getAssociation, listMemberOrgs, listProfileFields, multiOrgEnabled } from "@/lib/db/multi-org";',
    'import { OrgManager } from "./org-manager";',
    'import { FieldManager } from "./field-manager";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function AssociationDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!multiOrgEnabled()) {",
    '    return (<main className="shell"><h1>Associations</h1><p>Association management is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/associations");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const association = await getAssociation(id);",
    "  if (!association) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && association.ownerId && association.ownerId !== String(user?.id)) notFound();",
    "  const [orgs, fields] = await Promise.all([listMemberOrgs(association.id), listProfileFields(association.id)]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{association.subscriptionTier}{association.isFreeTier ? " · Partner" : ""}</p>',
    "      <h1>{association.name}</h1>",
    "      {association.primaryContactEmail ? (",
    '        <p className="note">{[association.primaryContactName, association.primaryContactEmail].filter(Boolean).join(" · ")}</p>',
    "      ) : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Member orgs</span><strong>{association.activeOrgsCount}</strong></article>',
    '        <article className="card"><span>Monthly price</span><strong>{association.isFreeTier ? "FREE" : `$${association.monthlyPrice.toFixed(2)}`}</strong></article>',
    '        <article className="card"><span>Discount</span><strong>{association.pricingDiscountPercentage}%</strong></article>',
    '        <article className="card"><span>Status</span><strong>{association.subscriptionStatus}</strong></article>',
    "      </section>",
    "      {association.orgsNeededForNextTier && association.orgsNeededForNextTier > 0 && association.nextTierDiscountPercentage != null ? (",
    '        <p className="note" role="status">{`Add ${association.orgsNeededForNextTier} more org${association.orgsNeededForNextTier === 1 ? "" : "s"} to reach a ${association.nextTierDiscountPercentage}% discount.`}</p>',
    "      ) : association.isFreeTier ? (",
    '        <p className="note" role="status">You have reached the free Partner tier. Thank you for growing the network.</p>',
    "      ) : null}",
    "      <h2>Member organizations</h2>",
    "      <p>Each organization you manage under this association. Their active count drives your incentive tier.</p>",
    "      <OrgManager associationId={association.id} orgs={orgs} isAdmin={isAdmin} />",
    "      <h2>Custom profile fields</h2>",
    "      <p>Define the specific information you collect from your member organizations. Standard fields (name, contact, address) are included automatically.</p>",
    "      <FieldManager associationId={association.id} fields={fields} />",
    '      <p><Link className="button" href="/associations">Back to associations</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/associations/[id]/org-manager.tsx (client) ---------------------

function orgManagerFile(): GeneratedModuleFile {
  return file("src/app/associations/[id]/org-manager.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type MemberOrg = {",
    "  id: string;",
    "  name: string;",
    "  primaryContactEmail: string;",
    "  subscriptionStatus: string;",
    "};",
    "",
    'const STATUSES = ["active", "trial", "inactive", "suspended"];',
    "",
    "// Member-org manager, ported from ChurchManagement: list orgs, add a new one,",
    "// change an org's subscription status (which re-tiers the association), and — for",
    "// admins — remove an org.",
    "export function OrgManager({",
    "  associationId,",
    "  orgs,",
    "  isAdmin",
    "}: {",
    "  associationId: string;",
    "  orgs: MemberOrg[];",
    "  isAdmin: boolean;",
    "}) {",
    "  const router = useRouter();",
    '  const [name, setName] = useState("");',
    '  const [email, setEmail] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function addOrg(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/associations/${associationId}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ name, primaryContactEmail: email })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not add this organization.");',
    "        return;",
    "      }",
    '      setName("");',
    '      setEmail("");',
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function changeStatus(orgId: string, next: string) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/associations/${associationId}/orgs/${orgId}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ subscriptionStatus: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this organization.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function removeOrg(orgId: string) {",
    '    if (!confirm("Remove this organization from the association?")) return;',
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/associations/${associationId}/orgs/${orgId}`, { method: \"DELETE\" });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not remove this organization.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      {orgs.length === 0 ? (",
    '        <p className="note">No member organizations yet. Add your first below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {orgs.map((org) => (",
    '            <article className="wide-card" key={org.id}>',
    "              <span>{org.subscriptionStatus}</span>",
    "              <strong>{org.name}</strong>",
    "              {org.primaryContactEmail ? <p>{org.primaryContactEmail}</p> : null}",
    '              <div className="stack">',
    '                <label className="note">Status',
    "                  <select",
    '                    className="input"',
    "                    defaultValue={org.subscriptionStatus}",
    "                    onChange={(e) => changeStatus(org.id, e.target.value)}",
    '                    disabled={status === "working"}',
    '                    aria-label={`Status for ${org.name}`}',
    "                  >",
    "                    {STATUSES.map((s) => (",
    "                      <option key={s} value={s}>{s}</option>",
    "                    ))}",
    "                  </select>",
    "                </label>",
    "                {isAdmin ? (",
    '                  <button className="button" type="button" onClick={() => removeOrg(org.id)} disabled={status === "working"}>Remove</button>',
    "                ) : null}",
    "              </div>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <form className="stack" onSubmit={addOrg}>',
    '        <input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Organization name" aria-label="Organization name" required />',
    '        <input className="input" value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="Primary contact email" aria-label="Organization contact email" />',
    '        {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '        <button className="button primary" type="submit" disabled={status === "working" || name.trim().length < 2}>Add organization</button>',
    "      </form>",
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/associations/[id]/field-manager.tsx (client) -------------------

function fieldManagerFile(): GeneratedModuleFile {
  return file("src/app/associations/[id]/field-manager.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type ProfileField = {",
    "  id: string;",
    "  fieldName: string;",
    "  fieldLabel: string;",
    "  fieldType: string;",
    "  isRequired: boolean;",
    "  helpText: string;",
    "};",
    "",
    'const FIELD_TYPES = ["text", "textarea", "number", "date", "email", "phone", "url", "dropdown", "checkbox"];',
    "",
    "// Custom-field manager, ported from ChurchProfileFields: list defined fields, add",
    "// a new one (label + internal snake_case name + type + required + help text), and",
    "// delete a field.",
    "export function FieldManager({",
    "  associationId,",
    "  fields",
    "}: {",
    "  associationId: string;",
    "  fields: ProfileField[];",
    "}) {",
    "  const router = useRouter();",
    '  const [label, setLabel] = useState("");',
    '  const [fieldName, setFieldName] = useState("");',
    '  const [fieldType, setFieldType] = useState("text");',
    "  const [required, setRequired] = useState(false);",
    '  const [helpText, setHelpText] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  function onLabel(value: string) {",
    "    setLabel(value);",
    "    // Derive the internal snake_case name, ported from ChurchProfileFields.",
    '    if (!fieldName) setFieldName(value.toLowerCase().replace(/\\s+/g, "_").replace(/[^a-z0-9_]/g, ""));',
    "  }",
    "",
    "  async function addField(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/associations/${associationId}/fields`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ fieldLabel: label, fieldName, fieldType, isRequired: required, helpText })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save this field.");',
    "        return;",
    "      }",
    '      setLabel("");',
    '      setFieldName("");',
    '      setFieldType("text");',
    "      setRequired(false);",
    '      setHelpText("");',
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function removeField(fieldId: string) {",
    '    if (!confirm("Delete this field? All data collected for it will be lost.")) return;',
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/associations/${associationId}/fields?fieldId=${encodeURIComponent(fieldId)}`, { method: \"DELETE\" });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not delete this field.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      {fields.length === 0 ? (",
    '        <p className="note">No custom fields yet. Add your first below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {fields.map((field) => (",
    '            <article className="wide-card" key={field.id}>',
    "              <strong>{field.fieldLabel}</strong>",
    '              <p className="note">',
    "                {field.fieldType}",
    '                {field.isRequired ? " · Required" : ""}',
    "              </p>",
    "              {field.helpText ? <p>{field.helpText}</p> : null}",
    '              <button className="button" type="button" onClick={() => removeField(field.id)} disabled={status === "working"}>Delete</button>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <form className="stack" onSubmit={addField}>',
    '        <input className="input" value={label} onChange={(e) => onLabel(e.target.value)} placeholder="Field label (e.g. Weekly Attendance)" aria-label="Field label" required />',
    '        <input className="input" value={fieldName} onChange={(e) => setFieldName(e.target.value.toLowerCase().replace(/\\s+/g, "_"))} placeholder="internal_field_name" aria-label="Internal field name" required />',
    '        <select className="input" value={fieldType} onChange={(e) => setFieldType(e.target.value)} aria-label="Field type">',
    "          {FIELD_TYPES.map((t) => (",
    "            <option key={t} value={t}>{t}</option>",
    "          ))}",
    "        </select>",
    '        <label className="check"><input type="checkbox" checked={required} onChange={(e) => setRequired(e.target.checked)} /> Required field</label>',
    '        <input className="input" value={helpText} onChange={(e) => setHelpText(e.target.value)} placeholder="Help text (optional)" aria-label="Help text" />',
    '        {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '        <button className="button primary" type="submit" disabled={status === "working" || label.trim().length < 1 || fieldName.trim().length < 1}>Add field</button>',
    "      </form>",
    "    </div>",
    "  );",
    "}"
  ]);
}

export const multiOrgModule: AppModule = {
  slug: "multi-org-association",
  name: "Multi-Org Association",
  tier: "optional",
  featureFlagEnv: "FEATURE_MULTI_ORG",
  files: () => [
    multiOrgLibFile(),
    associationsApiFile(),
    associationDetailApiFile(),
    orgDetailApiFile(),
    fieldsApiFile(),
    associationsPageFile(),
    addAssociationFormFile(),
    associationDetailPageFile(),
    orgManagerFile(),
    fieldManagerFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists multi_org_association_associations (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  name text not null default '',",
      "  slug text not null default '',",
      "  primary_contact_name text not null default '',",
      "  primary_contact_email text not null default '',",
      "  primary_contact_phone text not null default '',",
      "  address text not null default '',",
      "  city text not null default '',",
      "  state text not null default '',",
      "  zip_code text not null default '',",
      "  subscription_tier text not null default 'Starter',",
      "  subscription_status text not null default 'active',",
      "  active_orgs_count integer not null default 0,",
      "  pricing_discount_percentage integer not null default 0,",
      "  monthly_price numeric(10,2) not null default 49.00,",
      "  is_free_tier boolean not null default false,",
      "  orgs_needed_for_next_tier integer,",
      "  next_tier_discount_percentage integer,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists multi_org_association_associations_owner_idx on multi_org_association_associations (owner_id);",
      "create index if not exists multi_org_association_associations_tier_idx on multi_org_association_associations (subscription_tier);",
      "create index if not exists multi_org_association_associations_created_idx on multi_org_association_associations (created_at desc);",
      "",
      "create table if not exists multi_org_association_member_orgs (",
      "  id uuid primary key default gen_random_uuid(),",
      "  association_id uuid not null references multi_org_association_associations(id) on delete cascade,",
      "  owner_id uuid references users(id) on delete set null,",
      "  name text not null default '',",
      "  primary_contact_name text not null default '',",
      "  primary_contact_email text not null default '',",
      "  primary_contact_phone text not null default '',",
      "  subscription_status text not null default 'active',",
      "  subscription_tier text not null default 'basic',",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists multi_org_association_member_orgs_association_idx on multi_org_association_member_orgs (association_id);",
      "create index if not exists multi_org_association_member_orgs_status_idx on multi_org_association_member_orgs (subscription_status);",
      "",
      "create table if not exists multi_org_association_profile_fields (",
      "  id uuid primary key default gen_random_uuid(),",
      "  association_id uuid not null references multi_org_association_associations(id) on delete cascade,",
      "  field_name text not null default '',",
      "  field_label text not null default '',",
      "  field_type text not null default 'text',",
      "  is_required boolean not null default false,",
      "  display_order integer not null default 0,",
      "  help_text text not null default '',",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists multi_org_association_profile_fields_association_idx on multi_org_association_profile_fields (association_id, display_order);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- A sample association on the Growth tier (10% discount at 6 member orgs),",
      "-- ported from the Riverside Network fallback + the incentive ladder.",
      "insert into multi_org_association_associations (name, slug, primary_contact_name, primary_contact_email, city, state, subscription_tier, subscription_status, active_orgs_count, pricing_discount_percentage, monthly_price, is_free_tier, orgs_needed_for_next_tier, next_tier_discount_percentage) values",
      "  ('Riverside Network', 'riverside-network', 'Dana Ellis', 'dana@riverside.example.com', 'Springfield', 'IL', 'Growth', 'active', 6, 10, 44.10, false, 4, 25)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Multi-Org Association — set to false to switch association management off.",
    "FEATURE_MULTI_ORG=true"
  ],
  homeLinks: () => ['        <a className="button" href="/associations">Associations</a>'],
  navLinks: () => [{ href: "/associations", label: "Associations" }],
  requiredEnv: []
};
