// mutual-aid-benevolence — a community aid fund with hardship applications,
// benevolence-case review, and transparent stewardship. Ported from
// RebuildingDads' real Brotherhood/Mutual Aid program:
//   - src/components/MutualAidApplication.tsx (the applicant surface: assistance
//     categories, the hardship application form + fields, the applicant's
//     application history, and the fund-stats overview).
//   - src/components/BrotherhoodFundSettings.tsx (the member/stewardship settings:
//     monthly_child_support obligation, the +10% monthly-commitment + 25%
//     tax-savings math, and the mutual_aid_interest participation flag).
//   - supabase/migrations/20251106180619_create_mutual_aid_program_fixed.sql (the
//     real schema: assistance_categories, mutual_aid_fund, mutual_aid_contributions,
//     hardship_applications with its full review workflow + status enum
//     [pending/under_review/approved/denied/disbursed], assistance_grants, and the
//     update_mutual_aid_fund_stats aggregation that keeps the fund totals live).
// Generalized off the fathers-only framing into plain, warm "community aid"
// language so it drops into any app. Runs on the app owner's own database with
// graceful sample-data fallback, feature-flagged (FEATURE_MUTUAL_AID); customers
// browse the fund, apply, and track their own cases, admins review + disburse.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/mutual-aid.ts (model + queries, ported from the migration) ---

function mutualAidLibFile(): GeneratedModuleFile {
  return file("src/lib/db/mutual-aid.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The categories of help available, ported from assistance_categories: a name,",
    "// a description, and a per-category cap (max_amount).",
    "export type AidCategory = {",
    "  id: string;",
    "  name: string;",
    "  description: string;",
    "  maxAmount: number;",
    "  requiresDocumentation: boolean;",
    "  isActive: boolean;",
    "};",
    "",
    "// The status workflow, ported verbatim from hardship_applications.status CHECK",
    "// (pending -> under_review -> approved/denied -> disbursed).",
    "export const AID_STATUSES = [",
    '  "pending",',
    '  "under_review",',
    '  "approved",',
    '  "denied",',
    '  "disbursed"',
    "] as const;",
    "export type AidStatus = (typeof AID_STATUSES)[number];",
    "",
    "// A benevolence case / hardship application, ported from hardship_applications.",
    "export type AidApplication = {",
    "  id: string;",
    "  userId: string | null;",
    "  categoryId: string;",
    "  categoryName: string;",
    "  amountRequested: number;",
    "  situationDescription: string;",
    "  financialImpact: string;",
    "  howAssistanceHelps: string;",
    "  monthlyIncome: number | null;",
    "  monthlyExpenses: number | null;",
    "  childSupportPayment: number | null;",
    "  hasContributed: boolean;",
    "  totalContributed: number;",
    "  status: AidStatus;",
    "  reviewNotes: string;",
    "  denialReason: string;",
    "  amountApproved: number | null;",
    "  reviewedAt: string | null;",
    "  submittedAt: string;",
    "};",
    "",
    "// The transparent fund snapshot, ported from mutual_aid_fund + the",
    "// update_mutual_aid_fund_stats aggregation.",
    "export type FundStats = {",
    "  totalContributions: number;",
    "  totalDisbursed: number;",
    "  currentBalance: number;",
    "  totalContributors: number;",
    "  totalRecipients: number;",
    "  totalApplications: number;",
    "  totalApproved: number;",
    "};",
    "",
    "// The stewardship math, ported from BrotherhoodFundSettings: a member pledges",
    "// their obligation + 10% (operations/hardship reserve), and the charitable",
    "// contribution yields an estimated tax saving. Kept pure so pages can reuse it.",
    "export const OPERATIONS_MARKUP = 1.1; // ported: monthlyChildSupport * 1.1",
    "export const ESTIMATED_TAX_RATE = 0.25; // ported: 25% bracket assumption",
    "",
    "export function monthlyCommitment(obligation: number): number {",
    "  if (!obligation || obligation <= 0) return 0;",
    "  return Math.round(obligation * OPERATIONS_MARKUP * 100) / 100;",
    "}",
    "",
    "export function estimatedTaxSavings(obligation: number): number {",
    "  const commitment = monthlyCommitment(obligation);",
    "  if (commitment === 0) return 0;",
    "  return Math.round(commitment * ESTIMATED_TAX_RATE * 100) / 100;",
    "}",
    "",
    "export function effectiveCost(obligation: number): number {",
    "  return Math.round((monthlyCommitment(obligation) - estimatedTaxSavings(obligation)) * 100) / 100;",
    "}",
    "",
    "export function statusLabel(status: string): string {",
    '  return status.replace(/_/g, " ");',
    "}",
    "",
    "// Sample data so the fund, categories, and a case render before a DB is wired.",
    "const fallbackCategories: AidCategory[] = [",
    '  { id: "cat-legal", name: "Legal Fees", description: "Attorney fees, court costs, and legal documentation.", maxAmount: 5000, requiresDocumentation: true, isActive: true },',
    '  { id: "cat-emergency", name: "Emergency Expenses", description: "Unexpected emergencies (medical, housing, transportation).", maxAmount: 2000, requiresDocumentation: true, isActive: true },',
    '  { id: "cat-children", name: "Child-Related Expenses", description: "Costs for time with children (activities, school supplies).", maxAmount: 1000, requiresDocumentation: true, isActive: true },',
    '  { id: "cat-mental-health", name: "Mental Health Support", description: "Counseling, therapy, and mental health services.", maxAmount: 1500, requiresDocumentation: false, isActive: true },',
    '  { id: "cat-training", name: "Job Training / Education", description: "Skills training, certifications, or education.", maxAmount: 3000, requiresDocumentation: true, isActive: true },',
    '  { id: "cat-transport", name: "Transportation", description: "Vehicle repairs, gas, or transportation costs.", maxAmount: 800, requiresDocumentation: true, isActive: true }',
    "];",
    "",
    "const fallbackFund: FundStats = {",
    "  totalContributions: 12450,",
    "  totalDisbursed: 4800,",
    "  currentBalance: 7650,",
    "  totalContributors: 34,",
    "  totalRecipients: 9,",
    "  totalApplications: 21,",
    "  totalApproved: 12",
    "};",
    "",
    "const fallbackApplications: AidApplication[] = [",
    "  {",
    '    id: "sample-app-1",',
    '    userId: "sample-user",',
    '    categoryId: "cat-emergency",',
    '    categoryName: "Emergency Expenses",',
    "    amountRequested: 750,",
    '    situationDescription: "Car broke down and I need it to get to work and to see my kids.",',
    '    financialImpact: "Missed three shifts this week already; rent is due Friday.",',
    '    howAssistanceHelps: "Covers the repair so I can keep my job and my visitation schedule.",',
    "    monthlyIncome: 2600,",
    "    monthlyExpenses: 2400,",
    "    childSupportPayment: 600,",
    "    hasContributed: true,",
    "    totalContributed: 220,",
    '    status: "under_review",',
    '    reviewNotes: "",',
    '    denialReason: "",',
    "    amountApproved: null,",
    "    reviewedAt: null,",
    '    submittedAt: "2025-03-02T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function num(v: unknown): number { const n = Number(v); return Number.isFinite(n) ? n : 0; }",
    "function numOrNull(v: unknown): number | null { if (v == null) return null; const n = Number(v); return Number.isFinite(n) ? n : null; }",
    "",
    "function rowToCategory(row: Record<string, unknown>): AidCategory {",
    "  return {",
    "    id: String(row.id),",
    '    name: String(row.name || ""),',
    '    description: String(row.description || ""),',
    "    maxAmount: num(row.max_amount),",
    "    requiresDocumentation: row.requires_documentation === true || String(row.requires_documentation) === \"true\",",
    "    isActive: row.is_active === true || String(row.is_active) === \"true\"",
    "  };",
    "}",
    "",
    "function rowToApplication(row: Record<string, unknown>): AidApplication {",
    "  const status = String(row.status || \"pending\");",
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    "    categoryId: row.category_id != null ? String(row.category_id) : \"\",",
    '    categoryName: String(row.category_name || ""),',
    "    amountRequested: num(row.amount_requested),",
    '    situationDescription: String(row.situation_description || ""),',
    '    financialImpact: String(row.financial_impact || ""),',
    '    howAssistanceHelps: String(row.how_assistance_helps || ""),',
    "    monthlyIncome: numOrNull(row.monthly_income),",
    "    monthlyExpenses: numOrNull(row.monthly_expenses),",
    "    childSupportPayment: numOrNull(row.child_support_payment),",
    "    hasContributed: row.has_contributed === true || String(row.has_contributed) === \"true\",",
    "    totalContributed: num(row.total_contributed),",
    "    status: (AID_STATUSES as readonly string[]).includes(status) ? (status as AidStatus) : \"pending\",",
    '    reviewNotes: String(row.review_notes || ""),',
    '    denialReason: String(row.denial_reason || ""),',
    "    amountApproved: numOrNull(row.amount_approved),",
    "    reviewedAt: row.reviewed_at ? String(row.reviewed_at) : null,",
    '    submittedAt: row.submitted_at ? String(row.submitted_at) : ""',
    "  };",
    "}",
    "",
    "// Active categories, ported from the MutualAidApplication loadData query:",
    "// assistance_categories where is_active = true.",
    "export async function listCategories(): Promise<AidCategory[]> {",
    "  if (!hasDatabase()) return fallbackCategories;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, name, description, max_amount, requires_documentation, is_active",
    "      from mutual_aid_benevolence_categories",
    "      where is_active = true",
    "      order by name asc`;",
    "    return rows.map(rowToCategory);",
    "  } catch {",
    "    return fallbackCategories;",
    "  }",
    "}",
    "",
    "export async function getCategory(id: string): Promise<AidCategory | null> {",
    "  if (!hasDatabase()) return fallbackCategories.find((c) => c.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, name, description, max_amount, requires_documentation, is_active from mutual_aid_benevolence_categories where id = ${id} limit 1`;",
    "    return rows[0] ? rowToCategory(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// The live fund snapshot, ported from mutual_aid_fund + update_mutual_aid_fund_stats.",
    "// We compute it on read from contributions + grants + applications so it is always",
    "// correct without the DB triggers the original relied on.",
    "export async function getFundStats(): Promise<FundStats> {",
    "  if (!hasDatabase()) return fallbackFund;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select",
    "        (select coalesce(sum(amount), 0) from mutual_aid_benevolence_contributions) as total_contributions,",
    "        (select coalesce(sum(amount), 0) from mutual_aid_benevolence_grants) as total_disbursed,",
    "        (select count(distinct user_id) from mutual_aid_benevolence_contributions where user_id is not null) as total_contributors,",
    "        (select count(distinct user_id) from mutual_aid_benevolence_grants) as total_recipients,",
    "        (select count(*) from mutual_aid_benevolence_applications) as total_applications,",
    "        (select count(*) from mutual_aid_benevolence_applications where status in ('approved', 'disbursed')) as total_approved`;",
    "    const r = (rows[0] || {}) as Record<string, unknown>;",
    "    const totalContributions = num(r.total_contributions);",
    "    const totalDisbursed = num(r.total_disbursed);",
    "    return {",
    "      totalContributions,",
    "      totalDisbursed,",
    "      currentBalance: Math.round((totalContributions - totalDisbursed) * 100) / 100,",
    "      totalContributors: num(r.total_contributors),",
    "      totalRecipients: num(r.total_recipients),",
    "      totalApplications: num(r.total_applications),",
    "      totalApproved: num(r.total_approved)",
    "    };",
    "  } catch {",
    "    return fallbackFund;",
    "  }",
    "}",
    "",
    "// A member's own contribution total, ported from the contributions reduce in",
    "// MutualAidApplication (has_contributed + total_contributed).",
    "export async function getContributionStatus(userId: string): Promise<{ hasContributed: boolean; totalContributed: number }> {",
    "  if (!hasDatabase()) return { hasContributed: false, totalContributed: 0 };",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select coalesce(sum(amount), 0) as total, count(*) as n from mutual_aid_benevolence_contributions where user_id = ${userId}`;",
    "    const r = (rows[0] || {}) as Record<string, unknown>;",
    "    return { hasContributed: num(r.n) > 0, totalContributed: num(r.total) };",
    "  } catch {",
    "    return { hasContributed: false, totalContributed: 0 };",
    "  }",
    "}",
    "",
    "// An applicant's own case history, ported from the hardship_applications query",
    "// scoped to user_id, newest-first.",
    "export async function listMyApplications(userId: string): Promise<AidApplication[]> {",
    "  if (!hasDatabase()) return fallbackApplications.filter((a) => a.userId === userId || userId === \"sample-user\");",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select a.id, a.user_id, a.category_id, c.name as category_name, a.amount_requested,",
    "        a.situation_description, a.financial_impact, a.how_assistance_helps,",
    "        a.monthly_income, a.monthly_expenses, a.child_support_payment,",
    "        a.has_contributed, a.total_contributed, a.status, a.review_notes,",
    "        a.denial_reason, a.amount_approved, a.reviewed_at, a.submitted_at",
    "      from mutual_aid_benevolence_applications a",
    "      left join mutual_aid_benevolence_categories c on c.id = a.category_id",
    "      where a.user_id = ${userId}",
    "      order by a.submitted_at desc`;",
    "    return rows.map(rowToApplication);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// The admin review queue: everything not yet resolved, oldest-first so the",
    "// longest-waiting case surfaces first.",
    "export async function listPendingApplications(limit = 100): Promise<AidApplication[]> {",
    "  if (!hasDatabase()) return fallbackApplications;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select a.id, a.user_id, a.category_id, c.name as category_name, a.amount_requested,",
    "        a.situation_description, a.financial_impact, a.how_assistance_helps,",
    "        a.monthly_income, a.monthly_expenses, a.child_support_payment,",
    "        a.has_contributed, a.total_contributed, a.status, a.review_notes,",
    "        a.denial_reason, a.amount_approved, a.reviewed_at, a.submitted_at",
    "      from mutual_aid_benevolence_applications a",
    "      left join mutual_aid_benevolence_categories c on c.id = a.category_id",
    "      where a.status in ('pending', 'under_review')",
    "      order by a.submitted_at asc",
    "      limit ${limit}`;",
    "    return rows.map(rowToApplication);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// A single case, scoped by caller: applicants may only read their own; admins any.",
    "export async function getApplication(id: string): Promise<AidApplication | null> {",
    "  if (!hasDatabase()) return fallbackApplications.find((a) => a.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select a.id, a.user_id, a.category_id, c.name as category_name, a.amount_requested,",
    "        a.situation_description, a.financial_impact, a.how_assistance_helps,",
    "        a.monthly_income, a.monthly_expenses, a.child_support_payment,",
    "        a.has_contributed, a.total_contributed, a.status, a.review_notes,",
    "        a.denial_reason, a.amount_approved, a.reviewed_at, a.submitted_at",
    "      from mutual_aid_benevolence_applications a",
    "      left join mutual_aid_benevolence_categories c on c.id = a.category_id",
    "      where a.id = ${id} limit 1`;",
    "    return rows[0] ? rowToApplication(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SubmitApplicationInput = {",
    "  userId: string;",
    "  categoryId: string;",
    "  amountRequested: number;",
    "  situationDescription: string;",
    "  financialImpact: string;",
    "  howAssistanceHelps: string;",
    "  monthlyIncome?: number | null;",
    "  monthlyExpenses?: number | null;",
    "  childSupportPayment?: number | null;",
    "};",
    "",
    "// Submit a hardship application, ported from handleSubmitApplication: insert the",
    "// case with the applicant's financial snapshot and their standing as a contributor",
    "// (has_contributed / total_contributed), starting at status 'pending'.",
    "export async function submitApplication(input: SubmitApplicationInput): Promise<AidApplication | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const standing = await getContributionStatus(input.userId);",
    "    const rows = await sql`",
    "      insert into mutual_aid_benevolence_applications (",
    "        user_id, category_id, amount_requested, situation_description,",
    "        financial_impact, how_assistance_helps, monthly_income, monthly_expenses,",
    "        child_support_payment, has_contributed, total_contributed, status",
    "      ) values (",
    "        ${input.userId}, ${input.categoryId}, ${input.amountRequested},",
    "        ${input.situationDescription}, ${input.financialImpact}, ${input.howAssistanceHelps},",
    "        ${input.monthlyIncome ?? null}, ${input.monthlyExpenses ?? null},",
    "        ${input.childSupportPayment ?? null}, ${standing.hasContributed},",
    "        ${standing.totalContributed}, 'pending'",
    "      )",
    "      returning id, user_id, category_id, amount_requested, situation_description,",
    "        financial_impact, how_assistance_helps, monthly_income, monthly_expenses,",
    "        child_support_payment, has_contributed, total_contributed, status,",
    "        review_notes, denial_reason, amount_approved, reviewed_at, submitted_at`;",
    "    return rows[0] ? rowToApplication(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Record a contribution to the fund, ported from mutual_aid_contributions. Amount",
    "// must be positive; the fund snapshot recomputes from this on next read.",
    "export async function recordContribution(userId: string, amount: number, isRecurring = false, notes = \"\"): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  if (!(amount > 0)) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`insert into mutual_aid_benevolence_contributions (user_id, amount, is_recurring, notes) values (${userId}, ${amount}, ${isRecurring}, ${notes})`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export type ReviewInput = {",
    "  status: AidStatus;",
    "  amountApproved?: number | null;",
    "  reviewNotes?: string;",
    "  denialReason?: string;",
    "  reviewerId: string;",
    "};",
    "",
    "// Admin review/disbursement, ported from the hardship_applications review workflow",
    "// (status, reviewed_by, reviewed_at, review_notes, denial_reason, amount_approved).",
    "// When a case is disbursed, we also write the assistance grant that the fund's",
    "// total_disbursed / total_recipients aggregate reads from.",
    "export async function reviewApplication(id: string, input: ReviewInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const approved = input.status === \"approved\" || input.status === \"disbursed\";",
    "    await sql`",
    "      update mutual_aid_benevolence_applications set",
    "        status = ${input.status},",
    "        amount_approved = ${approved ? (input.amountApproved ?? null) : null},",
    "        review_notes = ${input.reviewNotes || \"\"},",
    "        denial_reason = ${input.status === \"denied\" ? (input.denialReason || \"\") : \"\"},",
    "        reviewed_by = ${input.reviewerId},",
    "        reviewed_at = now(),",
    "        updated_at = now()",
    "      where id = ${id}`;",
    "    if (input.status === \"disbursed\") {",
    "      const app = await getApplication(id);",
    "      const amount = input.amountApproved ?? (app ? app.amountRequested : 0);",
    "      if (app && app.userId && amount > 0) {",
    "        await sql`",
    "          insert into mutual_aid_benevolence_grants (application_id, user_id, category_id, amount, disbursement_method)",
    "          values (${id}, ${app.userId}, ${app.categoryId || null}, ${amount}, 'manual')`;",
    "      }",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function mutualAidEnabled(): boolean {",
    '  return process.env.FEATURE_MUTUAL_AID !== "false";',
    "}"
  ]);
}

// ---- src/app/api/mutual-aid/route.ts (fund + categories + apply + contribute) -

function mutualAidApiFile(): GeneratedModuleFile {
  return file("src/app/api/mutual-aid/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getFundStats, listCategories, submitApplication, recordContribution, mutualAidEnabled } from "@/lib/db/mutual-aid";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!mutualAidEnabled()) return NextResponse.json({ ok: false, message: "The aid fund is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const [fund, categories] = await Promise.all([getFundStats(), listCategories()]);",
    "  return NextResponse.json({ ok: true, fund, categories });",
    "}",
    "",
    "// POST handles both a new application and a fund contribution, chosen by intent.",
    "export async function POST(request: Request) {",
    '  if (!mutualAidEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role) || !user?.id) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const userId = String(user.id);",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const intent = typeof body.intent === "string" ? body.intent : "apply";',
    "",
    '  if (intent === "contribute") {',
    "    const amount = Number(body.amount);",
    "    if (!(amount > 0)) {",
    '      return NextResponse.json({ ok: false, message: "Enter a contribution amount greater than zero." }, { status: 400 });',
    "    }",
    "    const ok = await recordContribution(userId, amount, body.isRecurring === true, typeof body.notes === \"string\" ? body.notes : \"\");",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to record contributions." }, { status: 503 });',
    '    return NextResponse.json({ ok: true, message: "Thank you. Your contribution helps someone stay afloat." });',
    "  }",
    "",
    "  // Default intent: submit a hardship application.",
    '  const categoryId = typeof body.categoryId === "string" ? body.categoryId.trim() : "";',
    "  const amountRequested = Number(body.amountRequested);",
    '  const situationDescription = typeof body.situationDescription === "string" ? body.situationDescription.trim() : "";',
    '  const financialImpact = typeof body.financialImpact === "string" ? body.financialImpact.trim() : "";',
    '  const howAssistanceHelps = typeof body.howAssistanceHelps === "string" ? body.howAssistanceHelps.trim() : "";',
    "  if (!categoryId || !(amountRequested > 0) || situationDescription.length < 10 || !financialImpact || !howAssistanceHelps) {",
    '    return NextResponse.json({ ok: false, message: "Please choose a category, an amount, and describe your situation, its impact, and how the help works." }, { status: 400 });',
    "  }",
    "  const toNum = (v: unknown): number | null => { const n = Number(v); return Number.isFinite(n) && n >= 0 && v !== \"\" && v != null ? n : null; };",
    "  const created = await submitApplication({",
    "    userId,",
    "    categoryId,",
    "    amountRequested,",
    "    situationDescription,",
    "    financialImpact,",
    "    howAssistanceHelps,",
    "    monthlyIncome: toNum(body.monthlyIncome),",
    "    monthlyExpenses: toNum(body.monthlyExpenses),",
    "    childSupportPayment: toNum(body.childSupportPayment)",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to submit applications." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, application: created, message: "Application submitted. You will be notified when it is reviewed." });',
    "}"
  ]);
}

// ---- src/app/api/mutual-aid/[id]/route.ts (case detail + admin review) --------

function mutualAidDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/mutual-aid/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getApplication, reviewApplication, AID_STATUSES, mutualAidEnabled } from "@/lib/db/mutual-aid";',
    'import type { AidStatus } from "@/lib/db/mutual-aid";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!mutualAidEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const application = await getApplication(id);",
    '  if (!application) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Applicants may only read their own case; admins may read any.",
    "  if (!canAccessAdmin(user?.role) && application.userId !== (user?.id ? String(user.id) : null)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, application });",
    "}",
    "",
    "// Admin review/disbursement, the loop-closer for the pending queue.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = typeof body.status === "string" ? body.status : "";',
    "  if (!(AID_STATUSES as readonly string[]).includes(status)) {",
    '    return NextResponse.json({ ok: false, message: "Choose a valid review status." }, { status: 400 });',
    "  }",
    "  const amountApproved = body.amountApproved == null ? null : Number(body.amountApproved);",
    "  const ok = await reviewApplication(id, {",
    "    status: status as AidStatus,",
    "    amountApproved: Number.isFinite(amountApproved as number) ? (amountApproved as number) : null,",
    '    reviewNotes: typeof body.reviewNotes === "string" ? body.reviewNotes : "",',
    '    denialReason: typeof body.denialReason === "string" ? body.denialReason : "",',
    "    reviewerId: String(user.id)",
    "  });",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to review applications." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/mutual-aid/page.tsx (fund overview + apply + contribute) --------

function mutualAidPageFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getFundStats, listCategories, listMyApplications, getContributionStatus, statusLabel, mutualAidEnabled } from "@/lib/db/mutual-aid";',
    'import { ApplyForm } from "./apply-form";',
    'import { ContributeForm } from "./contribute-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MutualAidPage() {",
    "  if (!mutualAidEnabled()) {",
    '    return (<main className="shell"><h1>Community Aid Fund</h1><p>The aid fund is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mutual-aid");',
    "  const user = await getCurrentUser();",
    "  const userId = user?.id ? String(user.id) : \"\";",
    "  const [fund, categories, myApplications, standing] = await Promise.all([",
    "    getFundStats(),",
    "    listCategories(),",
    "    userId ? listMyApplications(userId) : Promise.resolve([]),",
    "    userId ? getContributionStatus(userId) : Promise.resolve({ hasContributed: false, totalContributed: 0 })",
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Community Aid Fund</p>',
    "      <h1>Aid &amp; hardship assistance</h1>",
    "      <p>Neighbors helping neighbors. Contribute what you can, apply when you need to, and every dollar in and out is tracked in the open.</p>",
    "",
    '      <section className="grid" aria-label="Fund statistics">',
    '        <article className="card"><span>Fund balance</span><strong>${fund.currentBalance.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Contributors</span><strong>{fund.totalContributors.toLocaleString()}</strong></article>',
    '        <article className="card"><span>People helped</span><strong>{fund.totalRecipients.toLocaleString()}</strong></article>',
    '        <article className="card"><span>Total given</span><strong>${fund.totalContributions.toLocaleString()}</strong></article>',
    "      </section>",
    "",
    "      {standing.hasContributed ? (",
    '        <p className="note" role="status">Thank you — you have given ${standing.totalContributed.toLocaleString()} so far.</p>',
    "      ) : null}",
    "",
    "      <h2>Contribute to the fund</h2>",
    "      <p>Your contribution goes toward covering someone else&apos;s hardship. It is a charitable gift, not a fee.</p>",
    "      <ContributeForm />",
    "",
    "      <h2>Apply for assistance</h2>",
    "      <p>Facing a hardship? Tell us what is happening. Every application is reviewed confidentially by our team.</p>",
    "      <ApplyForm categories={categories.map((c) => ({ id: c.id, name: c.name, description: c.description, maxAmount: c.maxAmount }))} />",
    "",
    "      <h2>My applications</h2>",
    "      {myApplications.length === 0 ? (",
    '        <p className="note">You have not submitted any applications yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {myApplications.map((app) => (",
    '            <Link className="wide-card" key={app.id} href={`/mutual-aid/${app.id}`}>',
    "              <span>{statusLabel(app.status)}</span>",
    "              <strong>{app.categoryName || \"Assistance\"}</strong>",
    '              <p className="note">Requested ${app.amountRequested.toLocaleString()}{app.amountApproved != null ? ` · Approved $${app.amountApproved.toLocaleString()}` : ""}</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mutual-aid/apply-form.tsx (client) -----------------------------

function applyFormFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/apply-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type CategoryOption = { id: string; name: string; description: string; maxAmount: number };",
    "",
    "export function ApplyForm({ categories }: { categories: CategoryOption[] }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    '  const [categoryId, setCategoryId] = useState<string>("");',
    "",
    "  const selected = categories.find((c) => c.id === categoryId);",
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/mutual-aid", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          intent: "apply",',
    '          categoryId: form.get("categoryId"),',
    '          amountRequested: form.get("amountRequested"),',
    '          situationDescription: form.get("situationDescription"),',
    '          financialImpact: form.get("financialImpact"),',
    '          howAssistanceHelps: form.get("howAssistanceHelps"),',
    '          monthlyIncome: form.get("monthlyIncome"),',
    '          monthlyExpenses: form.get("monthlyExpenses"),',
    '          childSupportPayment: form.get("childSupportPayment")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Application submitted.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Received</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <select className="input" name="categoryId" aria-label="Type of assistance" value={categoryId} onChange={(e) => setCategoryId(e.target.value)} required>',
    '        <option value="">Select a category…</option>',
    "        {categories.map((c) => (",
    "          <option key={c.id} value={c.id}>{c.name} (up to ${c.maxAmount.toLocaleString()})</option>",
    "        ))}",
    "      </select>",
    '      {selected ? <p className="note">{selected.description}</p> : null}',
    '      <input className="input" type="number" name="amountRequested" min="1" step="0.01" placeholder="Amount requested ($)" aria-label="Amount requested" required />',
    '      <textarea className="input" name="situationDescription" rows={4} placeholder="Describe your situation — what is happening and why you need help" aria-label="Describe your situation" required />',
    '      <textarea className="input" name="financialImpact" rows={3} placeholder="How is this affecting you financially?" aria-label="Financial impact" required />',
    '      <textarea className="input" name="howAssistanceHelps" rows={3} placeholder="How will receiving this assistance help?" aria-label="How will this help" required />',
    '      <input className="input" type="number" name="monthlyIncome" min="0" step="0.01" placeholder="Monthly income ($) — optional" aria-label="Monthly income" />',
    '      <input className="input" type="number" name="monthlyExpenses" min="0" step="0.01" placeholder="Monthly expenses ($) — optional" aria-label="Monthly expenses" />',
    '      <input className="input" type="number" name="childSupportPayment" min="0" step="0.01" placeholder="Ongoing obligations ($) — optional" aria-label="Ongoing obligations" />',
    '      <p className="note">All applications are reviewed confidentially and seen only by authorized reviewers.</p>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Submitting…" : "Submit application"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mutual-aid/contribute-form.tsx (client) ------------------------

function contributeFormFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/contribute-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ContributeForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/mutual-aid", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          intent: "contribute",',
    '          amount: form.get("amount"),',
    '          isRecurring: form.get("isRecurring") === "on"',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Thank you for your contribution.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Thank you</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" type="number" name="amount" min="1" step="0.01" placeholder="Contribution amount ($)" aria-label="Contribution amount" required />',
    '      <label className="check"><input type="checkbox" name="isRecurring" /> Make this a recurring monthly gift</label>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Sending…" : "Contribute"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mutual-aid/[id]/page.tsx (case detail) -------------------------

function mutualAidDetailPageFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getApplication, statusLabel, mutualAidEnabled } from "@/lib/db/mutual-aid";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MutualAidCasePage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!mutualAidEnabled()) {",
    '    return (<main className="shell"><h1>Community Aid Fund</h1><p>The aid fund is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mutual-aid");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const application = await getApplication(id);",
    "  if (!application) notFound();",
    "  const isOwner = application.userId === (user?.id ? String(user.id) : null);",
    "  if (!isOwner && !canAccessAdmin(user?.role)) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{statusLabel(application.status)}</p>',
    "      <h1>{application.categoryName || \"Assistance request\"}</h1>",
    '      <p className="note">Submitted {application.submittedAt ? new Date(application.submittedAt).toLocaleDateString() : ""}</p>',
    "",
    '      <section className="grid">',
    '        <article className="card"><span>Amount requested</span><strong>${application.amountRequested.toLocaleString()}</strong></article>',
    "        {application.amountApproved != null ? (",
    '          <article className="card"><span>Amount approved</span><strong>${application.amountApproved.toLocaleString()}</strong></article>',
    "        ) : null}",
    "      </section>",
    "",
    "      <h2>The situation</h2>",
    "      <p>{application.situationDescription}</p>",
    "      <h2>Financial impact</h2>",
    "      <p>{application.financialImpact}</p>",
    "      <h2>How it helps</h2>",
    "      <p>{application.howAssistanceHelps}</p>",
    "",
    "      {application.status === \"denied\" && application.denialReason ? (",
    '        <p className="note" role="status">Not approved: {application.denialReason}</p>',
    "      ) : null}",
    "",
    '      <p><Link className="button" href="/mutual-aid">Back to the fund</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mutual-aid/review/page.tsx (admin review queue) ----------------

function mutualAidReviewPageFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/review/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listPendingApplications, statusLabel, mutualAidEnabled } from "@/lib/db/mutual-aid";',
    'import { ReviewControls } from "./review-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MutualAidReviewPage() {",
    "  if (!mutualAidEnabled()) {",
    '    return (<main className="shell"><h1>Review</h1><p>The aid fund is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/mutual-aid/review");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Review</h1><p className="note">This review queue is for admins only.</p></main>);',
    "  }",
    "  const pending = await listPendingApplications();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Benevolence review queue</h1>",
    "      <p>Applications waiting on a decision, longest-waiting first. Approve, disburse, or decline each case.</p>",
    "      {pending.length === 0 ? (",
    '        <p className="note">Nothing waiting for review. The queue is clear.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {pending.map((app) => (",
    '            <article className="wide-card" key={app.id}>',
    "              <span>{statusLabel(app.status)}</span>",
    "              <strong>{app.categoryName || \"Assistance\"} — ${app.amountRequested.toLocaleString()}</strong>",
    "              <p>{app.situationDescription}</p>",
    '              <p className="note">Impact: {app.financialImpact}</p>',
    "              {app.monthlyIncome != null || app.monthlyExpenses != null ? (",
    '                <p className="note">Income ${(app.monthlyIncome ?? 0).toLocaleString()} · Expenses ${(app.monthlyExpenses ?? 0).toLocaleString()}{app.hasContributed ? ` · Contributor ($${app.totalContributed.toLocaleString()})` : ""}</p>',
    "              ) : null}",
    "              <ReviewControls id={app.id} defaultAmount={app.amountRequested} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/mutual-aid">Back to the fund</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/mutual-aid/review/review-controls.tsx (client) -----------------

function reviewControlsFile(): GeneratedModuleFile {
  return file("src/app/mutual-aid/review/review-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ReviewControls({ id, defaultAmount }: { id: string; defaultAmount: number }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "  const [amount, setAmount] = useState<string>(String(defaultAmount || \"\"));",
    '  const [reason, setReason] = useState<string>("");',
    "",
    "  async function review(nextStatus: string) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/mutual-aid/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          status: nextStatus,",
    "          amountApproved: amount ? Number(amount) : null,",
    "          denialReason: reason",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this case.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <input className="input" type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount to approve ($)" aria-label="Amount to approve" />',
    '      <input className="input" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason (only used when declining)" aria-label="Denial reason" />',
    '      <div className="stack">',
    '        <button className="button" type="button" onClick={() => review("under_review")} disabled={status === "working"}>Mark under review</button>',
    '        <button className="button primary" type="button" onClick={() => review("approved")} disabled={status === "working"}>Approve</button>',
    '        <button className="button primary" type="button" onClick={() => review("disbursed")} disabled={status === "working"}>Approve &amp; disburse</button>',
    '        <button className="button" type="button" onClick={() => review("denied")} disabled={status === "working"}>Decline</button>',
    "      </div>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const mutualAidModule: AppModule = {
  slug: "mutual-aid-benevolence",
  name: "Mutual Aid & Benevolence",
  tier: "optional",
  featureFlagEnv: "FEATURE_MUTUAL_AID",
  files: () => [
    mutualAidLibFile(),
    mutualAidApiFile(),
    mutualAidDetailApiFile(),
    mutualAidPageFile(),
    applyFormFile(),
    contributeFormFile(),
    mutualAidDetailPageFile(),
    mutualAidReviewPageFile(),
    reviewControlsFile()
  ],
  schemaSql: () =>
    [
      "",
      "-- Types of help available, ported from assistance_categories.",
      "create table if not exists mutual_aid_benevolence_categories (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null,",
      "  description text not null default '',",
      "  max_amount numeric(10, 2),",
      "  is_active boolean not null default true,",
      "  requires_documentation boolean not null default true,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists mutual_aid_benevolence_categories_active_idx on mutual_aid_benevolence_categories (is_active);",
      "",
      "-- Contributions into the fund, ported from mutual_aid_contributions.",
      "create table if not exists mutual_aid_benevolence_contributions (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete set null,",
      "  amount numeric(10, 2) not null check (amount > 0),",
      "  is_recurring boolean not null default false,",
      "  notes text not null default '',",
      "  contribution_date timestamptz not null default now(),",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mutual_aid_benevolence_contributions_user_idx on mutual_aid_benevolence_contributions (user_id);",
      "",
      "-- Hardship / benevolence applications, ported from hardship_applications",
      "-- including the full review workflow + status enum.",
      "create table if not exists mutual_aid_benevolence_applications (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  category_id uuid references mutual_aid_benevolence_categories(id),",
      "  amount_requested numeric(10, 2) not null check (amount_requested > 0),",
      "  situation_description text not null default '',",
      "  financial_impact text not null default '',",
      "  how_assistance_helps text not null default '',",
      "  monthly_income numeric(10, 2),",
      "  monthly_expenses numeric(10, 2),",
      "  child_support_payment numeric(10, 2),",
      "  has_contributed boolean not null default false,",
      "  total_contributed numeric(10, 2) not null default 0,",
      "  status text not null default 'pending' check (status in ('pending', 'under_review', 'approved', 'denied', 'disbursed')),",
      "  reviewed_by uuid references users(id) on delete set null,",
      "  reviewed_at timestamptz,",
      "  review_notes text not null default '',",
      "  denial_reason text not null default '',",
      "  amount_approved numeric(10, 2),",
      "  submitted_at timestamptz not null default now(),",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists mutual_aid_benevolence_applications_user_idx on mutual_aid_benevolence_applications (user_id);",
      "create index if not exists mutual_aid_benevolence_applications_status_idx on mutual_aid_benevolence_applications (status);",
      "create index if not exists mutual_aid_benevolence_applications_submitted_idx on mutual_aid_benevolence_applications (submitted_at desc);",
      "",
      "-- Disbursed grants, ported from assistance_grants; the fund's total_disbursed",
      "-- + total_recipients aggregate reads from this.",
      "create table if not exists mutual_aid_benevolence_grants (",
      "  id uuid primary key default gen_random_uuid(),",
      "  application_id uuid not null references mutual_aid_benevolence_applications(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  category_id uuid references mutual_aid_benevolence_categories(id),",
      "  amount numeric(10, 2) not null check (amount > 0),",
      "  disbursement_method text not null default 'manual',",
      "  disbursement_date timestamptz not null default now(),",
      "  notes text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists mutual_aid_benevolence_grants_user_idx on mutual_aid_benevolence_grants (user_id);",
      "create index if not exists mutual_aid_benevolence_grants_application_idx on mutual_aid_benevolence_grants (application_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into mutual_aid_benevolence_categories (name, description, max_amount, requires_documentation) values",
      "  ('Legal Fees', 'Attorney fees, court costs, and legal documentation.', 5000.00, true),",
      "  ('Emergency Expenses', 'Unexpected emergencies (medical, housing, transportation).', 2000.00, true),",
      "  ('Child-Related Expenses', 'Costs for time with children (activities, school supplies).', 1000.00, true),",
      "  ('Mental Health Support', 'Counseling, therapy, and mental health services.', 1500.00, false),",
      "  ('Job Training / Education', 'Skills training, certifications, or education.', 3000.00, true),",
      "  ('Transportation', 'Vehicle repairs, gas, or transportation costs.', 800.00, true)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Mutual Aid & Benevolence — set to false to switch the aid fund + applications + review off.",
    "FEATURE_MUTUAL_AID=true"
  ],
  homeLinks: () => ['        <a className="button" href="/mutual-aid">Aid Fund</a>'],
  navLinks: () => [{ href: "/mutual-aid", label: "Aid Fund" }]
};
