// needs-helper-matching — match a need with a helper (asymmetric): someone posts
// a need, someone else offers to help, and a safety-coded hand-off happens between
// them. Ported from ChurchConnect's real Care Connect system:
//   - backend/routes/care.py POST /api/care/request — the help-request model
//     (title, description, category, urgency, city, date_needed, recurring, status
//     open→matched→in_progress→completed→cancelled).
//   - care.py POST /api/care/profile + GET /api/care/helpers — helper profiles
//     (abilities, availability, has_vehicle, has_background_check, church_vouched →
//     "vouched", completed_visits), listed by most-completed first.
//   - care.py POST /api/care/match — pair a helper to a request, minting a 6-char
//     safety_code, carrying the helper's background-check/vouched flags onto the
//     match, flipping the request to "matched".
//   - care.py POST /api/care/checkin (safety-code verified) + /checkout (increments
//     the helper's completed_visits, completes the request) — the arrival/departure
//     safety hand-off.
//   - care.py POST /api/care/report + GET /api/care/admin/reports — safety incident
//     reports (concern/incident/emergency, action review/suspend/ban) for admins.
//   - care.py GET /api/care/my-matches/{email} — a person's matches as helper and as
//     requester.
// Generalized off the church framing into plain copy so it drops into any app.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_NEEDS); customers post/offer/browse, admins review reports.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/needs.ts (model + queries, ported from care.py) --------------

function needsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/needs.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A need's lifecycle, ported from care.py create_care_request status field:",
    '// open → matched → in_progress → completed → cancelled.',
    'export type NeedStatus = "open" | "matched" | "in_progress" | "completed" | "cancelled";',
    'export const NEED_STATUSES: NeedStatus[] = ["open", "matched", "in_progress", "completed", "cancelled"];',
    "",
    "// Urgency, ported from care.py urgency field (urgent, high, normal, low).",
    'export type Urgency = "urgent" | "high" | "normal" | "low";',
    'export const URGENCIES: Urgency[] = ["urgent", "high", "normal", "low"];',
    "",
    "// Categories, ported from care.py needs/category examples. Plain, app-neutral.",
    "export const NEED_CATEGORIES: string[] = [",
    '  "groceries",',
    '  "meals",',
    '  "transportation",',
    '  "companionship",',
    '  "yard_work",',
    '  "house_cleaning",',
    '  "errands",',
    '  "tech_help",',
    '  "prayer",',
    '  "general"',
    "];",
    "",
    "// A posted need (help request), ported from care.py care_request document.",
    "export type Need = {",
    "  id: string;",
    "  requesterId: string | null;",
    "  requesterName: string;",
    "  title: string;",
    "  description: string;",
    "  category: string;",
    "  urgency: Urgency;",
    "  city: string;",
    "  dateNeeded: string;",
    "  recurring: boolean;",
    "  status: NeedStatus;",
    "  matchedHelperId: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "// A helper offer profile, ported from care.py care_profile (can_help side):",
    "// abilities + availability + has_vehicle + verification flags + completed count.",
    "export type Helper = {",
    "  id: string;",
    "  userId: string | null;",
    "  name: string;",
    "  city: string;",
    "  abilities: string[];",
    "  availability: string[];",
    "  hasVehicle: boolean;",
    "  hasBackgroundCheck: boolean;",
    "  vouched: boolean;",
    "  completedVisits: number;",
    "};",
    "",
    "// A hand-off between a helper and a need, ported from care.py care_match:",
    "// carries the safety code + the helper's verification flags, and its own",
    "// pending_confirmation → confirmed → checked_in → completed → cancelled status.",
    'export type MatchStatus = "pending_confirmation" | "confirmed" | "checked_in" | "completed" | "cancelled";',
    "export type NeedMatch = {",
    "  id: string;",
    "  needId: string;",
    "  needTitle: string;",
    "  helperId: string | null;",
    "  helperName: string;",
    "  requesterId: string | null;",
    "  requesterName: string;",
    "  helperHasBackgroundCheck: boolean;",
    "  helperVouched: boolean;",
    "  status: MatchStatus;",
    "  safetyCode: string;",
    "  scheduledDate: string;",
    "  checkedInAt: string | null;",
    "  checkedOutAt: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "// A safety report, ported from care.py care_report (concern/incident/emergency).",
    "export type SafetyReport = {",
    "  id: string;",
    "  matchId: string | null;",
    "  reporterName: string;",
    "  reportType: string;",
    "  description: string;",
    '  actionRequested: string;',
    "  status: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A 6-char upper-case safety code, ported from care.py match creation",
    '// (str(uuid.uuid4())[:6].upper()) — verified at check-in.',
    "export function makeSafetyCode(): string {",
    '  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";',
    '  let code = "";',
    "  for (let i = 0; i < 6; i += 1) code += alphabet[Math.floor(Math.random() * alphabet.length)];",
    "  return code;",
    "}",
    "",
    "export function parseList(value: unknown): string[] {",
    '  if (Array.isArray(value)) return value.map((v) => String(v).trim()).filter(Boolean);',
    '  if (typeof value !== "string") return [];',
    "  return value.split(/[,\\n;]+/).map((v) => v.trim()).filter(Boolean);",
    "}",
    "",
    "const fallbackNeeds: Need[] = [",
    '  { id: "need-sample-1", requesterId: null, requesterName: "Marta H.", title: "Ride to a medical appointment", description: "I need a lift to a follow-up on Thursday morning and back home after.", category: "transportation", urgency: "high", city: "Riverside", dateNeeded: "", recurring: false, status: "open", matchedHelperId: null, createdAt: "" },',
    '  { id: "need-sample-2", requesterId: null, requesterName: "Dev P.", title: "Help carrying groceries up the stairs", description: "A hand once a week would mean the world — third-floor walk-up.", category: "groceries", urgency: "normal", city: "Riverside", dateNeeded: "", recurring: true, status: "open", matchedHelperId: null, createdAt: "" }',
    "];",
    "",
    "const fallbackHelpers: Helper[] = [",
    '  { id: "helper-sample-1", userId: null, name: "Sam Rivera", city: "Riverside", abilities: ["driving", "errands"], availability: ["weekend", "weekday_evening"], hasVehicle: true, hasBackgroundCheck: true, vouched: true, completedVisits: 12 },',
    '  { id: "helper-sample-2", userId: null, name: "Jordan Lee", city: "Riverside", abilities: ["companionship", "tech_help"], availability: ["weekday_afternoon"], hasVehicle: false, hasBackgroundCheck: false, vouched: false, completedVisits: 3 }',
    "];",
    "",
    "function rowToNeed(row: Record<string, unknown>): Need {",
    "  return {",
    "    id: String(row.id),",
    "    requesterId: row.requester_id != null ? String(row.requester_id) : null,",
    '    requesterName: String(row.requester_name || "Someone"),',
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    category: String(row.category || "general"),',
    '    urgency: (URGENCIES as string[]).includes(String(row.urgency)) ? (String(row.urgency) as Urgency) : "normal",',
    '    city: String(row.city || ""),',
    '    dateNeeded: String(row.date_needed || ""),',
    "    recurring: row.recurring === true || String(row.recurring) === \"true\",",
    '    status: (NEED_STATUSES as string[]).includes(String(row.status)) ? (String(row.status) as NeedStatus) : "open",',
    "    matchedHelperId: row.matched_helper_id != null ? String(row.matched_helper_id) : null,",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToHelper(row: Record<string, unknown>): Helper {",
    "  const toArr = (v: unknown): string[] => {",
    "    if (Array.isArray(v)) return v.map((x) => String(x));",
    '    if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "    return [];",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    name: String(row.name || "A neighbor"),',
    '    city: String(row.city || ""),',
    "    abilities: toArr(row.abilities),",
    "    availability: toArr(row.availability),",
    "    hasVehicle: row.has_vehicle === true || String(row.has_vehicle) === \"true\",",
    "    hasBackgroundCheck: row.has_background_check === true || String(row.has_background_check) === \"true\",",
    "    vouched: row.vouched === true || String(row.vouched) === \"true\",",
    "    completedVisits: Number(row.completed_visits || 0)",
    "  };",
    "}",
    "",
    "function rowToMatch(row: Record<string, unknown>): NeedMatch {",
    "  return {",
    "    id: String(row.id),",
    "    needId: String(row.need_id),",
    '    needTitle: String(row.need_title || ""),',
    "    helperId: row.helper_id != null ? String(row.helper_id) : null,",
    '    helperName: String(row.helper_name || ""),',
    "    requesterId: row.requester_id != null ? String(row.requester_id) : null,",
    '    requesterName: String(row.requester_name || ""),',
    "    helperHasBackgroundCheck: row.helper_has_background_check === true || String(row.helper_has_background_check) === \"true\",",
    "    helperVouched: row.helper_vouched === true || String(row.helper_vouched) === \"true\",",
    '    status: (["pending_confirmation", "confirmed", "checked_in", "completed", "cancelled"] as string[]).includes(String(row.status)) ? (String(row.status) as MatchStatus) : "pending_confirmation",',
    '    safetyCode: String(row.safety_code || ""),',
    '    scheduledDate: String(row.scheduled_date || ""),',
    "    checkedInAt: row.checked_in_at ? String(row.checked_in_at) : null,",
    "    checkedOutAt: row.checked_out_at ? String(row.checked_out_at) : null,",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- Needs (help requests), ported from care.py /api/care/requests ----------",
    "",
    "export type NeedFilters = { category?: string; urgency?: string; city?: string; status?: string; limit?: number };",
    "",
    "// List open needs, newest first — ported from care.py get_care_requests",
    '// (default status "open", sorted by created_at desc).',
    "export async function listNeeds(filters: NeedFilters = {}): Promise<Need[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const status = (filters.status || "open").trim().toLowerCase();',
    '  const category = (filters.category || "").trim().toLowerCase();',
    '  const city = (filters.city || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackNeeds",
    '      .filter((n) => !status || status === "all" || n.status === status)',
    "      .filter((n) => !category || n.category.toLowerCase() === category)",
    "      .filter((n) => !city || n.city.toLowerCase().includes(city))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    '    const statusFilter = status && status !== "all" ? status : null;',
    "    const categoryFilter = category || null;",
    "    const cityLike = city ? `%${city}%` : null;",
    "    const rows = await sql`",
    "      select id, requester_id, requester_name, title, description, category, urgency, city, date_needed, recurring, status, matched_helper_id, created_at",
    "      from needs_requests",
    "      where (${statusFilter}::text is null or status = ${statusFilter})",
    "        and (${categoryFilter}::text is null or lower(category) = ${categoryFilter})",
    "        and (${cityLike}::text is null or lower(city) like ${cityLike})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToNeed);",
    "  } catch {",
    "    return fallbackNeeds.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getNeed(id: string): Promise<Need | null> {",
    "  if (!hasDatabase()) return fallbackNeeds.find((n) => n.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, requester_id, requester_name, title, description, category, urgency, city, date_needed, recurring, status, matched_helper_id, created_at from needs_requests where id = ${id} limit 1`;",
    "    return rows[0] ? rowToNeed(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateNeedInput = {",
    "  requesterId: string | null;",
    "  requesterName: string;",
    "  title: string;",
    "  description?: string;",
    "  category?: string;",
    "  urgency?: Urgency;",
    "  city?: string;",
    "  dateNeeded?: string;",
    "  recurring?: boolean;",
    "};",
    "",
    "// Post a need, ported from care.py create_care_request (status starts 'open').",
    "export async function createNeed(input: CreateNeedInput): Promise<Need | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    '    const category = input.category && NEED_CATEGORIES.includes(input.category) ? input.category : "general";',
    '    const urgency: Urgency = input.urgency && (URGENCIES as string[]).includes(input.urgency) ? input.urgency : "normal";',
    "    const rows = await sql`",
    "      insert into needs_requests (requester_id, requester_name, title, description, category, urgency, city, date_needed, recurring, status)",
    '      values (${input.requesterId}, ${input.requesterName}, ${input.title}, ${input.description || ""}, ${category}, ${urgency}, ${input.city || ""}, ${input.dateNeeded || ""}, ${input.recurring || false}, \'open\')',
    "      returning id, requester_id, requester_name, title, description, category, urgency, city, date_needed, recurring, status, matched_helper_id, created_at",
    "    `;",
    "    return rows[0] ? rowToNeed(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// ---- Helpers (offers), ported from care.py /api/care/helpers ----------------",
    "",
    "// List available helpers, most-completed first — ported from get_available_helpers",
    "// (is_active + profile_type can_help/both, sorted completed_visits desc).",
    "export async function listHelpers(filters: { city?: string; ability?: string; verifiedOnly?: boolean; limit?: number } = {}): Promise<Helper[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const city = (filters.city || "").trim().toLowerCase();',
    '  const ability = (filters.ability || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackHelpers",
    "      .filter((h) => !city || h.city.toLowerCase().includes(city))",
    "      .filter((h) => !ability || h.abilities.map((a) => a.toLowerCase()).includes(ability))",
    "      .filter((h) => !filters.verifiedOnly || h.hasBackgroundCheck)",
    "      .sort((a, b) => b.completedVisits - a.completedVisits)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const cityLike = city ? `%${city}%` : null;",
    "    const rows = await sql`",
    "      select id, user_id, name, city, abilities, availability, has_vehicle, has_background_check, vouched, completed_visits",
    "      from needs_helpers",
    "      where is_active = true",
    "        and (${cityLike}::text is null or lower(city) like ${cityLike})",
    "        and (${filters.verifiedOnly ? true : null}::boolean is null or has_background_check = true)",
    "      order by completed_visits desc",
    "      limit ${limit}",
    "    `;",
    "    const helpers = rows.map(rowToHelper);",
    "    return ability ? helpers.filter((h) => h.abilities.map((a) => a.toLowerCase()).includes(ability)) : helpers;",
    "  } catch {",
    "    return fallbackHelpers.slice(0, limit);",
    "  }",
    "}",
    "",
    "export type UpsertHelperInput = {",
    "  userId: string;",
    "  name: string;",
    "  city?: string;",
    "  abilities?: string[];",
    "  availability?: string[];",
    "  hasVehicle?: boolean;",
    "};",
    "",
    "// Create/update the current user's helper offer, ported from create_or_update_care_profile",
    "// (de-dupe on the owning user, one offer per user; verification flags stay admin-set).",
    "export async function upsertHelper(input: UpsertHelperInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const abilities = JSON.stringify(input.abilities || []);",
    "    const availability = JSON.stringify(input.availability || []);",
    "    const existing = await sql`select id from needs_helpers where user_id = ${input.userId} limit 1`;",
    "    if (existing[0]) {",
    '      await sql`update needs_helpers set name = ${input.name}, city = ${input.city || ""}, abilities = ${abilities}, availability = ${availability}, has_vehicle = ${input.hasVehicle || false}, is_active = true, updated_at = now() where user_id = ${input.userId}`;',
    "      return true;",
    "    }",
    '    await sql`insert into needs_helpers (user_id, name, city, abilities, availability, has_vehicle) values (${input.userId}, ${input.name}, ${input.city || ""}, ${abilities}, ${availability}, ${input.hasVehicle || false})`;',
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Matches (the asymmetric hand-off), ported from care.py /api/care/match --",
    "",
    "// Pair a helper to a need: mint a safety code, copy the helper's verification",
    "// flags onto the match, flip the need to 'matched'. Ported from match_helper_to_request.",
    "export async function matchHelperToNeed(needId: string, helperUserId: string, helperName: string, scheduledDate: string): Promise<NeedMatch | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const needRows = await sql`select id, requester_id, requester_name, title, status from needs_requests where id = ${needId} limit 1`;",
    "    const need = needRows[0];",
    "    if (!need) return null;",
    '    if (String(need.status) !== "open") return null;',
    "    const helperRows = await sql`select id, has_background_check, vouched from needs_helpers where user_id = ${helperUserId} limit 1`;",
    "    const helper = helperRows[0];",
    "    const code = makeSafetyCode();",
    "    const rows = await sql`",
    "      insert into needs_matches (need_id, need_title, helper_id, helper_name, requester_id, requester_name, helper_has_background_check, helper_vouched, status, safety_code, scheduled_date)",
    "      values (${needId}, ${need.title}, ${helperUserId}, ${helperName}, ${need.requester_id}, ${need.requester_name},",
    "        ${helper ? helper.has_background_check === true : false}, ${helper ? helper.vouched === true : false},",
    "        'pending_confirmation', ${code}, ${scheduledDate})",
    "      returning id, need_id, need_title, helper_id, helper_name, requester_id, requester_name, helper_has_background_check, helper_vouched, status, safety_code, scheduled_date, checked_in_at, checked_out_at, created_at",
    "    `;",
    "    await sql`update needs_requests set status = 'matched', matched_helper_id = ${helperUserId} where id = ${needId}`;",
    "    return rows[0] ? rowToMatch(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Both sides of a person's matches, ported from care.py get_my_care_matches.",
    "export async function listMyMatches(userId: string): Promise<{ asHelper: NeedMatch[]; asRequester: NeedMatch[] }> {",
    "  if (!hasDatabase()) return { asHelper: [], asRequester: [] };",
    "  try {",
    "    const sql = getDatabase();",
    "    const asHelperRows = await sql`select id, need_id, need_title, helper_id, helper_name, requester_id, requester_name, helper_has_background_check, helper_vouched, status, safety_code, scheduled_date, checked_in_at, checked_out_at, created_at from needs_matches where helper_id = ${userId} order by created_at desc`;",
    "    const asRequesterRows = await sql`select id, need_id, need_title, helper_id, helper_name, requester_id, requester_name, helper_has_background_check, helper_vouched, status, safety_code, scheduled_date, checked_in_at, checked_out_at, created_at from needs_matches where requester_id = ${userId} order by created_at desc`;",
    "    return { asHelper: asHelperRows.map(rowToMatch), asRequester: asRequesterRows.map(rowToMatch) };",
    "  } catch {",
    "    return { asHelper: [], asRequester: [] };",
    "  }",
    "}",
    "",
    "// Check in on arrival — safety-code verified. Ported from care.py care_checkin",
    "// (403 on mismatched code; sets status checked_in + checked_in_at).",
    "export async function checkIn(matchId: string, actorId: string, safetyCode: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to check in." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, helper_id, safety_code, status from needs_matches where id = ${matchId} limit 1`;",
    "    const match = rows[0];",
    '    if (!match) return { ok: false, message: "That match no longer exists." };',
    '    if (String(match.helper_id) !== actorId) return { ok: false, message: "Only the assigned helper can check in." };',
    '    if (String(match.safety_code).toUpperCase() !== safetyCode.trim().toUpperCase()) return { ok: false, message: "That safety code doesn\'t match." };',
    "    await sql`update needs_matches set status = 'checked_in', checked_in_at = now() where id = ${matchId}`;",
    "    await sql`update needs_requests set status = 'in_progress' where id = (select need_id from needs_matches where id = ${matchId})`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not check in right now." };',
    "  }",
    "}",
    "",
    "// Check out on leaving — completes the match + need and increments the helper's",
    "// completed_visits. Ported from care.py care_checkout.",
    "export async function checkOut(matchId: string, actorId: string): Promise<{ ok: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to check out." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, helper_id, need_id, status from needs_matches where id = ${matchId} limit 1`;",
    "    const match = rows[0];",
    '    if (!match) return { ok: false, message: "That match no longer exists." };',
    '    if (String(match.helper_id) !== actorId) return { ok: false, message: "Only the assigned helper can check out." };',
    "    await sql`update needs_matches set status = 'completed', checked_out_at = now() where id = ${matchId}`;",
    "    await sql`update needs_requests set status = 'completed' where id = ${match.need_id}`;",
    "    await sql`update needs_helpers set completed_visits = completed_visits + 1 where user_id = ${actorId}`;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not check out right now." };',
    "  }",
    "}",
    "",
    "// ---- Safety reports, ported from care.py /api/care/report + admin/reports ----",
    "",
    "export type CreateReportInput = {",
    "  matchId?: string | null;",
    "  reporterName: string;",
    "  reportType?: string;",
    "  description: string;",
    "  actionRequested?: string;",
    "};",
    "",
    "export async function createReport(input: CreateReportInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    const reportType = ["concern", "incident", "emergency"].includes(input.reportType || "") ? input.reportType : "concern";',
    '    const action = ["review", "suspend", "ban"].includes(input.actionRequested || "") ? input.actionRequested : "review";',
    "    await sql`insert into needs_reports (match_id, reporter_name, report_type, description, action_requested, status) values (${input.matchId || null}, ${input.reporterName}, ${reportType}, ${input.description}, ${action}, 'pending')`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Admin-only queue of safety reports, ported from get_safety_reports.",
    "export async function listReports(status?: string, limit = 50): Promise<SafetyReport[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const cap = Math.min(200, Math.max(1, limit));",
    "    const statusFilter = status && status.trim() ? status.trim() : null;",
    "    const rows = await sql`",
    "      select id, match_id, reporter_name, report_type, description, action_requested, status, created_at",
    "      from needs_reports",
    "      where (${statusFilter}::text is null or status = ${statusFilter})",
    "      order by created_at desc",
    "      limit ${cap}",
    "    `;",
    "    return rows.map((row: Record<string, unknown>) => ({",
    "      id: String(row.id),",
    "      matchId: row.match_id != null ? String(row.match_id) : null,",
    '      reporterName: String(row.reporter_name || "Someone"),',
    '      reportType: String(row.report_type || "concern"),',
    '      description: String(row.description || ""),',
    '      actionRequested: String(row.action_requested || "review"),',
    '      status: String(row.status || "pending"),',
    '      createdAt: row.created_at ? String(row.created_at) : ""',
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export function needsEnabled(): boolean {",
    '  return process.env.FEATURE_NEEDS !== "false";',
    "}"
  ]);
}

// ---- src/app/api/needs/route.ts (list + post needs) --------------------------

function needsApiFile(): GeneratedModuleFile {
  return file("src/app/api/needs/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listNeeds, createNeed, needsEnabled } from "@/lib/db/needs";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false, message: "Needs board is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const needs = await listNeeds({",
    '    category: url.searchParams.get("category") || undefined,',
    '    urgency: url.searchParams.get("urgency") || undefined,',
    '    city: url.searchParams.get("city") || undefined,',
    '    status: url.searchParams.get("status") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, needs });",
    "}",
    "",
    "// Posting a need is a customer action (anyone signed in can ask for help).",
    "export async function POST(request: Request) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to post a need." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  if (title.length < 3) return NextResponse.json({ ok: false, message: "A short title for the need is required." }, { status: 400 });',
    "  const need = await createNeed({",
    '    requesterId: String(user?.id || ""),',
    '    requesterName: user?.name || user?.email || "Someone",',
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    '    category: typeof body.category === "string" ? body.category : undefined,',
    '    urgency: typeof body.urgency === "string" ? (body.urgency as any) : undefined,',
    '    city: typeof body.city === "string" ? body.city : undefined,',
    '    dateNeeded: typeof body.dateNeeded === "string" ? body.dateNeeded : undefined,',
    "    recurring: body.recurring === true",
    "  });",
    '  if (!need) return NextResponse.json({ ok: false, message: "Connect a database to post needs." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, need });",
    "}"
  ]);
}

// ---- src/app/api/needs/[id]/match/route.ts (offer to help) -------------------

function needMatchApiFile(): GeneratedModuleFile {
  return file("src/app/api/needs/[id]/match/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { matchHelperToNeed, needsEnabled } from "@/lib/db/needs";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// A signed-in customer offers to help a specific need — creates the safety-coded match.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to offer help." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const scheduledDate = typeof body.scheduledDate === "string" ? body.scheduledDate : "";',
    '  const helperId = String(user?.id || "");',
    '  const helperName = user?.name || user?.email || "A helper";',
    "  const match = await matchHelperToNeed(id, helperId, helperName, scheduledDate);",
    '  if (!match) return NextResponse.json({ ok: false, message: "This need is no longer open, or the database is not connected." }, { status: 409 });',
    "  return NextResponse.json({ ok: true, match });",
    "}"
  ]);
}

// ---- src/app/api/needs/matches/[id]/checkin/route.ts ------------------------

function checkinApiFile(): GeneratedModuleFile {
  return file("src/app/api/needs/matches/[id]/checkin/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { checkIn, checkOut, needsEnabled } from "@/lib/db/needs";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// One endpoint for both arrival (with safety code) and departure, chosen by ?action.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const actorId = String(user?.id || "");',
    '  const action = typeof body.action === "string" ? body.action : "check_in";',
    '  if (action === "check_out") {',
    "    const result = await checkOut(id, actorId);",
    '    if (!result.ok) return NextResponse.json({ ok: false, message: result.message || "Could not check out." }, { status: 409 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    '  const safetyCode = typeof body.safetyCode === "string" ? body.safetyCode : "";',
    '  if (!safetyCode.trim()) return NextResponse.json({ ok: false, message: "Enter the safety code to check in." }, { status: 400 });',
    "  const result = await checkIn(id, actorId, safetyCode);",
    '  if (!result.ok) return NextResponse.json({ ok: false, message: result.message || "Could not check in." }, { status: 409 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/needs/reports/route.ts (submit + admin list) ---------------

function reportsApiFile(): GeneratedModuleFile {
  return file("src/app/api/needs/reports/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { createReport, listReports, needsEnabled } from "@/lib/db/needs";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Admin-only queue of safety reports.",
    "export async function GET(request: Request) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const url = new URL(request.url);",
    '  const reports = await listReports(url.searchParams.get("status") || undefined);',
    "  return NextResponse.json({ ok: true, reports });",
    "}",
    "",
    "// Anyone signed in can file a safety concern about a hand-off.",
    "export async function POST(request: Request) {",
    '  if (!needsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const description = typeof body.description === "string" ? body.description.trim() : "";',
    '  if (description.length < 5) return NextResponse.json({ ok: false, message: "Please describe what happened." }, { status: 400 });',
    "  const created = await createReport({",
    '    matchId: typeof body.matchId === "string" ? body.matchId : null,',
    '    reporterName: user?.name || user?.email || "Someone",',
    '    reportType: typeof body.reportType === "string" ? body.reportType : undefined,',
    "    description,",
    '    actionRequested: typeof body.actionRequested === "string" ? body.actionRequested : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to file reports." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/needs/page.tsx (the needs board + post-a-need) -----------------

function needsPageFile(): GeneratedModuleFile {
  return file("src/app/needs/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listNeeds, NEED_CATEGORIES, needsEnabled } from "@/lib/db/needs";',
    'import { PostNeedForm } from "./post-need-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function NeedsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ category?: string; city?: string }>;",
    "}) {",
    "  if (!needsEnabled()) {",
    '    return (<main className="shell"><h1>Needs</h1><p>The needs board is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/needs");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const category = (params?.category || "").trim();',
    '  const city = (params?.city || "").trim();',
    "  const needs = await listNeeds({ category: category || undefined, city: city || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Needs</p>',
    "      <h1>Who needs a hand?</h1>",
    "      <p>Someone posts a need; someone else offers to help. Every hand-off gets a safety code so both people know who is coming and when.</p>",
    "",
    '      <form className="stack" method="get" role="search">',
    '        <select className="input" name="category" defaultValue={category} aria-label="Filter by category">',
    '          <option value="">All categories</option>',
    "          {NEED_CATEGORIES.map((c) => (",
    '            <option key={c} value={c}>{c.replace(/_/g, " ")}</option>',
    "          ))}",
    "        </select>",
    '        <input className="input" type="search" name="city" defaultValue={city} placeholder="City" aria-label="Filter by city" />',
    '        <button className="button primary" type="submit">Filter</button>',
    "      </form>",
    "",
    "      {needs.length === 0 ? (",
    '        <p className="note">No open needs right now. When someone posts one, it shows up here.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {needs.map((need) => (",
    '            <Link className="wide-card" key={need.id} href={`/needs/${need.id}`}>',
    '              <span>{need.urgency} · {need.category.replace(/_/g, " ")}{need.city ? ` · ${need.city}` : ""}</span>',
    "              <strong>{need.title}</strong>",
    "              {need.description ? <p>{need.description}</p> : null}",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Post a need</h2>",
    "      <PostNeedForm categories={NEED_CATEGORIES} />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/needs/post-need-form.tsx (client) ------------------------------

function postNeedFormFile(): GeneratedModuleFile {
  return file("src/app/needs/post-need-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function PostNeedForm({ categories }: { categories: string[] }) {",
    "  const router = useRouter();",
    '  const [title, setTitle] = useState("");',
    '  const [description, setDescription] = useState("");',
    '  const [category, setCategory] = useState(categories[0] || "general");',
    '  const [urgency, setUrgency] = useState("normal");',
    '  const [city, setCity] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/needs", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ title, description, category, urgency, city })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setTitle("");',
    '      setDescription("");',
    '      setCity("");',
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="What do you need help with?" aria-label="Need title" required />',
    '      <textarea className="input" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Add any details that would help." aria-label="Description" rows={3} />',
    '      <select className="input" value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Category">',
    '        {categories.map((c) => (<option key={c} value={c}>{c.replace(/_/g, " ")}</option>))}',
    "      </select>",
    '      <select className="input" value={urgency} onChange={(e) => setUrgency(e.target.value)} aria-label="Urgency">',
    '        <option value="urgent">Urgent</option>',
    '        <option value="high">High</option>',
    '        <option value="normal">Normal</option>',
    '        <option value="low">Low</option>',
    "      </select>",
    '      <input className="input" value={city} onChange={(e) => setCity(e.target.value)} placeholder="City" aria-label="City" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Posting…" : "Post this need"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/needs/[id]/page.tsx (need detail + offer to help) --------------

function needDetailPageFile(): GeneratedModuleFile {
  return file("src/app/needs/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getNeed, needsEnabled } from "@/lib/db/needs";',
    'import { OfferHelpButton } from "./offer-help-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function NeedDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!needsEnabled()) {",
    '    return (<main className="shell"><h1>Needs</h1><p>The needs board is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/needs");',
    "  const { id } = await params;",
    "  const need = await getNeed(id);",
    "  if (!need) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Need · {need.status.replace(/_/g, " ")}</p>',
    "      <h1>{need.title}</h1>",
    '      <p className="note">Asked by {need.requesterName}{need.city ? ` in ${need.city}` : ""} · {need.urgency} · {need.category.replace(/_/g, " ")}</p>',
    "      {need.description ? <p>{need.description}</p> : null}",
    '      {need.recurring ? <p className="note">This is a recurring need.</p> : null}',
    "",
    '      {need.status === "open" ? (',
    "        <OfferHelpButton needId={need.id} />",
    "      ) : (",
    '        <p className="note">This need has already been matched with a helper.</p>',
    "      )}",
    '      <p><Link className="button" href="/needs">Back to needs</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/needs/[id]/offer-help-button.tsx (client) ----------------------

function offerHelpButtonFile(): GeneratedModuleFile {
  return file("src/app/needs/[id]/offer-help-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function OfferHelpButton({ needId }: { needId: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "offering" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "  const [safetyCode, setSafetyCode] = useState<string | null>(null);",
    "",
    "  async function offer() {",
    '    setStatus("offering");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/needs/${needId}/match`, {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({})",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not offer help right now.");',
    "        return;",
    "      }",
    '      setSafetyCode(data.match?.safetyCode || null);',
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  if (safetyCode) {",
    "    return (",
    '      <section className="panel" aria-live="polite">',
    "        <p><strong>You’re matched.</strong> Share this safety code with the person you’re helping — you’ll enter it when you arrive:</p>",
    '        <p className="eyebrow" style={{ fontSize: "1.5rem", letterSpacing: "0.2em" }}>{safetyCode}</p>',
    '        <p className="note">Find this hand-off again under <a href="/needs/my-matches">my matches</a>.</p>',
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    "    <span>",
    '      <button className="button primary" type="button" onClick={offer} disabled={status === "offering"}>',
    '        {status === "offering" ? "Offering…" : "Offer to help"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert"> {message}</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

// ---- src/app/needs/my-matches/page.tsx (the hand-offs I'm part of) ----------

function myMatchesPageFile(): GeneratedModuleFile {
  return file("src/app/needs/my-matches/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listMyMatches, needsEnabled } from "@/lib/db/needs";',
    'import { CheckInOut } from "./check-in-out";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MyMatchesPage() {",
    "  if (!needsEnabled()) {",
    '    return (<main className="shell"><h1>Needs</h1><p>The needs board is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/needs/my-matches");',
    "  const user = await getCurrentUser();",
    '  const userId = user?.id ? String(user.id) : "";',
    "  const { asHelper, asRequester } = userId ? await listMyMatches(userId) : { asHelper: [], asRequester: [] };",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Needs</p>',
    "      <h1>My hand-offs</h1>",
    "",
    "      <h2>Where I’m helping</h2>",
    "      {asHelper.length === 0 ? (",
    '        <p className="note">You haven’t offered to help anyone yet. <Link href="/needs">Find a need</Link>.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {asHelper.map((m) => (",
    '            <article className="wide-card" key={m.id}>',
    '              <span>{m.status.replace(/_/g, " ")}</span>',
    "              <strong>{m.needTitle}</strong>",
    '              <p className="note">Helping {m.requesterName} · safety code {m.safetyCode}</p>',
    "              <CheckInOut match={{ id: m.id, status: m.status }} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "",
    "      <h2>Where I asked for help</h2>",
    "      {asRequester.length === 0 ? (",
    '        <p className="note">None of your needs are matched yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {asRequester.map((m) => (",
    '            <article className="wide-card" key={m.id}>',
    '              <span>{m.status.replace(/_/g, " ")}</span>',
    "              <strong>{m.needTitle}</strong>",
    '              <p className="note">{m.helperName} is helping{m.helperVouched ? " · vouched" : ""}{m.helperHasBackgroundCheck ? " · background-checked" : ""}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/needs">Back to needs</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/needs/my-matches/check-in-out.tsx (client) ---------------------

function checkInOutFile(): GeneratedModuleFile {
  return file("src/app/needs/my-matches/check-in-out.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function CheckInOut({ match }: { match: { id: string; status: string } }) {",
    "  const router = useRouter();",
    '  const [code, setCode] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function act(action: string) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/needs/matches/${match.id}/checkin`, {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action, safetyCode: code })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "That didn’t work.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    '  if (match.status === "completed" || match.status === "cancelled") {',
    '    return <p className="note">This hand-off is {match.status}.</p>;',
    "  }",
    "",
    '  if (match.status === "checked_in") {',
    "    return (",
    "      <span>",
    '        <button className="button" type="button" onClick={() => act("check_out")} disabled={status === "working"}>',
    '          {status === "working" ? "Saving…" : "Check out"}',
    "        </button>",
    '        {status === "error" ? <span className="note" role="alert"> {message}</span> : null}',
    "      </span>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <span className="stack">',
    '      <input className="input" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Safety code" aria-label="Safety code" />',
    '      <button className="button primary" type="button" onClick={() => act("check_in")} disabled={status === "working"}>',
    '        {status === "working" ? "Checking in…" : "Check in on arrival"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert"> {message}</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

export const needsHelperMatchingModule: AppModule = {
  slug: "needs-helper-matching",
  name: "Needs & Helper Matching",
  tier: "optional",
  featureFlagEnv: "FEATURE_NEEDS",
  files: () => [
    needsLibFile(),
    needsApiFile(),
    needMatchApiFile(),
    checkinApiFile(),
    reportsApiFile(),
    needsPageFile(),
    postNeedFormFile(),
    needDetailPageFile(),
    offerHelpButtonFile(),
    myMatchesPageFile(),
    checkInOutFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists needs_requests (",
      "  id uuid primary key default gen_random_uuid(),",
      "  requester_id uuid references users(id) on delete set null,",
      "  requester_name text not null default '',",
      "  title text not null,",
      "  description text not null default '',",
      "  category text not null default 'general',",
      "  urgency text not null default 'normal',",
      "  city text not null default '',",
      "  date_needed text not null default '',",
      "  recurring boolean not null default false,",
      "  status text not null default 'open',",
      "  matched_helper_id uuid references users(id) on delete set null,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists needs_requests_status_idx on needs_requests (status, created_at desc);",
      "create index if not exists needs_requests_category_idx on needs_requests (lower(category));",
      "",
      "create table if not exists needs_helpers (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid references users(id) on delete cascade,",
      "  name text not null default '',",
      "  city text not null default '',",
      "  abilities jsonb not null default '[]'::jsonb,",
      "  availability jsonb not null default '[]'::jsonb,",
      "  has_vehicle boolean not null default false,",
      "  has_background_check boolean not null default false,",
      "  vouched boolean not null default false,",
      "  completed_visits integer not null default 0,",
      "  is_active boolean not null default true,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists needs_helpers_user_idx on needs_helpers (user_id);",
      "create index if not exists needs_helpers_completed_idx on needs_helpers (completed_visits desc);",
      "",
      "create table if not exists needs_matches (",
      "  id uuid primary key default gen_random_uuid(),",
      "  need_id uuid not null references needs_requests(id) on delete cascade,",
      "  need_title text not null default '',",
      "  helper_id uuid references users(id) on delete set null,",
      "  helper_name text not null default '',",
      "  requester_id uuid references users(id) on delete set null,",
      "  requester_name text not null default '',",
      "  helper_has_background_check boolean not null default false,",
      "  helper_vouched boolean not null default false,",
      "  status text not null default 'pending_confirmation',",
      "  safety_code text not null,",
      "  scheduled_date text not null default '',",
      "  checked_in_at timestamptz,",
      "  checked_out_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists needs_matches_helper_idx on needs_matches (helper_id, created_at desc);",
      "create index if not exists needs_matches_requester_idx on needs_matches (requester_id, created_at desc);",
      "",
      "create table if not exists needs_reports (",
      "  id uuid primary key default gen_random_uuid(),",
      "  match_id uuid references needs_matches(id) on delete set null,",
      "  reporter_name text not null default '',",
      "  report_type text not null default 'concern',",
      "  description text not null default '',",
      "  action_requested text not null default 'review',",
      "  status text not null default 'pending',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists needs_reports_status_idx on needs_reports (status, created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into needs_requests (requester_name, title, description, category, urgency, city, recurring) values",
      "  ('Marta H.', 'Ride to a medical appointment', 'A lift to a follow-up and back home after would be a huge help.', 'transportation', 'high', 'Riverside', false),",
      "  ('Dev P.', 'Help carrying groceries up the stairs', 'A hand once a week would mean the world — third-floor walk-up.', 'groceries', 'normal', 'Riverside', true)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Needs & Helper Matching — set to false to switch the needs board + hand-offs off.",
    "FEATURE_NEEDS=true"
  ],
  homeLinks: () => ['        <a className="button" href="/needs">Needs board</a>'],
  navLinks: () => [{ href: "/needs", label: "Needs" }]
};
