// payments-billing — online giving, donations, and recurring gifts, ported from
// ChurchConnect's real giving system (src/components/OnlineGiving.tsx give/history
// views, backend/routes/stripe_payments.py checkout-session + webhook status
// tracking, backend/routes/universal_giving.py funds/recurring/yearly stats, and
// backend/routes/stripe_billing.py's recurring charge — adapted to Stripe
// Checkout's subscription mode because generated apps keep no card vault).
//
// Scope is deliberately what the foundation payments module LACKS: foundation
// covers product checkout (src/lib/payments.ts, /api/billing/*, `payments` table);
// this module adds designated-fund giving, donor gift history, monthly recurring
// gifts, and annual giving statements — its own /giving pages, /api/giving routes,
// and payments_billing_* tables, keyed to the same owner Stripe credentials.
// Feature-flagged (FEATURE_GIVING), donors give, admins see fund totals.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/giving-options.ts (pure option lists, client-safe) ----------
// The giving form is a client component; the preset amounts live in a file
// with no database driver so importing them never pulls @/lib/db/client toward
// the client bundle.

function givingOptionsFile(): GeneratedModuleFile {
  return file("src/lib/db/giving-options.ts", [
    "// Pure giving option lists — importable from client components (no database",
    "// driver in this file).",
    "",
    "// Preset gift amounts, ported from OnlineGiving.tsx PRESET_AMOUNTS.",
    "export const PRESET_AMOUNTS = [10, 25, 50, 100, 250, 500];"
  ]);
}

// ---- src/lib/db/giving.ts (model + queries) ----------------------------------

function givingLibFile(): GeneratedModuleFile {
  return file("src/lib/db/giving.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    'import { PRESET_AMOUNTS } from "@/lib/db/giving-options";',
    "",
    "// Re-exported for server-side callers; client components import the options",
    "// from @/lib/db/giving-options directly (keeps the db driver server-only).",
    "export { PRESET_AMOUNTS };",
    "",
    "export type GivingFund = { id: string; name: string; description: string };",
    "",
    "export type Gift = {",
    "  id: string;",
    "  donorName: string;",
    "  donorEmail: string;",
    "  fundName: string;",
    "  amountCents: number;",
    '  frequency: string; // "one-time" | "monthly"',
    '  status: string; // "pending" | "paid" | "failed"',
    "  createdAt: string;",
    "};",
    "",
    "export type RecurringGift = {",
    "  id: string;",
    "  donorName: string;",
    "  donorEmail: string;",
    "  fundName: string;",
    "  amountCents: number;",
    '  status: string; // "pending" | "active" | "cancelled"',
    "  createdAt: string;",
    "};",
    "",
    "export type GivingStats = { year: number; totalCents: number; giftCount: number; averageCents: number };",
    "export type FundTotal = { fundName: string; totalCents: number; giftCount: number };",
    "",
    "export function givingEnabled(): boolean {",
    '  return process.env.FEATURE_GIVING !== "false";',
    "}",
    "",
    "export function formatAmount(cents: number): string {",
    '  return "$" + (cents / 100).toFixed(2);',
    "}",
    "",
    "// Default designations, ported from OnlineGiving.tsx's fund selector.",
    "const fallbackFunds: GivingFund[] = [",
    '  { id: "general", name: "General Fund", description: "Where it is needed most." },',
    '  { id: "tithes", name: "Tithes", description: "Regular tithes and offerings." },',
    '  { id: "missions", name: "Missions", description: "Local and global mission work." },',
    '  { id: "building", name: "Building Fund", description: "Facilities and building projects." }',
    "];",
    "",
    "function rowToGift(row: Record<string, unknown>): Gift {",
    "  return {",
    "    id: String(row.id),",
    '    donorName: String(row.donor_name || "Anonymous"),',
    '    donorEmail: String(row.donor_email || ""),',
    '    fundName: String(row.fund_name || "General Fund"),',
    "    amountCents: Number(row.amount_cents || 0),",
    '    frequency: String(row.frequency || "one-time"),',
    '    status: String(row.status || "pending"),',
    '    createdAt: String(row.created_at || "")',
    "  };",
    "}",
    "",
    "// Active funds sorted by name, ported from OnlineGiving.tsx fetchUserContext.",
    "export async function listFunds(): Promise<GivingFund[]> {",
    "  if (!hasDatabase()) return fallbackFunds;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select id, name, description from payments_billing_funds where active = true order by name asc limit 50`;",
    "    if (!rows.length) return fallbackFunds;",
    '    return rows.map((row) => ({ id: String(row.id), name: String(row.name), description: String(row.description || "") }));',
    "  } catch {",
    "    return fallbackFunds;",
    "  }",
    "}",
    "",
    "export type RecordGiftInput = {",
    "  donorName: string;",
    "  donorEmail: string;",
    "  fundName: string;",
    "  amountCents: number;",
    "  frequency: string;",
    "  stripeSessionId: string;",
    "};",
    "",
    "// A gift starts pending and is marked paid/failed by the webhook — ported from",
    "// stripe_payments.py, which records the payment then updates it by intent id.",
    "export async function recordGift(input: RecordGiftInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into payments_billing_gifts (donor_name, donor_email, fund_name, amount_cents, frequency, stripe_session_id)",
    '      values (${input.donorName || "Anonymous"}, ${input.donorEmail}, ${input.fundName || "General Fund"},',
    '        ${input.amountCents}, ${input.frequency || "one-time"}, ${input.stripeSessionId})',
    "    `;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Webhook status updates, ported from stripe_payments.py stripe_webhook",
    "// (payment_intent.succeeded -> succeeded, payment_intent.payment_failed -> failed).",
    "export async function markGiftPaid(stripeSessionId: string): Promise<boolean> {",
    "  if (!hasDatabase() || !stripeSessionId) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update payments_billing_gifts set status = 'paid' where stripe_session_id = ${stripeSessionId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function markGiftFailed(stripeSessionId: string): Promise<boolean> {",
    "  if (!hasDatabase() || !stripeSessionId) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update payments_billing_gifts set status = 'failed' where stripe_session_id = ${stripeSessionId} and status = 'pending'`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// A donor's gifts for one year, newest first — ported from OnlineGiving.tsx",
    "// fetchDonationHistory (per-year date range, descending).",
    "export async function listGiftsForDonor(email: string, year: number): Promise<Gift[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, donor_name, donor_email, fund_name, amount_cents, frequency, status, created_at",
    "      from payments_billing_gifts",
    "      where lower(donor_email) = ${email.toLowerCase()}",
    "        and extract(year from created_at) = ${year}",
    "      order by created_at desc",
    "      limit 100",
    "    `;",
    "    return rows.map(rowToGift);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function listRecentGifts(limit = 50): Promise<Gift[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, donor_name, donor_email, fund_name, amount_cents, frequency, status, created_at",
    "      from payments_billing_gifts",
    "      order by created_at desc",
    "      limit ${Math.min(200, Math.max(1, limit))}",
    "    `;",
    "    return rows.map(rowToGift);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// Yearly totals for one donor, ported from universal_giving.py",
    "// get_user_giving_stats plus OnlineGiving.tsx's Total/Gifts/Average tiles.",
    "// Only paid gifts count toward totals.",
    "export async function givingStatsForDonor(email: string, year: number): Promise<GivingStats> {",
    "  const empty: GivingStats = { year, totalCents: 0, giftCount: 0, averageCents: 0 };",
    "  if (!hasDatabase()) return empty;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select coalesce(sum(amount_cents), 0)::int as total_cents, count(*)::int as gift_count",
    "      from payments_billing_gifts",
    "      where lower(donor_email) = ${email.toLowerCase()}",
    "        and status = 'paid'",
    "        and extract(year from created_at) = ${year}",
    "    `;",
    "    const totalCents = Number(rows[0]?.total_cents || 0);",
    "    const giftCount = Number(rows[0]?.gift_count || 0);",
    "    return { year, totalCents, giftCount, averageCents: giftCount ? Math.round(totalCents / giftCount) : 0 };",
    "  } catch {",
    "    return empty;",
    "  }",
    "}",
    "",
    "// Paid gifts grouped by fund for a year — the annual giving statement, and the",
    "// admin per-fund totals (GivingReports' fund breakdown).",
    "export async function fundTotalsForYear(year: number, email?: string): Promise<FundTotal[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const donor = email ? email.toLowerCase() : null;",
    "    const rows = await sql`",
    "      select fund_name, coalesce(sum(amount_cents), 0)::int as total_cents, count(*)::int as gift_count",
    "      from payments_billing_gifts",
    "      where status = 'paid'",
    "        and extract(year from created_at) = ${year}",
    "        and (${donor}::text is null or lower(donor_email) = ${donor})",
    "      group by fund_name",
    "      order by total_cents desc",
    "    `;",
    "    return rows.map((row) => ({",
    "      fundName: String(row.fund_name),",
    "      totalCents: Number(row.total_cents || 0),",
    "      giftCount: Number(row.gift_count || 0)",
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export type RecurringGiftInput = {",
    "  donorName: string;",
    "  donorEmail: string;",
    "  fundName: string;",
    "  amountCents: number;",
    "  stripeSessionId: string;",
    "};",
    "",
    "// Recurring gifts start pending and activate when checkout completes — the",
    "// generated-app equivalent of stripe_billing.py's saved-card recurring charge.",
    "export async function createRecurringGift(input: RecurringGiftInput): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into payments_billing_recurring_gifts (donor_name, donor_email, fund_name, amount_cents, stripe_session_id)",
    '      values (${input.donorName || "Anonymous"}, ${input.donorEmail}, ${input.fundName || "General Fund"},',
    "        ${input.amountCents}, ${input.stripeSessionId})",
    "    `;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function activateRecurringGift(stripeSessionId: string): Promise<boolean> {",
    "  if (!hasDatabase() || !stripeSessionId) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update payments_billing_recurring_gifts set status = 'active' where stripe_session_id = ${stripeSessionId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export async function listRecurringGiftsForDonor(email: string): Promise<RecurringGift[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, donor_name, donor_email, fund_name, amount_cents, status, created_at",
    "      from payments_billing_recurring_gifts",
    "      where lower(donor_email) = ${email.toLowerCase()} and status in ('pending', 'active')",
    "      order by created_at desc",
    "      limit 20",
    "    `;",
    "    return rows.map((row) => ({",
    "      id: String(row.id),",
    '      donorName: String(row.donor_name || "Anonymous"),',
    '      donorEmail: String(row.donor_email || ""),',
    '      fundName: String(row.fund_name || "General Fund"),',
    "      amountCents: Number(row.amount_cents || 0),",
    '      status: String(row.status || "pending"),',
    '      createdAt: String(row.created_at || "")',
    "    }));",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function countActiveRecurringGifts(): Promise<number> {",
    "  if (!hasDatabase()) return 0;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`select count(*)::int as n from payments_billing_recurring_gifts where status = 'active'`;",
    "    return Number(rows[0]?.n || 0);",
    "  } catch {",
    "    return 0;",
    "  }",
    "}"
  ]);
}

// ---- src/lib/giving-checkout.ts (Stripe Checkout for gifts) -------------------

function givingCheckoutLibFile(): GeneratedModuleFile {
  return file("src/lib/giving-checkout.ts", [
    "// Giving checkout on the app owner's own Stripe account, ported from",
    "// ChurchConnect stripe_payments.py create_checkout_session (one-time gifts are",
    '// a mode "payment" session built from name + amount). Monthly gifts use',
    "// Checkout's subscription mode with recurring price_data — the generated-app",
    "// equivalent of stripe_billing.py charge-subscription, since these apps keep no",
    "// card vault. Unlike the foundation product checkout, the session id is",
    "// returned so the webhook can settle each gift precisely (ChurchConnect tracks",
    "// payments by intent id the same way). Configuration is shared with the",
    "// foundation payments module (STRIPE_SECRET_KEY).",
    'import { stripeConfigured } from "@/lib/payments";',
    "",
    "export type GivingCheckoutInput = {",
    "  amountCents: number;",
    "  fundName: string;",
    "  monthly: boolean;",
    "  successUrl: string;",
    "  cancelUrl: string;",
    "  donorEmail?: string;",
    "};",
    "",
    "export type GivingCheckoutResult = { ok: boolean; url?: string; sessionId?: string; reason?: string };",
    "",
    "export async function createGivingCheckout(input: GivingCheckoutInput): Promise<GivingCheckoutResult> {",
    "  if (!stripeConfigured()) {",
    '    return { ok: false, reason: "Payments are not connected yet (set STRIPE_SECRET_KEY)." };',
    "  }",
    "  const body = new URLSearchParams();",
    '  body.set("mode", input.monthly ? "subscription" : "payment");',
    '  body.set("success_url", input.successUrl);',
    '  body.set("cancel_url", input.cancelUrl);',
    '  body.set("line_items[0][quantity]", "1");',
    '  body.set("line_items[0][price_data][currency]", "usd");',
    '  body.set("line_items[0][price_data][unit_amount]", String(Math.max(1, Math.round(input.amountCents))));',
    '  body.set("line_items[0][price_data][product_data][name]", (input.monthly ? "Monthly gift — " : "Gift — ") + (input.fundName || "General Fund"));',
    '  if (input.monthly) body.set("line_items[0][price_data][recurring][interval]", "month");',
    '  if (input.donorEmail) body.set("customer_email", input.donorEmail);',
    "  try {",
    '    const response = await fetch("https://api.stripe.com/v1/checkout/sessions", {',
    '      method: "POST",',
    "      headers: {",
    '        authorization: "Bearer " + process.env.STRIPE_SECRET_KEY,',
    '        "content-type": "application/x-www-form-urlencoded"',
    "      },",
    "      body: body.toString()",
    "    });",
    "    const data = (await response.json().catch(() => ({}))) as { id?: string; url?: string; error?: { message?: string } };",
    "    if (!response.ok || !data.url) {",
    '      return { ok: false, reason: (data.error && data.error.message) || ("The payment provider returned " + response.status) };',
    "    }",
    '    return { ok: true, url: data.url, sessionId: data.id || "" };',
    "  } catch {",
    '    return { ok: false, reason: "The payment provider was unreachable." };',
    "  }",
    "}"
  ]);
}

// ---- src/app/api/giving/checkout/route.ts -------------------------------------

function givingCheckoutApiFile(): GeneratedModuleFile {
  return file("src/app/api/giving/checkout/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { createGivingCheckout } from "@/lib/giving-checkout";',
    'import { createRecurringGift, givingEnabled, recordGift } from "@/lib/db/giving";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Ported from OnlineGiving.tsx handleGive (validation + redirect to checkout)",
    "// and stripe_payments.py create_checkout_session (session per gift).",
    "export async function POST(request: Request) {",
    "  if (!givingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const amountCents = typeof body.amountCents === "number" ? Math.round(body.amountCents) : 0;',
    "  if (amountCents < 100) {",
    '    return NextResponse.json({ ok: false, message: "Please enter a valid amount of at least $1." }, { status: 400 });',
    "  }",
    '  const fundName = typeof body.fundName === "string" && body.fundName.trim() ? body.fundName.trim() : "General Fund";',
    '  const donorName = typeof body.donorName === "string" && body.donorName.trim() ? body.donorName.trim() : user.email.split("@")[0];',
    '  const monthly = body.frequency === "monthly";',
    "  const origin = new URL(request.url).origin;",
    "  const checkout = await createGivingCheckout({",
    "    amountCents,",
    "    fundName,",
    "    monthly,",
    '    successUrl: origin + "/giving?status=success",',
    '    cancelUrl: origin + "/giving?status=canceled",',
    "    donorEmail: user.email",
    "  });",
    "  if (!checkout.ok || !checkout.url) {",
    '    return NextResponse.json({ ok: false, message: checkout.reason || "Checkout could not be started." }, { status: 400 });',
    "  }",
    "  // Record the pending gift so the webhook can settle it by session id. Best",
    "  // effort: with no database connected the checkout still works, only history",
    "  // is skipped (same graceful posture as the foundation payments module).",
    "  if (monthly) {",
    '    await createRecurringGift({ donorName, donorEmail: user.email, fundName, amountCents, stripeSessionId: checkout.sessionId || "" });',
    "  } else {",
    '    await recordGift({ donorName, donorEmail: user.email, fundName, amountCents, frequency: "one-time", stripeSessionId: checkout.sessionId || "" });',
    "  }",
    "  return NextResponse.json({ ok: true, url: checkout.url });",
    "}"
  ]);
}

// ---- src/app/api/giving/webhook/route.ts --------------------------------------

function givingWebhookApiFile(): GeneratedModuleFile {
  return file("src/app/api/giving/webhook/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { activateRecurringGift, givingEnabled, markGiftFailed, markGiftPaid } from "@/lib/db/giving";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Stripe webhook for gifts, ported from stripe_payments.py stripe_webhook:",
    "// completed sessions settle the matching gift (by session id, as the source",
    "// tracks by intent id); failed/expired sessions mark it failed. Point a second",
    "// webhook endpoint at /api/giving/webhook — the foundation /api/billing/webhook",
    "// keeps handling product checkouts (ChurchConnect runs multiple Stripe webhook",
    "// routes the same way). Events are acknowledged best effort, matching the",
    "// foundation webhook's posture, so the provider does not retry forever.",
    "export async function POST(request: Request) {",
    "  if (!givingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const payload = await request.text();",
    "  let event: { type?: string; data?: { object?: Record<string, unknown> } } = {};",
    "  try {",
    "    event = JSON.parse(payload);",
    "  } catch {",
    "    return NextResponse.json({ ok: false }, { status: 400 });",
    "  }",
    "  const object = event.data && event.data.object ? event.data.object : {};",
    '  const sessionId = object["id"] ? String(object["id"]) : "";',
    '  if (event.type === "checkout.session.completed") {',
    '    if (object["mode"] === "subscription") await activateRecurringGift(sessionId);',
    "    else await markGiftPaid(sessionId);",
    '  } else if (event.type === "checkout.session.expired" || event.type === "checkout.session.async_payment_failed") {',
    "    await markGiftFailed(sessionId);",
    "  }",
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/giving/gifts/route.ts (donor's own history) ------------------

function givingGiftsApiFile(): GeneratedModuleFile {
  return file("src/app/api/giving/gifts/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { givingEnabled, givingStatsForDonor, listGiftsForDonor } from "@/lib/db/giving";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// A donor's own gifts and yearly totals, ported from OnlineGiving.tsx's",
    "// history view + universal_giving.py get_user_giving_stats.",
    "export async function GET(request: Request) {",
    "  if (!givingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const yearParam = Number(url.searchParams.get("year") || "");',
    "  const year = Number.isInteger(yearParam) && yearParam > 2000 ? yearParam : new Date().getFullYear();",
    "  const [gifts, stats] = await Promise.all([listGiftsForDonor(user.email, year), givingStatsForDonor(user.email, year)]);",
    "  return NextResponse.json({ ok: true, year, gifts, stats });",
    "}"
  ]);
}

// ---- src/app/giving/page.tsx (give + your giving this year) -------------------

function givingPageFile(): GeneratedModuleFile {
  return file("src/app/giving/page.tsx", [
    'import Link from "next/link";',
    'import { getCurrentUser, requireCustomerAccess } from "@/lib/auth/session";',
    'import { formatAmount, givingEnabled, givingStatsForDonor, listFunds, listGiftsForDonor, listRecurringGiftsForDonor } from "@/lib/db/giving";',
    'import { GivingForm } from "./GivingForm";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "// Ported from OnlineGiving.tsx: the give view (preset amounts, designation,",
    "// donor info) plus the history view's Total/Gifts/Average tiles for the year.",
    "export default async function GivingPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ status?: string }>;",
    "}) {",
    "  if (!givingEnabled()) {",
    '    return (<main className="shell"><h1>Giving</h1><p>Giving is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/giving");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    "  const year = new Date().getFullYear();",
    "  const [funds, gifts, stats, recurring] = await Promise.all([",
    "    listFunds(),",
    '    user ? listGiftsForDonor(user.email, year) : Promise.resolve([]),',
    '    user ? givingStatsForDonor(user.email, year) : Promise.resolve({ year, totalCents: 0, giftCount: 0, averageCents: 0 }),',
    '    user ? listRecurringGiftsForDonor(user.email) : Promise.resolve([])',
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Giving</p>',
    "      <h1>Give</h1>",
    "      <p>Choose an amount and a designation. You will be taken to a secure checkout to complete your gift.</p>",
    '      {params?.status === "success" ? (',
    '        <p className="note">Thank you for your generous gift! Your donation has been recorded successfully.</p>',
    "      ) : null}",
    '      {params?.status === "canceled" ? (',
    '        <p className="note">Your gift was canceled. Nothing was charged.</p>',
    "      ) : null}",
    '      <GivingForm funds={funds.map((fund) => ({ id: fund.id, name: fund.name }))} defaultName={user ? user.email.split("@")[0] : ""} />',
    "      <h2>Your giving this year</h2>",
    '      <section className="metric-grid">',
    '        <article className="metric-card"><span>Total Giving</span><strong>{formatAmount(stats.totalCents)}</strong><p>Completed gifts in {year}.</p></article>',
    '        <article className="metric-card"><span>Gifts</span><strong>{stats.giftCount}</strong><p>Number of completed gifts.</p></article>',
    '        <article className="metric-card"><span>Average Gift</span><strong>{formatAmount(stats.averageCents)}</strong><p>Average completed gift.</p></article>',
    "      </section>",
    "      {recurring.length > 0 ? (",
    '        <section className="panel-list">',
    "          {recurring.map((gift) => (",
    '            <article className="wide-card" key={gift.id}>',
    "              <span>{gift.status}</span>",
    "              <strong>{formatAmount(gift.amountCents)} monthly</strong>",
    "              <p>{gift.fundName}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      ) : null}",
    "      {gifts.length === 0 ? (",
    '        <p className="note">No gifts recorded for {year} yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {gifts.map((gift) => (",
    '            <article className="wide-card" key={gift.id}>',
    "              <span>{gift.status}</span>",
    "              <strong>{formatAmount(gift.amountCents)}</strong>",
    '              <p>{gift.fundName}{gift.frequency === "monthly" ? " | Monthly" : ""} | {gift.createdAt ? new Date(gift.createdAt).toLocaleDateString() : ""}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/giving/statement">View your annual giving statement</Link></p>',
    '      <p className="note">Secure checkout. Gifts may be tax-deductible.</p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/giving/GivingForm.tsx (client capture form) ----------------------

function givingFormFile(): GeneratedModuleFile {
  return file("src/app/giving/GivingForm.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { PRESET_AMOUNTS } from "@/lib/db/giving-options";',
    "",
    "// Ported from OnlineGiving.tsx's give view: preset amount grid, custom amount,",
    "// fund designation, minimum $1 validation, then redirect to checkout. Monthly",
    "// gifts come from universal_giving.py's allow_recurring giving links.",
    "export function GivingForm({ funds, defaultName }: { funds: Array<{ id: string; name: string }>; defaultName: string }) {",
    '  const [amount, setAmount] = useState("");',
    '  const [fundName, setFundName] = useState(funds[0]?.name || "General Fund");',
    "  const [donorName, setDonorName] = useState(defaultName);",
    "  const [monthly, setMonthly] = useState(false);",
    "  const [submitting, setSubmitting] = useState(false);",
    '  const [error, setError] = useState("");',
    "",
    "  async function handleGive() {",
    "    const numAmount = parseFloat(amount);",
    "    if (!numAmount || numAmount < 1) {",
    '      setError("Please enter a valid amount of at least $1.");',
    "      return;",
    "    }",
    "    setSubmitting(true);",
    '    setError("");',
    "    try {",
    '      const response = await fetch("/api/giving/checkout", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          amountCents: Math.round(numAmount * 100),",
    "          fundName,",
    "          donorName: donorName.trim(),",
    '          frequency: monthly ? "monthly" : "one-time"',
    "        })",
    "      });",
    "      const data = (await response.json().catch(() => ({}))) as { ok?: boolean; url?: string; message?: string };",
    "      if (data.ok && data.url) {",
    "        window.location.href = data.url;",
    "        return;",
    "      }",
    '      setError(data.message || "Something went wrong. Please try again.");',
    "    } catch {",
    '      setError("Something went wrong. Please try again.");',
    "    }",
    "    setSubmitting(false);",
    "  }",
    "",
    "  return (",
    '    <section className="stack" aria-label="Give a gift">',
    '      <div className="action-row" role="group" aria-label="Suggested amounts">',
    "        {PRESET_AMOUNTS.map((preset) => (",
    "          <button",
    '            className={amount === String(preset) ? "button primary" : "button"}',
    '            key={preset}',
    '            type="button"',
    "            onClick={() => setAmount(String(preset))}",
    "          >",
    "            ${preset}",
    "          </button>",
    "        ))}",
    "      </div>",
    "      <label>",
    "        Amount",
    '        <input className="input" type="number" min="1" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Custom amount" aria-label="Gift amount in dollars" />',
    "      </label>",
    "      <label>",
    "        Designation",
    '        <select className="input" value={fundName} onChange={(event) => setFundName(event.target.value)} aria-label="Fund designation">',
    "          {funds.map((fund) => (",
    "            <option key={fund.id} value={fund.name}>{fund.name}</option>",
    "          ))}",
    "        </select>",
    "      </label>",
    "      <label>",
    "        Your name",
    '        <input className="input" type="text" value={donorName} onChange={(event) => setDonorName(event.target.value)} aria-label="Your name" />',
    "      </label>",
    "      <label>",
    '        <input type="checkbox" checked={monthly} onChange={(event) => setMonthly(event.target.checked)} /> Make this a monthly gift',
    "      </label>",
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    '      <button className="button primary" type="button" onClick={handleGive} disabled={submitting || !amount || parseFloat(amount) < 1}>',
    '        {submitting ? "Starting checkout…" : `Give $${amount || "0"}`}',
    "      </button>",
    "    </section>",
    "  );",
    "}"
  ]);
}

// ---- src/app/giving/statement/page.tsx (annual statement) ---------------------

function givingStatementPageFile(): GeneratedModuleFile {
  return file("src/app/giving/statement/page.tsx", [
    'import Link from "next/link";',
    'import { getCurrentUser, requireCustomerAccess } from "@/lib/auth/session";',
    'import { formatAmount, fundTotalsForYear, givingEnabled, givingStatsForDonor } from "@/lib/db/giving";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "// Annual giving statement grouped by fund, ported from universal_giving.py",
    "// get_user_giving_stats and OnlineGiving.tsx's per-year history (last five",
    "// years selectable, like its year dropdown).",
    "export default async function GivingStatementPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ year?: string }>;",
    "}) {",
    "  if (!givingEnabled()) {",
    '    return (<main className="shell"><h1>Giving</h1><p>Giving is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/giving/statement");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    "  const currentYear = new Date().getFullYear();",
    '  const requested = Number(params?.year || "");',
    "  const year = Number.isInteger(requested) && requested > 2000 && requested <= currentYear ? requested : currentYear;",
    "  const years = Array.from({ length: 5 }, (_, index) => currentYear - index);",
    "  const [lines, stats] = await Promise.all([",
    '    user ? fundTotalsForYear(year, user.email) : Promise.resolve([]),',
    '    user ? givingStatsForDonor(user.email, year) : Promise.resolve({ year, totalCents: 0, giftCount: 0, averageCents: 0 })',
    "  ]);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Giving</p>',
    "      <h1>Annual Giving Statement</h1>",
    "      <p>Completed gifts for {year}{user ? ` recorded for ${user.email}` : \"\"}. Keep this for your records.</p>",
    '      <div className="action-row">',
    "        {years.map((option) => (",
    '          <Link className={option === year ? "button primary" : "button"} key={option} href={`/giving/statement?year=${option}`}>{option}</Link>',
    "        ))}",
    "      </div>",
    '      <section className="metric-grid">',
    '        <article className="metric-card"><span>Total Giving</span><strong>{formatAmount(stats.totalCents)}</strong><p>All completed gifts in {year}.</p></article>',
    '        <article className="metric-card"><span>Gifts</span><strong>{stats.giftCount}</strong><p>Completed gifts in {year}.</p></article>',
    "      </section>",
    "      {lines.length === 0 ? (",
    '        <p className="note">No completed gifts recorded for {year}.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {lines.map((line) => (",
    '            <article className="wide-card" key={line.fundName}>',
    "              <span>{line.giftCount} {line.giftCount === 1 ? \"gift\" : \"gifts\"}</span>",
    "              <strong>{line.fundName}</strong>",
    "              <p>{formatAmount(line.totalCents)}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/giving">Back to giving</Link></p>',
    '      <p className="note">Gifts may be tax-deductible. Contact your administrator for an official receipt.</p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/admin/giving/page.tsx (fund totals + recent gifts) ---------------

function givingAdminPageFile(): GeneratedModuleFile {
  return file("src/app/admin/giving/page.tsx", [
    'import { requireAdminAccess } from "@/lib/auth/session";',
    'import { countActiveRecurringGifts, formatAmount, fundTotalsForYear, givingEnabled, listRecentGifts } from "@/lib/db/giving";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "// Admin view of giving: per-fund totals for the year, active recurring gifts,",
    "// and the latest gifts — ported from ChurchConnect's GivingReports breakdown.",
    "export default async function AdminGivingPage() {",
    "  if (!givingEnabled()) {",
    '    return (<main className="shell"><h1>Giving</h1><p>Giving is turned off for this app.</p></main>);',
    "  }",
    '  await requireAdminAccess("/admin/giving");',
    "  const year = new Date().getFullYear();",
    "  const [totals, recent, activeRecurring] = await Promise.all([fundTotalsForYear(year), listRecentGifts(25), countActiveRecurringGifts()]);",
    "  const totalCents = totals.reduce((sum, line) => sum + line.totalCents, 0);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Giving</h1>",
    "      <p>Fund totals, recurring gifts, and the latest activity for {year}.</p>",
    '      <section className="metric-grid">',
    '        <article className="metric-card"><span>Total Giving</span><strong>{formatAmount(totalCents)}</strong><p>Completed gifts in {year}.</p></article>',
    '        <article className="metric-card"><span>Funds</span><strong>{totals.length}</strong><p>Funds that received gifts.</p></article>',
    '        <article className="metric-card"><span>Recurring</span><strong>{activeRecurring}</strong><p>Active monthly gifts.</p></article>',
    "      </section>",
    "      {totals.length === 0 ? (",
    '        <p className="note">No completed gifts recorded for {year} yet.</p>',
    "      ) : (",
    '        <section className="grid">',
    "          {totals.map((line) => (",
    '            <article className="card" key={line.fundName}>',
    "              <span>{line.giftCount} {line.giftCount === 1 ? \"gift\" : \"gifts\"}</span>",
    "              <strong>{line.fundName}</strong>",
    "              <p>{formatAmount(line.totalCents)}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      {recent.length > 0 ? (",
    '        <section className="panel-list">',
    "          {recent.map((gift) => (",
    '            <article className="wide-card" key={gift.id}>',
    "              <span>{gift.status}</span>",
    "              <strong>{formatAmount(gift.amountCents)} — {gift.fundName}</strong>",
    '              <p>{gift.donorName || "Anonymous"}{gift.frequency === "monthly" ? " | Monthly" : ""} | {gift.createdAt ? new Date(gift.createdAt).toLocaleDateString() : ""}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      ) : null}",
    "    </main>",
    "  );",
    "}"
  ]);
}

export const paymentsBillingModule: AppModule = {
  slug: "payments-billing",
  name: "Payments, Billing & Giving",
  tier: "optional",
  featureFlagEnv: "FEATURE_GIVING",
  files: () => [
    givingOptionsFile(),
    givingLibFile(),
    givingCheckoutLibFile(),
    givingCheckoutApiFile(),
    givingWebhookApiFile(),
    givingGiftsApiFile(),
    givingPageFile(),
    givingFormFile(),
    givingStatementPageFile(),
    givingAdminPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists payments_billing_funds (",
      "  id uuid primary key default gen_random_uuid(),",
      "  name text not null,",
      "  description text not null default '',",
      "  active boolean not null default true,",
      "  created_at timestamptz not null default now()",
      ");",
      "create unique index if not exists payments_billing_funds_name_idx on payments_billing_funds (lower(name));",
      "",
      "create table if not exists payments_billing_gifts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  donor_name text not null default 'Anonymous',",
      "  donor_email text not null default '',",
      "  fund_name text not null default 'General Fund',",
      "  amount_cents integer not null default 0,",
      "  frequency text not null default 'one-time',",
      "  status text not null default 'pending',",
      "  stripe_session_id text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists payments_billing_gifts_donor_idx on payments_billing_gifts (lower(donor_email), created_at);",
      "create index if not exists payments_billing_gifts_session_idx on payments_billing_gifts (stripe_session_id);",
      "",
      "create table if not exists payments_billing_recurring_gifts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  donor_name text not null default 'Anonymous',",
      "  donor_email text not null default '',",
      "  fund_name text not null default 'General Fund',",
      "  amount_cents integer not null default 0,",
      "  status text not null default 'pending',",
      "  stripe_session_id text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists payments_billing_recurring_donor_idx on payments_billing_recurring_gifts (lower(donor_email));"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Default designations, ported from OnlineGiving.tsx's fund selector.",
      "insert into payments_billing_funds (name, description) values",
      "  ('General Fund', 'Where it is needed most.'),",
      "  ('Tithes', 'Regular tithes and offerings.'),",
      "  ('Missions', 'Local and global mission work.'),",
      "  ('Building Fund', 'Facilities and building projects.')",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Payments, Billing & Giving — online giving on the app owner's own Stripe",
    "# account. Uses the same STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET as the",
    "# foundation payments module (see below). Set to false to switch giving off.",
    "FEATURE_GIVING=true"
  ],
  homeLinks: () => ['        <a className="button" href="/giving">Give</a>'],
  navLinks: () => [{ href: "/giving", label: "Give" }],
  requiredEnv: ["STRIPE_SECRET_KEY"]
};
