// proof-approval-artifact — generate + preserve an immutable customer approval
// proof (a signed-off snapshot) before customized physical work is produced.
// Ported from LaserEngraving's real design-sharing/approval system:
//   - the design_shares model (backend/app/routers/extended_router.py create_share
//     + supabase/migrations/20260206030246_add_design_sharing.sql): id, design_id,
//     created_by, share_code, title, description, share_type
//     ['registry'|'brand'|'general'], is_active, view_count, use_count, created_at,
//     expires_at — plus the saved_designs.design_data snapshot the share points at.
//   - create_share: mint a URL-safe code (secrets.token_urlsafe(8)) for a design the
//     caller owns, optional expires_in_days, counters start at 0.
//   - get_share (byCode, SharedDesignLanding.tsx): resolve an ACTIVE, un-expired
//     share by code, bump view_count, return {share, design}; 410 when expired.
//   - "use design" (SharedDesignLanding.handleUseDesign): bump use_count when the
//     recipient acts on the shared design.
//   - list_my_shares (Shares.mine / ShareDesignDialog.tsx): the owner's own shares,
//     newest first, with per-link view/use stats + an active/disabled toggle.
//   - delete_share (Shares.remove): the owner removes their own share.
// Reframed off the share-link framing onto the approval-proof capability it really
// implements: the share_code is the PROOF CODE, the design_data is the immutable
// SNAPSHOT captured at approval time, view_count is proof-views, and use_count
// becomes the customer's recorded SIGN-OFF (approved) — the moment the snapshot is
// locked and physical work may proceed. Runs on the app owner's own database with
// graceful sample-data fallback, feature-flagged (FEATURE_PROOF); customers create
// proofs for their own work + sign them off, admins see every proof.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/proof.ts (model + queries, ported from extended_router.py) ---

function proofLibFile(): GeneratedModuleFile {
  return file("src/lib/db/proof.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    'import { randomBytes } from "crypto";',
    "",
    "// An approval proof, ported from LaserEngraving's design_shares row + the",
    "// saved_designs.design_data snapshot it points at. A proof pairs a public,",
    "// hard-to-guess code with an IMMUTABLE snapshot of exactly what the customer is",
    "// approving, so once signed off nobody can quietly change what was agreed.",
    'export type ProofStatus = "pending" | "approved" | "revised" | "expired";',
    "",
    "// The kind of work being signed off, ported verbatim from design_shares.share_type",
    "// ('registry' | 'brand' | 'general'), generalized off the laser framing.",
    'export type ProofKind = "registry" | "brand" | "general";',
    "",
    "export type ApprovalProof = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  proofCode: string;",
    "  title: string;",
    "  description: string;",
    "  kind: ProofKind;",
    "  // The immutable snapshot of what is being approved (ported from design_data).",
    "  snapshot: Record<string, unknown>;",
    "  isActive: boolean;",
    "  viewCount: number;",
    "  // Ported from use_count: bumped when the customer records their sign-off.",
    "  approvalCount: number;",
    "  approvedByName: string;",
    "  approvedAt: string;",
    "  createdAt: string;",
    "  expiresAt: string | null;",
    "};",
    "",
    "export type ProofFilters = { q?: string; kind?: string; ownerId?: string; limit?: number };",
    "",
    "// The proof kinds a customer can pick, ported from ShareDesignDialog's typeOptions.",
    "export const PROOF_KINDS: ProofKind[] = [\"registry\", \"brand\", \"general\"];",
    "",
    "export function kindLabel(kind: string): string {",
    "  switch (kind) {",
    '    case "registry": return "Registry / event";',
    '    case "brand": return "Brand / company";',
    '    default: return "General";',
    "  }",
    "}",
    "",
    "// Mint a URL-safe proof code, ported from create_share's secrets.token_urlsafe(8)",
    "// (8 random bytes, base64url, no padding) — short, unguessable, safe in a link.",
    "export function generateProofCode(): string {",
    '  return randomBytes(8).toString("base64").replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");',
    "}",
    "",
    "// Whether a proof has passed its optional expiry, ported from get_share's",
    "// expires_at check (expired links are 410 / no longer approvable).",
    "export function isExpired(expiresAt: string | null): boolean {",
    "  if (!expiresAt) return false;",
    "  const ts = new Date(expiresAt).getTime();",
    "  if (Number.isNaN(ts)) return false;",
    "  return ts < Date.now();",
    "}",
    "",
    "export function proofStatus(p: Pick<ApprovalProof, \"isActive\" | \"expiresAt\" | \"approvalCount\">): ProofStatus {",
    '  if (isExpired(p.expiresAt)) return "expired";',
    '  if (p.approvalCount > 0) return "approved";',
    '  if (!p.isActive) return "revised";',
    '  return "pending";',
    "}",
    "",
    "const fallbackProofs: ApprovalProof[] = [",
    "  {",
    '    id: "sample-1",',
    "    ownerId: null,",
    '    proofCode: "demo-approved",',
    "    title: \"Sarah & Tom's engraved cutting board\",",
    '    description: "Final layout before we cut. Please confirm the names and date are exactly right.",',
    '    kind: "registry",',
    '    snapshot: { elements: [{ type: "text", value: "Sarah & Tom" }, { type: "text", value: "06.14.2025" }], material: "walnut" },',
    "    isActive: true,",
    "    viewCount: 12,",
    "    approvalCount: 1,",
    '    approvedByName: "Sarah M.",',
    '    approvedAt: "2025-05-02T00:00:00.000Z",',
    '    createdAt: "2025-05-01T00:00:00.000Z",',
    "    expiresAt: null",
    "  },",
    "  {",
    '    id: "sample-2",',
    "    ownerId: null,",
    '    proofCode: "demo-pending",',
    '    title: "Northwind Coffee — logo tumblers",',
    '    description: "Proof of the logo placement across the run of 40 tumblers.",',
    '    kind: "brand",',
    '    snapshot: { elements: [{ type: "logo", value: "northwind-mark" }], material: "steel", quantity: 40 },',
    "    isActive: true,",
    "    viewCount: 3,",
    "    approvalCount: 0,",
    '    approvedByName: "",',
    '    approvedAt: "",',
    '    createdAt: "2025-05-10T00:00:00.000Z",',
    "    expiresAt: null",
    "  }",
    "];",
    "",
    "function toSnapshot(v: unknown): Record<string, unknown> {",
    '  if (v && typeof v === "object" && !Array.isArray(v)) return v as Record<string, unknown>;',
    '  if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return p && typeof p === "object" ? p : {}; } catch { return {}; } }',
    "  return {};",
    "}",
    "",
    "function rowToProof(row: Record<string, unknown>): ApprovalProof {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    proofCode: String(row.proof_code || ""),',
    '    title: String(row.title || ""),',
    '    description: String(row.description || ""),',
    '    kind: (String(row.kind || "general") as ProofKind),',
    "    snapshot: toSnapshot(row.snapshot),",
    '    isActive: row.is_active === true || String(row.is_active) === "true",',
    "    viewCount: Number(row.view_count || 0),",
    "    approvalCount: Number(row.approval_count || 0),",
    '    approvedByName: String(row.approved_by_name || ""),',
    '    approvedAt: row.approved_at ? String(row.approved_at) : "",',
    '    createdAt: row.created_at ? String(row.created_at) : "",',
    "    expiresAt: row.expires_at ? String(row.expires_at) : null",
    "  };",
    "}",
    "",
    "// The owner's own proofs, ported from list_my_shares (Shares.mine): scoped to the",
    "// creator, newest first. Admins pass no ownerId to see every proof.",
    "export async function listProofs(filters: ProofFilters = {}): Promise<ApprovalProof[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const kind = (filters.kind || "").trim();',
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackProofs",
    "      .filter((p) => !ownerId || p.ownerId === ownerId)",
    '      .filter((p) => !kind || kind === "all" || p.kind === kind)',
    '      .filter((p) => !q || (p.title + " " + p.description).toLowerCase().includes(q))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    '    const kd = kind && kind !== "all" ? kind : null;',
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "        view_count, approval_count, approved_by_name, approved_at, created_at, expires_at",
    "      from proof_approval_artifact_proofs",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${kd}::text is null or kind = ${kd})",
    "        and (${like}::text is null",
    "          or lower(title) like ${like}",
    "          or lower(description) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToProof);",
    "  } catch {",
    "    return fallbackProofs.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getProof(id: string): Promise<ApprovalProof | null> {",
    "  if (!hasDatabase()) return fallbackProofs.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "        view_count, approval_count, approved_by_name, approved_at, created_at, expires_at",
    "      from proof_approval_artifact_proofs where id = ${id} limit 1`;",
    "    return rows[0] ? rowToProof(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Resolve a proof by its public code + bump the view counter, ported from",
    "// get_share (byCode): only ACTIVE, un-expired proofs resolve; viewing an expired",
    "// proof returns { expired: true } instead of the record (get_share's 410).",
    "export async function getProofByCode(code: string): Promise<{ proof: ApprovalProof | null; expired: boolean }> {",
    "  if (!hasDatabase()) {",
    "    const p = fallbackProofs.find((x) => x.proofCode === code && x.isActive) || null;",
    "    if (p && isExpired(p.expiresAt)) return { proof: null, expired: true };",
    "    return { proof: p, expired: false };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "        view_count, approval_count, approved_by_name, approved_at, created_at, expires_at",
    "      from proof_approval_artifact_proofs",
    "      where proof_code = ${code} and is_active = true limit 1`;",
    "    if (!rows[0]) return { proof: null, expired: false };",
    "    const proof = rowToProof(rows[0]);",
    "    if (isExpired(proof.expiresAt)) return { proof: null, expired: true };",
    "    // Ported from get_share: bump view_count on every open of the proof link.",
    "    await sql`update proof_approval_artifact_proofs set view_count = view_count + 1 where id = ${proof.id}`;",
    "    return { proof: { ...proof, viewCount: proof.viewCount + 1 }, expired: false };",
    "  } catch {",
    "    return { proof: null, expired: false };",
    "  }",
    "}",
    "",
    "export type CreateProofInput = {",
    "  ownerId: string | null;",
    "  title: string;",
    "  description?: string;",
    "  kind?: ProofKind;",
    "  snapshot?: Record<string, unknown>;",
    "  expiresInDays?: number | null;",
    "};",
    "",
    "// Create a proof, ported from create_share: mint a code, capture the immutable",
    "// snapshot, optional expiry (expires_in_days), counters start at 0, is_active=true.",
    "export async function createProof(input: CreateProofInput): Promise<ApprovalProof | null> {",
    "  if (!hasDatabase()) return null;",
    "  const code = generateProofCode();",
    '  const kind: ProofKind = input.kind || "general";',
    "  const snapshot = JSON.stringify(input.snapshot || {});",
    "  const days = input.expiresInDays && input.expiresInDays > 0 ? Math.floor(input.expiresInDays) : null;",
    "  try {",
    "    const sql = getDatabase();",
    "    // expires_at is now() + N days when a window is set, else null (never expires),",
    "    // ported from create_share's expires computation.",
    "    const rows = days",
    "      ? await sql`",
    "          insert into proof_approval_artifact_proofs (",
    "            owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "            view_count, approval_count, expires_at",
    "          ) values (",
    '            ${input.ownerId || null}, ${code}, ${input.title}, ${input.description || ""},',
    "            ${kind}, ${snapshot}::jsonb, true, 0, 0, now() + (${days} || ' days')::interval",
    "          )",
    "          returning id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "            view_count, approval_count, approved_by_name, approved_at, created_at, expires_at`",
    "      : await sql`",
    "          insert into proof_approval_artifact_proofs (",
    "            owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "            view_count, approval_count, expires_at",
    "          ) values (",
    '            ${input.ownerId || null}, ${code}, ${input.title}, ${input.description || ""},',
    "            ${kind}, ${snapshot}::jsonb, true, 0, 0, null",
    "          )",
    "          returning id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "            view_count, approval_count, approved_by_name, approved_at, created_at, expires_at`;",
    "    return rows[0] ? rowToProof(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Record the customer's SIGN-OFF, ported from use_count bump (handleUseDesign):",
    "// this is the loop-closer — the snapshot is now approved and physical work may",
    "// proceed. We stamp who approved + when and lock the proof (is_active=false so it",
    "// can never be re-opened for edits). Only pending, active, un-expired proofs can be",
    "// signed off. Returns the sealed proof, or null if it was not approvable.",
    "export async function approveProof(code: string, approvedByName: string): Promise<ApprovalProof | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      update proof_approval_artifact_proofs",
    "      set approval_count = approval_count + 1,",
    "          approved_by_name = ${approvedByName || \"Customer\"},",
    "          approved_at = now(),",
    "          is_active = false",
    "      where proof_code = ${code} and is_active = true and approval_count = 0",
    "        and (expires_at is null or expires_at > now())",
    "      returning id, owner_id, proof_code, title, description, kind, snapshot, is_active,",
    "        view_count, approval_count, approved_by_name, approved_at, created_at, expires_at`;",
    "    return rows[0] ? rowToProof(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Deactivate a proof, ported from ShareDesignDialog's active/disabled toggle:",
    "// pulls a sent-but-not-yet-approved proof back so a revised one can be issued.",
    "// Approved (locked) proofs are immutable and cannot be reactivated.",
    "export async function deactivateProof(id: string, ownerId: string | null): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    if (ownerId) {",
    "      await sql`update proof_approval_artifact_proofs set is_active = false where id = ${id} and owner_id = ${ownerId} and approval_count = 0`;",
    "    } else {",
    "      await sql`update proof_approval_artifact_proofs set is_active = false where id = ${id} and approval_count = 0`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Remove a proof, ported from delete_share (Shares.remove): the owner deletes their",
    "// own. Scoped by owner unless the caller is an admin (ownerId omitted).",
    "export async function deleteProof(id: string, ownerId: string | null): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    if (ownerId) {",
    "      await sql`delete from proof_approval_artifact_proofs where id = ${id} and owner_id = ${ownerId}`;",
    "    } else {",
    "      await sql`delete from proof_approval_artifact_proofs where id = ${id}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function proofEnabled(): boolean {",
    '  return process.env.FEATURE_PROOF !== "false";',
    "}"
  ]);
}

// ---- src/app/api/proofs/route.ts (list + create) ----------------------------

function proofApiFile(): GeneratedModuleFile {
  return file("src/app/api/proofs/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listProofs, createProof, proofEnabled } from "@/lib/db/proof";',
    'import type { ProofKind } from "@/lib/db/proof";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!proofEnabled()) return NextResponse.json({ ok: false, message: "Approval proofs are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  // Customers see only the proofs they created; admins see every proof.",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const proofs = await listProofs({",
    '    q: url.searchParams.get("q") || undefined,',
    '    kind: url.searchParams.get("kind") || undefined,',
    "    ownerId",
    "  });",
    "  return NextResponse.json({ ok: true, proofs });",
    "}",
    "",
    "// Create a proof, ported from create_share. Scoped to the signed-in owner.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to create a proof." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give the proof a title so the customer knows what they are approving." }, { status: 400 });',
    "  }",
    '  const kind: ProofKind = body.kind === "registry" || body.kind === "brand" ? body.kind : "general";',
    '  const snapshot = body.snapshot && typeof body.snapshot === "object" && !Array.isArray(body.snapshot)',
    "    ? (body.snapshot as Record<string, unknown>)",
    "    : {};",
    '  const expiresInDays = typeof body.expiresInDays === "number" && body.expiresInDays > 0 ? body.expiresInDays : null;',
    "  const created = await createProof({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    title,",
    '    description: typeof body.description === "string" ? body.description : undefined,',
    "    kind,",
    "    snapshot,",
    "    expiresInDays",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save approval proofs." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, proof: created, message: "Proof created. Share the link with your customer to get their sign-off." });',
    "}"
  ]);
}

// ---- src/app/api/proofs/[id]/route.ts (detail + deactivate + delete) --------

function proofDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/proofs/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getProof, deactivateProof, deleteProof, proofEnabled } from "@/lib/db/proof";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!proofEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const proof = await getProof(id);",
    '  if (!proof) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Customers may only read the proofs they created.",
    "  if (!canAccessAdmin(user?.role) && proof.ownerId && proof.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, proof });",
    "}",
    "",
    "// Deactivate (pull back) a proof so a revised one can be issued — the owner or an",
    "// admin. Ported from ShareDesignDialog's active/disabled toggle. Approved proofs",
    "// are immutable and cannot be pulled back (enforced in deactivateProof).",
    "export async function PATCH(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const proof = await getProof(id);",
    '  if (!proof) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  if (!canAccessAdmin(user?.role) && proof.ownerId && proof.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const ownerScope = canAccessAdmin(user?.role) ? null : (user?.id ? String(user.id) : null);",
    "  const ok = await deactivateProof(id, ownerScope);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update proofs." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}",
    "",
    "// Delete a proof, ported from delete_share (admins only — deleting an approval",
    "// record is destructive; customers deactivate instead).",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const ok = await deleteProof(id, null);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to delete proofs." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/proofs/code/[code]/route.ts (public resolve + sign-off) -----

function proofCodeApiFile(): GeneratedModuleFile {
  return file("src/app/api/proofs/code/[code]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getProofByCode, approveProof, proofEnabled } from "@/lib/db/proof";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Resolve a proof by its public code + bump view_count, ported from get_share.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ code: string }> }) {",
    '  if (!proofEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { code } = await params;",
    "  const { proof, expired } = await getProofByCode(code);",
    '  if (expired) return NextResponse.json({ ok: false, expired: true, message: "This proof has expired. Ask for a fresh one." }, { status: 410 });',
    '  if (!proof) return NextResponse.json({ ok: false, message: "Proof not found or no longer active." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, proof });",
    "}",
    "",
    "// Record the customer's sign-off, ported from the use_count bump (handleUseDesign).",
    "// Sealing the proof locks the snapshot; physical work may now proceed.",
    "export async function POST(request: Request, { params }: { params: Promise<{ code: string }> }) {",
    '  if (!proofEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to approve this proof." }, { status: 401 });',
    "  const { code } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.approvedByName === "string" && body.approvedByName.trim()',
    "    ? body.approvedByName.trim()",
    '    : (user?.name || "Customer");',
    "  const sealed = await approveProof(code, name);",
    '  if (!sealed) return NextResponse.json({ ok: false, message: "This proof could not be approved — it may be expired, already signed off, or pulled back." }, { status: 409 });',
    '  return NextResponse.json({ ok: true, proof: sealed, message: "Signed off. Thank you — this is now locked and work can begin." });',
    "}"
  ]);
}

// ---- src/app/proofs/page.tsx (owner list + create) --------------------------

function proofPageFile(): GeneratedModuleFile {
  return file("src/app/proofs/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listProofs, proofStatus, kindLabel, proofEnabled } from "@/lib/db/proof";',
    'import { CreateProofForm } from "./create-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ProofsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; kind?: string }>;",
    "}) {",
    "  if (!proofEnabled()) {",
    '    return (<main className="shell"><h1>Approval proofs</h1><p>Approval proofs are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/proofs");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const kind = (params?.kind || "").trim();',
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = isAdmin ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const proofs = await listProofs({ q: q || undefined, kind: kind || undefined, ownerId });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Approval proofs</p>',
    "      <h1>Sign-off before you make it</h1>",
    "      <p>Lock in exactly what the customer approved before any customized work is produced. Each proof captures an immutable snapshot and a shareable sign-off link.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search proofs by title" aria-label="Search proofs" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {proofs.length === 0 ? (",
    '        <p className="note">{q ? `No proofs match "${q}" yet.` : "No proofs yet. Create your first one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {proofs.map((proof) => {",
    "            const status = proofStatus(proof);",
    "            return (",
    '              <Link className="wide-card" key={proof.id} href={`/proofs/${proof.id}`}>',
    "                <span>{status}</span>",
    "                <strong>{proof.title}</strong>",
    "                {proof.description ? <p>{proof.description}</p> : null}",
    '                <p className="note">',
    "                  {kindLabel(proof.kind)} · {proof.viewCount} views",
    '                  {proof.approvalCount > 0 ? ` · signed off by ${proof.approvedByName || "customer"}` : ""}',
    "                </p>",
    "              </Link>",
    "            );",
    "          })}",
    "        </section>",
    "      )}",
    "      <h2>Create an approval proof</h2>",
    "      <p>Give it a title, tell the customer what to check, and share the link. Nothing is produced until they sign off.</p>",
    "      <CreateProofForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/proofs/create-form.tsx (client) --------------------------------

function createFormFile(): GeneratedModuleFile {
  return file("src/app/proofs/create-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Ported from ShareDesignDialog's create form: a title, an optional note for the",
    "// customer, and the proof kind (registry / brand / general).",
    "export function CreateProofForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    '  const [code, setCode] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    '    const rawSnapshot = String(form.get("snapshot") || "").trim();',
    "    let snapshot: Record<string, unknown> = {};",
    "    if (rawSnapshot) {",
    '      try { const parsed = JSON.parse(rawSnapshot); if (parsed && typeof parsed === "object") snapshot = parsed; }',
    '      catch { snapshot = { notes: rawSnapshot }; }',
    "    }",
    "    try {",
    '      const response = await fetch("/api/proofs", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          description: form.get("description"),',
    '          kind: form.get("kind"),',
    "          snapshot",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Proof created.");',
    '      setCode(data.proof?.proofCode || "");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    '    const link = code ? `/proof/${code}` : "";',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Created</p>',
    "        <p>{message}</p>",
    '        {link ? <p className="note">Share this sign-off link with your customer: <code>{link}</code></p> : null}',
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="What is being approved? (e.g. Sarah & Tom\'s cutting board)" aria-label="Proof title" required />',
    '      <textarea className="input" name="description" rows={2} placeholder="Tell the customer exactly what to check before they sign off" aria-label="Instructions" />',
    '      <textarea className="input" name="snapshot" rows={4} placeholder=\'Optional: the exact spec to lock in (paste JSON, or plain notes)\' aria-label="Snapshot" />',
    '      <select className="input" name="kind" aria-label="Proof kind" defaultValue="general">',
    '        <option value="general">General</option>',
    '        <option value="registry">Registry / event</option>',
    '        <option value="brand">Brand / company</option>',
    "      </select>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Creating…" : "Create proof"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/proofs/[id]/page.tsx (owner detail + snapshot + controls) ------

function proofDetailPageFile(): GeneratedModuleFile {
  return file("src/app/proofs/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getProof, proofStatus, kindLabel, proofEnabled } from "@/lib/db/proof";',
    'import { ProofControls } from "./proof-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ProofDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!proofEnabled()) {",
    '    return (<main className="shell"><h1>Approval proofs</h1><p>Approval proofs are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/proofs");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const proof = await getProof(id);",
    "  if (!proof) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && proof.ownerId && proof.ownerId !== String(user?.id)) notFound();",
    "  const status = proofStatus(proof);",
    "  const snapshotText = JSON.stringify(proof.snapshot, null, 2);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{status}</p>',
    "      <h1>{proof.title}</h1>",
    "      {proof.description ? <p>{proof.description}</p> : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Kind</span><strong>{kindLabel(proof.kind)}</strong></article>',
    '        <article className="card"><span>Views</span><strong>{proof.viewCount}</strong></article>',
    '        <article className="card"><span>Signed off</span><strong>{proof.approvalCount > 0 ? "Yes" : "No"}</strong></article>',
    '        <article className="card"><span>Expires</span><strong>{proof.expiresAt ? new Date(proof.expiresAt).toLocaleDateString() : "Never"}</strong></article>',
    "      </section>",
    "      {proof.approvalCount > 0 ? (",
    '        <p className="note" role="status">Signed off by {proof.approvedByName || "the customer"}{proof.approvedAt ? ` on ${new Date(proof.approvedAt).toLocaleString()}` : ""}. This snapshot is locked.</p>',
    "      ) : null}",
    "      <h2>The locked snapshot</h2>",
    "      <p>This is the exact, immutable record of what is being approved. It cannot change once the customer signs off.</p>",
    '      <pre className="media" style={{ whiteSpace: "pre-wrap", overflowX: "auto" }}>{snapshotText}</pre>',
    '      <p className="note">Customer sign-off link: <code>{`/proof/${proof.proofCode}`}</code></p>',
    "      <ProofControls id={proof.id} code={proof.proofCode} signedOff={proof.approvalCount > 0} isAdmin={isAdmin} />",
    '      <p><Link className="button" href="/proofs">Back to proofs</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/proofs/[id]/proof-controls.tsx (client) ------------------------

function proofControlsFile(): GeneratedModuleFile {
  return file("src/app/proofs/[id]/proof-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Owner/admin controls, ported from ShareDesignDialog's active toggle + delete.",
    "// A signed-off proof is immutable: pull-back and delete are hidden once locked.",
    "export function ProofControls({ id, code, signedOff, isAdmin }: { id: string; code: string; signedOff: boolean; isAdmin: boolean }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    '  const [copied, setCopied] = useState(false);',
    "",
    "  function copyLink() {",
    "    try {",
    "      const url = `${window.location.origin}/proof/${code}`;",
    "      navigator.clipboard.writeText(url);",
    "      setCopied(true);",
    "      setTimeout(() => setCopied(false), 2000);",
    "    } catch {",
    "      // clipboard is best-effort.",
    "    }",
    "  }",
    "",
    "  async function pullBack() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/proofs/${id}`, { method: "PATCH" });',
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not pull back this proof.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  async function remove() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch(`/api/proofs/${id}`, { method: "DELETE" });',
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not delete this proof.");',
    "        return;",
    "      }",
    '      router.push("/proofs");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className="button" type="button" onClick={copyLink}>{copied ? "Copied" : "Copy sign-off link"}</button>',
    "      {!signedOff ? (",
    '        <button className="button" type="button" onClick={pullBack} disabled={status === "working"}>Pull back to revise</button>',
    "      ) : null}",
    "      {isAdmin ? (",
    '        <button className="button" type="button" onClick={remove} disabled={status === "working"}>Delete proof</button>',
    "      ) : null}",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/proof/[code]/page.tsx (customer sign-off landing) --------------

function proofLandingPageFile(): GeneratedModuleFile {
  return file("src/app/proof/[code]/page.tsx", [
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getProofByCode, kindLabel, isExpired, proofEnabled } from "@/lib/db/proof";',
    'import { SignOffPanel } from "./sign-off-panel";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "// The customer sign-off landing, ported from SharedDesignLanding.tsx: open the",
    "// proof by its code (which bumps view_count), show the immutable snapshot, and",
    "// let the customer sign off — the moment work is cleared to begin.",
    "export default async function ProofLandingPage({ params }: { params: Promise<{ code: string }> }) {",
    "  if (!proofEnabled()) {",
    '    return (<main className="shell"><h1>Approval proof</h1><p>Approval proofs are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/proofs");',
    "  const { code } = await params;",
    "  const { proof, expired } = await getProofByCode(code);",
    "",
    "  if (expired) {",
    "    return (",
    '      <main className="shell">',
    '        <p className="eyebrow">Approval proof</p>',
    "        <h1>This proof has expired</h1>",
    "        <p>Ask whoever sent it for a fresh sign-off link.</p>",
    "      </main>",
    "    );",
    "  }",
    "  if (!proof) {",
    "    return (",
    '      <main className="shell">',
    '        <p className="eyebrow">Approval proof</p>',
    "        <h1>Proof not available</h1>",
    "        <p>This sign-off link is no longer active. It may have been pulled back to be revised.</p>",
    "      </main>",
    "    );",
    "  }",
    "",
    "  const alreadySigned = proof.approvalCount > 0;",
    "  const snapshotText = JSON.stringify(proof.snapshot, null, 2);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{kindLabel(proof.kind)} · Approval proof</p>',
    "      <h1>{proof.title}</h1>",
    "      {proof.description ? <p>{proof.description}</p> : null}",
    "      <h2>Please review carefully</h2>",
    "      <p>Once you sign off, this is locked and we begin producing exactly what you see here. Check every detail.</p>",
    '      <pre className="media" style={{ whiteSpace: "pre-wrap", overflowX: "auto" }}>{snapshotText}</pre>',
    "      {alreadySigned ? (",
    '        <section className="panel" aria-live="polite">',
    '          <p className="eyebrow">Signed off</p>',
    '          <p>Approved by {proof.approvedByName || "you"}{proof.approvedAt ? ` on ${new Date(proof.approvedAt).toLocaleString()}` : ""}. This proof is locked and work is underway.</p>',
    "        </section>",
    "      ) : isExpired(proof.expiresAt) ? (",
    '        <p className="note">This proof has expired and can no longer be signed off.</p>',
    "      ) : (",
    "        <SignOffPanel code={proof.proofCode} />",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/proof/[code]/sign-off-panel.tsx (client) -----------------------

function signOffPanelFile(): GeneratedModuleFile {
  return file("src/app/proof/[code]/sign-off-panel.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The customer's sign-off action, ported from SharedDesignLanding.handleUseDesign",
    "// (the use_count bump): typing your name and confirming records an immutable,",
    "// timestamped approval and seals the proof.",
    "export function SignOffPanel({ code }: { code: string }) {",
    "  const router = useRouter();",
    '  const [name, setName] = useState("");',
    '  const [confirmed, setConfirmed] = useState(false);',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function signOff(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    if (!confirmed) return;",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/proofs/code/${code}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ approvedByName: name })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not record your sign-off. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Signed off. Thank you.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Signed off</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={signOff}>',
    '      <input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Type your name to sign" aria-label="Your name" required />',
    '      <label className="check"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> I have reviewed everything above and approve it exactly as shown.</label>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving" || !confirmed || name.trim().length < 2}>',
    '        {status === "saving" ? "Recording…" : "Approve & lock this proof"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

export const proofApprovalModule: AppModule = {
  slug: "proof-approval-artifact",
  name: "Proof & Approval Artifact",
  tier: "optional",
  featureFlagEnv: "FEATURE_PROOF",
  files: () => [
    proofLibFile(),
    proofApiFile(),
    proofDetailApiFile(),
    proofCodeApiFile(),
    proofPageFile(),
    createFormFile(),
    proofDetailPageFile(),
    proofControlsFile(),
    proofLandingPageFile(),
    signOffPanelFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists proof_approval_artifact_proofs (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  proof_code text unique not null,",
      "  title text not null default '',",
      "  description text not null default '',",
      "  kind text not null default 'general',",
      "  snapshot jsonb not null default '{}'::jsonb,",
      "  is_active boolean not null default true,",
      "  view_count integer not null default 0,",
      "  approval_count integer not null default 0,",
      "  approved_by_name text not null default '',",
      "  approved_at timestamptz,",
      "  created_at timestamptz not null default now(),",
      "  expires_at timestamptz",
      ");",
      "create index if not exists proof_approval_artifact_proofs_code_idx on proof_approval_artifact_proofs (proof_code);",
      "create index if not exists proof_approval_artifact_proofs_owner_idx on proof_approval_artifact_proofs (owner_id);",
      "create index if not exists proof_approval_artifact_proofs_created_idx on proof_approval_artifact_proofs (created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into proof_approval_artifact_proofs (proof_code, title, description, kind, snapshot, is_active, view_count, approval_count, approved_by_name, approved_at) values",
      "  ('demo-approved', 'Sarah & Tom''s engraved cutting board', 'Final layout before we cut. Please confirm the names and date are exactly right.', 'registry', '{\"elements\":[{\"type\":\"text\",\"value\":\"Sarah & Tom\"},{\"type\":\"text\",\"value\":\"06.14.2025\"}],\"material\":\"walnut\"}'::jsonb, false, 12, 1, 'Sarah M.', now())",
      "on conflict (proof_code) do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Proof & Approval Artifact — set to false to switch proof capture + customer sign-off off.",
    "FEATURE_PROOF=true"
  ],
  homeLinks: () => ['        <a className="button" href="/proofs">Approval proofs</a>'],
  navLinks: () => [{ href: "/proofs", label: "Approval proofs" }]
};
