// public-profile-og-sharing — public profile pages + rich share previews,
// ported from Kindred-Connection's real "soul page" system
// (backend/routers/public_profile.py + frontend/src/pages/PublicProfile.js).
// We keep its actual model — a public profile keyed by a lowercased @handle, with
// name, avatar, location, purpose, an archetype + "soul read" summary, a sweet-spot
// statement with talents/passions, and core-values / growth-goals / interests lists —
// and its actual behavior: a JSON profile endpoint (public/profile/{handle}), a
// bot-friendly Open Graph + Twitter-Card share page (og/{handle}) with canonical URL
// and image meta, and a Web-Share/clipboard "Share" action. Generalized from
// "Kindred souls" to any app's public member pages, with no provider names shown to
// users. Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_PUBLIC_PROFILE): customers manage their own handle, admins
// manage anyone's, and the share pages are public so link previews render.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/public-profiles.ts (model + queries, ported from public_profile.py) ----

function publicProfileLibFile(): GeneratedModuleFile {
  return file("src/lib/db/public-profiles.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The public profile record, ported field-for-field from public_profile.py's",
    "// JSON payload (public_profile / _fetch_public_user projection). Arrays that were",
    "// Mongo list fields (core_values, growth_goals, interests, talents, passions) are",
    "// stored as text[] columns here.",
    "export type PublicProfile = {",
    "  id: string;",
    "  userId: string | null;",
    "  handle: string;",
    "  name: string;",
    "  picture: string;",
    "  location: string;",
    "  purpose: string;",
    "  archetype: string;",
    "  summary: string;",
    "  sweetSpot: string;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  interests: string[];",
    "  talents: string[];",
    "  passions: string[];",
    "  published: boolean;",
    "};",
    "",
    "export type PublicProfileFilters = { q?: string; limit?: number };",
    "",
    "// Handles are stored + matched lowercase (ported from handle.lower() in",
    "// _fetch_public_user / og handlers). Keep only url-safe handle characters.",
    "export function normalizeHandle(raw: string): string {",
    '  return (raw || "")',
    "    .trim()",
    "    .toLowerCase()",
    '    .replace(/^@+/, "")',
    '    .replace(/[^a-z0-9._-]/g, "")',
    "    .slice(0, 40);",
    "}",
    "",
    "// Share title, ported from og_html/PublicProfile.js:",
    '//   archetype ? `${name} — ${archetype}` : `${name} on <app>`',
    "export function shareTitle(profile: Pick<PublicProfile, \"name\" | \"archetype\">, siteName: string): string {",
    '  const name = profile.name || "A member";',
    "  return profile.archetype ? `${name} — ${profile.archetype}` : `${name} on ${siteName}`;",
    "}",
    "",
    "// Share description, ported from og_html: sweet_spot || purpose || fallback,",
    "// stripped of surrounding quotes, clamped to 200 chars.",
    "export function shareDescription(profile: Pick<PublicProfile, \"sweetSpot\" | \"purpose\">): string {",
    '  let text = (profile.sweetSpot || profile.purpose || "Purpose-shaped connection.").trim();',
    "  text = text.replace(/^[\"']+|[\"']+$/g, \"\").trim();",
    "  return text.length > 200 ? text.slice(0, 197) + \"…\" : text;",
    "}",
    "",
    "const fallbackProfiles: PublicProfile[] = [",
    "  {",
    '    id: "sample-1",',
    "    userId: null,",
    '    handle: "ada",',
    '    name: "Ada Lovelace",',
    '    picture: "",',
    '    location: "London",',
    '    purpose: "Show where the work could go before anyone else can see it.",',
    '    archetype: "The Visionary",',
    '    summary: "Sees the pattern first and builds the bridge to it — patient with detail, restless with limits.",',
    '    sweetSpot: "Turning half-formed ideas into things people can actually use.",',
    '    coreValues: ["Curiosity", "Rigor", "Generosity"],',
    '    growthGoals: ["Finish before perfect", "Ask for help sooner"],',
    '    interests: ["Mathematics", "Music", "Machines"],',
    '    talents: ["Systems thinking", "Explaining hard things"],',
    '    passions: ["Invention", "Teaching"],',
    "    published: true",
    "  },",
    "  {",
    '    id: "sample-2",',
    "    userId: null,",
    '    handle: "grace",',
    '    name: "Grace Hopper",',
    '    picture: "",',
    '    location: "New York, NY",',
    '    purpose: "Make the machine speak a language people already know.",',
    '    archetype: "The Builder",',
    '    summary: "",',
    '    sweetSpot: "",',
    '    coreValues: ["Clarity", "Courage"],',
    '    growthGoals: ["Delegate the parts I love"],',
    '    interests: ["Compilers", "Teaching"],',
    '    talents: ["Translation", "Persistence"],',
    '    passions: ["Education"],',
    "    published: true",
    "  }",
    "];",
    "",
    "function toStringArray(value: unknown): string[] {",
    "  if (Array.isArray(value)) return value.map((v) => String(v)).filter((v) => v.trim().length > 0);",
    "  return [];",
    "}",
    "",
    "function rowToProfile(row: Record<string, unknown>): PublicProfile {",
    "  return {",
    "    id: String(row.id),",
    "    userId: row.user_id != null ? String(row.user_id) : null,",
    '    handle: String(row.handle || ""),',
    '    name: String(row.name || ""),',
    '    picture: String(row.picture || ""),',
    '    location: String(row.location || ""),',
    '    purpose: String(row.purpose || ""),',
    '    archetype: String(row.archetype || ""),',
    '    summary: String(row.summary || ""),',
    '    sweetSpot: String(row.sweet_spot || ""),',
    "    coreValues: toStringArray(row.core_values),",
    "    growthGoals: toStringArray(row.growth_goals),",
    "    interests: toStringArray(row.interests),",
    "    talents: toStringArray(row.talents),",
    "    passions: toStringArray(row.passions),",
    "    published: row.published !== false",
    "  };",
    "}",
    "",
    "// Public directory of published profiles, with optional name/handle/purpose search.",
    "export async function listPublicProfiles(filters: PublicProfileFilters = {}): Promise<PublicProfile[]> {",
    "  const limit = Math.min(100, Math.max(1, filters.limit || 50));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackProfiles",
    "      .filter((p) => p.published)",
    "      .filter((p) => !q || (p.name + \" \" + p.handle + \" \" + p.purpose).toLowerCase().includes(q))",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const rows = await sql`",
    "      select id, user_id, handle, name, picture, location, purpose, archetype, summary,",
    "             sweet_spot, core_values, growth_goals, interests, talents, passions, published",
    "      from public_profile_pages",
    "      where published = true",
    "        and (${like}::text is null",
    "          or lower(name) like ${like}",
    "          or lower(handle) like ${like}",
    "          or lower(purpose) like ${like})",
    "      order by name asc, handle asc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToProfile);",
    "  } catch {",
    "    return fallbackProfiles.filter((p) => p.published).slice(0, limit);",
    "  }",
    "}",
    "",
    "// Ported from _fetch_public_user: look a profile up by its lowercased handle.",
    "export async function getPublicProfileByHandle(handleRaw: string): Promise<PublicProfile | null> {",
    "  const handle = normalizeHandle(handleRaw);",
    "  if (!handle) return null;",
    "  if (!hasDatabase()) return fallbackProfiles.find((p) => p.handle === handle && p.published) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, handle, name, picture, location, purpose, archetype, summary,",
    "             sweet_spot, core_values, growth_goals, interests, talents, passions, published",
    "      from public_profile_pages where handle = ${handle} limit 1",
    "    `;",
    "    const profile = rows[0] ? rowToProfile(rows[0]) : null;",
    "    return profile && profile.published ? profile : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// The current signed-in user's own profile page (by ownership), for the editor.",
    "export async function getProfileForUser(userId: string): Promise<PublicProfile | null> {",
    "  if (!userId || !hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, handle, name, picture, location, purpose, archetype, summary,",
    "             sweet_spot, core_values, growth_goals, interests, talents, passions, published",
    "      from public_profile_pages where user_id = ${userId} limit 1",
    "    `;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type UpsertProfileInput = {",
    "  userId: string;",
    "  handle: string;",
    "  name: string;",
    "  picture?: string;",
    "  location?: string;",
    "  purpose?: string;",
    "  archetype?: string;",
    "  summary?: string;",
    "  sweetSpot?: string;",
    "  coreValues?: string[];",
    "  growthGoals?: string[];",
    "  interests?: string[];",
    "  talents?: string[];",
    "  passions?: string[];",
    "  published?: boolean;",
    "};",
    "",
    "export type UpsertResult = { ok: boolean; reason?: string };",
    "",
    "// Create or update the caller's public profile, de-duping on handle (a handle can",
    "// only belong to one user — the equivalent of the unique-handle lookup in the source).",
    "export async function upsertProfile(input: UpsertProfileInput): Promise<UpsertResult> {",
    "  if (!hasDatabase()) return { ok: false, reason: \"no-db\" };",
    "  const handle = normalizeHandle(input.handle);",
    '  if (!handle) return { ok: false, reason: "bad-handle" };',
    '  if (!input.name.trim()) return { ok: false, reason: "no-name" };',
    "  const sql = getDatabase();",
    "  try {",
    "    // A handle taken by a different user blocks the write.",
    "    const clash = await sql`select user_id from public_profile_pages where handle = ${handle} limit 1`;",
    "    if (clash[0] && String(clash[0].user_id) !== input.userId) {",
    '      return { ok: false, reason: "handle-taken" };',
    "    }",
    "    const coreValues = input.coreValues || [];",
    "    const growthGoals = input.growthGoals || [];",
    "    const interests = input.interests || [];",
    "    const talents = input.talents || [];",
    "    const passions = input.passions || [];",
    "    const published = input.published !== false;",
    "    const existing = await sql`select id from public_profile_pages where user_id = ${input.userId} limit 1`;",
    "    if (existing[0]) {",
    "      await sql`",
    "        update public_profile_pages set",
    "          handle = ${handle},",
    "          name = ${input.name.trim()},",
    '          picture = ${input.picture || ""},',
    '          location = ${input.location || ""},',
    '          purpose = ${input.purpose || ""},',
    '          archetype = ${input.archetype || ""},',
    '          summary = ${input.summary || ""},',
    '          sweet_spot = ${input.sweetSpot || ""},',
    "          core_values = ${coreValues},",
    "          growth_goals = ${growthGoals},",
    "          interests = ${interests},",
    "          talents = ${talents},",
    "          passions = ${passions},",
    "          published = ${published},",
    "          updated_at = now()",
    "        where id = ${existing[0].id}",
    "      `;",
    "      return { ok: true };",
    "    }",
    "    await sql`",
    "      insert into public_profile_pages",
    "        (user_id, handle, name, picture, location, purpose, archetype, summary, sweet_spot,",
    "         core_values, growth_goals, interests, talents, passions, published)",
    "      values",
    "        (${input.userId}, ${handle}, ${input.name.trim()}, ${input.picture || \"\"}, ${input.location || \"\"},",
    "         ${input.purpose || \"\"}, ${input.archetype || \"\"}, ${input.summary || \"\"}, ${input.sweetSpot || \"\"},",
    "         ${coreValues}, ${growthGoals}, ${interests}, ${talents}, ${passions}, ${published})",
    "    `;",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, reason: "error" };',
    "  }",
    "}",
    "",
    "export function publicProfileEnabled(): boolean {",
    '  return process.env.FEATURE_PUBLIC_PROFILE !== "false";',
    "}",
    "",
    "// The app's public base URL, used for canonical + og:url + share links (ported",
    "// from APP_PUBLIC_URL in public_profile.py). Falls back to a relative path.",
    "export function publicBaseUrl(): string {",
    '  return (process.env.APP_PUBLIC_URL || process.env.NEXT_PUBLIC_APP_URL || "").replace(/\\/+$/, "");',
    "}",
    "",
    "export function shareSiteName(): string {",
    '  return process.env.NEXT_PUBLIC_APP_NAME || "our community";',
    "}"
  ]);
}

// ---- src/app/api/public-profiles/route.ts (list + upsert) -------------------

function publicProfileApiFile(): GeneratedModuleFile {
  return file("src/app/api/public-profiles/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listPublicProfiles, upsertProfile, publicProfileEnabled } from "@/lib/db/public-profiles";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function toStringList(value: unknown): string[] {",
    "  if (Array.isArray(value)) return value.map((v) => String(v).trim()).filter(Boolean);",
    '  if (typeof value === "string") return value.split(",").map((v) => v.trim()).filter(Boolean);',
    "  return [];",
    "}",
    "",
    "export async function GET(request: Request) {",
    '  if (!publicProfileEnabled()) return NextResponse.json({ ok: false, message: "Public profiles are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const profiles = await listPublicProfiles({ q: url.searchParams.get("q") || undefined });',
    "  return NextResponse.json({ ok: true, profiles });",
    "}",
    "",
    "// Save a profile. A signed-in customer may save their OWN profile; admins may save",
    "// on behalf of any user by passing userId.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const isAdmin = canAccessAdmin(user.role);',
    '  const targetUserId = isAdmin && typeof body.userId === "string" && body.userId.trim()',
    "    ? body.userId.trim()",
    "    : user.email;",
    '  const handle = typeof body.handle === "string" ? body.handle : "";',
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    '  if (!handle.trim()) return NextResponse.json({ ok: false, message: "Pick a handle for your page." }, { status: 400 });',
    '  if (!name) return NextResponse.json({ ok: false, message: "A display name is required." }, { status: 400 });',
    "  const result = await upsertProfile({",
    "    userId: targetUserId,",
    "    handle,",
    "    name,",
    '    picture: typeof body.picture === "string" ? body.picture : undefined,',
    '    location: typeof body.location === "string" ? body.location : undefined,',
    '    purpose: typeof body.purpose === "string" ? body.purpose : undefined,',
    '    archetype: typeof body.archetype === "string" ? body.archetype : undefined,',
    '    summary: typeof body.summary === "string" ? body.summary : undefined,',
    '    sweetSpot: typeof body.sweetSpot === "string" ? body.sweetSpot : undefined,',
    "    coreValues: toStringList(body.coreValues),",
    "    growthGoals: toStringList(body.growthGoals),",
    "    interests: toStringList(body.interests),",
    "    talents: toStringList(body.talents),",
    "    passions: toStringList(body.passions),",
    '    published: body.published === false ? false : true',
    "  });",
    "  if (!result.ok) {",
    '    if (result.reason === "handle-taken") return NextResponse.json({ ok: false, message: "That handle is already taken." }, { status: 409 });',
    '    if (result.reason === "bad-handle") return NextResponse.json({ ok: false, message: "Use letters, numbers, dots, dashes or underscores." }, { status: 400 });',
    '    if (result.reason === "no-db") return NextResponse.json({ ok: false, message: "Connect a database to save your profile." }, { status: 503 });',
    '    return NextResponse.json({ ok: false, message: "Could not save your profile." }, { status: 500 });',
    "  }",
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/public-profiles/[handle]/route.ts (public JSON, ported from /public/profile/{handle}) ----

function publicProfileJsonApiFile(): GeneratedModuleFile {
  return file("src/app/api/public-profiles/[handle]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getPublicProfileByHandle, publicProfileEnabled } from "@/lib/db/public-profiles";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Public JSON profile — the direct port of GET /api/public/profile/{handle}.",
    "// Intentionally unauthenticated: this is what powers link previews and the",
    "// public profile page. Only PUBLISHED profiles are ever returned.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ handle: string }> }) {",
    '  if (!publicProfileEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const { handle } = await params;",
    "  const profile = await getPublicProfileByHandle(handle);",
    '  if (!profile) return NextResponse.json({ ok: false, message: "Not found" }, { status: 404 });',
    "  return NextResponse.json({",
    "    ok: true,",
    "    handle: profile.handle,",
    "    name: profile.name,",
    "    picture: profile.picture,",
    "    location: profile.location,",
    "    purpose: profile.purpose,",
    "    archetype: profile.archetype,",
    "    summary: profile.summary,",
    "    sweetSpot: profile.sweetSpot,",
    "    coreValues: profile.coreValues,",
    "    growthGoals: profile.growthGoals,",
    "    interests: profile.interests,",
    "    talents: profile.talents,",
    "    passions: profile.passions",
    "  });",
    "}"
  ]);
}

// ---- src/app/api/public-profiles/[handle]/og/route.ts ----
// Bot-friendly HTML share page with OG + Twitter meta, ported from og_html().

function publicProfileOgApiFile(): GeneratedModuleFile {
  return file("src/app/api/public-profiles/[handle]/og/route.ts", [
    'import { getPublicProfileByHandle, shareTitle, shareDescription, publicProfileEnabled, publicBaseUrl, shareSiteName } from "@/lib/db/public-profiles";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function escapeHtml(value: string): string {",
    "  return value",
    '    .replace(/&/g, "&amp;")',
    '    .replace(/</g, "&lt;")',
    '    .replace(/>/g, "&gt;")',
    '    .replace(/"/g, "&quot;")',
    "    .replace(/'/g, \"&#39;\");",
    "}",
    "",
    "// GET /api/public-profiles/{handle}/og — the port of og_html(): render a small",
    "// HTML document carrying Open Graph + Twitter-Card meta so links unfurl richly,",
    "// then redirect a human visitor to the real profile page.",
    "export async function GET(_request: Request, { params }: { params: Promise<{ handle: string }> }) {",
    '  if (!publicProfileEnabled()) return new Response("Not found", { status: 404 });',
    "  const { handle } = await params;",
    "  const profile = await getPublicProfileByHandle(handle);",
    '  if (!profile) return new Response("Not found", { status: 404 });',
    "",
    "  const site = shareSiteName();",
    "  const base = publicBaseUrl();",
    "  const profileUrl = `${base}/p/${profile.handle}`;",
    "  const title = shareTitle(profile, site);",
    "  const description = shareDescription(profile);",
    '  const image = profile.picture && profile.picture.startsWith("http") ? profile.picture : "";',
    "",
    "  const eTitle = escapeHtml(title);",
    "  const eDesc = escapeHtml(description);",
    '  const eName = escapeHtml(profile.name || "A member");',
    "  const eUrl = escapeHtml(profileUrl);",
    "  const eImg = escapeHtml(image);",
    "  const eHandle = escapeHtml(profile.handle);",
    "  const eSite = escapeHtml(site);",
    "  const redirectJson = JSON.stringify(profileUrl);",
    "",
    "  const imageTags = image",
    "    ? [",
    '        `  <meta property="og:image" content="${eImg}" />`,',
    '        `  <meta property="og:image:alt" content="${eName} on ${eSite}" />`,',
    '        `  <meta name="twitter:image" content="${eImg}" />`',
    '      ].join("\\n")',
    '    : "";',
    "",
    "  const body = [",
    '    "<!doctype html>",',
    '    \'<html lang="en">\',',
    '    "<head>",',
    '    \'  <meta charset="utf-8" />\',',
    '    \'  <meta name="viewport" content="width=device-width,initial-scale=1" />\',',
    "    `  <title>${eTitle}</title>`,",
    "    `  <meta name=\"description\" content=\"${eDesc}\" />`,",
    '    \'  <meta property="og:type" content="profile" />\',',
    "    `  <meta property=\"og:site_name\" content=\"${eSite}\" />`,",
    "    `  <meta property=\"og:title\" content=\"${eTitle}\" />`,",
    "    `  <meta property=\"og:description\" content=\"${eDesc}\" />`,",
    "    `  <meta property=\"og:url\" content=\"${eUrl}\" />`,",
    "    `  <meta property=\"profile:username\" content=\"${eHandle}\" />`,",
    "    imageTags,",
    '    \'  <meta name="twitter:card" content="summary_large_image" />\',',
    "    `  <meta name=\"twitter:title\" content=\"${eTitle}\" />`,",
    "    `  <meta name=\"twitter:description\" content=\"${eDesc}\" />`,",
    "    `  <link rel=\"canonical\" href=\"${eUrl}\" />`,",
    "    `  <meta http-equiv=\"refresh\" content=\"0;url=${eUrl}\" />`,",
    '    "  <style>body{margin:0;font-family:Georgia,serif;background:#faf9f6;color:#2c3539;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}.card{max-width:540px;text-align:center}h1{font-size:28px;margin:0 0 8px}p{color:#5c666a;margin:0 0 24px}a{display:inline-block;background:#2c3539;color:#faf9f6;padding:12px 28px;border-radius:999px;text-decoration:none}</style>",',
    '    "</head>",',
    '    "<body>",',
    '    \'  <div class="card">\',',
    "    `    <h1>${eTitle}</h1>`,",
    "    `    <p>${eDesc}</p>`,",
    "    `    <a href=\"${eUrl}\">Read profile →</a>`,",
    '    "  </div>",',
    "    `  <script>window.location.replace(${redirectJson});</script>`,",
    '    "</body>",',
    '    "</html>"',
    "  ]",
    '    .filter((line) => line !== "")',
    '    .join("\\n");',
    "",
    "  return new Response(body, {",
    "    status: 200,",
    '    headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "public, max-age=300" }',
    "  });",
    "}"
  ]);
}

// ---- src/app/p/page.tsx (public directory of profiles) ----------------------

function publicProfileListPageFile(): GeneratedModuleFile {
  return file("src/app/p/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listPublicProfiles, publicProfileEnabled } from "@/lib/db/public-profiles";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function PublicProfilesPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string }>;",
    "}) {",
    "  if (!publicProfileEnabled()) {",
    '    return (<main className="shell"><h1>Profiles</h1><p>Public profiles are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/p");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    "  const profiles = await listPublicProfiles({ q: q || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Profiles</p>',
    "      <h1>Member profiles</h1>",
    "      <p>Browse public profile pages. Each one has a shareable link with a rich preview.</p>",
    '      <p><Link className="button" href="/p/me">Edit my profile</Link></p>',
    '      <form className="stack" method="get" role="search">',
    '        <label className="label" htmlFor="profile-search">Search profiles</label>',
    '        <input className="input" id="profile-search" type="search" name="q" defaultValue={q} placeholder="Search by name, handle, or purpose" aria-label="Search profiles" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {profiles.length === 0 ? (",
    '        <p className="note">{q ? `No profiles match "${q}" yet.` : "No public profiles yet. Be the first to publish one."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {profiles.map((profile) => (",
    '            <Link className="wide-card" key={profile.id} href={`/p/${profile.handle}`}>',
    '              <span>{profile.archetype || "Member"}</span>',
    "              <strong>{profile.name}</strong>",
    "              <p>{[`@${profile.handle}`, profile.location, profile.purpose].filter(Boolean).join(\" · \")}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/p/[handle]/page.tsx (the public profile page, ported from PublicProfile.js) ----

function publicProfilePageFile(): GeneratedModuleFile {
  return file("src/app/p/[handle]/page.tsx", [
    'import Link from "next/link";',
    'import type { Metadata } from "next";',
    'import { notFound } from "next/navigation";',
    'import { getPublicProfileByHandle, shareTitle, shareDescription, publicProfileEnabled, publicBaseUrl, shareSiteName } from "@/lib/db/public-profiles";',
    'import ShareButton from "./share-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "// Server-rendered OG/Twitter meta — the Next 15 equivalent of the <Helmet> block",
    "// in PublicProfile.js — so the page URL itself unfurls into a rich card.",
    "export async function generateMetadata({ params }: { params: Promise<{ handle: string }> }): Promise<Metadata> {",
    "  if (!publicProfileEnabled()) return { title: \"Profiles\" };",
    "  const { handle } = await params;",
    "  const profile = await getPublicProfileByHandle(handle);",
    '  if (!profile) return { title: "Profile not found" };',
    "  const site = shareSiteName();",
    "  const title = shareTitle(profile, site);",
    "  const description = shareDescription(profile);",
    "  const base = publicBaseUrl();",
    "  const url = `${base}/p/${profile.handle}`;",
    '  const images = profile.picture && profile.picture.startsWith("http") ? [profile.picture] : [];',
    "  return {",
    "    title,",
    "    description,",
    "    alternates: { canonical: url },",
    "    openGraph: {",
    '      type: "profile",',
    "      siteName: site,",
    "      title,",
    "      description,",
    "      url,",
    "      images",
    "    },",
    "    twitter: {",
    '      card: "summary_large_image",',
    "      title,",
    "      description,",
    "      images",
    "    }",
    "  };",
    "}",
    "",
    "// The public profile page is PUBLIC (no auth) so shared links resolve for anyone —",
    "// exactly as /me/{handle} was in the source SPA. Only published profiles resolve.",
    "export default async function PublicProfilePage({ params }: { params: Promise<{ handle: string }> }) {",
    "  if (!publicProfileEnabled()) {",
    '    return (<main className="shell"><h1>Profiles</h1><p>Public profiles are turned off for this app.</p></main>);',
    "  }",
    "  const { handle } = await params;",
    "  const profile = await getPublicProfileByHandle(handle);",
    "  if (!profile) notFound();",
    "",
    "  const site = shareSiteName();",
    "  const base = publicBaseUrl();",
    "  const shareUrl = `${base}/api/public-profiles/${profile.handle}/og`;",
    "",
    "  return (",
    '    <main className="shell" data-testid="public-profile">',
    '      <div className="stack" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexDirection: "row" }}>',
    '        <p className="eyebrow">Profile</p>',
    "        <ShareButton shareUrl={shareUrl} name={profile.name} />",
    "      </div>",
    '      <header className="grid">',
    "        {profile.picture ? (",
    '          <img src={profile.picture} alt={profile.name} width={192} height={192} style={{ borderRadius: 16, objectFit: "cover" }} />',
    "        ) : (",
    '          <div className="card" aria-hidden="true" style={{ width: 192, height: 192, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 64 }}>{(profile.name || "?").charAt(0)}</div>',
    "        )}",
    "        <div>",
    "          {profile.archetype ? <p className=\"eyebrow\">{profile.archetype}</p> : null}",
    "          <h1>{profile.name}</h1>",
    "          {profile.location ? <p className=\"note\">{profile.location}</p> : null}",
    "          <p className=\"note\">@{profile.handle}</p>",
    "        </div>",
    "      </header>",
    "",
    "      {profile.purpose ? (",
    '        <section className="panel">',
    '          <p className="eyebrow">Purpose</p>',
    "          <p style={{ fontStyle: \"italic\", fontSize: \"1.25rem\" }}>&ldquo;{profile.purpose}&rdquo;</p>",
    "        </section>",
    "      ) : null}",
    "",
    "      {profile.summary ? (",
    '        <section className="panel">',
    '          <p className="eyebrow">Read</p>',
    "          <p>{profile.summary}</p>",
    "        </section>",
    "      ) : null}",
    "",
    "      {profile.sweetSpot ? (",
    '        <section className="panel">',
    '          <p className="eyebrow">Sweet spot</p>',
    "          <p style={{ fontStyle: \"italic\", fontSize: \"1.1rem\" }}>&ldquo;{profile.sweetSpot}&rdquo;</p>",
    "          {(profile.talents.length > 0 || profile.passions.length > 0) ? (",
    '            <div className="grid">',
    "              {profile.talents.length > 0 ? (",
    "                <div>",
    '                  <p className="eyebrow">Good at</p>',
    "                  <ul>{profile.talents.map((t) => <li key={t}>{t}</li>)}</ul>",
    "                </div>",
    "              ) : null}",
    "              {profile.passions.length > 0 ? (",
    "                <div>",
    '                  <p className="eyebrow">Loves</p>',
    "                  <ul>{profile.passions.map((p) => <li key={p}>{p}</li>)}</ul>",
    "                </div>",
    "              ) : null}",
    "            </div>",
    "          ) : null}",
    "        </section>",
    "      ) : null}",
    "",
    "      {(profile.coreValues.length > 0 || profile.growthGoals.length > 0) ? (",
    '        <section className="grid">',
    "          {profile.coreValues.length > 0 ? (",
    "            <div>",
    '              <p className="eyebrow">Core values</p>',
    '              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{profile.coreValues.map((v) => <span key={v} className="chip">{v}</span>)}</div>',
    "            </div>",
    "          ) : null}",
    "          {profile.growthGoals.length > 0 ? (",
    "            <div>",
    '              <p className="eyebrow">Growing toward</p>',
    "              <ul>{profile.growthGoals.map((g) => <li key={g}>{g}</li>)}</ul>",
    "            </div>",
    "          ) : null}",
    "        </section>",
    "      ) : null}",
    "",
    "      {profile.interests.length > 0 ? (",
    '        <section>',
    '          <p className="eyebrow">Interests</p>',
    '          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{profile.interests.map((i) => <span key={i} className="chip">{i}</span>)}</div>',
    "        </section>",
    "      ) : null}",
    "",
    '      <p><Link className="button" href="/p">Browse all profiles</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/p/[handle]/share-button.tsx (Web Share + clipboard, ported from handleShare) ----

function shareButtonFile(): GeneratedModuleFile {
  return file("src/app/p/[handle]/share-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "// Ported from PublicProfile.js handleShare(): use the native Web Share sheet when",
    "// available, otherwise copy the share URL to the clipboard with feedback.",
    "export default function ShareButton({ shareUrl, name }: { shareUrl: string; name: string }) {",
    '  const [status, setStatus] = useState<"idle" | "copied" | "error">("idle");',
    "",
    "  async function onShare() {",
    "    try {",
    '      if (typeof navigator !== "undefined" && navigator.share) {',
    "        await navigator.share({",
    "          title: name ? `${name}` : \"A profile\",",
    "          url: shareUrl",
    "        });",
    "        return;",
    "      }",
    "    } catch {",
    "      // fall through to clipboard",
    "    }",
    "    try {",
    "      await navigator.clipboard.writeText(shareUrl);",
    '      setStatus("copied");',
    '      setTimeout(() => setStatus("idle"), 2500);',
    "    } catch {",
    '      setStatus("error");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <span className="stack" style={{ display: "inline-flex", flexDirection: "row", alignItems: "center", gap: 8 }}>',
    '      <button type="button" className="button" onClick={onShare}>Share</button>',
    '      {status === "copied" ? <span className="note" role="status">Link copied.</span> : null}',
    '      {status === "error" ? <span className="note" role="status">Copy this URL: {shareUrl}</span> : null}',
    "    </span>",
    "  );",
    "}"
  ]);
}

// ---- src/app/p/me/page.tsx (owner editor for one's own profile) -------------

function myProfileEditorPageFile(): GeneratedModuleFile {
  return file("src/app/p/me/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { getProfileForUser, publicProfileEnabled } from "@/lib/db/public-profiles";',
    'import ProfileEditor from "./editor";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function MyProfilePage() {",
    "  if (!publicProfileEnabled()) {",
    '    return (<main className="shell"><h1>My profile</h1><p>Public profiles are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/p/me");',
    "  const user = await getCurrentUser();",
    "  const profile = user ? await getProfileForUser(user.email) : null;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Profile</p>',
    "      <h1>My public profile</h1>",
    "      <p>Set up your shareable profile page. When published, anyone with the link gets a rich preview.</p>",
    "      <ProfileEditor initial={profile} />",
    '      {profile ? <p><Link className="button" href={`/p/${profile.handle}`}>View my public page</Link></p> : null}',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/p/me/editor.tsx (client form that POSTs to the API) ------------

function profileEditorFile(): GeneratedModuleFile {
  return file("src/app/p/me/editor.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "type ProfileShape = {",
    "  handle: string;",
    "  name: string;",
    "  picture: string;",
    "  location: string;",
    "  purpose: string;",
    "  archetype: string;",
    "  summary: string;",
    "  sweetSpot: string;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  interests: string[];",
    "  talents: string[];",
    "  passions: string[];",
    "  published: boolean;",
    "} | null;",
    "",
    "function joinList(value: string[] | undefined): string {",
    '  return (value || []).join(", ");',
    "}",
    "",
    "export default function ProfileEditor({ initial }: { initial: ProfileShape }) {",
    '  const [handle, setHandle] = useState(initial?.handle || "");',
    '  const [name, setName] = useState(initial?.name || "");',
    '  const [picture, setPicture] = useState(initial?.picture || "");',
    '  const [location, setLocation] = useState(initial?.location || "");',
    '  const [purpose, setPurpose] = useState(initial?.purpose || "");',
    '  const [archetype, setArchetype] = useState(initial?.archetype || "");',
    '  const [summary, setSummary] = useState(initial?.summary || "");',
    '  const [sweetSpot, setSweetSpot] = useState(initial?.sweetSpot || "");',
    "  const [coreValues, setCoreValues] = useState(joinList(initial?.coreValues));",
    "  const [growthGoals, setGrowthGoals] = useState(joinList(initial?.growthGoals));",
    "  const [interests, setInterests] = useState(joinList(initial?.interests));",
    "  const [talents, setTalents] = useState(joinList(initial?.talents));",
    "  const [passions, setPassions] = useState(joinList(initial?.passions));",
    "  const [published, setPublished] = useState(initial?.published !== false);",
    '  const [state, setState] = useState<"idle" | "saving" | "saved" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function onSubmit(event: React.FormEvent) {",
    "    event.preventDefault();",
    '    setState("saving");',
    '    setMessage("");',
    "    try {",
    '      const res = await fetch("/api/public-profiles", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          handle, name, picture, location, purpose, archetype, summary, sweetSpot,",
    "          coreValues, growthGoals, interests, talents, passions, published",
    "        })",
    "      });",
    "      const data = await res.json().catch(() => ({}));",
    "      if (!res.ok || !data.ok) {",
    '        setState("error");',
    '        setMessage(data.message || "Could not save your profile.");',
    "        return;",
    "      }",
    '      setState("saved");',
    '      setMessage("Saved.");',
    "    } catch {",
    '      setState("error");',
    '      setMessage("Something went wrong. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={onSubmit}>',
    '      <label className="label" htmlFor="pp-handle">Handle</label>',
    '      <input className="input" id="pp-handle" name="handle" value={handle} onChange={(e) => setHandle(e.target.value)} placeholder="your-handle" required />',
    '      <label className="label" htmlFor="pp-name">Display name</label>',
    '      <input className="input" id="pp-name" name="name" value={name} onChange={(e) => setName(e.target.value)} required />',
    '      <label className="label" htmlFor="pp-picture">Photo URL</label>',
    '      <input className="input" id="pp-picture" name="picture" value={picture} onChange={(e) => setPicture(e.target.value)} placeholder="https://…" />',
    '      <label className="label" htmlFor="pp-location">Location</label>',
    '      <input className="input" id="pp-location" name="location" value={location} onChange={(e) => setLocation(e.target.value)} />',
    '      <label className="label" htmlFor="pp-archetype">Archetype</label>',
    '      <input className="input" id="pp-archetype" name="archetype" value={archetype} onChange={(e) => setArchetype(e.target.value)} placeholder="e.g. The Builder" />',
    '      <label className="label" htmlFor="pp-purpose">Purpose</label>',
    '      <textarea className="input" id="pp-purpose" name="purpose" value={purpose} onChange={(e) => setPurpose(e.target.value)} rows={2} />',
    '      <label className="label" htmlFor="pp-summary">Summary / read</label>',
    '      <textarea className="input" id="pp-summary" name="summary" value={summary} onChange={(e) => setSummary(e.target.value)} rows={2} />',
    '      <label className="label" htmlFor="pp-sweet">Sweet spot</label>',
    '      <textarea className="input" id="pp-sweet" name="sweetSpot" value={sweetSpot} onChange={(e) => setSweetSpot(e.target.value)} rows={2} />',
    '      <label className="label" htmlFor="pp-values">Core values (comma-separated)</label>',
    '      <input className="input" id="pp-values" name="coreValues" value={coreValues} onChange={(e) => setCoreValues(e.target.value)} />',
    '      <label className="label" htmlFor="pp-goals">Growth goals (comma-separated)</label>',
    '      <input className="input" id="pp-goals" name="growthGoals" value={growthGoals} onChange={(e) => setGrowthGoals(e.target.value)} />',
    '      <label className="label" htmlFor="pp-interests">Interests (comma-separated)</label>',
    '      <input className="input" id="pp-interests" name="interests" value={interests} onChange={(e) => setInterests(e.target.value)} />',
    '      <label className="label" htmlFor="pp-talents">Good at (comma-separated)</label>',
    '      <input className="input" id="pp-talents" name="talents" value={talents} onChange={(e) => setTalents(e.target.value)} />',
    '      <label className="label" htmlFor="pp-passions">Loves (comma-separated)</label>',
    '      <input className="input" id="pp-passions" name="passions" value={passions} onChange={(e) => setPassions(e.target.value)} />',
    '      <label className="label" style={{ display: "flex", flexDirection: "row", alignItems: "center", gap: 8 }}>',
    '        <input type="checkbox" checked={published} onChange={(e) => setPublished(e.target.checked)} />',
    "        Published (visible to anyone with the link)",
    "      </label>",
    '      <button className="button primary" type="submit" disabled={state === "saving"}>{state === "saving" ? "Saving…" : "Save profile"}</button>',
    '      {message ? <p className="note" role="status" aria-live="polite">{message}</p> : null}',
    "    </form>",
    "  );",
    "}"
  ]);
}

export const publicProfileModule: AppModule = {
  slug: "public-profile-og-sharing",
  name: "Public Profiles & Share Previews",
  tier: "optional",
  featureFlagEnv: "FEATURE_PUBLIC_PROFILE",
  files: () => [
    publicProfileLibFile(),
    publicProfileApiFile(),
    publicProfileJsonApiFile(),
    publicProfileOgApiFile(),
    publicProfileListPageFile(),
    publicProfilePageFile(),
    shareButtonFile(),
    myProfileEditorPageFile(),
    profileEditorFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists public_profile_pages (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id text,",
      "  handle text not null unique,",
      "  name text not null default '',",
      "  picture text not null default '',",
      "  location text not null default '',",
      "  purpose text not null default '',",
      "  archetype text not null default '',",
      "  summary text not null default '',",
      "  sweet_spot text not null default '',",
      "  core_values text[] not null default '{}',",
      "  growth_goals text[] not null default '{}',",
      "  interests text[] not null default '{}',",
      "  talents text[] not null default '{}',",
      "  passions text[] not null default '{}',",
      "  published boolean not null default true,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists public_profile_pages_handle_idx on public_profile_pages (handle);",
      "create index if not exists public_profile_pages_user_idx on public_profile_pages (user_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into public_profile_pages (handle, name, location, purpose, archetype, summary, sweet_spot, core_values, growth_goals, interests, talents, passions, published) values",
      "  ('ada', 'Ada Lovelace', 'London', 'Show where the work could go before anyone else can see it.', 'The Visionary', 'Sees the pattern first and builds the bridge to it.', 'Turning half-formed ideas into things people can use.', array['Curiosity','Rigor'], array['Finish before perfect'], array['Mathematics','Music'], array['Systems thinking'], array['Invention'], true)",
      "on conflict (handle) do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Public Profiles & Share Previews — set to false to switch public profile pages off.",
    "FEATURE_PUBLIC_PROFILE=true",
    "# Public base URL used for canonical + Open Graph share links (e.g. https://app.example.com).",
    "APP_PUBLIC_URL=",
    "# Optional display name shown in share previews.",
    "NEXT_PUBLIC_APP_NAME="
  ],
  homeLinks: () => ['        <a className="button" href="/p">Profiles</a>'],
  navLinks: () => [{ href: "/p", label: "Profiles" }]
};
