// purpose-onboarding — a deep first-run capture of a person's purpose, values,
// growth goals, drivers, reflection and honest motivation, ported from
// Kindred-Connection's real onboarding system (backend/server.py OnboardingIn /
// ProfileUpdate models + POST /onboarding, GET+PATCH /profile/me,
// POST /profile/reanalyze; frontend/src/pages/Onboarding.js multi-step capture +
// VALUE_OPTIONS; Profile.js insights display). We keep its actual data model —
// purpose, core_values, growth_goals[], drivers, reflection, motivation +
// motivation_text, looking_for, and a derived "insights" read (archetype /
// summary / strengths / growth_edges / recommended_path) — and its real logic:
// one profile per user, submitting marks them onboarded, the same
// analyze-purpose pass runs on submit and can be re-run ("reanalyze"). The AI
// soul-read is replaced with a deterministic, provider-free heuristic so the
// module runs on the app owner's own database with graceful sample-data
// fallback, no external keys, and no provider names shown to users.
// Feature-flagged (FEATURE_ONBOARDING); customers complete/read their own
// onboarding, admins can review any profile.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/onboarding-options.ts (pure option lists, client-safe) ------
// The capture form is a client component; option lists live in a file with no
// database driver so importing them never pulls @/lib/db/client toward the
// client bundle (the split live-on-mission had to make by hand).

function onboardingOptionsFile(): GeneratedModuleFile {
  return file("src/lib/db/onboarding-options.ts", [
    "// Pure onboarding option lists — importable from client components (no",
    "// database driver in this file).",
    "",
    "// Ported from Kindred-Connection Onboarding.js VALUE_OPTIONS — the values a",
    "// person can claim as their own.",
    "export const VALUE_OPTIONS = [",
    '  "Honesty", "Curiosity", "Compassion", "Integrity", "Courage", "Discipline",',
    '  "Joy", "Service", "Beauty", "Truth", "Stewardship", "Patience",',
    '  "Brotherhood", "Tenderness", "Equity", "Creativity", "Faith", "Adventure"',
    "];",
    "",
    "// Ported from Onboarding.js step 1 motivation options — the honest reason a",
    "// person shows up. Each maps to what they say they are looking for.",
    "export const MOTIVATION_OPTIONS: Array<{ key: string; label: string; hint: string; lookingFor: string }> = [",
    '  { key: "friend", label: "I want a real connection that sees me", hint: "Not a quick fix. Something real.", lookingFor: "connection" },',
    '  { key: "lonely", label: "I am not sure what I need yet", hint: "It is okay not to know. We will help.", lookingFor: "connection" },',
    '  { key: "community", label: "I want people who are growing", hint: "A community moving in the same direction.", lookingFor: "community" },',
    '  { key: "both", label: "Growth first — and maybe more later", hint: "The slow path. Often the lasting one.", lookingFor: "both" },',
    '  { key: "purpose", label: "I am clear: I want to build something", hint: "Specific and intentional.", lookingFor: "purpose" }',
    "];"
  ]);
}

// ---- src/lib/db/onboarding.ts (model + queries + insight derivation) --------

function onboardingLibFile(): GeneratedModuleFile {
  return file("src/lib/db/onboarding.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    'import { MOTIVATION_OPTIONS, VALUE_OPTIONS } from "@/lib/db/onboarding-options";',
    "",
    "// Re-exported for server-side callers; client components import the options",
    "// from @/lib/db/onboarding-options directly (keeps the db driver server-only).",
    "export { MOTIVATION_OPTIONS, VALUE_OPTIONS };",
    "",
    "export type OnboardingInsights = {",
    "  archetype: string;",
    "  summary: string;",
    "  strengths: string[];",
    "  growthEdges: string[];",
    "  recommendedPath: string;",
    "};",
    "",
    "export type OnboardingProfile = {",
    "  id: string;",
    "  userId: string;",
    "  purpose: string;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  drivers: string;",
    "  reflection: string;",
    "  motivation: string;",
    "  motivationText: string;",
    "  lookingFor: string;",
    "  onboarded: boolean;",
    "  insights: OnboardingInsights | null;",
    "  completeness: number;",
    "  updatedAt: string;",
    "};",
    "",
    "export type OnboardingInput = {",
    "  purpose: string;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  drivers: string;",
    "  reflection: string;",
    "  motivation?: string;",
    "  motivationText?: string;",
    "  lookingFor?: string;",
    "};",
    "",
    "// Ported from Onboarding.js canNext gates — the minimum a real onboarding must",
    "// carry before it means anything.",
    "export function validateOnboarding(input: Partial<OnboardingInput>): string | null {",
    '  if (!input.purpose || input.purpose.trim().length <= 10) return "Say a little more about your purpose.";',
    "  const values = (input.coreValues || []).filter((v) => v && v.trim());",
    '  if (values.length < 3) return "Choose at least three core values.";',
    "  const goals = (input.growthGoals || []).filter((g) => g && g.trim());",
    '  if (goals.length < 1) return "Name at least one thing you are growing toward.";',
    '  if (!input.drivers || input.drivers.trim().length <= 5) return "Tell us what drives you.";',
    '  if (!input.reflection || input.reflection.trim().length <= 5) return "Share one true reflection.";',
    "  return null;",
    "}",
    "",
    "// Completeness score in the spirit of the source's profile richness — the more",
    "// of the deep capture is filled in, the more there is to read.",
    "export function calculateCompleteness(input: Partial<OnboardingInput>): number {",
    "  let score = 0;",
    "  if (input.purpose && input.purpose.trim().length > 10) score += 25;",
    "  if ((input.coreValues || []).filter((v) => v && v.trim()).length >= 3) score += 20;",
    "  if ((input.growthGoals || []).filter((g) => g && g.trim()).length >= 1) score += 20;",
    "  if (input.drivers && input.drivers.trim().length > 5) score += 15;",
    "  if (input.reflection && input.reflection.trim().length > 5) score += 15;",
    "  if (input.motivation && input.motivation.trim()) score += 5;",
    "  return Math.min(100, score);",
    "}",
    "",
    "// Deterministic, provider-free stand-in for the source's analyze-purpose soul",
    "// read (server.py claude_analyze_purpose). Same shape — archetype, summary,",
    "// strengths, growth edges, a recommended path — derived from what the person",
    "// actually wrote, so it runs with no external keys. The source biases anyone",
    "// naming loneliness toward connection first, not what they are chasing; we keep",
    "// that: motivation 'lonely'/'friend' -> connection, 'community' -> community,",
    "// 'purpose' -> purpose, else 'both'.",
    "const ARCHETYPES = [",
    '  "The Quiet Builder", "The Tender Witness", "The Steadfast Servant",',
    '  "The Open Seeker", "The Bridge", "The Steady Flame"',
    "];",
    "",
    "export function deriveInsights(input: OnboardingInput): OnboardingInsights {",
    "  const values = input.coreValues.filter((v) => v && v.trim());",
    "  const goals = input.growthGoals.filter((g) => g && g.trim());",
    "  const seed = (input.purpose + input.drivers + values.join(\"\")).length;",
    "  const archetype = ARCHETYPES[seed % ARCHETYPES.length];",
    "  const strengths = values.slice(0, 3);",
    "  while (strengths.length < 3) strengths.push([\"Self-aware\", \"Open-hearted\", \"Intentional\"][strengths.length]);",
    '  const recommendedPath = input.motivation === "lonely" || input.motivation === "friend"',
    '    ? "connection"',
    '    : input.motivation === "community"',
    '      ? "community"',
    '      : input.motivation === "purpose"',
    '        ? "purpose"',
    '        : "both";',
    "  return {",
    "    archetype,",
    "    summary:",
    "      goals.length > 0",
    '        ? `Someone building toward ${goals[0].toLowerCase()} — grounded in ${values.slice(0, 2).join(" and ") || "clear values"}.`',
    '        : "A thoughtful person walking a meaningful path of growth.",',
    "    strengths,",
    '    growthEdges: ["Patience with self", "Trusting the process"],',
    "    recommendedPath",
    "  };",
    "}",
    "",
    "const fallbackProfile: OnboardingProfile = {",
    '  id: "sample-1",',
    '  userId: "sample-user",',
    '  purpose: "To bridge honest reflection with real action, and help others do the same.",',
    '  coreValues: ["Honesty", "Compassion", "Courage"],',
    '  growthGoals: ["Finish the first draft", "A steadier daily rhythm", "Lead one small gathering"],',
    '  drivers: "The belief that growth is not a luxury — it is how a life stays alive.",',
    '  reflection: "I used to chase outcomes; now I try to chase resonance.",',
    '  motivation: "community",',
    '  motivationText: "",',
    '  lookingFor: "community",',
    "  onboarded: true,",
    "  insights: {",
    '    archetype: "The Quiet Builder",',
    '    summary: "Someone building toward finishing the first draft — grounded in Honesty and Compassion.",',
    '    strengths: ["Honesty", "Compassion", "Courage"],',
    '    growthEdges: ["Patience with self", "Trusting the process"],',
    '    recommendedPath: "community"',
    "  },",
    "  completeness: 100,",
    '  updatedAt: "2026-01-01T00:00:00.000Z"',
    "};",
    "",
    "function parseJson<T>(value: unknown, fallback: T): T {",
    "  if (value == null) return fallback;",
    '  if (typeof value === "object") return value as T;',
    '  if (typeof value === "string") {',
    "    try { return JSON.parse(value) as T; } catch { return fallback; }",
    "  }",
    "  return fallback;",
    "}",
    "",
    "function rowToProfile(row: Record<string, unknown>): OnboardingProfile {",
    "  return {",
    "    id: String(row.id),",
    "    userId: String(row.user_id),",
    '    purpose: String(row.purpose || ""),',
    "    coreValues: parseJson<string[]>(row.core_values, []),",
    "    growthGoals: parseJson<string[]>(row.growth_goals, []),",
    '    drivers: String(row.drivers || ""),',
    '    reflection: String(row.reflection || ""),',
    '    motivation: String(row.motivation || ""),',
    '    motivationText: String(row.motivation_text || ""),',
    '    lookingFor: String(row.looking_for || ""),',
    "    onboarded: Boolean(row.onboarded),",
    "    insights: parseJson<OnboardingInsights | null>(row.insights, null),",
    "    completeness: Number(row.completeness || 0),",
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "// GET /profile/me — one profile per user.",
    "export async function getProfileForUser(userId: string): Promise<OnboardingProfile | null> {",
    "  if (!hasDatabase()) return userId ? { ...fallbackProfile, userId } : fallbackProfile;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, purpose, core_values, growth_goals, drivers, reflection,",
    "        motivation, motivation_text, looking_for, onboarded, insights, completeness, updated_at",
    "      from onboarding_profiles where user_id = ${userId} limit 1",
    "    `;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Admin review — list everyone who has begun onboarding, most complete first.",
    "export async function listProfiles(limit = 100): Promise<OnboardingProfile[]> {",
    "  const capped = Math.min(200, Math.max(1, limit));",
    "  if (!hasDatabase()) return [fallbackProfile].slice(0, capped);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, purpose, core_values, growth_goals, drivers, reflection,",
    "        motivation, motivation_text, looking_for, onboarded, insights, completeness, updated_at",
    "      from onboarding_profiles",
    "      order by completeness desc, updated_at desc",
    "      limit ${capped}",
    "    `;",
    "    return rows.map(rowToProfile);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function getProfileById(id: string): Promise<OnboardingProfile | null> {",
    "  if (!hasDatabase()) return id === fallbackProfile.id ? fallbackProfile : null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, user_id, purpose, core_values, growth_goals, drivers, reflection,",
    "        motivation, motivation_text, looking_for, onboarded, insights, completeness, updated_at",
    "      from onboarding_profiles where id = ${id} limit 1",
    "    `;",
    "    return rows[0] ? rowToProfile(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// POST /onboarding — submit marks the person onboarded and runs the insight",
    "// pass; upserts one row per user. Ported from server.py submit_onboarding.",
    "export async function submitOnboarding(userId: string, input: OnboardingInput): Promise<OnboardingProfile | null> {",
    "  if (!hasDatabase()) return null;",
    "  const insights = deriveInsights(input);",
    "  const completeness = calculateCompleteness(input);",
    "  const values = input.coreValues.filter((v) => v && v.trim());",
    "  const goals = input.growthGoals.filter((g) => g && g.trim());",
    "  const sql = getDatabase();",
    "  const existing = await sql`select id from onboarding_profiles where user_id = ${userId} limit 1`;",
    "  if (existing[0]) {",
    "    await sql`",
    "      update onboarding_profiles set",
    "        purpose = ${input.purpose},",
    "        core_values = ${JSON.stringify(values)},",
    "        growth_goals = ${JSON.stringify(goals)},",
    "        drivers = ${input.drivers},",
    "        reflection = ${input.reflection},",
    '        motivation = ${input.motivation || ""},',
    '        motivation_text = ${input.motivationText || ""},',
    '        looking_for = ${input.lookingFor || ""},',
    "        onboarded = true,",
    "        insights = ${JSON.stringify(insights)},",
    "        completeness = ${completeness},",
    "        updated_at = now()",
    "      where id = ${existing[0].id}",
    "    `;",
    "  } else {",
    "    await sql`",
    "      insert into onboarding_profiles",
    "        (user_id, purpose, core_values, growth_goals, drivers, reflection,",
    "         motivation, motivation_text, looking_for, onboarded, insights, completeness)",
    "      values (${userId}, ${input.purpose}, ${JSON.stringify(values)}, ${JSON.stringify(goals)},",
    '        ${input.drivers}, ${input.reflection}, ${input.motivation || ""}, ${input.motivationText || ""},',
    '        ${input.lookingFor || ""}, true, ${JSON.stringify(insights)}, ${completeness})',
    "    `;",
    "  }",
    "  return getProfileForUser(userId);",
    "}",
    "",
    "// POST /profile/reanalyze — re-run the insight pass over the stored profile.",
    "export async function reanalyzeProfile(userId: string): Promise<OnboardingInsights | null> {",
    "  const profile = await getProfileForUser(userId);",
    "  if (!profile) return null;",
    "  const insights = deriveInsights({",
    "    purpose: profile.purpose,",
    "    coreValues: profile.coreValues,",
    "    growthGoals: profile.growthGoals,",
    "    drivers: profile.drivers,",
    "    reflection: profile.reflection,",
    "    motivation: profile.motivation,",
    "    motivationText: profile.motivationText,",
    "    lookingFor: profile.lookingFor",
    "  });",
    "  if (!hasDatabase()) return insights;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update onboarding_profiles set insights = ${JSON.stringify(insights)}, updated_at = now() where user_id = ${userId}`;",
    "  } catch {",
    "    return insights;",
    "  }",
    "  return insights;",
    "}",
    "",
    "export function onboardingEnabled(): boolean {",
    '  return process.env.FEATURE_ONBOARDING !== "false";',
    "}"
  ]);
}

// ---- src/app/api/onboarding/route.ts (GET my profile, POST submit) ----------

function onboardingApiFile(): GeneratedModuleFile {
  return file("src/app/api/onboarding/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import {',
    "  getProfileForUser,",
    "  submitOnboarding,",
    "  validateOnboarding,",
    "  onboardingEnabled",
    '} from "@/lib/db/onboarding";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!onboardingEnabled()) return NextResponse.json({ ok: false, message: "Onboarding is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const profile = await getProfileForUser(user.id);",
    "  return NextResponse.json({ ok: true, profile });",
    "}",
    "",
    "// Ported from POST /onboarding — submitting marks the person onboarded and runs",
    "// the insight pass. Any signed-in customer may complete their own onboarding.",
    "export async function POST(request: Request) {",
    '  if (!onboardingEnabled()) return NextResponse.json({ ok: false, message: "Onboarding is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const input = {",
    '    purpose: typeof body.purpose === "string" ? body.purpose.trim() : "",',
    "    coreValues: Array.isArray(body.coreValues) ? body.coreValues.map((v) => String(v)) : [],",
    "    growthGoals: Array.isArray(body.growthGoals) ? body.growthGoals.map((g) => String(g)) : [],",
    '    drivers: typeof body.drivers === "string" ? body.drivers.trim() : "",',
    '    reflection: typeof body.reflection === "string" ? body.reflection.trim() : "",',
    '    motivation: typeof body.motivation === "string" ? body.motivation : "",',
    '    motivationText: typeof body.motivationText === "string" ? body.motivationText : "",',
    '    lookingFor: typeof body.lookingFor === "string" ? body.lookingFor : ""',
    "  };",
    "  const problem = validateOnboarding(input);",
    "  if (problem) return NextResponse.json({ ok: false, message: problem }, { status: 400 });",
    "  const profile = await submitOnboarding(user.id, input);",
    '  if (!profile) return NextResponse.json({ ok: false, message: "Connect a database to save your onboarding." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, profile });",
    "}"
  ]);
}

// ---- src/app/api/onboarding/reanalyze/route.ts (POST reanalyze) -------------

function onboardingReanalyzeApiFile(): GeneratedModuleFile {
  return file("src/app/api/onboarding/reanalyze/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { reanalyzeProfile, onboardingEnabled } from "@/lib/db/onboarding";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Ported from POST /profile/reanalyze — re-derive the insight read on demand.",
    "export async function POST() {",
    '  if (!onboardingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const insights = await reanalyzeProfile(user.id);",
    '  if (!insights) return NextResponse.json({ ok: false, message: "Complete your onboarding first." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, insights });",
    "}"
  ]);
}

// ---- src/app/api/onboarding/[id]/route.ts (admin review of one profile) -----

function onboardingDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/onboarding/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getProfileById, onboardingEnabled } from "@/lib/db/onboarding";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!onboardingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const profile = await getProfileById(id);",
    '  if (!profile) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, profile });",
    "}"
  ]);
}

// ---- src/app/onboarding/page.tsx (the person's own onboarding + soul read) --

function onboardingPageFile(): GeneratedModuleFile {
  return file("src/app/onboarding/page.tsx", [
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { getProfileForUser, onboardingEnabled } from "@/lib/db/onboarding";',
    'import { OnboardingForm } from "./OnboardingForm";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OnboardingPage() {",
    "  if (!onboardingEnabled()) {",
    '    return (<main className="shell"><h1>Onboarding</h1><p>Onboarding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/onboarding");',
    "  const user = await getCurrentUser();",
    "  const profile = user ? await getProfileForUser(user.id) : null;",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Onboarding</p>',
    "      {profile?.onboarded ? (",
    "        <>",
    "          <h1>Your becoming</h1>",
    "          {profile.insights ? (",
    "            <>",
    '              <p className="note">{profile.insights.archetype}</p>',
    '              <p className="lede">&ldquo;{profile.insights.summary}&rdquo;</p>',
    '              <section className="grid">',
    "                {profile.insights.strengths.length > 0 ? (",
    '                  <article className="card"><span>Strengths</span><strong>{profile.insights.strengths.join(", ")}</strong></article>',
    "                ) : null}",
    "                {profile.insights.growthEdges.length > 0 ? (",
    '                  <article className="card"><span>Growth edges</span><strong>{profile.insights.growthEdges.join(", ")}</strong></article>',
    "                ) : null}",
    '                <article className="card"><span>Recommended path</span><strong>{profile.insights.recommendedPath}</strong></article>',
    "              </section>",
    "            </>",
    "          ) : null}",
    '          <p>You can update your answers below and refresh your read at any time.</p>',
    "          <OnboardingForm initial={profile} />",
    "        </>",
    "      ) : (",
    "        <>",
    "          <h1>Before we begin</h1>",
    "          <p>Take a few minutes to look inward first. Your purpose, your values, and what",
    "            drives you — this is the ground everything else is built on.</p>",
    "          <OnboardingForm initial={profile} />",
    "        </>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/onboarding/OnboardingForm.tsx (client capture form) ------------

function onboardingFormFile(): GeneratedModuleFile {
  return file("src/app/onboarding/OnboardingForm.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    'import { VALUE_OPTIONS, MOTIVATION_OPTIONS } from "@/lib/db/onboarding-options";',
    "",
    "type Initial = {",
    "  purpose: string;",
    "  coreValues: string[];",
    "  growthGoals: string[];",
    "  drivers: string;",
    "  reflection: string;",
    "  motivation: string;",
    "  motivationText: string;",
    "} | null;",
    "",
    "// The insight read the server returns after a successful save — rendered",
    "// inline so the reveal never depends on a page refresh succeeding.",
    "type RevealedInsights = {",
    "  archetype: string;",
    "  summary: string;",
    "  strengths: string[];",
    "  growthEdges: string[];",
    "  recommendedPath: string;",
    "};",
    "",
    "export function OnboardingForm({ initial }: { initial: Initial }) {",
    "  const router = useRouter();",
    '  const [purpose, setPurpose] = useState(initial?.purpose || "");',
    "  const [coreValues, setCoreValues] = useState<string[]>(initial?.coreValues || []);",
    '  const [growthGoals, setGrowthGoals] = useState<string[]>([',
    '    initial?.growthGoals?.[0] || "",',
    '    initial?.growthGoals?.[1] || "",',
    '    initial?.growthGoals?.[2] || ""',
    "  ]);",
    '  const [drivers, setDrivers] = useState(initial?.drivers || "");',
    '  const [reflection, setReflection] = useState(initial?.reflection || "");',
    '  const [motivation, setMotivation] = useState(initial?.motivation || "");',
    '  const [motivationText, setMotivationText] = useState(initial?.motivationText || "");',
    "  const [saving, setSaving] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "  const [revealed, setRevealed] = useState<RevealedInsights | null>(null);",
    "",
    "  function toggleValue(value: string) {",
    "    setCoreValues((current) =>",
    "      current.includes(value)",
    "        ? current.filter((v) => v !== value)",
    "        : current.length < 6",
    "          ? [...current, value]",
    "          : current",
    "    );",
    "  }",
    "",
    "  async function onSubmit(event: React.FormEvent) {",
    "    event.preventDefault();",
    "    setError(null);",
    "    setSaving(true);",
    "    try {",
    '      const lookingFor = MOTIVATION_OPTIONS.find((m) => m.key === motivation)?.lookingFor || "";',
    '      const response = await fetch("/api/onboarding", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          purpose,",
    "          coreValues,",
    "          growthGoals: growthGoals.filter((g) => g.trim()),",
    "          drivers,",
    "          reflection,",
    "          motivation,",
    "          motivationText,",
    "          lookingFor",
    "        })",
    "      });",
    "      // A failed response may be an HTML error page, not JSON — never let the",
    "      // parse throw swallow the real problem.",
    "      const result = await response.json().catch(() => null);",
    "      if (!response.ok || !result?.ok) {",
    "        setError(",
    "          (result && result.message) ||",
    "            `Could not save your onboarding (error ${response.status}). Please try again.`",
    "        );",
    "        return;",
    "      }",
    "      // Show the read immediately from the save response itself — the reveal",
    "      // must never depend on the background refresh succeeding.",
    "      setRevealed(result.profile?.insights || null);",
    "      router.refresh();",
    "    } catch {",
    '      setError("Something went wrong sending your answers. Please check your connection and try again.");',
    "    } finally {",
    "      setSaving(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={onSubmit}>',
    "      <fieldset>",
    "        <legend>What brings you here?</legend>",
    "        {MOTIVATION_OPTIONS.map((option) => (",
    '          <label key={option.key} className="choice">',
    '            <input type="radio" name="motivation" value={option.key} checked={motivation === option.key} onChange={() => setMotivation(option.key)} />',
    "            <span><strong>{option.label}</strong> — {option.hint}</span>",
    "          </label>",
    "        ))}",
    "      </fieldset>",
    "",
    '      <label htmlFor="onb-motivation-text">If anything else is true, say it (optional)</label>',
    '      <textarea id="onb-motivation-text" className="input" rows={2} value={motivationText} onChange={(e) => setMotivationText(e.target.value)} placeholder="The thing under the thing." />',
    "",
    '      <label htmlFor="onb-purpose">What is your purpose? (not your job — the thing you would do anyway)</label>',
    '      <textarea id="onb-purpose" className="input" rows={4} value={purpose} onChange={(e) => setPurpose(e.target.value)} placeholder="To bridge honest reflection with real action..." required />',
    "",
    '      <fieldset>',
    "        <legend>Choose your core values (pick 3–6)</legend>",
    '        <div className="chip-row">',
    "          {VALUE_OPTIONS.map((value) => (",
    "            <button",
    "              key={value}",
    '              type="button"',
    "              aria-pressed={coreValues.includes(value)}",
    '              className={coreValues.includes(value) ? "chip chip-on" : "chip"}',
    "              onClick={() => toggleValue(value)}",
    "            >",
    "              {value}",
    "            </button>",
    "          ))}",
    "        </div>",
    "      </fieldset>",
    "",
    '      <fieldset>',
    "        <legend>What are you growing toward? (name up to three)</legend>",
    "        {[0, 1, 2].map((i) => (",
    "          <input",
    "            key={i}",
    '            className="input"',
    "            aria-label={`Growth goal ${i + 1}`}",
    '            value={growthGoals[i] || ""}',
    "            onChange={(e) => {",
    "              const next = [...growthGoals];",
    "              next[i] = e.target.value;",
    "              setGrowthGoals(next);",
    "            }}",
    '            placeholder={["Finish the first draft", "A steadier daily rhythm", "Lead one small gathering"][i]}',
    "          />",
    "        ))}",
    "      </fieldset>",
    "",
    '      <label htmlFor="onb-drivers">What drives you?</label>',
    '      <textarea id="onb-drivers" className="input" rows={3} value={drivers} onChange={(e) => setDrivers(e.target.value)} placeholder="The belief that growth is not a luxury..." required />',
    "",
    '      <label htmlFor="onb-reflection">Tell us something true (a reflection)</label>',
    '      <textarea id="onb-reflection" className="input" rows={4} value={reflection} onChange={(e) => setReflection(e.target.value)} placeholder="I used to chase outcomes; now I chase resonance..." required />',
    "",
    "      {revealed ? (",
    '        <section className="grid" role="status" aria-live="polite">',
    '          <article className="card">',
    "            <span>Your archetype</span>",
    "            <strong>{revealed.archetype}</strong>",
    "            <p>{revealed.summary}</p>",
    "          </article>",
    "          {revealed.strengths.length > 0 ? (",
    '            <article className="card"><span>Strengths</span><strong>{revealed.strengths.join(", ")}</strong></article>',
    "          ) : null}",
    '          <article className="card"><span>Recommended path</span><strong>{revealed.recommendedPath}</strong></article>',
    "        </section>",
    "      ) : null}",
    '      {revealed ? <p className="note">Saved. Your read lives on this page — update your answers any time.</p> : null}',
    '      {error ? <p className="note" role="alert">{error}</p> : null}',
    '      <button className="button primary" type="submit" disabled={saving}>',
    '        {saving ? "Reflecting…" : revealed || initial?.purpose ? "Save and refresh my read" : "Reveal my archetype"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/onboarding/review/page.tsx (admin: everyone's profiles) --------

function onboardingReviewPageFile(): GeneratedModuleFile {
  return file("src/app/onboarding/review/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listProfiles, onboardingEnabled } from "@/lib/db/onboarding";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OnboardingReviewPage() {",
    "  if (!onboardingEnabled()) {",
    '    return (<main className="shell"><h1>Onboarding</h1><p>Onboarding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/onboarding/review");',
    "  const user = await getCurrentUser();",
    "  if (!user || !canAccessAdmin(user.role)) {",
    '    return (<main className="shell"><h1>Onboarding review</h1><p className="note">Admins only.</p></main>);',
    "  }",
    "  const profiles = await listProfiles();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Onboarding</p>',
    "      <h1>Onboarding review</h1>",
    "      <p>Everyone who has begun their onboarding, most complete first.</p>",
    "      {profiles.length === 0 ? (",
    '        <p className="note">No one has completed onboarding yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {profiles.map((profile) => (",
    '            <Link className="wide-card" key={profile.id} href={`/onboarding/review/${profile.id}`}>',
    "              <span>{profile.insights?.archetype || (profile.onboarded ? \"Onboarded\" : \"In progress\")}</span>",
    "              <strong>{profile.purpose ? profile.purpose.slice(0, 60) : \"No purpose yet\"}</strong>",
    "              <p>{profile.completeness}% complete · {profile.coreValues.slice(0, 3).join(\", \")}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/onboarding/review/[id]/page.tsx (admin: one profile) -----------

function onboardingReviewDetailPageFile(): GeneratedModuleFile {
  return file("src/app/onboarding/review/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getProfileById, onboardingEnabled } from "@/lib/db/onboarding";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OnboardingReviewDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!onboardingEnabled()) {",
    '    return (<main className="shell"><h1>Onboarding</h1><p>Onboarding is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/onboarding/review");',
    "  const user = await getCurrentUser();",
    "  if (!user || !canAccessAdmin(user.role)) {",
    '    return (<main className="shell"><h1>Onboarding review</h1><p className="note">Admins only.</p></main>);',
    "  }",
    "  const { id } = await params;",
    "  const profile = await getProfileById(id);",
    "  if (!profile) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Onboarding</p>',
    "      <h1>{profile.insights?.archetype || \"Profile\"}</h1>",
    "      {profile.insights?.summary ? <p className=\"lede\">&ldquo;{profile.insights.summary}&rdquo;</p> : null}",
    '      <section className="grid">',
    "        {profile.purpose ? (<article className=\"card\"><span>Purpose</span><strong>{profile.purpose}</strong></article>) : null}",
    "        {profile.coreValues.length > 0 ? (<article className=\"card\"><span>Core values</span><strong>{profile.coreValues.join(\", \")}</strong></article>) : null}",
    "        {profile.growthGoals.length > 0 ? (<article className=\"card\"><span>Growth goals</span><strong>{profile.growthGoals.join(\", \")}</strong></article>) : null}",
    "        {profile.drivers ? (<article className=\"card\"><span>What drives them</span><strong>{profile.drivers}</strong></article>) : null}",
    "        {profile.reflection ? (<article className=\"card\"><span>Reflection</span><strong>{profile.reflection}</strong></article>) : null}",
    "        {profile.motivation ? (<article className=\"card\"><span>Motivation</span><strong>{profile.motivation}{profile.motivationText ? ` — ${profile.motivationText}` : \"\"}</strong></article>) : null}",
    "      </section>",
    '      <p><Link className="button" href="/onboarding/review">Back to review</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

export const purposeOnboardingModule: AppModule = {
  slug: "purpose-onboarding",
  name: "Purpose Onboarding",
  tier: "optional",
  featureFlagEnv: "FEATURE_ONBOARDING",
  files: () => [
    onboardingOptionsFile(),
    onboardingLibFile(),
    onboardingApiFile(),
    onboardingReanalyzeApiFile(),
    onboardingDetailApiFile(),
    onboardingPageFile(),
    onboardingFormFile(),
    onboardingReviewPageFile(),
    onboardingReviewDetailPageFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists onboarding_profiles (",
      "  id uuid primary key default gen_random_uuid(),",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  purpose text not null default '',",
      "  core_values jsonb not null default '[]'::jsonb,",
      "  growth_goals jsonb not null default '[]'::jsonb,",
      "  drivers text not null default '',",
      "  reflection text not null default '',",
      "  motivation text not null default '',",
      "  motivation_text text not null default '',",
      "  looking_for text not null default '',",
      "  onboarded boolean not null default false,",
      "  insights jsonb,",
      "  completeness integer not null default 0,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create unique index if not exists onboarding_profiles_user_idx on onboarding_profiles (user_id);",
      "create index if not exists onboarding_profiles_completeness_idx on onboarding_profiles (completeness desc);"
    ].join("\n"),
  seedSql: () => "",
  envLines: () => [
    "",
    "# Purpose Onboarding — set to false to switch the first-run purpose capture off.",
    "FEATURE_ONBOARDING=true"
  ],
  homeLinks: () => ['        <a className="button" href="/onboarding">Begin onboarding</a>'],
  navLinks: () => [{ href: "/onboarding", label: "Onboarding" }]
};
