// ratings-reviews — ratings, reviews, and reputation for makers, content, and
// orgs. Ported from TWO real sources, fused into one module:
//
//   1. JeepFix src/components/RatingModal.tsx + supabase fix_ratings/solutions:
//      - the fix_ratings model (solution_id, worked [boolean], difficulty_rating
//        1-5 with DIFFICULTY_LABELS, time_taken, cost, notes, created_at).
//      - handleSubmit's aggregate recompute: after inserting a rating, re-read all
//        ratings for the subject, compute successRate = worked/total*100 and
//        rating_count = total, and write them back onto the subject
//        (solutions.success_rate + rating_count).
//
//   2. ChurchConnect backend/routes/church_reviews.py:
//      - the review model (subject_id, anonymous initials display, overall_rating
//        1-5, review_text/title, would_recommend, good_fit_tags, helpful_count,
//        is_public + is_approved moderation, created_at).
//      - submit_public_review's anonymous-name derivation ("J.D." initials).
//      - recalculate_church_ratings: overall average, 1-5 star distribution,
//        recommendation_rate %, most-recent-review date, written back onto the
//        subject (avg_rating, review_count, recommendation_rate).
//      - get_church_reviews sort options (recent, helpful, rating_high, rating_low).
//      - mark_helpful ($inc helpful_count).
//      - admin moderate_review (approve / reject / hide) + get_pending_reviews.
//
// Generalized off "solutions"/"churches" into a neutral "subject" (a maker,
// a piece of content, or an org) so it drops into any app. Runs on the app
// owner's own database with graceful sample-data fallback, feature-flagged
// (FEATURE_RATINGS); customers browse + rate, admins moderate.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/ratings-reviews.ts (model + queries) ------------------------

function ratingsLibFile(): GeneratedModuleFile {
  return file("src/lib/db/ratings-reviews.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The thing being rated — a maker, a piece of content, or an org. Ported from",
    "// JeepFix's `solutions` (the reputation-carrying row that holds the rolled-up",
    "// success_rate + rating_count) and ChurchConnect's church rating summary",
    "// (avg_rating, review_count, recommendation_rate).",
    "export type RatedSubject = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  kind: string;",
    "  title: string;",
    "  summary: string;",
    "  avgRating: number;",
    "  successRate: number;",
    "  recommendationRate: number;",
    "  ratingCount: number;",
    "  createdAt: string;",
    "};",
    "",
    "// A single rating/review. Fuses JeepFix fix_ratings (worked, difficulty_rating,",
    "// time_taken, cost, notes) with ChurchConnect review fields (overall_rating,",
    "// review_text, would_recommend, helpful_count, is_public/is_approved moderation).",
    "export type Rating = {",
    "  id: string;",
    "  subjectId: string;",
    "  authorId: string | null;",
    "  anonymousName: string;",
    "  worked: boolean;",
    "  overallRating: number;",
    "  difficultyRating: number;",
    "  timeTaken: string;",
    "  cost: string;",
    "  reviewText: string;",
    "  wouldRecommend: boolean;",
    "  helpfulCount: number;",
    "  isPublic: boolean;",
    "  isApproved: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "// The kinds of things reputation attaches to for this module's framing.",
    'export const SUBJECT_KINDS = ["maker", "content", "org"];',
    "",
    "// Difficulty labels, ported verbatim from RatingModal.tsx DIFFICULTY_LABELS.",
    'export const DIFFICULTY_LABELS = ["Very Easy", "Easy", "Moderate", "Hard", "Expert"];',
    "",
    "export function difficultyLabel(rating: number): string {",
    "  const i = Math.min(5, Math.max(1, Math.round(rating))) - 1;",
    '  return DIFFICULTY_LABELS[i] || "Moderate";',
    "}",
    "",
    "// Anonymous display name from initials, ported from church_reviews.py",
    '// submit_public_review: "Jane Doe" -> "J.D.", one-word/empty -> "J." / "A.".',
    "export function anonymousName(name: string): string {",
    '  const parts = (name || "").trim().split(/\\s+/).filter(Boolean);',
    "  if (parts.length >= 2) {",
    "    return `${parts[0][0]}.${parts[parts.length - 1][0]}.`.toUpperCase();",
    "  }",
    '  if (parts.length === 1) return `${parts[0][0]}.`.toUpperCase();',
    '  return "A.";',
    "}",
    "",
    "export type SubjectFilters = { q?: string; kind?: string; limit?: number };",
    'export type RatingSort = "recent" | "helpful" | "rating_high" | "rating_low";',
    "",
    "const fallbackSubjects: RatedSubject[] = [",
    "  {",
    '    id: "sample-1",',
    "    ownerId: null,",
    '    kind: "content",',
    '    title: "Fix a soft brake pedal",',
    '    summary: "Bleed the lines and check the master cylinder — a common, doable fix.",',
    "    avgRating: 4.6,",
    "    successRate: 88,",
    "    recommendationRate: 92,",
    "    ratingCount: 25,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-2",',
    "    ownerId: null,",
    '    kind: "maker",',
    '    title: "North Shore Auto Works",',
    '    summary: "Independent shop known for honest diagnostics and fair pricing.",',
    "    avgRating: 4.2,",
    "    successRate: 0,",
    "    recommendationRate: 80,",
    "    ratingCount: 10,",
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackRatings: Rating[] = [",
    "  {",
    '    id: "rating-1",',
    '    subjectId: "sample-1",',
    "    authorId: null,",
    '    anonymousName: "M.S.",',
    "    worked: true,",
    "    overallRating: 5,",
    "    difficultyRating: 2,",
    '    timeTaken: "2 hours",',
    '    cost: "$40",',
    '    reviewText: "Followed it step by step and the pedal is firm again. Save yourself a shop visit.",',
    "    wouldRecommend: true,",
    "    helpfulCount: 12,",
    "    isPublic: true,",
    "    isApproved: true,",
    '    createdAt: "2025-01-10T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "rating-2",',
    '    subjectId: "sample-1",',
    "    authorId: null,",
    '    anonymousName: "A.",',
    "    worked: false,",
    "    overallRating: 3,",
    "    difficultyRating: 4,",
    '    timeTaken: "half a day",',
    '    cost: "$0",',
    '    reviewText: "Turned out my issue was the ABS module, not the lines. Still a good writeup.",',
    "    wouldRecommend: true,",
    "    helpfulCount: 3,",
    "    isPublic: true,",
    "    isApproved: true,",
    '    createdAt: "2025-01-12T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToSubject(row: Record<string, unknown>): RatedSubject {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    kind: String(row.kind || "content"),',
    '    title: String(row.title || ""),',
    '    summary: String(row.summary || ""),',
    "    avgRating: Number(row.avg_rating || 0),",
    "    successRate: Number(row.success_rate || 0),",
    "    recommendationRate: Number(row.recommendation_rate || 0),",
    "    ratingCount: Number(row.rating_count || 0),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToRating(row: Record<string, unknown>): Rating {",
    "  return {",
    "    id: String(row.id),",
    "    subjectId: String(row.subject_id),",
    "    authorId: row.author_id != null ? String(row.author_id) : null,",
    '    anonymousName: String(row.anonymous_name || "A."),',
    '    worked: row.worked === true || String(row.worked) === "true",',
    "    overallRating: Number(row.overall_rating || 0),",
    "    difficultyRating: Number(row.difficulty_rating || 3),",
    '    timeTaken: String(row.time_taken || ""),',
    '    cost: String(row.cost || ""),',
    '    reviewText: String(row.review_text || ""),',
    '    wouldRecommend: row.would_recommend === true || String(row.would_recommend) === "true",',
    "    helpfulCount: Number(row.helpful_count || 0),",
    '    isPublic: row.is_public === true || String(row.is_public) === "true",',
    '    isApproved: row.is_approved === true || String(row.is_approved) === "true",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// List + search subjects, generalized from ChurchConnect discovery: match title",
    "// or summary (and optionally kind), highest-rated first.",
    "export async function listSubjects(filters: SubjectFilters = {}): Promise<RatedSubject[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    "  const kind = filters.kind;",
    "  if (!hasDatabase()) {",
    "    return fallbackSubjects",
    "      .filter((s) => !kind || s.kind === kind)",
    '      .filter((s) => !q || (s.title + " " + s.summary).toLowerCase().includes(q))',
    "      .sort((a, b) => b.avgRating - a.avgRating)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    "    const k = kind || null;",
    "    const rows = await sql`",
    "      select id, owner_id, kind, title, summary, avg_rating, success_rate,",
    "        recommendation_rate, rating_count, created_at",
    "      from ratings_reviews_subjects",
    "      where (${k}::text is null or kind = ${k})",
    "        and (${like}::text is null",
    "          or lower(title) like ${like}",
    "          or lower(summary) like ${like})",
    "      order by avg_rating desc, rating_count desc, created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToSubject);",
    "  } catch {",
    "    return fallbackSubjects.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getSubject(id: string): Promise<RatedSubject | null> {",
    "  if (!hasDatabase()) return fallbackSubjects.find((s) => s.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, kind, title, summary, avg_rating, success_rate,",
    "        recommendation_rate, rating_count, created_at",
    "      from ratings_reviews_subjects where id = ${id} limit 1`;",
    "    return rows[0] ? rowToSubject(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateSubjectInput = {",
    "  ownerId?: string | null;",
    "  kind?: string;",
    "  title: string;",
    "  summary?: string;",
    "};",
    "",
    "// Register a subject to collect reputation on. Scoped to the owner (user.id).",
    "export async function createSubject(input: CreateSubjectInput): Promise<RatedSubject | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into ratings_reviews_subjects (owner_id, kind, title, summary)",
    '      values (${input.ownerId || null}, ${input.kind || "content"}, ${input.title}, ${input.summary || ""})',
    "      returning id, owner_id, kind, title, summary, avg_rating, success_rate,",
    "        recommendation_rate, rating_count, created_at`;",
    "    return rows[0] ? rowToSubject(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Reviews for a subject, ported from get_church_reviews: only public + approved,",
    "// with the recent / helpful / rating_high / rating_low sort options.",
    'export async function listRatings(subjectId: string, sort: RatingSort = "recent", limit = 50): Promise<Rating[]> {',
    "  const capped = Math.min(200, Math.max(1, limit));",
    "  if (!hasDatabase()) {",
    "    const rows = fallbackRatings.filter((r) => r.subjectId === subjectId && r.isPublic && r.isApproved);",
    "    return sortRatings(rows, sort).slice(0, capped);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, subject_id, author_id, anonymous_name, worked, overall_rating,",
    "        difficulty_rating, time_taken, cost, review_text, would_recommend,",
    "        helpful_count, is_public, is_approved, created_at",
    "      from ratings_reviews_ratings",
    "      where subject_id = ${subjectId} and is_public = true and is_approved = true",
    "      order by",
    "        case when ${sort} = 'helpful' then helpful_count end desc,",
    "        case when ${sort} = 'rating_high' then overall_rating end desc,",
    "        case when ${sort} = 'rating_low' then overall_rating end asc,",
    "        created_at desc",
    "      limit ${capped}",
    "    `;",
    "    return rows.map(rowToRating);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "function sortRatings(rows: Rating[], sort: RatingSort): Rating[] {",
    "  const copy = [...rows];",
    '  if (sort === "helpful") return copy.sort((a, b) => b.helpfulCount - a.helpfulCount);',
    '  if (sort === "rating_high") return copy.sort((a, b) => b.overallRating - a.overallRating);',
    '  if (sort === "rating_low") return copy.sort((a, b) => a.overallRating - b.overallRating);',
    "  return copy.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));",
    "}",
    "",
    "// The 1-5 star distribution + rolled-up numbers for a subject, ported from",
    "// recalculate_church_ratings' rating_distribution + recommendation_rate.",
    "export type RatingSummary = {",
    "  total: number;",
    "  avgRating: number;",
    "  successRate: number;",
    "  recommendationRate: number;",
    "  distribution: Record<number, number>;",
    "};",
    "",
    "export function summarize(ratings: Rating[]): RatingSummary {",
    "  const total = ratings.length;",
    "  const distribution: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };",
    "  let overallSum = 0;",
    "  let overallCount = 0;",
    "  let workedCount = 0;",
    "  let recommendCount = 0;",
    "  for (const r of ratings) {",
    "    if (r.overallRating >= 1 && r.overallRating <= 5) {",
    "      distribution[r.overallRating] = (distribution[r.overallRating] || 0) + 1;",
    "      overallSum += r.overallRating;",
    "      overallCount += 1;",
    "    }",
    "    if (r.worked) workedCount += 1;",
    "    if (r.wouldRecommend) recommendCount += 1;",
    "  }",
    "  return {",
    "    total,",
    "    avgRating: overallCount ? Math.round((overallSum / overallCount) * 10) / 10 : 0,",
    "    successRate: total ? Math.round((workedCount / total) * 100) : 0,",
    "    recommendationRate: total ? Math.round((recommendCount / total) * 100) : 0,",
    "    distribution",
    "  };",
    "}",
    "",
    "export type SubmitRatingInput = {",
    "  subjectId: string;",
    "  authorId?: string | null;",
    "  authorName?: string;",
    "  worked: boolean;",
    "  overallRating?: number;",
    "  difficultyRating?: number;",
    "  timeTaken?: string;",
    "  cost?: string;",
    "  reviewText?: string;",
    "  wouldRecommend?: boolean;",
    "  isPublic?: boolean;",
    "};",
    "",
    "// Submit a rating, then recompute + write back the subject's aggregates — the",
    "// core of both sources: JeepFix handleSubmit (insert fix_rating -> re-read all",
    "// -> success_rate + rating_count) and church_reviews recalculate_church_ratings",
    "// (avg_rating + recommendation_rate). Reviews auto-approve (is_approved=true),",
    "// mirroring church_reviews' 'auto-approve for now' policy; admins can hide later.",
    "export async function submitRating(input: SubmitRatingInput): Promise<Rating | null> {",
    "  if (!hasDatabase()) return null;",
    "  const overall = clampStar(input.overallRating, input.worked ? 5 : 3);",
    "  const difficulty = clampStar(input.difficultyRating, 3);",
    '  const anon = anonymousName(input.authorName || "");',
    "  const wouldRecommend = input.wouldRecommend !== false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into ratings_reviews_ratings (",
    "        subject_id, author_id, anonymous_name, worked, overall_rating,",
    "        difficulty_rating, time_taken, cost, review_text, would_recommend,",
    "        is_public, is_approved",
    "      ) values (",
    "        ${input.subjectId}, ${input.authorId || null}, ${anon}, ${input.worked},",
    '        ${overall}, ${difficulty}, ${input.timeTaken || ""}, ${input.cost || ""},',
    '        ${input.reviewText || ""}, ${wouldRecommend}, ${input.isPublic !== false}, true',
    "      )",
    "      returning id, subject_id, author_id, anonymous_name, worked, overall_rating,",
    "        difficulty_rating, time_taken, cost, review_text, would_recommend,",
    "        helpful_count, is_public, is_approved, created_at`;",
    "    const created = rows[0] ? rowToRating(rows[0]) : null;",
    "    if (created) await recalculateSubject(input.subjectId);",
    "    return created;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "function clampStar(value: number | undefined, fallback: number): number {",
    '  if (typeof value !== "number" || Number.isNaN(value)) return fallback;',
    "  return Math.min(5, Math.max(1, Math.round(value)));",
    "}",
    "",
    "// Recompute the rolled-up reputation onto the subject. Ported from JeepFix",
    "// handleSubmit's re-read-and-update and church_reviews recalculate_church_ratings:",
    "// count public+approved ratings, average the stars, take the worked-rate as the",
    "// success_rate, and the would_recommend-rate as recommendation_rate.",
    "export async function recalculateSubject(subjectId: string): Promise<RatingSummary | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, subject_id, author_id, anonymous_name, worked, overall_rating,",
    "        difficulty_rating, time_taken, cost, review_text, would_recommend,",
    "        helpful_count, is_public, is_approved, created_at",
    "      from ratings_reviews_ratings",
    "      where subject_id = ${subjectId} and is_public = true and is_approved = true`;",
    "    const ratings = rows.map(rowToRating);",
    "    const summary = summarize(ratings);",
    "    await sql`",
    "      update ratings_reviews_subjects set",
    "        avg_rating = ${summary.avgRating},",
    "        success_rate = ${summary.successRate},",
    "        recommendation_rate = ${summary.recommendationRate},",
    "        rating_count = ${summary.total}",
    "      where id = ${subjectId}`;",
    "    return summary;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Mark a review helpful, ported from mark_helpful ($inc helpful_count).",
    "export async function markHelpful(ratingId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update ratings_reviews_ratings set helpful_count = helpful_count + 1 where id = ${ratingId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Admin moderation, ported from moderate_review (approve / reject / hide). A",
    "// hidden or rejected review drops out of the public list and the aggregates.",
    "export async function moderateRating(",
    "  ratingId: string,",
    '  action: "approve" | "reject" | "hide"',
    "): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    const found = await sql`select subject_id from ratings_reviews_ratings where id = ${ratingId} limit 1`;",
    "    if (!found[0]) return false;",
    "    const subjectId = String(found[0].subject_id);",
    '    if (action === "approve") {',
    "      await sql`update ratings_reviews_ratings set is_approved = true, is_public = true where id = ${ratingId}`;",
    '    } else if (action === "reject") {',
    "      await sql`update ratings_reviews_ratings set is_approved = false, is_public = false where id = ${ratingId}`;",
    "    } else {",
    "      await sql`update ratings_reviews_ratings set is_public = false where id = ${ratingId}`;",
    "    }",
    "    await recalculateSubject(subjectId);",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// The moderation queue — everything not yet approved, ported from",
    "// get_pending_reviews (is_approved = false).",
    "export async function listPending(limit = 50): Promise<Rating[]> {",
    "  if (!hasDatabase()) return [];",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, subject_id, author_id, anonymous_name, worked, overall_rating,",
    "        difficulty_rating, time_taken, cost, review_text, would_recommend,",
    "        helpful_count, is_public, is_approved, created_at",
    "      from ratings_reviews_ratings",
    "      where is_approved = false",
    "      order by created_at desc limit ${Math.min(200, Math.max(1, limit))}`;",
    "    return rows.map(rowToRating);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export function ratingsReviewsEnabled(): boolean {",
    '  return process.env.FEATURE_RATINGS !== "false";',
    "}"
  ]);
}

// ---- src/app/api/ratings-reviews/route.ts (list + create subject) -----------

function subjectsApiFile(): GeneratedModuleFile {
  return file("src/app/api/ratings-reviews/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listSubjects, createSubject, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!ratingsReviewsEnabled()) return NextResponse.json({ ok: false, message: "Ratings are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const subjects = await listSubjects({",
    '    q: url.searchParams.get("q") || undefined,',
    '    kind: url.searchParams.get("kind") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, subjects });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "A title is required." }, { status: 400 });',
    "  }",
    "  const created = await createSubject({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    title,",
    '    kind: typeof body.kind === "string" ? body.kind : undefined,',
    '    summary: typeof body.summary === "string" ? body.summary : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save this." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, subject: created });",
    "}"
  ]);
}

// ---- src/app/api/ratings-reviews/[id]/route.ts (detail + submit rating) ------

function subjectDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/ratings-reviews/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getSubject, listRatings, submitRating, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    'import type { RatingSort } from "@/lib/db/ratings-reviews";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!ratingsReviewsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const subject = await getSubject(id);",
    '  if (!subject) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const url = new URL(request.url);",
    '  const sort = (url.searchParams.get("sort") || "recent") as RatingSort;',
    "  const ratings = await listRatings(id, sort);",
    "  return NextResponse.json({ ok: true, subject, ratings });",
    "}",
    "",
    "// Submit a rating/review for this subject, ported from JeepFix handleSubmit +",
    "// church_reviews submit_public_review (aggregates recomputed server-side).",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to rate." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  if (typeof body.worked !== "boolean") {',
    '    return NextResponse.json({ ok: false, message: "Please say whether it worked for you." }, { status: 400 });',
    "  }",
    "  const created = await submitRating({",
    "    subjectId: id,",
    "    authorId: user?.id ? String(user.id) : null,",
    '    authorName: typeof body.authorName === "string" ? body.authorName : (user?.name || ""),',
    "    worked: body.worked,",
    '    overallRating: typeof body.overallRating === "number" ? body.overallRating : undefined,',
    '    difficultyRating: typeof body.difficultyRating === "number" ? body.difficultyRating : undefined,',
    '    timeTaken: typeof body.timeTaken === "string" ? body.timeTaken : undefined,',
    '    cost: typeof body.cost === "string" ? body.cost : undefined,',
    '    reviewText: typeof body.reviewText === "string" ? body.reviewText : undefined,',
    "    wouldRecommend: body.wouldRecommend !== false",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save ratings." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, rating: created, message: "Thank you for your rating! It helps others." });',
    "}"
  ]);
}

// ---- src/app/api/ratings-reviews/[id]/moderate/route.ts (admin + helpful) ---

function moderateApiFile(): GeneratedModuleFile {
  return file("src/app/api/ratings-reviews/[id]/moderate/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { markHelpful, moderateRating, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Mark a review helpful — any signed-in customer. Ported from mark_helpful.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!ratingsReviewsEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const ok = await markHelpful(id);",
    "  return NextResponse.json({ ok });",
    "}",
    "",
    "// Approve / reject / hide a review — admins only. Ported from moderate_review.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = body.action === "reject" || body.action === "hide" ? body.action : "approve";',
    "  const ok = await moderateRating(id, action);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to moderate." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/page.tsx (subject list + search) ---------------

function subjectsPageFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listSubjects, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    'import { AddSubjectForm } from "./add-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function RatingsReviewsPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; kind?: string }>;",
    "}) {",
    "  if (!ratingsReviewsEnabled()) {",
    '    return (<main className="shell"><h1>Ratings &amp; Reviews</h1><p>Ratings are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ratings-reviews");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const kind = (params?.kind || "").trim();',
    "  const subjects = await listSubjects({ q: q || undefined, kind: kind || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Reputation</p>',
    "      <h1>Ratings &amp; Reviews</h1>",
    "      <p>Real ratings from real people — for the makers, guides, and organizations worth knowing about.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search by name" aria-label="Search" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {subjects.length === 0 ? (",
    '        <p className="note">{q ? `Nothing matches "${q}" yet.` : "Nothing has been added to rate yet. Add the first one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {subjects.map((s) => (",
    '            <Link className="wide-card" key={s.id} href={`/ratings-reviews/${s.id}`}>',
    "              <span>{s.kind}</span>",
    "              <strong>{s.title}</strong>",
    "              {s.summary ? <p>{s.summary}</p> : null}",
    '              <p className="note">',
    '                {s.ratingCount > 0 ? `${s.avgRating.toFixed(1)} ★ · ${s.ratingCount} rating${s.ratingCount === 1 ? "" : "s"} · ${s.successRate}% worked` : "No ratings yet"}',
    "              </p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Add something to rate</h2>",
    "      <p>Know a maker, a guide, or an organization others should hear about? Add it and start the reputation.</p>",
    "      <AddSubjectForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/add-form.tsx (client) --------------------------

function addFormFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/add-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function AddSubjectForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/ratings-reviews", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          kind: form.get("kind"),',
    '          summary: form.get("summary")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("idle");',
    "      if (data.subject?.id) {",
    "        router.push(`/ratings-reviews/${data.subject.id}`);",
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Name it (a maker, a guide, an org)" aria-label="Title" required />',
    '      <select className="input" name="kind" aria-label="Kind" defaultValue="content">',
    '        <option value="maker">Maker</option>',
    '        <option value="content">Content / guide</option>',
    '        <option value="org">Organization</option>',
    "      </select>",
    '      <textarea className="input" name="summary" rows={3} placeholder="A sentence on what this is." aria-label="Summary" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Adding…" : "Add"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/[id]/page.tsx (detail: summary + reviews + rate)

function subjectDetailPageFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { getSubject, listRatings, summarize, difficultyLabel, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    'import { RateForm } from "./rate-form";',
    'import { HelpfulButton } from "./helpful-button";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SubjectDetailPage({",
    "  params,",
    "  searchParams",
    "}: {",
    "  params: Promise<{ id: string }>;",
    "  searchParams?: Promise<{ sort?: string }>;",
    "}) {",
    "  if (!ratingsReviewsEnabled()) {",
    '    return (<main className="shell"><h1>Ratings &amp; Reviews</h1><p>Ratings are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ratings-reviews");',
    "  const { id } = await params;",
    "  const sp = searchParams ? await searchParams : undefined;",
    '  const sort = (sp?.sort === "helpful" || sp?.sort === "rating_high" || sp?.sort === "rating_low") ? sp.sort : "recent";',
    "  const subject = await getSubject(id);",
    "  if (!subject) notFound();",
    "  const ratings = await listRatings(id, sort);",
    "  const summary = summarize(ratings);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{subject.kind}</p>',
    "      <h1>{subject.title}</h1>",
    "      {subject.summary ? <p>{subject.summary}</p> : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Rating</span><strong>{summary.total > 0 ? `${summary.avgRating.toFixed(1)} ★` : "—"}</strong></article>',
    '        <article className="card"><span>Worked for</span><strong>{summary.total > 0 ? `${summary.successRate}%` : "—"}</strong></article>',
    '        <article className="card"><span>Would recommend</span><strong>{summary.total > 0 ? `${summary.recommendationRate}%` : "—"}</strong></article>',
    '        <article className="card"><span>Ratings</span><strong>{summary.total}</strong></article>',
    "      </section>",
    "      {summary.total > 0 ? (",
    '        <section className="stack" aria-label="Star distribution">',
    "          {[5, 4, 3, 2, 1].map((star) => (",
    '            <p className="note" key={star}>{star} ★ · {summary.distribution[star] || 0}</p>',
    "          ))}",
    "        </section>",
    "      ) : null}",
    "      <h2>Reviews</h2>",
    '      <form className="stack" method="get">',
    '        <select className="input" name="sort" defaultValue={sort} aria-label="Sort reviews">',
    '          <option value="recent">Most recent</option>',
    '          <option value="helpful">Most helpful</option>',
    '          <option value="rating_high">Highest rated</option>',
    '          <option value="rating_low">Lowest rated</option>',
    "        </select>",
    '        <button className="button" type="submit">Sort</button>',
    "      </form>",
    "      {ratings.length === 0 ? (",
    '        <p className="note">No reviews yet. Be the first to rate this.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {ratings.map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    '              <span>{r.overallRating} ★ · {r.worked ? "Worked" : "Did not work"}</span>',
    "              <strong>{r.anonymousName}</strong>",
    '              <p className="note">Difficulty: {difficultyLabel(r.difficultyRating)}{r.timeTaken ? ` · ${r.timeTaken}` : ""}{r.cost ? ` · ${r.cost}` : ""}</p>',
    "              {r.reviewText ? <p>{r.reviewText}</p> : null}",
    "              <HelpfulButton id={r.id} count={r.helpfulCount} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Rate this</h2>",
    "      <RateForm subjectId={subject.id} />",
    '      <p><Link className="button" href="/ratings-reviews">Back to all</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/[id]/rate-form.tsx (client, from RatingModal) --

function rateFormFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/[id]/rate-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Ported from JeepFix RatingModal.tsx: worked yes/no, difficulty 1-5 with the",
    "// same labels, time taken, cost, and free-text notes.",
    'const DIFFICULTY_LABELS = ["Very Easy", "Easy", "Moderate", "Hard", "Expert"];',
    "",
    "export function RateForm({ subjectId }: { subjectId: string }) {",
    "  const router = useRouter();",
    "  const [worked, setWorked] = useState<boolean | null>(null);",
    "  const [overallRating, setOverallRating] = useState(5);",
    "  const [difficultyRating, setDifficultyRating] = useState(3);",
    '  const [timeTaken, setTimeTaken] = useState("");',
    '  const [cost, setCost] = useState("");',
    '  const [reviewText, setReviewText] = useState("");',
    "  const [wouldRecommend, setWouldRecommend] = useState(true);",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit() {",
    "    if (worked === null) return;",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/ratings-reviews/${subjectId}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    "          worked,",
    "          overallRating,",
    "          difficultyRating,",
    "          timeTaken,",
    "          cost,",
    "          reviewText,",
    "          wouldRecommend",
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Failed to submit rating. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Thank you for your rating!");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Received</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      <fieldset>",
    "        <legend>Did this work for you?</legend>",
    '        <div className="stack">',
    '          <button type="button" className={worked === true ? "button primary" : "button"} onClick={() => setWorked(true)} aria-pressed={worked === true}>Yes, it worked</button>',
    '          <button type="button" className={worked === false ? "button primary" : "button"} onClick={() => setWorked(false)} aria-pressed={worked === false}>No, it didn&apos;t</button>',
    "        </div>",
    "      </fieldset>",
    '      <label className="stack">Overall rating',
    '        <select className="input" value={overallRating} onChange={(e) => setOverallRating(Number(e.target.value))} aria-label="Overall rating">',
    "          {[5, 4, 3, 2, 1].map((n) => (<option key={n} value={n}>{n} ★</option>))}",
    "        </select>",
    "      </label>",
    '      <label className="stack">How difficult was it?',
    '        <select className="input" value={difficultyRating} onChange={(e) => setDifficultyRating(Number(e.target.value))} aria-label="Difficulty">',
    "          {[1, 2, 3, 4, 5].map((n) => (<option key={n} value={n}>{DIFFICULTY_LABELS[n - 1]}</option>))}",
    "        </select>",
    "      </label>",
    '      <input className="input" value={timeTaken} onChange={(e) => setTimeTaken(e.target.value)} placeholder="Time taken (e.g., 2 hours)" aria-label="Time taken" />',
    '      <input className="input" value={cost} onChange={(e) => setCost(e.target.value)} placeholder="Cost (e.g., $150)" aria-label="Cost" />',
    '      <textarea className="input" value={reviewText} onChange={(e) => setReviewText(e.target.value)} rows={3} placeholder="Tips, gotchas, or details that might help others…" aria-label="Notes" />',
    '      <label className="check"><input type="checkbox" checked={wouldRecommend} onChange={(e) => setWouldRecommend(e.target.checked)} /> I would recommend this to others</label>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="button" onClick={submit} disabled={worked === null || status === "saving"}>',
    '        {status === "saving" ? "Submitting…" : "Submit rating"}',
    "      </button>",
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/[id]/helpful-button.tsx (client) ---------------

function helpfulButtonFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/[id]/helpful-button.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    "",
    "// Ported from mark_helpful — an optimistic helpful-count bump.",
    "export function HelpfulButton({ id, count }: { id: string; count: number }) {",
    "  const [helpful, setHelpful] = useState(count);",
    "  const [done, setDone] = useState(false);",
    "",
    "  async function mark() {",
    "    if (done) return;",
    "    setDone(true);",
    "    setHelpful((n) => n + 1);",
    "    try {",
    "      await fetch(`/api/ratings-reviews/${id}/moderate`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({})",
    "      });",
    "    } catch {",
    "      // best-effort; the local bump already gave feedback.",
    "    }",
    "  }",
    "",
    "  return (",
    '    <button className="button" type="button" onClick={mark} disabled={done} aria-label="Mark this review helpful">',
    '      {done ? "Thanks!" : "Helpful"} · {helpful}',
    "    </button>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/moderate/page.tsx (admin queue) ----------------

function moderatePageFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/moderate/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listPending, difficultyLabel, ratingsReviewsEnabled } from "@/lib/db/ratings-reviews";',
    'import { ModerateButtons } from "./moderate-buttons";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ModeratePage() {",
    "  if (!ratingsReviewsEnabled()) {",
    '    return (<main className="shell"><h1>Moderation</h1><p>Ratings are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/ratings-reviews/moderate");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Moderation</h1><p className="note">This queue is for admins only.</p></main>);',
    "  }",
    "  const pending = await listPending();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Review moderation</h1>",
    "      <p>Reviews are public by default. Hidden or rejected reviews drop out of the ratings.</p>",
    "      {pending.length === 0 ? (",
    '        <p className="note">Nothing pending. The queue is clear.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {pending.map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    '              <span>{r.overallRating} ★ · {r.worked ? "Worked" : "Did not work"}</span>',
    "              <strong>{r.anonymousName}</strong>",
    '              <p className="note">Difficulty: {difficultyLabel(r.difficultyRating)}</p>',
    "              {r.reviewText ? <p>{r.reviewText}</p> : null}",
    "              <ModerateButtons id={r.id} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/ratings-reviews">Back to all</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/ratings-reviews/moderate/moderate-buttons.tsx (client) ---------

function moderateButtonsFile(): GeneratedModuleFile {
  return file("src/app/ratings-reviews/moderate/moderate-buttons.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ModerateButtons({ id }: { id: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    '  async function moderate(action: "approve" | "reject" | "hide") {',
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/ratings-reviews/${id}/moderate`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this review.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className="button primary" type="button" onClick={() => moderate("approve")} disabled={status === "working"}>Approve</button>',
    '      <button className="button" type="button" onClick={() => moderate("hide")} disabled={status === "working"}>Hide</button>',
    '      <button className="button" type="button" onClick={() => moderate("reject")} disabled={status === "working"}>Reject</button>',
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const ratingsReviewsModule: AppModule = {
  slug: "ratings-reviews",
  name: "Ratings & Reviews",
  tier: "optional",
  featureFlagEnv: "FEATURE_RATINGS",
  files: () => [
    ratingsLibFile(),
    subjectsApiFile(),
    subjectDetailApiFile(),
    moderateApiFile(),
    subjectsPageFile(),
    addFormFile(),
    subjectDetailPageFile(),
    rateFormFile(),
    helpfulButtonFile(),
    moderatePageFile(),
    moderateButtonsFile()
  ],
  schemaSql: () =>
    [
      "",
      "-- The rated subject (maker / content / org). Holds the rolled-up reputation,",
      "-- ported from JeepFix solutions (success_rate, rating_count) + church rating",
      "-- summary (avg_rating, recommendation_rate).",
      "create table if not exists ratings_reviews_subjects (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  kind text not null default 'content',",
      "  title text not null default '',",
      "  summary text not null default '',",
      "  avg_rating numeric not null default 0,",
      "  success_rate numeric not null default 0,",
      "  recommendation_rate numeric not null default 0,",
      "  rating_count integer not null default 0,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists ratings_reviews_subjects_kind_idx on ratings_reviews_subjects (kind);",
      "create index if not exists ratings_reviews_subjects_rating_idx on ratings_reviews_subjects (avg_rating desc);",
      "create index if not exists ratings_reviews_subjects_owner_idx on ratings_reviews_subjects (owner_id);",
      "",
      "-- A single rating/review, fused from JeepFix fix_ratings (worked,",
      "-- difficulty_rating, time_taken, cost, notes) + church review fields",
      "-- (overall_rating, review_text, would_recommend, helpful_count, moderation).",
      "create table if not exists ratings_reviews_ratings (",
      "  id uuid primary key default gen_random_uuid(),",
      "  subject_id uuid not null references ratings_reviews_subjects(id) on delete cascade,",
      "  author_id uuid references users(id) on delete set null,",
      "  anonymous_name text not null default 'A.',",
      "  worked boolean not null default true,",
      "  overall_rating integer not null default 5,",
      "  difficulty_rating integer not null default 3,",
      "  time_taken text not null default '',",
      "  cost text not null default '',",
      "  review_text text not null default '',",
      "  would_recommend boolean not null default true,",
      "  helpful_count integer not null default 0,",
      "  is_public boolean not null default true,",
      "  is_approved boolean not null default true,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists ratings_reviews_ratings_subject_idx on ratings_reviews_ratings (subject_id, created_at desc);",
      "create index if not exists ratings_reviews_ratings_approved_idx on ratings_reviews_ratings (is_approved);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into ratings_reviews_subjects (id, kind, title, summary, avg_rating, success_rate, recommendation_rate, rating_count) values",
      "  ('11111111-1111-1111-1111-111111111111', 'content', 'Fix a soft brake pedal', 'Bleed the lines and check the master cylinder — a common, doable fix.', 4.6, 88, 92, 2)",
      "on conflict do nothing;",
      "insert into ratings_reviews_ratings (subject_id, anonymous_name, worked, overall_rating, difficulty_rating, time_taken, cost, review_text, would_recommend, helpful_count) values",
      "  ('11111111-1111-1111-1111-111111111111', 'M.S.', true, 5, 2, '2 hours', '$40', 'Followed it step by step and the pedal is firm again.', true, 12),",
      "  ('11111111-1111-1111-1111-111111111111', 'A.', false, 3, 4, 'half a day', '$0', 'Turned out my issue was the ABS module, not the lines.', true, 3)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Ratings & Reviews — set to false to switch ratings, reviews, and reputation off.",
    "FEATURE_RATINGS=true"
  ],
  homeLinks: () => ['        <a className="button" href="/ratings-reviews">Ratings &amp; Reviews</a>'],
  navLinks: () => [{ href: "/ratings-reviews", label: "Ratings & Reviews" }]
};
