// scripture-sermon-tools — a personal scripture/reference library (save + tag +
// search verses) plus AI-assisted talk/sermon preparation. Ported from
// ChurchConnect's real system:
//   - backend/routes/scripture_library.py — the personal library / favorites model
//     (reference, verse_text, translation, living/real-life translation, notes,
//     tags, categories) with save/update/remove + list-with-derived-facets, and
//     the /api/scripture/log-view history + save-personal collection.
//   - backend/routes/scripture_search.py — the smart-search result shape
//     (reference, verse_text, living_translation, topics, application,
//     heart_message) and the auto-detect (reference / topic / question) search.
//   - backend/routes/sermon_prep.py — the sermon-preparation record (title,
//     passage, sermon_type, series_name/position, estimated_duration, outline
//     sections, scriptures, research_notes, manuscript, delivery_notes, status,
//     tags), the 7 built-in outline templates (expository/topical/narrative/
//     evangelistic/teaching/pastoral/apologetic), and the AI helpers
//     suggest-scriptures / suggest-points / teaching-insights.
//   - backend/routes/__init__.py get_ai_response/get_ai_json_response — the
//     "AI service not configured" degrade path when no key is set (ported here as
//     an optional owner key that the UI never blocks on).
// Generalized off the church framing into plain "talks/messages" copy so it drops
// into any app. Runs on the app owner's own database with graceful sample-data
// fallback, feature-flagged (FEATURE_SCRIPTURE); customers save verses + prep
// their own talks (rows scoped to user.id), admins can see all prep.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/scripture.ts (model + queries, ported from the real sources) --

function scriptureLibFile(): GeneratedModuleFile {
  return file("src/lib/db/scripture.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A saved reference, ported from scripture_library.py toggle_favorite +",
    "// save_to_personal_library: a reference, its verse text, a translation label, a",
    "// plain-language 'living translation', free-form notes, and tags/categories for",
    "// filing. Scoped to the person who saved it (ownerId).",
    "export type SavedReference = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  reference: string;",
    "  verseText: string;",
    "  translation: string;",
    "  livingTranslation: string;",
    "  notes: string;",
    "  tags: string[];",
    "  categories: string[];",
    "  createdAt: string;",
    "  updatedAt: string;",
    "};",
    "",
    "export type SavedFilters = { ownerId?: string; category?: string; tag?: string; search?: string; limit?: number };",
    "",
    "// The sermon/talk types, ported verbatim from sermon_prep.py create_sermon +",
    "// the built-in template ids (used to pick a starting outline).",
    "export const TALK_TYPES = [",
    '  "expository",',
    '  "topical",',
    '  "narrative",',
    '  "evangelistic",',
    '  "teaching",',
    '  "pastoral",',
    '  "apologetic"',
    "];",
    "",
    "// The lifecycle status, ported from sermon_prep.py (default 'idea').",
    "export const TALK_STATUSES = [\"idea\", \"researching\", \"outlining\", \"drafting\", \"ready\", \"delivered\"];",
    "",
    "export type OutlineSection = { id: string; title: string; content: string; order: number };",
    "",
    "// The 7 built-in outline templates, ported verbatim from sermon_prep.py",
    "// list_templates builtin_templates (generalized wording kept faithful).",
    "export type OutlineTemplate = { id: string; name: string; description: string; outline: { title: string; content: string }[] };",
    "",
    "export const BUILTIN_TEMPLATES: OutlineTemplate[] = [",
    "  {",
    '    id: "template-expository",',
    '    name: "Expository",',
    '    description: "Verse-by-verse walk through a passage with detailed exegesis.",',
    "    outline: [",
    '      { title: "Introduction", content: "Hook the audience, introduce the passage and its context" },',
    '      { title: "Historical/Cultural Background", content: "Set the scene for the original audience" },',
    '      { title: "Verse-by-Verse Analysis", content: "Walk through the text methodically" },',
    '      { title: "Core Truths", content: "What does this passage teach?" },',
    '      { title: "Practical Application", content: "How do we live this out today?" },',
    '      { title: "Conclusion & Call to Action", content: "Summarize and challenge" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-topical",',
    '    name: "Topical",',
    '    description: "Address a specific topic or theme.",',
    "    outline: [",
    '      { title: "Introduction", content: "Why this topic matters" },',
    '      { title: "Foundation", content: "What the text says" },',
    '      { title: "Point 1", content: "First key insight" },',
    '      { title: "Point 2", content: "Second key insight" },',
    '      { title: "Point 3", content: "Third key insight" },',
    '      { title: "Practical Steps", content: "How to apply" },',
    '      { title: "Conclusion", content: "Wrap up with hope" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-narrative",',
    '    name: "Narrative",',
    '    description: "Storytelling approach following a narrative arc.",',
    "    outline: [",
    '      { title: "Setting the Scene", content: "Describe the context and characters" },',
    '      { title: "Rising Action", content: "Build tension and conflict" },',
    '      { title: "Climax", content: "The turning point" },',
    '      { title: "Resolution", content: "How it works out" },',
    '      { title: "Contemporary Connection", content: "Our story in their story" },',
    '      { title: "Invitation", content: "How will you respond?" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-evangelistic",',
    '    name: "Evangelistic",',
    '    description: "A clear, welcoming message for newcomers.",',
    "    outline: [",
    '      { title: "Common Ground", content: "Start where they are" },',
    '      { title: "The Problem", content: "Name the real need" },',
    '      { title: "The Solution", content: "The heart of the message" },',
    '      { title: "The Response", content: "What is being asked" },',
    '      { title: "The Promise", content: "What changes" },',
    '      { title: "The Invitation", content: "A clear call to respond" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-teaching",',
    '    name: "Teaching",',
    '    description: "Concept-focused with clear explanations.",',
    "    outline: [",
    '      { title: "Introduction", content: "Why this matters" },',
    '      { title: "Definition", content: "What it is and isn\'t" },',
    '      { title: "Support", content: "Key passages" },',
    '      { title: "Context", content: "How this has been understood" },',
    '      { title: "Common Misconceptions", content: "Address errors" },',
    '      { title: "So What?", content: "Practical implications" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-pastoral",',
    '    name: "Pastoral",',
    '    description: "Addressing felt needs with compassion.",',
    "    outline: [",
    '      { title: "Acknowledgment", content: "Name the struggle" },',
    '      { title: "You Are Not Alone", content: "Examples that resonate" },',
    '      { title: "A Bigger Heart", content: "How this speaks to our pain" },',
    '      { title: "Promises", content: "Words for comfort" },',
    '      { title: "Practical Help", content: "Steps toward healing" },',
    '      { title: "Hope & Encouragement", content: "Looking forward" }',
    "    ]",
    "  },",
    "  {",
    '    id: "template-apologetic",',
    '    name: "Apologetic",',
    '    description: "Making a reasoned case with evidence.",',
    "    outline: [",
    '      { title: "The Challenge", content: "The objection or question" },',
    '      { title: "Why It Matters", content: "Real-world implications" },',
    '      { title: "The Evidence", content: "Historical, philosophical, practical" },',
    '      { title: "The Perspective", content: "What the text says" },',
    '      { title: "Answering Objections", content: "Common counter-arguments" },',
    '      { title: "Living Confidently", content: "From head to heart" }',
    "    ]",
    "  }",
    "];",
    "",
    "export function templateById(id: string): OutlineTemplate | null {",
    "  return BUILTIN_TEMPLATES.find((t) => t.id === id) || null;",
    "}",
    "",
    "// Turn a template's outline into numbered sections (ported from create_sermon's",
    "// default_outline shape: id/title/content/order).",
    "export function outlineFromTemplate(id: string): OutlineSection[] {",
    "  const template = templateById(id) || BUILTIN_TEMPLATES[1];",
    "  return template.outline.map((s, i) => ({",
    "    id: `s${i + 1}`,",
    "    title: s.title,",
    "    content: s.content,",
    "    order: i + 1",
    "  }));",
    "}",
    "",
    "const fallbackSaved: SavedReference[] = [",
    "  {",
    '    id: "sample-ref-1",',
    "    ownerId: null,",
    '    reference: "Philippians 4:6-7",',
    '    verseText: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests.",',
    '    translation: "NIV",',
    '    livingTranslation: "Do not let worry run the show. Bring what is weighing on you into the open, and a steadying calm can settle over you.",',
    '    notes: "Anchor verse for a talk on anxiety.",',
    '    tags: ["peace", "anxiety"],',
    '    categories: ["comfort"],',
    '    createdAt: "2025-01-01T00:00:00.000Z",',
    '    updatedAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-ref-2",',
    "    ownerId: null,",
    '    reference: "Proverbs 3:5-6",',
    '    verseText: "Trust with all your heart and lean not on your own understanding; in all your ways submit, and your paths will be made straight.",',
    '    translation: "NIV",',
    '    livingTranslation: "When the way forward is unclear, trust beyond what you can figure out on your own — the road tends to straighten as you go.",',
    '    notes: "",',
    '    tags: ["trust", "guidance"],',
    '    categories: ["direction"],',
    '    createdAt: "2025-02-01T00:00:00.000Z",',
    '    updatedAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function toStrings(v: unknown): string[] {",
    "  if (Array.isArray(v)) return v.map((x) => String(x)).filter(Boolean);",
    '  if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "  return [];",
    "}",
    "",
    "function rowToSaved(row: Record<string, unknown>): SavedReference {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    reference: String(row.reference || ""),',
    '    verseText: String(row.verse_text || ""),',
    '    translation: String(row.translation || "NIV"),',
    '    livingTranslation: String(row.living_translation || ""),',
    '    notes: String(row.notes || ""),',
    "    tags: toStrings(row.tags),",
    "    categories: toStrings(row.categories),",
    '    createdAt: row.created_at ? String(row.created_at) : "",',
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "// List a person's saved references, ported from scripture_library.py get_favorites:",
    "// filter by category/tag and a search across reference/text/notes, plus the derived",
    "// available-categories + available-tags facets; newest-updated first.",
    "export type SavedListing = { saved: SavedReference[]; availableCategories: string[]; availableTags: string[] };",
    "",
    "export async function listSaved(filters: SavedFilters = {}): Promise<SavedListing> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const search = (filters.search || "").trim().toLowerCase();',
    "  const ownerId = filters.ownerId;",
    "  const category = filters.category;",
    "  const tag = filters.tag;",
    "  const deriveFacets = (rows: SavedReference[]): { availableCategories: string[]; availableTags: string[] } => {",
    "    const cats = new Set<string>();",
    "    const tags = new Set<string>();",
    "    for (const r of rows) { r.categories.forEach((c) => cats.add(c)); r.tags.forEach((t) => tags.add(t)); }",
    "    return { availableCategories: Array.from(cats), availableTags: Array.from(tags) };",
    "  };",
    "  if (!hasDatabase()) {",
    "    const mine = fallbackSaved.filter((r) => !ownerId || r.ownerId === ownerId);",
    "    const facets = deriveFacets(mine);",
    "    const saved = mine",
    "      .filter((r) => !category || r.categories.includes(category))",
    "      .filter((r) => !tag || r.tags.includes(tag))",
    '      .filter((r) => !search || (r.reference + " " + r.verseText + " " + r.notes + " " + r.livingTranslation).toLowerCase().includes(search))',
    "      .slice(0, limit);",
    "    return { saved, ...facets };",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const cat = category || null;",
    "    const tg = tag || null;",
    "    const like = search ? `%${search}%` : null;",
    "    const rows = await sql`",
    "      select id, owner_id, reference, verse_text, translation, living_translation,",
    "        notes, tags, categories, created_at, updated_at",
    "      from scripture_sermon_tools_saved_references",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${cat}::text is null or categories ? ${cat})",
    "        and (${tg}::text is null or tags ? ${tg})",
    "        and (${like}::text is null",
    "          or lower(reference) like ${like}",
    "          or lower(verse_text) like ${like}",
    "          or lower(notes) like ${like})",
    "      order by updated_at desc",
    "      limit ${limit}",
    "    `;",
    "    const saved = rows.map(rowToSaved);",
    "    // Facets are derived across ALL the owner's rows, ported from get_favorites.",
    "    const allRows = await sql`",
    "      select tags, categories from scripture_sermon_tools_saved_references",
    "      where (${owner}::uuid is null or owner_id = ${owner})`;",
    "    const facets = deriveFacets(allRows.map(rowToSaved));",
    "    return { saved, ...facets };",
    "  } catch {",
    "    const facets = deriveFacets(fallbackSaved);",
    "    return { saved: fallbackSaved.slice(0, limit), ...facets };",
    "  }",
    "}",
    "",
    "export async function getSaved(id: string): Promise<SavedReference | null> {",
    "  if (!hasDatabase()) return fallbackSaved.find((r) => r.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, reference, verse_text, translation, living_translation,",
    "        notes, tags, categories, created_at, updated_at",
    "      from scripture_sermon_tools_saved_references where id = ${id} limit 1`;",
    "    return rows[0] ? rowToSaved(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SaveReferenceInput = {",
    "  ownerId: string | null;",
    "  reference: string;",
    "  verseText?: string;",
    "  translation?: string;",
    "  livingTranslation?: string;",
    "  notes?: string;",
    "  tags?: string[];",
    "  categories?: string[];",
    "};",
    "",
    "// Save (or update) a reference, ported from scripture_library.py toggle_favorite:",
    "// upsert on (owner_id, reference) so re-saving the same verse edits it in place.",
    "export async function saveReference(input: SaveReferenceInput): Promise<SavedReference | null> {",
    "  if (!hasDatabase()) return null;",
    '  const reference = (input.reference || "").trim();',
    "  if (!reference) return null;",
    "  const tags = JSON.stringify(input.tags || []);",
    "  const categories = JSON.stringify(input.categories || []);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into scripture_sermon_tools_saved_references (",
    "        owner_id, reference, verse_text, translation, living_translation, notes, tags, categories",
    "      ) values (",
    '        ${input.ownerId || null}, ${reference}, ${input.verseText || ""},',
    '        ${input.translation || "NIV"}, ${input.livingTranslation || ""},',
    '        ${input.notes || ""}, ${tags}, ${categories}',
    "      )",
    "      on conflict (owner_id, reference) do update set",
    "        verse_text = excluded.verse_text,",
    "        translation = excluded.translation,",
    "        living_translation = excluded.living_translation,",
    "        notes = excluded.notes,",
    "        tags = excluded.tags,",
    "        categories = excluded.categories,",
    "        updated_at = now()",
    "      returning id, owner_id, reference, verse_text, translation, living_translation,",
    "        notes, tags, categories, created_at, updated_at`;",
    "    return rows[0] ? rowToSaved(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Remove a saved reference, ported from toggle_favorite's remove path. Scoped to",
    "// the owner so no one can delete someone else's library.",
    "export async function removeSaved(id: string, ownerId: string | null): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    if (ownerId) {",
    "      await sql`delete from scripture_sermon_tools_saved_references where id = ${id} and owner_id = ${ownerId}`;",
    "    } else {",
    "      await sql`delete from scripture_sermon_tools_saved_references where id = ${id}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Talks / sermon preparation (ported from sermon_prep.py) --------------",
    "",
    "export type Talk = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  title: string;",
    "  passage: string;",
    "  talkType: string;",
    "  seriesName: string;",
    "  seriesPosition: number | null;",
    "  estimatedDuration: number;",
    "  outline: OutlineSection[];",
    "  scriptures: string[];",
    "  researchNotes: string;",
    "  manuscript: string;",
    "  deliveryNotes: string;",
    "  status: string;",
    "  tags: string[];",
    "  createdAt: string;",
    "  updatedAt: string;",
    "};",
    "",
    "export type TalkFilters = { ownerId?: string; status?: string; search?: string; limit?: number };",
    "",
    "const fallbackTalks: Talk[] = [",
    "  {",
    '    id: "sample-talk-1",',
    "    ownerId: null,",
    '    title: "Peace that outlasts the storm",',
    '    passage: "Philippians 4:6-7",',
    '    talkType: "topical",',
    "    seriesName: \"\",",
    "    seriesPosition: null,",
    "    estimatedDuration: 30,",
    '    outline: outlineFromTemplate("template-topical"),',
    '    scriptures: ["Philippians 4:6-7", "Matthew 6:34"],',
    '    researchNotes: "Focus on the difference between avoiding worry and handing it off.",',
    '    manuscript: "",',
    '    deliveryNotes: "",',
    '    status: "outlining",',
    '    tags: ["peace", "anxiety"],',
    '    createdAt: "2025-01-05T00:00:00.000Z",',
    '    updatedAt: "2025-01-06T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToTalk(row: Record<string, unknown>): Talk {",
    "  const toOutline = (v: unknown): OutlineSection[] => {",
    "    const parse = (arr: unknown[]): OutlineSection[] => arr.map((raw, i) => {",
    "      const s = (raw && typeof raw === \"object\") ? (raw as Record<string, unknown>) : {};",
    "      return {",
    "        id: s.id ? String(s.id) : `s${i + 1}`,",
    '        title: String(s.title || ""),',
    '        content: String(s.content || ""),',
    "        order: Number(s.order || i + 1)",
    "      };",
    "    });",
    "    if (Array.isArray(v)) return parse(v);",
    '    if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? parse(p) : []; } catch { return []; } }',
    "    return [];",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    title: String(row.title || "Untitled talk"),',
    '    passage: String(row.passage || ""),',
    '    talkType: String(row.talk_type || "topical"),',
    '    seriesName: String(row.series_name || ""),',
    "    seriesPosition: row.series_position != null ? Number(row.series_position) : null,",
    "    estimatedDuration: Number(row.estimated_duration || 30),",
    "    outline: toOutline(row.outline),",
    "    scriptures: toStrings(row.scriptures),",
    '    researchNotes: String(row.research_notes || ""),',
    '    manuscript: String(row.manuscript || ""),',
    '    deliveryNotes: String(row.delivery_notes || ""),',
    '    status: String(row.status || "idea"),',
    "    tags: toStrings(row.tags),",
    '    createdAt: row.created_at ? String(row.created_at) : "",',
    '    updatedAt: row.updated_at ? String(row.updated_at) : ""',
    "  };",
    "}",
    "",
    "// List a person's talks, ported from sermon_prep.py list_sermons (filter by status,",
    "// newest-first), scoped to the owner and with a title/passage search added.",
    "export async function listTalks(filters: TalkFilters = {}): Promise<Talk[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    "  const ownerId = filters.ownerId;",
    '  const status = (filters.status || "").trim();',
    '  const search = (filters.search || "").trim().toLowerCase();',
    "  if (!hasDatabase()) {",
    "    return fallbackTalks",
    "      .filter((t) => !ownerId || t.ownerId === ownerId)",
    '      .filter((t) => !status || status === "all" || t.status === status)',
    '      .filter((t) => !search || (t.title + " " + t.passage).toLowerCase().includes(search))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    '    const st = status && status !== "all" ? status : null;',
    "    const like = search ? `%${search}%` : null;",
    "    const rows = await sql`",
    "      select id, owner_id, title, passage, talk_type, series_name, series_position,",
    "        estimated_duration, outline, scriptures, research_notes, manuscript,",
    "        delivery_notes, status, tags, created_at, updated_at",
    "      from scripture_sermon_tools_talks",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${st}::text is null or status = ${st})",
    "        and (${like}::text is null or lower(title) like ${like} or lower(passage) like ${like})",
    "      order by updated_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToTalk);",
    "  } catch {",
    "    return fallbackTalks.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getTalk(id: string): Promise<Talk | null> {",
    "  if (!hasDatabase()) return fallbackTalks.find((t) => t.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, title, passage, talk_type, series_name, series_position,",
    "        estimated_duration, outline, scriptures, research_notes, manuscript,",
    "        delivery_notes, status, tags, created_at, updated_at",
    "      from scripture_sermon_tools_talks where id = ${id} limit 1`;",
    "    return rows[0] ? rowToTalk(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateTalkInput = {",
    "  ownerId: string | null;",
    "  title: string;",
    "  passage?: string;",
    "  talkType?: string;",
    "  templateId?: string;",
    "  seriesName?: string;",
    "  estimatedDuration?: number;",
    "  scriptures?: string[];",
    "};",
    "",
    "// Create a talk, ported from sermon_prep.py create_sermon: it seeds a default",
    "// outline (from the chosen template) and starts life as an 'idea'.",
    "export async function createTalk(input: CreateTalkInput): Promise<Talk | null> {",
    "  if (!hasDatabase()) return null;",
    '  const talkType = TALK_TYPES.includes(input.talkType || "") ? String(input.talkType) : "topical";',
    "  const templateId = input.templateId || `template-${talkType}`;",
    "  const outline = JSON.stringify(outlineFromTemplate(templateId));",
    "  const scriptures = JSON.stringify(input.scriptures || []);",
    "  const duration = Math.min(240, Math.max(1, input.estimatedDuration || 30));",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into scripture_sermon_tools_talks (",
    "        owner_id, title, passage, talk_type, series_name, estimated_duration,",
    "        outline, scriptures, status",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.title}, ${input.passage || ""}, ${talkType},',
    '        ${input.seriesName || ""}, ${duration}, ${outline}, ${scriptures}, ${"idea"}',
    "      )",
    "      returning id, owner_id, title, passage, talk_type, series_name, series_position,",
    "        estimated_duration, outline, scriptures, research_notes, manuscript,",
    "        delivery_notes, status, tags, created_at, updated_at`;",
    "    return rows[0] ? rowToTalk(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type UpdateTalkInput = {",
    "  title?: string;",
    "  passage?: string;",
    "  talkType?: string;",
    "  seriesName?: string;",
    "  seriesPosition?: number | null;",
    "  estimatedDuration?: number;",
    "  outline?: OutlineSection[];",
    "  scriptures?: string[];",
    "  researchNotes?: string;",
    "  manuscript?: string;",
    "  deliveryNotes?: string;",
    "  status?: string;",
    "  tags?: string[];",
    "};",
    "",
    "// Update a talk, ported from sermon_prep.py update_sermon's allowed-fields set.",
    "// Only whitelisted columns are touched; every value is parameterized.",
    "export async function updateTalk(id: string, ownerId: string | null, input: UpdateTalkInput): Promise<Talk | null> {",
    "  if (!hasDatabase()) return null;",
    "  const sets: string[] = [];",
    "  const values: unknown[] = [];",
    "  const add = (column: string, value: unknown) => { values.push(value); sets.push(`${column} = $${values.length}`); };",
    '  if (input.title !== undefined) add("title", String(input.title));',
    '  if (input.passage !== undefined) add("passage", String(input.passage));',
    '  if (input.talkType !== undefined && TALK_TYPES.includes(input.talkType)) add("talk_type", input.talkType);',
    '  if (input.seriesName !== undefined) add("series_name", String(input.seriesName));',
    '  if (input.seriesPosition !== undefined) add("series_position", input.seriesPosition);',
    '  if (input.estimatedDuration !== undefined) add("estimated_duration", Math.min(240, Math.max(1, input.estimatedDuration)));',
    '  if (input.outline !== undefined) add("outline", JSON.stringify(input.outline));',
    '  if (input.scriptures !== undefined) add("scriptures", JSON.stringify(input.scriptures));',
    '  if (input.researchNotes !== undefined) add("research_notes", String(input.researchNotes));',
    '  if (input.manuscript !== undefined) add("manuscript", String(input.manuscript));',
    '  if (input.deliveryNotes !== undefined) add("delivery_notes", String(input.deliveryNotes));',
    '  if (input.status !== undefined && TALK_STATUSES.includes(input.status)) add("status", input.status);',
    '  if (input.tags !== undefined) add("tags", JSON.stringify(input.tags));',
    "  if (sets.length === 0) return getTalk(id);",
    "  try {",
    "    const sql = getDatabase();",
    "    // Column names in `sets` are whitelisted literals above; only $-parameters",
    "    // carry values. The id (and optional owner scope) are the final parameters.",
    "    values.push(id);",
    "    const idParam = `$${values.length}`;",
    "    let ownerClause = \"\";",
    "    if (ownerId) { values.push(ownerId); ownerClause = ` and owner_id = $${values.length}`; }",
    "    const text = `update scripture_sermon_tools_talks set ${sets.join(\", \")}, updated_at = now()` +",
    "      ` where id = ${idParam}${ownerClause}` +",
    "      ` returning id, owner_id, title, passage, talk_type, series_name, series_position,` +",
    "      ` estimated_duration, outline, scriptures, research_notes, manuscript,` +",
    "      ` delivery_notes, status, tags, created_at, updated_at`;",
    "    const rows = await sql.query(text, values);",
    "    return rows[0] ? rowToTalk(rows[0] as Record<string, unknown>) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Delete a talk, ported from sermon_prep.py delete_sermon, scoped to the owner.",
    "export async function deleteTalk(id: string, ownerId: string | null): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    if (ownerId) {",
    "      await sql`delete from scripture_sermon_tools_talks where id = ${id} and owner_id = ${ownerId}`;",
    "    } else {",
    "      await sql`delete from scripture_sermon_tools_talks where id = ${id}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function scriptureEnabled(): boolean {",
    '  return process.env.FEATURE_SCRIPTURE !== "false";',
    "}",
    "",
    "// The owner's own AI key is optional. Without it, the AI-assist endpoints degrade",
    "// gracefully (ported from get_ai_response's 'AI service not configured' path) —",
    "// they return a clearly-labelled starter draft instead of blocking the UI.",
    "export function aiConfigured(): boolean {",
    "  return Boolean((process.env.SCRIPTURE_AI_API_KEY || \"\").trim());",
    "}"
  ]);
}

// ---- src/lib/scripture/ai.ts (AI-assist, ported from sermon_prep.py) --------

function scriptureAiFile(): GeneratedModuleFile {
  return file("src/lib/scripture/ai.ts", [
    'import { aiConfigured } from "@/lib/db/scripture";',
    "",
    "// AI-assisted preparation, ported from sermon_prep.py suggest_scriptures /",
    "// suggest_points / teaching_insights. Runs on the app owner's OWN AI key; when",
    "// no key is set it returns a graceful, clearly-labelled starter (never blocks).",
    "",
    "export type ScriptureSuggestion = { reference: string; summary: string };",
    "export type PointSuggestion = { title: string; description: string; keyScripture: string };",
    "",
    "const ANTHROPIC_URL = \"https://api.anthropic.com/v1/messages\";",
    "",
    "// Ask the owner's model for JSON and parse it resiliently, ported from",
    "// get_ai_json_response (strip code fences, then slice first { to last }).",
    "async function askJson(system: string, user: string): Promise<Record<string, unknown> | null> {",
    '  const key = (process.env.SCRIPTURE_AI_API_KEY || "").trim();',
    "  if (!key) return null;",
    '  const model = (process.env.SCRIPTURE_AI_MODEL || "claude-3-5-haiku-latest").trim();',
    "  try {",
    "    const response = await fetch(ANTHROPIC_URL, {",
    '      method: "POST",',
    "      headers: {",
    '        "content-type": "application/json",',
    '        "x-api-key": key,',
    '        "anthropic-version": "2023-06-01"',
    "      },",
    "      body: JSON.stringify({",
    "        model,",
    "        max_tokens: 1500,",
    "        system,",
    '        messages: [{ role: "user", content: user }]',
    "      })",
    "    });",
    "    if (!response.ok) return null;",
    "    const data = (await response.json()) as { content?: Array<{ text?: string }> };",
    '    const text = (data.content || []).map((c) => c.text || "").join("").trim();',
    "    if (!text) return null;",
    "    const candidates: string[] = [];",
    '    if (text.includes("```json")) { try { candidates.push(text.split("```json", 2)[1].split("```", 1)[0].trim()); } catch { /* ignore */ } }',
    '    if (text.includes("```")) { try { candidates.push(text.split("```", 2)[1].split("```", 1)[0].trim()); } catch { /* ignore */ } }',
    "    candidates.push(text);",
    '    const first = text.indexOf("{");',
    '    const last = text.lastIndexOf("}");',
    "    if (first !== -1 && last > first) candidates.push(text.slice(first, last + 1));",
    "    for (const candidate of candidates) {",
    "      try { const parsed = JSON.parse(candidate); if (parsed && typeof parsed === \"object\") return parsed as Record<string, unknown>; } catch { /* try next */ }",
    "    }",
    "    return null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// suggest_scriptures — supporting (and optionally contrasting) references for a",
    "// topic. Ported verbatim from sermon_prep.py's system prompt + return shape.",
    "export async function suggestScriptures(topic: string, includeOpposing = false): Promise<{ supporting: ScriptureSuggestion[]; opposing: ScriptureSuggestion[]; live: boolean }> {",
    "  const system = [",
    '    "You are a scripture and talk-preparation assistant. Given a topic, suggest relevant references.",',
    '    "Return ONLY JSON: {\\"supporting\\":[{\\"reference\\":\\"John 3:16\\",\\"summary\\":\\"...\\"}],\\"opposing\\":[{\\"reference\\":\\"Luke 12:51\\",\\"summary\\":\\"...\\"}]}.",',
    '    "Provide 5-8 supporting. If contrasting references are requested provide 3-5, else an empty opposing array.",',
    '    "Use standard reference format (e.g. 1 Corinthians 13:4-7). Keep each summary to one sentence."',
    '  ].join("\\n");',
    "  const user = `Topic: \"${topic}\"\\nInclude contrasting references: ${includeOpposing ? \"Yes\" : \"No\"}`;",
    "  const parsed = await askJson(system, user);",
    "  const toList = (v: unknown): ScriptureSuggestion[] =>",
    "    Array.isArray(v)",
    "      ? v.map((raw) => {",
    "          const r = (raw && typeof raw === \"object\") ? (raw as Record<string, unknown>) : {};",
    '          return { reference: String(r.reference || ""), summary: String(r.summary || "") };',
    "        }).filter((s) => s.reference)",
    "      : [];",
    "  if (!parsed) {",
    "    // Graceful starter when no owner key is set — clearly not an AI answer.",
    "    return {",
    "      supporting: [",
    '        { reference: "", summary: `Add an AI key to auto-suggest references for \"${topic}\". Until then, add references you know by hand.` }',
    "      ].filter((s) => s.reference || !aiConfigured()),",
    "      opposing: [],",
    "      live: false",
    "    };",
    "  }",
    "  return { supporting: toList(parsed.supporting), opposing: includeOpposing ? toList(parsed.opposing) : [], live: true };",
    "}",
    "",
    "// suggest_points — an outline of main points from a title + references, ported",
    "// from sermon_prep.py suggest_sermon_points.",
    "export async function suggestPoints(title: string, talkType: string, scriptures: string[]): Promise<{ points: PointSuggestion[]; live: boolean }> {",
    '  const scriptureList = scriptures.length ? scriptures.map((s) => `- ${s}`).join("\\n") : "No specific references provided";',
    "  const system = [",
    '    "You are a talk-preparation expert. Given a title, type, and references, suggest a compelling outline.",',
    '    "Return ONLY JSON: {\\"points\\":[{\\"title\\":\\"...\\",\\"description\\":\\"...\\",\\"key_scripture\\":\\"...\\"}]}.",',
    '    "Provide 3-5 main points that build on each other, memorable and practical, with a strong opening and closing application."',
    '  ].join("\\n");',
    "  const user = `Title: \"${title}\"\\nType: ${talkType}\\nReferences:\\n${scriptureList}`;",
    "  const parsed = await askJson(system, user);",
    "  if (!parsed || !Array.isArray(parsed.points)) {",
    "    return { points: [], live: false };",
    "  }",
    "  const points = (parsed.points as unknown[]).map((raw) => {",
    "    const p = (raw && typeof raw === \"object\") ? (raw as Record<string, unknown>) : {};",
    '    return { title: String(p.title || ""), description: String(p.description || ""), keyScripture: String(p.key_scripture || p.keyScripture || "") };',
    "  }).filter((p) => p.title);",
    "  return { points, live: true };",
    "}",
    "",
    "// teaching_insights — simplify / cross_reference / application for a passage,",
    "// ported from sermon_prep.py get_teaching_insights (the three insight types).",
    "export type InsightType = \"simplify\" | \"cross_reference\" | \"application\";",
    "",
    "export async function teachingInsights(scriptureRef: string, scriptureText: string, insightType: InsightType): Promise<{ insights: Record<string, unknown> | null; live: boolean }> {",
    "  const systems: Record<InsightType, string> = {",
    '    simplify: "You help explain complex ideas plainly. Return ONLY JSON with keys simplified_explanation (string), key_concepts (array of {term,explanation}), historical_context (string), analogy (string), teaching_tip (string). Avoid jargon; keep it accurate.",',
    '    cross_reference: "You surface how a passage connects across the text. Return ONLY JSON with keys connections (array of {from,to,how_used,significance}), related_passages (array of {reference,connection}), preaching_insight (string).",',
    '    application: "You turn a passage into practical, specific applications. Return ONLY JSON with keys main_truth (string), applications (array of {audience,situation,action,encouragement}), discussion_questions (array of strings), closing_challenge (string)."',
    "  };",
    '  const user = `Reference: ${scriptureRef}${scriptureText ? `\\nText: \"${scriptureText}\"` : ""}\\nProduce ${insightType} insights.`;',
    "  const parsed = await askJson(systems[insightType], user);",
    "  return { insights: parsed, live: Boolean(parsed) };",
    "}"
  ]);
}

// ---- src/app/api/scripture/library/route.ts (list + save) -------------------

function libraryApiFile(): GeneratedModuleFile {
  return file("src/app/api/scripture/library/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listSaved, saveReference, scriptureEnabled } from "@/lib/db/scripture";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// List the signed-in person's saved references, ported from get_favorites",
    "// (category/tag/search filters + derived facets). Always scoped to the owner.",
    "export async function GET(request: Request) {",
    '  if (!scriptureEnabled()) return NextResponse.json({ ok: false, message: "Scripture tools are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const listing = await listSaved({",
    "    ownerId: user?.id ? String(user.id) : undefined,",
    '    category: url.searchParams.get("category") || undefined,',
    '    tag: url.searchParams.get("tag") || undefined,',
    '    search: url.searchParams.get("q") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, ...listing });",
    "}",
    "",
    "// Save (or update) a reference, ported from toggle_favorite. Scoped to user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to save references." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const reference = typeof body.reference === "string" ? body.reference.trim() : "";',
    "  if (reference.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "A reference is required." }, { status: 400 });',
    "  }",
    "  const tags = Array.isArray(body.tags) ? body.tags.map((t) => String(t).trim()).filter(Boolean) : [];",
    "  const categories = Array.isArray(body.categories) ? body.categories.map((c) => String(c).trim()).filter(Boolean) : [];",
    "  const saved = await saveReference({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    reference,",
    '    verseText: typeof body.verseText === "string" ? body.verseText : undefined,',
    '    translation: typeof body.translation === "string" ? body.translation : undefined,',
    '    livingTranslation: typeof body.livingTranslation === "string" ? body.livingTranslation : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined,',
    "    tags,",
    "    categories",
    "  });",
    '  if (!saved) return NextResponse.json({ ok: false, message: "Connect a database to save references." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, saved });",
    "}"
  ]);
}

// ---- src/app/api/scripture/library/[id]/route.ts (remove) -------------------

function libraryDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/scripture/library/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getSaved, removeSaved, scriptureEnabled } from "@/lib/db/scripture";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Remove a saved reference, ported from toggle_favorite's remove path. Owners",
    "// may only delete their own rows.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!scriptureEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const existing = await getSaved(id);",
    "  const ownerId = user?.id ? String(user.id) : null;",
    "  if (existing && existing.ownerId && existing.ownerId !== ownerId) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const ok = await removeSaved(id, ownerId);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to manage your library." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/scripture/talks/route.ts (list + create) -------------------

function talksApiFile(): GeneratedModuleFile {
  return file("src/app/api/scripture/talks/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listTalks, createTalk, scriptureEnabled } from "@/lib/db/scripture";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// List talks, ported from list_sermons (status filter, newest first). Customers",
    "// see only their own; admins see every talk.",
    "export async function GET(request: Request) {",
    '  if (!scriptureEnabled()) return NextResponse.json({ ok: false, message: "Scripture tools are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const talks = await listTalks({",
    "    ownerId,",
    '    status: url.searchParams.get("status") || undefined,',
    '    search: url.searchParams.get("q") || undefined',
    "  });",
    "  return NextResponse.json({ ok: true, talks });",
    "}",
    "",
    "// Create a talk, ported from create_sermon (seeds an outline from a template).",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to start a talk." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    "  if (title.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give your talk a title." }, { status: 400 });',
    "  }",
    "  const scriptures = Array.isArray(body.scriptures) ? body.scriptures.map((s) => String(s).trim()).filter(Boolean) : [];",
    "  const created = await createTalk({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    title,",
    '    passage: typeof body.passage === "string" ? body.passage : undefined,',
    '    talkType: typeof body.talkType === "string" ? body.talkType : undefined,',
    '    templateId: typeof body.templateId === "string" ? body.templateId : undefined,',
    '    seriesName: typeof body.seriesName === "string" ? body.seriesName : undefined,',
    '    estimatedDuration: typeof body.estimatedDuration === "number" ? body.estimatedDuration : undefined,',
    "    scriptures",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save talks." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, talk: created });",
    "}"
  ]);
}

// ---- src/app/api/scripture/talks/[id]/route.ts (detail + update + delete) ---

function talkDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/scripture/talks/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getTalk, updateTalk, deleteTalk, scriptureEnabled } from "@/lib/db/scripture";',
    'import type { OutlineSection } from "@/lib/db/scripture";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "function canTouch(talk: { ownerId: string | null }, userId: string | null, isAdmin: boolean): boolean {",
    "  if (isAdmin) return true;",
    "  return !talk.ownerId || talk.ownerId === userId;",
    "}",
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!scriptureEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const talk = await getTalk(id);",
    '  if (!talk) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  if (!canTouch(talk, user?.id ? String(user.id) : null, canAccessAdmin(user?.role))) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, talk });",
    "}",
    "",
    "// Update a talk, ported from update_sermon. Owner (or admin) only.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const talk = await getTalk(id);",
    '  if (!talk) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const userId = user?.id ? String(user.id) : null;",
    "  if (!canTouch(talk, userId, isAdmin)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const outline = Array.isArray(body.outline)",
    "    ? (body.outline as unknown[]).map((raw, i) => {",
    "        const s = (raw && typeof raw === \"object\") ? (raw as Record<string, unknown>) : {};",
    "        return { id: s.id ? String(s.id) : `s${i + 1}`, title: String(s.title || \"\"), content: String(s.content || \"\"), order: Number(s.order || i + 1) } as OutlineSection;",
    "      })",
    "    : undefined;",
    "  const scriptures = Array.isArray(body.scriptures) ? body.scriptures.map((s) => String(s).trim()).filter(Boolean) : undefined;",
    "  const tags = Array.isArray(body.tags) ? body.tags.map((t) => String(t).trim()).filter(Boolean) : undefined;",
    "  // The owner scope is enforced in the query; admins pass null owner to bypass it.",
    "  const scopeOwner = isAdmin ? null : userId;",
    "  const updated = await updateTalk(id, scopeOwner, {",
    '    title: typeof body.title === "string" ? body.title : undefined,',
    '    passage: typeof body.passage === "string" ? body.passage : undefined,',
    '    talkType: typeof body.talkType === "string" ? body.talkType : undefined,',
    '    seriesName: typeof body.seriesName === "string" ? body.seriesName : undefined,',
    '    estimatedDuration: typeof body.estimatedDuration === "number" ? body.estimatedDuration : undefined,',
    "    outline,",
    "    scriptures,",
    '    researchNotes: typeof body.researchNotes === "string" ? body.researchNotes : undefined,',
    '    manuscript: typeof body.manuscript === "string" ? body.manuscript : undefined,',
    '    deliveryNotes: typeof body.deliveryNotes === "string" ? body.deliveryNotes : undefined,',
    '    status: typeof body.status === "string" ? body.status : undefined,',
    "    tags",
    "  });",
    '  if (!updated) return NextResponse.json({ ok: false, message: "Connect a database to update talks." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, talk: updated });",
    "}",
    "",
    "// Delete a talk, ported from delete_sermon. Owner (or admin) only.",
    "export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const talk = await getTalk(id);",
    '  if (!talk) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const userId = user?.id ? String(user.id) : null;",
    "  if (!canTouch(talk, userId, isAdmin)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const ok = await deleteTalk(id, isAdmin ? null : userId);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to delete talks." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/scripture/assist/route.ts (AI-assist) ----------------------

function assistApiFile(): GeneratedModuleFile {
  return file("src/app/api/scripture/assist/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { scriptureEnabled, aiConfigured } from "@/lib/db/scripture";',
    'import { suggestScriptures, suggestPoints, teachingInsights } from "@/lib/scripture/ai";',
    'import type { InsightType } from "@/lib/scripture/ai";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// AI-assisted preparation, ported from sermon_prep.py suggest_scriptures /",
    "// suggest_points / teaching_insights. Runs on the app owner's own key and",
    "// degrades gracefully when unset (never a hard error to the user).",
    "export async function POST(request: Request) {",
    '  if (!scriptureEnabled()) return NextResponse.json({ ok: false, message: "Scripture tools are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const kind = typeof body.kind === "string" ? body.kind : "scriptures";',
    "  if (!aiConfigured()) {",
    "    // Ported from get_ai_response's 'AI service not configured' path — surfaced as",
    "    // a soft, actionable message rather than a 500.",
    '    return NextResponse.json({ ok: true, live: false, message: "Add your AI key to enable suggestions. You can still prepare everything by hand." });',
    "  }",
    '  if (kind === "points") {',
    '    const title = typeof body.title === "string" ? body.title.trim() : "";',
    '    if (!title) return NextResponse.json({ ok: false, message: "A title is required." }, { status: 400 });',
    '    const talkType = typeof body.talkType === "string" ? body.talkType : "topical";',
    "    const scriptures = Array.isArray(body.scriptures) ? body.scriptures.map((s) => String(s)) : [];",
    "    const result = await suggestPoints(title, talkType, scriptures);",
    "    return NextResponse.json({ ok: true, ...result });",
    "  }",
    '  if (kind === "insights") {',
    '    const scriptureRef = typeof body.scriptureRef === "string" ? body.scriptureRef.trim() : "";',
    '    if (!scriptureRef) return NextResponse.json({ ok: false, message: "A reference is required." }, { status: 400 });',
    '    const scriptureText = typeof body.scriptureText === "string" ? body.scriptureText : "";',
    '    const insightType = (["simplify", "cross_reference", "application"].includes(String(body.insightType)) ? body.insightType : "simplify") as InsightType;',
    "    const result = await teachingInsights(scriptureRef, scriptureText, insightType);",
    "    return NextResponse.json({ ok: true, ...result });",
    "  }",
    "  // default: scripture suggestions",
    '  const topic = typeof body.topic === "string" ? body.topic.trim() : "";',
    '  if (!topic) return NextResponse.json({ ok: false, message: "A topic is required." }, { status: 400 });',
    "  const result = await suggestScriptures(topic, body.includeOpposing === true);",
    "  return NextResponse.json({ ok: true, ...result });",
    "}"
  ]);
}

// ---- src/app/scripture/page.tsx (library + search + save) -------------------

function scripturePageFile(): GeneratedModuleFile {
  return file("src/app/scripture/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { listSaved, scriptureEnabled } from "@/lib/db/scripture";',
    'import { SaveReferenceForm } from "./save-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function ScripturePage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; category?: string; tag?: string }>;",
    "}) {",
    "  if (!scriptureEnabled()) {",
    '    return (<main className="shell"><h1>Scripture library</h1><p>Scripture tools are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scripture");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const category = (params?.category || "").trim();',
    '  const tag = (params?.tag || "").trim();',
    "  const { saved, availableCategories, availableTags } = await listSaved({",
    "    ownerId: user?.id ? String(user.id) : undefined,",
    "    search: q || undefined,",
    "    category: category || undefined,",
    "    tag: tag || undefined",
    "  });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Scripture</p>',
    "      <h1>Your reference library</h1>",
    "      <p>Save the references that matter, add a plain-language note, and tag them so they are ready when you sit down to prepare a talk.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search your references" aria-label="Search references" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {(availableCategories.length > 0 || availableTags.length > 0) ? (",
    '        <p className="note">',
    '          {availableCategories.map((c) => (<Link key={c} className="link" href={`/scripture?category=${encodeURIComponent(c)}`}>{c}</Link>))}',
    '          {availableTags.map((t) => (<Link key={t} className="link" href={`/scripture?tag=${encodeURIComponent(t)}`}>#{t}</Link>))}',
    "        </p>",
    "      ) : null}",
    "      {saved.length === 0 ? (",
    '        <p className="note">{q ? `Nothing saved matches "${q}" yet.` : "No saved references yet. Add your first one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {saved.map((r) => (",
    '            <article className="wide-card" key={r.id}>',
    "              <span>{r.translation}</span>",
    "              <strong>{r.reference}</strong>",
    "              {r.verseText ? <p>{r.verseText}</p> : null}",
    '              {r.livingTranslation ? <p className="note">In plain words: {r.livingTranslation}</p> : null}',
    "              {r.notes ? <p>{r.notes}</p> : null}",
    '              {(r.tags.length > 0 || r.categories.length > 0) ? (',
    '                <p className="note">{[...r.categories, ...r.tags.map((t) => `#${t}`)].join(" · ")}</p>',
    "              ) : null}",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Save a reference</h2>",
    "      <SaveReferenceForm />",
    '      <p><Link className="button" href="/scripture/talks">Talk & sermon prep</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scripture/save-form.tsx (client) -------------------------------

function saveFormFile(): GeneratedModuleFile {
  return file("src/app/scripture/save-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Save a reference to the personal library, ported from ScriptureLibrary.tsx +",
    "// toggle_favorite: reference, verse text, translation, a plain-language note, and",
    "// comma-separated tags/categories.",
    "export function SaveReferenceForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    '    const splitList = (v: FormDataEntryValue | null) => String(v || "").split(",").map((x) => x.trim()).filter(Boolean);',
    "    try {",
    '      const response = await fetch("/api/scripture/library", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          reference: form.get("reference"),',
    '          verseText: form.get("verseText"),',
    '          translation: form.get("translation"),',
    '          livingTranslation: form.get("livingTranslation"),',
    '          notes: form.get("notes"),',
    '          tags: splitList(form.get("tags")),',
    '          categories: splitList(form.get("categories"))',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Saved to your library.");',
    "      (event.target as HTMLFormElement).reset();",
    "      router.refresh();",
    '      setStatus("idle");',
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="reference" placeholder="Reference (e.g. Philippians 4:6-7)" aria-label="Reference" required />',
    '      <textarea className="input" name="verseText" rows={3} placeholder="The verse text" aria-label="Verse text" />',
    '      <input className="input" name="translation" placeholder="Translation (e.g. NIV)" aria-label="Translation" defaultValue="NIV" />',
    '      <textarea className="input" name="livingTranslation" rows={2} placeholder="Optional: say it in plain, everyday words" aria-label="Plain-language version" />',
    '      <textarea className="input" name="notes" rows={2} placeholder="Your notes" aria-label="Notes" />',
    '      <input className="input" name="categories" placeholder="Categories, comma-separated" aria-label="Categories" />',
    '      <input className="input" name="tags" placeholder="Tags, comma-separated" aria-label="Tags" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Save reference"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scripture/talks/page.tsx (talk list + new talk) ----------------

function talksPageFile(): GeneratedModuleFile {
  return file("src/app/scripture/talks/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listTalks, BUILTIN_TEMPLATES, scriptureEnabled } from "@/lib/db/scripture";',
    'import { NewTalkForm } from "./new-talk-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TalksPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; status?: string }>;",
    "}) {",
    "  if (!scriptureEnabled()) {",
    '    return (<main className="shell"><h1>Talk prep</h1><p>Scripture tools are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scripture/talks");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const status = (params?.status || "").trim();',
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = isAdmin ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const talks = await listTalks({ ownerId, status: status || undefined, search: q || undefined });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Preparation</p>',
    "      <h1>Talk &amp; sermon prep</h1>",
    "      <p>Start from a proven outline, gather your references, and build toward a manuscript. Pick a template and go.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search your talks" aria-label="Search talks" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {talks.length === 0 ? (",
    '        <p className="note">{q ? `No talks match "${q}" yet.` : "No talks yet. Start one below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {talks.map((t) => (",
    '            <Link className="wide-card" key={t.id} href={`/scripture/talks/${t.id}`}>',
    "              <span>{t.status}</span>",
    "              <strong>{t.title}</strong>",
    "              <p>{[t.passage, t.talkType].filter(Boolean).join(\" · \")}</p>",
    '              <p className="note">{t.outline.length} sections · ~{t.estimatedDuration} min</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Start a new talk</h2>",
    "      <NewTalkForm templates={BUILTIN_TEMPLATES.map((tpl) => ({ id: tpl.id, name: tpl.name, description: tpl.description }))} />",
    '      <p><Link className="button" href="/scripture">Back to library</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scripture/talks/new-talk-form.tsx (client) ---------------------

function newTalkFormFile(): GeneratedModuleFile {
  return file("src/app/scripture/talks/new-talk-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Start a new talk, ported from create_sermon: title, passage, and a template",
    "// pick (which seeds the starting outline).",
    "type TemplateOption = { id: string; name: string; description: string };",
    "",
    "export function NewTalkForm({ templates }: { templates: TemplateOption[] }) {",
    "  const router = useRouter();",
    '  const [templateId, setTemplateId] = useState(templates[0]?.id || "template-topical");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/scripture/talks", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          passage: form.get("passage"),',
    "          templateId,",
    '          talkType: templateId.replace("template-", "")',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not start the talk.");',
    "        return;",
    "      }",
    "      if (data.talk?.id) {",
    "        router.push(`/scripture/talks/${data.talk.id}`);",
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Title" aria-label="Talk title" required />',
    '      <input className="input" name="passage" placeholder="Main passage (optional)" aria-label="Main passage" />',
    '      <fieldset className="stack">',
    "        <legend>Choose a starting outline</legend>",
    "        {templates.map((tpl) => (",
    '          <label className="check" key={tpl.id}>',
    '            <input type="radio" name="template" checked={templateId === tpl.id} onChange={() => setTemplateId(tpl.id)} />{" "}',
    "            <strong>{tpl.name}</strong> — {tpl.description}",
    "          </label>",
    "        ))}",
    "      </fieldset>",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Creating…" : "Create talk"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scripture/talks/[id]/page.tsx (talk detail + editor + AI) ------

function talkDetailPageFile(): GeneratedModuleFile {
  return file("src/app/scripture/talks/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getTalk, aiConfigured, scriptureEnabled } from "@/lib/db/scripture";',
    'import { TalkEditor } from "./talk-editor";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TalkDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!scriptureEnabled()) {",
    '    return (<main className="shell"><h1>Talk prep</h1><p>Scripture tools are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/scripture/talks");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const talk = await getTalk(id);",
    "  if (!talk) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && talk.ownerId && talk.ownerId !== String(user?.id)) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{talk.status}</p>',
    "      <h1>{talk.title}</h1>",
    '      <p className="note">{[talk.passage, talk.talkType, `~${talk.estimatedDuration} min`].filter(Boolean).join(" · ")}</p>',
    "      <TalkEditor talk={talk} aiEnabled={aiConfigured()} />",
    '      <p><Link className="button" href="/scripture/talks">Back to talks</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/scripture/talks/[id]/talk-editor.tsx (client) ------------------

function talkEditorFile(): GeneratedModuleFile {
  return file("src/app/scripture/talks/[id]/talk-editor.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The talk editor, ported from sermon_prep.py update_sermon + the AI assist",
    "// endpoints: edit the outline sections + research notes + manuscript + status,",
    "// and ask for scripture / point suggestions when an AI key is set.",
    "type OutlineSection = { id: string; title: string; content: string; order: number };",
    "type Talk = {",
    "  id: string;",
    "  title: string;",
    "  passage: string;",
    "  talkType: string;",
    "  status: string;",
    "  estimatedDuration: number;",
    "  outline: OutlineSection[];",
    "  scriptures: string[];",
    "  researchNotes: string;",
    "  manuscript: string;",
    "  deliveryNotes: string;",
    "};",
    "",
    'const STATUSES = ["idea", "researching", "outlining", "drafting", "ready", "delivered"];',
    "",
    "export function TalkEditor({ talk, aiEnabled }: { talk: Talk; aiEnabled: boolean }) {",
    "  const router = useRouter();",
    "  const [outline, setOutline] = useState<OutlineSection[]>(talk.outline);",
    "  const [researchNotes, setResearchNotes] = useState(talk.researchNotes);",
    "  const [manuscript, setManuscript] = useState(talk.manuscript);",
    "  const [status, setStatus] = useState(talk.status);",
    '  const [saveState, setSaveState] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  // AI assist state",
    '  const [topic, setTopic] = useState(talk.title);',
    "  const [suggestions, setSuggestions] = useState<{ reference: string; summary: string }[]>([]);",
    "  const [points, setPoints] = useState<{ title: string; description: string; keyScripture: string }[]>([]);",
    '  const [aiState, setAiState] = useState<"idle" | "working">("idle");',
    '  const [aiNote, setAiNote] = useState("");',
    "",
    "  function editSection(index: number, field: \"title\" | \"content\", value: string) {",
    "    setOutline((prev) => prev.map((s, i) => (i === index ? { ...s, [field]: value } : s)));",
    "  }",
    "",
    "  async function save() {",
    '    setSaveState("saving");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/scripture/talks/${talk.id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ outline, researchNotes, manuscript, status })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setSaveState("error");',
    '        setMessage(data.message || "Could not save. Please try again.");',
    "        return;",
    "      }",
    '      setSaveState("done");',
    '      setMessage("Saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setSaveState("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  async function suggestScriptures() {",
    '    setAiState("working");',
    '    setAiNote("");',
    "    try {",
    '      const response = await fetch("/api/scripture/assist", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ kind: "scriptures", topic })',
    "      });",
    "      const data = await response.json();",
    '      if (data.live === false) { setAiNote(data.message || "Add an AI key to enable suggestions."); setSuggestions([]); }',
    "      else setSuggestions(data.supporting || []);",
    "    } catch {",
    '      setAiNote("Could not reach the AI service.");',
    "    } finally {",
    '      setAiState("idle");',
    "    }",
    "  }",
    "",
    "  async function suggestPoints() {",
    '    setAiState("working");',
    '    setAiNote("");',
    "    try {",
    '      const response = await fetch("/api/scripture/assist", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ kind: "points", title: topic, talkType: talk.talkType, scriptures: talk.scriptures })',
    "      });",
    "      const data = await response.json();",
    '      if (data.live === false) { setAiNote(data.message || "Add an AI key to enable suggestions."); setPoints([]); }',
    "      else setPoints(data.points || []);",
    "    } catch {",
    '      setAiNote("Could not reach the AI service.");',
    "    } finally {",
    '      setAiState("idle");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      <section>",
    "        <h2>Outline</h2>",
    "        {outline.map((section, index) => (",
    '          <article className="panel stack" key={section.id}>',
    '            <input className="input" value={section.title} onChange={(e) => editSection(index, "title", e.target.value)} aria-label={`Section ${index + 1} title`} />',
    '            <textarea className="input" rows={3} value={section.content} onChange={(e) => editSection(index, "content", e.target.value)} aria-label={`Section ${index + 1} content`} />',
    "          </article>",
    "        ))}",
    "      </section>",
    "",
    "      <section className=\"stack\">",
    "        <h2>Research notes</h2>",
    '        <textarea className="input" rows={4} value={researchNotes} onChange={(e) => setResearchNotes(e.target.value)} aria-label="Research notes" />',
    "        <h2>Manuscript</h2>",
    '        <textarea className="input" rows={8} value={manuscript} onChange={(e) => setManuscript(e.target.value)} aria-label="Manuscript" />',
    "        <label className=\"stack\">Status",
    '          <select className="input" value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Status">',
    "            {STATUSES.map((s) => (<option key={s} value={s}>{s}</option>))}",
    "          </select>",
    "        </label>",
    '        {message ? <p className="note" role={saveState === "error" ? "alert" : "status"}>{message}</p> : null}',
    '        <button className="button primary" type="button" onClick={save} disabled={saveState === "saving"}>{saveState === "saving" ? "Saving…" : "Save talk"}</button>',
    "      </section>",
    "",
    '      <section className="stack">',
    "        <h2>AI assist</h2>",
    "        {aiEnabled ? (",
    "          <>",
    '            <input className="input" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Topic or title" aria-label="AI topic" />',
    '            <div className="stack">',
    '              <button className="button" type="button" onClick={suggestScriptures} disabled={aiState === "working"}>Suggest references</button>',
    '              <button className="button" type="button" onClick={suggestPoints} disabled={aiState === "working"}>Suggest points</button>',
    "            </div>",
    "          </>",
    "        ) : (",
    '          <p className="note">Add your AI key to auto-suggest references and outline points. Everything here works without it.</p>',
    "        )}",
    '        {aiNote ? <p className="note" role="status">{aiNote}</p> : null}',
    "        {suggestions.length > 0 ? (",
    '          <ul className="panel-list">',
    '            {suggestions.map((s, i) => (<li key={i} className="wide-card"><strong>{s.reference}</strong><span className="note">{s.summary}</span></li>))}',
    "          </ul>",
    "        ) : null}",
    "        {points.length > 0 ? (",
    '          <ul className="panel-list">',
    '            {points.map((p, i) => (<li key={i} className="wide-card"><strong>{p.title}</strong><p>{p.description}</p>{p.keyScripture ? <span className="note">{p.keyScripture}</span> : null}</li>))}',
    "          </ul>",
    "        ) : null}",
    "      </section>",
    "    </div>",
    "  );",
    "}"
  ]);
}

export const scriptureSermonModule: AppModule = {
  slug: "scripture-sermon-tools",
  name: "Scripture & Sermon Tools",
  tier: "optional",
  featureFlagEnv: "FEATURE_SCRIPTURE",
  files: () => [
    scriptureLibFile(),
    scriptureAiFile(),
    libraryApiFile(),
    libraryDetailApiFile(),
    talksApiFile(),
    talkDetailApiFile(),
    assistApiFile(),
    scripturePageFile(),
    saveFormFile(),
    talksPageFile(),
    newTalkFormFile(),
    talkDetailPageFile(),
    talkEditorFile()
  ],
  schemaSql: () =>
    [
      "",
      "-- Personal reference library, ported from scripture_library.py favorites +",
      "-- personal_scripture_library (reference, verse_text, translation, living",
      "-- translation, notes, tags, categories). Scoped to the owner.",
      "create table if not exists scripture_sermon_tools_saved_references (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  reference text not null,",
      "  verse_text text not null default '',",
      "  translation text not null default 'NIV',",
      "  living_translation text not null default '',",
      "  notes text not null default '',",
      "  tags jsonb not null default '[]'::jsonb,",
      "  categories jsonb not null default '[]'::jsonb,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now(),",
      "  unique (owner_id, reference)",
      ");",
      "create index if not exists scripture_sermon_tools_saved_owner_idx on scripture_sermon_tools_saved_references (owner_id);",
      "create index if not exists scripture_sermon_tools_saved_updated_idx on scripture_sermon_tools_saved_references (updated_at desc);",
      "",
      "-- Talk / sermon preparation, ported from sermon_prep.py sermon_preparations",
      "-- (title, passage, sermon_type, series, estimated_duration, outline sections,",
      "-- scriptures, research_notes, manuscript, delivery_notes, status, tags).",
      "create table if not exists scripture_sermon_tools_talks (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  title text not null default 'Untitled talk',",
      "  passage text not null default '',",
      "  talk_type text not null default 'topical',",
      "  series_name text not null default '',",
      "  series_position integer,",
      "  estimated_duration integer not null default 30,",
      "  outline jsonb not null default '[]'::jsonb,",
      "  scriptures jsonb not null default '[]'::jsonb,",
      "  research_notes text not null default '',",
      "  manuscript text not null default '',",
      "  delivery_notes text not null default '',",
      "  status text not null default 'idea',",
      "  tags jsonb not null default '[]'::jsonb,",
      "  created_at timestamptz not null default now(),",
      "  updated_at timestamptz not null default now()",
      ");",
      "create index if not exists scripture_sermon_tools_talks_owner_idx on scripture_sermon_tools_talks (owner_id);",
      "create index if not exists scripture_sermon_tools_talks_status_idx on scripture_sermon_tools_talks (status);",
      "create index if not exists scripture_sermon_tools_talks_updated_idx on scripture_sermon_tools_talks (updated_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into scripture_sermon_tools_saved_references (reference, verse_text, translation, living_translation, notes, tags, categories) values",
      "  ('Philippians 4:6-7', 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests.', 'NIV', 'Do not let worry run the show. Bring what is weighing on you into the open, and a steadying calm can settle over you.', 'Anchor verse for a talk on anxiety.', '[\"peace\",\"anxiety\"]'::jsonb, '[\"comfort\"]'::jsonb)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Scripture & Sermon Tools — set to false to switch the library + talk prep off.",
    "FEATURE_SCRIPTURE=true",
    "# Optional: the app owner's own AI key powers reference + outline suggestions.",
    "# Leave unset and the tools still work fully — AI assist just stays dormant.",
    "SCRIPTURE_AI_API_KEY=",
    "# Optional: override the model used for AI assist (defaults to a small, fast one).",
    "SCRIPTURE_AI_MODEL="
  ],
  requiredEnv: [],
  homeLinks: () => ['        <a className="button" href="/scripture">Scripture library</a>'],
  navLinks: () => [
    { href: "/scripture", label: "Scripture" },
    { href: "/scripture/talks", label: "Talk prep" }
  ]
};
