// staffing — one job: fill shifts. Roles, posted shifts, volunteer sign-up,
// and a schedule that flags short-handed rooms or uncleared people.
// Ported from ChurchConnect backend/routes/childcare_staffing.py:
//   DEFAULT_RATIOS (infant 1:4, toddler 1:5, preschool 1:7, pre_k 1:8,
//   elementary 1:10), staffing ROLES with clearance requirements
//   (requires_background_check / cpr / child_protection_training, min_age_to_serve),
//   SHIFTS (event_date, start/end time, room, role, slots_needed) that volunteers
//   self-sign-up for, the (shift,user) unique-signup guard + drop, and the
//   get_schedule composition (filled vs slots_needed, needs_more, uncleared_alert).
// Check-in is a different brick (`checkin`). Packs may snap both together.
// Events + booking a room stay on `events-scheduling` — that is one flow, two stages.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

function staffingLibFile(): GeneratedModuleFile {
  return file("src/lib/db/staffing.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// The standard adult-to-child ratios, ported verbatim from DEFAULT_RATIOS.",
    "export const DEFAULT_RATIOS = [",
    '  { ageBand: "infant", minAge: 0, maxAge: 1, ratio: "1:4", notes: "0-12 months" },',
    '  { ageBand: "toddler", minAge: 1, maxAge: 2, ratio: "1:5", notes: "1-2 years" },',
    '  { ageBand: "preschool", minAge: 3, maxAge: 4, ratio: "1:7", notes: "3-4 years" },',
    '  { ageBand: "pre_k", minAge: 4, maxAge: 5, ratio: "1:8", notes: "Pre-K" },',
    '  { ageBand: "elementary", minAge: 5, maxAge: 12, ratio: "1:10", notes: "K-5th grade" }',
    "];",
    "",
    "// A staffing role, ported from childcare_staffing.py RoleIn: what clearances a",
    "// volunteer must hold to serve in it.",
    "export type StaffRole = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  description: string;",
    "  requiresBackgroundCheck: boolean;",
    "  requiresCpr: boolean;",
    "  requiresChildProtectionTraining: boolean;",
    "  minAgeToServe: number;",
    "  createdAt: string;",
    "};",
    "",
    "// A shift volunteers self-sign-up for, ported from ShiftIn.",
    "export type Shift = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  eventDate: string;",
    "  startTime: string;",
    "  endTime: string;",
    "  roomName: string;",
    "  roleId: string | null;",
    "  slotsNeeded: number;",
    "  notes: string;",
    "  createdAt: string;",
    "};",
    "",
    "// A volunteer's signup for a shift, ported from signup_for_shift: the clearance",
    "// flag is captured at signup time so the schedule can flag uncleared volunteers.",
    "export type ShiftSignup = {",
    "  id: string;",
    "  shiftId: string;",
    "  userId: string;",
    "  name: string;",
    "  email: string;",
    "  isClearedAtSignup: boolean;",
    "  signedUpAt: string;",
    "};",
    "",
    "// A shift composed with its role + signups + ratio analysis, ported from the",
    "// get_schedule dashboard composition.",
    "export type ScheduledShift = Shift & {",
    "  role: StaffRole | null;",
    "  signups: ShiftSignup[];",
    "  filled: number;",
    "  clearedFilled: number;",
    "  needsMore: number;",
    "  unclearedAlert: boolean;",
    "};",
    "",
    "const fallbackRoles: StaffRole[] = [];",
    "const fallbackShifts: Shift[] = [];",
    "const fallbackSignups: ShiftSignup[] = [];",
    "",
    "function rowToRole(row: Record<string, unknown>): StaffRole {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    name: String(row.name || ""),',
    '    description: String(row.description || ""),',
    '    requiresBackgroundCheck: row.requires_background_check === true || String(row.requires_background_check) === "true",',
    '    requiresCpr: row.requires_cpr === true || String(row.requires_cpr) === "true",',
    '    requiresChildProtectionTraining: row.requires_child_protection_training === true || String(row.requires_child_protection_training) === "true",',
    "    minAgeToServe: Number(row.min_age_to_serve || 18),",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToShift(row: Record<string, unknown>): Shift {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    eventDate: row.event_date ? String(row.event_date) : "",',
    '    startTime: String(row.start_time || ""),',
    '    endTime: String(row.end_time || ""),',
    '    roomName: String(row.room_name || ""),',
    "    roleId: row.role_id != null ? String(row.role_id) : null,",
    "    slotsNeeded: Number(row.slots_needed || 1),",
    '    notes: String(row.notes || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToSignup(row: Record<string, unknown>): ShiftSignup {",
    "  return {",
    "    id: String(row.id),",
    '    shiftId: String(row.shift_id || ""),',
    '    userId: String(row.user_id || ""),',
    '    name: String(row.name || ""),',
    '    email: String(row.email || ""),',
    '    isClearedAtSignup: row.is_cleared_at_signup === true || String(row.is_cleared_at_signup) === "true",',
    '    signedUpAt: row.signed_up_at ? String(row.signed_up_at) : ""',
    "  };",
    "}",
    "",
    "// List staffing roles, ported from list_roles (name order), scoped to an owner.",
    "export async function listRoles(ownerId?: string): Promise<StaffRole[]> {",
    "  if (!hasDatabase()) return fallbackRoles.filter((r) => !ownerId || r.ownerId === ownerId);",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve, created_at",
    "      from staffing_roles",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "      order by name asc`;",
    "    return rows.map(rowToRole);",
    "  } catch {",
    "    return fallbackRoles;",
    "  }",
    "}",
    "",
    "export type CreateRoleInput = {",
    "  ownerId: string | null;",
    "  name: string;",
    "  description?: string;",
    "  requiresBackgroundCheck?: boolean;",
    "  requiresCpr?: boolean;",
    "  requiresChildProtectionTraining?: boolean;",
    "  minAgeToServe?: number;",
    "};",
    "",
    "// Create a staffing role, ported from create_role (admin-gated at the API layer).",
    "export async function createRole(input: CreateRoleInput): Promise<StaffRole | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into staffing_roles (",
    "        owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve",
    "      ) values (",
    '        ${input.ownerId || null}, ${input.name}, ${input.description || ""},',
    "        ${input.requiresBackgroundCheck !== false}, ${input.requiresCpr === true},",
    "        ${input.requiresChildProtectionTraining !== false}, ${input.minAgeToServe || 18}",
    "      )",
    "      returning id, owner_id, name, description, requires_background_check, requires_cpr,",
    "        requires_child_protection_training, min_age_to_serve, created_at`;",
    "    return rows[0] ? rowToRole(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// List shifts in a date range, ported from list_shifts (event_date/start_time",
    "// order), scoped to an owner.",
    "export async function listShifts(ownerId?: string, startDate?: string, endDate?: string): Promise<Shift[]> {",
    "  if (!hasDatabase()) return fallbackShifts.filter((s) => !ownerId || s.ownerId === ownerId);",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const from = startDate || null;",
    "    const to = endDate || null;",
    "    const rows = await sql`",
    "      select id, owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes, created_at",
    "      from staffing_shifts",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${from}::text is null or event_date >= ${from})",
    "        and (${to}::text is null or event_date <= ${to})",
    "      order by event_date asc, start_time asc`;",
    "    return rows.map(rowToShift);",
    "  } catch {",
    "    return fallbackShifts;",
    "  }",
    "}",
    "",
    "export type CreateShiftInput = {",
    "  ownerId: string | null;",
    "  eventDate: string;",
    "  startTime: string;",
    "  endTime: string;",
    "  roomName?: string;",
    "  roleId?: string | null;",
    "  slotsNeeded?: number;",
    "  notes?: string;",
    "};",
    "",
    "// Create a shift, ported from create_shift.",
    "export async function createShift(input: CreateShiftInput): Promise<Shift | null> {",
    "  if (!hasDatabase()) return null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into staffing_shifts (",
    "        owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.eventDate}, ${input.startTime}, ${input.endTime},",
    '        ${input.roomName || ""}, ${input.roleId || null}, ${Math.max(1, input.slotsNeeded || 1)},',
    '        ${input.notes || ""}',
    "      )",
    "      returning id, owner_id, event_date, start_time, end_time, room_name, role_id,",
    "        slots_needed, notes, created_at`;",
    "    return rows[0] ? rowToShift(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Sign a volunteer up for a shift, ported from signup_for_shift: the (shift,user)",
    "// unique guard means a repeat is a no-op, and the volunteer's cleared flag is",
    "// captured at signup time. Returns already=true if they were already on it.",
    "export async function signupForShift(",
    "  shiftId: string,",
    "  user: { id: string; name?: string; email?: string; cleared?: boolean }",
    "): Promise<{ ok: boolean; already?: boolean; message?: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to sign up for shifts." };',
    "  try {",
    "    const sql = getDatabase();",
    "    const shift = await sql`select id from staffing_shifts where id = ${shiftId} limit 1`;",
    '    if (!shift[0]) return { ok: false, message: "That shift was not found." };',
    "    const cleared = user.cleared === true;",
    "    const rows = await sql`",
    "      insert into staffing_shift_signups (shift_id, user_id, name, email, is_cleared_at_signup)",
    '      values (${shiftId}, ${user.id}, ${user.name || ""}, ${user.email || ""}, ${cleared})',
    "      on conflict (shift_id, user_id) do nothing",
    "      returning id`;",
    "    if (!rows[0]) return { ok: true, already: true };",
    "    return { ok: true };",
    "  } catch {",
    '    return { ok: false, message: "Could not sign up. Please try again." };',
    "  }",
    "}",
    "",
    "// Drop a volunteer from a shift, ported from drop_signup.",
    "export async function dropSignup(shiftId: string, userId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`delete from staffing_shift_signups where shift_id = ${shiftId} and user_id = ${userId}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "async function composeSchedule(shifts: Shift[], ownerId?: string): Promise<ScheduledShift[]> {",
    "  if (shifts.length === 0) return [];",
    "  const roles = await listRoles(ownerId);",
    "  const roleById = new Map(roles.map((r) => [r.id, r]));",
    "  let signupsByShift = new Map<string, ShiftSignup[]>();",
    "  if (!hasDatabase()) {",
    "    for (const s of fallbackSignups) {",
    "      const list = signupsByShift.get(s.shiftId) || [];",
    "      list.push(s);",
    "      signupsByShift.set(s.shiftId, list);",
    "    }",
    "  } else {",
    "    try {",
    "      const sql = getDatabase();",
    "      const ids = shifts.map((s) => s.id);",
    "      const rows = await sql`",
    "        select id, shift_id, user_id, name, email, is_cleared_at_signup, signed_up_at",
    "        from staffing_shift_signups where shift_id = any(${ids})`;",
    "      const grouped = new Map<string, ShiftSignup[]>();",
    "      for (const row of rows) {",
    "        const signup = rowToSignup(row);",
    "        const list = grouped.get(signup.shiftId) || [];",
    "        list.push(signup);",
    "        grouped.set(signup.shiftId, list);",
    "      }",
    "      signupsByShift = grouped;",
    "    } catch {",
    "      signupsByShift = new Map();",
    "    }",
    "  }",
    "  return shifts.map((shift) => {",
    "    const signups = signupsByShift.get(shift.id) || [];",
    "    const clearedFilled = signups.filter((x) => x.isClearedAtSignup).length;",
    "    return {",
    "      ...shift,",
    "      role: shift.roleId ? roleById.get(shift.roleId) || null : null,",
    "      signups,",
    "      filled: signups.length,",
    "      clearedFilled,",
    "      needsMore: Math.max(0, shift.slotsNeeded - signups.length),",
    "      unclearedAlert: clearedFilled < signups.length",
    "    };",
    "  });",
    "}",
    "",
    "// The schedule view for a date, ported from get_schedule: each shift composed",
    "// with its role and signups, plus filled vs slots_needed (needs_more) and an",
    "// uncleared_alert when a signed-up volunteer was not cleared at signup.",
    "export async function getSchedule(date: string, ownerId?: string): Promise<ScheduledShift[]> {",
    "  return composeSchedule(await listShifts(ownerId, date, date), ownerId);",
    "}",
    "",
    "export async function getUpcomingSchedule(ownerId?: string): Promise<ScheduledShift[]> {",
    "  return composeSchedule(await listShifts(ownerId), ownerId);",
    "}",
    "",
    "export function staffingEnabled(): boolean {",
    '  return process.env.FEATURE_STAFFING !== "false";',
    "}"
  ]);
}

function staffingApiFile(): GeneratedModuleFile {
  return file("src/app/api/staffing/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    "import {",
    "  listRoles, createRole, listShifts, createShift, getSchedule, DEFAULT_RATIOS, staffingEnabled",
    '} from "@/lib/db/staffing";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Roles, shifts, and the schedule view — ported from childcare_staffing.py's read",
    "// endpoints (list_roles / list_shifts / get_schedule + DEFAULT_RATIOS).",
    "export async function GET(request: Request) {",
    '  if (!staffingEnabled()) return NextResponse.json({ ok: false, message: "Staffing is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    '  const date = url.searchParams.get("date") || "";',
    "  const roles = await listRoles(ownerId);",
    "  if (date) {",
    "    const schedule = await getSchedule(date, ownerId);",
    "    return NextResponse.json({ ok: true, roles, schedule, ratios: DEFAULT_RATIOS });",
    "  }",
    "  const shifts = await listShifts(ownerId);",
    "  return NextResponse.json({ ok: true, roles, shifts, ratios: DEFAULT_RATIOS });",
    "}",
    "",
    "// Create a staffing role or a shift. Defining roles is an admin control (ported",
    "// from create_role's church-admin gate); creating shifts is open to any signed-in",
    "// owner (ported from create_shift). The body's `kind` selects which.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const kind = typeof body.kind === "string" ? body.kind : "shift";',
    "  const ownerId = user?.id ? String(user.id) : null;",
    "",
    '  if (kind === "role") {',
    "    // Defining staffing roles is admin-only, ported from create_role.",
    '    if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins define staffing roles." }, { status: 403 });',
    '    const name = typeof body.name === "string" ? body.name.trim() : "";',
    '    if (name.length < 2) return NextResponse.json({ ok: false, message: "Name the role." }, { status: 400 });',
    "    const role = await createRole({",
    "      ownerId,",
    "      name,",
    '      description: typeof body.description === "string" ? body.description : undefined,',
    "      requiresBackgroundCheck: body.requiresBackgroundCheck !== false,",
    "      requiresCpr: body.requiresCpr === true,",
    "      requiresChildProtectionTraining: body.requiresChildProtectionTraining !== false,",
    '      minAgeToServe: typeof body.minAgeToServe === "number" ? body.minAgeToServe : undefined',
    "    });",
    '    if (!role) return NextResponse.json({ ok: false, message: "Connect a database to define roles." }, { status: 503 });',
    "    return NextResponse.json({ ok: true, role });",
    "  }",
    "",
    '  const eventDate = typeof body.eventDate === "string" ? body.eventDate.trim() : "";',
    '  const startTime = typeof body.startTime === "string" ? body.startTime.trim() : "";',
    '  const endTime = typeof body.endTime === "string" ? body.endTime.trim() : "";',
    "  if (!eventDate || !startTime || !endTime) {",
    '    return NextResponse.json({ ok: false, message: "A date, start time, and end time are required." }, { status: 400 });',
    "  }",
    "  const shift = await createShift({",
    "    ownerId,",
    "    eventDate,",
    "    startTime,",
    "    endTime,",
    '    roomName: typeof body.roomName === "string" ? body.roomName : undefined,',
    '    roleId: typeof body.roleId === "string" ? body.roleId : null,',
    '    slotsNeeded: typeof body.slotsNeeded === "number" ? body.slotsNeeded : undefined,',
    '    notes: typeof body.notes === "string" ? body.notes : undefined',
    "  });",
    '  if (!shift) return NextResponse.json({ ok: false, message: "Connect a database to schedule shifts." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, shift });",
    "}"
  ]);
}

function staffingSignupApiFile(): GeneratedModuleFile {
  return file("src/app/api/staffing/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { signupForShift, dropSignup, staffingEnabled } from "@/lib/db/staffing";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Volunteer self-sign-up / drop, ported from signup_for_shift + drop_signup. Any",
    "// signed-in user signs themselves up (or off) — the volunteer scopes to user.id.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!staffingEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessCustomerArea(user.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "signup";',
    '  if (action === "drop") {',
    "    const dropped = await dropSignup(id, String(user.id));",
    '    if (!dropped) return NextResponse.json({ ok: false, message: "Connect a database to update shifts." }, { status: 503 });',
    "    return NextResponse.json({ ok: true });",
    "  }",
    "  const result = await signupForShift(id, {",
    "    id: String(user.id),",
    '    name: user.name || "",',
    '    email: user.email || "",',
    "    // Clearance is captured at signup; wire a real background-check store to set this.",
    "    cleared: body.cleared === true",
    "  });",
    '  if (!result.ok) return NextResponse.json(result, { status: 400 });',
    "  return NextResponse.json(result);",
    "}"
  ]);
}

function staffingPageFile(): GeneratedModuleFile {
  return file("src/app/staffing/page.tsx", [
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listRoles, getUpcomingSchedule, DEFAULT_RATIOS, staffingEnabled } from "@/lib/db/staffing";',
    'import { StaffingForms, ShiftSignupButtons } from "./staffing-forms";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function StaffingPage() {",
    "  if (!staffingEnabled()) {",
    '    return (<main className="shell"><h1>Staffing</h1><p>Staffing is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/staffing");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = user?.id ? String(user.id) : undefined;",
    "  const userId = user?.id ? String(user.id) : \"\";",
    "  const roles = await listRoles(ownerId);",
    "  const shifts = await getUpcomingSchedule(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Staffing</p>',
    "      <h1>Fill the shifts</h1>",
    "      <p>Define the roles people can serve in, post shifts, and let volunteers sign themselves up. The schedule flags any shift that is short-handed or has an uncleared volunteer.</p>",
    "      <h2>Adult-to-child ratios</h2>",
    "      <p>Standard safe ratios per age band — the baseline every room should staff to.</p>",
    '      <section className="panel-list">',
    "        {DEFAULT_RATIOS.map((r) => (",
    '          <article className="wide-card" key={r.ageBand}>',
    "            <span>{r.ratio}</span>",
    "            <strong>{r.ageBand.replace(\"_\", \" \")}</strong>",
    '            <p className="note">{r.notes}</p>',
    "          </article>",
    "        ))}",
    "      </section>",
    "      <h2>Roles</h2>",
    "      {roles.length === 0 ? (",
    '        <p className="note">No roles defined yet.{isAdmin ? " Add one below." : ""}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {roles.map((role) => (",
    '            <article className="wide-card" key={role.id}>',
    "              <strong>{role.name}</strong>",
    "              {role.description ? <p>{role.description}</p> : null}",
    '              <p className="note">{[',
    '                role.requiresBackgroundCheck ? "Background check" : "",',
    '                role.requiresCpr ? "CPR" : "",',
    '                role.requiresChildProtectionTraining ? "Child protection training" : "",',
    '                `Min age ${role.minAgeToServe}`',
    '              ].filter(Boolean).join(" · ")}</p>',
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Upcoming shifts</h2>",
    "      {shifts.length === 0 ? (",
    '        <p className="note">No shifts posted yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {shifts.map((shift) => (",
    '            <article className="wide-card" key={shift.id}>',
    '              <span>{[shift.eventDate, `${shift.startTime}–${shift.endTime}`].filter(Boolean).join(" · ")}</span>',
    '              <strong>{shift.roomName || shift.role?.name || "Shift"}</strong>',
    '              <p className="note">{shift.filled} of {shift.slotsNeeded} filled{shift.needsMore ? ` · needs ${shift.needsMore} more` : ""}{shift.unclearedAlert ? " · uncleared volunteer" : ""}</p>',
    "              <ShiftSignupButtons shiftId={shift.id} alreadySigned={shift.signups.some((s) => s.userId === userId)} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <StaffingForms isAdmin={isAdmin} roles={roles.map((r) => ({ id: r.id, name: r.name }))} />",
    "    </main>",
    "  );",
    "}"
  ]);
}

function staffingFormsFile(): GeneratedModuleFile {
  return file("src/app/staffing/staffing-forms.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Post a shift (any owner) and — for admins — define a staffing role. Ported from",
    "// childcare_staffing.py create_shift + create_role.",
    "export function StaffingForms({ isAdmin, roles }: { isAdmin: boolean; roles: Array<{ id: string; name: string }> }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function post(url: string, payload: Record<string, unknown>) {",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(url, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(payload)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    "  async function submitShift(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = new FormData(event.currentTarget);",
    '    await post("/api/staffing", {',
    '      kind: "shift",',
    '      eventDate: form.get("eventDate"),',
    '      startTime: form.get("startTime"),',
    '      endTime: form.get("endTime"),',
    '      roomName: form.get("roomName"),',
    '      roleId: form.get("roleId") || null,',
    '      slotsNeeded: Number(form.get("slotsNeeded") || 1)',
    "    });",
    "  }",
    "",
    "  async function submitRole(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    "    const form = new FormData(event.currentTarget);",
    '    await post("/api/staffing", {',
    '      kind: "role",',
    '      name: form.get("name"),',
    '      description: form.get("description"),',
    '      requiresBackgroundCheck: form.get("requiresBackgroundCheck") === "on",',
    '      requiresCpr: form.get("requiresCpr") === "on",',
    '      requiresChildProtectionTraining: form.get("requiresChildProtectionTraining") === "on",',
    '      minAgeToServe: Number(form.get("minAgeToServe") || 18)',
    "    });",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      <h2>Post a shift</h2>",
    '      <form className="stack" onSubmit={submitShift}>',
    '        <input className="input" name="eventDate" type="date" aria-label="Shift date" required />',
    '        <input className="input" name="startTime" placeholder="Start (e.g. 09:00)" aria-label="Start time" required />',
    '        <input className="input" name="endTime" placeholder="End (e.g. 10:30)" aria-label="End time" required />',
    '        <input className="input" name="roomName" placeholder="Room (e.g. Infant Room)" aria-label="Room" />',
    "        <select className=\"input\" name=\"roleId\" aria-label=\"Role\" defaultValue=\"\">",
    '          <option value="">Any role</option>',
    "          {roles.map((r) => (",
    "            <option key={r.id} value={r.id}>{r.name}</option>",
    "          ))}",
    "        </select>",
    '        <input className="input" name="slotsNeeded" type="number" min={1} defaultValue={1} aria-label="Slots needed" />',
    '        <button className="button primary" type="submit" disabled={status === "saving"}>Post shift</button>',
    "      </form>",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Define a role</h2>",
    '          <form className="stack" onSubmit={submitRole}>',
    '            <input className="input" name="name" placeholder="Role name (e.g. Nursery Lead)" aria-label="Role name" required />',
    '            <input className="input" name="description" placeholder="What this role does (optional)" aria-label="Role description" />',
    '            <label className="check"><input type="checkbox" name="requiresBackgroundCheck" defaultChecked /> Requires background check</label>',
    '            <label className="check"><input type="checkbox" name="requiresCpr" /> Requires CPR</label>',
    '            <label className="check"><input type="checkbox" name="requiresChildProtectionTraining" defaultChecked /> Requires child protection training</label>',
    '            <input className="input" name="minAgeToServe" type="number" min={0} defaultValue={18} aria-label="Minimum age to serve" />',
    '            <button className="button" type="submit" disabled={status === "saving"}>Add role</button>',
    "          </form>",
    "        </>",
    "      ) : null}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      {status === "done" ? <p className="note" role="status">{message}</p> : null}',
    "    </div>",
    "  );",
    "}",
    "",
    "export function ShiftSignupButtons({ shiftId, alreadySigned }: { shiftId: string; alreadySigned: boolean }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function act(action: \"signup\" | \"drop\") {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/staffing/${shiftId}`, {",
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this shift.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    "      {alreadySigned ? (",
    '        <button className="button" type="button" onClick={() => act("drop")} disabled={status === "working"}>Drop this shift</button>',
    "      ) : (",
    '        <button className="button primary" type="button" onClick={() => act("signup")} disabled={status === "working"}>Sign up</button>',
    "      )}",
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const staffingModule: AppModule = {
  slug: "staffing",
  name: "Staffing",
  tier: "optional",
  featureFlagEnv: "FEATURE_STAFFING",
  files: () => [
    staffingLibFile(),
    staffingApiFile(),
    staffingSignupApiFile(),
    staffingPageFile(),
    staffingFormsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists staffing_roles (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  name text not null,",
      "  description text not null default '',",
      "  requires_background_check boolean not null default true,",
      "  requires_cpr boolean not null default false,",
      "  requires_child_protection_training boolean not null default true,",
      "  min_age_to_serve integer not null default 18,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists staffing_roles_owner_idx on staffing_roles (owner_id);",
      "",
      "create table if not exists staffing_shifts (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  event_date text not null,",
      "  start_time text not null default '',",
      "  end_time text not null default '',",
      "  room_name text not null default '',",
      "  role_id uuid references staffing_roles(id) on delete set null,",
      "  slots_needed integer not null default 1,",
      "  notes text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists staffing_shifts_owner_date_idx on staffing_shifts (owner_id, event_date);",
      "",
      "create table if not exists staffing_shift_signups (",
      "  id uuid primary key default gen_random_uuid(),",
      "  shift_id uuid not null references staffing_shifts(id) on delete cascade,",
      "  user_id uuid not null references users(id) on delete cascade,",
      "  name text not null default '',",
      "  email text not null default '',",
      "  is_cleared_at_signup boolean not null default false,",
      "  signed_up_at timestamptz not null default now(),",
      "  unique (shift_id, user_id)",
      ");",
      "create index if not exists staffing_shift_signups_shift_idx on staffing_shift_signups (shift_id);"
    ].join("\n"),
  envLines: () => [
    "",
    "# Staffing — set to false to switch roles, shifts, and sign-up off.",
    "FEATURE_STAFFING=true"
  ],
  homeLinks: () => ['        <a className="button" href="/staffing">Staffing</a>'],
  navLinks: () => [{ href: "/staffing", label: "Staffing" }]
};
