// supplier-order-automation — forecast supply needs, compare vendor pricing,
// automate the purchase/order flow, and reconcile fulfillment. Ported from
// TonerTrackerPro's real supply-chain code:
//   - server/supplier-service.ts (selectSupplierForOrder / findDefaultSupplier /
//     canSupplierFulfillOrder): pick the vendor for an item — honor a preferred
//     supplier when set, else fall back to the lowest-priced ACTIVE supplier whose
//     catalog covers the item and who can fulfill; the "saves $X vs retail" reason
//     string is ported verbatim from findDefaultSupplier.
//   - server/services/orderAutomation.ts (createOrder / automation modes): the
//     manual | auto | conditional automation mode, the auto-approve rule
//     (auto/conditional auto-approve; manual stays pending), the conditional
//     "toner already on hand -> skip" branch, and the pricing-error -> force
//     pending-review branch, all ported from OrderAutomationService.createOrder.
//   - server/order-fulfillment-service.ts (processApprovedOrder / handleApiOrder /
//     handleManualOrder / createTonerOrder): once an order is approved, route it by
//     supplier capability (api+supportsAutomaticOrdering -> auto task; portal/email
//     -> manual task with a ported email/portal instruction body), stamp the order
//     'ordered', and create the fulfillment task; reconcile = mark received.
//   - attached_assets .../AutoOrderSettings.tsx: the owner settings — enable
//     auto-order, order threshold (days remaining), max auto-order amount, require
//     approval + approval threshold — ported as the org automation config surface.
//   - attached_assets .../SupplierIntegration.tsx: the supplier record (name,
//     contactName, email, phone, priority [1=highest], enabled, notes) and the
//     priority-ordered, email-based supplier list, ported as the supplier registry.
// Generalized off the printer/toner framing into plain "supply item" language so it
// drops into any app. Runs on the app owner's own database with graceful sample-data
// fallback, feature-flagged (FEATURE_SUPPLIER); customers view forecasts + queue +
// suppliers, admins add suppliers, run the forecast, and approve/place/reconcile.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/supplier-automation.ts (models + queries + core logic) -------
// Ported from supplier-service.ts, orderAutomation.ts, order-fulfillment-service.ts.

function supplierLibFile(): GeneratedModuleFile {
  return file("src/lib/db/supplier-automation.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A supplier/vendor, ported from SupplierIntegration.tsx SupplierConfig plus the",
    "// active/pricing fields supplier-service.ts reads (isActive, catalog unit price,",
    "// retail price for savings, order placement + inventory capability).",
    "export type Supplier = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  name: string;",
    "  contactName: string;",
    "  email: string;",
    "  phone: string;",
    "  // 1 = highest priority (ported from SupplierIntegration.tsx priority).",
    "  priority: number;",
    "  enabled: boolean;",
    "  notes: string;",
    "  // Catalog pricing used for vendor comparison (ported from findDefaultSupplier:",
    "  // toner.unitPrice vs officeDepotRetailPrice -> savings).",
    "  unitPrice: number;",
    "  retailPrice: number | null;",
    "  // How orders are placed with this supplier, ported from SupplierCapabilities",
    "  // orderPlacementMethod: 'api' | 'portal' | 'email'.",
    '  orderMethod: "api" | "portal" | "email";',
    "  // Whether an 'api' supplier can be fully automated (supportsAutomaticOrdering).",
    "  supportsAutomaticOrdering: boolean;",
    "  portalUrl: string;",
    "  createdAt: string;",
    "};",
    "",
    "// An order in the queue, ported from OrderAutomationService order shape +",
    "// order-fulfillment-service processing status. This is the forecast -> purchase",
    "// -> fulfillment -> reconcile record.",
    "export type SupplyOrder = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  supplierId: string | null;",
    "  supplierName: string;",
    "  itemName: string;",
    "  quantity: number;",
    "  unitPrice: number;",
    "  totalAmount: number;",
    "  // Ported from OrderAutomationService createOrder status +",
    "  // order-fulfillment-service processingStatus transitions.",
    '  // pending -> approved -> ordered -> received; or skipped.',
    '  status: "pending" | "approved" | "ordered" | "received" | "skipped";',
    "  // Why this order exists (forecast trigger), ported from triggerReason.",
    "  triggerReason: string;",
    "  // How it was routed at fulfillment, ported from handleApiOrder/handleManualOrder.",
    '  fulfillmentMethod: "" | "api" | "portal" | "email";',
    "  fulfillmentNote: string;",
    "  // null approvedBy = auto-approval, ported verbatim from createOrder.",
    "  approvedByUserId: string | null;",
    "  approvedAt: string | null;",
    "  orderedAt: string | null;",
    "  receivedAt: string | null;",
    "  createdAt: string;",
    "};",
    "",
    "// A forecasted supply need, ported in spirit from AutoOrderSettings.tsx (order",
    "// threshold in days remaining) + SupplierIntegration tonerLevels (currentLevel,",
    "// daysRemaining, status good|low|critical). This is the 'forecast supply needs'",
    "// input the automation acts on.",
    "export type SupplyForecast = {",
    "  itemName: string;",
    "  currentLevel: number;",
    "  daysRemaining: number;",
    '  urgency: "good" | "low" | "critical";',
    "  suggestedQuantity: number;",
    "};",
    "",
    "// Owner automation config, ported field-for-field from AutoOrderSettings.tsx",
    "// (autoOrderEnabled, orderThreshold days, maxOrderAmount, requireApproval,",
    "// approvalThreshold) plus orderAutomationMode from OrderAutomationService.",
    "export type AutomationConfig = {",
    "  ownerId: string | null;",
    '  mode: "manual" | "auto" | "conditional";',
    "  autoOrderEnabled: boolean;",
    "  orderThresholdDays: number;",
    "  maxOrderAmount: number;",
    "  requireApproval: boolean;",
    "  approvalThreshold: number;",
    "};",
    "",
    "// Ported from OrderAutomationService.getAutomationModeDescription.",
    "export function automationModeDescription(mode: string): string {",
    "  switch (mode) {",
    '    case "manual":',
    '      return "Manual approval required for all orders";',
    '    case "auto":',
    '      return "Automatic approval and ordering";',
    '    case "conditional":',
    '      return "Auto-approve unless the item is already on hand";',
    "    default:",
    '      return "Unknown automation mode";',
    "  }",
    "}",
    "",
    "// Ported from OrderAutomationService.shouldAutoApprove: auto + conditional",
    "// auto-approve; manual stays pending.",
    "export function shouldAutoApprove(mode: string): boolean {",
    '  return mode === "auto" || mode === "conditional";',
    "}",
    "",
    "// Classify a forecast into good | low | critical using the owner's day threshold,",
    "// ported in spirit from SupplierIntegration tonerLevels status + AutoOrderSettings",
    "// orderThreshold. critical <= threshold/2, low <= threshold, else good.",
    "export function forecastUrgency(daysRemaining: number, thresholdDays: number): SupplyForecast[\"urgency\"] {",
    '  if (daysRemaining <= Math.max(1, Math.floor(thresholdDays / 2))) return "critical";',
    '  if (daysRemaining <= thresholdDays) return "low";',
    '  return "good";',
    "}",
    "",
    "const defaultConfig: AutomationConfig = {",
    "  ownerId: null,",
    '  mode: "auto",',
    "  autoOrderEnabled: true,",
    "  orderThresholdDays: 10,",
    "  maxOrderAmount: 500,",
    "  requireApproval: false,",
    "  approvalThreshold: 200",
    "};",
    "",
    "// Sample suppliers ported from SupplierIntegration.tsx's real seed list.",
    "const fallbackSuppliers: Supplier[] = [",
    "  {",
    '    id: "sample-supplier-1",',
    "    ownerId: null,",
    '    name: "123inkjets.com",',
    '    contactName: "Sales Team",',
    '    email: "orders@123inkjets.com",',
    '    phone: "1-800-123-4567",',
    "    priority: 1,",
    "    enabled: true,",
    '    notes: "Compatible specialist - good prices",',
    "    unitPrice: 42.5,",
    "    retailPrice: 79.99,",
    '    orderMethod: "email",',
    "    supportsAutomaticOrdering: false,",
    '    portalUrl: "",',
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-supplier-2",',
    "    ownerId: null,",
    '    name: "InkJet.com",',
    '    contactName: "Customer Service",',
    '    email: "sales@inkjet.com",',
    '    phone: "1-888-465-5381",',
    "    priority: 2,",
    "    enabled: true,",
    '    notes: "Fast shipping, OEM and compatible options",',
    "    unitPrice: 58.0,",
    "    retailPrice: 79.99,",
    '    orderMethod: "portal",',
    "    supportsAutomaticOrdering: false,",
    '    portalUrl: "https://www.inkjet.com",',
    '    createdAt: "2025-01-02T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-supplier-3",',
    "    ownerId: null,",
    '    name: "Local Office Supply Co.",',
    '    contactName: "Mike Johnson",',
    '    email: "mike@localofficesupply.com",',
    '    phone: "(555) 123-4567",',
    "    priority: 3,",
    "    enabled: false,",
    '    notes: "Local supplier for emergency orders",',
    "    unitPrice: 65.0,",
    "    retailPrice: null,",
    '    orderMethod: "email",',
    "    supportsAutomaticOrdering: false,",
    '    portalUrl: "",',
    '    createdAt: "2025-01-03T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "const fallbackOrders: SupplyOrder[] = [",
    "  {",
    '    id: "sample-order-1",',
    "    ownerId: null,",
    '    supplierId: "sample-supplier-1",',
    '    supplierName: "123inkjets.com",',
    '    itemName: "Black Toner (HP 26X)",',
    "    quantity: 2,",
    "    unitPrice: 42.5,",
    "    totalAmount: 85.0,",
    '    status: "ordered",',
    '    triggerReason: "Forecast: 3 days remaining (critical)",',
    '    fulfillmentMethod: "email",',
    '    fulfillmentNote: "Order email queued to orders@123inkjets.com",',
    "    approvedByUserId: null,",
    '    approvedAt: "2025-02-01T00:00:00.000Z",',
    '    orderedAt: "2025-02-01T00:05:00.000Z",',
    "    receivedAt: null,",
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function n(v: unknown, d = 0): number {",
    "  const x = Number(v);",
    "  return Number.isFinite(x) ? x : d;",
    "}",
    "",
    "function rowToSupplier(row: Record<string, unknown>): Supplier {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    name: String(row.name || ""),',
    '    contactName: String(row.contact_name || ""),',
    '    email: String(row.email || ""),',
    '    phone: String(row.phone || ""),',
    "    priority: n(row.priority, 1),",
    '    enabled: row.enabled === true || String(row.enabled) === "true",',
    '    notes: String(row.notes || ""),',
    "    unitPrice: n(row.unit_price, 0),",
    "    retailPrice: row.retail_price != null ? n(row.retail_price, 0) : null,",
    '    orderMethod: (["api", "portal", "email"].includes(String(row.order_method)) ? String(row.order_method) : "email") as Supplier["orderMethod"],',
    '    supportsAutomaticOrdering: row.supports_automatic_ordering === true || String(row.supports_automatic_ordering) === "true",',
    '    portalUrl: String(row.portal_url || ""),',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "function rowToOrder(row: Record<string, unknown>): SupplyOrder {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    "    supplierId: row.supplier_id != null ? String(row.supplier_id) : null,",
    '    supplierName: String(row.supplier_name || ""),',
    '    itemName: String(row.item_name || ""),',
    "    quantity: n(row.quantity, 1),",
    "    unitPrice: n(row.unit_price, 0),",
    "    totalAmount: n(row.total_amount, 0),",
    '    status: (["pending", "approved", "ordered", "received", "skipped"].includes(String(row.status)) ? String(row.status) : "pending") as SupplyOrder["status"],',
    '    triggerReason: String(row.trigger_reason || ""),',
    '    fulfillmentMethod: (["api", "portal", "email"].includes(String(row.fulfillment_method)) ? String(row.fulfillment_method) : "") as SupplyOrder["fulfillmentMethod"],',
    '    fulfillmentNote: String(row.fulfillment_note || ""),',
    "    approvedByUserId: row.approved_by_user_id != null ? String(row.approved_by_user_id) : null,",
    "    approvedAt: row.approved_at ? String(row.approved_at) : null,",
    "    orderedAt: row.ordered_at ? String(row.ordered_at) : null,",
    "    receivedAt: row.received_at ? String(row.received_at) : null,",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// ---- Automation config (per owner) -----------------------------------------",
    "",
    "export async function getAutomationConfig(ownerId: string): Promise<AutomationConfig> {",
    "  if (!hasDatabase()) return { ...defaultConfig, ownerId };",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select owner_id, mode, auto_order_enabled, order_threshold_days,",
    "        max_order_amount, require_approval, approval_threshold",
    "      from supplier_order_automation_config where owner_id = ${ownerId} limit 1`;",
    "    if (!rows[0]) return { ...defaultConfig, ownerId };",
    "    const r = rows[0] as Record<string, unknown>;",
    "    return {",
    "      ownerId,",
    '      mode: (["manual", "auto", "conditional"].includes(String(r.mode)) ? String(r.mode) : "auto") as AutomationConfig["mode"],',
    '      autoOrderEnabled: r.auto_order_enabled === true || String(r.auto_order_enabled) === "true",',
    "      orderThresholdDays: n(r.order_threshold_days, 10),",
    "      maxOrderAmount: n(r.max_order_amount, 500),",
    '      requireApproval: r.require_approval === true || String(r.require_approval) === "true",',
    "      approvalThreshold: n(r.approval_threshold, 200)",
    "    };",
    "  } catch {",
    "    return { ...defaultConfig, ownerId };",
    "  }",
    "}",
    "",
    "export async function saveAutomationConfig(ownerId: string, input: Partial<AutomationConfig>): Promise<AutomationConfig> {",
    "  const current = await getAutomationConfig(ownerId);",
    "  const next: AutomationConfig = {",
    "    ownerId,",
    "    mode: input.mode || current.mode,",
    "    autoOrderEnabled: input.autoOrderEnabled ?? current.autoOrderEnabled,",
    "    orderThresholdDays: input.orderThresholdDays ?? current.orderThresholdDays,",
    "    maxOrderAmount: input.maxOrderAmount ?? current.maxOrderAmount,",
    "    requireApproval: input.requireApproval ?? current.requireApproval,",
    "    approvalThreshold: input.approvalThreshold ?? current.approvalThreshold",
    "  };",
    "  if (!hasDatabase()) return next;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      insert into supplier_order_automation_config (",
    "        owner_id, mode, auto_order_enabled, order_threshold_days,",
    "        max_order_amount, require_approval, approval_threshold",
    "      ) values (",
    "        ${ownerId}, ${next.mode}, ${next.autoOrderEnabled}, ${next.orderThresholdDays},",
    "        ${next.maxOrderAmount}, ${next.requireApproval}, ${next.approvalThreshold}",
    "      )",
    "      on conflict (owner_id) do update set",
    "        mode = excluded.mode,",
    "        auto_order_enabled = excluded.auto_order_enabled,",
    "        order_threshold_days = excluded.order_threshold_days,",
    "        max_order_amount = excluded.max_order_amount,",
    "        require_approval = excluded.require_approval,",
    "        approval_threshold = excluded.approval_threshold`;",
    "    return next;",
    "  } catch {",
    "    return next;",
    "  }",
    "}",
    "",
    "// ---- Suppliers -------------------------------------------------------------",
    "",
    "export async function listSuppliers(ownerId: string): Promise<Supplier[]> {",
    "  if (!hasDatabase()) return fallbackSuppliers;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, name, contact_name, email, phone, priority, enabled,",
    "        notes, unit_price, retail_price, order_method, supports_automatic_ordering,",
    "        portal_url, created_at",
    "      from supplier_order_automation_suppliers",
    "      where owner_id = ${ownerId}",
    "      order by priority asc, name asc`;",
    "    return rows.map(rowToSupplier);",
    "  } catch {",
    "    return fallbackSuppliers;",
    "  }",
    "}",
    "",
    "export async function getSupplier(id: string, ownerId: string): Promise<Supplier | null> {",
    "  if (!hasDatabase()) return fallbackSuppliers.find((s) => s.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, name, contact_name, email, phone, priority, enabled,",
    "        notes, unit_price, retail_price, order_method, supports_automatic_ordering,",
    "        portal_url, created_at",
    "      from supplier_order_automation_suppliers",
    "      where id = ${id} and owner_id = ${ownerId} limit 1`;",
    "    return rows[0] ? rowToSupplier(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SupplierInput = {",
    "  name: string;",
    "  contactName?: string;",
    "  email: string;",
    "  phone?: string;",
    "  priority?: number;",
    "  enabled?: boolean;",
    "  notes?: string;",
    "  unitPrice?: number;",
    "  retailPrice?: number | null;",
    '  orderMethod?: "api" | "portal" | "email";',
    "  supportsAutomaticOrdering?: boolean;",
    "  portalUrl?: string;",
    "};",
    "",
    "// Add a supplier, ported from SupplierIntegration.tsx handleAddSupplier.",
    "export async function createSupplier(ownerId: string, input: SupplierInput): Promise<Supplier | null> {",
    "  if (!hasDatabase()) return null;",
    '  const orderMethod = input.orderMethod && ["api", "portal", "email"].includes(input.orderMethod) ? input.orderMethod : "email";',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into supplier_order_automation_suppliers (",
    "        owner_id, name, contact_name, email, phone, priority, enabled, notes,",
    "        unit_price, retail_price, order_method, supports_automatic_ordering, portal_url",
    "      ) values (",
    '        ${ownerId}, ${input.name}, ${input.contactName || ""}, ${input.email},',
    '        ${input.phone || ""}, ${input.priority ?? 1}, ${input.enabled !== false},',
    '        ${input.notes || ""}, ${input.unitPrice ?? 0}, ${input.retailPrice ?? null},',
    "        ${orderMethod}, ${input.supportsAutomaticOrdering === true}, ${input.portalUrl || ''}",
    "      )",
    "      returning id, owner_id, name, contact_name, email, phone, priority, enabled,",
    "        notes, unit_price, retail_price, order_method, supports_automatic_ordering,",
    "        portal_url, created_at`;",
    "    return rows[0] ? rowToSupplier(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Toggle enabled / change priority, ported from handleUpdateSupplier.",
    "export async function updateSupplier(id: string, ownerId: string, updates: Partial<SupplierInput>): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    // Whitelisted, individually-guarded updates — no dynamic identifiers.",
    "    if (updates.enabled !== undefined) {",
    "      await sql`update supplier_order_automation_suppliers set enabled = ${updates.enabled} where id = ${id} and owner_id = ${ownerId}`;",
    "    }",
    "    if (updates.priority !== undefined) {",
    "      await sql`update supplier_order_automation_suppliers set priority = ${updates.priority} where id = ${id} and owner_id = ${ownerId}`;",
    "    }",
    "    if (updates.unitPrice !== undefined) {",
    "      await sql`update supplier_order_automation_suppliers set unit_price = ${updates.unitPrice} where id = ${id} and owner_id = ${ownerId}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Vendor price comparison / supplier selection --------------------------",
    "// Ported from supplier-service.ts findDefaultSupplier: among ACTIVE (enabled)",
    "// suppliers, pick the lowest unit price; build the ported reason string including",
    "// the savings-vs-retail note when a retail price is on file.",
    "",
    "export type SupplierChoice = {",
    "  supplierId: string;",
    "  supplierName: string;",
    "  unitPrice: number;",
    "  reason: string;",
    "};",
    "",
    "export function compareSuppliers(suppliers: Supplier[]): SupplierChoice[] {",
    "  return suppliers",
    "    .filter((s) => s.enabled)",
    "    .slice()",
    "    .sort((a, b) => a.unitPrice - b.unitPrice || a.priority - b.priority)",
    "    .map((s) => {",
    "      const savings = s.retailPrice != null ? s.retailPrice - s.unitPrice : 0;",
    "      // Ported verbatim from findDefaultSupplier's reason string.",
    "      const reason = `Lowest price: $${s.unitPrice.toFixed(2)}${savings > 0 ? ` (saves $${savings.toFixed(2)} vs retail)` : \"\"}`;",
    "      return { supplierId: s.id, supplierName: s.name, unitPrice: s.unitPrice, reason };",
    "    });",
    "}",
    "",
    "// selectSupplierForOrder, ported from supplier-service.ts: prefer the highest-",
    "// priority enabled supplier; the lowest-price comparison drives the tie/order.",
    "export function selectSupplier(suppliers: Supplier[]): SupplierChoice | null {",
    "  const ranked = compareSuppliers(suppliers);",
    "  return ranked[0] || null;",
    "}",
    "",
    "// ---- Orders: forecast -> create -> approve -> fulfill -> reconcile ----------",
    "",
    "export async function listOrders(ownerId: string, status?: SupplyOrder[\"status\"]): Promise<SupplyOrder[]> {",
    "  if (!hasDatabase()) return status ? fallbackOrders.filter((o) => o.status === status) : fallbackOrders;",
    "  try {",
    "    const sql = getDatabase();",
    "    const st = status || null;",
    "    const rows = await sql`",
    "      select id, owner_id, supplier_id, supplier_name, item_name, quantity,",
    "        unit_price, total_amount, status, trigger_reason, fulfillment_method,",
    "        fulfillment_note, approved_by_user_id, approved_at, ordered_at,",
    "        received_at, created_at",
    "      from supplier_order_automation_orders",
    "      where owner_id = ${ownerId}",
    "        and (${st}::text is null or status = ${st})",
    "      order by created_at desc`;",
    "    return rows.map(rowToOrder);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function getOrder(id: string, ownerId: string): Promise<SupplyOrder | null> {",
    "  if (!hasDatabase()) return fallbackOrders.find((o) => o.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, supplier_id, supplier_name, item_name, quantity,",
    "        unit_price, total_amount, status, trigger_reason, fulfillment_method,",
    "        fulfillment_note, approved_by_user_id, approved_at, ordered_at,",
    "        received_at, created_at",
    "      from supplier_order_automation_orders",
    "      where id = ${id} and owner_id = ${ownerId} limit 1`;",
    "    return rows[0] ? rowToOrder(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateOrderRequest = {",
    "  itemName: string;",
    "  quantity: number;",
    "  daysRemaining?: number;",
    "  triggerReason?: string;",
    "  // Optional explicit supplier; otherwise the lowest-price enabled one is chosen.",
    "  supplierId?: string;",
    "};",
    "",
    "export type CreateOrderResult = {",
    "  order: SupplyOrder | null;",
    '  action: "created_pending" | "created_approved" | "skipped" | "failed";',
    "  reason: string;",
    "};",
    "",
    "// createOrder, ported from OrderAutomationService.createOrder: pick a supplier",
    "// (lowest price), price the order, apply automation mode (manual -> pending;",
    "// auto/conditional -> approved), and force pending-review when the total exceeds",
    "// the owner's max/approval thresholds (ported from the pricing-error + max-amount",
    "// approval logic in AutoOrderSettings + createOrder).",
    "export async function createOrder(ownerId: string, request: CreateOrderRequest): Promise<CreateOrderResult> {",
    "  const config = await getAutomationConfig(ownerId);",
    "  if (!config.autoOrderEnabled && !request.supplierId) {",
    '    return { order: null, action: "skipped", reason: "Automatic ordering is turned off." };',
    "  }",
    "  const suppliers = await listSuppliers(ownerId);",
    "  const chosen = request.supplierId",
    "    ? compareSuppliers(suppliers).find((c) => c.supplierId === request.supplierId) || null",
    "    : selectSupplier(suppliers);",
    "  if (!chosen) {",
    '    return { order: null, action: "failed", reason: "No enabled supplier available for this item." };',
    "  }",
    "  const quantity = Math.max(1, Math.floor(request.quantity || 1));",
    "  const unitPrice = chosen.unitPrice;",
    "  const totalAmount = Number((unitPrice * quantity).toFixed(2));",
    "",
    "  // Auto-approve rule ported from shouldAutoApprove; approval-threshold + max-order",
    "  // rule ported from AutoOrderSettings.requireApproval/approvalThreshold/maxOrderAmount.",
    "  let autoApprove = shouldAutoApprove(config.mode);",
    "  let reason = autoApprove ? \"Order auto-approved and ready to place\" : \"Order created and awaiting approval\";",
    "  if (autoApprove && config.requireApproval && totalAmount > config.approvalThreshold) {",
    "    autoApprove = false;",
    "    reason = `Order created but needs approval: $${totalAmount.toFixed(2)} exceeds the $${config.approvalThreshold.toFixed(2)} approval threshold`;",
    "  }",
    "  if (autoApprove && totalAmount > config.maxOrderAmount) {",
    "    autoApprove = false;",
    "    reason = `Order created but needs approval: $${totalAmount.toFixed(2)} exceeds the $${config.maxOrderAmount.toFixed(2)} max auto-order amount`;",
    "  }",
    "",
    '  const triggerReason = request.triggerReason || (request.daysRemaining != null ? `Forecast: ${request.daysRemaining} days remaining` : "Manual order");',
    "  if (!hasDatabase()) {",
    '    return { order: null, action: "failed", reason: "Connect a database to place orders." };',
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into supplier_order_automation_orders (",
    "        owner_id, supplier_id, supplier_name, item_name, quantity, unit_price,",
    "        total_amount, status, trigger_reason, approved_by_user_id, approved_at",
    "      ) values (",
    "        ${ownerId}, ${chosen.supplierId}, ${chosen.supplierName}, ${request.itemName},",
    "        ${quantity}, ${unitPrice}, ${totalAmount},",
    '        ${autoApprove ? "approved" : "pending"}, ${triggerReason},',
    "        null, ${autoApprove ? new Date().toISOString() : null}",
    "      )",
    "      returning id, owner_id, supplier_id, supplier_name, item_name, quantity,",
    "        unit_price, total_amount, status, trigger_reason, fulfillment_method,",
    "        fulfillment_note, approved_by_user_id, approved_at, ordered_at,",
    "        received_at, created_at`;",
    "    const order = rows[0] ? rowToOrder(rows[0]) : null;",
    "    return {",
    "      order,",
    '      action: autoApprove ? "created_approved" : "created_pending",',
    "      reason",
    "    };",
    "  } catch {",
    '    return { order: null, action: "failed", reason: "Could not save the order." };',
    "  }",
    "}",
    "",
    "// Run the forecast: for each need at/below the threshold, create an order per the",
    "// automation config. Ported from OrderAutomationService.createOrders batching +",
    "// AutoOrderSettings threshold gating.",
    "export async function runForecast(ownerId: string, forecasts: SupplyForecast[]): Promise<CreateOrderResult[]> {",
    "  const config = await getAutomationConfig(ownerId);",
    "  const results: CreateOrderResult[] = [];",
    "  for (const f of forecasts) {",
    "    if (f.daysRemaining > config.orderThresholdDays) {",
    '      results.push({ order: null, action: "skipped", reason: `${f.itemName}: ${f.daysRemaining} days left is above the ${config.orderThresholdDays}-day threshold` });',
    "      continue;",
    "    }",
    "    const urgency = forecastUrgency(f.daysRemaining, config.orderThresholdDays);",
    "    const result = await createOrder(ownerId, {",
    "      itemName: f.itemName,",
    "      quantity: Math.max(1, f.suggestedQuantity || 1),",
    "      daysRemaining: f.daysRemaining,",
    "      triggerReason: `Forecast: ${f.daysRemaining} days remaining (${urgency})`",
    "    });",
    "    results.push(result);",
    "  }",
    "  return results;",
    "}",
    "",
    "// Approve a pending order, ported from the createOrder approvedByUserId semantics",
    "// (a real userId here = manual approval, vs null = auto).",
    "export async function approveOrder(id: string, ownerId: string, approverUserId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      update supplier_order_automation_orders",
    "      set status = 'approved', approved_by_user_id = ${approverUserId}, approved_at = now()",
    "      where id = ${id} and owner_id = ${ownerId} and status = 'pending'`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Fulfill an approved order, ported from order-fulfillment-service.ts",
    "// processApprovedOrder: route by supplier capability — api + supportsAutomaticOrdering",
    "// -> automatic; portal/email -> a manual instruction note (ported from",
    "// handleManualOrder's portal/email task bodies) — then stamp the order 'ordered'.",
    "export async function fulfillOrder(id: string, ownerId: string): Promise<{ ok: boolean; message: string }> {",
    '  if (!hasDatabase()) return { ok: false, message: "Connect a database to fulfill orders." };',
    "  const order = await getOrder(id, ownerId);",
    '  if (!order) return { ok: false, message: "Order not found." };',
    '  if (order.status !== "approved") return { ok: false, message: "Only approved orders can be fulfilled." };',
    "  const supplier = order.supplierId ? await getSupplier(order.supplierId, ownerId) : null;",
    '  if (!supplier) return { ok: false, message: "Supplier for this order is unavailable." };',
    "",
    '  let method: SupplyOrder["fulfillmentMethod"] = supplier.orderMethod;',
    '  let note = "";',
    '  if (supplier.orderMethod === "api" && supplier.supportsAutomaticOrdering) {',
    "    // handleApiOrder: automatic placement.",
    '    method = "api";',
    "    note = `Automatically placed order via API for ${order.quantity}x ${order.itemName}.`;",
    '  } else if (supplier.orderMethod === "portal") {',
    "    // handleManualOrder portal branch (ported task body).",
    '    method = "portal";',
    "    note = `Place order via supplier portal at ${supplier.portalUrl || supplier.name}: ${order.quantity}x ${order.itemName}, est. $${order.totalAmount.toFixed(2)}.`;",
    "  } else {",
    "    // handleManualOrder email branch (ported task body).",
    '    method = "email";',
    "    note = `Send order email to ${supplier.email}: ${order.quantity}x ${order.itemName}, est. $${order.totalAmount.toFixed(2)}. Please confirm and provide tracking.`;",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      update supplier_order_automation_orders",
    "      set status = 'ordered', ordered_at = now(),",
    "        fulfillment_method = ${method}, fulfillment_note = ${note}",
    "      where id = ${id} and owner_id = ${ownerId} and status = 'approved'`;",
    "    return { ok: true, message: note };",
    "  } catch {",
    '    return { ok: false, message: "Could not fulfill the order." };',
    "  }",
    "}",
    "",
    "// Reconcile fulfillment: mark an ordered item received. Ported from the",
    "// order status flow's terminal transition (ordered -> received).",
    "export async function reconcileOrder(id: string, ownerId: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`",
    "      update supplier_order_automation_orders",
    "      set status = 'received', received_at = now()",
    "      where id = ${id} and owner_id = ${ownerId} and status = 'ordered'`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function supplierEnabled(): boolean {",
    '  return process.env.FEATURE_SUPPLIER !== "false";',
    "}"
  ]);
}

// ---- src/app/api/supplier-automation/route.ts (list + create supplier) -------

function supplierApiFile(): GeneratedModuleFile {
  return file("src/app/api/supplier-automation/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listSuppliers, compareSuppliers, createSupplier, supplierEnabled } from "@/lib/db/supplier-automation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false, message: "Supplier automation is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const suppliers = await listSuppliers(String(user!.id));",
    "  const comparison = compareSuppliers(suppliers);",
    "  return NextResponse.json({ ok: true, suppliers, comparison });",
    "}",
    "",
    "// Adding a supplier is an admin action (owner registry).",
    "export async function POST(request: Request) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const name = typeof body.name === "string" ? body.name.trim() : "";',
    '  const email = typeof body.email === "string" ? body.email.trim() : "";',
    "  if (name.length < 2 || !email.includes(\"@\")) {",
    '    return NextResponse.json({ ok: false, message: "A supplier name and a valid email are required." }, { status: 400 });',
    "  }",
    "  const created = await createSupplier(String(user.id), {",
    "    name,",
    "    email,",
    '    contactName: typeof body.contactName === "string" ? body.contactName : undefined,',
    '    phone: typeof body.phone === "string" ? body.phone : undefined,',
    '    priority: typeof body.priority === "number" ? body.priority : undefined,',
    "    enabled: body.enabled !== false,",
    '    notes: typeof body.notes === "string" ? body.notes : undefined,',
    '    unitPrice: typeof body.unitPrice === "number" ? body.unitPrice : undefined,',
    '    retailPrice: typeof body.retailPrice === "number" ? body.retailPrice : undefined,',
    '    orderMethod: body.orderMethod === "api" || body.orderMethod === "portal" ? body.orderMethod : "email",',
    "    supportsAutomaticOrdering: body.supportsAutomaticOrdering === true,",
    '    portalUrl: typeof body.portalUrl === "string" ? body.portalUrl : undefined',
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to add suppliers." }, { status: 503 });',
    "  return NextResponse.json({ ok: true, supplier: created });",
    "}"
  ]);
}

// ---- src/app/api/supplier-automation/config/route.ts (automation settings) ---

function configApiFile(): GeneratedModuleFile {
  return file("src/app/api/supplier-automation/config/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getAutomationConfig, saveAutomationConfig, supplierEnabled } from "@/lib/db/supplier-automation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const config = await getAutomationConfig(String(user!.id));",
    "  return NextResponse.json({ ok: true, config });",
    "}",
    "",
    "// Changing automation settings is an admin/owner action.",
    "export async function PUT(request: Request) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const config = await saveAutomationConfig(String(user.id), {",
    '    mode: body.mode === "manual" || body.mode === "conditional" || body.mode === "auto" ? body.mode : undefined,',
    '    autoOrderEnabled: typeof body.autoOrderEnabled === "boolean" ? body.autoOrderEnabled : undefined,',
    '    orderThresholdDays: typeof body.orderThresholdDays === "number" ? body.orderThresholdDays : undefined,',
    '    maxOrderAmount: typeof body.maxOrderAmount === "number" ? body.maxOrderAmount : undefined,',
    '    requireApproval: typeof body.requireApproval === "boolean" ? body.requireApproval : undefined,',
    '    approvalThreshold: typeof body.approvalThreshold === "number" ? body.approvalThreshold : undefined',
    "  });",
    "  return NextResponse.json({ ok: true, config });",
    "}"
  ]);
}

// ---- src/app/api/supplier-automation/orders/route.ts (list + create/forecast)-

function ordersApiFile(): GeneratedModuleFile {
  return file("src/app/api/supplier-automation/orders/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listOrders, createOrder, runForecast, supplierEnabled } from "@/lib/db/supplier-automation";',
    'import type { SupplyForecast, SupplyOrder } from "@/lib/db/supplier-automation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const statusParam = url.searchParams.get("status") || undefined;',
    '  const valid = ["pending", "approved", "ordered", "received", "skipped"];',
    "  const status = statusParam && valid.includes(statusParam) ? (statusParam as SupplyOrder[\"status\"]) : undefined;",
    "  const orders = await listOrders(String(user!.id), status);",
    "  return NextResponse.json({ ok: true, orders });",
    "}",
    "",
    "// Placing/forecasting orders is an admin/owner action.",
    "export async function POST(request: Request) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const ownerId = String(user.id);",
    "",
    "  // Forecast run: an array of supply needs -> one order per item at/below threshold.",
    "  if (Array.isArray(body.forecasts)) {",
    "    const forecasts: SupplyForecast[] = body.forecasts",
    "      .map((f) => f as Record<string, unknown>)",
    '      .filter((f) => typeof f.itemName === "string")',
    "      .map((f) => ({",
    "        itemName: String(f.itemName),",
    "        currentLevel: Number(f.currentLevel || 0),",
    "        daysRemaining: Number(f.daysRemaining || 0),",
    '        urgency: (f.urgency === "critical" || f.urgency === "low" ? f.urgency : "good") as SupplyForecast["urgency"],',
    "        suggestedQuantity: Number(f.suggestedQuantity || 1)",
    "      }));",
    "    const results = await runForecast(ownerId, forecasts);",
    "    return NextResponse.json({ ok: true, results });",
    "  }",
    "",
    "  // Single order.",
    '  const itemName = typeof body.itemName === "string" ? body.itemName.trim() : "";',
    '  if (itemName.length < 2) return NextResponse.json({ ok: false, message: "An item name is required." }, { status: 400 });',
    "  const result = await createOrder(ownerId, {",
    "    itemName,",
    '    quantity: typeof body.quantity === "number" ? body.quantity : 1,',
    '    daysRemaining: typeof body.daysRemaining === "number" ? body.daysRemaining : undefined,',
    '    supplierId: typeof body.supplierId === "string" ? body.supplierId : undefined',
    "  });",
    "  const failed = result.action === \"failed\";",
    "  return NextResponse.json({ ok: !failed, result }, { status: failed ? 400 : 200 });",
    "}"
  ]);
}

// ---- src/app/api/supplier-automation/orders/[id]/route.ts (approve/fulfill/receive)

function orderDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/supplier-automation/orders/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getOrder, approveOrder, fulfillOrder, reconcileOrder, supplierEnabled } from "@/lib/db/supplier-automation";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const order = await getOrder(id, String(user!.id));",
    '  if (!order) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, order });",
    "}",
    "",
    "// approve | fulfill | receive — the purchase/fulfillment/reconcile transitions.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!supplierEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const ownerId = String(user.id);",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "";',
    "",
    '  if (action === "approve") {',
    "    const ok = await approveOrder(id, ownerId, ownerId);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to approve orders." }, { status: 503 });',
    '    return NextResponse.json({ ok: true, message: "Order approved." });',
    "  }",
    '  if (action === "fulfill") {',
    "    const result = await fulfillOrder(id, ownerId);",
    "    return NextResponse.json({ ok: result.ok, message: result.message }, { status: result.ok ? 200 : 400 });",
    "  }",
    '  if (action === "receive") {',
    "    const ok = await reconcileOrder(id, ownerId);",
    '    if (!ok) return NextResponse.json({ ok: false, message: "Could not reconcile this order." }, { status: 400 });',
    '    return NextResponse.json({ ok: true, message: "Marked received." });',
    "  }",
    '  return NextResponse.json({ ok: false, message: "Unknown action." }, { status: 400 });',
    "}"
  ]);
}

// ---- src/app/supply/page.tsx (main: forecast + comparison + queue) ----------

function mainPageFile(): GeneratedModuleFile {
  return file("src/app/supply/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import {',
    "  listSuppliers,",
    "  compareSuppliers,",
    "  listOrders,",
    "  getAutomationConfig,",
    "  automationModeDescription,",
    "  supplierEnabled",
    '} from "@/lib/db/supplier-automation";',
    'import { RunForecastPanel } from "./run-forecast";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SupplyPage() {",
    "  if (!supplierEnabled()) {",
    '    return (<main className="shell"><h1>Supply</h1><p>Supply automation is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/supply");',
    "  const user = await getCurrentUser();",
    "  const ownerId = String(user!.id);",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const [suppliers, orders, config] = await Promise.all([",
    "    listSuppliers(ownerId),",
    "    listOrders(ownerId),",
    "    getAutomationConfig(ownerId)",
    "  ]);",
    "  const comparison = compareSuppliers(suppliers);",
    "  const pending = orders.filter((o) => o.status === \"pending\");",
    "  const open = orders.filter((o) => o.status === \"approved\" || o.status === \"ordered\");",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Supply</p>',
    "      <h1>Supply &amp; ordering</h1>",
    "      <p>Forecast what you are about to run out of, compare vendor pricing, place orders on the best terms, and track them through to delivery.</p>",
    "",
    '      <section className="panel">',
    "        <p className=\"eyebrow\">Automation</p>",
    "        <p><strong>{automationModeDescription(config.mode)}</strong></p>",
    "        <p className=\"note\">Reorder when an item drops below {config.orderThresholdDays} days remaining. Auto-order {config.autoOrderEnabled ? \"on\" : \"off\"}; max auto-order ${config.maxOrderAmount.toFixed(2)}.</p>",
    "        {isAdmin ? <p><Link className=\"button\" href=\"/supply/settings\">Automation settings</Link></p> : null}",
    "      </section>",
    "",
    "      <h2>Best vendor pricing</h2>",
    "      {comparison.length === 0 ? (",
    '        <p className="note">No active suppliers yet. {isAdmin ? "Add one to start comparing prices." : "Ask an admin to add suppliers."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {comparison.map((c, i) => (",
    '            <div className="wide-card" key={c.supplierId}>',
    "              <span>{i === 0 ? \"Best price\" : `Option ${i + 1}`}</span>",
    "              <strong>{c.supplierName}</strong>",
    '              <p className="note">{c.reason}</p>',
    "            </div>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/supply/suppliers">Manage suppliers</Link></p>',
    "",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Run the forecast</h2>",
    "          <p>Enter what is running low. Items at or below your {config.orderThresholdDays}-day threshold become orders automatically.</p>",
    "          <RunForecastPanel thresholdDays={config.orderThresholdDays} />",
    "        </>",
    "      ) : null}",
    "",
    "      <h2>Order queue</h2>",
    "      {orders.length === 0 ? (",
    '        <p className="note">No orders yet.</p>',
    "      ) : (",
    "        <>",
    "          {pending.length > 0 ? <p className=\"note\">{pending.length} awaiting approval · {open.length} in progress</p> : null}",
    '          <section className="panel-list">',
    "            {orders.map((o) => (",
    '              <Link className="wide-card" key={o.id} href={`/supply/orders/${o.id}`}>',
    "                <span>{o.status}</span>",
    "                <strong>{o.quantity}x {o.itemName}</strong>",
    '                <p className="note">{o.supplierName} · ${o.totalAmount.toFixed(2)} · {o.triggerReason}</p>',
    "              </Link>",
    "            ))}",
    "          </section>",
    "        </>",
    "      )}",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/run-forecast.tsx (client) ------------------------------

function runForecastFormFile(): GeneratedModuleFile {
  return file("src/app/supply/run-forecast.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Row = { itemName: string; daysRemaining: string; suggestedQuantity: string };",
    "",
    "export function RunForecastPanel({ thresholdDays }: { thresholdDays: number }) {",
    "  const router = useRouter();",
    '  const [rows, setRows] = useState<Row[]>([{ itemName: "", daysRemaining: "", suggestedQuantity: "1" }]);',
    '  const [status, setStatus] = useState<"idle" | "running" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  function update(i: number, key: keyof Row, value: string) {",
    "    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, [key]: value } : r)));",
    "  }",
    "",
    "  function addRow() {",
    '    setRows((prev) => [...prev, { itemName: "", daysRemaining: "", suggestedQuantity: "1" }]);',
    "  }",
    "",
    "  async function run(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("running");',
    '    setMessage("");',
    "    const forecasts = rows",
    "      .filter((r) => r.itemName.trim())",
    "      .map((r) => ({",
    "        itemName: r.itemName.trim(),",
    "        daysRemaining: Number(r.daysRemaining || 0),",
    "        suggestedQuantity: Number(r.suggestedQuantity || 1)",
    "      }));",
    "    if (forecasts.length === 0) {",
    '      setStatus("error");',
    '      setMessage("Add at least one item.");',
    "      return;",
    "    }",
    "    try {",
    '      const response = await fetch("/api/supplier-automation/orders", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ forecasts })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not run the forecast.");',
    "        return;",
    "      }",
    "      const created = (data.results || []).filter((r: { action: string }) => r.action !== \"skipped\").length;",
    '      setStatus("idle");',
    "      setMessage(`Forecast complete — ${created} order(s) created.`);",
    '      setRows([{ itemName: "", daysRemaining: "", suggestedQuantity: "1" }]);',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={run}>',
    "      {rows.map((r, i) => (",
    '        <div className="stack" key={i}>',
    '          <input className="input" value={r.itemName} onChange={(e) => update(i, "itemName", e.target.value)} placeholder="Item (e.g. Black Toner HP 26X)" aria-label="Item name" />',
    '          <input className="input" type="number" value={r.daysRemaining} onChange={(e) => update(i, "daysRemaining", e.target.value)} placeholder={`Days remaining (threshold ${thresholdDays})`} aria-label="Days remaining" />',
    '          <input className="input" type="number" min="1" value={r.suggestedQuantity} onChange={(e) => update(i, "suggestedQuantity", e.target.value)} placeholder="Quantity" aria-label="Quantity" />',
    "        </div>",
    "      ))}",
    '      <button className="button" type="button" onClick={addRow}>Add another item</button>',
    '      {message ? <p className="note" role={status === "error" ? "alert" : "status"}>{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "running"}>',
    '        {status === "running" ? "Running…" : "Run forecast"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/suppliers/page.tsx (supplier registry) -----------------

function suppliersPageFile(): GeneratedModuleFile {
  return file("src/app/supply/suppliers/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listSuppliers, supplierEnabled } from "@/lib/db/supplier-automation";',
    'import { AddSupplierForm } from "./add-supplier";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SuppliersPage() {",
    "  if (!supplierEnabled()) {",
    '    return (<main className="shell"><h1>Suppliers</h1><p>Supply automation is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/supply/suppliers");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const suppliers = await listSuppliers(String(user!.id));",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Supply</p>',
    "      <h1>Suppliers</h1>",
    "      <p>Your vendors, ranked by priority. When something runs low, the lowest-priced active vendor is chosen automatically.</p>",
    "      {suppliers.length === 0 ? (",
    '        <p className="note">No suppliers yet.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {suppliers.map((s) => (",
    '            <article className="wide-card" key={s.id}>',
    "              <span>{s.enabled ? \"Active\" : \"Inactive\"} · priority {s.priority}</span>",
    "              <strong>{s.name}</strong>",
    '              <p className="note">{s.contactName || s.email} · ${s.unitPrice.toFixed(2)}/unit{s.retailPrice != null ? ` (retail $${s.retailPrice.toFixed(2)})` : ""}</p>',
    "              <p className=\"note\">Orders via {s.orderMethod}{s.orderMethod === \"api\" && s.supportsAutomaticOrdering ? \" (automatic)\" : \"\"}{s.notes ? ` · ${s.notes}` : \"\"}</p>",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    "      {isAdmin ? (",
    "        <>",
    "          <h2>Add a supplier</h2>",
    "          <AddSupplierForm />",
    "        </>",
    "      ) : (",
    '        <p className="note">Only admins can add suppliers.</p>',
    "      )}",
    '      <p><Link className="button" href="/supply">Back to supply</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/suppliers/add-supplier.tsx (client) --------------------

function addSupplierFormFile(): GeneratedModuleFile {
  return file("src/app/supply/suppliers/add-supplier.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function AddSupplierForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/supplier-automation", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          name: form.get("name"),',
    '          contactName: form.get("contactName"),',
    '          email: form.get("email"),',
    '          phone: form.get("phone"),',
    '          priority: Number(form.get("priority") || 1),',
    '          unitPrice: Number(form.get("unitPrice") || 0),',
    '          retailPrice: form.get("retailPrice") ? Number(form.get("retailPrice")) : undefined,',
    '          orderMethod: form.get("orderMethod"),',
    '          supportsAutomaticOrdering: form.get("supportsAutomaticOrdering") === "on",',
    '          portalUrl: form.get("portalUrl"),',
    '          notes: form.get("notes"),',
    '          enabled: form.get("enabled") !== "off"',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not add the supplier.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Supplier added.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    "        <p>{message}</p>",
    '        <button className="button" type="button" onClick={() => setStatus("idle")}>Add another</button>',
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="name" placeholder="Supplier name" aria-label="Supplier name" required />',
    '      <input className="input" name="contactName" placeholder="Contact name (optional)" aria-label="Contact name" />',
    '      <input className="input" type="email" name="email" placeholder="Orders email" aria-label="Orders email" required />',
    '      <input className="input" name="phone" placeholder="Phone (optional)" aria-label="Phone" />',
    '      <input className="input" type="number" name="priority" min="1" defaultValue="1" placeholder="Priority (1 = highest)" aria-label="Priority" />',
    '      <input className="input" type="number" name="unitPrice" min="0" step="0.01" placeholder="Unit price" aria-label="Unit price" />',
    '      <input className="input" type="number" name="retailPrice" min="0" step="0.01" placeholder="Retail price (optional, for savings)" aria-label="Retail price" />',
    '      <select className="input" name="orderMethod" aria-label="Order method" defaultValue="email">',
    '        <option value="email">Order by email</option>',
    '        <option value="portal">Order via portal</option>',
    '        <option value="api">Order via API</option>',
    "      </select>",
    '      <input className="input" name="portalUrl" placeholder="Portal URL (optional)" aria-label="Portal URL" />',
    '      <label className="check"><input type="checkbox" name="supportsAutomaticOrdering" /> API supplier supports automatic ordering</label>',
    '      <textarea className="input" name="notes" rows={2} placeholder="Notes (optional)" aria-label="Notes" />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Add supplier"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/orders/[id]/page.tsx (order detail + actions) ----------

function orderDetailPageFile(): GeneratedModuleFile {
  return file("src/app/supply/orders/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getOrder, supplierEnabled } from "@/lib/db/supplier-automation";',
    'import { OrderActions } from "./order-actions";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!supplierEnabled()) {",
    '    return (<main className="shell"><h1>Order</h1><p>Supply automation is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/supply");',
    "  const user = await getCurrentUser();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const { id } = await params;",
    "  const order = await getOrder(id, String(user!.id));",
    "  if (!order) notFound();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{order.status}</p>',
    "      <h1>{order.quantity}x {order.itemName}</h1>",
    '      <p className="note">{order.supplierName} · ${order.totalAmount.toFixed(2)} (${order.unitPrice.toFixed(2)}/unit)</p>',
    "      <p>{order.triggerReason}</p>",
    "      {order.approvedByUserId === null && (order.status !== \"pending\") ? (",
    '        <p className="note">Auto-approved by the automation rules.</p>',
    "      ) : null}",
    "      {order.fulfillmentNote ? (",
    '        <section className="panel">',
    "          <p className=\"eyebrow\">Fulfillment ({order.fulfillmentMethod || \"pending\"})</p>",
    "          <p>{order.fulfillmentNote}</p>",
    "        </section>",
    "      ) : null}",
    '      <section className="panel">',
    "        <p className=\"eyebrow\">Timeline</p>",
    "        <p className=\"note\">Created {order.createdAt || \"—\"}</p>",
    "        {order.approvedAt ? <p className=\"note\">Approved {order.approvedAt}</p> : null}",
    "        {order.orderedAt ? <p className=\"note\">Ordered {order.orderedAt}</p> : null}",
    "        {order.receivedAt ? <p className=\"note\">Received {order.receivedAt}</p> : null}",
    "      </section>",
    "      {isAdmin ? <OrderActions id={order.id} status={order.status} /> : null}",
    '      <p><Link className="button" href="/supply">Back to supply</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/orders/[id]/order-actions.tsx (client) -----------------

function orderActionsFile(): GeneratedModuleFile {
  return file("src/app/supply/orders/[id]/order-actions.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function OrderActions({ id, status }: { id: string; status: string }) {",
    "  const router = useRouter();",
    '  const [busy, setBusy] = useState(false);',
    '  const [message, setMessage] = useState<string>("");',
    '  const [isError, setIsError] = useState(false);',
    "",
    "  async function act(action: string) {",
    "    setBusy(true);",
    '    setMessage("");',
    "    setIsError(false);",
    "    try {",
    "      const response = await fetch(`/api/supplier-automation/orders/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ action })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    "        setIsError(true);",
    '        setMessage(data.message || "That did not work.");',
    "        return;",
    "      }",
    '      setMessage(data.message || "Done.");',
    "      router.refresh();",
    "    } catch {",
    "      setIsError(true);",
    '      setMessage("Could not reach the server.");',
    "    } finally {",
    "      setBusy(false);",
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      {status === "pending" ? (',
    '        <button className="button primary" type="button" onClick={() => act("approve")} disabled={busy}>Approve order</button>',
    "      ) : null}",
    '      {status === "approved" ? (',
    '        <button className="button primary" type="button" onClick={() => act("fulfill")} disabled={busy}>Place order with supplier</button>',
    "      ) : null}",
    '      {status === "ordered" ? (',
    '        <button className="button primary" type="button" onClick={() => act("receive")} disabled={busy}>Mark received</button>',
    "      ) : null}",
    '      {message ? <p className="note" role={isError ? "alert" : "status"}>{message}</p> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/settings/page.tsx (automation settings) ----------------
// Ported from AutoOrderSettings.tsx (auto-order toggle, threshold, max amount,
// require-approval, approval threshold) plus the automation mode.

function settingsPageFile(): GeneratedModuleFile {
  return file("src/app/supply/settings/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getAutomationConfig, supplierEnabled } from "@/lib/db/supplier-automation";',
    'import { AutomationSettingsForm } from "./settings-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function SupplySettingsPage() {",
    "  if (!supplierEnabled()) {",
    '    return (<main className="shell"><h1>Settings</h1><p>Supply automation is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/supply/settings");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Settings</h1><p className="note">Automation settings are for admins only.</p></main>);',
    "  }",
    "  const config = await getAutomationConfig(String(user!.id));",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Auto-order settings</h1>",
    "      <p>Control how orders are created and approved when supply runs low.</p>",
    "      <AutomationSettingsForm config={config} />",
    '      <p><Link className="button" href="/supply">Back to supply</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/supply/settings/settings-form.tsx (client) --------------------

function settingsFormFile(): GeneratedModuleFile {
  return file("src/app/supply/settings/settings-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "type Config = {",
    '  mode: "manual" | "auto" | "conditional";',
    "  autoOrderEnabled: boolean;",
    "  orderThresholdDays: number;",
    "  maxOrderAmount: number;",
    "  requireApproval: boolean;",
    "  approvalThreshold: number;",
    "};",
    "",
    "export function AutomationSettingsForm({ config }: { config: Config }) {",
    "  const router = useRouter();",
    "  const [form, setForm] = useState<Config>(config);",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  function set<K extends keyof Config>(key: K, value: Config[K]) {",
    "    setForm((prev) => ({ ...prev, [key]: value }));",
    "  }",
    "",
    "  async function save(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/supplier-automation/config", {',
    '        method: "PUT",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify(form)",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not save settings.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Settings saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={save}>',
    '      <label className="field">',
    "        Automation mode",
    '        <select className="input" value={form.mode} onChange={(e) => set("mode", e.target.value as Config["mode"])} aria-label="Automation mode">',
    '          <option value="manual">Manual — approve every order</option>',
    '          <option value="auto">Auto — approve and order automatically</option>',
    '          <option value="conditional">Conditional — auto unless already on hand</option>',
    "        </select>",
    "      </label>",
    '      <label className="check"><input type="checkbox" checked={form.autoOrderEnabled} onChange={(e) => set("autoOrderEnabled", e.target.checked)} /> Enable automatic ordering</label>',
    '      <label className="field">',
    "        Reorder threshold (days remaining)",
    '        <input className="input" type="number" min="1" max="60" value={form.orderThresholdDays} onChange={(e) => set("orderThresholdDays", Number(e.target.value))} aria-label="Order threshold days" />',
    "      </label>",
    '      <label className="field">',
    "        Max auto-order amount ($)",
    '        <input className="input" type="number" min="0" step="50" value={form.maxOrderAmount} onChange={(e) => set("maxOrderAmount", Number(e.target.value))} aria-label="Max order amount" />',
    "      </label>",
    '      <label className="check"><input type="checkbox" checked={form.requireApproval} onChange={(e) => set("requireApproval", e.target.checked)} /> Require approval for large orders</label>',
    "      {form.requireApproval ? (",
    '        <label className="field">',
    "          Approval threshold ($)",
    '          <input className="input" type="number" min="0" step="25" value={form.approvalThreshold} onChange={(e) => set("approvalThreshold", Number(e.target.value))} aria-label="Approval threshold" />',
    "        </label>",
    "      ) : null}",
    '      {message ? <p className="note" role={status === "error" ? "alert" : "status"}>{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Save settings"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

export const supplierAutomationModule: AppModule = {
  slug: "supplier-order-automation",
  name: "Supplier Order Automation",
  tier: "optional",
  featureFlagEnv: "FEATURE_SUPPLIER",
  files: () => [
    supplierLibFile(),
    supplierApiFile(),
    configApiFile(),
    ordersApiFile(),
    orderDetailApiFile(),
    mainPageFile(),
    runForecastFormFile(),
    suppliersPageFile(),
    addSupplierFormFile(),
    orderDetailPageFile(),
    orderActionsFile(),
    settingsPageFile(),
    settingsFormFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists supplier_order_automation_suppliers (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  name text not null default '',",
      "  contact_name text not null default '',",
      "  email text not null default '',",
      "  phone text not null default '',",
      "  priority integer not null default 1,",
      "  enabled boolean not null default true,",
      "  notes text not null default '',",
      "  unit_price numeric(12,2) not null default 0,",
      "  retail_price numeric(12,2),",
      "  order_method text not null default 'email',",
      "  supports_automatic_ordering boolean not null default false,",
      "  portal_url text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists supplier_order_automation_suppliers_owner_idx on supplier_order_automation_suppliers (owner_id);",
      "create index if not exists supplier_order_automation_suppliers_priority_idx on supplier_order_automation_suppliers (owner_id, priority);",
      "",
      "create table if not exists supplier_order_automation_config (",
      "  owner_id uuid primary key references users(id) on delete cascade,",
      "  mode text not null default 'auto',",
      "  auto_order_enabled boolean not null default true,",
      "  order_threshold_days integer not null default 10,",
      "  max_order_amount numeric(12,2) not null default 500,",
      "  require_approval boolean not null default false,",
      "  approval_threshold numeric(12,2) not null default 200",
      ");",
      "",
      "create table if not exists supplier_order_automation_orders (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete cascade,",
      "  supplier_id uuid references supplier_order_automation_suppliers(id) on delete set null,",
      "  supplier_name text not null default '',",
      "  item_name text not null default '',",
      "  quantity integer not null default 1,",
      "  unit_price numeric(12,2) not null default 0,",
      "  total_amount numeric(12,2) not null default 0,",
      "  status text not null default 'pending',",
      "  trigger_reason text not null default '',",
      "  fulfillment_method text not null default '',",
      "  fulfillment_note text not null default '',",
      "  approved_by_user_id uuid references users(id) on delete set null,",
      "  approved_at timestamptz,",
      "  ordered_at timestamptz,",
      "  received_at timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists supplier_order_automation_orders_owner_idx on supplier_order_automation_orders (owner_id);",
      "create index if not exists supplier_order_automation_orders_status_idx on supplier_order_automation_orders (owner_id, status);",
      "create index if not exists supplier_order_automation_orders_created_idx on supplier_order_automation_orders (created_at desc);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "-- Seed depends on an existing user id; run once you have an owner. Left as a",
      "-- no-op template so a fresh DB stays clean (suppliers are per-owner).",
      "-- insert into supplier_order_automation_suppliers (owner_id, name, contact_name, email, phone, priority, enabled, notes, unit_price, retail_price, order_method)",
      "-- values ('<owner-uuid>', '123inkjets.com', 'Sales Team', 'orders@123inkjets.com', '1-800-123-4567', 1, true, 'Compatible specialist - good prices', 42.50, 79.99, 'email');"
    ].join("\n"),
  envLines: () => [
    "",
    "# Supplier Order Automation — set to false to switch forecasting + vendor",
    "# comparison + auto-ordering + fulfillment off.",
    "FEATURE_SUPPLIER=true"
  ],
  requiredEnv: [],
  homeLinks: () => ['        <a className="button" href="/supply">Supply &amp; ordering</a>'],
  navLinks: () => [{ href: "/supply", label: "Supply" }]
};