// testimony-engine — capture, store, surface, and review real stories, then close
// the loop from a solved problem back to a testimony. Ported from ChurchConnect's
// real testimony system (backend/routes/testimonies.py):
//   - the testimony model (id, member_name, member_email, title, summary,
//     full_story, video_url + extract_youtube_id/thumbnail derivation, category,
//     tags, is_approved [defaults FALSE — requires review], is_public,
//     is_anonymous, is_featured, view_count, like_count, created_at,
//     follow_up_scheduled).
//   - GET /api/testimonies filtering (category, is_approved, is_public, search
//     across title/summary/tags), newest-first.
//   - GET /api/testimonies/featured and /matching/{category} (others-found-hope).
//   - POST /api/testimonies create_testimony (defaults is_approved=false, derives
//     youtube id + hqdefault thumbnail, schedules a 30-day follow-up when an email
//     is given and the story isn't anonymous — schedule_testimony_follow_up).
//   - POST /api/testimonies/{id}/view and /like counter bumps.
//   - the admin review/approval queue (is_approved gate) that solicit + approve
//     flows hang off of.
// Generalized off the church framing into plain, warm copy so it drops into any
// app. Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_TESTIMONY); customers read approved stories + submit,
// admins review/approve/feature.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/testimony.ts (model + queries, ported from testimonies.py) ---

function testimonyLibFile(): GeneratedModuleFile {
  return file("src/lib/db/testimony.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A testimony record, ported from testimonies.py create_testimony. Stories are",
    "// captured unapproved (isApproved=false) and only surface publicly once an admin",
    "// reviews them — that review/approval queue is the loop-closer.",
    "export type Testimony = {",
    "  id: string;",
    "  authorId: string | null;",
    "  authorName: string;",
    "  authorEmail: string;",
    "  title: string;",
    "  summary: string;",
    "  fullStory: string;",
    "  videoUrl: string;",
    "  youtubeVideoId: string;",
    "  thumbnailUrl: string;",
    "  category: string;",
    "  tags: string[];",
    "  isApproved: boolean;",
    "  isPublic: boolean;",
    "  isAnonymous: boolean;",
    "  isFeatured: boolean;",
    "  viewCount: number;",
    "  likeCount: number;",
    "  followUpScheduled: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "export type TestimonyFilters = {",
    "  category?: string;",
    "  search?: string;",
    "  isApproved?: boolean;",
    "  isPublic?: boolean;",
    "  limit?: number;",
    "};",
    "",
    "// The categories a story can be filed under (ported in spirit from the church",
    "// system's crisis + growth categories, generalized to any app's problem space).",
    "export const TESTIMONY_CATEGORIES = [",
    '  "breakthrough",',
    '  "recovery",',
    '  "grief",',
    '  "mental-health",',
    '  "relationships",',
    '  "provision",',
    '  "other"',
    "];",
    "",
    "export function displayName(t: Pick<Testimony, \"authorName\" | \"isAnonymous\">): string {",
    '  return t.isAnonymous ? "Anonymous" : (t.authorName || "Anonymous");',
    "}",
    "",
    "// Extract a YouTube video id from the common URL shapes, ported verbatim from",
    "// testimonies.py extract_youtube_id (watch?v=, youtu.be/, /embed/, bare 11-char id).",
    "export function extractYoutubeId(url: string): string {",
    '  if (!url) return "";',
    "  const patterns = [",
    "    /(?:youtube\\.com\\/watch\\?v=|youtu\\.be\\/|youtube\\.com\\/embed\\/)([^&\\n?#]+)/,",
    "    /^([a-zA-Z0-9_-]{11})$/",
    "  ];",
    "  for (const pattern of patterns) {",
    "    const match = url.match(pattern);",
    "    if (match && match[1]) return match[1];",
    "  }",
    '  return "";',
    "}",
    "",
    "// Derive the hqdefault thumbnail from a YouTube id, ported from create_testimony.",
    "export function thumbnailFor(youtubeId: string, provided?: string): string {",
    "  if (provided && provided.trim()) return provided.trim();",
    '  if (youtubeId) return `https://img.youtube.com/vi/${youtubeId}/hqdefault.jpg`;',
    '  return "";',
    "}",
    "",
    "const fallbackTestimonies: Testimony[] = [",
    "  {",
    '    id: "sample-1",',
    "    authorId: null,",
    '    authorName: "Maria S.",',
    '    authorEmail: "",',
    '    title: "I found my footing again",',
    '    summary: "After months stuck, one small step changed everything.",',
    '    fullStory: "I was ready to give up. Then someone here reminded me I did not have to do it alone. Six weeks later I am standing on solid ground.",',
    '    videoUrl: "",',
    '    youtubeVideoId: "",',
    '    thumbnailUrl: "",',
    '    category: "breakthrough",',
    '    tags: ["hope", "perseverance"],',
    "    isApproved: true,",
    "    isPublic: true,",
    "    isAnonymous: false,",
    "    isFeatured: true,",
    "    viewCount: 128,",
    "    likeCount: 41,",
    "    followUpScheduled: false,",
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-2",',
    "    authorId: null,",
    '    authorName: "Anonymous",',
    '    authorEmail: "",',
    '    title: "The day the fog lifted",',
    '    summary: "Recovery is possible — I am living proof.",',
    '    fullStory: "For years I thought this was just how life felt. Getting the right support changed that. If you are in the fog, keep going.",',
    '    videoUrl: "",',
    '    youtubeVideoId: "",',
    '    thumbnailUrl: "",',
    '    category: "recovery",',
    '    tags: ["recovery"],',
    "    isApproved: true,",
    "    isPublic: true,",
    "    isAnonymous: true,",
    "    isFeatured: false,",
    "    viewCount: 57,",
    "    likeCount: 19,",
    "    followUpScheduled: false,",
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToTestimony(row: Record<string, unknown>): Testimony {",
    "  const toTags = (v: unknown): string[] => {",
    "    if (Array.isArray(v)) return v.map((x) => String(x));",
    '    if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "    return [];",
    "  };",
    "  return {",
    "    id: String(row.id),",
    "    authorId: row.author_id != null ? String(row.author_id) : null,",
    '    authorName: String(row.author_name || "Anonymous"),',
    '    authorEmail: String(row.author_email || ""),',
    '    title: String(row.title || ""),',
    '    summary: String(row.summary || ""),',
    '    fullStory: String(row.full_story || ""),',
    '    videoUrl: String(row.video_url || ""),',
    '    youtubeVideoId: String(row.youtube_video_id || ""),',
    '    thumbnailUrl: String(row.thumbnail_url || ""),',
    '    category: String(row.category || "other"),',
    "    tags: toTags(row.tags),",
    "    isApproved: row.is_approved === true || String(row.is_approved) === \"true\",",
    "    isPublic: row.is_public === true || String(row.is_public) === \"true\",",
    "    isAnonymous: row.is_anonymous === true || String(row.is_anonymous) === \"true\",",
    "    isFeatured: row.is_featured === true || String(row.is_featured) === \"true\",",
    "    viewCount: Number(row.view_count || 0),",
    "    likeCount: Number(row.like_count || 0),",
    "    followUpScheduled: row.follow_up_scheduled === true || String(row.follow_up_scheduled) === \"true\",",
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// List + filter, ported from testimonies.py get_testimonies: filter by category,",
    "// approval, public flag, and a search across title/summary/tags; newest first.",
    "export async function listTestimonies(filters: TestimonyFilters = {}): Promise<Testimony[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 50));",
    '  const search = (filters.search || "").trim().toLowerCase();',
    "  const isApproved = filters.isApproved;",
    "  const isPublic = filters.isPublic;",
    "  const category = filters.category;",
    "  if (!hasDatabase()) {",
    "    return fallbackTestimonies",
    "      .filter((t) => (isApproved === undefined || t.isApproved === isApproved))",
    "      .filter((t) => (isPublic === undefined || t.isPublic === isPublic))",
    "      .filter((t) => (!category || t.category === category))",
    "      .filter((t) => !search",
    '        || (t.title + " " + t.summary + " " + t.tags.join(" ")).toLowerCase().includes(search))',
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = search ? `%${search}%` : null;",
    "    const cat = category || null;",
    "    const approved = isApproved === undefined ? null : isApproved;",
    "    const pub = isPublic === undefined ? null : isPublic;",
    "    const rows = await sql`",
    "      select id, author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags, is_approved,",
    "        is_public, is_anonymous, is_featured, view_count, like_count,",
    "        follow_up_scheduled, created_at",
    "      from testimony_stories",
    "      where (${cat}::text is null or category = ${cat})",
    "        and (${approved}::boolean is null or is_approved = ${approved})",
    "        and (${pub}::boolean is null or is_public = ${pub})",
    "        and (${like}::text is null",
    "          or lower(title) like ${like}",
    "          or lower(summary) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToTestimony);",
    "  } catch {",
    "    return fallbackTestimonies.slice(0, limit);",
    "  }",
    "}",
    "",
    "// Featured stories for a homepage strip, ported from get_featured_testimonies:",
    "// approved + public + featured, newest first.",
    "export async function listFeatured(limit = 10): Promise<Testimony[]> {",
    "  if (!hasDatabase()) return fallbackTestimonies.filter((t) => t.isFeatured).slice(0, limit);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags, is_approved,",
    "        is_public, is_anonymous, is_featured, view_count, like_count,",
    "        follow_up_scheduled, created_at",
    "      from testimony_stories",
    "      where is_featured = true and is_approved = true and is_public = true",
    "      order by created_at desc limit ${limit}",
    "    `;",
    "    return rows.map(rowToTestimony);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "// 'Others found hope' suggestions, ported from get_matching_testimonies: same",
    "// category, approved + public, most-viewed first, excluding the current story.",
    "export async function listMatching(category: string, excludeId?: string, limit = 5): Promise<Testimony[]> {",
    "  if (!hasDatabase()) {",
    "    return fallbackTestimonies",
    "      .filter((t) => t.category === category && t.isApproved && t.isPublic && t.id !== excludeId)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const exclude = excludeId || null;",
    "    const rows = await sql`",
    "      select id, author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags, is_approved,",
    "        is_public, is_anonymous, is_featured, view_count, like_count,",
    "        follow_up_scheduled, created_at",
    "      from testimony_stories",
    "      where category = ${category} and is_approved = true and is_public = true",
    "        and (${exclude}::uuid is null or id <> ${exclude})",
    "      order by view_count desc limit ${limit}",
    "    `;",
    "    return rows.map(rowToTestimony);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "export async function getTestimony(id: string): Promise<Testimony | null> {",
    "  if (!hasDatabase()) return fallbackTestimonies.find((t) => t.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags, is_approved,",
    "        is_public, is_anonymous, is_featured, view_count, like_count,",
    "        follow_up_scheduled, created_at",
    "      from testimony_stories where id = ${id} limit 1`;",
    "    return rows[0] ? rowToTestimony(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type SubmitTestimonyInput = {",
    "  authorId?: string | null;",
    "  authorName?: string;",
    "  authorEmail?: string;",
    "  title: string;",
    "  summary?: string;",
    "  fullStory: string;",
    "  videoUrl?: string;",
    "  category?: string;",
    "  tags?: string[];",
    "  isPublic?: boolean;",
    "  isAnonymous?: boolean;",
    "};",
    "",
    "// Capture a new story, ported from testimonies.py create_testimony: derive the",
    "// youtube id + thumbnail, store UNAPPROVED (is_approved=false — review required),",
    "// and, when a non-anonymous email is given, schedule the 30-day follow-up that",
    "// closes the loop back to the storyteller.",
    "export async function submitTestimony(input: SubmitTestimonyInput): Promise<Testimony | null> {",
    "  if (!hasDatabase()) return null;",
    '  const videoUrl = (input.videoUrl || "").trim();',
    "  const youtubeId = extractYoutubeId(videoUrl);",
    "  const thumbnail = thumbnailFor(youtubeId);",
    '  const authorName = input.isAnonymous ? "Anonymous" : (input.authorName || "Anonymous");',
    '  const email = (input.authorEmail || "").trim();',
    "  const isAnonymous = input.isAnonymous === true;",
    "  const willFollowUp = Boolean(email) && !isAnonymous;",
    "  const tags = JSON.stringify(input.tags || []);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into testimony_stories (",
    "        author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags,",
    "        is_approved, is_public, is_anonymous, is_featured, follow_up_scheduled",
    "      ) values (",
    "        ${input.authorId || null}, ${authorName}, ${email}, ${input.title},",
    '        ${input.summary || ""}, ${input.fullStory}, ${videoUrl}, ${youtubeId},',
    '        ${thumbnail}, ${input.category || "other"}, ${tags},',
    "        false, ${input.isPublic !== false}, ${isAnonymous}, false, ${willFollowUp}",
    "      )",
    "      returning id, author_id, author_name, author_email, title, summary, full_story,",
    "        video_url, youtube_video_id, thumbnail_url, category, tags, is_approved,",
    "        is_public, is_anonymous, is_featured, view_count, like_count,",
    "        follow_up_scheduled, created_at`;",
    "    const created = rows[0] ? rowToTestimony(rows[0]) : null;",
    "    // Schedule a 30-day check-in, ported from schedule_testimony_follow_up.",
    "    if (created && willFollowUp) {",
    "      try {",
    "        await sql`",
    "          insert into testimony_follow_ups (testimony_id, email, scheduled_for, status, message)",
    "          values (",
    "            ${created.id}, ${email}, now() + interval '30 days', 'scheduled',",
    "            'We wanted to check in and see how you are doing since you shared your story. Your testimony has touched lives.'",
    "          )`;",
    "      } catch {",
    "        // follow-up is best-effort; the story is already captured.",
    "      }",
    "    }",
    "    return created;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Record a view + bump the counter, ported from record_testimony_view.",
    "export async function recordView(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update testimony_stories set view_count = view_count + 1 where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// Like a story, ported from like_testimony.",
    "export async function likeTestimony(id: string): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update testimony_stories set like_count = like_count + 1 where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// The review/approval queue — everything captured but not yet reviewed. This is",
    "// the admin loop-closer implied by create_testimony's is_approved=false default.",
    "export async function listPending(limit = 50): Promise<Testimony[]> {",
    "  return listTestimonies({ isApproved: false, limit });",
    "}",
    "",
    "// Approve (or send back to the queue) a story, and optionally feature it.",
    "export async function reviewTestimony(id: string, approve: boolean, feature = false): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update testimony_stories set is_approved = ${approve}, is_featured = ${feature && approve} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function testimonyEnabled(): boolean {",
    '  return process.env.FEATURE_TESTIMONY !== "false";',
    "}"
  ]);
}

// ---- src/app/api/testimonies/route.ts (list + submit) -----------------------

function testimonyApiFile(): GeneratedModuleFile {
  return file("src/app/api/testimonies/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listTestimonies, submitTestimony, testimonyEnabled } from "@/lib/db/testimony";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!testimonyEnabled()) return NextResponse.json({ ok: false, message: "Testimonies are turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  const testimonies = await listTestimonies({",
    '    category: url.searchParams.get("category") || undefined,',
    '    search: url.searchParams.get("search") || undefined,',
    "    // Customers only ever see approved, public stories through this endpoint.",
    "    isApproved: true,",
    "    isPublic: true",
    "  });",
    "  return NextResponse.json({ ok: true, testimonies });",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to share your story." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const title = typeof body.title === "string" ? body.title.trim() : "";',
    '  const fullStory = typeof body.fullStory === "string" ? body.fullStory.trim() : "";',
    "  if (title.length < 2 || fullStory.length < 10) {",
    '    return NextResponse.json({ ok: false, message: "A title and a few sentences of your story are required." }, { status: 400 });',
    "  }",
    "  const tags = Array.isArray(body.tags) ? body.tags.map((t) => String(t).trim()).filter(Boolean) : [];",
    "  const created = await submitTestimony({",
    "    authorId: user?.id ? String(user.id) : null,",
    '    authorName: typeof body.authorName === "string" ? body.authorName : (user?.name || ""),',
    "    authorEmail: user?.email ? String(user.email) : undefined,",
    "    title,",
    "    fullStory,",
    '    summary: typeof body.summary === "string" ? body.summary : undefined,',
    '    videoUrl: typeof body.videoUrl === "string" ? body.videoUrl : undefined,',
    '    category: typeof body.category === "string" ? body.category : undefined,',
    "    tags,",
    "    isPublic: body.isPublic !== false,",
    "    isAnonymous: body.isAnonymous === true",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save stories." }, { status: 503 });',
    "  // Ported from create_testimony: stories are captured for review, not published live.",
    '  return NextResponse.json({ ok: true, testimony: created, message: "Thank you. Your story is in review and will be published once approved." });',
    "}"
  ]);
}

// ---- src/app/api/testimonies/[id]/route.ts (detail + view/like/review) ------

function testimonyDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/testimonies/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getTestimony, recordView, likeTestimony, reviewTestimony, testimonyEnabled } from "@/lib/db/testimony";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!testimonyEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const testimony = await getTestimony(id);",
    '  if (!testimony) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Unapproved stories are only visible to admins.",
    '  if (!testimony.isApproved && !canAccessAdmin(user?.role)) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  return NextResponse.json({ ok: true, testimony });",
    "}",
    "",
    "// Counter bumps (view/like), ported from record_testimony_view + like_testimony.",
    "export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!testimonyEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const action = typeof body.action === "string" ? body.action : "view";',
    '  const ok = action === "like" ? await likeTestimony(id) : await recordView(id);',
    "  return NextResponse.json({ ok });",
    "}",
    "",
    "// Admin review/approval, the loop-closer for the pending queue.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const approve = body.approve !== false;",
    "  const feature = body.feature === true;",
    "  const ok = await reviewTestimony(id, approve, feature);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to review stories." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/testimonies/page.tsx (public wall + submit) --------------------

function testimonyPageFile(): GeneratedModuleFile {
  return file("src/app/testimonies/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess } from "@/lib/auth/session";',
    'import { listTestimonies, displayName, testimonyEnabled } from "@/lib/db/testimony";',
    'import { ShareStoryForm } from "./share-form";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TestimoniesPage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; category?: string }>;",
    "}) {",
    "  if (!testimonyEnabled()) {",
    '    return (<main className="shell"><h1>Stories</h1><p>Stories are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/testimonies");',
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const category = (params?.category || "").trim();',
    "  const testimonies = await listTestimonies({",
    "    search: q || undefined,",
    "    category: category || undefined,",
    "    isApproved: true,",
    "    isPublic: true",
    "  });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Stories</p>',
    "      <h1>Testimonies</h1>",
    "      <p>Real stories from real people who found their way through. Every problem solved here becomes hope for someone still in it.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search stories" aria-label="Search testimonies" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {testimonies.length === 0 ? (",
    '        <p className="note">{q ? `No stories match "${q}" yet.` : "No stories yet. Be the first to share yours."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {testimonies.map((t) => (",
    '            <Link className="wide-card" key={t.id} href={`/testimonies/${t.id}`}>',
    "              <span>{t.category}</span>",
    "              <strong>{t.title}</strong>",
    "              {t.summary ? <p>{t.summary}</p> : null}",
    '              <p className="note">{displayName(t)} · {t.likeCount} found this hopeful</p>',
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Share your story</h2>",
    "      <p>Been through something and come out the other side? Your story could be the reason someone else keeps going. Every story is reviewed before it is published.</p>",
    "      <ShareStoryForm />",
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/testimonies/share-form.tsx (client) ----------------------------

function shareFormFile(): GeneratedModuleFile {
  return file("src/app/testimonies/share-form.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ShareStoryForm() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    "    try {",
    '      const response = await fetch("/api/testimonies", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          title: form.get("title"),',
    '          summary: form.get("summary"),',
    '          fullStory: form.get("fullStory"),',
    '          videoUrl: form.get("videoUrl"),',
    '          category: form.get("category"),',
    '          isAnonymous: form.get("isAnonymous") === "on"',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Thank you. Your story is in review.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Received</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="title" placeholder="Give your story a title" aria-label="Story title" required />',
    '      <input className="input" name="summary" placeholder="One line: what changed?" aria-label="Story summary" />',
    '      <textarea className="input" name="fullStory" rows={6} placeholder="Tell it in your own words — what were you facing, and how did you get through?" aria-label="Your story" required />',
    '      <input className="input" name="videoUrl" placeholder="Optional: a YouTube link to a video version" aria-label="Video URL" />',
    '      <select className="input" name="category" aria-label="Category" defaultValue="breakthrough">',
    '        <option value="breakthrough">Breakthrough</option>',
    '        <option value="recovery">Recovery</option>',
    '        <option value="grief">Grief</option>',
    '        <option value="mental-health">Mental health</option>',
    '        <option value="relationships">Relationships</option>',
    '        <option value="provision">Provision</option>',
    '        <option value="other">Other</option>',
    "      </select>",
    '      <label className="check"><input type="checkbox" name="isAnonymous" /> Share this anonymously</label>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Sending…" : "Share my story"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/testimonies/[id]/page.tsx (detail + others-found-hope) ---------

function testimonyDetailPageFile(): GeneratedModuleFile {
  return file("src/app/testimonies/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getTestimony, listMatching, displayName, testimonyEnabled } from "@/lib/db/testimony";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TestimonyDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!testimonyEnabled()) {",
    '    return (<main className="shell"><h1>Stories</h1><p>Stories are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/testimonies");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const testimony = await getTestimony(id);",
    "  if (!testimony) notFound();",
    "  if (!testimony.isApproved && !canAccessAdmin(user?.role)) notFound();",
    "  const others = await listMatching(testimony.category, testimony.id);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{testimony.category}</p>',
    "      <h1>{testimony.title}</h1>",
    '      <p className="note">Shared by {displayName(testimony)}</p>',
    "      {!testimony.isApproved ? (",
    '        <p className="note" role="status">This story is awaiting review and is only visible to reviewers.</p>',
    "      ) : null}",
    "      {testimony.thumbnailUrl ? (",
    '        <img className="media" src={testimony.thumbnailUrl} alt="" />',
    "      ) : null}",
    "      {testimony.summary ? <p><strong>{testimony.summary}</strong></p> : null}",
    "      <p>{testimony.fullStory}</p>",
    "      {others.length > 0 ? (",
    "        <>",
    "          <h2>Others found hope here too</h2>",
    '          <section className="panel-list">',
    "            {others.map((o) => (",
    '              <Link className="wide-card" key={o.id} href={`/testimonies/${o.id}`}>',
    "                <span>{o.category}</span>",
    "                <strong>{o.title}</strong>",
    "                {o.summary ? <p>{o.summary}</p> : null}",
    "              </Link>",
    "            ))}",
    "          </section>",
    "        </>",
    "      ) : null}",
    '      <p><Link className="button" href="/testimonies">Back to stories</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/testimonies/review/page.tsx (admin approval queue) -------------

function testimonyReviewPageFile(): GeneratedModuleFile {
  return file("src/app/testimonies/review/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listPending, displayName, testimonyEnabled } from "@/lib/db/testimony";',
    'import { ReviewButtons } from "./review-buttons";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function TestimonyReviewPage() {",
    "  if (!testimonyEnabled()) {",
    '    return (<main className="shell"><h1>Review</h1><p>Stories are turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/testimonies/review");',
    "  const user = await getCurrentUser();",
    "  if (!canAccessAdmin(user?.role)) {",
    '    return (<main className="shell"><h1>Review</h1><p className="note">This review queue is for admins only.</p></main>);',
    "  }",
    "  const pending = await listPending();",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Admin</p>',
    "      <h1>Story review queue</h1>",
    "      <p>Stories are captured here before they go public. Approve the ones ready to encourage others.</p>",
    "      {pending.length === 0 ? (",
    '        <p className="note">Nothing waiting for review. The queue is clear.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {pending.map((t) => (",
    '            <article className="wide-card" key={t.id}>',
    "              <span>{t.category}</span>",
    "              <strong>{t.title}</strong>",
    '              <p className="note">Shared by {displayName(t)}</p>',
    "              {t.summary ? <p>{t.summary}</p> : null}",
    "              <p>{t.fullStory}</p>",
    "              <ReviewButtons id={t.id} />",
    "            </article>",
    "          ))}",
    "        </section>",
    "      )}",
    '      <p><Link className="button" href="/testimonies">Back to stories</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/testimonies/review/review-buttons.tsx (client) -----------------

function reviewButtonsFile(): GeneratedModuleFile {
  return file("src/app/testimonies/review/review-buttons.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function ReviewButtons({ id }: { id: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState<string>("");',
    "",
    "  async function review(approve: boolean, feature: boolean) {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/testimonies/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ approve, feature })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this story.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className="button primary" type="button" onClick={() => review(true, true)} disabled={status === "working"}>Approve &amp; feature</button>',
    '      <button className="button" type="button" onClick={() => review(true, false)} disabled={status === "working"}>Approve</button>',
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const testimonyEngineModule: AppModule = {
  slug: "testimony-engine",
  name: "Testimony Engine",
  tier: "optional",
  featureFlagEnv: "FEATURE_TESTIMONY",
  files: () => [
    testimonyLibFile(),
    testimonyApiFile(),
    testimonyDetailApiFile(),
    testimonyPageFile(),
    shareFormFile(),
    testimonyDetailPageFile(),
    testimonyReviewPageFile(),
    reviewButtonsFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists testimony_stories (",
      "  id uuid primary key default gen_random_uuid(),",
      "  author_id uuid references users(id) on delete set null,",
      "  author_name text not null default 'Anonymous',",
      "  author_email text not null default '',",
      "  title text not null default '',",
      "  summary text not null default '',",
      "  full_story text not null default '',",
      "  video_url text not null default '',",
      "  youtube_video_id text not null default '',",
      "  thumbnail_url text not null default '',",
      "  category text not null default 'other',",
      "  tags jsonb not null default '[]'::jsonb,",
      "  is_approved boolean not null default false,",
      "  is_public boolean not null default true,",
      "  is_anonymous boolean not null default false,",
      "  is_featured boolean not null default false,",
      "  view_count integer not null default 0,",
      "  like_count integer not null default 0,",
      "  follow_up_scheduled boolean not null default false,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists testimony_stories_category_idx on testimony_stories (category);",
      "create index if not exists testimony_stories_approved_idx on testimony_stories (is_approved);",
      "create index if not exists testimony_stories_created_idx on testimony_stories (created_at desc);",
      "",
      "create table if not exists testimony_follow_ups (",
      "  id uuid primary key default gen_random_uuid(),",
      "  testimony_id uuid not null references testimony_stories(id) on delete cascade,",
      "  email text not null,",
      "  scheduled_for timestamptz not null,",
      "  status text not null default 'scheduled',",
      "  message text not null default '',",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists testimony_follow_ups_testimony_idx on testimony_follow_ups (testimony_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into testimony_stories (author_name, title, summary, full_story, category, tags, is_approved, is_public, is_featured, view_count, like_count) values",
      "  ('Maria S.', 'I found my footing again', 'After months stuck, one small step changed everything.', 'I was ready to give up. Then someone here reminded me I did not have to do it alone. Six weeks later I am standing on solid ground.', 'breakthrough', '[\"hope\",\"perseverance\"]'::jsonb, true, true, true, 128, 41)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Testimony Engine — set to false to switch story capture + review + wall off.",
    "FEATURE_TESTIMONY=true"
  ],
  homeLinks: () => ['        <a className="button" href="/testimonies">Stories</a>'],
  navLinks: () => [{ href: "/testimonies", label: "Stories" }]
};
