// website-builder — a site setup wizard + a branded landing-page builder, ported
// from the real "Websites & Domains" product (Website-friends repo:
// src/components/admin/WebsitesAndDomains.tsx + DomainSearchModal.tsx +
// LandingPage.tsx + supabase/functions/check-domain-availability) and
// ChurchConnect's WebsiteSetupWizard.tsx. We keep the actual model and flow:
//   - a WEBSITE record (site_name/site_title, site_url, status
//     [provisioning/active/inactive/maintenance], storage_used_mb,
//     bandwidth_used_gb, monthly_visitors, divi_enabled, ai_designer_used,
//     deployment_date) — ported from WebsitesAndDomains + the websites table
//     columns and the wizard's provisionWebsite payload.
//   - a DOMAIN choice per site (subdomain / custom / existing) with a
//     domain_name, price/cost, auto_renew, registration + expiration dates and
//     the "expiring soon (<30 days)" derivation — ported from WebsitesAndDomains'
//     domain cards and the wizard's step-1 domain picker.
//   - domain availability + pricing across popular TLDs, ported verbatim from
//     DomainSearchModal COMMON_EXTENSIONS + check-domain-availability's TLD price
//     table and the "commonUnavailable" heuristic, so it degrades gracefully to a
//     local check when no registrar key is set (PORKBUN/registrar key optional).
//   - a landing-page builder: headline, subheadline, CTA, price line, and a
//     feature checklist + a published toggle — ported from LandingPage.tsx's real
//     hero + feature grid + "What's Included" checklist structure, generalized off
//     the hosting-brand copy so it drops into any app.
// Runs on the app owner's own database with graceful sample-data fallback,
// feature-flagged (FEATURE_WEBSITE); customers build/view their own sites +
// landing pages (rows scoped to user.id), admins see all and set status.

import type { AppModule, GeneratedModuleFile } from "./types";

function file(path: string, lines: string[]): GeneratedModuleFile {
  return { path, content: lines.join("\n") + "\n" };
}

// ---- src/lib/db/website.ts (model + queries, ported from the real sources) ---

function websiteLibFile(): GeneratedModuleFile {
  return file("src/lib/db/website.ts", [
    'import { getDatabase, hasDatabase } from "@/lib/db/client";',
    "",
    "// A website record, ported from WebsitesAndDomains.tsx + the websites table",
    "// (site_name, site_url, status, storage_used_mb, bandwidth_used_gb,",
    "// monthly_visitors, divi_enabled, ai_designer_used, deployment_date) and the",
    "// wizard's provisionWebsite payload (site_title, admin_email, domain choice).",
    "export type WebsiteStatus = \"provisioning\" | \"active\" | \"inactive\" | \"maintenance\";",
    "",
    "// How the site gets its address, ported from the wizard's step-1 domainChoice.",
    "export type DomainChoice = \"subdomain\" | \"custom\" | \"existing\";",
    "",
    "export type Website = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  siteName: string;",
    "  siteUrl: string;",
    "  domainName: string;",
    "  domainChoice: DomainChoice;",
    "  adminEmail: string;",
    "  status: WebsiteStatus;",
    "  storageUsedMb: number;",
    "  bandwidthUsedGb: number;",
    "  monthlyVisitors: number;",
    "  diviEnabled: boolean;",
    "  aiDesignerUsed: boolean;",
    "  domainCost: number;",
    "  autoRenew: boolean;",
    "  registrationDate: string;",
    "  expirationDate: string;",
    "  deploymentDate: string;",
    "  createdAt: string;",
    "};",
    "",
    "export type WebsiteFilters = { q?: string; status?: string; ownerId?: string; limit?: number };",
    "",
    "// Popular TLDs + at-cost pricing, ported verbatim from DomainSearchModal",
    "// COMMON_EXTENSIONS and check-domain-availability's domainPricing table.",
    "export const DOMAIN_PRICING: Record<string, number> = {",
    '  ".com": 10.93,',
    '  ".net": 14.15,',
    '  ".org": 12.79,',
    '  ".io": 39.0,',
    '  ".co": 32.98,',
    '  ".app": 16.98,',
    '  ".dev": 14.98,',
    '  ".ai": 99.0,',
    '  ".tech": 54.98,',
    '  ".shop": 34.98',
    "};",
    "",
    'export const COMMON_EXTENSIONS = Object.keys(DOMAIN_PRICING);',
    "",
    "// Ported from check-domain-availability: names that are always taken, used for",
    "// the local availability heuristic when no registrar key is configured.",
    'const COMMON_UNAVAILABLE = ["google", "facebook", "amazon", "apple", "microsoft"];',
    "",
    "export type DomainResult = { domain: string; available: boolean; price: number; extension: string };",
    "",
    "export function priceForExtension(extension: string): number {",
    "  return DOMAIN_PRICING[extension] || 14.99;",
    "}",
    "",
    "// A registrar API key is optional; without it we fall back to the same local",
    "// heuristic the edge function uses (never blocks the wizard).",
    "export function registrarConfigured(): boolean {",
    "  return Boolean((process.env.DOMAIN_REGISTRAR_API_KEY || \"\").trim());",
    "}",
    "",
    "// Check availability + price across the popular TLDs, ported from",
    "// DomainSearchModal.handleSearch: strip protocol/path, take the base name, fan",
    "// out over COMMON_EXTENSIONS, sort available-first then cheapest-first.",
    "export function checkDomains(query: string): DomainResult[] {",
    '  const cleanQuery = query.trim().toLowerCase().replace(/^https?:\\/\\//, "").replace(/\\/$/, "");',
    '  const baseName = cleanQuery.split(".")[0].replace(/[^a-z0-9-]/g, "");',
    '  if (!baseName) return [];',
    "  const results = COMMON_EXTENSIONS.map((extension) => {",
    "    const domain = `${baseName}${extension}`;",
    "    // Ported heuristic: well-known names are unavailable, everything else is open.",
    "    const available = !COMMON_UNAVAILABLE.includes(baseName);",
    "    return { domain, available, price: priceForExtension(extension), extension };",
    "  });",
    "  return results.sort((a, b) => {",
    "    if (a.available !== b.available) return a.available ? -1 : 1;",
    "    return a.price - b.price;",
    "  });",
    "}",
    "",
    "export function siteStatusOptions(): WebsiteStatus[] {",
    '  return ["provisioning", "active", "inactive", "maintenance"];',
    "}",
    "",
    "// Days until a domain expires + the <30-day 'expiring soon' flag, ported from",
    "// WebsitesAndDomains' daysUntilExpiry / isExpiringSoon derivation.",
    "export function daysUntilExpiry(expirationDate: string): number | null {",
    "  if (!expirationDate) return null;",
    "  const ts = new Date(expirationDate).getTime();",
    "  if (Number.isNaN(ts)) return null;",
    "  return Math.ceil((ts - Date.now()) / (1000 * 60 * 60 * 24));",
    "}",
    "",
    "export function isExpiringSoon(expirationDate: string): boolean {",
    "  const days = daysUntilExpiry(expirationDate);",
    "  return days !== null && days < 30 && days > 0;",
    "}",
    "",
    "const fallbackWebsites: Website[] = [",
    "  {",
    '    id: "sample-1",',
    "    ownerId: null,",
    '    siteName: "Bright Studio",',
    '    siteUrl: "https://brightstudio.example.com",',
    '    domainName: "brightstudio.com",',
    '    domainChoice: "custom",',
    '    adminEmail: "hello@brightstudio.com",',
    '    status: "active",',
    "    storageUsedMb: 512,",
    "    bandwidthUsedGb: 3.2,",
    "    monthlyVisitors: 1840,",
    "    diviEnabled: true,",
    "    aiDesignerUsed: true,",
    "    domainCost: 10.93,",
    "    autoRenew: true,",
    '    registrationDate: "2025-01-01",',
    '    expirationDate: "2026-01-01",',
    '    deploymentDate: "2025-01-05",',
    '    createdAt: "2025-01-01T00:00:00.000Z"',
    "  },",
    "  {",
    '    id: "sample-2",',
    "    ownerId: null,",
    '    siteName: "Corner Bakery",',
    '    siteUrl: "",',
    '    domainName: "cornerbakery.app",',
    '    domainChoice: "custom",',
    '    adminEmail: "team@cornerbakery.app",',
    '    status: "provisioning",',
    "    storageUsedMb: 0,",
    "    bandwidthUsedGb: 0,",
    "    monthlyVisitors: 0,",
    "    diviEnabled: false,",
    "    aiDesignerUsed: false,",
    "    domainCost: 16.98,",
    "    autoRenew: true,",
    '    registrationDate: "2025-02-01",',
    '    expirationDate: "2026-02-01",',
    '    deploymentDate: "",',
    '    createdAt: "2025-02-01T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function rowToWebsite(row: Record<string, unknown>): Website {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    '    siteName: String(row.site_name || ""),',
    '    siteUrl: String(row.site_url || ""),',
    '    domainName: String(row.domain_name || ""),',
    '    domainChoice: (String(row.domain_choice || "custom") as DomainChoice),',
    '    adminEmail: String(row.admin_email || ""),',
    '    status: (String(row.status || "provisioning") as WebsiteStatus),',
    "    storageUsedMb: Number(row.storage_used_mb || 0),",
    "    bandwidthUsedGb: Number(row.bandwidth_used_gb || 0),",
    "    monthlyVisitors: Number(row.monthly_visitors || 0),",
    '    diviEnabled: row.divi_enabled === true || String(row.divi_enabled) === "true",',
    '    aiDesignerUsed: row.ai_designer_used === true || String(row.ai_designer_used) === "true",',
    "    domainCost: Number(row.domain_cost || 0),",
    '    autoRenew: row.auto_renew === true || String(row.auto_renew) === "true",',
    '    registrationDate: row.registration_date ? String(row.registration_date) : "",',
    '    expirationDate: row.expiration_date ? String(row.expiration_date) : "",',
    '    deploymentDate: row.deployment_date ? String(row.deployment_date) : "",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "// List + search + status filter, ported from WebsitesAndDomains' filteredWebsites",
    "// (match site_name / site_url), scoped to an owner when ownerId is given; newest",
    "// first, mirroring the .order('created_at', { ascending: false }) load.",
    "export async function listWebsites(filters: WebsiteFilters = {}): Promise<Website[]> {",
    "  const limit = Math.min(200, Math.max(1, filters.limit || 100));",
    '  const q = (filters.q || "").trim().toLowerCase();',
    '  const status = (filters.status || "").trim();',
    "  const ownerId = filters.ownerId;",
    "  if (!hasDatabase()) {",
    "    return fallbackWebsites",
    "      .filter((w) => !ownerId || w.ownerId === ownerId)",
    '      .filter((w) => !q || (w.siteName + " " + w.siteUrl + " " + w.domainName).toLowerCase().includes(q))',
    "      .filter((w) => !status || status === \"all\" || w.status === status)",
    "      .slice(0, limit);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const like = q ? `%${q}%` : null;",
    '    const st = status && status !== "all" ? status : null;',
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, site_name, site_url, domain_name, domain_choice, admin_email,",
    "        status, storage_used_mb, bandwidth_used_gb, monthly_visitors, divi_enabled,",
    "        ai_designer_used, domain_cost, auto_renew, registration_date, expiration_date,",
    "        deployment_date, created_at",
    "      from website_builder_sites",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "        and (${st}::text is null or status = ${st})",
    "        and (${like}::text is null",
    "          or lower(site_name) like ${like}",
    "          or lower(site_url) like ${like}",
    "          or lower(domain_name) like ${like})",
    "      order by created_at desc",
    "      limit ${limit}",
    "    `;",
    "    return rows.map(rowToWebsite);",
    "  } catch {",
    "    return fallbackWebsites.slice(0, limit);",
    "  }",
    "}",
    "",
    "export async function getWebsite(id: string): Promise<Website | null> {",
    "  if (!hasDatabase()) return fallbackWebsites.find((w) => w.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, site_name, site_url, domain_name, domain_choice, admin_email,",
    "        status, storage_used_mb, bandwidth_used_gb, monthly_visitors, divi_enabled,",
    "        ai_designer_used, domain_cost, auto_renew, registration_date, expiration_date,",
    "        deployment_date, created_at",
    "      from website_builder_sites where id = ${id} limit 1`;",
    "    return rows[0] ? rowToWebsite(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateWebsiteInput = {",
    "  ownerId: string | null;",
    "  siteName: string;",
    "  domainName?: string;",
    "  domainChoice?: DomainChoice;",
    "  adminEmail?: string;",
    "  diviEnabled?: boolean;",
    "};",
    "",
    "// Create a site, ported from the wizard's provisionWebsite: the record starts",
    "// life as 'provisioning' with an at-cost domain price + a 1-year expiry, and the",
    "// address comes from the chosen domain (subdomain / custom / existing).",
    "export async function createWebsite(input: CreateWebsiteInput): Promise<Website | null> {",
    "  if (!hasDatabase()) return null;",
    '  const domainName = (input.domainName || "").trim().toLowerCase();',
    '  const choice: DomainChoice = input.domainChoice || "custom";',
    '  const extension = domainName.includes(".") ? domainName.substring(domainName.lastIndexOf(".")) : ".com";',
    "  const cost = priceForExtension(extension);",
    '  const siteUrl = domainName ? `https://${domainName}` : "";',
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into website_builder_sites (",
    "        owner_id, site_name, site_url, domain_name, domain_choice, admin_email,",
    "        status, domain_cost, auto_renew, registration_date, expiration_date",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.siteName}, ${siteUrl}, ${domainName},",
    '        ${choice}, ${input.adminEmail || ""}, ${"provisioning"}, ${cost}, ${true},',
    "        now(), now() + interval '1 year'",
    "      )",
    "      returning id, owner_id, site_name, site_url, domain_name, domain_choice, admin_email,",
    "        status, storage_used_mb, bandwidth_used_gb, monthly_visitors, divi_enabled,",
    "        ai_designer_used, domain_cost, auto_renew, registration_date, expiration_date,",
    "        deployment_date, created_at`;",
    "    if (input.diviEnabled && rows[0]) {",
    "      await sql`update website_builder_sites set divi_enabled = true where id = ${String(rows[0].id)}`;",
    "    }",
    "    return rows[0] ? rowToWebsite(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Set a site's status, ported from WebsitesAndDomains' status pills; when a site",
    "// goes 'active' we stamp the deployment_date, mirroring the wizard's go-live.",
    "export async function setWebsiteStatus(id: string, status: WebsiteStatus): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    '    if (status === "active") {',
    "      await sql`update website_builder_sites set status = ${status}, deployment_date = coalesce(deployment_date, now()) where id = ${id}`;",
    "    } else {",
    "      await sql`update website_builder_sites set status = ${status} where id = ${id}`;",
    "    }",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "// ---- Landing pages (ported from LandingPage.tsx) ---------------------------",
    "",
    "// A landing page, ported from LandingPage.tsx's real structure: a hero headline",
    "// + subheadline, a CTA label, a price line ($5/month), and the 'What's Included'",
    "// feature checklist — generalized off the hosting-brand copy.",
    "export type LandingPage = {",
    "  id: string;",
    "  ownerId: string | null;",
    "  websiteId: string | null;",
    "  slug: string;",
    "  brandName: string;",
    "  headline: string;",
    "  subheadline: string;",
    "  ctaLabel: string;",
    "  priceLine: string;",
    "  features: string[];",
    "  published: boolean;",
    "  createdAt: string;",
    "};",
    "",
    "// The default feature checklist, ported from LandingPage.tsx's included-features",
    "// list, generalized so it reads for any product.",
    "export const DEFAULT_LANDING_FEATURES = [",
    '  "Everything you need to launch",',
    '  "Professional email included",',
    '  "Premium themes & builder",',
    '  "AI-powered designer",',
    '  "Fast, reliable hosting",',
    '  "Domain registration at cost",',
    '  "SSL certificates included",',
    '  "Daily backups",',
    '  "Expert support",',
    '  "No setup fees"',
    "];",
    "",
    "function slugify(value: string): string {",
    '  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "page";',
    "}",
    "",
    "const fallbackLandingPages: LandingPage[] = [",
    "  {",
    '    id: "sample-lp-1",',
    "    ownerId: null,",
    '    websiteId: "sample-1",',
    '    slug: "bright-studio",',
    '    brandName: "Bright Studio",',
    '    headline: "Design that moves people",',
    '    subheadline: "Everything you need to launch and grow your brand online — fast.",',
    '    ctaLabel: "Get Started Today",',
    '    priceLine: "$5/month + domain costs",',
    "    features: DEFAULT_LANDING_FEATURES,",
    "    published: true,",
    '    createdAt: "2025-01-06T00:00:00.000Z"',
    "  }",
    "];",
    "",
    "function toFeatures(v: unknown): string[] {",
    "  if (Array.isArray(v)) return v.map((x) => String(x)).filter(Boolean);",
    '  if (typeof v === "string" && v.trim()) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map((x) => String(x)) : []; } catch { return []; } }',
    "  return [];",
    "}",
    "",
    "function rowToLanding(row: Record<string, unknown>): LandingPage {",
    "  return {",
    "    id: String(row.id),",
    "    ownerId: row.owner_id != null ? String(row.owner_id) : null,",
    "    websiteId: row.website_id != null ? String(row.website_id) : null,",
    '    slug: String(row.slug || ""),',
    '    brandName: String(row.brand_name || ""),',
    '    headline: String(row.headline || ""),',
    '    subheadline: String(row.subheadline || ""),',
    '    ctaLabel: String(row.cta_label || "Get Started"),',
    '    priceLine: String(row.price_line || ""),',
    "    features: toFeatures(row.features),",
    '    published: row.published === true || String(row.published) === "true",',
    '    createdAt: row.created_at ? String(row.created_at) : ""',
    "  };",
    "}",
    "",
    "export async function listLandingPages(ownerId?: string, limit = 100): Promise<LandingPage[]> {",
    "  const cap = Math.min(200, Math.max(1, limit));",
    "  if (!hasDatabase()) {",
    "    return fallbackLandingPages.filter((p) => !ownerId || p.ownerId === ownerId).slice(0, cap);",
    "  }",
    "  try {",
    "    const sql = getDatabase();",
    "    const owner = ownerId || null;",
    "    const rows = await sql`",
    "      select id, owner_id, website_id, slug, brand_name, headline, subheadline,",
    "        cta_label, price_line, features, published, created_at",
    "      from website_builder_landing_pages",
    "      where (${owner}::uuid is null or owner_id = ${owner})",
    "      order by created_at desc limit ${cap}",
    "    `;",
    "    return rows.map(rowToLanding);",
    "  } catch {",
    "    return fallbackLandingPages.slice(0, cap);",
    "  }",
    "}",
    "",
    "export async function getLandingPage(id: string): Promise<LandingPage | null> {",
    "  if (!hasDatabase()) return fallbackLandingPages.find((p) => p.id === id) || null;",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      select id, owner_id, website_id, slug, brand_name, headline, subheadline,",
    "        cta_label, price_line, features, published, created_at",
    "      from website_builder_landing_pages where id = ${id} limit 1`;",
    "    return rows[0] ? rowToLanding(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "export type CreateLandingInput = {",
    "  ownerId: string | null;",
    "  websiteId?: string | null;",
    "  brandName: string;",
    "  headline: string;",
    "  subheadline?: string;",
    "  ctaLabel?: string;",
    "  priceLine?: string;",
    "  features?: string[];",
    "  published?: boolean;",
    "};",
    "",
    "// Build a landing page, ported from LandingPage.tsx's hero + feature grid: a",
    "// brand name, a big headline + subheadline, a CTA, a price line, and the feature",
    "// checklist. Published defaults false so it is a draft until the owner ships it.",
    "export async function createLandingPage(input: CreateLandingInput): Promise<LandingPage | null> {",
    "  if (!hasDatabase()) return null;",
    "  const slug = slugify(input.brandName || input.headline);",
    "  const features = JSON.stringify(input.features && input.features.length ? input.features : DEFAULT_LANDING_FEATURES);",
    "  try {",
    "    const sql = getDatabase();",
    "    const rows = await sql`",
    "      insert into website_builder_landing_pages (",
    "        owner_id, website_id, slug, brand_name, headline, subheadline, cta_label,",
    "        price_line, features, published",
    "      ) values (",
    "        ${input.ownerId || null}, ${input.websiteId || null}, ${slug}, ${input.brandName},",
    '        ${input.headline}, ${input.subheadline || ""}, ${input.ctaLabel || "Get Started"},',
    '        ${input.priceLine || ""}, ${features}, ${input.published === true}',
    "      )",
    "      returning id, owner_id, website_id, slug, brand_name, headline, subheadline,",
    "        cta_label, price_line, features, published, created_at`;",
    "    return rows[0] ? rowToLanding(rows[0]) : null;",
    "  } catch {",
    "    return null;",
    "  }",
    "}",
    "",
    "// Publish / unpublish a landing page (the LandingPage.tsx go-live toggle).",
    "export async function setLandingPublished(id: string, published: boolean): Promise<boolean> {",
    "  if (!hasDatabase()) return false;",
    "  try {",
    "    const sql = getDatabase();",
    "    await sql`update website_builder_landing_pages set published = ${published} where id = ${id}`;",
    "    return true;",
    "  } catch {",
    "    return false;",
    "  }",
    "}",
    "",
    "export function websiteEnabled(): boolean {",
    '  return process.env.FEATURE_WEBSITE !== "false";',
    "}"
  ]);
}

// ---- src/app/api/website/domains/route.ts (availability check) --------------

function domainApiFile(): GeneratedModuleFile {
  return file("src/app/api/website/domains/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { checkDomains, registrarConfigured, websiteEnabled } from "@/lib/db/website";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "// Domain availability + pricing across the popular TLDs, ported from",
    "// DomainSearchModal.handleSearch. Uses a registrar key when set, otherwise the",
    "// same local heuristic the edge function falls back to — never blocks.",
    "export async function GET(request: Request) {",
    '  if (!websiteEnabled()) return NextResponse.json({ ok: false, message: "The website builder is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    '  const query = (url.searchParams.get("q") || "").trim();',
    '  if (!query) return NextResponse.json({ ok: true, results: [], live: registrarConfigured() });',
    "  const results = checkDomains(query);",
    "  return NextResponse.json({ ok: true, results, live: registrarConfigured() });",
    "}"
  ]);
}

// ---- src/app/api/website/route.ts (list + create site) ----------------------

function websiteApiFile(): GeneratedModuleFile {
  return file("src/app/api/website/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listWebsites, createWebsite, websiteEnabled } from "@/lib/db/website";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(request: Request) {",
    '  if (!websiteEnabled()) return NextResponse.json({ ok: false, message: "The website builder is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const url = new URL(request.url);",
    "  // Customers see only their own sites; admins see every site.",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const sites = await listWebsites({",
    '    q: url.searchParams.get("q") || undefined,',
    '    status: url.searchParams.get("status") || undefined,',
    "    ownerId",
    "  });",
    "  return NextResponse.json({ ok: true, sites });",
    "}",
    "",
    "// Create a site through the wizard, ported from provisionWebsite. Scoped to the",
    "// signed-in owner via user.id.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to create a site." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const siteName = typeof body.siteName === "string" ? body.siteName.trim() : "";',
    "  if (siteName.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "Give your site a name." }, { status: 400 });',
    "  }",
    '  const domainChoice = body.domainChoice === "subdomain" || body.domainChoice === "existing" ? body.domainChoice : "custom";',
    "  const created = await createWebsite({",
    "    ownerId: user?.id ? String(user.id) : null,",
    "    siteName,",
    '    domainName: typeof body.domainName === "string" ? body.domainName : undefined,',
    "    domainChoice,",
    '    adminEmail: typeof body.adminEmail === "string" ? body.adminEmail : (user?.email ? String(user.email) : undefined),',
    "    diviEnabled: body.diviEnabled === true",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save sites." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, site: created, message: "Your site is being set up." });',
    "}"
  ]);
}

// ---- src/app/api/website/[id]/route.ts (detail + status) --------------------

function websiteDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/website/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getWebsite, setWebsiteStatus, siteStatusOptions, websiteEnabled } from "@/lib/db/website";',
    'import type { WebsiteStatus } from "@/lib/db/website";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!websiteEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const site = await getWebsite(id);",
    '  if (!site) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  // Customers may only read their own sites.",
    "  if (!canAccessAdmin(user?.role) && site.ownerId && site.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, site });",
    "}",
    "",
    "// Set a site's status (provisioning/active/inactive/maintenance) — admins only,",
    "// the operator control from WebsitesAndDomains' status pills.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!user || !canAccessAdmin(user.role)) return NextResponse.json({ ok: false, message: "Admins only." }, { status: 403 });',
    "  const { id } = await params;",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const status = typeof body.status === "string" ? body.status : "";',
    "  if (!siteStatusOptions().includes(status as WebsiteStatus)) {",
    '    return NextResponse.json({ ok: false, message: "Unknown status." }, { status: 400 });',
    "  }",
    "  const ok = await setWebsiteStatus(id, status as WebsiteStatus);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update sites." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/api/website/landing/route.ts (list + create landing page) ------

function landingApiFile(): GeneratedModuleFile {
  return file("src/app/api/website/landing/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { listLandingPages, createLandingPage, websiteEnabled } from "@/lib/db/website";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET() {",
    '  if (!websiteEnabled()) return NextResponse.json({ ok: false, message: "The website builder is turned off for this app." }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const pages = await listLandingPages(ownerId);",
    "  return NextResponse.json({ ok: true, pages });",
    "}",
    "",
    "// Build a landing page, ported from LandingPage.tsx. Scoped to the owner.",
    "export async function POST(request: Request) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in to build a landing page." }, { status: 401 });',
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    '  const brandName = typeof body.brandName === "string" ? body.brandName.trim() : "";',
    '  const headline = typeof body.headline === "string" ? body.headline.trim() : "";',
    "  if (brandName.length < 2 || headline.length < 2) {",
    '    return NextResponse.json({ ok: false, message: "A brand name and a headline are required." }, { status: 400 });',
    "  }",
    "  const features = Array.isArray(body.features) ? body.features.map((f) => String(f).trim()).filter(Boolean) : undefined;",
    "  const created = await createLandingPage({",
    "    ownerId: user?.id ? String(user.id) : null,",
    '    websiteId: typeof body.websiteId === "string" ? body.websiteId : null,',
    "    brandName,",
    "    headline,",
    '    subheadline: typeof body.subheadline === "string" ? body.subheadline : undefined,',
    '    ctaLabel: typeof body.ctaLabel === "string" ? body.ctaLabel : undefined,',
    '    priceLine: typeof body.priceLine === "string" ? body.priceLine : undefined,',
    "    features,",
    "    published: body.published === true",
    "  });",
    '  if (!created) return NextResponse.json({ ok: false, message: "Connect a database to save landing pages." }, { status: 503 });',
    '  return NextResponse.json({ ok: true, page: created });',
    "}"
  ]);
}

// ---- src/app/api/website/landing/[id]/route.ts (publish toggle) -------------

function landingDetailApiFile(): GeneratedModuleFile {
  return file("src/app/api/website/landing/[id]/route.ts", [
    'import { NextResponse } from "next/server";',
    'import { getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin, canAccessCustomerArea } from "@/lib/auth/roles";',
    'import { getLandingPage, setLandingPublished, websiteEnabled } from "@/lib/db/website";',
    "",
    'export const runtime = "nodejs";',
    'export const dynamic = "force-dynamic";',
    "",
    "export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {",
    '  if (!websiteEnabled()) return NextResponse.json({ ok: false }, { status: 404 });',
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const page = await getLandingPage(id);",
    '  if (!page) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  if (!canAccessAdmin(user?.role) && page.ownerId && page.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  return NextResponse.json({ ok: true, page });",
    "}",
    "",
    "// Publish / unpublish — the owner (or an admin) ships their landing page live.",
    "export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {",
    "  const user = await getCurrentUser();",
    '  if (!canAccessCustomerArea(user?.role)) return NextResponse.json({ ok: false, message: "Please sign in." }, { status: 401 });',
    "  const { id } = await params;",
    "  const page = await getLandingPage(id);",
    '  if (!page) return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  if (!canAccessAdmin(user?.role) && page.ownerId && page.ownerId !== String(user?.id)) {",
    '    return NextResponse.json({ ok: false, message: "Not found." }, { status: 404 });',
    "  }",
    "  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;",
    "  const published = body.published !== false;",
    "  const ok = await setLandingPublished(id, published);",
    '  if (!ok) return NextResponse.json({ ok: false, message: "Connect a database to update landing pages." }, { status: 503 });',
    "  return NextResponse.json({ ok: true });",
    "}"
  ]);
}

// ---- src/app/website/page.tsx (site list + wizard) --------------------------

function websitePageFile(): GeneratedModuleFile {
  return file("src/app/website/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listWebsites, isExpiringSoon, daysUntilExpiry, websiteEnabled } from "@/lib/db/website";',
    'import { SiteWizard } from "./site-wizard";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function WebsitePage({",
    "  searchParams",
    "}: {",
    "  searchParams?: Promise<{ q?: string; status?: string }>;",
    "}) {",
    "  if (!websiteEnabled()) {",
    '    return (<main className="shell"><h1>Websites</h1><p>The website builder is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/website");',
    "  const user = await getCurrentUser();",
    "  const params = searchParams ? await searchParams : undefined;",
    '  const q = (params?.q || "").trim();',
    '  const status = (params?.status || "").trim();',
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  const ownerId = isAdmin ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const sites = await listWebsites({ q: q || undefined, status: status || undefined, ownerId });",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Websites</p>',
    "      <h1>Your sites</h1>",
    "      <p>Set up a site in a few steps and point it at a domain. Track storage, traffic, and renewals in one place.</p>",
    '      <form className="stack" method="get" role="search">',
    '        <input className="input" type="search" name="q" defaultValue={q} placeholder="Search by name, URL, or domain" aria-label="Search sites" />',
    '        <button className="button primary" type="submit">Search</button>',
    "      </form>",
    "      {sites.length === 0 ? (",
    '        <p className="note">{q ? `No sites match "${q}" yet.` : "No sites yet. Start with the wizard below."}</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {sites.map((site) => {",
    "            const expiring = isExpiringSoon(site.expirationDate);",
    "            const days = daysUntilExpiry(site.expirationDate);",
    "            return (",
    '              <Link className="wide-card" key={site.id} href={`/website/${site.id}`}>',
    "                <span>{site.status}</span>",
    "                <strong>{site.siteName}</strong>",
    "                <p>{[site.domainName, site.siteUrl].filter(Boolean).join(\" · \")}</p>",
    "                <p className=\"note\">",
    "                  {`${site.monthlyVisitors.toLocaleString()} visitors/mo`}",
    "                  {site.diviEnabled ? \" · Builder on\" : \"\"}",
    "                  {site.aiDesignerUsed ? \" · AI designed\" : \"\"}",
    "                  {expiring && days !== null ? ` · Renews in ${days} days` : \"\"}",
    "                </p>",
    "              </Link>",
    "            );",
    "          })}",
    "        </section>",
    "      )}",
    "      <h2>Create a site</h2>",
    "      <p>Pick an address, name your site, and we will start setting it up.</p>",
    "      <SiteWizard />",
    '      <p><Link className="button" href="/website/landing">Landing page builder</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/site-wizard.tsx (client wizard) ------------------------

function siteWizardFile(): GeneratedModuleFile {
  return file("src/app/website/site-wizard.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The site setup wizard, ported from ChurchConnect's WebsiteSetupWizard +",
    "// DomainSearchModal: pick an address (subdomain / your own domain / bring your",
    "// own), check availability across the popular TLDs, name the site, and create it.",
    "type DomainResult = { domain: string; available: boolean; price: number; extension: string };",
    "",
    "export function SiteWizard() {",
    "  const router = useRouter();",
    '  const [choice, setChoice] = useState<"subdomain" | "custom" | "existing">("custom");',
    '  const [query, setQuery] = useState("");',
    '  const [domainName, setDomainName] = useState("");',
    "  const [results, setResults] = useState<DomainResult[]>([]);",
    '  const [checking, setChecking] = useState(false);',
    '  const [siteName, setSiteName] = useState("");',
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function checkDomain() {",
    "    if (!query.trim()) return;",
    "    setChecking(true);",
    "    setResults([]);",
    "    try {",
    "      const response = await fetch(`/api/website/domains?q=${encodeURIComponent(query.trim())}`);",
    "      const data = await response.json();",
    "      if (data.ok) setResults(data.results || []);",
    "    } catch {",
    "      // availability is best-effort; the user can still type a domain directly.",
    "    } finally {",
    "      setChecking(false);",
    "    }",
    "  }",
    "",
    "  async function create(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    try {",
    '      const response = await fetch("/api/website", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ siteName, domainName, domainChoice: choice })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage(data.message || "Your site is being set up.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Created</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={create}>',
    '      <fieldset className="stack">',
    "        <legend>Choose your web address</legend>",
    '        <label className="check"><input type="radio" name="choice" checked={choice === "subdomain"} onChange={() => setChoice("subdomain")} /> Free subdomain</label>',
    '        <label className="check"><input type="radio" name="choice" checked={choice === "custom"} onChange={() => setChoice("custom")} /> Get your own domain</label>',
    '        <label className="check"><input type="radio" name="choice" checked={choice === "existing"} onChange={() => setChoice("existing")} /> Use a domain you own</label>',
    "      </fieldset>",
    '      {choice === "custom" ? (',
    '        <div className="stack">',
    '          <input className="input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search a name (e.g. brightstudio)" aria-label="Domain search" />',
    '          <button className="button" type="button" onClick={checkDomain} disabled={checking || !query.trim()}>{checking ? "Checking…" : "Check availability"}</button>',
    "          {results.length > 0 ? (",
    '            <ul className="panel-list">',
    "              {results.map((r) => (",
    '                <li key={r.domain}>',
    '                  <button type="button" className={domainName === r.domain ? "wide-card selected" : "wide-card"} disabled={!r.available} onClick={() => setDomainName(r.domain)}>',
    "                    <strong>{r.domain}</strong>",
    '                    <span className="note">{r.available ? `Available · $${r.price.toFixed(2)}/yr` : "Not available"}</span>',
    "                  </button>",
    "                </li>",
    "              ))}",
    "            </ul>",
    "          ) : null}",
    "        </div>",
    "      ) : (",
    '        <input className="input" value={domainName} onChange={(e) => setDomainName(e.target.value.toLowerCase())} placeholder={choice === "subdomain" ? "yourbrand (a subdomain)" : "yourbrand.com (a domain you own)"} aria-label="Domain name" />',
    "      )}",
    '      <input className="input" value={siteName} onChange={(e) => setSiteName(e.target.value)} placeholder="Name your site" aria-label="Site name" required />',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving" || siteName.trim().length < 2}>',
    '        {status === "saving" ? "Setting up…" : "Create site"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/[id]/page.tsx (site detail + admin status) -------------

function websiteDetailPageFile(): GeneratedModuleFile {
  return file("src/app/website/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getWebsite, isExpiringSoon, daysUntilExpiry, websiteEnabled } from "@/lib/db/website";',
    'import { StatusControls } from "./status-controls";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function WebsiteDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!websiteEnabled()) {",
    '    return (<main className="shell"><h1>Websites</h1><p>The website builder is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/website");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const site = await getWebsite(id);",
    "  if (!site) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && site.ownerId && site.ownerId !== String(user?.id)) notFound();",
    "  const expiring = isExpiringSoon(site.expirationDate);",
    "  const days = daysUntilExpiry(site.expirationDate);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{site.status}</p>',
    "      <h1>{site.siteName}</h1>",
    "      {site.siteUrl ? (",
    '        <p><a className="link" href={site.siteUrl} target="_blank" rel="noopener noreferrer">{site.siteUrl}</a></p>',
    "      ) : null}",
    '      <section className="grid">',
    '        <article className="card"><span>Domain</span><strong>{site.domainName || "—"}</strong></article>',
    '        <article className="card"><span>Storage</span><strong>{(site.storageUsedMb / 1024).toFixed(1)} GB</strong></article>',
    '        <article className="card"><span>Bandwidth</span><strong>{site.bandwidthUsedGb.toFixed(1)} GB</strong></article>',
    '        <article className="card"><span>Visitors / mo</span><strong>{site.monthlyVisitors.toLocaleString()}</strong></article>',
    "      </section>",
    '      <section className="grid">',
    '        <article className="card"><span>Registered</span><strong>{site.registrationDate ? new Date(site.registrationDate).toLocaleDateString() : "—"}</strong></article>',
    '        <article className="card"><span>Renews</span><strong>{site.expirationDate ? new Date(site.expirationDate).toLocaleDateString() : "—"}</strong></article>',
    '        <article className="card"><span>Annual cost</span><strong>${site.domainCost.toFixed(2)}</strong></article>',
    '        <article className="card"><span>Auto-renew</span><strong>{site.autoRenew ? "On" : "Off"}</strong></article>',
    "      </section>",
    "      {expiring && days !== null ? (",
    '        <p className="note" role="status">This domain renews in {days} days.</p>',
    "      ) : null}",
    "      {site.diviEnabled || site.aiDesignerUsed ? (",
    "        <p className=\"note\">{[site.diviEnabled ? \"Builder enabled\" : \"\", site.aiDesignerUsed ? \"AI designer used\" : \"\"].filter(Boolean).join(\" · \")}</p>",
    "      ) : null}",
    "      {isAdmin ? <StatusControls id={site.id} current={site.status} /> : null}",
    '      <p><Link className="button" href="/website">Back to sites</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/[id]/status-controls.tsx (client, admin) ---------------

function statusControlsFile(): GeneratedModuleFile {
  return file("src/app/website/[id]/status-controls.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// Admin status pills, ported from WebsitesAndDomains' status control.",
    'const STATUSES = ["provisioning", "active", "inactive", "maintenance"] as const;',
    "",
    "export function StatusControls({ id, current }: { id: string; current: string }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function apply(next: string) {",
    "    if (next === current) return;",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/website/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ status: next })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update the site.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '        setStatus("error");',
    '        setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <p className="eyebrow">Set status</p>',
    '      <div className="stack">',
    "        {STATUSES.map((s) => (",
    '          <button key={s} type="button" className={s === current ? "button primary" : "button"} onClick={() => apply(s)} disabled={status === "working"}>{s}</button>',
    "        ))}",
    "      </div>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/landing/page.tsx (landing pages list + builder) --------

function landingPageFile(): GeneratedModuleFile {
  return file("src/app/website/landing/page.tsx", [
    'import Link from "next/link";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { listLandingPages, websiteEnabled } from "@/lib/db/website";',
    'import { LandingBuilder } from "./landing-builder";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function LandingPagesPage() {",
    "  if (!websiteEnabled()) {",
    '    return (<main className="shell"><h1>Landing pages</h1><p>The website builder is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/website/landing");',
    "  const user = await getCurrentUser();",
    "  const ownerId = canAccessAdmin(user?.role) ? undefined : (user?.id ? String(user.id) : undefined);",
    "  const pages = await listLandingPages(ownerId);",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">Landing pages</p>',
    "      <h1>Branded landing pages</h1>",
    "      <p>Spin up a landing page with a headline, a call to action, and a feature checklist. Publish it when it is ready.</p>",
    "      {pages.length === 0 ? (",
    '        <p className="note">No landing pages yet. Build your first one below.</p>',
    "      ) : (",
    '        <section className="panel-list">',
    "          {pages.map((page) => (",
    '            <Link className="wide-card" key={page.id} href={`/website/landing/${page.id}`}>',
    '              <span>{page.published ? "Published" : "Draft"}</span>',
    "              <strong>{page.brandName}</strong>",
    "              <p>{page.headline}</p>",
    "            </Link>",
    "          ))}",
    "        </section>",
    "      )}",
    "      <h2>Build a landing page</h2>",
    "      <LandingBuilder />",
    '      <p><Link className="button" href="/website">Back to sites</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/landing/landing-builder.tsx (client) -------------------

function landingBuilderFile(): GeneratedModuleFile {
  return file("src/app/website/landing/landing-builder.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "// The landing-page builder, ported from LandingPage.tsx: brand, headline,",
    "// subheadline, CTA label, a price line, and a feature checklist (one per line).",
    "export function LandingBuilder() {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "saving" | "error" | "done">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function submit(event: React.FormEvent<HTMLFormElement>) {",
    "    event.preventDefault();",
    '    setStatus("saving");',
    '    setMessage("");',
    "    const form = new FormData(event.currentTarget);",
    '    const featuresRaw = String(form.get("features") || "");',
    '    const features = featuresRaw.split("\\n").map((f) => f.trim()).filter(Boolean);',
    "    try {",
    '      const response = await fetch("/api/website/landing", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({",
    '          brandName: form.get("brandName"),',
    '          headline: form.get("headline"),',
    '          subheadline: form.get("subheadline"),',
    '          ctaLabel: form.get("ctaLabel"),',
    '          priceLine: form.get("priceLine"),',
    "          features,",
    '          published: form.get("published") === "on"',
    "        })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Something went wrong. Please try again.");',
    "        return;",
    "      }",
    '      setStatus("done");',
    '      setMessage("Your landing page is saved.");',
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server. Please try again.");',
    "    }",
    "  }",
    "",
    '  if (status === "done") {',
    "    return (",
    '      <section className="panel" aria-live="polite">',
    '        <p className="eyebrow">Saved</p>',
    "        <p>{message}</p>",
    "      </section>",
    "    );",
    "  }",
    "",
    "  return (",
    '    <form className="stack" onSubmit={submit}>',
    '      <input className="input" name="brandName" placeholder="Brand name" aria-label="Brand name" required />',
    '      <input className="input" name="headline" placeholder="Headline — the big promise" aria-label="Headline" required />',
    '      <input className="input" name="subheadline" placeholder="Subheadline — one line of detail" aria-label="Subheadline" />',
    '      <input className="input" name="ctaLabel" placeholder="Button text (e.g. Get Started Today)" aria-label="Call to action" defaultValue="Get Started Today" />',
    '      <input className="input" name="priceLine" placeholder="Price line (e.g. $5/month + domain costs)" aria-label="Price line" />',
    '      <textarea className="input" name="features" rows={6} placeholder="One feature per line (leave blank for the defaults)" aria-label="Features" />',
    '      <label className="check"><input type="checkbox" name="published" /> Publish now</label>',
    '      {status === "error" ? <p className="note" role="alert">{message}</p> : null}',
    '      <button className="button primary" type="submit" disabled={status === "saving"}>',
    '        {status === "saving" ? "Saving…" : "Save landing page"}',
    "      </button>",
    "    </form>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/landing/[id]/page.tsx (rendered landing page + publish) -

function landingDetailPageFile(): GeneratedModuleFile {
  return file("src/app/website/landing/[id]/page.tsx", [
    'import Link from "next/link";',
    'import { notFound } from "next/navigation";',
    'import { requireCustomerAccess, getCurrentUser } from "@/lib/auth/session";',
    'import { canAccessAdmin } from "@/lib/auth/roles";',
    'import { getLandingPage, DEFAULT_LANDING_FEATURES, websiteEnabled } from "@/lib/db/website";',
    'import { PublishToggle } from "./publish-toggle";',
    "",
    'export const dynamic = "force-dynamic";',
    "",
    "export default async function LandingDetailPage({ params }: { params: Promise<{ id: string }> }) {",
    "  if (!websiteEnabled()) {",
    '    return (<main className="shell"><h1>Landing page</h1><p>The website builder is turned off for this app.</p></main>);',
    "  }",
    '  await requireCustomerAccess("/website/landing");',
    "  const user = await getCurrentUser();",
    "  const { id } = await params;",
    "  const page = await getLandingPage(id);",
    "  if (!page) notFound();",
    "  const isAdmin = canAccessAdmin(user?.role);",
    "  if (!isAdmin && page.ownerId && page.ownerId !== String(user?.id)) notFound();",
    "  const features = page.features.length ? page.features : DEFAULT_LANDING_FEATURES;",
    "  const canManage = isAdmin || (page.ownerId && page.ownerId === String(user?.id));",
    "",
    "  return (",
    '    <main className="shell">',
    '      <p className="eyebrow">{page.published ? "Published" : "Draft"} · {page.brandName}</p>',
    "      {/* Rendered preview, ported from LandingPage.tsx's hero + feature checklist. */}",
    '      <section className="hero">',
    "        <h1>{page.headline}</h1>",
    "        {page.subheadline ? <p>{page.subheadline}</p> : null}",
    '        <p><span className="button primary">{page.ctaLabel}</span>{page.priceLine ? <span className="note"> {page.priceLine}</span> : null}</p>',
    "      </section>",
    "      <h2>What's included</h2>",
    '      <ul className="feature-list">',
    "        {features.map((feature, index) => (",
    "          <li key={index}>{feature}</li>",
    "        ))}",
    "      </ul>",
    "      {canManage ? <PublishToggle id={page.id} published={page.published} /> : null}",
    '      <p><Link className="button" href="/website/landing">Back to landing pages</Link></p>',
    "    </main>",
    "  );",
    "}"
  ]);
}

// ---- src/app/website/landing/[id]/publish-toggle.tsx (client) ---------------

function publishToggleFile(): GeneratedModuleFile {
  return file("src/app/website/landing/[id]/publish-toggle.tsx", [
    '"use client";',
    "",
    'import { useState } from "react";',
    'import { useRouter } from "next/navigation";',
    "",
    "export function PublishToggle({ id, published }: { id: string; published: boolean }) {",
    "  const router = useRouter();",
    '  const [status, setStatus] = useState<"idle" | "working" | "error">("idle");',
    '  const [message, setMessage] = useState("");',
    "",
    "  async function toggle() {",
    '    setStatus("working");',
    '    setMessage("");',
    "    try {",
    "      const response = await fetch(`/api/website/landing/${id}`, {",
    '        method: "PATCH",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ published: !published })",
    "      });",
    "      const data = await response.json();",
    "      if (!response.ok || !data.ok) {",
    '        setStatus("error");',
    '        setMessage(data.message || "Could not update this page.");',
    "        return;",
    "      }",
    "      router.refresh();",
    "    } catch {",
    '      setStatus("error");',
    '      setMessage("Could not reach the server.");',
    "    }",
    "  }",
    "",
    "  return (",
    '    <div className="stack">',
    '      <button className="button primary" type="button" onClick={toggle} disabled={status === "working"}>',
    '        {published ? "Unpublish" : "Publish"}',
    "      </button>",
    '      {status === "error" ? <span className="note" role="alert">{message}</span> : null}',
    "    </div>",
    "  );",
    "}"
  ]);
}

export const websiteBuilderModule: AppModule = {
  slug: "website-builder",
  name: "Website Builder",
  tier: "optional",
  featureFlagEnv: "FEATURE_WEBSITE",
  files: () => [
    websiteLibFile(),
    domainApiFile(),
    websiteApiFile(),
    websiteDetailApiFile(),
    landingApiFile(),
    landingDetailApiFile(),
    websitePageFile(),
    siteWizardFile(),
    websiteDetailPageFile(),
    statusControlsFile(),
    landingPageFile(),
    landingBuilderFile(),
    landingDetailPageFile(),
    publishToggleFile()
  ],
  schemaSql: () =>
    [
      "",
      "create table if not exists website_builder_sites (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  site_name text not null default '',",
      "  site_url text not null default '',",
      "  domain_name text not null default '',",
      "  domain_choice text not null default 'custom',",
      "  admin_email text not null default '',",
      "  status text not null default 'provisioning',",
      "  storage_used_mb integer not null default 0,",
      "  bandwidth_used_gb numeric(10,2) not null default 0,",
      "  monthly_visitors integer not null default 0,",
      "  divi_enabled boolean not null default false,",
      "  ai_designer_used boolean not null default false,",
      "  domain_cost numeric(10,2) not null default 0,",
      "  auto_renew boolean not null default true,",
      "  registration_date timestamptz,",
      "  expiration_date timestamptz,",
      "  deployment_date timestamptz,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists website_builder_sites_owner_idx on website_builder_sites (owner_id);",
      "create index if not exists website_builder_sites_status_idx on website_builder_sites (status);",
      "create index if not exists website_builder_sites_created_idx on website_builder_sites (created_at desc);",
      "",
      "create table if not exists website_builder_landing_pages (",
      "  id uuid primary key default gen_random_uuid(),",
      "  owner_id uuid references users(id) on delete set null,",
      "  website_id uuid references website_builder_sites(id) on delete set null,",
      "  slug text not null default 'page',",
      "  brand_name text not null default '',",
      "  headline text not null default '',",
      "  subheadline text not null default '',",
      "  cta_label text not null default 'Get Started',",
      "  price_line text not null default '',",
      "  features jsonb not null default '[]'::jsonb,",
      "  published boolean not null default false,",
      "  created_at timestamptz not null default now()",
      ");",
      "create index if not exists website_builder_landing_pages_owner_idx on website_builder_landing_pages (owner_id);",
      "create index if not exists website_builder_landing_pages_website_idx on website_builder_landing_pages (website_id);"
    ].join("\n"),
  seedSql: () =>
    [
      "",
      "insert into website_builder_sites (site_name, site_url, domain_name, domain_choice, admin_email, status, storage_used_mb, bandwidth_used_gb, monthly_visitors, divi_enabled, ai_designer_used, domain_cost, auto_renew, registration_date, expiration_date, deployment_date) values",
      "  ('Bright Studio', 'https://brightstudio.example.com', 'brightstudio.com', 'custom', 'hello@brightstudio.com', 'active', 512, 3.2, 1840, true, true, 10.93, true, now(), now() + interval '1 year', now())",
      "on conflict do nothing;",
      "",
      "insert into website_builder_landing_pages (slug, brand_name, headline, subheadline, cta_label, price_line, features, published) values",
      "  ('bright-studio', 'Bright Studio', 'Design that moves people', 'Everything you need to launch and grow your brand online — fast.', 'Get Started Today', '$5/month + domain costs', '[\"Everything you need to launch\",\"Professional email included\",\"Premium themes & builder\",\"AI-powered designer\",\"Fast, reliable hosting\",\"Domain registration at cost\",\"SSL certificates included\",\"Daily backups\",\"Expert support\",\"No setup fees\"]'::jsonb, true)",
      "on conflict do nothing;"
    ].join("\n"),
  envLines: () => [
    "",
    "# Website Builder — set to false to switch the site wizard + landing builder off.",
    "FEATURE_WEBSITE=true",
    "# Optional: a domain registrar API key enables live availability checks.",
    "# Without it, availability falls back to a local heuristic (never blocks the UI).",
    "DOMAIN_REGISTRAR_API_KEY="
  ],
  homeLinks: () => ['        <a className="button" href="/website">Website Builder</a>'],
  navLinks: () => [{ href: "/website", label: "Websites" }],
  requiredEnv: []
};